### ISSUE TITLE
Facebook 로그인

### ISSUE THREAD

**Issue by ingari** [JJoriping/KKuTu#100]
이슈 #12 를 참고하여 `Server/lib/Web/public/js/` 경로에 `facebook.js` 에 API 키까지 넣어서 저장했으나 페이스북 로그인을 누르면 Please wait.. (2) 가 뜹니다.

**Comment by JJoriping** [comment]
안녕하세요. 해당 문구는 페이스북 API를 올바르게 불러오지 못하는 등의 문제로 발생했을 가능성이 큽니다.
 개발자 도구(`F12` 키로 열 수 있습니다.)의 Console 탭에서 페이스북 관련 오류가 있는지 확인해 보세요. 인터넷 연결 상태가 원인이 될 수 있으며, 구현 특성 상 해당 문구를 완전히 없앨 수는 없는 점 양해 바랍니다.

**Comment by ingari** [comment]
답변 감사합니다.
Please wait.. (2) 가 뜨는 오류는 사라져서 로그인은 됩니다만 로그아웃이 되지 않습니다.

**Comment by CHEEY-BORIN** [comment]
아직도 버그가 진행되고 있나요? 버그가 고쳐졌다면 이슈 닫아주세요.
