### ISSUE TITLE
/gwaill 관리자 페이지 불러오기 오류

### ISSUE THREAD

**Issue by GloriaAin** [JJoriping/KKuTu#1001]
global.json에 ADMIN 값에도 저의 식별 고유번호도 적고
관리자 페이지 접속도 시도해봤는데, Cannot GET /gwaill라는 오류가 뜨더군요.
오류 해결 방법이나 관련 이슈가 있을까요?

**Comment by lshqqytiger** [comment]
[참고](https://github.com/JJoriping/KKuTu/blob/fadc0f1699e31252a216463be5bd7bda01cf1c06/Server/lib/Web/routes/admin.js#L27)
