### ISSUE TITLE
moremi/body.png 질문

### ISSUE THREAD

**Issue by GloriaAin** [JJoriping/KKuTu#1005]
![dfsdsffds](https://user-images.githubusercontent.com/80574663/165506395-074472c8-6a6e-44c8-80c8-5b6e9180fac2.PNG)
moremi/body.png 부분을 .gif 파일로 변환 시키려고 하는데,
body.png를 .gif 파일로 변경하고, 수정 할 파일은 어디인지 궁금합니다.

**Comment by lshqqytiger** [comment]
아이템 속성(json)에 `"gif": true`를 추가하시면 됩니다.

**Comment by GloriaAin** [comment]
![asdfdafsdf](https://user-images.githubusercontent.com/80574663/165508207-52b9b3c1-3b5f-4887-8d36-7bf51722afcf.PNG)
이런식으로 모레미 자체의 색깔을 .gif로 변환하고 싶습니다.
그러면 아이템 속성에서 무엇을 검색해야 하나요?

**Comment by lshqqytiger** [comment]
모레미 색과 관련된 속성은 없습니다.
직접 구현하셔야 합니다.

**Comment by GloriaAin** [comment]
알겠습니다. 이슈 닫도록 하겠습니다.
