### ISSUE TITLE
아이템 삭제 질문

### ISSUE THREAD

**Issue by GloriaAin** [JJoriping/KKuTu#1006]
![dafs](https://user-images.githubusercontent.com/80574663/165512805-6736bc3e-7291-4973-8893-a3934940cf3b.PNG)
상점에서 아이템을 추가 해야 되는데, group 부분을 적지 않아서
상점 아이템들이 전부 
![asdfdasf](https://user-images.githubusercontent.com/80574663/165512895-dfa42a1d-16bd-46b6-8bde-6f3082736204.PNG)
저렇게 날아가버렸습니다.
pgAdmin으로 아이템을 삭제하려고 하는데, 삭제하는 방법을 자세히 모르겠는데,
관련 자료나 방법이 있을까요?

**Comment by lshqqytiger** [comment]
group 부분을 적지 않아도 다른 아이템에는 영향을 주지 않습니다.
상점이 제대로 로드되지 않는 현상은 #925 에서 해결되었습니다.
