### ISSUE TITLE
게임 서버 run bat 가열리지않음(튕김현상)

### ISSUE THREAD

**Issue by dalnala** [JJoriping/KKuTu#1007]
안녕하세요 끄투가 고장나서 다시설치해서 다시열려는 사람입니다.
다시설치했는데 run.bat가 계속 꺼지네요? 이거 어케 고치죠?

**Comment by kmsimproject** [comment]
server-setup 배치파일을 실행하셨나요? 혹은 node.js가 깔려 있으신가요?

**Comment by GloriaAin** [comment]
server-setup.bat 파일을 실행하신 후에 run.bat을 실행하셔야 합니다.

**Comment by lshqqytiger** [comment]
`server-flush.bat` 실행 후 `server-setup.bat` 실행 후 다시 시도해보세요.
그래도 같은 증상이 반복된다면 Node.js나 npm이 설치되어 있지 않거나 Node.js나 npm에 문제가 발생한 것일 수 있습니다.

**Comment by dalnala** [comment]
일단 섭ㅓ 스타트 bat는 실행했고 node.js 도 설치되있습니다. 서버 flus인가뭔가도 누르고 다시했는데......안대고

**Comment by lshqqytiger** [comment]
cmd 또는 PowerShell로 run.bat을 실행시켜서 stdout 값을 봐야 정확한 원인 파악이 될 것 같습니다.

**Comment by dalnala** [comment]
그러면 파워셸 명령어 알려주세요

**Comment by lshqqytiger** [comment]
```ps
.\run.bat
```

**Comment by dalnala** [comment]
그러면 일단 cmd 로 실행해보겠습니다

**Comment by dalnala** [comment]
파일에다가 cmd추가해서하는거예요 아님 그냥 cmd에서 하는거예요?

**Comment by kmsimproject** [comment]
cd로 **자신의 끄투서버 폴더**로 이동해서 하면 됩니다.

**Comment by dalnala** [comment]
네

**Comment by dalnala** [comment]
한번내일해보겠습니다

**Comment by lshqqytiger** [comment]
![화면 캡처 2022-04-30 160402](https://user-images.githubusercontent.com/39524005/166095676-35ff09de-291a-46ff-8023-66bc8770e62f.png)

**Comment by dalnala** [comment]
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ITCODY\AppData\Roaming\npm-cache\_logs\2022-05-05T02_34_34_128Z-debug.log
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>

**Comment by dalnala** [comment]
가 나옴요

**Comment by lshqqytiger** [comment]
package.json이 `C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server` 경로에 존재하나요?

**Comment by dalnala** [comment]
package.json파일 존재합니다.

**Comment by dalnala** [comment]
그런데


Microsoft Windows [Version 10.0.19044.1645]
(c) Microsoft Corporation. All rights reserved.

C:\Users\ITCODY>cd C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>./run.bat
'.'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ITCODY\AppData\Roaming\npm-cache\_logs\2022-05-05T02_38_06_975Z-debug.log

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ITCODY\AppData\Roaming\npm-cache\_logs\2022-05-05T02_39_20_453Z-debug.log

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
이 cmd에 나옵니다.

**Comment by lshqqytiger** [comment]
#1012

**Comment by dalnala** [comment]
:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/node_modules"
지정된 파일을 찾을 수 없습니다. 이  뜨는데 server-flush.bat 실행하면

**Comment by lshqqytiger** [comment]
무시해도 되는 오류입니다.

**Comment by dalnala** [comment]
네

**Comment by dalnala** [comment]
또또또또ㄸ또또또또또또또또 안열려 했는데 플러시 하고 setup 했ㄴㅡㄴ데도 또또또또 안열려!!!!!!!!!!!!!!

**Comment by ggoguma** [comment]
이슈에서 채팅은 자제해주시기 바랍니다.

**Comment by lshqqytiger** [comment]
![화면 캡처 2022-05-05 120540](https://user-images.githubusercontent.com/39524005/166858154-0276c955-562a-4ec2-bf10-604dc6709851.png)
![화면 캡처 2022-05-05 120525](https://user-images.githubusercontent.com/39524005/166858160-38244461-097d-48c9-bcf5-3a657f742c7d.png)
#1012 적용 후 순서대로 잘 따라하셨다면 문제 없이 잘 됩니다.

**Comment by dalnala** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

새로운 크로스 플랫폼 PowerShell 사용 https://aka.ms/pscore6

PS C:\Users\ITCODY> cd C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> ./server-flush.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>del "Server\run.bat"

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>del "Server\lib\Web\lib\in_game_kkutu.js"

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/node_modules"
지정된 파일을 찾을 수 없습니다.

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/lib/node_modules"

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/lib/etc"
지정된 파일을 찾을 수 없습니다.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> ./server-setup.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>cd ./Server

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>node setup
Please wait... This may take several minutes.
npm install
up to date in 0.41s

found 0 vulnerabilities


npm install ./lib --prefix "./lib"
Completed.

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>cd ./lib

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib>echo npm start  1>../run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib>grunt default pack
Running "concat:basic" (concat) task

Running "uglify:build" (uglify) task
>> 7 files created 174.3 kB → 121.79 kB

Running "pack" task

Done.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> cd ./Server
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> node setup
Please wait... This may take several minutes.
npm install
up to date in 0.363s

found 0 vulnerabilities


npm install ./lib --prefix "./lib"
Completed.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> cd ./lib
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib> echo npm start
npm
start
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib> cd C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> cd Server
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> .\run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>npm start
npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ITCODY\AppData\Roaming\npm-cache\_logs\2022-05-05T08_01_57_811Z-debug.log
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>

**Comment by dalnala** [comment]
![아 끄투 망!해!라!](https://user-images.githubusercontent.com/83485008/166884121-38c91fb5-52b8-4069-9b23-8a79d921ee79.jpg)

**Comment by dalnala** [comment]
어.라? 안되내 다른 방법 없을까요

**Comment by dalnala** [comment]
아니면..... 혹시 관리자 power shell?

**Comment by dalnala** [comment]
도 아ㄴ되네

**Comment by lshqqytiger** [comment]
#1012 변경 사항 적용을 안하신 것 같습니다.

**Comment by dalnala** [comment]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

새로운 크로스 플랫폼 PowerShell 사용 https://aka.ms/pscore6

PS C:\Users\ITCODY> cd C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> ./server-flush.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>del "Server\run.bat"

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>del "Server\lib\Web\lib\in_game_kkutu.js"

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/node_modules"
지정된 파일을 찾을 수 없습니다.

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/lib/node_modules"

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>rmdir /S /Q "./Server/lib/etc"
지정된 파일을 찾을 수 없습니다.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> ./server-setup.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master>cd ./Server

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>node setup
Please wait... This may take several minutes.
npm install
up to date in 0.412s

found 0 vulnerabilities


npm install ./lib --prefix "./lib"
Completed.

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>cd ./lib

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib>echo npm start  1>../run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib>grunt default pack
Running "concat:basic" (concat) task

Running "uglify:build" (uglify) task
>> 7 files created 174.3 kB → 121.79 kB

Running "pack" task

Done.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> cd ./Server
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> node setup
Please wait... This may take several minutes.
npm install
up to date in 0.394s

found 0 vulnerabilities


npm install ./lib --prefix "./lib"
Completed.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> cd ./lib
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib> echo npm start  1>../run.bat
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server\lib> cd C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master> cd Server
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> ./run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>?
'?'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> run.bat
run.bat : 'run.bat' 용어가 cmdlet, 함수, 스크립트 파일 또는 실행할 수 있는 프로그램 이름으로 인식되지 않습니다. 이름이
정확한지 확인하고 경로가 포함된 경우 경로가 올바른지 검증한 다음 다시 시도하십시오.
위치 줄:1 문자:1
+ run.bat
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (run.bat:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Suggestion [3,General]: run.bat 명령이 현재 위치에 있지만 이 명령을 찾을 수 없습니다. Windows PowerShell은 기본적으로 현재 위치에서 명령을 로드하지 않습니다. 이 명령을 신뢰하는 경우 대신 ".\run.bat"을(를) 입력하십시오. 자세한 내용은 "get-help about_Command_Precedence"를 참조하십시오.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server> ./run.bat

C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>?
'?'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>
PS C:\Users\ITCODY\Desktop\KKutu-master\KKuTu-master\Server>

**Comment by dalnala** [comment]
일단 powershell 로 했는데 ./run.bat 하면 명령어가 갑자기 또 ?이 생기면서 실행이 안되여

**Comment by lshqqytiger** [comment]
`./run.bat` 대신 `npm start`는 되던가요

**Comment by dalnala** [comment]
네 안됩니다

**Comment by lshqqytiger** [comment]
**#1012 의 [File Changed](https://github.com/JJoriping/KKuTu/pull/1012/files)를 모두 적용 후** `server-flush.bat` 실행 후 `server-setup.bat` 실행 후 `npm start`를 실행 하신게 맞나요?

**Comment by dalnala** [comment]
[Server/lib/package-lock.json]은 무슨 파일을 뜻하나요?

**Comment by lshqqytiger** [comment]
끄투와 무관한 질문은 하지말아주세요. #689 [npm Docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json)

**Comment by dalnala** [comment]
적용 했는데 이젠 아예  안켜저서 이슈 닫겠습니다.
