### ISSUE TITLE
google 로그인 후 닉네임 앞에 undefined가 붙습니다

### ISSUE THREAD

**Issue by GloriaAin** [JJoriping/KKuTu#1008]
![asdfadfs](https://user-images.githubusercontent.com/80574663/166093619-eae69769-27f2-4e96-b433-bea0220240a6.PNG)
구글 로그인 구현 후, 로그인을 해보았을때 닉네임 앞에 undefined라는 별명이 붙는데요,
이는 어떻게 해결하나요?

**Comment by lshqqytiger** [comment]
#1009

**Comment by GloriaAin** [comment]
해결 되었습니다. 감사합니다 :)
