### ISSUE TITLE
구글아이디 문제와 오류

### ISSUE THREAD

**Issue by minesna** [JJoriping/KKuTu#101]
1.이슈 #97  번과 같은 오류가 발생 하였네요..

2.(C:\Users\minesna\Desktop\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:303:14)
ReplyError: ERR wrong number of arguments for 'set' command at parseError (C:\Users\minesna\Desktop\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:193:12) at parseType (C:\Users\minesna\Desktop\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:303:14)
이런 오류가 뜨네요... 빠른 시일 내에 답변 부탁드리겠습니다..

**Comment by JJoriping** [comment]
안녕하세요. 주어진 호출 스택에는 redis-parser라는 다른 모듈의 함수밖에 없어 정확히 어디서 생긴 문제인지 알 수 없습니다. 오류 내용으로만 봤을 때 Redis의 SET 명령어(https://redis.io/commands/set)에서 발생한 문제인 것으로 보입니다.

**Comment by minesna** [comment]
1번도 알려주세요 ㅠㅠ

**Comment by JJoriping** [comment]
해당 이슈에 의견을 제시해 놓았으니 확인해 주세요.
