### ISSUE TITLE
오리지널 서버와 거리 먼 이슈일 수 있는데..

### ISSUE THREAD

**Issue by GloriaAin** [JJoriping/KKuTu#1010]
레벨을 확장하면 GM 이라는 admin 전용 레벨을 만드는 법이 무엇일까요?

**Comment by lshqqytiger** [comment]
깃허브 이슈에서 다룰 내용은 아닌 것 같습니다.
관리자에게만 별도의 이미지 파일을 적용하는 방법은 여러가지가 있을 수 있습니다.
