### ISSUE TITLE
모바일에서 방 접속과 방 생성이 안되는 버그

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#1011]
![image](https://user-images.githubusercontent.com/93064596/166131679-43868e97-58c0-4bcb-95af-356fa06aeefa.png)

사진처럼 콘솔에는 오류가 이렇게 떠있고
서버에 있는 콘솔에서는 따로 오류 메시지가 없습니다

모바일에서만 그렇고 pc에서는 해당 문제가 발생하지 않는데 어떻하나요?

**Comment by lshqqytiger** [comment]
PR에 관련된 이슈인 경우 해당 PR의 Conversation 란에 남겨주시면 빠른 원인 파악 및 조치에 도움이 됩니다.
커밋 [f1140af](https://github.com/JJoriping/KKuTu/pull/871/commits/f1140af698c9440fbc1b04c13eccc15dd9336613)에서 해결되었습니다.
