### ISSUE TITLE
단어

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#1013]
여러 단어 한번에 삭제하는거 어떻게 하나요 만약 못한다면 기능을 만드려고 하는데 혹시 /gwalli 수정할수 있는 파일 어디있는지 아나요

**Comment by lshqqytiger** [comment]
gwalli.pug
in_gwalli.js
admin.js
위 파일들을 수정하시면 됩니다.

**Comment by Random-Studio** [comment]
해결하셨으면 이슈 닫아주세요.

**Comment by june2007** [comment]
이슈 닫았습니다
