### ISSUE TITLE
끄투코리아 게임관련

### ISSUE THREAD

**Issue by diwerfhe43** [JJoriping/KKuTu#1014]
플레이어수를 늘릴수없을까여?

**Comment by lshqqytiger** [comment]
무슨 목적의 이슈인지 잘 모르겠습니다.
프리서버 끄투코리아에 관한 내용이라면 깃허브 이슈에서는 각 프리서버에 대해서는 다루지 않으므로 다른 곳에 문의해주시고
(프리서버와 무관하게) 플레이어 수 제한을 건드리고 싶으신 것이라면 kkutu.js, master.js, slave.js, kkutu.pug를 수정하시면 됩니다.

**Comment by diwerfhe43** [comment]
네 개발용맞습니다 감사합니다.

**Comment by diwerfhe43** [comment]
그 죄송하지만 일단 바꿨는데 안됬는데 다시질문하기뭐하네요..
