### ISSUE TITLE
끄투 방설정문의

### ISSUE THREAD

**Issue by diwerfhe43** [JJoriping/KKuTu#1015]
끄투에서  아무말대잔치라는 설정을개발할려고하는데요 어떻게하는지알려주실수있을까요?

**Comment by lshqqytiger** [comment]
#689

**Comment by diwerfhe43** [comment]
2. 이곳은 본인이 개발하기를 원하는 기능을 어떻게 구현하는지 질문하는 곳이 아닙니다.
확인했습니다 죄송합니다.
