### ISSUE TITLE
질문합니다

### ISSUE THREAD

**Issue by silvermello** [JJoriping/KKuTu#1017]
관리페이지에서 인벤토리와 장착중인아이템을 건드리다가
모두 사라졌는데 어떻게하나
![d캡처](https://user-images.githubusercontent.com/105197076/167441489-172bcfbc-b2a9-455c-a3d4-c70d1de6334c.PNG)
요

**Comment by whskr** [comment]
> #453 존재하는 이슈 작성하기 전에 확인해주세요
453번 이슈랑은 현상이 다른 것 같은데요...
+ 스크린샷만 달랑 올리면 도움 드리기 어렵습니다. 어떤 식으로 건드리셨는지도 알려주세요

**Comment by lshqqytiger** [comment]
관리 페이지에서 box 값에 유효하지 않은(JSON으로 파싱할 수 없는) 값을 입력하신 것 같습니다.
정확히 어떤 값을 입력하셨는지에 대한 언급은 없으므로 더 자세히 답변드릴 수 없습니다.

**Comment by silvermello** [comment]
잠시컴퓨터를 재부팅하느라 늦었습니다
box에는 {"abcdefg":1,"b1_gm":1,"sqpants":1} 되있고
equip은 {"Mbadge":"b1_gm","sqpants":1} (관리페이지에 이렇게 되있었습니다 죄송합니다)

**Comment by silvermello** [comment]
해결됬네요 이슈 닫겠습니다
