### ISSUE TITLE
끄투 인증서 관련

### ISSUE THREAD

**Issue by SV-discord** [JJoriping/KKuTu#1018]
끄투 인증서를 등록했는데

internal/modules/cjs/loader.js:1174 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\1117Kkutu\Server\lib\sub\global.json: Unexpected token U in JSON at position 518 at parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\1117Kkutu\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:1137:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) at Module.load (internal/modules/cjs/loader.js:985:32)
G: CLOSED WITH CODE 1
W: CLOSED WITH CODE null
internal/modules/cjs/loader.js:1174 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\1117Kkutu\Server\lib\sub\global.json: Unexpected token U in JSON at position 518 at parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\1117Kkutu\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:1137:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) at Module.load (internal/modules/cjs/loader.js:985:32)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:1174 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\1117Kkutu\Server\lib\sub\global.json: Unexpected token U in JSON at position 518 at parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1171:22) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\1117Kkutu\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:1137:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) at Module.load (internal/modules/cjs/loader.js:985:32)
Worker 1716 died

이렇게 오류가 뜹니다 어떻게 해결하죠?

**Comment by lshqqytiger** [comment]
global.json이 JSON 문법에 맞지 않게 작성되었습니다. (518번째 'U' 부분 확인)
