### ISSUE TITLE
방 접속 불가

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#1019]
서버는 연결 되는데 방을 만들려고 하면 "방과 연결하는 중..."만 계속 뜹니다.

**Comment by lshqqytiger** [comment]
게임 서버의 방 웹소켓 포트로 접근하지 못하고 있는 것 같습니다.
localhost 또는 127.0.0.1로 접속하셨는지, PR #871 을 이용 중이신지 알려주세요.

**Comment by wd5dw** [comment]
localhost로 접속했으며 PR을 이용하고 있지 않습니다.

**Comment by lshqqytiger** [comment]
개발자도구나 서버 로그에 오류가 출력되는지 확인해보세요.
8496 포트로 게임 서버가 열려있지 않을 수 있습니다.

**Comment by lshqqytiger** [comment]
따로 소스코드 수정하신 점이 있을까요?

**Comment by 1325ok** [comment]
저도 예전에 같은 상황을 경험 했는데
WAF를 사용한다면 아래글을 참고해보세요

https://github.com/JJoriping/KKuTu/issues/1011
