### ISSUE TITLE
gwalli 사용법에 대하여

### ISSUE THREAD

**Issue by teameffooort** [JJoriping/KKuTu#102]
Oauth 기능을 사용하지 않고 gwalli를 사용하는 방법은 없을까요?

**Comment by ingari** [comment]
비로그인 상태로도 관리 페이지를 사용 가능 하다면 해킹?의 가능성이 있기 때문이기도 하고..
어쨌든 OAuth 기능을 사용하지 않고 gwalli 페이지를 사용하는 방벙은 없습니다.

**Comment by teameffooort** [comment]
루프백 아이피상태에서 Oauth 를 젓용할 수 있을까요?

**Comment by ingari** [comment]
루프백 아이디여도 상관없을 듯 합니다.
이슈 #1을 참고해주세요.

**Comment by teameffooort** [comment]
집에가서. 해보고. 해결되면 이슈 닫겟습니다

**Comment by teameffooort** [comment]
읽어 봤습니다만 Oauth가 처음이라 읽어봐도 잘 모르겠더군요. 네이버 개발자 홈페이지 가서 API 생성하고 API 키를 받아서 써 있는대로 해 봤는데도 안됩니다. 왜 이러는지 알 수 있을가요?
