### ISSUE TITLE
단어추가하면 어인정으로 추가되는데 노인정단어 추가할떄 어떻게 하죠?

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#1020]
단어추가 하고 보면 타입이 INJEONG 인데 타입이 1인 단어로 추가하려면 어떻게 해야하죠?
참고로 주제를 노인정단어로 해도 어인정 단어로 추가됩니다

**Comment by Preta-Crowz** [comment]
단어 플래그를 설정해주시면 됩니다.
![image](https://user-images.githubusercontent.com/16697820/170890930-9ca2f734-d3b5-4609-80ba-69cbe2aa0f8e.png)
