### ISSUE TITLE
디스코드 로그인 구현

### ISSUE THREAD

**Issue by Gt5588** [JJoriping/KKuTu#1023]
auth.json에 디스코드 api 넣으면 된다고 해서
디스코드에 개발자에서 뉴 애플리케이션 만들고
APPLICATION ID과 PUBLIC KEY를 auth.json에 넣고
OAuth2에 가서 주소 추가를 했는데요
![제목 없3333음](https://user-images.githubusercontent.com/104167191/170677524-99ad2363-9843-4056-a6a3-2d78bf364252.png)
사진 처럼 나옵니다.. 제가 뭘 또 건드려야하는지 모르겠습니다...
유튜브 보면 구현 강의가 있는데... 뭔가 다르더라구요.. ㅠㅠ

**Comment by whskr** [comment]
리다이렉트 URI 제대로 설정 하셨나요?
![image](https://user-images.githubusercontent.com/57280515/170678141-20186ee1-86ce-44d3-93a2-f64f4ece3a86.png)

**Comment by lshqqytiger** [comment]
Application ID와 Public Key가 뭘 뜻하는 건지 잘 모르겠습니다.
필요한 것은 Client ID와 Client Secret입니다.

**Comment by Gt5588** [comment]
> 리다이렉트 URI 제대로 설정 하셨나요? ![image](https://user-images.githubusercontent.com/57280515/170678141-20186ee1-86ce-44d3-93a2-f64f4ece3a86.png)

네 제대로 넣었습니다!
![캡1처](https://user-images.githubusercontent.com/104167191/170743379-c011af04-7f94-45ee-8391-49d44f0129da.PNG)

이렇게 넣는거 아닌가요??

**Comment by lshqqytiger** [comment]
auth.json의 discord.callbackURL 값을 수정하셨다면 원래대로 되돌려보세요.

**Comment by Gt5588** [comment]
> auth.json의 discord.callbackURL 값을 수정하셨다면 원래대로 되돌려보세요.
![캡123처](https://user-images.githubusercontent.com/104167191/170823569-da58749d-b66c-4e50-ad1e-1dbdc3d1fb0b.PNG)
사진과 같이 건든거 없습니다.
디스코드에서 뭘 건드여야 될까요??

**Comment by IAMIHAH** [comment]
ClientSecret을 공개하시면 안됩니다. 사진 삭제 하시고 Secret Reset하시기 바랍니다.
또한 auth.json의 `discord.callbackURL` 값을 `/login/discord/callback`으로 설정 하신 후, 디스코드에도 redirect_url을 `본인서버주소/login/discord/callback`으로 설정하신 뒤 서버를 재시작하세요.
이후 `본인서버주소/login/discord`로 이동하셔도 안되는 부분 있으시면 다시 올려주세요.

**Comment by lshqqytiger** [comment]
Client Secret 값이 잘못되었습니다.
Discord OAuth API의 Client Secret 값은 uuid 형태로 제공되지 않습니다.

**Comment by Gt5588** [comment]
> Client Secret 값이 잘못되었습니다. Discord OAuth API의 Client Secret 값은 hash 형태로 제공되지 않습니다. 현재 discord.clientSecret에 입력된 값은 Public Key입니다. Client Secret 값을 입력해주세요.

입력 하라는 값을 입력을 했음에도 같은 오류가 뜹니다.
api를 새로 만들어서 해야될까요?
서버 재부팅도 몇번 해봤습니다.

**Comment by Gt5588** [comment]
> > Client Secret 값이 잘못되었습니다. Discord OAuth API의 Client Secret 값은 hash 형태로 제공되지 않습니다. 현재 discord.clientSecret에 입력된 값은 Public Key입니다. Client Secret 값을 입력해주세요.
> 
> 입력 하라는 값을 입력을 했음에도 같은 오류가 뜹니다. api를 새로 만들어서 해야될까요? 서버 재부팅도 몇번 해봤습니다.

서버 문제였는지 몇십번 재부팅 해보니 갑자기 잘 작동 합니다! ㅠㅠ 이슈 닫겠습니다 감사합니다.
