### ISSUE TITLE
숫자 단어 추가(+ 달달소 등재)

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#1026]
숫자 단어를 추가하면 추가는 되지만 사전에는 검색해도 안나옵니다. 어떻게 고치죠?

+달달소에 현재 제 끄투서버를 검수요청 했지만 계속 서버를 키고 있음에도 불구하고 #검수요청 중 입니다. 어떡하죠?

**Comment by IAMIHAH** [comment]
1. 끄투에서 맨 앞 글자와 마지막 글자에 숫자를 넣게 되는 일은 드뭅니다. 맨 앞과 마지막 글자의 숫자는 한국어로 변환하는 것을 추천드립니다.
해결 방법은 다른 분들이 알려주실 수 있을 것 같네요.
2. 검수 요청은 이 곳에서 바라시면 안됩니다. 원래는 1~2일 기준으로 승인이 되었는데, 최근 신청을 넣은 결과 대략 보름 정도는 걸리는 것 같습니다.

**Comment by lshqqytiger** [comment]
숫자만 있는 단어를 ko 테이블에 추가하신 후 사전에 검색할 경우 tryDict에서 en 테이블에서 검색하도록 GET 요청을 보냅니다.
숫자-숫자 잇기를 허용하고 싶으신 거라면 tryDict에서 테이블을 판정하지 않도록 하시고 GET /dict 라우터에서 ko와 en 테이블에서 각각 한번씩 검색하도록 수정하세요.

**Comment by june2007** [comment]
감사합니다 이슈 닫겠습니다
