### ISSUE TITLE
gwalli 단어db 기능이 맛갔습니다

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#1028]
끄투 단어 DB 다루기 있잖아요
거기서 단어 조회,추가 가 안됩니다. 아마도 gwalli.pug 를 좀 만졌는데 그거 잘못해서 오류가 일난것 같네요.

legend 끄투 DB 다루기
		div
			input#db-word(placeholder='단어')
			button#db-go 조회
			div#word-data
				div#wd-id
				input#wd-flag
				table
					thead: tr
						td #
						td type
						td theme
						td mean
						td 행동
					tbody#wd-data
			div#word-flag
			div#word-hit
			button#word-add 추가
			button#db-apply 적용
	fieldset
		legend 끄투 DB에 단어 추가하기
		div
			input#db-theme(placeholder='주제 (~부터 적으면 검색)')
			textarea#db-list(rows=20, cols=100)
			button#db-ok 확인
	fieldset

저게 코드입니다.

**Comment by whskr** [comment]
어떤 의도로 이슈를 생성한 건지 잘 모르겠습니다.
끄투 서버 자체의 문제점은 아닌 것 같습니다. #689 
어떤 식으로 어떤 내용의 오류가 발생하는지 자세히 알려주세요.
