### ISSUE TITLE
질문 두개만 드리겠습니다 ㅠㅠ

### ISSUE THREAD

**Issue by yytk123456** [JJoriping/KKuTu#103]
gwalli를 admin 퍼미션이 있는 사람만 접속 가능하게 해주는 구문은 어느쪽인가요?

루프백 아이피로 하면 Oauth 적용때문에  하나도 쓸수가 없어서요..
루프백 아이피 상태에서도 Oauth 적용을 하는 방법을 알려주셔도 완전 감사할거 
같습니다
이벤트격으로 학교에서 진행하는데 미리 추가를 해놓는게 좋을거 같아서요. (서버 지원이 좀 늦게 됩니다 ㅠㅠ)

--

db.sql 자체를 수정해서 추가를 하지는 못할까요?
한번 해봤더니 인식을 못하더라구요..

**Comment by JJoriping** [comment]
주제가 다른 질문은 다른 분들이 찾아 보기가 쉽도록 가급적 별도의 이슈로 등록하는 것을 권합니다.

* `./gwalli`로 접근 가능한 세션을 확인하기 위해서 파일 `./Server/lib/Web/routes/admin.js`의 `checkAdmin` 함수를 호출하니 이 쪽의 소스 코드를 확인해 보세요. 또한 OAuth를 로컬에서 하는 방법은 해당 OAuth 서비스 제공 업체 쪽의 지원이 있어야만 가능하며 끄투에서 기본적으로 제공하는 세 업체에서는 제공하지 않는 것으로 알고 있습니다.

* 파일 `./db.sql`은 별도의 압축이나 이진화 등이 없는 일반 텍스트 파일이지만 그 내용이 매우 많으므로 일반적인 텍스트 편집기로는 수정하기 힘듭니다. 이러한 파일을 전문적으로 다루는 프로그램을 별도로 이용해 보세요.

**Comment by yytk123456** [comment]
C도 전문적으로 안배워서 뭐라 써있는지 잘 모르겠네요. 노가다로 뛰는게 제일 좋을거 같아요

저는 db.sql 을 visual studio code 로 수정하고 있는데 적용이 되지 않습니다. db.sql 파일을 따로 postgreSQL데이터베이스에 재 업로드 해야 되는 건가요?

**Comment by JJoriping** [comment]
네. 파일 `./db.sql`은 그 자체가 데이터베이스가 아니라 기존 끄투 데이터베이스의 내용을 기록해 둔
 파일이기 때문에 이 파일을 수정해도 데이터베이스에 바로 영향을 주지는 않습니다. 지속적인 수정 및 관리를 위해서는 PostgreSQL 관련 GUI 툴(pgAdmin)을 이용하길 권장합니다.
