### ISSUE TITLE
JS 파일 정렬

### ISSUE THREAD

**Issue by kimchamchi** [JJoriping/KKuTu#1030]
in_game_kkutu.min.js에 칭호를 추가할려고 접속을 했는데 이런식으로 나옵니다 
이걸 좀 알아볼수 있게 정렬을 못하나요
![image](https://user-images.githubusercontent.com/94619639/177774346-4cbe668f-2a55-4957-8ba6-dcb06f9bf3f3.png)

**Comment by IAMIHAH** [comment]
`*.min.js` 파일들은 직접 수정하는 것이 아닙니다.

`Server/lib/Web/lib/kkutu/*.js` 파일을 수정 후 grunt를 돌려주셔야 합니다.

**Comment by lshqqytiger** [comment]
#136

**Comment by kimchamchi** [comment]
해결
