### ISSUE TITLE
pgadmin 만지다가 단어 날라갔습니다

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#1032]
pgadmin 에서 명령어 만지다가 단어db를 다 날려버렸습니다 혹시 단어 db를 다운받고 적용시킬수 있을 수 있나요?
pgadmin에서 db백업 같은건 안해놨습니다. 어떡하죠
아니면 명령어를 취소 하는 방법은 없을까요?

**Comment by lshqqytiger** [comment]
일반적으로는 백업 없이 진행한 쿼리를 취소하거나 이전으로 되돌리는 것은 불가능합니다.
초기 DB 상태로 되돌리시려면 main DB를 drop하신 후 레포지토리 최상위 경로의 db.sql 파일로 DB 최초 구축 시와 동일하게 작업해주시면 됩니다.

**Comment by june2007** [comment]
감사합니다 복구 하였습니다.
