### ISSUE TITLE
server-setup.bat 실행불가

### ISSUE THREAD

**Issue by chomi220112** [JJoriping/KKuTu#1034]
키면 바로 꺼지는데 cmd로 확인한 문자는

[C:\Users\USER\Desktop\KKuTu>server-setup.bat

C:\Users\USER\Desktop\KKuTu>cd ./Server

C:\Users\USER\Desktop\KKuTu\Server>node setup

C:\Users\USER\Desktop\KKuTu\Server\setup.js:22
let step = [
    ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

C:\Users\USER\Desktop\KKuTu\Server>cd ./lib

C:\Users\USER\Desktop\KKuTu\Server\lib>echo npm start  1>../run.bat

C:\Users\USER\Desktop\KKuTu\Server\lib>grunt default pack

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Users\USER\Desktop\KKuTu\Server\lib\node_modules\grunt\bin\grunt'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

C:\Users\USER\Desktop\KKuTu\Server\lib>]

 Run.bat만 생성되고 npm 설치시키니까 에러뜨네요. 혹시 도와주실수 있나요?

**Comment by Carlo-Woo** [comment]
1. 님이랑 비슷한 사람들이 이런 이슈 계속 올려서 사람들이 #689 를 몇 번이나 외쳤지만 한 번 더 알려드립니다. **끄투 레포지토리 이슈 기능은 `끄투 내부 코드` 상의 문제를 제보하라고 만든 거지, 기능 안 돌아간다고 도와달라 하는 게시판이라든가 고객센터 같은 목적은 없습니다.**
2. 끄투를 운영하려면 기본적인 코딩 실력은 당연히 요구되는 사항입니다. 정 모르겠으면 다른 프리서버를 즐기든가, 외주를 두든가, 코딩 실력을 지금이라도 키우든가 하세요.
3. npm은 해당 명령어 입력 **전**에 해야 하는 것으로 알고 있습니다.

**Comment by lshqqytiger** [comment]
#689 에 저촉되는 내용은 아닌 것 같습니다.
설치된 grunt와 Node.js 버전이 어떻게 되시나요?

**Comment by chomi220112** [comment]
10.37(0.10.37)버전입니다.
그리고 끄투 내부 코드 맞습니다...저 아무것도 안 건드렸습니다.

**Comment by chomi220112** [comment]
그리고 저 예전에 #689 5번은 본거같습니다

**Comment by lshqqytiger** [comment]
ES6 문법(`let` 포함)은 Node.js 6.0.0부터 지원합니다.

**Comment by chomi220112** [comment]
네 감사합니다
