### ISSUE TITLE
끄투 서버에서 어드민 설정 어떻게 하나요?

### ISSUE THREAD

**Issue by seojin111** [JJoriping/KKuTu#1035]
어드민 설정해서 이름이 어드면,운영자 이렇게 나오는거 어떻게 하나요?

**Comment by lshqqytiger** [comment]
#23

**Comment by seojin111** [comment]
#kill 880049926887841792 채팅창에 하라는데 어디 채팅창 말아는거죠?

**Comment by seojin111** [comment]
그리고 /id 치면 discord-880049926887841792 이렇게 나오는데 앞에 있는 디스코드 표스도 해야되나요?

**Comment by seojin111** [comment]
UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '사용자 고유 ID'; 그리고 이거  어디에 집어넣어야 하나요?

**Comment by whskr** [comment]
1. #689 
끄투 서버 자체의 문제점이 아닙니다. 비슷한 내용의 이슈가 존재합니다.
2. 관리자 권한은 `Server/lib/sub/global.json`에서 "ADMIN": [ "id" ] 식으로 줄 수 있습니다.
(/id를 쳐서 나온 값을 복사해서 넣으시면 됩니다. 디스코드로 로그인했다면 discord- 부분도 같이...)
관리자 권한을 줬다면 서버를 재시작해 주세요.
3. GM 휘장은 관리 페이지 (/gwalli)를 통해 유저에게 장착 또는 인벤토리에 줄 수 있습니다.

**Comment by lshqqytiger** [comment]
1. #23 의 Comment 내용을 그대로 따라하시라는 말이 아니고 참고하시라는 뜻이었습니다.
2. 그런 질문 하실 것을 예상하고 (또한 이미 그런 질문이 여러 이슈에서 나왔던 바 있기에) 이미 Wiki의 [S~global.json](https://github.com/JJoriping/KKuTu/wiki/S~global.json) 페이지에 예시까지 전부 적어두었습니다.
3. `main` DB를 대상으로 실행해야하는 SQL 구문입니다. PSQL Shell에서 `main` DB를 타겟으로 실행하시거나 pgAdmin 등의 기타 데이터베이스 관리 도구를 통해 실행하시거나 관리 페이지의 `유저 DB 관리하기` 메뉴를 통해 `box` 컬럼을 수정하시면 됩니다. #221
