### ISSUE TITLE
/gwalli 여기서 테이블이 뭔가요?

### ISSUE THREAD

**Issue by seojin111** [JJoriping/KKuTu#1036]
테이블에 뭐를 넣어야 되는지 모르겠습니다
그리고 암호에서 global.json 여기서 설정한 암호를 /gwalli 관리자 사이트에 했는데 
아무일도 일어나지 않습니다 도와주세요
추가질분:단어 어떻게 추가하는건지 모르겠습니다 ..

**Comment by lshqqytiger** [comment]
Duplicate of #359 #586

**Comment by june2007** [comment]
테이블에는 한국어 단어를 추가할꺼면 ko, 영어 단어를 추가 할거면 en을 적고 하면 됩니다.
그리고 단어 추가는 끄투 DB에 단어 추가하기 저거 아래 칸(2개 칸 중에서 큰 칸)에 추가할 단어 적으시고 작은 칸에 주제코드 적으시면 됩니다.(만약 주제코드에 POK를 적으면 <포켓몬스터>주제로 추가 됌) 그리고 아래 확인 버튼을 누르시면 OK 라고 뜨는데 파란색 확인 버튼 누르시고 사전에 검색하면 나올것 입니다.
