### ISSUE TITLE
d-link 와이파이로 포드포워딩 하는법 알는사람

### ISSUE THREAD

**Issue by seojin111** [JJoriping/KKuTu#1037]
d-link 와이파이로 포드포워딩 하는법을 잘모르겠습니다

**Comment by lshqqytiger** [comment]
D-Link 공유기의 경우 공유기 모델마다 WebCM 인터페이스에 차이가 많이 나므로 직접 찾아보셔야 합니다.
이 곳은 끄투 자체의 문제점을 다루는 곳이지 포트포워딩 하는 방법에 대해 묻는 곳이 아닙니다. #689

**Comment by kdhkr** [comment]
#689 
Please refer: https://eu.dlink.com/uk/en/support/faq/routers/mydlink-routers/dir-810l/how-do-i-configure-port-forwarding-on-my-router
