### ISSUE TITLE
끄투 서버를 열었는데 에러가 뜹니다

### ISSUE THREAD

**Issue by chanhui13** [JJoriping/KKuTu#1038]
끄투서버를 열었거든요 근데  **서버**가 안열어요

에러:
node:internal/modules/cjs/loader:936 throw err; ^ Error: Cannot find module './sub/global.json' Require stack: - C:\Users\[x]\Desktop\kkutu-master\Server\lib\const.js - C:\Users\[x]\Desktop\kkutu-master\Server\lib\Game\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15) at Function.Module._load (node:internal/modules/cjs/loader:778:27) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.&lt;anonymous> (C:\Users\[x]\Desktop\kkutu-master\Server\lib\const.js:19:14) at Module._compile (node:internal/modules/cjs/loader:1105:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'C:\\Users\\[x]\\Desktop\\kkutu-master\\Server\\lib\\const.js', 'C:\\Users\\[x]\\Desktop\\kkutu-master\\Server\\lib\\Game\\cluster.js' ] }
G: CLOSED WITH CODE 1
2번째 에러:
node:internal/modules/cjs/loader:936 throw err; ^ Error: Cannot find module '../sub/global.json' Require stack: - C:\Users\[x]\Desktop\kkutu-master\Server\lib\Web\db.js - C:\Users\[x]\Desktop\kkutu-master\Server\lib\Web\main.js - C:\Users\[x]\Desktop\kkutu-master\Server\lib\Web\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15) at Function.Module._load (node:internal/modules/cjs/loader:778:27) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object.&lt;anonymous> (C:\Users\[x]\Desktop\kkutu-master\Server\lib\Web\db.js:22:15) at Module._compile (node:internal/modules/cjs/loader:1105:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'C:\\Users\\[x]\\Desktop\\kkutu-master\\Server\\lib\\Web\\db.js', 'C:\\Users\\[x]\\Desktop\\kkutu-master\\Server\\lib\\Web\\main.js', 'C:\\Users\\[x]\\Desktop\\kkutu-master\\Server\\lib\\Web\\cluster.js' ] }
Worker 2808 died
W: CLOSED WITH CODE 0

**Comment by lshqqytiger** [comment]
[README.md#공통](https://github.com/JJoriping/KKuTu#%EA%B3%B5%ED%86%B5)
