### ISSUE TITLE
로그인(OAuth) 관련 질문

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#104]
안녕하세요, 새로 서버를 열려하는 새내기 입니다.
이번에 네이버 로그인을 먼저 구현해 친구들과 테스트를 해보려 하는데,
친구들이 로그인을 하게 하면, 제가 루프백 아이피라 로그인 안되고(localhost, 127.0.0.1 도 안됩니다. 도메인만 되더군요..;)

그러면, 루프백 아이피가 아닌 제 아이피로 oauth 인증 방법이 궁금합니다..!

**Comment by JJoriping** [comment]
이슈 #103 쪽을 참고해 보세요. 안타깝지만 끄투 쪽에서 쉽게 해결할 수 있는 방법이 아닙니다.
