### ISSUE TITLE
외부에서 방 만들기 불가와 방 입장 불가

### ISSUE THREAD

**Issue by suhoyun** [JJoriping/KKuTu#1044]
방 입장 시도 또는 방 만들기 시도시 방과 연결하는 중에서 멈추고 개발자 도구 콘솔에서는websocket is closed before the connection is established와 연결 중 문제가 발생했습니다! 라고 출력됩니다

**Comment by lshqqytiger** [comment]
따로 소스코드 수정하신 부분이 있을까요?

**Comment by suhoyun** [comment]
> 따로 소스코드 수정하신 부분이 있을까요?

auth.json,ko_kr.json ,setting.json,global.json 외에 수정하지 않았습니다

**Comment by lshqqytiger** [comment]
가장 최근 tree에서 다운로드 후 구축하신게 맞나요?

**Comment by suhoyun** [comment]
> 가장 최근 tree에서 다운로드 후 구축하신게 맞나요?
가장 최근 tree에서 다운로드 하였습니다

**Comment by chuhyeonjin** [comment]
외부에서 방 만들기가 불가하시다는건 망 내부에서는 방 만들기와 입장이 가능하신건가요?

**Comment by lshqqytiger** [comment]
포트 개방이 안되어 있는 것 같습니다.
지정한 방 웹 소켓 포트(기본값 8496)에 대한 접근을 허용한 후 다시 시도해보세요.

**Comment by suhoyun** [comment]
> 외부에서 방 만들기가 불가하시다는건 망 내부에서는 방 만들기와 입장이 가능하신건가요?

네 내부망에서는 가능합니다

**Comment by suhoyun** [comment]
> > 외부에서 방 만들기가 불가하시다는건 망 내부에서는 방 만들기와 입장이 가능하신건가요?
> 
> 네 내부망에서는 가능합니다

ㄱ

> 포트 개방이 안되어 있는 것 같습니다. 지정한 방 웹 소켓 포트(기본값 8496)에 대한 접근을 허용한 후 다시 시도해보세요.

해결하였습니다 감사합니다

**Comment by lshqqytiger** [comment]
Duplicate of #983
