### ISSUE TITLE
메인로비 화면이 분리되는 오류

### ISSUE THREAD

**Issue by B0X0B** [JJoriping/KKuTu#1045]
![322](https://user-images.githubusercontent.com/73378483/191783367-4d282ce2-ac45-4530-8ade-c5bfcb9fb75e.PNG)
![캡처](https://user-images.githubusercontent.com/73378483/191783373-248bcf10-a83c-4002-a523-72de5acff8b3.PNG)
![캡처2](https://user-images.githubusercontent.com/73378483/191783376-dba418fb-da1f-4b88-b177-353a67ebec45.PNG)
처음에는 분리가 되어있다가 몇초 지나면 원래대로 돌아오긴 합니다.
하지만 오끄감이 플레이를 해도 NaN 값이 뜨고, 모바일에서 접속했을때도
저 화면과 똑같이 나왔습니다.

풀 리퀘스트 중에 닉네임 변경 리퀘가 있어서 그걸 참고하면서 썼습니다.
해결 방안이 없으면 이슈 닫겠습니다.

**Comment by lshqqytiger** [comment]
적어주신 내용으론 정확한 증상 파악이 어렵네요.
#584 와 비슷한 내용으로 보이는데 녹화본이 있으면 증상 파악에 도움이 될 것 같습니다.

**Comment by B0X0B** [comment]
https://youtube.com/watch?v=pPtVWXFTdjk&feature=share&si=EMSIkaIECMiOmarE6JChQQ
깃허브 영상길이 제한때문에 유튜브로 올립니다

**Comment by lshqqytiger** [comment]
프론트엔드에서 오류가 발생했을 때 저렇게 됩니다.
개발자도구 로그를 확인해보세요.

**Comment by Preta-Crowz** [comment]
CSS 및 레이아웃이 로딩이 제대로 안된것 같습니다.

**Comment by B0X0B** [comment]
해결
