### ISSUE TITLE
github는 어떻게 끄투섭에서 로그인 되게 할 수 있나요?

### ISSUE THREAD

**Issue by kogunggom111** [JJoriping/KKuTu#1046]
네 지금 이슈를 받는 이 사이트, github는 어떻게 끄투섭에서 로그인 되게 할수 있을까요?
혹시몰라 다른이슈도 찾아봤는데 다 다른 곳만 알려주시고 저는 github 먼저 하게 하고 싶어서 그러는데
혹시 어떻게 해야 github 로그인 되게 할 수 있을까요?

**Comment by kdhkr** [comment]
#589
