### ISSUE TITLE
로그인 버튼이 안보입니다

### ISSUE THREAD

**Issue by krsamue101** [JJoriping/KKuTu#1049]
네이버 auth를  추가하려 하는데 네이버 로그인 버튼이 보이질 않네요..ㅠ auth.json에 클라이언트 아이디와 시크릿도 넣었는데 보이질 않아요. 그래서 https://github.com/JJoriping/KKuTu/issues/309

이 이슈처럼 네이버 auth파일을 제외한 js 모두 이름을 바꿔도 안나오네요..

**Comment by Preta-Crowz** [comment]
oauth js파일이 있는 폴더 스크린샷 올려주실 수 있으신가요?

**Comment by krsamue101** [comment]
Server/lib/Web/auth 여기요

**Comment by Preta-Crowz** [comment]
> Server/lib/Web/auth 여기요

..스크린샷이요

**Comment by krsamue101** [comment]
![Uploading 20221105_221333.jpg…]()

**Comment by Preta-Crowz** [comment]
> ![Uploading 20221105_221333.jpg…]()
> 

업로드 다 된 뒤에 올려주셔야 보입니다. 먼저 저장하시면 업로드 중 문구 그대로 올라옵니다.

**Comment by krsamue101** [comment]
![20221105_221333](https://user-images.githubusercontent.com/105032235/200122044-102672d1-417e-4677-a87c-163c7d2690ac.jpg)

**Comment by krsamue101** [comment]
됐나요??

**Comment by Preta-Crowz** [comment]
..폴더 안을 찍어주세요

**Comment by krsamue101** [comment]
![20221105_222905](https://user-images.githubusercontent.com/105032235/200122313-ccc32c75-ef3d-4d75-b7c7-329fb61ca683.jpg)

**Comment by Preta-Crowz** [comment]
설정이 되지 않은 js파일은 모두 확장자를 바꿔 인식되지 않게 해주세요. (언급하신 이슈 하단에도 언급된 내용입니다.)
