### ISSUE TITLE
GM 휘장을 장착하였을때 닉네임 앞에 출력되는 [GM] 칭호는 어느쪽을 바꿔줘야 수정할 수 있나요?

### ISSUE THREAD

**Issue by ment12da** [JJoriping/KKuTu#105]
제목 그대로 입니다. GM 휘장을 장착하였을때 닉네임 앞에 출력되는 [GM]칭호는 어디를 수정해줘야 바꿀 수 있는지 궁금합니다.

**Comment by Ganggroid** [comment]
in_game_kkutu_shop.css

**Comment by ment12da** [comment]
.x-gm .users-name::before{ content: "[GM]"; color: #2F77D9; text-shadow: 0px 0px 2px #2AF; }
.chat-item>.x-gm::before{ content: "[GM]"; color: #2F77D9; text-shadow: 0px 0px 2px #2AF; }
.room-user-title>.x-gm::before{ content: "[GM]"; color: #2F77D9; text-shadow: 0px 0px 2px #2AF; }
이쪽인거 같은데 다른 휘장을 장착했을때도 칭호가 출력되도록 할 수 있나요?

**Comment by Ganggroid** [comment]
네
