### ISSUE TITLE
server-flush.bat 오류

### ISSUE THREAD

**Issue by Forzaluiza** [JJoriping/KKuTu#1050]
in_game_kkutu.js 에서 욕설과 레벨 제한 변경 후  server-flush.bat, server-setup.bat 를 해도 변경사항이 저장되지 않습니다. 
계속 돌아오네요 변경 전 상태로 해결 방안이 있나요??

**Comment by norhu1130** [comment]
grunt default pack을 Server/lib경로에서 해주셔야 합니다.

**Comment by Forzaluiza** [comment]
감사합니다

**Comment by kdhkr** [comment]
안녕하세요, `KKuTu` 서버의 `in_game_kkutu.js` 파일은 `./Server/lib/Web/lib/kkutu` 디렉토리에 위치한 `head.js`, `ready.js`, `body.js`의 합본입니다.

`grunt default pack`을 실행할 경우 Grunt가 `head.js`, `ready.js`, `body.js` 파일의 내용을 합쳐 `in_game_kkutu.js` (Unminified), `in_game_kkutu.min.js` (Minified)를 생성합니다.

따라서 특별한 경우가 아니라면 `in_game_kkutu.js`를 직접 편집하는 것은 추천하지 않습니다.
