### ISSUE TITLE
배경음악과 효과음을 변경하려면 어떻게 해야할까요.

### ISSUE THREAD

**Issue by Lhakmin** [JJoriping/KKuTu#1051]

**Comment by Lhakmin** [comment]
어떤 파일인지는 알겠는데 어떻게 바꾸는지 몰라요

**Comment by Preta-Crowz** [comment]
invalid issue - read : #689

**Comment by Lhakmin** [comment]
이슈 뒤져보고 와도 없어서 물어봤습니다만, 어느 파일을 어떻게 해야 끄투의 배경음 또는 효과음이 변경되는지 그걸 물어보고싶어서 이슈를 열었습니다. 어떻게 해야 끄투의 효과음과 배경음을 바꿀 수 있을까요?

**Comment by Lhakmin** [comment]
#403 이걸 봐도 파일만 알고 하는 방법을 몰라서 궁금합니다.

**Comment by Lhakmin** [comment]
알겠습니다만 진짜 궁금했습니다. 그리고 이런걸 도와줄 사람도 없었습니다.
내 끄투 서버의 문제만 올리고 이런 부적인 요소는 올리지 않겠습니다.

**Comment by Preta-Crowz** [comment]
> 끄투 서버의 정상적인 운영을 위해서는 충분한 개발 실력을 요구합니다. 부족하다고 여겨질 경우, 다른 개발자를 구하거나 외주를 맡기시기 바랍니다. 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.
