### ISSUE TITLE
외부에서 게임서버에 접속했을때 "서버와의 연결이 종료되었습니다. (#1006)"라고 뜹니다.

### ISSUE THREAD

**Issue by gustmdakdl** [JJoriping/KKuTu#1054]
내부아이피로 접속했을땐 게임서버에 접속되지만, 외부아이피로 접속할 땐 '서버와의 연결이 종료되었습니다. (#1006)"라고 뜹니다.
![화면 캡처 2022-12-17 212858](https://user-images.githubusercontent.com/120700962/208241917-6d46410f-010a-42c0-ab28-481386cf068c.png)

![화면 캡처 2022-12-17 212928](https://user-images.githubusercontent.com/120700962/208241905-5af0e889-c67f-40b3-b154-0599ef611945.png)
![화면 캡처 2022-12-17 213041](https://user-images.githubusercontent.com/120700962/208241953-f0fa8f17-0b0f-434b-a1a7-ed5c1d74a874.png)

**Comment by lshqqytiger** [comment]
게임 채널 포트(기본값 8080)가 열려 있지 않거나 방화벽에서 접속을 차단하고 있습니다.
외부에서 8080, 8496 포트로 접속할 수 있게 해주세요.

**Comment by gustmdakdl** [comment]
해결되었습니다. 감사합니다.
