### ISSUE TITLE
영단어 DB 가 통째로 날아갔는데 WordNet DB를 적용 하는 방법 없나요?

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#1055]
끄투 단어 DB가 Worldnet DB를 따른다고 해서 저 데이터베이스를 이용해서 다시 복구를 할 수는 없나요?

**Comment by kdhkr** [comment]
`db.sql`에서 `kkutu_en_*` 테이블만 import하세요.
이곳은 끄투 자체의 문제점을 기술하는 곳입니다. #689
