### ISSUE TITLE
db 를만들었 는데요 근데 이렇게 뜹니다ㅠㅠㅠ

### ISSUE THREAD

**Issue by frgrtyt** [JJoriping/KKuTu#1056]
createdb: 데이터베이스 만들기 실패: ?ㅻ쪟:  "main" ?대쫫???곗씠?곕쿋?댁뒪???대? ?덉쓬

**Comment by Preta-Crowz** [comment]
#689, #843
인코딩 문제로 깨져있지만, 오류 자체는 대부분 동일한 오류입니다. 확실하지 않다면 인코딩 설정을 변경하고 다시 시도해보세요.

**Comment by lshqqytiger** [comment]
Duplicate of #391
