### ISSUE TITLE
서버 열었는데 이렇게 뜨네요 ㅠㅠ

### ISSUE THREAD

**Issue by frgrtyt** [JJoriping/KKuTu#1057]
internal/modules/cjs/loader.js:968 throw err; ^ Error: Cannot find module './sub/global.json' Require stack: - C:\Users\nsh02\OneDrive\바탕 화면\KKuTu-master\Server\lib\const.js - C:\Users\nsh02\OneDrive\바탕 화면\KKuTu-master\Server\lib\Game\cluster.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15) at Function.Module._load (internal/modules/cjs/loader.js:841:27) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (C:\Users\nsh02\OneDrive\바탕 화면\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:1137:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'C:\\Users\\nsh02\\OneDrive\\바탕 화면\\KKuTu-master\\Server\\lib\\const.js', 'C:\\Users\\nsh02\\OneDrive\\바탕 화면\\KKuTu-master\\Server\\lib\\Game\\cluster.js' ] }
G: CLOSED WITH CODE 1
W: CLOSED WITH CODE null
오류입니다

**Comment by Preta-Crowz** [comment]
Invalid issue - READ : #689

**Comment by lshqqytiger** [comment]
[README.md 46번째 줄](https://github.com/JJoriping/KKuTu/blob/9552e33ed3643d176a175eda36b5e1267830733d/README.md?plain=1#L46) 확인해주세요.
