### ISSUE TITLE
DB 관련 질문

### ISSUE THREAD

**Issue by Astro36** [JJoriping/KKuTu#106]
제가 끄투 단어 DB를 이용하여 텔레그램에서 끝말잇기를 할 수 있는 봇을 만드려고 합니다.
단어 DB가 PostgreSQL 형태로 되어 있어서 수정 및 이식에 어려움을 겪고 있는데 json과 같은 postgresql 이외의 형태로 단어 데이터를 얻을 수 있을까요?

**Comment by JJoriping** [comment]
안녕하세요. 본 레포지토리에서 별도로 다른 형태의 파일은 제공하고 있지 않으며 주어진 파일 `./db.sql`을 Python 등으로 직접 적절히 가공하기 바랍니다.

**Comment by Astro36** [comment]
@JJoriping `dp.sql`의 라이선스는 GPL-3.0인가요?

**Comment by JJoriping** [comment]
해당 파일 상단에 라이선스와 관련된 내용을 주석으로 명시해 놓았습니다.
