### ISSUE TITLE
서버를 열려고 하면 오류가 나며 열리지 않습니다.

### ISSUE THREAD

**Issue by BJbluepsy** [JJoriping/KKuTu#107]
![pkt](https://user-images.githubusercontent.com/16697820/27336364-49e6ecee-560a-11e7-8d33-78dc8e8342d2.png)

서버를 열려고 할 때 마다 위 사진과 같은 오류가 지속적으로 발생하여 서버가 열리지 않습니다.
다른 프로그램상에는 오류가 없고, 현재 사용중인 끄투 서버 파일 중 하나가 오류의 원인인듯 하나, 아직 알아내지는 못했습니다.

**Comment by yunho0508** [comment]
관리자 권한으로 실행해 보셨나요?

**Comment by BJbluepsy** [comment]
제가 직접 수정한파일로는 열리지 않고요, 다른 서버의 파일을 이용하여 테스트해봤을때는 잘 열렸습니다.

**Comment by yunho0508** [comment]
제가 너무 성급하게 봤내요.. 웹서버를 할당하다가 오류가 나는것 같은대... 저는 저 할당하는 부분을 127.0.0.1로 번경하여 고쳤습니다.

**Comment by BJbluepsy** [comment]
그러면 변경하는 방법좀 알려주세요~!

**Comment by JJoriping** [comment]
다른 프로그램에서 포트 8000 및 8416을 사용하고 있기 때문에 EADDRINUSE 오류가 발생한 것으로 보입니다. netstat 등의 도구를 이용해 해당 포트를 사용하고 있는 서비스가 있는지 확인해 보기 바랍니다.
