### ISSUE TITLE
서버 구축중 오류가 생겨 질문드립니다.

### ISSUE THREAD

**Issue by scm1400** [JJoriping/KKuTu#1070]
웹소켓 연결이 실패한 것(?)으로 추정되는데 도움 받을 수 있을까요 ㅠ

로컬에선 잘 되었는데 서버에 올리니 문제가 발생했습니다.

주소:
http://zepkkutu-env.eba-4upqpmzv.ap-northeast-2.elasticbeanstalk.com/

콘솔
![image](https://user-images.githubusercontent.com/35059497/218268386-9b724354-27d8-464c-a390-972accb76ba4.png)

보안그룹 설정
![image](https://user-images.githubusercontent.com/35059497/218268338-73406d0c-d96c-447d-a6a4-082dd37026a5.png)

#URL 조회시
![image](https://user-images.githubusercontent.com/35059497/218266721-6520d3c9-93d3-4430-8836-25a078ef5685.png)

화면
![image](https://user-images.githubusercontent.com/35059497/218266602-89c47190-9d52-496d-8d30-46d27c6fd04c.png)

**Comment by lshqqytiger** [comment]
외부에서 확인 시 8080, 8496 포트가 닫혀있는 것으로 조회됩니다.

**Comment by scm1400** [comment]
허 이상하네요 ㅠ
원인을 확정해주셨으니.. 다시 확인해보겠습니다 
늦은 시간에 댓글 남겨주셔서 감사합니다

**Comment by Kerlib** [comment]
#689

**Comment by scm1400** [comment]
> 외부에서 확인 시 8080, 8496 포트가 닫혀있는 것으로 조회됩니다.

뭔가 로드 밸런서에서 막히는 느낌이네요ㅠ
서버 IP에 직접 접근하면 웹소켓 연결이 되는데 url 주소에서만 안되네요 ㅠ
로드밸런서 설정을 어떻게 해야하는지 아는분 계실까요

**Comment by lshqqytiger** [comment]
전 따로 개인 도메인에 A레코드 추가해서 연결했었습니다.

**Comment by scm1400** [comment]
> 전 따로 개인 도메인에 A레코드 추가해서 연결했었습니다.
휴 로드밸런서 제거하니 되는거같네요 ㅠㅠ
링크 요기로 잘되네요 
http://zepkkutuserver-env.eba-xkdxtwnv.ap-northeast-2.elasticbeanstalk.com/?server=0

lshqqytiger님 처럼 해야겠어요..
감사합니다

로드밸런서 짜증..
