### ISSUE TITLE
끄투서버 ssl 적용오류

### ISSUE THREAD

**Issue by frgrtyt** [JJoriping/KKuTu#1080]
ssl 적용을 했는데 요렇게뜨네요?
s.js:646 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode); ^ Error: ENOENT: no such file or directory, open 'C:\Users\curun\Document\KuTu-master\Server\ssl\ca_bundle.crt' at Object.fs.openSync (fs.js:646:18) at Object.fs.readFileSync (fs.js:551:33) at module.exports (C:\Users\curun\Document\KKuTu-master\Server\lib\sub\secure.js:35:31) at Object.&lt;anonymous> (C:\Users\curun\Document\KKuTu-master\Server\lib\Game\slave.js:28:18) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17)
[2023-05-01 18:18:07] Worker @1 22240 died
fs.js:646 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode); ^ Error: ENOENT: no such file or directory, open 'C:\Users\curun\Document\KuTu-master\Server\ssl\ca_bundle.crt' at Object.fs.openSync (fs.js:646:18) at Object.fs.readFileSync (fs.js:551:33) at module.exports (C:\Users\curun\Document\KKuTu-master\Server\lib\sub\secure.js:35:31) at Object.&lt;anonymous> (C:\Users\curun\Document\KKuTu-master\Server\lib\Game\slave.js:28:18) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17)
[2023-05-01 18:18:07] Worker @1 14200 died
fs.js:646 return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode); ^ Error: ENOENT: no such file or directory, open 'C:\Users\curun\Document\KuTu-master\Server\ssl\ca_bundle.crt' at Object.fs.openSync (fs.js:646:18) at Object.fs.readFileSync (fs.js:551:33) at module.exports (C:\Users\curun\Document\KKuTu-master\Server\lib\sub\secure.js:35:31) at Object.&lt;anonymous> (C:\Users\curun\Document\KKuTu-master\Server\lib\Game\slave.js:28:18) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17)
[2023-05-01 18:18:07] Worker @1 20360 died
G: CLOSED WITH CODE null

**Comment by lshqqytiger** [comment]
```
Error: ENOENT: no such file or directory, open 'C:\Users\curun\Document\KuTu-master\Server\ssl\ca_bundle.crt'
```
`C:\Users\curun\Document\KuTu-master\Server\ssl\ca_bundle.crt` 경로를 찾을 수 없습니다.

**Comment by frgrtyt** [comment]
module.js:674 throw err; ^ SyntaxError: C:\Users\curun\Document\KKuTu-master\Server\lib\sub\global.json: Unexpected token U in JSON at position 547 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (module.js:671:27) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.&lt;anonymous> (C:\Users\curun\Document\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10)
G: CLOSED WITH CODE 1
module.js:674 throw err; ^ SyntaxError: C:\Users\curun\Document\KKuTu-master\Server\lib\sub\global.json: Unexpected token U in JSON at position 547 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (module.js:671:27) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.&lt;anonymous> (C:\Users\curun\Document\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10)
Worker 14776 died
W: CLOSED WITH CODE 0

**Comment by lshqqytiger** [comment]
`global.json`에 JSON 문법 오류가 있습니다.
`"C:\Users\..."` (X) 유효하지 않은 Escape 문자(`\U`)
`"C:\\Users\\..."` (O) 유효한 Escape 문자(`\\`)
`"C:/Users/..."` (O)

**Comment by frgrtyt** [comment]
:\Users\curun\Document\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocket.js:344 else throw new Error('not opened'); ^ Error: not opened at WebSocket.send (C:\Users\curun\Document\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocket.js:344:18) at C:\Users\curun\Document\KKuTu-master\Server\lib\Web\main.js:129:26 at Array.forEach (&lt;anonymous>) at Timeout._onTimeout (C:\Users\curun\Document\KKuTu-master\Server\lib\Web\main.js:128:15) at ontimeout (timers.js:482:11) at tryOnTimeout (timers.js:317:5) at Timer.listOnTimeout (timers.js:277:5)
Worker 10668 died
W: CLOSED WITH CODE 0

**Comment by lshqqytiger** [comment]
게임 서버 웹소켓이 열리지 않은 상태에서 웹 서버가 `seek` 메시지를 전송했습니다.
일반적인 상황에서는 발생하지 않는 오류입니다.
