### ISSUE TITLE
모바일 끄투서버 만들기

### ISSUE THREAD

**Issue by frgrtyt** [JJoriping/KKuTu#1081]
혹시 모바일로 끄투서버를 만들수 없을까요?

**Comment by lshqqytiger** [comment]
루팅된 안드로이드 스마트폰에서는 이론적으로는 가능합니다.
(루트 권한 없이 외부에서 접속 불가능)
윈도우 노트북, 태블릿에서도 가능합니다.

**Comment by frgrtyt** [comment]
배치파일 어덯게 실행해요?

**Comment by lshqqytiger** [comment]
배치파일은 실행할 수 없습니다.
termux와 같은 터미널 에뮬레이터를 사용해 리눅스 환경에서 실행할 수 있습니다.

**Comment by ljoljo9959** [comment]
#689
