### ISSUE TITLE
한방단어 관련 질문

### ISSUE THREAD

**Issue by dyumryum** [JJoriping/KKuTu#1085]
단어를 추가해서 한방단어가 아니게 된 단어가
끝말잇기에서 한방단어로 인식합니다.
이를 해결하고 싶은데 어떻게 해야하나요?

**Comment by jhj1228** [comment]
[#509](https://github.com/JJoriping/KKuTu/issues/509)

**Comment by dyumryum** [comment]
확인했습니다.
kkutu_manner에서 어떤 부분을 수정해야 작동하는 건가요?

**Comment by lshqqytiger** [comment]
`_id` 컬럼 값이 `더 이상 한방이 아닌 글자`인 레코드를 삭제하세요.

**Comment by dyumryum** [comment]
번복 죄송합니다.
pgadmin 4에서 kkutu_manner_ko 우클릭 후 자료 보기/편집에서 수정하는 것이 맞나요...?

**Comment by lshqqytiger** [comment]
```sql
DELETE FROM kkutu_manner_ko WHERE _id = '뷁';
```

**Comment by dyumryum** [comment]
감사합니다. 이슈 닫겠습니다.
