### ISSUE TITLE
끄투 서버 실행시 오류

### ISSUE THREAD

**Issue by Barang2** [JJoriping/KKuTu#1087]
서버는 정상작동 합니다, 그런데 자꾸 서버를 켤때마다 뜨는 오류가 있어서 문의드립니다

![캡처](https://github.com/JJoriping/KKuTu/assets/79014539/f0ee3c05-1c4c-4443-b9b1-e4918ec1f8c8)

이게 어떤 오류인지 알 수 있을까요?
run.bat 파일 실행시 나오는 cmd에서 뜨는 오류입니다

**Comment by lshqqytiger** [comment]
Electron에서 출력하는 랜더링 오류로 보입니다. 무시하셔도 끄투 서버 구동에는 문제가 없습니다.

**Comment by Barang2** [comment]
> Electron에서 출력하는 랜더링 오류로 보입니다. 무시하셔도 끄투 서버 구동에는 문제가 없습니다.

알겠습니다. 답변 감사합니다!
