### ISSUE TITLE
끄투 관리 페이지 gwalli  오류 400

### ISSUE THREAD

**Issue by KIWIMING-cyber** [JJoriping/KKuTu#1089]
제가 만든 끄투 gwalli에 들어갔는데
{
    "error": 400
}
라고 뜹니다. 전에 제 프렌드가 도와줘서 들가긴했는데 오늘 오류 뜹니다.
그래서 ssl 문제인가 봤는데 아니고요. 어떻게 하죠잉

**Comment by lshqqytiger** [comment]
먼저 관리자 권한이 있는 계정으로 로그인 하셔야 합니다.

**Comment by KIWIMING-cyber** [comment]
했는데요 운영자 휘장 있는 계정

**Comment by lshqqytiger** [comment]
휘장으로 구분하지 않습니다. [참고](https://github.com/JJoriping/KKuTu/wiki/S~global.json)

**Comment by KIWIMING-cyber** [comment]
global.json 에서 admin에 제 id 입력했어요 예로 들면 discord-78312879398 이런거

**Comment by lshqqytiger** [comment]
JSON 문법을 지켜서 배열로 작성하셨나요?

**Comment by KIWIMING-cyber** [comment]
네

**Comment by KIWIMING-cyber** [comment]
{
	"ADMIN": [ "discord-829621968914612264","discord-660090737135845376","discord-1133943078290473010" ],
	"MAIN_PORTS": [ 8080 ],
	"GAME_SERVER_HOST": "127.0.0.2",
	"KKUTUHOT_PATH": "/kkutu/data/kkutuhot.json",
	"PASS":"1234",
	"PG_HOST": "localhost",
	"PG_USER": "postgres",
	"PG_PASSWORD": "1234",
	"PG_PORT": 5432,
	"PG_DATABASE": "main",
	"GOOGLE_RECAPTCHA_TO_GUEST": false,
	"GOOGLE_RECAPTCHA_TO_USER": false,
	"GOOGLE_RECAPTCHA_SITE_KEY": "Your Google Recaptcha site key Here",
	"GOOGLE_RECAPTCHA_SECRET_KEY": "Your Google Recaptcha secret key Here",
	"IS_SECURED": false,
	"SSL_OPTIONS": {
		"PRIVKEY": "C:/Users/HP/Desktop/KKuTu-master/KKuTu-master/Server/lib/sub/private.key",
		"CERT": "Your SSL Certificate Here",
		"CA": "Your SSL CA-Bundle Here",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": false
	},
	"USER_BLOCK_OPTIONS": {
		"USE_MODULE": false,
		"USE_X_FORWARDED_FOR": false,
		"BLOCK_IP_ONLY_FOR_GUEST": true,
		"DEFAULT_BLOCKED_TEXT": "관리자에 의해 서비스 이용이 제한되었습니다.",
		"BLOCKED_FOREVER": "영구 이용제한"
	}
}

**Comment by lshqqytiger** [comment]
로그인한 계정의 식별 번호가 맞는지 확인해보세요. 그리고 DB 비밀번호가 보입니다.

**Comment by KIWIMING-cyber** [comment]
식별번호 맞는뎁셔

**Comment by lshqqytiger** [comment]
인게임에서 관리자 명령어가 동작하는지 확인해보세요. (#yell 등)
