### ISSUE TITLE
한국어 단어 뜻 (mean) 추가 시 에러 문의

### ISSUE THREAD

**Issue by CheolPang** [JJoriping/KKuTu#1090]
관리자 페이지에서 한국어 단어에 뜻을 추가하려고 하면 
Error when querying: INSERT INTO kkutu_ko ("flag", "type", "theme", "mean", "_id") VALUES ('4', '0', '30', '＂1＂［1］（1）경제 관리를 위한 수단이라는 관점에서 본 가격.', '가격공간') ON CONFLICT (_id) DO UPDATE SET "flag"='4', "type"='0', "theme"='30', "mean"='＂1＂［1］（1）경제 관리를 위한 수단이라는 관점에서 본 가격.' [2023-11-05 21:43:14] Context: error: ON CONFLICT 절을 사용하는 경우, unique 나 exclude 제약 조건이 있어야 함

이라고 오류가 나네요..

**Comment by Preta-Crowz** [comment]
DB 구성이 잘못된것 같습니다. 수동으로 _id에 UNIQUE를 달아주셔야할것 같습니다.

**Comment by CheolPang** [comment]
감사합니다. 나중에 DB 구성을 다시 해보겠습니다. 이슈 닫습니다.
