### ISSUE TITLE
끄투가 안켜져요

### ISSUE THREAD

**Issue by Hye0Ngit** [JJoriping/KKuTu#1094]
![image](https://github.com/JJoriping/KKuTu/assets/86336662/305ac5db-2f11-4d8c-a0c7-fbfe03e68d0e)
윈도우11 23H2, PostgreSQL 14.10, NodeJS 16.20.2 버전입니다

**Comment by d0ul** [comment]
Global.inc.json 파일에 설정을 저장하셨다면, 파일명을 global.json으로 바꿔보세요.

**Comment by lshqqytiger** [comment]
#1038
