### ISSUE TITLE
끄투 서버 구축 후 localhost에 들어갔을때 생긴 버그입니다

### ISSUE THREAD

**Issue by aslhanball** [JJoriping/KKuTu#1097]
ERROR OCCURRED! This worker will die in 10 seconds. :8496 [2023-12-29 9:16:22 ├F10: PM┤] ERROR: Error: Unknown authenticationOk message typeMessage

**Comment by aslhanball** [comment]
지금은 [2023-12-30 08:15:42] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2023-12-30 08:15:42] Game server #1 closed: 1006 라 뜨네요

**Comment by aslhanball** [comment]
페이지가 작동하지 않습니다.localhost에서 전송한 데이터가 없습니다. 라고 떠서 프리서버에 접속이 불가능합니다

**Comment by d0ul** [comment]
게임 서버에 오류가 있진 않은지 확인해보세요.
웹 서버만으로는 끄투를 실행할 수 없습니다.

**Comment by aslhanball** [comment]
Error when querying: UPDATE users SET "server"='' WHERE "server"='0' [2023-12-30 11:55:38] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2023-12-30 11:55:38] Context: error: "users" 이름의 릴레이션(relation)이 없습니다 [2023-12-30 11:55:38] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다 이건 어떻게 해결하나요

**Comment by d0ul** [comment]
Postgres 권한 오류입니다. 사용자 정보와 테이블, 데이터베이스의 권한을 확인해보세요.

**Comment by aslhanball** [comment]
사용자 정보와 테이블, 데이터베이스는 어디서 보나요?

**Comment by d0ul** [comment]
Postgres 콘솔에서 다음 명령어를 실행하여 권한 부여가 가능합니다:

**유저 생성**
`CREATE USER 계정이름 PASSWORD '비밀번호' SUPERUSER;`

**권한 부여**
`GRANT ALL PRIVILEGES ON DATABASE main TO 계정이름;`

**Comment by aslhanball** [comment]
Postgres 콘솔이 안보입니다. 명령 프롬포트에 쓰는건가요?

**Comment by lshqqytiger** [comment]
권한 문제처럼 보이지는 않고 데이터베이스 구축이 제대로 되지 않은 것 같습니다.
데이터베이스 구축부터 다시 해보세요.

**Comment by aslhanball** [comment]
데이터베이스 구축을 설정하고 있을때 ?대쫫???곗씠?곕쿋?댁뒪???대? ?덉쓬    이렇게 뜨는데 어떻게 해야하나요

**Comment by lshqqytiger** [comment]
먼저 기존에 구축한 데이터베이스를 drop하세요.

**Comment by aslhanball** [comment]
drop하는 명령어가 무엇인지 알수 있을까요?

**Comment by lshqqytiger** [comment]
```sql
DROP DATABASE main;
```

**Comment by aslhanball** [comment]
'drop'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다. 라고 떠서 데이터베이스를 드랍할수 없습니다.

**Comment by lshqqytiger** [comment]
CMD 명령어가 아니기 때문입니다. PSQL Shell에서 실행해야 하고 CMD나 PowerShell에서 해결하려면 [dropdb](https://www.postgresql.org/docs/11/app-dropdb.html)를 통해야 합니다.

**Comment by aslhanball** [comment]
dropdb -p 5000 -h eden -i -e demo 를 사용하면 되는건가요?

**Comment by lshqqytiger** [comment]
그건 예시일 뿐입니다. 인자는 상황에 맞게 바꾸셔야 합니다.
로컬 서버라면 `dropdb main`도 작동할 것으로 보입니다.

**Comment by aslhanball** [comment]
'dropdb'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다. 라고 뜨네요 저는 Nodejs,postgres,redis 기반으로 만들었습니다

**Comment by 10kwon** [comment]
> 'dropdb'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다. 라고 뜨네요 저는 Nodejs,postgres,redis 기반으로 만들었습니다

https://github.com/JJoriping/KKuTu/issues/1097#issuecomment-1872442227

**Comment by lshqqytiger** [comment]
dropdb.exe는 PostgreSQL 설치 위치에 있는 실행 파일입니다. 해당 파일 경로로 먼저 이동하세요.
![image](https://github.com/JJoriping/KKuTu/assets/39524005/0fa66993-c01f-4fdd-be70-09ebfb2a3eab)

**Comment by aslhanball** [comment]
파일 경로로 이동한 뒤 클릭하면 되는건가요

**Comment by lshqqytiger** [comment]
CMD인 경우
```
cd postgresql설치경로\버전\bin
(다른 파티션인 경우 전환 필요. d: e: 등)
dropdb -U postgres main
```

PowerShell인 경우
```
cd postgresql설치경로\버전\bin
.\dropdb -U postgres main
```

PSQL Shell인 경우
엔터 4번 입력 후 비밀번호 입력.
```sql
DROP DATABASE main;
```
![스크린샷 2023-12-30 160453](https://github.com/JJoriping/KKuTu/assets/39524005/c5243b69-4391-4356-a9df-a53a66659a59)

**Comment by d0ul** [comment]
**Windows 11의 경우**
우클릭 하여 Windows 터미널에서 열기

**Windows 10의 경우**
주소창 경로 복사하셔서 `cd` 옆에 붙여넣으세요.

**Comment by aslhanball** [comment]
감사합니다 덕분에 잘되네요
