### ISSUE TITLE
주제를 추가한뒤 게임에서 주제 추가가 안되어있습니다.

### ISSUE THREAD

**Issue by aslhanball** [JJoriping/KKuTu#1099]
#222 번에서 본걸로 KO_INJEONG에 주제의 이름을 추가한뒤 KO_KR에 추가한 뒤 게임에서 테스트할려고 들어갔는데 KO_KR을 수정해서 에러가 납니다.

**Comment by d0ul** [comment]
서버 및 웹 서버 재시작 후 새로 추가한 데이터가 적용됩니다.

**Comment by aslhanball** [comment]
그게 아닌 에러가 뜨며 웹이 먹통됩니다

**Comment by lshqqytiger** [comment]
오류 내용을 알려주셔야 하고 아마 수정하신 json 파일에 문법 오류가 있을 것으로 생각됩니다.

**Comment by aslhanball** [comment]
문법을 수정하고 난 뒤 확인했는데 주제가 없습니다

**Comment by aslhanball** [comment]
일단 이건 신조어가 안보이는거같은거여서 이 이슈는 닫겠습니다.
