### ISSUE TITLE
끄투 위키

### ISSUE THREAD

**Issue by ryush00** [JJoriping/KKuTu#11]
Github 위키 기능을 사용하는게 어떨까 싶습니다. 사용법이나 설치법, 문제 해결 등등의 공유가 좀 더 체계화 될거라고 생각합니다.

**Comment by JJoriping** [comment]
일단 위키를 열고 간단하게 내용을 적어보았습니다. 방학이 끝나고도 관리할 여유가 있을지 잘 모르겠네요.

**Comment by ryush00** [comment]
감사합니다!
