### ISSUE TITLE
구글 로그인 오류

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#110]
로그인 시도를 하면 
![_2017_06_25_16_25_37_833](https://user-images.githubusercontent.com/28685734/27514354-02617404-59c3-11e7-89aa-1d2c22632b12.png)
이렇게 나오는데 어떻게 하죠..?

**Comment by JJoriping** [comment]
안녕하세요. 사진에서 확인할 수 있듯이 무효(invalid)한 권한 요청 `https://www.googleapis.com/oauth2/v1/certs`으로 인해 발생한 것이니 이를 적절히 조치해 주세요.

**Comment by Sichisky** [comment]
흠.. login.pug 와 jauth 를 수정했습니다. 더 수정할게 있나요?

아니면 그냥 https 저거를 다른 주소로 바꾸면 되나요?

**Comment by JJoriping** [comment]
본 레포지토리에는 `https://www.googleapis.com/oauth2/v1/certs` 쪽으로 통신하는 부분이 없는데 어떤 이유로 추가하게 되었는지 모르겠습니다. 현재 구글이 제공하고 있는 oAuth 방식이 레포지토리의 것과 다른가요?

**Comment by Sichisky** [comment]
아뇨 달라진건 없을텐데..
..뭐가 문젠지 전 아직은 모르겠네용 ;
