### ISSUE TITLE
주제가 안보입니다

### ISSUE THREAD

**Issue by aslhanball** [JJoriping/KKuTu#1100]
신조어,가톨릭,의학이 사전 목록과 단어에는 등재되있지만 자음퀴즈,단대같은곳에서 안보입니다.

**Comment by lshqqytiger** [comment]
일반 주제:
한국어의 경우 Const.KO_THEME, 영어의 경우 Const.EN_THEME에 추가.
어인정 주제:
Const.IJP_EXCEPT에서 제외.

**Comment by aslhanball** [comment]
그 IJP_EXCEPT에 있는 단어가 안보이는건가요?

**Comment by lshqqytiger** [comment]
IJP_EXCEPT는 InJeongPick (주제선택)에서 except (제외)되는 주제 목록입니다.

**Comment by aslhanball** [comment]
그 인정픽이 exports.KO_INJEONG 인가요?

**Comment by aslhanball** [comment]
그 신조어 가톨릭 의학이 IJP_EXCEPT에 없는데 안보여서요..

**Comment by lshqqytiger** [comment]
가톨릭, 의학은 어인정 주제가 아니고 일반 주제입니다.
신조어는 잘 되는걸 확인했습니다.
![image](https://github.com/JJoriping/KKuTu/assets/39524005/7dd61785-aaaa-49bc-abc3-0e6a828289c4)

**Comment by aslhanball** [comment]
![dsadsadsadsadsadsadsa](https://github.com/JJoriping/KKuTu/assets/155160367/b5488630-ed4f-4a54-8c6b-238ed742d70d)
이렇게떠서요..

**Comment by lshqqytiger** [comment]
서버 재시작해보셨나요

**Comment by aslhanball** [comment]
네 재시작한 후입니다

**Comment by lshqqytiger** [comment]
그럼 남은 방법은 강제로 넣는 것 밖에 없죠.
```js
exports.KO_IJP = ...;
exports.KO_IJP.push("OIJ");
```

**Comment by aslhanball** [comment]
어디쓰면돼나요?

**Comment by lshqqytiger** [comment]
const.js exports.IJP_EXCEPT 밑에 있습니다.

**Comment by aslhanball** [comment]
감사합니다

**Comment by aslhanball** [comment]
그 추가했는데 또 주제가 추가 안돼서요

**Comment by aslhanball** [comment]
![dfsfdsdfsfdsfds](https://github.com/JJoriping/KKuTu/assets/155160367/0ca56025-a0db-4beb-8a2d-983f50b71453)
여기서 잘못된점이 있나요?

**Comment by aslhanball** [comment]
> const.js exports.IJP_EXCEPT 밑에 있습니다.

그 밑에 쓰는게 아니라 밑에 따로 있는건가요?

**Comment by lshqqytiger** [comment]
`exports.KO_IJP = ...;`은 뒤 내용이 길어서 생략한 것이었습니다.
```js
exports.IJP_EXCEPT = [
	...
];
exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
exports.KO_IJP.push("OIJ");
```

**Comment by aslhanball** [comment]
] 부분에 에러가 생겼습니다.

**Comment by aslhanball** [comment]
> `exports.KO_IJP = ...;`은 뒤 내용이 길어서 생략한 것이었습니다.
> 
> ```js
> exports.IJP_EXCEPT = [
> 	...
> ];
> exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
> exports.KO_IJP.push("OIJ");
> ```
여기 있는 ] 부분에 에러가 나 작동을 안합니다

**Comment by lshqqytiger** [comment]
그대로 복사, 붙여넣기하지 마세요. 코드 위치를 찾기 쉽게 주변 내용을 적어드린 것 뿐입니다.

**Comment by aslhanball** [comment]
네

**Comment by aslhanball** [comment]
![dsasdasdadsasda](https://github.com/JJoriping/KKuTu/assets/155160367/9ee9463e-8193-4f15-b98d-9f16e189f150)
이렇게 하면 이제 된건가요?

**Comment by lshqqytiger** [comment]
신조어 주제만 문제가 되는 것 아닌가요? 그리고 
```
exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
```
이 줄은 가장 위에 한 줄만 있으면 됩니다.

**Comment by aslhanball** [comment]
그 제가 만든 주제들도 안보여서요...

**Comment by lshqqytiger** [comment]
그러면
```js
exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
```
이 줄 바로 아래 줄에
```js
exports.KO_IJP.push("OIJ", "다른주제코드", "다른주제코드");
```
처럼 한 줄로 적거나 
```js
exports.KO_IJP.push("OIJ");
exports.KO_IJP.push("다른주제코드");
exports.KO_IJP.push("다른주제코드");
```
처럼 나열하세요.

**Comment by aslhanball** [comment]
그래도 추가가 안됩니다..

**Comment by aslhanball** [comment]
> 그러면
> 
> ```js
> exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
> ```
> 
> 이 줄 바로 아래 줄에
> 
> ```js
> exports.KO_IJP.push("OIJ", "다른주제코드", "다른주제코드");
> ```
> 
> 처럼 한 줄로 적거나
> 
> ```js
> exports.KO_IJP.push("OIJ");
> exports.KO_IJP.push("다른주제코드");
> exports.KO_IJP.push("다른주제코드");
> ```
> 
> 처럼 나열하세요.

이것을 보고 2가지 방법을 시도해봤지만 신조어/유행어는 사전 카테고리에는 있고 나머지는 아예 단어들만 쓸수 있습니다...

**Comment by aslhanball** [comment]
![sdadsadsadsasda](https://github.com/JJoriping/KKuTu/assets/155160367/e9051fb8-b459-4a80-9742-ee9d30b083f0)
![dsadsasdadsasda](https://github.com/JJoriping/KKuTu/assets/155160367/a4521347-4559-4c5b-bc3d-4d8d5831866b)
이런식으로 사전에는 단어 주제가 뜨지만 게임에는 주제는 뜨지 않습니다.

**Comment by aslhanball** [comment]
태초마을로가서 닫겠습니다 그때도 버그생기면 

> 그러면
> 
> ```js
> exports.KO_IJP = exports.KO_INJEONG.concat(exports.KO_THEME).filter(function(item){ return !exports.IJP_EXCEPT.includes(item); });
> ```
> 
> 이 줄 바로 아래 줄에
> 
> ```js
> exports.KO_IJP.push("OIJ", "다른주제코드", "다른주제코드");
> ```
> 
> 처럼 한 줄로 적거나
> 
> ```js
> exports.KO_IJP.push("OIJ");
> exports.KO_IJP.push("다른주제코드");
> exports.KO_IJP.push("다른주제코드");
> ```
> 
> 처럼 나열하세요.

태초마을로가져서 닫겠습니다 또생기면 이거 한번더 사용해보겠습니다.

**Comment by Preta-Crowz** [comment]
주제 추가 자체가 제대로 되지 않은것 같습니다. 혹시 언어 파일만 수정하진 않으셨냐요?

**Comment by aslhanball** [comment]
현재 해결되었습니다
