### ISSUE TITLE
아이템을 구매했는데 인벤토리에 안보입니다.

### ISSUE THREAD

**Issue by aslhanball** [JJoriping/KKuTu#1102]
제목 그대로 아이템을 구매했는데 인벤토리에서 안보입니다

**Comment by d0ul** [comment]
구매하신 아이템을 ‘되팔기’했는지, 구매 후 새로고침 했는지 다시 확인해 주세요.

앞으로 이슈를 작성하실 때는 아래 내용을 지켜 주시면 보다 빨리 답변드릴 수 있을 것 같습니다.

# 좋은 이슈의 작성 방법
* 재현 절차를 작성하세요.
* 문제가 되는 로그나 코드를 올리세요.
* 스크린샷이 가능하다면, 올려주세요.

**Comment by mjonthemoon** [comment]
깃허브 이슈는 사용자의 과실로 일어난 오류를 소스의 오류인 양 물어보라고 있는 기능이 아닙니다. 올바른 과정을 거쳤다면(아이템을 올바르게 추가하고 아이템 고유 ID에 맞게 아이템 이미지를 적당한 폴더에 저장해 두었다면) 그러한 오류는 나타나지 않아야 합니다
끄투 프리서버를 운영하시기 위해서는 최소한의 프로그래밍 지식이 있어야 합니다. 구글링 조금만 하면 해결 방법을 찾을 수 있을 만한 오류들을 자꾸 끄투 오픈소스 레포지토리 이슈에 반복적으로 올리시는데 그러시지 않으셨으면 좋겠습니다 🙏

**Comment by aslhanball** [comment]
> 구매하신 아이템을 ‘되팔기’했는지, 구매 후 새로고침 했는지 다시 확인해 주세요.
> 
> 앞으로 이슈를 작성하실 때는 아래 내용을 지켜 주시면 보다 빨리 답변드릴 수 있을 것 같습니다.
> 
> # 좋은 이슈의 작성 방법
> * 재현 절차를 작성하세요.
> * 문제가 되는 로그나 코드를 올리세요.
> * 스크린샷이 가능하다면, 올려주세요.

GM 배지도 안보이며, 인벤토리 자체의 기본 아이템도 안보입니다. 되팔이는 안했고요. 구매 후 새로고침은 많이 해본뒤에 작성한겁니다.

**Comment by aslhanball** [comment]
문제가 되는 로그나 코드는 없으며 스크린샷을 올려도 영상이 아니라면 사실상 불가능합니다.

**Comment by d0ul** [comment]
> > 구매하신 아이템을 ‘되팔기’했는지, 구매 후 새로고침 했는지 다시 확인해 주세요.
> > 앞으로 이슈를 작성하실 때는 아래 내용을 지켜 주시면 보다 빨리 답변드릴 수 있을 것 같습니다.
> > # 좋은 이슈의 작성 방법
> > 
> > * 재현 절차를 작성하세요.
> > * 문제가 되는 로그나 코드를 올리세요.
> > * 스크린샷이 가능하다면, 올려주세요.
> 
> GM 배지도 안보이며, 인벤토리 자체의 기본 아이템도 안보입니다. 되팔이는 안했고요. 구매 후 새로고침은 많이 해본뒤에 작성한겁니다.

GM 배지는 비매품입니다. 관리 페이지에서 수동으로 적용하셔야 합니다.

**Comment by aslhanball** [comment]
> > > 구매하신 아이템을 ‘되팔기’했는지, 구매 후 새로고침 했는지 다시 확인해 주세요.
> > > 앞으로 이슈를 작성하실 때는 아래 내용을 지켜 주시면 보다 빨리 답변드릴 수 있을 것 같습니다.
> > > # 좋은 이슈의 작성 방법
> > > 
> > > * 재현 절차를 작성하세요.
> > > * 문제가 되는 로그나 코드를 올리세요.
> > > * 스크린샷이 가능하다면, 올려주세요.
> > 
> > 
> > GM 배지도 안보이며, 인벤토리 자체의 기본 아이템도 안보입니다. 되팔이는 안했고요. 구매 후 새로고침은 많이 해본뒤에 작성한겁니다.
> 
> GM 배지는 비매품입니다. 관리 페이지에서 수동으로 적용하셔야 합니다.

현재 관리 페이지에서 적용한 후입니다. 기본 눈,입도 안보입니다.

**Comment by Preta-Crowz** [comment]
> 현재 관리 페이지에서 적용한 후입니다. 기본 눈,입도 안보입니다.

인벤토리 데이터를 확인해주세요. 끄투는 기본적으로 아이템 로딩 실패에 대한 폴백이 구현되어 있지 않아, 한개의 아이템이라도 잘못된 값이 들어가면 인벤토리 자체를 로딩할수 없습니다.

**Comment by aslhanball** [comment]
감사합니다. 이슈 닫습니다.
