### ISSUE TITLE
PostgreSQL 5432 포트 접속 오류

### ISSUE THREAD

**Issue by CheolPang** [JJoriping/KKuTu#1104]
sudo node RailfansnailKKuTu/Server/lib/Game/cluster.js 0 1을 실행하여 서버를 열려고 하였으나 라즈베리파이 OS (Debian) 재부팅 후 부터 Error when connect to PostgreSQL server: Error: connect ECONNREFUSED 127.0.0.1:5432 에러가 뜨며 서버가 시작되지 않습니다. (Debian)

**Comment by aslhanball** [comment]
#123

**Comment by lshqqytiger** [comment]
PostgreSQL 서버가 5432 포트로 열려있고 연결 가능한지 확인하세요.
재부팅 후 증상이 나타났다면 서비스가 자동 시작으로 설정되어있지 않을 가능성이 높습니다.

**Comment by CheolPang** [comment]
OS 재설치 및 PostgreSQL 재설치로 해결했습니다. 감사합니다.
