### ISSUE TITLE
특수규칙 관련하여

### ISSUE THREAD

**Issue by s3zzio** [JJoriping/KKuTu#1107]
안녕하세요 ㅎㅎ,
한 게임의 유형에서 특수 규칙이 **6개** 이상일 때의 상황에 대한 궁금한 점이 있습니다. (방생성 확인 버튼의 위를 기준으로) 최대 여섯 개의 특수 규칙만 클릭 가능하며, 그 이상의 규칙은 클릭이 되지 않는 것으로 파악되었습니다. 게임 모드 하나당 특수 규칙 생성에 제한이 있는지에 대해 궁금합니다. 만약 제한이 있다면, 6개 이상의 규칙을 설정하는 다른 방법이 있는지 알고 싶습니다. 관련 정보를 찾아봤지만 유사한 내용을 찾지 못하여 이슈를 작성합니다 . 부족한 정보가 있을 수 있으므로, 첨부된 파일도 함께 참고해 주시면 감사하겠습니다. :)

![게임](https://github.com/JJoriping/KKuTu/assets/164531388/57d6d625-0f8b-4554-9ac4-f11374fdbe91)

감사합니다.

**Comment by jhj1228** [comment]
제한은 없으며 kkutu.pug에서 misc의 크기를 조절하면 됩니다.

**Comment by s3zzio** [comment]
정말 고맙습니다. 수정 했으므로 이슈 닫겠습니다.
