### ISSUE TITLE
서버를 열고 접속할려할시 문제가 발생합니다

### ISSUE THREAD

**Issue by DevloperCheongwol** [JJoriping/KKuTu#111]
![default](https://user-images.githubusercontent.com/23010804/27537162-8179bd6a-5aad-11e7-98ff-63a19d30e613.PNG)
웹에 들어갈시 나는 오류이고
![default](https://user-images.githubusercontent.com/23010804/27537170-89d9bb72-5aad-11e7-89bd-d96329ca9565.PNG)
콘솔은 이렇습니다

**Comment by JJoriping** [comment]
세션 정보를 읽을 수 없어 발생한 오류입니다. [파일 `./Server/lib/Web/main.js`의 세션 초기화 부분](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/main.js#L55)에서 세션 미들웨어를 적절히 초기화했는지 확인해 보세요. Redis가 설치되지 않은 환경에서 56번 줄의 주석을 해제한 경우 초기화에 실패하게 됩니다.

**Comment by DevloperCheongwol** [comment]
감사합니다 지금봤네여!!!
