### ISSUE TITLE
방을 생성하지 못하는 오류가 있음

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#1118]
http://seedkkutu.kro.kr

접속, 로그인까지는 되지만 방을 생성하게 되면 생성이 되지 않으며, localhost에서만 생성 및 접속이 가능함.

**Comment by lshqqytiger** [comment]
![image](https://github.com/user-attachments/assets/e8118ec5-d600-43df-8bea-0e151b210016)
방 포트가 닫혀있습니다.

**Comment by ghost** [comment]
3416  포트 개방했는데 접속 안됩니다

**Comment by 1ongames** [comment]
![image](https://github.com/user-attachments/assets/848659e0-48cf-42fb-a439-a723cca59162)

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/d300edcc-d9a5-47d8-961b-13aaa6cc72e7)

**Comment by lshqqytiger** [comment]
공유기나 라우터가 있다면 그쪽 설정을 확인해보세요.

**Comment by ghost** [comment]
> 공유기나 라우터가 있다면 그쪽 설정을 확인해보세요.

사용중인 서버 호스팅에서 처음부터 80, 443, 8080, 3000, 3030 포트만 개방되어있었네요

**Comment by ghost** [comment]
해결
