### ISSUE TITLE
방 만들기가 되지 않습니다.

### ISSUE THREAD

**Issue by ment12da** [JJoriping/KKuTu#112]
호스팅 업체 스위프트 노드로 서버를 이전한 후 서버를 열어서 들어가는 것 까지는 됬습니다. 허나 방만들기만 되지 않네요.. 너무 어이 없는 질문일 수도 있겠지만 혹시나 해서 이슈 남겨봅니다.

**Comment by JJoriping** [comment]
안녕하세요. 방을 만들 경우 로비(기본값 8080)와는 다른 포트(기본값 8496)와 연결하게 됩니다. 각 포트에 대해 적절히 포워딩을 했는지 확인해 보세요.

**Comment by ment12da** [comment]
감사합니다. 해결되었습니다.
