### ISSUE TITLE
리플레이 (경기저장) 관련

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#1120]
안녕하세요
게임 관전자에게는 경기저장 기능이 불가하도록 비활성화 되어있는데, 이를 수정할수 있는 방법이 있나요?

**Comment by kdhkr** [comment]
우선 #689 참고해 주세요.
현재 끄투 리플레이 파일은 서버에서 저장된 플레이 기록을 불러오는 것이 아닌, 클라이언트에서 받거나 보낸 요청을 직접 기록하는 방식으로 구현되어 있습니다. 이에 따라 중도입장한 플레이어에게 플레이 기록을 제공하는 것은 전면적인 코드 수정 없이는 어려울 것으로 보입니다.
다만, 게임 시작 전부터 게임방에 입장해있던 플레이어에게 플레이 기록 저장을 허용하는 것은 비교적 쉽게 구현할 수 있을 것으로 사료됩니다.

**Comment by wd5dw** [comment]
관전자도 f12키를 통하여 쉽게 경기저장 할수있는것을 발견하여 닫습니다
