### ISSUE TITLE
리눅스에서는 ./server-flush가 실행이 안되던데... 어떻게 하나요?

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#113]
리눅스에서는 ./server-flush가 실행이 안되던데... 어떻게 하나요?

**Comment by hatty163** [comment]
우분투 16.04로 서버 열었고, 상단 메뉴 수정하고 플레이어 제한 수정하느라 서버에 파일 올리고 재부팅해도 안바뀌네요...

**Comment by JJoriping** [comment]
파일 `./server-flush.bat`은 설치된 서버 관리자를 제거할 때 사용합니다. 파일 내용 중 `del` 명령어는 리눅스에서 제공하는 것이 아니므로 대신 `rm`을 사용해 보세요.
