### ISSUE TITLE
jjo.kr 및 kkutu.kr 사망으로 인한 서버 조회 불가능 문제

### ISSUE THREAD

**Issue by EririKawaii** [JJoriping/KKuTu#115]
이곳에 올리는 게 올바른지는 모르겠으나 끄투 프리서버의 상태를 확인하고 등록할 수 있는 http://jjo.kr/kkutu 및
 http://kkutu.kr/kkutu 페이지가 접속이 불가능해져 위 작업들도 불가능한 상태입니다.

**Comment by hatty163** [comment]
지금 수정됬습니다. 아마 업그레이드였던 듯

**Comment by JJoriping** [comment]
안녕하세요. 홈페이지 개편 작업으로 잠시 서버를 닫았으며 현재 정상 작동하고 있습니다.
