### ISSUE TITLE
일반 회원가입을 추가할려 합니다.

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#116]
> 일반 회원 가입 기능을 구현해 보시는 것도 추천합니다. 웹 페이지를 새로 만들 때에는 웹 클라이언트 측에서 `./Server/lib/Web/views/(뷰 이름).pug`과 `./Server/lib/Web/lib/(JS 이름).js`, `./Server/lib/Web/public/css/(CSS 이름).css` 파일을 각각 생성해 주시고 uglify를 위해 `./Server/lib/Gruntfile.js`를 적절히 수정해 주신 뒤 uglify 후 웹 서버(`./Server/lib/Web/main.js` 등)에서 해당 페이지 주소를 라우팅해 주시면 됩니다.

가 이해가 되지 않습니다. 어떻게 하는지 자세히 알려주셨으면 합니다.

**Comment by JJoriping** [comment]
안녕하세요. 일반 회원 가입을 위해서 회원 가입을 위한 별도 페이지 제작이 필요한데, 이 때 위에서 설명한 작업을 해야 한다는 의미입니다. 예를 들어 회원 가입 페이지의 이름(식별자)을 `join`이라 할 때, 뷰 파일 `./Server/lib/Web/views/join.pug`, 프론트엔드 스크립트 파일 `./Server/lib/Web/lib/in_join.js`, 스타일시트 파일 `./Server/lib/Web/public/css/in_join.css`을 작성한 뒤 파일 `./Server/lib/Gruntfile.js`의 상수 `LIST`에 프론트엔드 스크립트 파일의 이름(이 경우 `in_join`)을 원소로 추가합니다. 그 후 grunt 작업을 하고 파일 `./Server/lib/Web/main.js`에 아래 소스 코드를 추가하여 웹 서버를 실행시키면 외부에서 URL `/join`을 통해 회원 가입 페이지를 볼 수 있습니다.
``` javascript
Server.get("/join", function(req, res){
  page(req, res, "join");
});
```

회원 가입 전체를 구현하고자 한다면 이 페이지를 본 사용자가 입력한 정보를 토대로 서버의 데이터베이스에 회원 정보를 추가하는 작업 및 해당 회원 정보로 로그인할 수 있도록 하는 작업도 필요할 것입니다.

**Comment by hatty163** [comment]
![image](https://user-images.githubusercontent.com/14357656/28212105-dd6f1742-68da-11e7-8f0b-9db32bdb4fe0.png)
이렇게 파일을 구성하고 파일질라로 서버에
![image](https://user-images.githubusercontent.com/14357656/28212127-ef91085e-68da-11e7-897a-ab99979d992f.png)
/root/KKuTu/Server/lib/Web/public/login_email
에 올리고, *(주소 생략)*/login_email/index.php에 들어가보려고 하니

> Cannot GET /login_email/

이렇게 뜹니다. 어떻게 해결하죠 (MySQL 데이터베이스와 PHP 좀 사용해서 로그인 페이지 구성했습니다)


**그리고 만약 저 위에것을 해결하면 로그인 시 무엇을 하게 하면 되나요? (페이지의 로그인 버튼을 눌렀을때 어떻게 하게 하면 되나요?)**

**Comment by hatty163** [comment]
아 참고로 /login_email/index.php로 들어가면 index.php가 다운로드(???)됩니다.

**Comment by JJoriping** [comment]
php를 이용하기 위해서는 웹 서버가 php를 해석할 수 있도록 별도의 미들웨어를 설치해야 합니다. express-php 모듈 등을 검색해 express(웹 서버) 환경에서 php를 이용하는 방법을 확인해 보세요. 로그인 버튼을 누른 뒤에는 구현에 따라 달라질 수 있으며 일반적으로 https 및 POST 방법을 이용해 서버로 계정 정보를 전송합니다. 이후 서버가 데이터베이스를 조회하여 계정 정보와 일치하는 계정을 찾으면 세션(`req.session`) 정보에 로그인 상태를 기록하게 됩니다.

**Comment by hatty163** [comment]
> php를 이용하기 위해서는 웹 서버가 php를 해석할 수 있도록 별도의 미들웨어를 설치해야 합니다. express-php 모듈 등을 검색해 express(웹 서버) 환경에서 php를 이용하는 방법을 확인해 보세요. 로그인 버튼을 누른 뒤에는 구현에 따라 달라질 수 있으며 일반적으로 https 및 POST 방법을 이용해 서버로 계정 정보를 전송합니다. 이후 서버가 데이터베이스를 조회하여 계정 정보와 일치하는 계정을 찾으면 세션(req.session) 정보에 로그인 상태를 기록하게 됩니다.

어떻게 하는지 모르겠습니다. nginx는 끄투와 동시에 열 수 없기 때문에 쓰지 못하고요.
![image](https://user-images.githubusercontent.com/14357656/28238200-9b353afa-6989-11e7-86ee-b80c9ee2b086.png)
파일은 이러합니다. 어떻게 해야 될까요?

**Comment by small-sunshines** [comment]
흠.. Node.js 에서 PHP를 사용할 수 있는 방법이 있는지는 잘 모르겠습니다만, Nginx 하고 Node,js, PHP-FPM 을 동시에 사용하는 방법이 없지는 않습니다. 하지만 이는 엄청나게 복잡하며, 한번 Node.js 를 배우셔서 Node.js 를 이용한 개발을 해보시는 것이 더욱 간단한 방법이 아닐까 싶습니다.
