### ISSUE TITLE
포트 변경을 하려면 어느 곳을 바꿔야 하나요

### ISSUE THREAD

**Issue by minesna** [JJoriping/KKuTu#117]
포트 변경은 어느 곳을 바꿔야 하나요

**Comment by hatty163** [comment]
게임 서버 포트는 `global.json`에서 MAIN PORTS : 8080을 바꾸시면 됩니다.

**Comment by minesna** [comment]
그것을 말한건 아니지만 감사합니다

**Comment by gameworld3340** [comment]
main.js에서 Server.listen(80); 이 부분을 바꿔주시면 됩니다
이걸 질문하시는게 맞는지는 잘 모르겠네요
