### ISSUE TITLE
한국어 타자 대결 / 솎솎에서 '뮤'라는 단어만 나옵니다.

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#119]
![image](https://user-images.githubusercontent.com/14357656/28258814-3193cba8-6b0e-11e7-859b-59acb2c87478.png)`

![image](https://user-images.githubusercontent.com/14357656/28258856-6461c4b8-6b0e-11e7-8fca-b217fcea18f7.png)`

보이시는 것처럼 '뮤'라는 단어만 나옵니다. 왜 이럴까요?

**Comment by JJoriping** [comment]
각 게임 유형에 대한 구현은 디렉토리 `./Server/lib/Game/games`에서 이루어지고 있습니다. 이 중 타자 대결은 `typing`, 솎솎은 `sock`과 대응됩니다. 각 구현들의 [단어를 불러오는 부분](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Game/games/typing.js#L49)에서 확인할 수 있듯이 단어들은 데이터베이스에서 가져옵니다. 데이터베이스에 단어들이 잘 등록되어 있고 구현 부분에서 단어들을 올바르게 불러오고 있는지 psql 및 `console.log` 등을 통해 확인해 보세요.
