### ISSUE TITLE
페이스북 앱 ID를 어디에 넣어야 하는 거죠?

### ISSUE THREAD

**Issue by 7020kjs** [JJoriping/KKuTu#12]
앱 id를 어디에 넣어야 할지 전혀 모르겠습니다.

**Comment by pkquell** [comment]
Server/lib/Web/public/js/ 폴더에 facebook.js 파일을 만드셔야 합니다.

[](https://github.com/pkquell/KKuTu/blob/master/Server/lib/Web/public/js/facebook.js) 링크를 참고하세요.

**Comment by 7020kjs** [comment]
고쳤습니다. 감사합니다 :D
