### ISSUE TITLE
서버가 127.0.0.1로 밖에 접속이 안됩니다.

### ISSUE THREAD

**Issue by Mummu0409** [JJoriping/KKuTu#121]
도메인 연결을 시키려고 먼저 외부아이피를 브라우저에 입력해보았는데요, 들어가면 접속이 안되고 127.0.0.1, localhost 로 밖에 접속이 안됩니다. 참고로 저는 공유기 사용 안하고 벽면에서 랜선으로 인터넷 연결 합니다. 어떻게 해야 되나요?

**Comment by KKHaneul** [comment]
IP의 외부접속 개방 여부를 먼저 확인해보세요

**Comment by syskiller** [comment]
일단은 렌선을 연결 하셨다고 하였는대 통신사가 어디인지 인터넷 TV 를 보시는지...
통신사의 홈게이트 웨이가있는지 확인을 하셔야합니다.
그리고 윈도우의 경우 실행을 누르고 cmd 라고 치고 엔터
ipconfig 라고 치시면 내부 아이피(PC)에서 활당 받은 IP 를 알수있고
웹브라우저를 열어 주소창에 ipconfig.kr 입력후 이사이트에 들어가면 리얼아이피(유동이겠지만 ) 이 표시됩니다.
만약 내부아이피와 리얼 아이피가 틀리다면 공유기 또는 홈게이트 웨이가 설치되어있는경우라서
DMZ 설정이나 포트 포워딩 세팅을 해주어야합니다 ^^;

**Comment by BJbluepsy** [comment]
저도 같은 현상으로 접속이 되지 않습니다.
현재 아이피타임, 디오넷 공유기가 있으나, 아이피타임은 컴퓨터에 연결되어있지 않으며, 디오넷은 브릿지모드로 변경해둔 상태입니다.

**Comment by syskiller** [comment]
BJbluepsy 님 일단 통신사를 확인 하시고요 내트워크 구성에 홈게이트웨이(KT,SK 등에서 재공하는 것)구성이 들어가 있는지 확인을 하셔야합니다. 
즉 위에서 제가 말한대로 내부아이피와 외부 아이피가 동일한지부터 확인을 하시기를 바랍니다 ^^;

**Comment by BJbluepsy** [comment]
확인 다 해보았으며, 현재 해결된 상태입니다. 인터넷 공급사가 80번 포트를 막은것으로 판단하여 3141번 포트를 사용해본 결과 잘 작동됩니다.
