### ISSUE TITLE
서버 구동 후 게임 리스트가 실행되지 않습니다.

### ISSUE THREAD

**Issue by syskiller** [JJoriping/KKuTu#122]
![3](https://user-images.githubusercontent.com/8081988/28491514-18ce0c22-6f2e-11e7-8668-afb3fe9ba174.png)
위의 스샷처럼 정상적으로 실행은 되는듯하니
![4](https://user-images.githubusercontent.com/8081988/28491519-2eb62e8e-6f2e-11e7-81d1-068ccaefddfa.png)
웹에서 구동을하면 서버리스트에 나타나지도 않고(기본 세팅) 접속할수없습니다.
DB 구축은 정상적인것같구 웹서버 또한 정상적인것 같습니다
게임서버에서 문재가있는것 같은대... 이부분이 난의하내요...

현재 기본세팅에서 DB 암호 부분과 관리자 아이디 ,암호 부분만 수정 하였습니다..
조언 부탁드립니다.

**Comment by KKHaneul** [comment]
http://jjo.kr/kkutu 에 있는 끄투 프리서버 리스트는 직접 등록하셔야 합니다.

그 IP로 외부에서의 접속이 허용되어 있는지 살펴보세요.

**Comment by syskiller** [comment]
아 감사합니다.. 
내부에서 태스트를 해보려 했는대
 http://jjo.kr/kkutu 에 있는 끄투 프리서버 리스트는 직접 등록 해야 하는군요 ^^;
음 일단 집에 웹서버 를 운영 하고 있어 80포트는 사용이 힘들꺼같은대.. 포트 포워딩으로 변경해서 사용 해도 될까요? 그리고 끄투에서 사용되는 포트를 알고싶습니다...

**Comment by gameworld3340** [comment]
포트 변경같은 경우는 `lib\web\main.js`의 `Server.listen(?);` 부분에서 가능합니다.
저는 현재 2라는 포트로 지정하여놓고 서버를 실행시키면 나오는 << KKuTu Server:? >>에서 419라는
포트가 나와(?) 포트포워딩에 8080,5432,8496,419를 추가해놓았습니다. (제 기준입니다.)

**Comment by JJoriping** [comment]
사진에서 가장 먼저 발생한 오류(unexpected server response)는 [파일 `./Server/lib/Web/main.js`](https://github.com/JJoriping/KKuTu/blob/256c92f48d2a2cebc6d3369aa845384b01d1ca9f/Server/lib/Web/main.js#L136)에 의한 것입니다. 이는 웹 서버가 게임 서버와의 연결에 실패한 경우 발생합니다. 웹 서버는 주소 `127.0.0.2` 및 특정 포트를 통해 게임 서버에 웹소켓 연결을 시도합니다. 사용하는 포트에 대해서는 위키
 문서 [클러스터링](https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81#%ED%8F%AC%ED%8A%B8-%EB%B2%88%ED%98%B8)를 참고하세요.
