### ISSUE TITLE
SSL 적용 및 socket hang up

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#126]
main.js에 listen 값을 443으로 바꾸고, ws://를 wss://로 바꿨는데, (main.js의
gameServers[i] = new GameClient(KEY, ws://127.0.0.2:${v}/${KEY}); / kkutu&m_kkutu.pug의
gameServers[i] = new GameClient(KEY, ws://127.0.0.2:${v}/${KEY});를 모두 wss://로 바꾸고 SSL 인증서를 발급받아도 http://kkutu.hatty163.com:443/ 은 들어가지나 https://kkutu.hatty163.com/ 은 들어가지지 않습니다. 하지만, Apache 기본 페이지에서는 (서버를 끄면 나옵니다) SSL이 적용되어 있습니다.  또, wss://로 바꾼 다음 게임 서버가 Game server #1 has an error: Error: socket hang up라면서 연결되지 않습니다. 뭐가 문제인가요?

**Comment by small-sunshines** [comment]
흠.. 가능하시다면 Nginx ReverseProxy 를 이용한 HTTPS 서버 구현을 권장드립니다. Express.js 를 통한 TLS 서버 구축은 끄투의 경우 끄투 소스를 수정하여야 하는 불편함이 있어 Node.js를 잘 아시지 못하시는 분이라면 오히려 Nginx 를 조금 배우셔서 Nginx 에서 ReverseProxy 를 구성하시는 방식이 오히려 더 효과적이라 보입니다.
