### ISSUE TITLE
방을 새로 만들면 서버에서 연결이 끊어집니다.

### ISSUE THREAD

**Issue by 7020kjs** [JJoriping/KKuTu#13]
http://0xbof.me/

> [2017-02-17 22:08:15] Chan @0 Msg #O0xA0J5ZNw2c35buTWuxhYgaLVnkD4QA: {"type":"enter","title":"회원님의 방","password":"","limit":"8","mode":"3","round":"5","time":"60","opts":{"injpick":[],"manner":false,"injeong":true,"mission":false,"loanword":false,"proverb":false,"strict":false,"sami":false,"no2":false}}
> // 연결이 끊어졌다고 나옴
>[2017-02-17 22:09:55] Exit #O0xA0J5ZNw2c35buTWuxhYgaLVnkD4QA

**Comment by JJoriping** [comment]
무슨 뜻인지 모르겠습니다. 연결이 끊어졌다는 말이 특정한 오류를 출력하고 끊어진다는 말씀이신가요? 또한 해당 레포지토리는 @Ganggroid 님의 레포지토리에서 포크하신 것 같은데, 본 레포지토리의 소스 코드로는 정상 작동하고 있으니 다시 확인해 주세요.

**Comment by 7020kjs** [comment]
고쳤습니다.
알고보니 도메인 쪽에 문제가 있더라고요. ;;
