### ISSUE TITLE
단어 분류 추가

### ISSUE THREAD

**Issue by Yukeu** [JJoriping/KKuTu#132]
gwalli에 들어가서 맨 아래에 있는 

끄투 DB에 단어 추가하기

라는 명령어로 특정 단어의 분류를 공급하는 기능은 알겠는데 분류의 이름을 표시하는 방법을 모르겠습니다

**Comment by JJoriping** [comment]
이슈 #67 을 참고해 보세요.

**Comment by Yukeu** [comment]
늦게 확인해서 죄송합니다 ㅠㅠ 제가 말한게 그런 추가가 아니라, 현재 등록되 있지 않은 XX라는 분류를 추가하고 인게임에서 OOO라고 표시되게 하고 싶은데 어떻게 하는지 모르겠습니다 ㅠㅠ

**Comment by Yukeu** [comment]
폴더 들어가서 수정하니 해결됐네요. 닫겠슙니당

**Comment by KORraimi** [comment]
안녕하세요 저도 같은 문제에 처해 있어서 이 댓글을 보는데 이해가 안되네요. 알기 쉽게 설명좀 해주실래요
