### ISSUE TITLE
db.sql에 있는 의문의 숫자의 정체가 궁금합니다

### ISSUE THREAD

**Issue by Eeclipse** [JJoriping/KKuTu#133]
에콜드파리	0	＂1＂［1］（1）	0	5	170
연차관	1	＂1＂［1］（1）	0	0	0
와영	1	＂1＂［1］（1）	0	0	350
옴찍옴찍하다	5	＂1＂［1］（1）	0	0	0
와 같이 이런 숫자들로 데이터 베이스가 되어있는데 저 뒤의 숫자의 의미가 궁금합니다

**Comment by JJoriping** [comment]
순서대로 ① 표제어, ② 품사, ③ 뜻, ④ 사용자가 입력한 횟수, ⑤ 특성 플래그, ⑥ 주제를 나타냅니다.
나올 수 있는 품사 목록은 [이 곳](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/lang/ko_KR.json#L396), 주제 목록은 [이 곳](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/lang/ko_KR.json#L422)에서 확인하기 바랍니다. 특성 플래그는 [이 곳](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/const.js#L239)에 나열된 값들을 이진 연산한 값입니다.

**Comment by june2007** [comment]
사용자 입력한 횟수를 다루는 파일이 어디있는지 알 수 있을까요?

**Comment by lshqqytiger** [comment]
파일로 다루지 않습니다. 데이터베이스의 hit 컬럼입니다.
