### ISSUE TITLE
다른 GM휘장을 추가하려면 어떻해 해야되여

### ISSUE THREAD

**Issue by dongnebook** [JJoriping/KKuTu#135]
다른 GM휘장을 추가하려면 어떻게 해야되여

**Comment by JJoriping** [comment]
휘장을 포함한 모레미 치장 아이템은 테이블 `kkutu_shop`에서 다루고 있으며 관리 페이지(파일 `./Server/lib/Web/views/gwalli.pug` 참고)에서도 편집할 수 있습니다.
