### ISSUE TITLE
끄투 클라이언트 수정하려면 어떻게해야되요?

### ISSUE THREAD

**Issue by hjki001** [JJoriping/KKuTu#136]
이소스를 오픈소스화시킨 쪼리핑님에게경의를 표합니다.
끄투구동까지성공했는데
막상 끄투 클라를 수정하려고보니까 뭘 어떻게 건들어야되는지 감이 잘안오는데
그래서 질문드리는거예요
질문: 끄투 프리서버 클라이언트 수정하려면 어떻게 해야되요??

**Comment by JJoriping** [comment]
안녕하세요. 프리 서버와 그 클라이언트의 소스 코드에 대해 하나씩 설명하기에는 시간적 여유가 없어 지연되고 있으니 양해 부탁드립니다. 요약하자면 웹 클라이언트의 소스 코드는 모두 `./Server/lib/Web/lib` 안에 있습니다. 그 중에서도 끄투 게임과 관련된 부분은 `./Server/lib/Web/lib/kkutu` 안에 있습니다. 웹 클라이언트의 소스 코드를 수정한 경우 [Gruntfile.js](https://github.com/JJoriping/KKuTu/wiki/C~Gruntfile.js) 문서를 참고하여 grunt 작업을 해야 합니다. grunt 작업에 대한 내용은 다른 곳에도 자세하게 나와 있으니 검색 엔진을 활용해 보세요.

**Comment by hjki001** [comment]
그 html 파일수정을하려는데 갤러리를 개조후 부가기능으로사용할예정 이었지만
아무리찾아봐도 html파일을찾아볼수가없어서다시질문올립니다.

**Comment by JJoriping** [comment]
끄투는 페이지를 표시시키는 방법으로(뷰로써) HTML을 직접 사용하지 않고, 대신 [pug](https://pugjs.org/) 템플릿 엔진을 이용하고 있습니다. 뷰 파일들은 `./Server/lib/Web/views` 폴더에 있으니 확인해 보세요.

**Comment by hjki001** [comment]
네 잘알겠습니다 해결했으니 이이슈는 닫겠습니다.
