### ISSUE TITLE
네이버 쇼설 로그인 오류 때문에 질문드려봅니다

### ISSUE THREAD

**Issue by hjki001** [JJoriping/KKuTu#137]
#40 참고하여 수정하였는데
![default](https://user-images.githubusercontent.com/30684551/29362966-0036684a-82c9-11e7-9ab5-a57be7ab0fde.png)
로그인화면은정상적인데 네이버로 로그인하려면
![default](https://user-images.githubusercontent.com/30684551/29362955-f542ed6e-82c8-11e7-921d-f6a336ce8ec5.png)
이와 같이 오류를뿜으면서 로그인이 전혀안돼는 현상이 발생합니다.
![default](https://user-images.githubusercontent.com/30684551/29363148-cbf4e204-82c9-11e7-9e70-ca24bbe3f606.png)
코드는 제데로 됐습니다.
![default](https://user-images.githubusercontent.com/30684551/29363163-db58a8fc-82c9-11e7-904c-df2e93feac96.png)
콘솔에서도 문제가없는데 왜이럴까요? 궁금합니다

**Comment by ment12da** [comment]
리다이렉트 URL이 잘못되있습니다. 자신의 서버 도메인으로 재 수정을 부탁드립니다.

**Comment by kjbkjb1122** [comment]
` in_login.min.js` 에서 리다이렉트 url이 kkutu.kr로 되있으니 수정 부탁합니다.

**Comment by hjki001** [comment]
오 감사합니다 덕분에 잘알고갑니다 ㅎㅎ

**Comment by hjki001** [comment]
해결했으니 이 이슈는 닫겠습니다
