### ISSUE TITLE
관리자 페이지 접속 방법

### ISSUE THREAD

**Issue by hjki001** [JJoriping/KKuTu#138]
#15 를참고해서히려는데 ADMIN 배열에 무슨값을넣어야하나요?
정확한값을넣지않아선지 자꾸 /gwalli 접속할때마다 {ERROR 400} 만뜹니다 어떻게 해결하나요?

**Comment by ment12da** [comment]
ADMIN 배열에는 권한을 받을 일련번호를 넣어줘야합니다. 즉 인게임내에서 로그인후, /id 를 쳐서 나오는 값을 넣어야 한다는 소리죠.

**Comment by hjki001** [comment]
아그걸생각못했네요 당장확인해봐야겠습니다..
해결됬으니 이 이슈는 닫겠습니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
닌 도대체 그럼 ADMIN에다 뭘 집어넣었던거냐? 니 닉네임 썼냐?

**Comment by kjbkjb1122** [comment]
@SoManyIdiotsInKKuTuIssues 니 닉네임이 아니라 닉네임 식별코드야 옘병새끼야
