### ISSUE TITLE
데이터베이스 구축 까지는 했는데..

### ISSUE THREAD

**Issue by Terbium65** [JJoriping/KKuTu#139]
마지막에 run.bat를 실행하면 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.10.10
3 info using node@v6.10.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kkutu-server@2.5.0~prestart: kkutu-server@2.5.0
6 silly lifecycle kkutu-server@2.5.0~prestart: no script for prestart, continuing
7 info lifecycle kkutu-server@2.5.0~start: kkutu-server@2.5.0
8 verbose lifecycle kkutu-server@2.5.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle kkutu-server@2.5.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Owner\Downloads\KKuTu-master\KKuTu-master\Server\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\nodejs\;C:\PostgreSQL\pg96\bin;C:\Program Files (x86)\Java\jre1.8.0_111;C:\Users\Owner\AppData\Roaming\npm
10 verbose lifecycle kkutu-server@2.5.0~start: CWD: C:\Users\Owner\Downloads\KKuTu-master\KKuTu-master\Server
11 silly lifecycle kkutu-server@2.5.0~start: Args: [ '/d /s /c', 'electron .' ]
12 silly lifecycle kkutu-server@2.5.0~start: Returned: code: 1  signal: null
13 info lifecycle kkutu-server@2.5.0~start: Failed to exec start script
14 verbose stack Error: kkutu-server@2.5.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid kkutu-server@2.5.0
16 verbose cwd C:\Users\Owner\Downloads\KKuTu-master\KKuTu-master\Server
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error kkutu-server@2.5.0 start: `electron .`
22 error Exit status 1
23 error Failed at the kkutu-server@2.5.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the kkutu-server package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs kkutu-server
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls kkutu-server
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
-------------
이렇게 뜨네요..어떻게 해야되나요

**Comment by hjki001** [comment]
node.js 이 권장버전인지확인부탁드립니다,

**Comment by Terbium65** [comment]
우선은
------------------------------------
[2017-08-23 19:21:20] << KKuTu Web >>
[2017-08-23 19:21:22] Game server #undefined has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2017-08-23 19:21:22] Game server #undefined closed: 1006
[2017-08-23 19:21:22] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
[2017-08-23 19:21:22] Run with no-redis mode.
[2017-08-23 19:21:22] DB is ready.
-------------------------------------
여기 까지는 됐어요.그런데 정작 감자 서버에 들어가지를 못하네요.이럴 땐 어떻게 하나요?

**Comment by hjki001** [comment]
127.0.0.2는 게임서버와웹서버를 연결하기위해 예약해놓은 주소입니다.
포트는 8080를 사용합니다. 혹시 8080포트 사용하는 예 아파치 서버 같은게 구동되나 확인 부탁드립니다.

**Comment by Terbium65** [comment]
그 아파치 서버 127.0.0.1:8080 하니까 It works! 라고 뜨는데 이게 되는건가요? 제가 컴알못이라 ..

**Comment by hjki001** [comment]
it works! 라 뜨신다고요?
그럼 한글로 이것일겁니다. 정상작동한다는의미입니다
아파치서버를 삭제하시고, 정안돼시면 원격해드리겠습니다.
여기에 원격(팀뷰어) 아이디랑 비번남겨주십시요,

**Comment by hatty163** [comment]
@hjki001 팀뷰어 아이디랑 비밀번호를 여기에 남기면 큰일나죠. 님은 상관없지만 다른 사람이 보고 들어가면 어쩔 겁니까?

**Comment by minesna** [comment]
@hatty163 1회 사용하게 하고 바꾸면됩니다
