### ISSUE TITLE
서버 접속시 에러가 발생하고 종료됩니다..

### ISSUE THREAD

**Issue by hygn** [JJoriping/KKuTu#14]
> events.js:160 throw er; // Unhandled 'error' event ^ Error: bind EACCES null:80 at Object.exports._errnoException (util.js:1022:11) at exports._exceptionWithHostPort (util.js:1045:20) at cb (net.js:1324:16) at rr (cluster.js:625:14) at Worker. (cluster.js:594:9) at process. (cluster.js:765:8) at emitTwo (events.js:111:20) at process.emit (events.js:191:7) at process.nextTick (internal/child_process.js:744:12) at _combinedTickCallback (internal/process/next_tick.js:67:7)
> [2017-02-17 13:35:49] Exit web server #1
> Worker 6092 died
> W: CLOSED WITH CODE 0
를 내뿜고 웹브라우저 상에서는 404가 발생합니다.
주소는<a href="http://ec2-54-213-178-233.us-west-2.compute.amazonaws.com/">이곳</a>입니다

**Comment by JJoriping** [comment]
EACCES가 액세스가 거부되어 발생하는 걸로 알고 있습니다. 포트는 80번으로 잘 잡혀 있는 것 같습니다만 호스트가 null이라서 생기는 문제가 아닐까요?

**Comment by hygn** [comment]
자바스트립트쪽을 잘 몰라서 알아봐야겠네요.....

**Comment by ryush00** [comment]
혹시 리눅스 사용하시나요? 리눅스면 root 권한 없으면 80번 포트 사용 못하는걸로 알고 있습니다.

**Comment by hygn** [comment]
윈도우 서버2016 nano 입니다

**Comment by hygn** [comment]
일단 같은 서버에서 IIS 가 80번 포트를 쓰고 있어서 리버스 프록시를 구성해야겟네요
