### ISSUE TITLE
네이버 페이스북 구글 로그인 외 (예:카카오톡,트위터 로그인)  추가하는법

### ISSUE THREAD

**Issue by hjki001** [JJoriping/KKuTu#140]
기본 소셜 로그인 (페이스북,네이버,구글 로그인) 외 카카오톡 로그인 이나 트위터 로그인을 따로추가 하는법에대해 알려주시면 감사드리겠습니다.

**Comment by JJoriping** [comment]
안녕하세요. 다른 OAuth 서비스를 이용하기 위해서는 해당 서비스 제공자로부터 고유 키를 발급받은 뒤 파일 `./Server/lib/Web/lib/in_login.js` 및 `./Server/lib/sub/jauth.js` 중심으로 변경이 필요합니다. 이슈 #7 을 참고해 보세요.
