### ISSUE TITLE
아파치 노드 프록시 사용이 불가능한가요?

### ISSUE THREAD

**Issue by k4584587** [JJoriping/KKuTu#142]
![2017-08-30 2 01 00](https://user-images.githubusercontent.com/17105857/29856136-da6bca24-8d8b-11e7-9a1a-a01394a36429.png)

아파치 프록시로 서버를 구성했는데 서버로 들어가면 이런오류가 발생합니다.
프록시로 접속가능 하게할려면 어떻게 해야하나요?

httpd.conf 설정 내용입니다.

ProxyRequests off
    <Proxy *>
            Order deny,allow
            Allow from all
    </Proxy>
    <Location />
            ProxyPass http://localhost:6565/
            ProxyPassReverse http://localhost:6565/
    </Location>

**Comment by small-sunshines** [comment]
Apache 리버스프록시로 서버를 구성하실 때에 몇개 포트를 더 열어주고, WebSocket가 사용이 가능하게끔 설정해주셔야 합니다.

끄투에서 사용하는 포트는 웹서버 80(기본값), 게임서버 8080(기본값), 8080에 특정 값을 더한 포트(아마 433정도 될것같은데.. 다른분들의 코멘트를 기다리시거나 설명서에 잘 보시면 포트와 관련된 부분도 언급되어있습니다.)

**Comment by small-sunshines** [comment]
설명 확인 후 다시 연락드립니다. 웹서버의 포트점유 범위는 웹서버 설정 포트(예를들자면 80) 이며,

게임서버의 포트점유 범위는 기본포트 및 (기본포트+416+게임서버 워커 번호) 입니다.

게임서버 워커 번호의 범위는 0 부터 (게임서버 워커 생성갯수 - 1) 이며, 워커 생성갯수만큼 포트를 열어주셔야 합니다.

예를 들자면, 게임서버 기본포트가 8080 이며, 워커 생성갯수가 4개 라고한다면, 게임서버 워커에서 점유하는 포트는 8080, 8496, 8497, 8498, 8499 입니다.

그리고 게임서버는 WebSocket 를 사용할 수 있게끔 설정해주셔야 합니다.

**Comment by small-sunshines** [comment]
혹시 WebSocket ReverseProxy 설정하는방법이 필요하시다면

[https://stackoverflow.com/a/41685748](https://stackoverflow.com/a/41685748)

여기를 참고하시길 바랍니다.
