### ISSUE TITLE
구글 로그인 작동 안함

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#143]
제가 끄투 서버를 열고 구글 로그인을 구현하였습니다.
그런데 일부 컴퓨터에서 구글 로그인이 작동하지 않는 것을 보고, DOM 탐색기로 문제를 보니
![1504071389221](https://user-images.githubusercontent.com/14357656/29901856-73bc7e22-8e35-11e7-8e78-6a1ab007b931.png)
가 뜨네요. 뭐가 문제인가요?

**Comment by Kim-Daewoon** [comment]
구글 api js가 정상적으로 임포트 되어있는지 확인 부탁드립니다.
