### ISSUE TITLE
로그 보는 방법

### ISSUE THREAD

**Issue by gameworld3340** [JJoriping/KKuTu#144]
따로 끄투 서버가 꺼저도 로그가 저장되는 곳이 있나요?

**Comment by JJoriping** [comment]
안타깝게도 별도로 기록되지 않습니다. 다만 로그는 모두 파일 `./Server/lib/sub/jjlog.js`에서 정의한 함수를 이용하고 있으니 해당 함수를 수정하면 로그를 파일 등으로 기록할 수 있습니다.

**Comment by small-sunshines** [comment]
아니면 pm2 를 이용하여 Node.js 프로세스를 기동하는 방법이 있습니다만, 이를 이용할 경우 마스터 프로세스와 워커 프로세스간 통신에 교란이 생기기에 일부 코드를 수정하셔야 합니다.
