### ISSUE TITLE
서버 여는중 구글 로그인 오류가 납니다

### ISSUE THREAD

**Issue by playkkutumaker** [JJoriping/KKuTu#145]
![image](https://user-images.githubusercontent.com/31624406/30029822-bffa32dc-91c5-11e7-8848-3299a7dc7c96.png)

사진입니다
승인된 리디엑션인가 저거 어케 설정하나요?
그리고 저에게 뜨던데 인게임 서버 접속시#1006 오류가 나며 끊깁니다

**Comment by hatty163** [comment]
리다이렉션은 http://misutgaru.iptime.org:2/로 하셔야죠;;;

**Comment by kjbkjb1122** [comment]
여담으로 `main.js`에서 건드리신 포트가 없다면
포트 안 쓰셔도 됩니다.
