### ISSUE TITLE
1006에러가 납니다 도와주십쇼

### ISSUE THREAD

**Issue by playkkutumaker** [JJoriping/KKuTu#146]
![image](https://user-images.githubusercontent.com/31624406/30052614-019980f8-9261-11e7-824e-d0a4fdc96f74.png)

**Comment by playkkutumaker** [comment]
로컬호스트쪽으로 가게 되면 오류가 뜨지 않습니다

**Comment by minesna** [comment]
사용하는 포트가 모두 개방되어있지 않은것 같습니다.
포드포워딩보다는 DMZ를 추천합니다

**Comment by small-sunshines** [comment]
웹서버의 포트점유 범위는 웹서버 설정 포트(예를들자면 80) 이며,

게임서버의 포트점유 범위는 기본포트 및 (기본포트+416+게임서버 워커 번호) 입니다.

게임서버 워커 번호의 범위는 0 부터 (게임서버 워커 생성갯수 - 1) 이며, 워커 생성갯수만큼 포트를 열어주셔야 합니다.

예를 들자면, 게임서버 기본포트가 8080 이며, 워커 생성갯수가 4개 라고한다면, 게임서버 워커에서 점유하는 포트는 8080, 8496, 8497, 8498, 8499 입니다.

그리고 게임서버는 WebSocket 를 사용할 수 있게끔 설정해주셔야 합니다.

(다른 이슈에서 답변한 내용 복사)
