### ISSUE TITLE
서버가 구동이 되지 않습니다

### ISSUE THREAD

**Issue by playkkutumaker** [JJoriping/KKuTu#148]
웹서버를 접속 시 게임서버를 로딩하지 못합니다,다른 이슈를 보니 #123 에서 오류가 난 사람이 있더군요
여기서 게임서버,postgresql 서버를 먼저 구동시키는 방법은 없나요??

**Comment by small-sunshines** [comment]
postgresql 은 설치 후 구동하시면 되며, 끄투 서버를 GUI 프로그램으로 실행시키신다면 자동으로 게임서버가 먼저 켜집니다.
