### ISSUE TITLE
점수가 표시되지 않습니다

### ISSUE THREAD

**Issue by cho060303** [JJoriping/KKuTu#149]
![image](https://user-images.githubusercontent.com/23472828/30249180-6c083358-9671-11e7-9690-c2240e6ecd9d.png)

위와 같은 현상이 일어납니다 
Redis서버를 실행해도 같은 현상이 일어납니다

**Comment by ment12da** [comment]
오늘 제가 끄투 서버를 운영하던 중에도 저 문제가 발생하였습니다. 몇일전, kkutu.js 235번줄 즉
```		my.id = sid;``` 에서 ```		my.id = "guest:" + sid;``` 이런식으로 수정 한후 생긴 오류같습니다. 즉 235번 줄에 ```		my.id = "guest:" + sid;``` 이 코드를 임시적으로 ```		my.id = sid;``` 으로 바꾸시면 해결될꺼 같습니다.

**Comment by cho060303** [comment]
감사합니다 해결되었습니다
