### ISSUE TITLE
서버 구축중 궁금한점 있어서 이슈 남겨봅니다.

### ISSUE THREAD

**Issue by ys0503** [JJoriping/KKuTu#15]
일단 끄투 소스 공개에 매우 감사드립니다.
끄투 서버 구축중 궁금한점 두가지 있어서 이슈 한번 남겨봅니다.

1. 끄투서버 구동후 들어가보니 서버 목록에 감자서버밖에 없더군요, 끄투 본서버처럼 서버를 감자, 냉이... 등등으로 어떻게 나누는지 궁금합니다.

2. 웹 클라이언트에서 끄투 관리자 페이지에 들어가는 법과 끄투 DB에 단어를 추가하는 방법이 궁금합니다.

**Comment by JJoriping** [comment]
안녕하세요. 서버 분할에 대한 이야기는 [끄투 위키](https://github.com/JJoriping/KKuTu/wiki/%EC%9B%B9-%EC%84%9C%EB%B2%84)에 정리해 놓았으니 참고해 보세요.

**Comment by JJoriping** [comment]
관리자 페이지를 접속하기 위해서는 `./Server/lib/sub/global.json`의 `ADMIN` 배열에 OAuth 등으로 얻은 클라이언트 식별자를 추가한 뒤, 해당 계정으로 로그인하여 URL `/gwalli` 쪽으로 들어가시면 됩니다. 데이터베이스에 쓰기 작업을 할 때 페이지 가장 위의 암호 입력란에 `./Server/lib/sub/global.json`의 `PASS`에 해당하는 값이 들어가 있어야 합니다.

**Comment by ys0503** [comment]
관리자 페이지 관련 사항은 잘 해결했습니다. 감사합니다! 그런데 클러스터링 위키 페이지를 보고 
수정해줬는데도 서버목록에 감자서버밖에 뜨지 않는데 혹시 제가 더 수정해야할 부분이 있는건가요?

**Comment by JJoriping** [comment]
아 깜빡한 사항이 있었네요. 이 작업까지 해 주시면 될 겁니다.
* 게임 서버를 클러스터링하는 경우 클러스터링된 각 서버의 포트 번호를 ./Server/lib/sub/global.json의 MAIN_PORTS 배열에 기입해야 합니다. 포트 번호 간격은 게임 서버의 프로세스 수보다 커야 하며 권장 간격은 10입니다.

**Comment by ys0503** [comment]
제가 작성을 잘못한건지 포트 번호 간격을 권장사항인 10씩 띄어 8080, 8090, 8100 식으로 해당 배열에 기입했더니 서버구동은 되는데 바로 ECONNREFUSED 오류가뜨면서 게임서버가 바로 닫혀버리네요. 8070 이런식으로 작성해도 똑같은 오류가 발생합니다.  어떻게 해야할까요?

**Comment by JJoriping** [comment]
서버 관리자를 이용하시는 것 같군요. 이때까지 서버 관리자를 통해 서버를 여는 경우 클러스터링을 할 수가 없었습니다. 방금 관련 패치를 해 놓았으니 번거롭더라도 이 레포지토리를 다시 내려받아 주세요.

**Comment by ys0503** [comment]
감사합니다 :) 이제는 잘 되네요!
