### ISSUE TITLE
데이터 베이스 구축부터 서버 들어가게 하기, 서버 열기, 로그인 연결, 케린터 변경 등 알려주세요.

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#150]
너무 어렵습니다 다 알려주세요

**Comment by hatty163** [comment]
> 네. 이 쉬운 기본 상식으로만 이루어진 말을 모르겠으면 **끄투 서버 열려는거 때려 치우세요.** 뭐 끄투가 마***** 서버처럼 열기만 하면 열리는 줄 아십니까? 프로그래밍 공부하고 오세요. 명령어도 다 나와 있습니다.

**Comment by JJoriping** [comment]
이슈 #153 을 참고해 보세요.

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
제품을 샀으면 사용설명서를 읽어봐야지 읽지도 않고 질문하네

이새끼는 갤럭시폰 전원버튼 안눌러진다고 삼성병원 중환자실에 있는 이건희까지 깨울새끼다 ㄹㅇ

**Comment by hjki001** [comment]
와우 이쉬운걸 모르네 ㅋ
