### ISSUE TITLE
이건 어쩌죠?

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#152]
![image](https://user-images.githubusercontent.com/31878663/30364408-149c6f32-989f-11e7-8efa-bdca17bad6f7.png)
이건 엌[하죠?

**Comment by gameworld3340** [comment]
제바알..
`global.json`에서 `PG_PASS` 수정 바랍니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
옘병. 리드미 안읽냐?
