### ISSUE TITLE
도메인 연결및 네이버 로그인, 페북 로그인, 구글 로그인, 로고 바꾸기, 서버 늘리기(재대로 햇갈리지 않게게), 밑서버 등록법, 등 개설후 해야될걸 알려주세요ㅗ

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#153]
제곧내

**Comment by ment12da** [comment]
"도메인 연결및 네이버 로그인, 페북 로그인, 구글 로그인, 로고 바꾸기, 서버 늘리기(재대로 햇갈리지 않게게), 밑서버 등록법, 등 개설후 해야될걸 알려주세요"

어느정도 지식은 가지고 계셔야 운영이 가능하고, 여는게 가능한 부분인데 처음부터 끝까지 다모르시면 그냥 여는걸 포기하시는게 맞아요. 그리고 ```README.md``` 에 몇몇 부분은 나와있고, 몇몇 이슈를 찾아보면 다 나오는 내용을 꼭 이런식으로 이슈를 남겨야 할까요?

이슈를 찾아보고, 모른다면 찾아보고 그다음 정말 모르겠으면 이슈를 남기세요. 무작정 이렇게 이슈를 남기는건 올바른 행동이 아니라고 봅니다.

**Comment by KKHaneul** [comment]
README.md에서 정의하고 있는 내용들은 장식이 아닙니다. 모두 서버를 여는 데 필요한 정보들을 알 수 있는 내용들이며 이런 무분별한 이슈가 열리지 않게 해주는 역할도 합니다만, 이런 이슈를 여신 걸 보니 애초에 그 파일의 내용을 읽지조차 않으신 것 같네요.

더하기 빼기를 알아야 곱하기 나누기를 아는 법인데 더하기 빼기조차 모르시고 알고 싶지도 않아하시면 그냥 때려치시는 게 낫습니다.

**Comment by hatty163** [comment]
> "도메인 연결및 네이버 로그인, 페북 로그인, 구글 로그인, 로고 바꾸기, 서버 늘리기(재대로 햇갈리지 않게게), 밑서버 등록법, 등 개설후 해야될걸 알려주세요ㅗ"

뒤에 엿(ㅗ)는 뭡니까? 또, 이정도면 그냥 끄투 서버 여는거 때려치세요. 끄투가 모 서버처럼 그렇게 2분 내로 안열립니다. 뭐 이게 간편설치기(구동기)인줄 아십니까? 그리고 `Readme.md`는 왜 있습니까? 님같은 무개념을 위한 문서입니다. 이슈를 참고하시고 모르겠으면 그때 올리셔야죠. 그리고 프로그래밍 상식을 모르시면 어차피 끄투 서버 열고 유지보수 못합니다. 또, 네아로, 페이스북, 구글 등의 로그인은 많이 나와 있고, 로고는 그냥 로고 이미지만 바꾸시면 되지 않습니까? `밑서버`는 또 뭡니까? 뭔 말인지 이해가 안가네요. 도메인 연결은 그리고 왕초보도 할 수 있습니다. 그냥 A레코드 만들면 끝인데, 이걸 모르시나요? 제발인데 이런 이슈는 집어 치우세요.

**Comment by JJoriping** [comment]
안녕하세요. 모든 분들의 컴퓨터 활용 능력을 고려해서 설명을 작성하기에는 시간적 여유가 많이 모자라 아래 설명한 방법보다 더 자세하게는 제공하기 곤란한 점 이해해 주기 바랍니다.

* **도메인 연결** 방법은 다른 사이트에서 검색해 익히는 것을 권합니다.
* 네이버, 페이스북 등의 로그인 기능은 따로 **OAuth**라 하며, 이를 검색어로 본 레포지토리 이슈를 검색하면 다른 분들의 문답을 확인할 수 있습니다.
* 로고 등의 이미지 파일은 레포지토리 내 이미지 파일(png, ico)을 수정하면 됩니다.
* **서버 증설**은 [클러스터링](https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81) 항목을 참고해 보세요.
* **서버 등록**은 [내 서버 등록하기](https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0) 항목을 참고해 보세요.
* **개설 후**에는 더 이상 이러한 이슈로 다른 분들이 안타까워하지 않도록 충분한 컴퓨터 활용 능력을 쌓는 것이 어떨까요?

**Comment by minesna** [comment]
@hatty163 
오타가 날수있습니다.
이슈에서 그렇게 말하실것 까지는...
