### ISSUE TITLE
서버 취약점에 관한 버그 제보

### ISSUE THREAD

**Issue by 7020kjs** [JJoriping/KKuTu#154]
Windows 서버에서만 가능한 버그입니다.
`#yell <script>parent.window.close(); </script>`
본 명령어를 GUEST로 작성 시, 서버가 종료됩니다.

**Comment by Ganggroid** [comment]
GUEST는 어드민 권한을 갖고 있지 않기 때문에 공지 명령어는 사용이 불가능 합니다.
그리고 `#yell <script>parent.window.close(); </script>`를 써야 종료가 되는지, 아니면 yell 명령어를 쓰면 종료가 되는건지 자세히 알려주시면 감사하겠습니다.

**Comment by 7020kjs** [comment]
GUEST이나 해당 명령어가 콘솔에서 표시되고, 방어 코드가 없으므로 종료됩니다.
취약점 제보로, 전자에 가깝습니다.

**Comment by JJoriping** [comment]
안녕하세요. 제보 감사드리며 해당 문제는 커밋 55553c3 에서 처리했습니다.
