### ISSUE TITLE
DB 종류 변경

### ISSUE THREAD

**Issue by SkyLightQP** [JJoriping/KKuTu#155]
기존 PostgreSQL에서 MariaDB나 기타 DB 프로그램으로 바꾸려합니다.
DB 관련 함수를 다루는 파일이 있던데 그 쪽에 수정해주면 되나요?

**Comment by Kim-Daewoon** [comment]
아마 collection.js, db.js 쪽을 수정해주시면 될것 같습니다.

**Comment by SkyLightQP** [comment]
감사합니다
