### ISSUE TITLE
네이버 아이디 연동

### ISSUE THREAD

**Issue by korharu** [JJoriping/KKuTu#156]
일단 네이버 로그인창까지 띄우는건 되는데 로그인 하고 확인버튼을 누르게 되면 로그인이 안된 상태로 메인화면으로 오네요...

**Comment by Kim-Daewoon** [comment]
로그인 방식을 추가하기 위해서는 서버/클라이언트 수정이 필요합니다.
모두 수정하신 것이 맞으신지요?

**Comment by korharu** [comment]
KKuTu-master\Client 이 폴더 말씀하시는건가요...?

**Comment by JJoriping** [comment]
웹 서버가 여러 프로세스로 나누어져 있다면 각 프로세스가 동일한 세션 저장소(기본적으로 Redis)에 접근하고 있는지 확인해 보세요. 그렇지 않고 별개의 저장소를 이용하는 경우 한 클라이언트의 요청을 받는 서버 프로세스가 달라(=다른 저장소를 이용해) 세션 유지에 문제가 생깁니다.

**Comment by korharu** [comment]
아 다시 만들어보니 되네요. 감사합니다
