### ISSUE TITLE
끄투 프리서버 목록에서 403 오류

### ISSUE THREAD

**Issue by yunho0508** [JJoriping/KKuTu#157]
끄투 서버를 어떤 사유 때문에 종료하고 삭제하려고 했으나 '이런! POST /kkutu/manage 요청이 403 (Forbidden) 오류가 되어 돌아왔습니다.' 라는 오류와 함께 삭제가 되지 않는군요(비밀번호는 정확합니다)

**Comment by Kim-Daewoon** [comment]
403오류는 비밀번호가 맞지 않을 때 뜨는 오류입니다.
다시 한번 확인해보세요.

**Comment by yunho0508** [comment]
다시 한번 해보니까 되네요!! 감사합니다!
