### ISSUE TITLE
같은 서버에서 2개의 Redis 인스턴스를 돌릴 수 있나요?

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#158]
우선 한 단독 서버에 끄투 서버를 돌리고 있었습니다. 그런데 서버를 하나 추가로 만들었는데요, 데이터베이스 이름 관련 설정은 찾을 수 있어 이름을 바꾸었지만 Redis 설정은 어디에도 찾아볼 수 없습니다. 같은 서버에서 2개의 Redis 인스턴스를 돌릴 수 없으면 Redis 기능이 담긴 스크립트를 완전히 삭제할 방법은 없나요?

**Comment by gameworld3340** [comment]
랭킹 버튼을 제거하세요..
