### ISSUE TITLE
클러스터링 관련

### ISSUE THREAD

**Issue by korharu** [JJoriping/KKuTu#159]
웹에서 서버 2개가 뜨는것까진 확인했습니다.
그런데 사람이 접속하면 이 오류가 뜨네요
ReplyError: ERR wrong number of arguments for 'set' command at parseError (C:\Users\Korharu\Desktop\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:193:12) at parseType (C:\Users\Korharu\Desktop\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:303:14)
해결 방법 없을까요...?
웹서버는 30포트를 사용하고 global.json의 메인포트는 10000, 20000 으로 설정했습니다.
클러스터링 하기전에는 잘되던 로그인이 안되더군요... Bad Request라고 뜨던데 어떻게 해결하나요?

**Comment by JJoriping** [comment]
제시된 오류는 Redis 데이터베이스를 이용하기 위한 질의문이 잘못되었다는 내용입니다. 구체적으로 어디서
 그런 질의문으로 오류를 일으켰는지는 호출 스택에서 끄투 코드(node_modules 폴더 밖)를 살펴봐야 알 수 있습니다.
