### ISSUE TITLE
OAuth 관련, Redis서버 관련 질문드립니다

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#160]
뭘 어떻게수정하여야 하나요?
그리고 소스는 어디서 구하죠
그리고 REdis서버 어떻게 하는지 알ㄹ려주세요

**Comment by kjbkjb1122** [comment]
소스는 [여기](https://github.com/JJoriping/KKuTu/archive/master.zip)
redis는 [여기](http://devbible.tistory.com/449)에서 다운 받아주세요

**Comment by TheRealTolspac** [comment]
프로그래밍 상식을 모르시면 때려치는 것이 낫습니다.
