### ISSUE TITLE
등록중 이건 어쩌죠?

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#161]
![image](https://user-images.githubusercontent.com/31878663/30766612-25aa00ca-a031-11e7-8012-f882e10ee06a.png)
http://happykkutu.kro.kr/kkutu-dHA6Ly9oYX.html 으로 가라는데 어케설정 하죠?

**Comment by hatty163** [comment]
...
KKuTu/Server/lib/Web/public에
kkutu-dHA6Ly9oYX.html 파일을 만드시고 내용에는 http://happykkutu.kro.kr 적으세요

**Comment by minesna** [comment]
새로운 서버네요 환영합니다

**Comment by gameworld3340** [comment]
@minesna 그런걸 왜 여기에...

**Comment by minesna** [comment]
@gameworld3340 환영인사를 하고싶었지만 연락할 길이 없었습니다 흐음

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
국어능력조차 의심되는 새끼들이 이런건 잘도 물어보네

국어부터 배우고와라 아가야~

**Comment by kjbkjb1122** [comment]
@SoManyIdiotsInKKuTuIssues 끄알못이 잘난착 하는 새끼가 이런건 잘 답변하네

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
@kjbkjb1122 으응?? 머라고?? 관리자페이지 조잡하다고 하는 병신새끼 말이라 잘 안들리는데?

**Comment by pprcYT** [comment]
?
