### ISSUE TITLE
휘장 아이템 만드는법

### ISSUE THREAD

**Issue by korharu** [JJoriping/KKuTu#163]
휘장 아이템 어떻게 만드나요...? DB 수정하는거같던데... 맞나요...?

**Comment by gameworld3340** [comment]
관리 페이지에서 상점 아이템 b1_gm 불러오시고 따라서 새로 만드시면 되요.

**Comment by korharu** [comment]
그룹은 어떻게 사용하는거죠? 그리고 이미지는 어떻게 적용하나요?

**Comment by gameworld3340** [comment]
제가 말한대로 b1_gm 불러오시면 어떻게 해야할건지 대충 감이 오실텐데..
사진은 서버 파일 검색 'b1_gm'하시면 나오고 그 폴더에 ID를 적으시면되요

**Comment by korharu** [comment]
감사합니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
국어사전 어떻게 읽나요..? 소리내서 읽는거같던데.. 맞나요..?

**Comment by korharu** [comment]
그걸 왜 여기서 물으시는지?
@SoManyIdiotsInKKuTuIssues
