### ISSUE TITLE
휘장에 칭호 넣는법

### ISSUE THREAD

**Issue by korharu** [JJoriping/KKuTu#164]
b1_wd 라는 휘장이 있는데 채팅 치면 [단어] 라는 칭호를 넣고싶습니다... 어떻게 하나요...?

**Comment by minesna** [comment]
body.js와 in_game_kkutu_shop.css 를 수정해보세요

**Comment by korharu** [comment]
in_game_kkutu.min.js도 건드려야하네요 감사합니다!
