### ISSUE TITLE
끄투 서버 분리에 관련된 질문

### ISSUE THREAD

**Issue by small-sunshines** [JJoriping/KKuTu#165]
제가 직접 몇몇부분의 소스를 손봐서 끄투 서버를 분리시켜놨습니다.

자세한 정보는 다음 3개의 저장소로 가신다면 확실하게 확인이 가능할 것이라 봅니다.
[웹서버](https://github.com/small-sunshines/kkutu-web)
[게임서버](https://github.com/small-sunshines/kkutu-game)
[라이브러리](https://github.com/small-sunshines/kkutu-lib)

1. 위 저장소가 라이선스 등의 문제가 있는지 및
2. 추후 배포되는 끄투도 저런식으로 분할이 가능한 구조가 되게끔 코드변경의 계획이 있으신지

에 대한 답변 부탁드립니다.

**Comment by JJoriping** [comment]
안녕하세요, 끄투 소스 코드에 관심을 가져 주어 감사합니다. 라이선스 관련한 문제는 없습니다만, 소스 코드 개편은 많은 시간이 걸리는 만큼 학기 중에는 염두에만 두고 있고 아직 착수한 상황은 아닙니다.
