### ISSUE TITLE
kkutu.kr에서 플레이어 수가 확인불가로 표현됩니다.

### ISSUE THREAD

**Issue by gameworld3340** [JJoriping/KKuTu#167]
kkutu.kr에서 트와이스 끄투가 웹서버와 게임서버가 모두 켜저있고 게임도 플레이가 가능한데
kkutu.kr에서는 확인 불가로 표시가 됩니다.
http://twutu.semin.xyz/servers도 확인해봤습니다만 
{"list":[null,null],"max":400}로 표시가됩니다.
무슨 오류인지 아시는분께서는 답변 부탁드리겠습니다 !

**Comment by gameworld3340** [comment]
해결됬습니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
지 게임서버 문제가지고 왜 여기다가 이슈를 여는지

남탓하기전에 자신부터 돌아봅시다~
