### ISSUE TITLE
kkutu.kr 서버 리스트 관련 이슈

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#168]
현재 상위노출 ''이펙트''가 심각한 상황입니다. 뒤로 갈수록 서버들이 인원이 줄어들고, 유저들이 앞에 2-3 서버만 들어가는 상황입니다. 아무래도 핑(응답속도)순이라던지, 접속자 순이라든지 자동 정렬되어 공평해 졌으면 합니다.

**Comment by gameworld3340** [comment]
인정합니다 ㅠ
