### ISSUE TITLE
SSL 적용 이후 Socket hang up 에러

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#169]
웹 서버에 SSL 인증서를 적용한 이후, 게임 서버는 정상적으로 켜지나 웹 서버와 연결될 때 Socket hang up 에러가 뜨면서 연결되지 않습니다. 다른 이슈도 참조해 보았으나 대채로 어떻게 해야 하는지 감이 오지 않아서 이슈를 남겨봅니다. 어떻게 해야 할까요?

**Comment by small-sunshines** [comment]
흠.. 예상되는 에러로는 보안 이슈로 인해서 ws:// 로는 연결이 되지 않는 것 같습니다.

게임서버에도 SSL을 적용하셔서 wss:// 연결이 가능하게끔 수정하신 뒤, kkutu.pug 52라인의 ws:// 를 wss:// 로 수정하여 주시면 될 것 같습니다.

**Comment by hatty163** [comment]
흠...
`var options = {
  host: 'localhost',
  port: 443,
  ca: fs.readFileSync('ssl.ca-bundle'),
  key: fs.readFileSync('ssl.key'),
  cert: fs.readFileSync('ssl.crt')
};`
`https.createServer(options, Server).listen(443, function(){
  console.log("Https server listening on port " + 443);
});`

이렇게 웹 서버와 똑같은 소스를 넣었는데도 이러네요... 혹시 정확하게 어떻게 해야 하는지 알려주실 수 있나요?

**Comment by small-sunshines** [comment]
아.. 웹서버 어디엔가 게임서버와 연결하는 부분이 하나 있었급니다. 질문의 본제를 파악하지 못했군요.

아마 main.js 에 보시면 있을겁니다.

**Comment by hatty163** [comment]
onst.MAIN_PORTS.forEach(function(v, i){
	var KEY = process.env['WS_KEY'];
	
	gameServers[i] = new GameClient(KEY, `wss://127.0.0.2:${v}/${KEY}`);
});
function GameClient(id, url){
	var my = this;
	
	my.id = id;
	my.socket = new WS(url, { perMessageDeflate: false });
	
	my.send = function(type, data){
		if(!data) data = {};
		data.type = type;
		
		my.socket.send(JSON.stringify(data));
	};
	my.socket.on('open', function(){
		JLog.info(`Game server #${my.id} connected`);
	});
	my.socket.on('error', function(err){
		JLog.warn(`Game server #${my.id} has an error: ${err.toString()}`);
	});
	my.socket.on('close', function(code){
		JLog.error(`Game server #${my.id} closed: ${code}`);
		my.socket.removeAllListeners();
		delete my.socket;
	});
	my.socket.on('message', function(data){
		var _data = data;
		var i;
		
		data = JSON.parse(data);
		
		switch(data.type){
			case "seek":
				my.seek = data.value;
				break;
			case "narrate-friend":
				for(i in data.list){
					gameServers[i].send('narrate-friend', { id: data.id, s: data.s, stat: data.stat, list: data.list[i] });
				}
				break;
			default:
		}
	});
}
여기 말하시는건가요

**Comment by hatty163** [comment]
nginx reverseproxy로 성공적으로 열었습니다. 그런데, 서버를 들어가려고 하면 불러오는 중... 1에서 멈추고, DOM 탐색기로 로그를 보면
```in_game_kkutu.min.js:21 Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at h (https://xn--vz0b065d.xn--t60b56a/js/in_game_kkutu.min.js:21:30348)
    at Object.success (https://xn--vz0b065d.xn--t60b56a/js/in_game_kkutu.min.js:21:15736)
    at f (https://xn--vz0b065d.xn--t60b56a/js/jquery.js:19:18299)
    at Object.fireWith [as resolveWith] (https://xn--vz0b065d.xn--t60b56a/js/jquery.js:19:19085)
    at r (https://xn--vz0b065d.xn--t60b56a/js/jquery.js:21:16009)
    at XMLHttpRequest.r (https://xn--vz0b065d.xn--t60b56a/js/jquery.js:21:21631)
h @ in_game_kkutu.min.js:21
(anonymous) @ in_game_kkutu.min.js:21
f @ jquery.js:19
fireWith @ jquery.js:19
r @ jquery.js:21
r @ jquery.js:21
XMLHttpRequest.send (async)
send @ jquery.js:21
ajax @ jquery.js:21
st.(anonymous function) @ jquery.js:21
processShop @ in_game_kkutu.min.js:21
(anonymous) @ in_game_kkutu.min.js:22
e @ in_game_kkutu.min.js:21
(anonymous) @ in_game_kkutu.min.js:21```
라고 뜹니다. 어떻게 하죠?

**Comment by small-sunshines** [comment]
위 오류는 보안 이슈(?)로 인하여 https 로 접속된 상태에선 ws 로는 접속이 불가능한 경우입니다. kkutu.pug 및 m_kkutu.pug 에서 #url 을 찾으셔서 ws:// 를 wss:// 로 바꿔주시면 됩니다.

**Comment by hatty163** [comment]
```var https = require("https");

var fs = require("fs");

var options = {

ca: fs.readFileSync('ssl.ca-bundle'),

key: fs.readFileSync('ssl.key'),

cert: fs.readFileSync('ssl.crt')

};

이 형식으로 main.js에 소스를 추가하고 ws://를 wss://로 고쳤습니다. 아까처럼 무한로딩이 일어나진 않으나, 불러오는 중... 앞으로 1에서 서버와의 연결이 종료되었다고 뜹니다.

**Comment by small-sunshines** [comment]
혹시 pug 파일도 같이 처리해주셨나요?

kkutu.pug 파일 및 m_kkutu.pug 파일에
'''
span#URL= `ws://${locals.HOST}:${locals.PORT}/${locals._id}`
'''

라고 되어있는 부분이 있다면

'''
span#URL= `wss://${locals.HOST}:${locals.PORT}/${locals._id}`
'''

로 수정하신 뒤 개발자도구의 로그를 확인해보시면서 코멘트 부탁드립니다.

**Comment by hatty163** [comment]
수정하니
![image](https://user-images.githubusercontent.com/14357656/31112673-11034ad8-a850-11e7-9214-ede2b6648a01.png)
이렇게 뜨네요.

**Comment by small-sunshines** [comment]
게임서버 SSL 관련 문제군요.. 이것은 한번 패치방법을 내일즈음 내놓도록 하겠습니다.

**Comment by hatty163** [comment]
흠... 게임서버에 SSL을 달고 오니 이번엔
![image](https://user-images.githubusercontent.com/14357656/31113515-9c2fe0ae-a854-11e7-802e-20cee11cc116.png)
이렇게 뜨네요 ㅠ

**Comment by hatty163** [comment]
![image](https://user-images.githubusercontent.com/14357656/31114971-774a101e-a85b-11e7-8bfe-65cce455fe62.png)
더불어 이 오류도 뜨네요

**Comment by small-sunshines** [comment]
The port 20 is not allowed. 의 경우 20포트는 이미 다른 서비스에서 사용하도록 규약되어있는 포트이므로 저런 오류가 발생하는 것입니다.

두번째 ERR_CONNECTION_CLOSED 의 경우, 위의 오류로 인하여 자동으로 연결이 해제되는 오류로 보입니다.

제가 아는 바로는 2000번 이상의 포트부터 자유적으로 이용할 수 있는 포트로 알고있으며, 게임서버의 기본 포트를 2000번 이상으로 설정해주시기 바랍니다.

개인적으로는 8080부터 10 단위로 띄워서 설정하셨으면 합니다.

(예시: 0번서버 => 8080, 1번서버 => 8090, 2번서버 => 9000 ...)

**Comment by hatty163** [comment]
포트 에러는 해결되었습니다. 그러나, 아직도 이 에러가 뜨면서 로딩이 되지 않습니다.
![image](https://user-images.githubusercontent.com/14357656/31154631-69367d36-a8e3-11e7-9792-372e39f3387b.png)

**Comment by small-sunshines** [comment]
현재 HTTPS 대응코드가 삽입된 소스코드를 집에 도착해서 급하게 만든 뒤 차에서도 수정을 거듭하여 코드 통합 요청을 남겨놨습니다. 아직 확실히 검증이 되지 않은 코드입니다만, 현재 PR 요청이 되어있는 코드를 다운받으셔서 사용하셔도 됩니다.

**Comment by hatty163** [comment]
해결되었습니다. 감사합니다.
