### ISSUE TITLE
redis 관련 질문

### ISSUE THREAD

**Issue by gameworld3340** [JJoriping/KKuTu#170]
서버 호스팅을 변경하면서 데이터베이스는 모두 백업을 해서 적용을 시켰습니다만
redis는 어떻게 하는지 전혀 모르겠네요 redis 설치는 했습니다만 redis를 전에 쓰던걸로 쓸려면
어떻게 해야할지 질문 드립니다.

**Comment by small-sunshines** [comment]
Redis의 경우 캐싱을 위한 메모리기반 데이터베이스이므로 Redis에서 password 등의 설정 뒤, 끄투에서 Redis 관련 설정을 입력해주신 뒤 끄투 서버를 작동해주시면 됩니다.

PostgreSQL의 경우 데이터베이스를 백업해오셔야 하지만, Redis는 원래부터 캐싱을 위한 데이터베이스이므로 큰 상관이 없습니다.

**Comment by gameworld3340** [comment]
password를 어떻게 설정을 하는지 잘 모르겠네요..

**Comment by small-sunshines** [comment]
보통 Redis의 경우 내부에서만 사용하기 때문에 Redis 의 경우 password 설정이 없으며, 끄투에서도 Redis password 설정은 존재하지 않습니다만, 일부 개조를 통하면 Redis의 경우에도 password 설정이 가능합니다.

한마디로 정리하자면 Redis의 경우 password 설정이 당장은 필요하지 않습니다.

**Comment by gameworld3340** [comment]
그래서 다른곳으로 redis 데이터 같은걸 ㅇ따로 개조를 해야한다는 말씀이신가요 ?

**Comment by small-sunshines** [comment]
흠.. 조금 알기 쉽게 설명해드리자면,

현재 끄투에는 Redis 접속을 위한 password 를 설정하는 옵션은 존재하지 않습니다.
Redis 데이터를 옮길 때에 개조가 필요한 것이 아니라,
Redis에 접속할 때 사용할 password 를 입력할 옵션이 없다는 것입니다.

Redis 는 잠깐동안 필요한 데이터를 저장해 두는 곳이기 때문에 이전 서버에서의 데이터를 옮겨올 필요가 없습니다. 중요한 데이터들은 PostgreSQL에 존재하기 때문이죠.
