### ISSUE TITLE
구글 400오류

### ISSUE THREAD

**Issue by kjbkjb1122** [JJoriping/KKuTu#171]
![default](https://user-images.githubusercontent.com/25769512/31131241-87a634c2-a894-11e7-80d4-e53588577b35.PNG)
![1](https://user-images.githubusercontent.com/25769512/31131250-8d091e48-a894-11e7-8c37-99aa4e4719b0.PNG)
![2](https://user-images.githubusercontent.com/25769512/31131253-8e68e7a0-a894-11e7-9bde-71f5e37bd6c7.PNG)
![3](https://user-images.githubusercontent.com/25769512/31131254-8f8b2b48-a894-11e7-85d5-b24d7c25aac0.PNG)
**(중요한 부분은 가렸습니다.)**
저가 대충 해석하기로는 
'대상 도메인에 대한 로그인 힌트를 생성하기 위한 사용 권한이 거부되었습니다.'
라고 써있는데
도데체 왜 이러는 것일까요?
뭐라도 쓰다가 잘못한 건가, 뭐를 안 쓴건가 궁금하네요.
도메인은 kkutu.cf입니다.

**Comment by gameworld3340** [comment]
`Google Api ID`는 안쓰셔도 되구요
클라이언트 아이디를 `Google ID`부분에 클라이언트 보안 비밀을 `Google Secret`에 써주시면 됩니다.
(서버 리붓은 필수인건 아시겠죠..?)

**Comment by kjbkjb1122** [comment]
리붓은 당연히 하였죠
grunt작업도 했습니당^^~

**Comment by kjbkjb1122** [comment]
flash를 누르고 다시 setup을 하고 서버를 킨 결과, (혹시 몰라 redis도 켰음)
아직도 이럽니다.
`jauth.js` 와 `login.pug` 말고도 또 다른 것을 건드리거나
잘못된 것이 있나요?
분명 클라이언트 아이디와 클라이언트 보안 비밀을 복사하고 몇 번 흩어보아서 맞는 것을 보았습니다.'대상 도메인에 대한 로그인 힌트를 생성하기 위한 사용 권한이 거부되었습니다.'
이라는 상태의 메시지를 뿜는 것을 보아 무슨 권한을 주어야 하나요???

**Comment by gameworld3340** [comment]
구글 로그인의 경우는 다른건 수정 안해도 됩니다.
디스코드 게임의세상#8357 친추해주셔서 DM 해주시면 자세하게 설명해드릴 수 있을것 같습니다!

**Comment by gameworld3340** [comment]
아 그리고 방금 kkutu.cf에 들어가서 구글 로그인 확인을 해본 결과
redirect 주소가 175.120.15.100으로 표시가 되어있습니다.
한번 확인해보세요
![image](https://user-images.githubusercontent.com/30207346/31178100-01fe7a0e-a953-11e7-8b6a-828698e276ea.png)

**Comment by korharu** [comment]
구글에서 승인된 리디렉션 URL을 자신의 도메인으로 수정해보세요 근데 왜 리디렉션 주소가 끄투 박물관이죠...?

**Comment by kjbkjb1122** [comment]
승인된 원본 자바스크립트 링크와 리디렉션 URL을 둘 다 kkutuscreen.tk:80(임시로 바꿈)으로 하였습니다.
그런데 그거와 상관없이 F12를 눌러 보니까
![1](https://user-images.githubusercontent.com/25769512/31304348-753bc892-ab5a-11e7-9b73-8e1e73d18b99.PNG)

HTTP400: BAD REQUEST - 잘못된 구문으로 인해 서버에서 요청을 처리할 수 없습니다. 라고 뜨네요.

내용은
(XHR)GET - https://accounts.google.com/o/oauth2/auth?redirect_uri=storagerelay%3A%2F%2Fhttp%2F175.120.15.100%3Fid%3Dauth178724&response_type=permission id_token&scope=email profile openid https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fplus.login&openid.realm=&client_id=808398003864-glb2fp595b44o34inovtamgh9rs6258f.apps.googleusercontent.com&ss_domain=http%3A%2F%2F175.120.15.100&fetch_basic_profile=true&gsiwebsdk=2

여기 중에 빨간색으로 쓰인 글씨(오류와 관련됨)는
HTTP400 : BAD REQUEST - 잘못된 구문으로 인해 서버에서 요청을 처리할 수 없습니다.
(XHR)GET
(내용 중)id_token&scope=email profile openid https%3A%2F%2F

**Comment by gameworld3340** [comment]
https://accounts.google.com/o/oauth2/auth?redirect_uri=storagerelay%3A%2F%2Fhttp%2F175.120.15.100%3Fid%3Dauth178724&response_type=permission id_token&scope=email profile openid 이 주소면 아직도 redirect 주소가 175.120.15.100로 되어있는건데요; 그리고 포트는 main.js에서 포트를 건드리신게 없다면 안써주셔도 됩니다

**Comment by gameworld3340** [comment]
![image](https://user-images.githubusercontent.com/30207346/31304527-d72cd8f4-ab5d-11e7-9079-c30cc74c7c38.png)
현재 운영하고 있는 서버에서 이런식으로 써서 사용하고 있는데 로그인 오류가 발생하지 않습니다.

**Comment by korharu** [comment]
끄투 스크립트쪽 수정해보셨나요 확인해보세요

**Comment by gameworld3340** [comment]
@korharu 구글 로그인은 jauth.js만 수정하면 되는걸로 압니다
(login.pug는 상관이 없어요)

**Comment by korharu** [comment]
@gameworld3340 전 pug를 말한적이...

**Comment by gameworld3340** [comment]
@korharu 진지충..

**Comment by kjbkjb1122** [comment]
도메인에 문제가 있었군요 그래서 kkutuscreen.kro.kr에는 또 다른 오류가 뜨네용..  님처럼 .xyz나 .com을 마련해야겠어용

**Comment by gameworld3340** [comment]
무슨소리신지 kkutuscreen.kro까지만 읽는게 아니라 그것만 보이는겁니다
인식은 잘 됩니다

**Comment by kjbkjb1122** [comment]
400. That’s an error.

Error: redirect_uri_mismatch
The JavaScript origin in the request, http://kkutuscreen.kro.kr, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/741044124082-dg9gvt93hv8af4eljfajhvj909v61ebk.apps.googleusercontent.com?project=741044124082 to update the authorized JavaScript origins.

저기 링크에서는 api console에서 업데이트를 하라는데
원본 자바 스크립트랑 리디렉션도 https://kkutuscreen.kro.kr로 해놨다만 안되네용....

**Comment by kjbkjb1122** [comment]
해결이 되었습니다.
감사합니다~~

**Comment by kkutu-hooss** [comment]
당신도 저랑 같은 비쥬얼 코드를 쓰네요
