### ISSUE TITLE
소유권 인증이 되지 않습니다.

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#173]
소유권을 인증하라 해서,
![image](https://user-images.githubusercontent.com/14357656/31164829-b3b9aec4-a923-11e7-96e2-36aa5506fdb3.png)
파일을 업로드 하고, 정상 접속 확인도 되었으나,
![image](https://user-images.githubusercontent.com/14357656/31164863-d0835988-a923-11e7-946b-d00586e24cad.png)
이렇게 소유권 인증 화면만 계속 뜹니다. 또한, 등록 때 https://끄투.닷넷으로 등록해주시면 감사하겠습니다.

**Comment by hatty163** [comment]
![image](https://user-images.githubusercontent.com/14357656/31164914-f490326a-a923-11e7-9ecf-f2b0eef45eda.png)
이렇게 정상접속도 됩니다.

**Comment by gameworld3340** [comment]
https://twutu.xyz도 소유권 인증이 되지 않습니다아..

**Comment by ment12da** [comment]
https://nettu.teamneon.org 도 소유권 인증이 불가능합니다.

**Comment by gameworld3340** [comment]
현재 새로 등록하시면 가능합니다
