### ISSUE TITLE
DB 를 생성하면 에러가 뜹니다

### ISSUE THREAD

**Issue by cheatful57** [JJoriping/KKuTu#174]
C:\Program Files\PostgreSQL\9.6\bin>createdb  postgres main
C:\Program Files\PostgreSQL\9.6\bin>createdb -U postgres main

createdb: template1 데이터베이스에 연결 할 수 없음: 서버에 연결할 수 없음: Connection refused (0x0000274D/10061)
        "localhost" (::1) 호스트에 서버가 가동 중인지,
        5432 포트로 TCP/IP 연결이 가능한지 살펴보십시오.
서버에 연결할 수 없음: Connection refused (0x0000274D/10061)
        "localhost" (127.0.0.1) 호스트에 서버가 가동 중인지,
        5432 포트로 TCP/IP 연결이 가능한지 살펴보십시오.

**Comment by Kim-Daewoon** [comment]
`createdb -U postgres main` 로 시도해보세요.

**Comment by kjbkjb1122** [comment]
createdb -U "postgres" "main" 이거 입니다.
따음표를 붙혀주셔야 되고여
psql -U "postgres" -d "main" -f "(SQL 파일 경로)"
같은 경우에는
kkutu-master에 있는 db.sql을 경로에 포함하면 됩니다.
예 : C:\Users\administrator\Desktop\KKuTu-master

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
이새끼 분명히 PostgreSQL 설치할때 포트에 5432 말고 다른거 넣었다 내가봄

**Comment by kjbkjb1122** [comment]
포트는 global.json에서 포트 바꿔주면 별 상관은 없어요.
그리고 문제 해결되셨으면 닫아주시기 바랍니다.

**Comment by gameworld3340** [comment]
global.json에서의 포트랑 PostgreSQL의 포트는 다릅니다
