### ISSUE TITLE
오류 페이지를 나타나게 할려면 어떻게 해야할까요?

### ISSUE THREAD

**Issue by gameworld3340** [JJoriping/KKuTu#175]
404, 401 등의 오류 페이지를 나타나게 할 수 있는 방법을 알고싶습니다.
인터넷에 검색해봐도 잘 모르겠네요

**Comment by kjbkjb1122** [comment]
무슨 오류 페이지인지는 모르겠네용
구체적으로 다시 물어주시기 바랍니다.

**Comment by gameworld3340** [comment]
404, 401 등의 오류페이지라고 말해드렸습니다만

**Comment by pkpai0926** [comment]
이런 글이 있네요.
참고해보세요.
https://www.hacksparrow.com/express-js-custom-error-pages-404-and-500.html

**Comment by gameworld3340** [comment]
해결했습니다.
