### ISSUE TITLE
프리서버에 서버추가가 안됩니다.

### ISSUE THREAD

**Issue by vkdlfl** [JJoriping/KKuTu#176]
저작권 관련 정보 양식 ko_KR en_US , layout m_layout 모두 다 설정 했는데 "홈페이지 또는 게임 페이지의 저작권 관련 내용 표시가 조건에 맞지 않습니다." 라고 뜨는데 어떻게 해야되나요?

**Comment by gameworld3340** [comment]
ko_KR을 어떻게 작성하셨는지 알려주셔야 확인을 합니다

**Comment by vkdlfl** [comment]
{
	"GLOBAL": {
		"GPL": "<div style='color: #666;'>글자로 놀자! 끄투 온라인 Copyright (C) 2017 파이리(jsm954u@mgmail.com)<br>이 프로그램은 제품에 대한 어떠한 형태의 보증도 제공되지 않습니다.<br>이 프로그램은 자유 소프트웨어이며 배포 규정을 만족시키는 조건 아래 자유롭게 재배포할 수 있습니다.<br>이에 대한 자세한 사항은 본 프로그램의 구현을 담은 다음 레포지토리에서 확인하십시오: <a target='_blank'href='https://github.com/vkdlfl/LifeKKuTu'>https://github.com/vkdlfl/LifeKKuTu</a></div>",
라고 썻습니다

**Comment by JJoriping** [comment]
`target='_blank'`와 `href=…` 사이에 공백을 하나 추가해 주세요.

**Comment by KKuTuIssueFuck** [comment]
븅신아 그거 하나 못하냐 쯧쯧
