### ISSUE TITLE
GWALLI에서 특수 문자로 단어를 생성하면 삭제가 되지 않습니다.(예를 들면 % ? 이런거)

### ISSUE THREAD

**Issue by shj0303** [JJoriping/KKuTu#177]
제가 실수로 ? 단어를 추가했는데 GWALLI에서 삭제가 되질 않네요. 어떻게 해야할까요?

**Comment by gameworld3340** [comment]
단어를 불러오시고 X를 누르시고 적용을 누르세요

**Comment by shj0303** [comment]
불러오기 해도 아예 안뜹니다

**Comment by gameworld3340** [comment]
그럼 단어가 없는것 아닐까요?

**Comment by shj0303** [comment]
하지만 게임에서는 사용이 됩니다. 어떻게 해야하죠?

**Comment by KKuTuIssueFuck** [comment]
데이터베이스를 초기화 하세요병신새끼야 그러면서 끄투서버를 어떻게 연다는거야 개병신새끼가

**Comment by shj0303** [comment]
어휴 급식냄새 ㄷㄷ
