### ISSUE TITLE
단어 분류 추가

### ISSUE THREAD

**Issue by KORraimi** [JJoriping/KKuTu#178]
단어 분류 추가를 못하겠습니다. KO_KR 파일에 "theme_NAM": "<이름>" 으로 등록을 했는데 그러면 서버가 오류를 내뿜꼬 죽습니다. 방법을 좀 알려주시면 감사하겟습니당.

**Comment by pkpai0926** [comment]
`"theme_NAM": "<이름>" `뒤에 `,` 붙이셨나요? `"theme_NAM": "<이름>" ,` 이런 식이어야 합니다.

**Comment by KORraimi** [comment]
아하 해볼께여

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
제발 리드미나 이미 열린 이슈부터 읽고 모르겠으면 새로 달아라

110번 버스 어떻게 타요? > 330번 정류장 가시면 됩니다 > 330번 정류장 어떻게 가요? > 롯데마트 끼고 우회전하시면 있습니다 > 롯데마트가 뭔데요?

병신

**Comment by KORraimi** [comment]
꼭 ㅂㅅ이라고 욕하는 새끼가 있어요 ㅡㅡ 데이터베이스 내 구조를 몰라서 올렸더만 ㅅㅂ 열린이슈 다읽어도 원하는 방법 안나와서 질문했더만 꼭 욕하는 ㅂㅅ이 있네 ㅋㅋ 야 애미뒤진놈나 자살하자

**Comment by KORraimi** [comment]
아니면 방법을 알려주던가 초면에 욕질하고 지랄하넼ㅋㅋㅋ 끄투도 몬여는 초딩새끼는 쨔저서 옵치나 하러가라

**Comment by KORraimi** [comment]
욕설때문에 기분 잡치고 끄투 여는것도 포기했습니다. 닫을께요

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
하이고 씨벌 무서워 죽겠네 ㅎ 이슈 댓글 하나만으로 상대방 나이와 직업 판독해버리기~ 궁예질 지려버리기~ ㅇㅈ? (궁예: 누가 지금 인정 소리를 내었느냐? 나도 인정 좀 하자)

**Comment by kjbkjb1122** [comment]
@SoManyIdiotsInKKuTuIssues ㄴㅇㅈ readme에 언급 된 거 없는데요;;; 알고좀 말하죠
