### ISSUE TITLE
GM휘장 얻는 방법

### ISSUE THREAD

**Issue by kjbkjb1122** [JJoriping/KKuTu#179]
`Server\lib\sub\global.json`파일을 수정하고 성공적으로 GM권한을 얻었습니다.
그 다음으로 휘장을 얻으려 하는데
psql로 `UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '116048762675434286450';`을 치라는
이슈를 보고 윈도우 검색창에 나오는 psql를 실행 후,
`UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '116048762675434286450';`를 쳤다만
다음에는 데이터베이스 [postgres]라 뜨네요
예시라도 알려주시면 감사하겠습니다.

**Comment by gameworld3340** [comment]
편하게 관리 페이지에서 하세요

**Comment by kjbkjb1122** [comment]
관리 페이지에서 하고 싶은데 모르는 내용들이 대다수입니다만..

**Comment by pkpai0926** [comment]
PostgreSQL과 psql을 처음 써 보시는 군요..
psql 실행 후, 먼저 DB 서버에 접속하기 위해 서버 주소와 포트, DB명, 접속할 계정명과 비밀번호를 입력한 다음 `# UPDATE users SET box = '{"b1_gm":1}' WHERE _id = 'XXXXXXXXXXX';`를 입력하셔야 합니다.

**Comment by kjbkjb1122** [comment]
![a](https://user-images.githubusercontent.com/25769512/31427294-bf205870-aea1-11e7-9461-c5328e79b05b.PNG)
이렇게 뜨네요
포트는 main.js에서 다룬 것이 없습니다.

**Comment by gameworld3340** [comment]
관리페이지가 조잡하다뇨.. 잘 모르시는분께는 관리 페이지가 제일 좋습니다
조금만 알아도 관리 페이지는 쉽게 다룰 수 있습니다
(그리고 데이터베이스는 main 포트는 5432 유저네임은 postgres인걸로 알고있습니다)

**Comment by kjbkjb1122** [comment]
명령문을 풀어서 해결해 보겠습니다. 감사해요

**Comment by kjbkjb1122** [comment]
psql를 포기하고 관리자페이지로 넘어오겠습니다.
관리페이지에서 두루 보았지만 뭐가 뭔지 모르겠습니다 :(
관리페이지에서 어떻게 해야할 지 알려주실 수 있을까요? (정말 죄송합니다;;;)

**Comment by gameworld3340** [comment]
암호에는` global.json`에서 썻던 `PASS`를 적어주세요.
테이블에는 `ko` 혹은 `en`을 적어주시면 되구요

그 다음부터는 조금만 봐도 알 수 있습니다

**Comment by kjbkjb1122** [comment]
오 되었습니다!
