### ISSUE TITLE
두 가지 오류입니다.

### ISSUE THREAD

**Issue by kjbkjb1122** [JJoriping/KKuTu#180]
1번째 모바일에 상점 기능이 안 뜹니다
2번째 자신의 프로필 관리에 들어가지지 않습니다.

**Comment by gameworld3340** [comment]
1. 모바일은 상점이 월래 안 뜹니다
2. 로그인을 했다면 뜰수밖에 없습니다
그리고 이슈를 너무 막 쓰지말아주셨으면 좋겠어요 ㅠㅠ..

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
정작 지 뚝배기에 치명타 두번쳐맞은건 모르고있음

배울 거 다 배우고 열라고 좀 씨발 애새끼들이 오픈소스로 풀어놨더니만 마인크래프트 서버인줄 알아요 ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kjbkjb1122** [comment]
@SoManyIdiotsInKKuTuIssues 끄알못+깃알못이 자기가 잘났다고 욕까지 하여 알리고 싶었음? ㅉㅉ
