### ISSUE TITLE
휘장에다가 칭호 붙이기

### ISSUE THREAD

**Issue by kjbkjb1122** [JJoriping/KKuTu#181]
다른 이슈를 봤는데 어떻게 수정해야할지를 몰라서 이렇게 씁니다.

**Comment by gameworld3340** [comment]
이슈 검색하면 나오는데 꼭 이렇게 새로 이슈를 작성할 필요가 있을까요?
진짜 질문을 하실거면 뭘 찾아보기라도 하시고 질문을 남기시면 좋을것같네요

**Comment by kjbkjb1122** [comment]
이 이슈를 보고 만든 겁니다.
저 3파일이 너무 길어서 뭐가 뭔지 몰라서 이슈를 남긴 겁니다.

**Comment by gameworld3340** [comment]
body.js는 필요없구요
in_game_kkutu_shop.css에서 이미 칭호가 적용되어있는 `b1_gm`만 검색해도 압니다
in_game_kkutu_min.js에서 이미 칭호가 적용되어있는 `b1_gm`만 검색해도 압니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
서버 css, js 파일에 대한 기본적인 이해조차 부족한 사람이 끄투서버 열어보겠다고 깝치는 꼴 보니 우습기만 하다

눈삔거 아니면 제발 찾아보고 질문해라

**Comment by BasixKOR** [comment]
최소한 이미 있는 이슈에 코멘트 다세요.

**Comment by kjbkjb1122** [comment]
@SoManyIdiotsInKKuTuIssues 부족한 점 저격 감사드립니다~

**Comment by minesna** [comment]
@kjbkjb1122 좋으면으로 바라보는 모습 너무 좋습니다..

**Comment by KKuTuIssueFuck** [comment]
@kjbkjb1122 병신아 계속 질문만 할거면 이슈에 답변을 왜하냐 그냥 지도 모르면서 다른사람한테 지새끼도 모르는거 답변하는 병신새끼가
