### ISSUE TITLE
여기서 욕하는 사람들 어떻게 못합니까?

### ISSUE THREAD

**Issue by KORraimi** [JJoriping/KKuTu#182]
SoManyIdiotsInKKuTuIssues
이분이 다짜고짜 들어와서 욕질하는데ㅡㅡ 신고기능 없나요?

**Comment by BasixKOR** [comment]
그게 끄투 문제인가요? 아니라면 이슈 닫아주세요. 관련 없는 invaild 이슈입니다.

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
아이고 이게 누구시당가 ㅋㅋㅋ 이슈 댓글만 보고도 상대방의 나이와 직업을 때려맞히신다는 [[그새끼]] 아니신가 ㅋㅋㅋ 이 닦고 발 씻고 자라 아가야

**Comment by SkyLightQP** [comment]
여기는 끄투에 관련된 버그, 건의 등등을 올리는 곳입니다.
이런 글은 자제하는게 좋지 않을까 싶네요 :(

**Comment by pkpai0926** [comment]
메일 폭탄 오니까 이제 싸우지 마세요.

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
@pkpai0926 메일폭탄은 네이버에 108배할 부분이지만 저는 끄투 이슈에 오는 끊임없는 등신새끼들을 보다못해 털고있는것이니 대자대비하신 부처님의 마음으로 양해때려주시면 삼가 아리가또 고자이마스 (아이마스 아님 ㅎ) 인 부분입니다 부처님 착한 심장도둑 ㅇㅈ? (부처: 나무아미타불 인정음보살 땅땅땅)

**Comment by minesna** [comment]
와 엄청 달렸네

**Comment by minesna** [comment]
@SoManyIdiotsInKKuTuIssues 그만 해주세요

**Comment by KORraimi** [comment]
그러면SoManyIdiotsInKKuTuIssues님, 제가 올리신 이슈에 대함 해결법을 알려 주시죠? 여긴 끄투 질문하는곳인데? 그렇게 시비만 터시지 마시고요~

**Comment by BasixKOR** [comment]
질문하는 곳 아닙니다. 끄투 자체의 문제(이슈)를 트래킹하는 공간입니다.

용도부터 잘못 알고 계셨군요.

**Comment by KORraimi** [comment]
@SoManyIdiotsInKKuTuIssues 진짜로 저분이 제 이슈창에서 욕만 안했으면 이일 없을텐데말이죠. 저만 꼭집어 공격하는것도 아니고

**Comment by BasixKOR** [comment]
서버 자체에 대한 지식을 여기서 계속 물어보는 일이 사실 한 두번이었습니까? 구글 검색 하나로 해결될 일을 여기서 질문하는 것도 한 두번이었나요? 전 이 상황이 아주 이상하다고 보이지는 않는데요.

**Comment by KORraimi** [comment]
@BasixKOR 저기서 말한 질문은 기술적 문제(technical Issue)입니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
니가올린 이슈가 뭔문제인지는 알거없고 구문하나 틀린걸 못알아먹어서 개발자한테 질문하는건 개븅신이냐 뭐하는새끼냐 자칭 개발자라는 새끼가 구문하나 틀린거 못찾아서 직접 질문때리누? 그냥 편하게 때려치우고 마인크래프트 1.5.2 비정품서버나 열어라

**Comment by BasixKOR** [comment]
끄투의 기술적 문제가 아니라 당신이 모르는 문제 아니었나요?

**Comment by minesna** [comment]
제발 메일이.....

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
하이고 쒸이벌~ technical issues도 아는분이 syntax error를 모름? 철자다이죠부?

**Comment by KORraimi** [comment]
그리고 구굴에 " 끄투 단어 분류 추가하기" 치면 뭐가 나옵니까? 네이버 블로그에 뭐 친절하게 설명이라도 되있나요?

**Comment by BasixKOR** [comment]
postgresql 치실 생각은 해보셨나요? 소스코드 읽어 보셨나요?

**Comment by Kim-Daewoon** [comment]
끄투 단어 분류 추가는 소스코드를 정독해본다면 충분히 할 수 있습니다.
또한 해당 이슈를 보아하니 단순한 JSON syntax error인것 같습니다. 작성자분께서 JSON 문법에 대해 잘 알지 못하여 생긴 문제이니 딱히 이상한 점은 없다고 봅니다.

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
으따 마 행님요 이거 상이라도 드려야겠구마잉

아 물론 상은 느이집 네덕상 ㅎ

**Comment by KORraimi** [comment]
아이고 쒸이벌~ @SoManyIdiotsInKKuTuIssues님^^ 
kakaotalk193@gmail.com 으로 메일하세요^^ 불만 있으시면^^

**Comment by KORraimi** [comment]
@Kim-Daewoon 해당 이슈는 pkpai님이 다신거 보고 해결 했습니다

**Comment by pkpai0926** [comment]
그럼 close하세요

**Comment by BasixKOR** [comment]
메일로 인해 불편함을 드려 죄송합니다. 혹여 GitHub에서 직접 Unsubscribe해주시겠습니까? 정말 죄송합니다.

**Comment by KORraimi** [comment]
해결도 한 이슈 안닫고 나두었더만 욕만 달리고 좀 실망했었습니다

**Comment by BasixKOR** [comment]
어.. 해결한 이슈를 안 닫았다는 말씀이시라면, 그것도 문제 아닙니까?

**Comment by KORraimi** [comment]
@BasixKOR 넵 좋은저녁 보네세요 죄송합니다

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
비융신 지잘못인걸 왜 나한테 쌩지랄이신지

난 내 개인정보 까면서 느새끼랑 대화할 의사가 없습니다^^

**Comment by KORraimi** [comment]
알림껐으니 혼자 지랄발광 하시고요 그럼 전 다시 본업하러 가보겠습니다^^

**Comment by KORraimi** [comment]
물론 더달리면 보는 사람들 기분도 나빠지니깐 닫아놓고^^

**Comment by BasixKOR** [comment]
@KORraimi 마침 오신 김에, 본인의 이슈로 인해 다른 분에게 피해가 간다는 점 분명히 인지해주시고요. 다음에는 제발 관련 검색어 검색하시고 소스코드 분석도 해보세요.

**Comment by minesna** [comment]
@Kim-Daewoon json 저기 싸우는데 .,,

**Comment by BasixKOR** [comment]
안녕히 계세요!

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
푸하하하하하하하하

**Comment by BasixKOR** [comment]
* 이 이슈로 인하여 이 저장소를 Watch 하고 계신 분들께 정말 죄송합니다.

**Comment by KKuTuIssueFuck** [comment]
ㅇㅇ 어떻게 못함 병신아
