### ISSUE TITLE
회원가입 만들기

### ISSUE THREAD

**Issue by alanimdeo** [JJoriping/KKuTu#183]
1. 친구들끼리 끄투 서버를 열어서 게임을 하려는데요, 소셜 아이디로 로그인 이외에 아이디로 회원 가입을 해서 할 순 없나요? 

2. 관리 페이지는 어떻게 들어가는건가요?

**Comment by yunho0508** [comment]
1. 직접 구현하셔야 될듯 합니다.

2. 자신의 서버 주소/gwalli

2번은 닫힌 이슈 조금만 찾아봐도 아실 수 있으신건대...

**Comment by kjbkjb1122** [comment]
1번만 답변 드릴께요
https://github.com/zacharski/supersearchclient
를 다운 받아서 적절히 활용해보세요.

**Comment by small-sunshines** [comment]
1번은 직접 구현하셔야 합니다만, 제가 PR넣어둔 Passport 를 사용하는 코드를 살펴보신 뒤, Passport 로 로컬로그인을 구현하는 것을 보시면서 만드신다면 조금 수월하실것이라 봅니다만,

Pug 및 Express.js 를 사용하실 수 있는 능력이 있으시다면 수정을 하시는 것을 추천드리는 바입니다.

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
일단 리드미나 다른 이슈 읽기만 해도 알 수 있는 관리자페이지 접속방법 모른다고 떼기장쓰는새끼는 죽었다 깨어나도 절대 못함

**Comment by kjbkjb1122** [comment]
small님 처럼 하실 꺼면 #1도 읽는 것도 좋겠습니다.

**Comment by KKuTuIssueFuck** [comment]
@kjbkjb1122 #1 이슈를 왜 읽니 병신아 ㅉㅉ
passport가 뭔지나 아시나 니같은 새끼는 뭔지도 모르면서 말하는게 제일 꼴보기싫어

**Comment by JJoriping** [comment]
완전한 답변은 아니지만 이슈 #116 을 참고해 보세요.
