### ISSUE TITLE
상점에 gif 파일을 넣었는데, 모레미와 배경이 보이지 않습니다.

### ISSUE THREAD

**Issue by yangpa2449** [JJoriping/KKuTu#184]
상점에 아이템 추가를 연습하던 도중, gif도 된다는 사실을 알게 되었습니다.
저희 끄투 디자이너분이 제공해주신 gif 파일을 적용해 보았는데, gif는 정상적으로 작동하는데 적용하면 모레미가 보이지 않고 흰 색 바탕으로 바뀌고 모레미의 형체가 사라집니다.

어떠한 이유인지는 잘 모르겠습니다. gwalli에서 "gif":true도 넣었습니다.
파일의 문제인지, 끄투 내의 gif를 넣을때 더 해야되는 무엇인가가 있는지 알려주시면 감사하겠습니다.

감사합니다.

**Comment by KKuTuIssueFuck** [comment]
이 새끼 `img/kkutu/moremi`에 gif 파일 넣는거 봤다

**Comment by yangpa2449** [comment]
질문을 했으면 답변을 하시던가요. 그냥 선시 터시려고 하시는것 같은데 모르시면 답변 달지 마세요.

**Comment by KKuTuIssueFuck** [comment]
으응 질문한적 없어버리고  ^^

**Comment by JJoriping** [comment]
gif 파일의 배경 부분이 투명(RGBA 0x00000000)인지 확인해 보세요.
