### ISSUE TITLE
run.bat에서 오류가 뜹니다.

### ISSUE THREAD

**Issue by Eeclipse** [JJoriping/KKuTu#185]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.3.0
3 info using node@v8.2.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle kkutu-server@2.5.0~prestart: kkutu-server@2.5.0
6 info lifecycle kkutu-server@2.5.0~start: kkutu-server@2.5.0
7 verbose lifecycle kkutu-server@2.5.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle kkutu-server@2.5.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Navy\Documents\RYFreeKKutuSV\KKuTu-master\Server\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Java\jdk1.8.0_111\bin;C:\Users\Navy\AppData\Roaming\.minecraft\.minecraft\saves;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Users\Navy\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Navy\AppData\Local\Programs\Python\Python36-32\;C:\Users\Navy\AppData\Local\Microsoft\WindowsApps;C:\Users\Navy\AppData\Roaming\npm
9 verbose lifecycle kkutu-server@2.5.0~start: CWD: C:\Users\Navy\Documents\RYFreeKKutuSV\KKuTu-master\Server
10 silly lifecycle kkutu-server@2.5.0~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle kkutu-server@2.5.0~start: Returned: code: 1  signal: null
12 info lifecycle kkutu-server@2.5.0~start: Failed to exec start script
13 verbose stack Error: kkutu-server@2.5.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:921:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid kkutu-server@2.5.0
15 verbose cwd C:\Users\Navy\Documents\RYFreeKKutuSV\KKuTu-master\Server
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.2.1
19 verbose npm  v5.3.0
20 error code ELIFECYCLE
21 error errno 1
22 error kkutu-server@2.5.0 start: `electron .`
22 error Exit status 1
23 error Failed at the kkutu-server@2.5.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

이렇게 오류가 뜹니다.. 어떻게 해야하나요

**Comment by kjbkjb1122** [comment]
node.js문제는 없어보이고
내 문서에 두신 것 같네요.
바탕화면으로 옮기신 다음에 데이터베이스 입력 작업을 다시 해보세요

**Comment by KKuTuIssueFuck** [comment]
@kjbkjb1122 으응 ^^ 데이터베이스 입력을 왜 다시해 그냥 db.sql에 있던 데이터베이스를 main 이라는 이름의 데이터베이스에 넣어놨으니까 안해도되 병신아 에휴 ^^ 내 문서도 상관 없어요 아는척 겁나 잘하는님아

**Comment by KKuTuIssueFuck** [comment]
.

**Comment by yaj0928** [comment]
그렇네요
