### ISSUE TITLE
중간에 특수문자가 있는 단어?

### ISSUE THREAD

**Issue by AgarYoBob** [JJoriping/KKuTu#186]
나이트\r\n로프로페인	1	＂1＂［1］（1）	0	1	\r\n

db.sql을 찾다가 이상한걸 발견했네요.
이건 대체 무엇인가요?

**Comment by JJoriping** [comment]
일괄 작업에 과정에 다소 문제가 생긴 것 같습니다. 해당 행을 삭제하고 커밋했으니 확인해 보세요. 제보 감사드립니다.
