### ISSUE TITLE
ERROR OCCURRED! This worker will die in 10 seconds.

### ISSUE THREAD

**Issue by vkdlfl** [JJoriping/KKuTu#188]
![image](https://user-images.githubusercontent.com/32217676/31995037-c339e990-b9bd-11e7-83a8-623c0e16d8f7.png)
로그에 이런게 뜨는데 왜 그런진 모르겠는데 이동식 디스크에 복사 한 후에 이런 현상이 일어난거 보니 이동식 디스크에 복사 한것 때문인것 같은데 해결법좀 알려주실 수 있나요?
+
해티님 말로는 Proverbs.txt가 없어서 그렇다는데 
![image](https://user-images.githubusercontent.com/32217676/31995254-996bdd98-b9be-11e7-92b6-5a0724a9d0ff.png) 메모장이 있는데도 에러가 뜹니다 어떻게 하죠..?

**Comment by godtuonline** [comment]
지금 dekstop에 끄투가 있는걸로 인식되는것같은데
global.json가서 KKUTUHOT_PATH를 한번 확인해보세요

**Comment by JJoriping** [comment]
경로 `.../Server/lib/data/proverbs.txt`에 해당 파일이 있는지 확인해 보세요. 위 제시된 스크린샷은 `.../Server/lib/etc/data` 안에 있는 것이므로 프로그램에서 원하는 위치와 다릅니다.
