### ISSUE TITLE
GM임명은 어떻게 하나요..(본인)/단어추가는 어떻게 하나요..

### ISSUE THREAD

**Issue by and1094** [JJoriping/KKuTu#189]
프리서버를 금방 만든 사람입니다. 로그인 문제 같은 건 다 해결했는데 이제 게임을 즐기기만 하면 되겠네요.
그런데 다른 서버를 보면 GM분들이 계시는데 # 제가 관리자니까 GM으로 하고 싶은데 어떻게 하면 GM임명이 되나요? 꼭 필요한 건 아니지만 단어추가도 어떻게 하는지 알려주시면 대단히 감사하겠습니다.

**Comment by godtuonline** [comment]
다른 이슈를 찾아보시는게 좋을것같으시네요

**Comment by TheRealTolspac** [comment]
GM임명은 `lib/sub/global.json`에서 `admin` 배열에 식별번호를 넣으시면 됩니다.
단어추가는 `/gwalli`에서 암호(`lib/sub/global.json`의 `pass` 배열)와 테이블에 `ko`를 치신 후,
끄투 DB에 단어 추.... 배열에서 추가하시면 되겠습니다.

**Comment by and1094** [comment]
정말 감사합니다^^

**Comment by and1094** [comment]
진짜 죄송한데ㅠ 식별번호를 어디서 보나요..?

**Comment by TheRealTolspac** [comment]
해결 되셨으면 이슈 닫아주시면 좋겠습니다~ ^^

**Comment by and1094** [comment]
이슈는 어떻게 닫나요..? 제가 깃허브 처음이라서..^^

**Comment by and1094** [comment]
/gwalli은 어떻게 실행하는지 알려주시면 안되나요..?(계속 질문해서 죄송합니다^^:;)

**Comment by godtuonline** [comment]
도메인/gwalli 다른 이슈 검색만해도 아는건데 계속 질문하시면 좀 그렇다고봅니다

**Comment by and1094** [comment]
네 알겠습니다..

**Comment by and1094** [comment]
거의 해결되었네요. 이제 단어추가만 하면 됩니다. 답변 해주신 분들 모두 감사합니다.
