### ISSUE TITLE
웹페이지에서 제시하는 파일 이름으로 파일을 생성할 수 없습니다.

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#19]
![2](https://cloud.githubusercontent.com/assets/13843919/23094753/09ffff80-f642-11e6-8eda-d6f9651a0992.PNG)
이 화면에서 파란색으로 가려져 있는 구간에서 제시된 파일 이름으로 Notepad++로 html 파일을 생성하면

![default](https://cloud.githubusercontent.com/assets/13843919/23094737/d2f98632-f641-11e6-8450-6dadd936ebd8.PNG)
와 같은 화면을 뿜으면서 '지정된 위치에 저장할 수 없습니다' 라고 합니다.

파일 이름에서 문제인가요? 아니면 제 컴퓨터 문제인가요?

**Comment by ryush00** [comment]
바탕화면에 저 파일을 저장한 다음 옮겨보세요.

**Comment by kim-min** [comment]
바탕화면 저장시 저 오류가 발생합니다.

**Comment by ryush00** [comment]
헉.. 혹시 http:// .... / 되는 부분도 복사하셨나요?

**Comment by kim-min** [comment]
파일이름을 http://..../ 로 하면 바로 위 오류가 발생하네요

**Comment by ryush00** [comment]
그 http://서버주소/ 이 뒤를 저장할 파일 이름으로 하셔야 해요.

**Comment by kim-min** [comment]
만약에 그 파일을 만들었다면 서버등록은 어떻게 해야하나요?

**Comment by ryush00** [comment]
제가 끄투 소스를 아직 다 둘러본 게 아니라 정확히 답변해드리기는 힘들다만
아마도 `Server/lib/Web/public` 폴더에 방금 생성하신 파일을 넣고 그 파일의 내용을 서버 주소로 바꾸고 (아마 하셨겠지만) 서버 등록 과정을 진행하시면 될 것 같습니다.

등록 과정쪽은 제가 제작한 게 아니라 @JJoriping 이분이 답변해 주실 것 같네요.

**Comment by kim-min** [comment]
감사합니다

**Comment by JJoriping** [comment]
서버 등록 절차는 기본적으로 서버 등록 페이지에서 그 방법을 알려드리고 있습니다. 크게 복잡하거나 어려운 작업이 아니니 페이지에서 요구하는 대로 천천히 따라 주시고 [끄투 위키](https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0)를 참고하실 수도 있습니다.
