### ISSUE TITLE
DB 단어 추가했는데 다른 주제라고 뜨네요

### ISSUE THREAD

**Issue by and1094** [JJoriping/KKuTu#190]
저번 이슈에서 GM 임명, 단어 추가하는 법을 여쭤봤는데 GM, 단어도 다 성공했어요 근데..서버 열고 테스트하려니까 다른 주제라네요 어떻게 해야되나요..

**Comment by godtuonline** [comment]
해당 글만으로는 무슨 말인지 이해할 수가 없습니다.
스크린샷을 함께 업로드해주시거나, 설명을 더 해주시면 감사드리겠습니다.

**Comment by and1094** [comment]
알겠습니다 잠시만요

**Comment by and1094** [comment]
![default](https://user-images.githubusercontent.com/33094445/32131443-faac316c-bbe8-11e7-9062-b7d3ee78c1f8.png)

**Comment by and1094** [comment]
그래도 단어가 추가된 것 같긴 하네요

**Comment by godtuonline** [comment]
단어 대결 주제 선택하신것같은데 무슨 주제인지.. 알려주셔야죠

**Comment by and1094** [comment]
주제는 ABC끄투입니다..

**Comment by godtuonline** [comment]
그럼 주제를 똑바로 추가 안 하시는겁니다

**Comment by TheRealTolspac** [comment]
먼저 주제만들기는 `KO_KR.json`의 394줄에 `"theme_EN": "KR",`
를 적어주시고 `/gwalli`에서
`자격`에다 숫자 기입후 `끄투 DB다루기`에서 추가한 단어를 넣으신 후,
`type`배열에는 일반인 경우는 1, 그 이외의 것은 [여기](github.com/jjoriping/KKuTu/blob/master/Server/lib/const.js#L239)에서 원하는 키워드를 넣어주세요
`theme`배열에는 `KO_KR.json`에서 적은 EN을 적으면 됩니다.

EN = 알파벳(3글자)
KR = 예: 라이트노벨

**Comment by and1094** [comment]
네 정말 감사합니다.. 근데 행동은 안해도 되나요?

**Comment by TheRealTolspac** [comment]
행동은 필요없다 보는데....

**Comment by and1094** [comment]
네 알겠습니다..

**Comment by and1094** [comment]
이제 완전히 해결됐네요.. 정말 감사합니다^^
