### ISSUE TITLE
구글 클라이언트 ID 추가후 오류

### ISSUE THREAD

**Issue by KoreanMJ** [JJoriping/KKuTu#191]
const NAVER_ID = "Naver App Id";
const NAVER_SECRET = "Naver App Secret";
const GOOGLE_ID = "881443472677-a094ghpm9i85itr1eelfcp90afn0kdvn.apps.googleusercontent.com";
const GOOGLE_API = "[지움]";
const GOOGLE_SECRET = "[지움]";
// const TWITTER_KEY = "";

이렇게 작성 후 끄투온라인 서버 Manager을 켜서
서버를 구동시켰는데

E:\KKutu Online\Server\lib\sub\jauth.js:91 fields: "id,name,gender"X ^ SyntaxError: Unexpected identifier at createScript (vm.js:56:10) at Object.runInThisContext (vm.js:97:10) at Module._compile (module.js:542:28) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object.&lt;anonymous> (E:\KKutu Online\Server\lib\Web\main.js:28:14)
Worker 7576 died

다음과 같은 오류가 발생합니다.

**Comment by godtuonline** [comment]
GOOGLE_ID랑
GOOGLE_API랑 똑같이 쓰는거에요. (둘중 하나는 안써도되는걸로 알고있음)

**Comment by KoreanMJ** [comment]
ID랑 API랑 똑같이써보고
API칸을 비워봤는데도
똑같은 오류가 발생합니다

**Comment by TheRealTolspac** [comment]
jauth.js 91줄의 "id,name,gender" 오른쪽에 있는 X를 빼세요

**Comment by KoreanMJ** [comment]
해결됬습니다. 감사합니다.
