### ISSUE TITLE
구글 로그인 401오류

### ISSUE THREAD

**Issue by KoreanMJ** [JJoriping/KKuTu#193]
/lib/sub/jauth 파일에
------------------------------------------------------------------------
const NAVER_ID = "";
const NAVER_SECRET = "";
const GOOGLE_ID = "881443472677-a094ghpm9i85itr1eelfcp90afn0kdvn.apps.googleusercontent.com";
const GOOGLE_API = "";
const GOOGLE_SECRET = "[원래는 적어놨습니다]";
------------------------------------------------------------------------
이라고 적어놨는데

![error](https://user-images.githubusercontent.com/33196781/32370824-c4b4c5c2-c0d1-11e7-8fe5-0db646d298ab.png)

다음과 같은 오류가 발생합니다.

**Comment by TheRealTolspac** [comment]
`login.pug`의 24줄의 contect=""의 따음표안에 클라이언트 아이디 넣으셨습니까?

**Comment by KoreanMJ** [comment]
그래도 똑같이 401오류가 발생합니다.

Request Details

    redirect_uri=storagerelay://http/211.59.135.22?id=auth760975
    response_type=permission id_token
    scope=email profile openid https://www.googleapis.com/auth/plus.login
    openid.realm=
    client_id=881443472677-a094ghpm9i85itr1eelfcp90afn0kdvn.apps.googleusercontent.com
    ss_domain=http://211.59.135.22
    fetch_basic_profile=true
    gsiwebsdk=2

**Comment by godtuonline** [comment]
설정 잘 하셨는지..

**Comment by KoreanMJ** [comment]
설정할게 뭐뭐있죠 처음에 서버키자마자
global.js를 설정하고
web/view/login/pug와
sub/jauth를 수정했습니다.

**Comment by TheRealTolspac** [comment]
구글 로그인 설정 사이트를 보여주세요
