### ISSUE TITLE
끄투 봇 질문

### ISSUE THREAD

**Issue by and1094** [JJoriping/KKuTu#194]
프리 서버에는 사기 봇을 제외한 봇들은 모두 아무 단어도 못 쓰는 걸로 알고 있습니다.
그래서 봇을 만들고 싶은데, 찾아봐도 안 나오는 것 같길래 질문 드립니다.

끄투 봇은 어떻게 만드나요??

**Comment by godtuonline** [comment]
사기 봇을 제외한 봇들이 단어를 쓸 수 있게 할 수 있는 법은 이슈 #3 에 설명이 있으니 확인해 보시면 좋을 것 같습니다.

**Comment by and1094** [comment]
감사합니다.

**Comment by and1094** [comment]
이제 classic.js에서 수정해야 된다는 것도 알겠는데.. 이슈 #38 에서 로봇 플레이를 반복하라고 하던데 전 이 이슈를 봐도 어느 부분을 수정해야 하는 지 모르겠네요. 플레이반복을 어디서 수정하나요??

**Comment by godtuonline** [comment]
ROBOT_HIT_LIMIT 를 늘려주면 될 것 같습니다

**Comment by and1094** [comment]
네 감사합니다

**Comment by and1094** [comment]
일단 늘렸는데 아직도 사끄봇 외엔 움직이지가 않는 것 같네요.. 음.. 좀 더 바꿔보고 말씀드리겠습니다

**Comment by and1094** [comment]
헐 뭘 어떻게 했는지.. 이제 사끄봇도 아무것도 몰라요..

**Comment by TheRealTolspac** [comment]
그 이상으로 건들지 마시고 봇을 플레이하면서 히트 수를 늘려주시면 좋겠습니다만....
