### ISSUE TITLE
끄투 접속하면 맨 하단에 나오는 Copyright나 링크 같은 것..

### ISSUE THREAD

**Issue by and1094** [JJoriping/KKuTu#195]
끄투 접속하면 맨 하단에 나오는 Copyrignt 말고도 막 써져있잖아요.. 이거 어디 파일에서 수정하나요? 좀 찾아보긴 했는데 안보이네요... 
![default](https://user-images.githubusercontent.com/33094445/32550869-f7e14958-c4d1-11e7-8018-c54fec7fc7bf.png)

**Comment by godtuonline** [comment]
위키보시면 아는데요... ko_KR입니다..
메세지를 삭제하실려면 무슨 pug파일이엿는데 기억안남

**Comment by and1094** [comment]
넹..
