### ISSUE TITLE
https 구현문의 - 미해결

### ISSUE THREAD

**Issue by TheRealTolspac** [JJoriping/KKuTu#197]
풀리퀘스트에 있는 https 구현 파일을 보고 그대로 따라했는데
global.json의 private key, cert, ca, pfx을 어떻게 얻는지 알려드릴 수 있을까요...?

**Comment by godtuonline** [comment]
SSL을 구매하시거나 let's encrypt에서 무료로 발급 받으실 수 있습니다.
그러면 해당 인증에 필요한 모든것을 다운받으실 수 있습니다.

**Comment by TheRealTolspac** [comment]
네 감사합니다^^~

**Comment by TheRealTolspac** [comment]
![default](https://user-images.githubusercontent.com/32929371/33886707-d0d3e6ee-df8a-11e7-8da2-50e2ea4a1b48.PNG)
발급은 완료 했다만, 어디에 무슨 키가 있는 지 잘 모르겠습니다.
