### ISSUE TITLE
oAuth 를 통해 로그인 했을때 인게임 이름 변경

### ISSUE THREAD

**Issue by alforeplay** [JJoriping/KKuTu#199]
인게임상 이름을 따로 부여 할 수 있나요? 구현 되어 있지 않다면 어디를 수정해야 하나요? 핸들링 해주는 부분을 못 찾겠습니다.

**Comment by small-sunshines** [comment]
흠.. 저도 잘은 모르겠지만 제가 PR넣은 커밋에선 auth.js 에서 가능합니다..

**Comment by small-sunshines** [comment]
수정합니다. 현재 끄투 메인Repo에 반영된 소스에서는 /Web/auth 에 있는 각 제공자 별 소셜로그인 설정파일에서 로그인에 관여하고 있습니다.

그 부분의 소스를 확인해주시면 될 것 같습니다.
