### ISSUE TITLE
한글 도메인을 http://jjo.kr/kkutu 서버리스트에 추가할 수 없는 문제

### ISSUE THREAD

**Issue by horyu1234** [JJoriping/KKuTu#20]
서버 리스트 추가시 [http://끄투.한국](http://끄투.한국) 으로는 인증 파일 자체를 못찾아, 소유권 인증이 정상적으로 안됩니다.
인식이 안되는 인증 파일: [http://끄투.한국/kkutu-dHA6Ly/rqY.html](http://끄투.한국/kkutu-dHA6Ly/rqY.html)

현재는 변환된 주소인 [http://xn--vz0b065d.xn--3e0b707e](http://xn--vz0b065d.xn--3e0b707e) 로 서버 리스트에 등록해둔 상태입니다.
현재 올려둔 인증 파일: [http://xn--vz0b065d.xn--3e0b707e/kkutu-dHA6Ly94bi.html](http://xn--vz0b065d.xn--3e0b707e/kkutu-dHA6Ly94bi.html)

감사합니다.

**Comment by JJoriping** [comment]
안녕하세요. 해시 값에 `/`가 들어가는 건 의도하지 않았는데 다른 한글 도메인 서버가 잘 등록된 점으로 보아 아마 인코딩 관련 문제가 아닐까 싶습니다. 일단 가독성을 위해 끄투.한국 서버의 홈페이지 URL을 한글로 수정하였으니 확인해 보세요.
