### ISSUE TITLE
구글 로그인 401오류

### ISSUE THREAD

**Issue by yaj0928** [JJoriping/KKuTu#200]
네이버 로그인 포기하고 페이스북 포기하고 구글이라도 할라했는데 API는  Google Cloud OS Login API로 해놨는데 이게 맞을란가요.ㅠㅠ 그리고 key를 입력을해도
![image](https://user-images.githubusercontent.com/33867923/33074060-31859bce-cf08-11e7-81d4-f9cb32148a53.png)
이 오류가 뜹니다 도와주십시요.ㅠㅠㅠ

**Comment by godtuonline** [comment]
그 API가 아니라 구글 OAuth Api입니다....

**Comment by yaj0928** [comment]
그API는 아에 생성이 오류가 떠서 안되더라고요,,ㅠㅠ
