### ISSUE TITLE
kkutu.kr에서 등록했을때 적었던 비밀번호를 까먹었습니다 ㅠㅠ

### ISSUE THREAD

**Issue by godtuonline** [JJoriping/KKuTu#202]
http://godtu.cf 라는 주소의 서버를 번거로우시겠지만 삭제해주시면 감사드리겠습니다..ㅠ
혹시 가능하시다면 이런식으로 비밀번호를 쓰는것이 아닌 끄투처럼 소셜 로그인을 사용해서 비밀번호를 대신 해서 사용했으면 좋겠습니다 ㅠ
그리고 지금 이걸 냅두고 새로운 주소로 쓸려고하는데 되지 않아서
다시한번(..) 번거로우시겠지만 갓투.kr로 등록부탁드리겠습니다. 이름은 갓투로..
계속 이미 등록된 서버입니다. 라고 표시가 됩니다

**Comment by yaj0928** [comment]
아..갓퉄ㅋㅋㅋㅋ

**Comment by godtuonline** [comment]
@yaj0928 이슈와 관련없는 이야기는 자제해주셨으면 좋겠습니다

**Comment by minesna** [comment]
레포지토리가 겹쳐서 그럴수있습니다. 원래 쓰던거랑 같은 서버인데 도메인만 다르다면 등록할 필요는 없을꺼 같습니다

**Comment by minesna** [comment]
냅두고 하는것보다는 하나를 선택해서 하나는 지워달라하는게 맞지않을까요

**Comment by godtuonline** [comment]
비번 알아내서 지웠습니다
