### ISSUE TITLE
네이버 로그인 문제

### ISSUE THREAD

**Issue by yaj0928** [JJoriping/KKuTu#203]
네이버 로그인 연동을 힘들게 하고 
딱 로그인을 한순간... Unauthorized 이것이 뜨고 다시해야하네요.. 이거 고치는 방법 없을까요 
+ 관리자를 gmalli이거 관리자를 제 아이피로 설정할수는 없나요 로그인이 안되다 보니까 관리자를 못하겠네요

**Comment by TheRealTolspac** [comment]
무작정 이슈 남기지 말고 다른 이슈나 인터넷을 보세요.
님이 원하는 것은 찾아나오면 다 나옵니다.
.은 일부 수정이 필요하니 oauth로 해결하세요

**Comment by JJoriping** [comment]
이슈 #208 을 참고하세요.
