### ISSUE TITLE
kkutu.kr 서버 정렬 방식 개편

### ISSUE THREAD

**Issue by hatty163** [JJoriping/KKuTu#206]
현재 상위노출 ''이펙트''가 심각한 상황입니다. 뒤로 갈수록 서버들이 인원이 줄어들고, 유저들이 앞에 2-3 서버만 들어가는 상황입니다. 아무래도 핑(응답속도)순이라던지, 접속자 순이라든지 자동 정렬되어 공평해 졌으면 합니다. 예전 끄투 리스트에는 정렬 방법을 바꿀 수 있던 걸로 알고 있습니다. 이걸 이용하여 기본적으로 서버 인원 순, 핑 순 등으로 개편했으면 합니다.

**Comment by ment12da** [comment]
접속자순으로 자동정렬을 하였을때에는 현재와 같은 결과를 불러올 것이라 생각됩니다.

또한, 핑순으로 정렬할경우를 말해보자면 현재 kkutu.kr의 핑 계산은 원할하지 않습니다. 근대 이 원할하지 못한 값으로 정렬한다면 당연히 원할하지 못한 순서가 나올 것이라 예상됩니다.

**Comment by Tilto0822** [comment]
현재 쪼리핑님께서는 KKSP-끄투 위성 프로젝트를 기반으로 한 새로운 끄투 서버 정렬을 개발하고 계신 점 참고 부탁드리겠습니다.

**Comment by JJoriping** [comment]
개편된 끄투 프리 서버 목록 페이지가 2021년 1월 31일 게시되었으므로 이 이슈를 닫습니다.
