### ISSUE TITLE
관리자 설정문의

### ISSUE THREAD

**Issue by yaj0928** [JJoriping/KKuTu#208]
주소/gwalli 이렇게 들어가면 관리자 모드로 들어간다고 알고있습니다 근데 저는 지금 네이버 로그인도 안되는 상황이여서 이슈남겨봅니다.. 전에도 남겨봤지만 답변이 없길레.. 관리자를 컴퓨터의 ip로 설정은 안되나요..? 설정은 또 ./server/lib/sub/global.json 여기서 하는게 맞는건가요..?

**Comment by hatty163** [comment]
... 뭐라고 하시는지 하나도 이해가 가지 않습니다

**Comment by JJoriping** [comment]
관리 페이지를 특정 IP 주소에서만 접근 가능하게 하려면 express를 이용한 라우팅 과정에서 관리 관련 페이지인 경우에 대해 IP 주소를 확인하면 됩니다. IP 주소를 얻는 방법은 [Express 4.x API 참조 문서](http://expressjs.com/ko/api.html#req.ip)를 참고하세요.

**Comment by JJoriping** [comment]
기존에 구현된 관리자 확인 방식을 바꾸려면 [함수 `checkAdmin()`](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/routes/admin.js#L264)을 수정해 보세요.
