### ISSUE TITLE
끄투 상단 공지?

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#213]
![_2017_12_02_17_45_57_725](https://user-images.githubusercontent.com/31066511/33513579-ad356e42-d788-11e7-9636-073e7070bc41.png)
이건 어떻게 하는건가요..?

메세지 내용 말고, 저 상단 공지 같은거요

**Comment by horyu1234** [comment]
`Server/lib/Web/public/global_notice.html` 파일을 수정하시면 됩니다.

**Comment by Sichisky** [comment]
@horyu1234 감사합니다.
