### ISSUE TITLE
패치노트?

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#214]
![_2017_12_02_17_46_45_696](https://user-images.githubusercontent.com/31066511/33513588-cfba3dda-d788-11e7-98c3-d0096b94d32e.png)
이렇게 버전과 설명이 있는 이것 어떻게 수정하는지 부탁드립니다.

**Comment by horyu1234** [comment]
`Server/lib/Web/public/kkutu_bulletin.html` 파일을 수정하시면 됩니다.

**Comment by Sichisky** [comment]
@horyu1234 감사합니다.
