### ISSUE TITLE
GM 휘장 관련

### ISSUE THREAD

**Issue by rickykim2005** [JJoriping/KKuTu#215]
psql에 아래 글을 썼는데 오류가 발생되며 GM 휘장 지급이 안됩니다.
![1](https://user-images.githubusercontent.com/34229487/33539412-9a5954aa-d909-11e7-915d-e8d66a4dc61e.jpg)

**Comment by TheRealTolspac** [comment]
편하게 관리 사이트에서 하세요.
다른 이슈로 찾아보면 관리 사이트로 GM 휘장을 얻을 수 있는 방법이 나옵니다.

**Comment by ment12da** [comment]
psql 에서 보이는 바로는 현재 접속해있는 DB가 main이 아닌 postgres 입니다. 다시 한번 확인 부탁드립니다.
