### ISSUE TITLE
Oauth 관련 심각한 취약점 발견

### ISSUE THREAD

**Issue by small-sunshines** [JJoriping/KKuTu#216]
![image](https://user-images.githubusercontent.com/11470513/33597459-d7fce284-d9e2-11e7-893d-72a8af216754.png)

위에서 보시는것처럼 oauth 유저정보가 중복될 경우 심각한 오류를 초래할 수 있는 취약점이 @horyu1234 님에 의해 발견되었습니다. 확인 부탁드립니다.

**Comment by horyu1234** [comment]
시간이 나면 취약점 패치하여 한번 풀리퀫 올려보겠습니다.

**Comment by small-sunshines** [comment]
이번 취약점에 대한 패치방법을 찾아냈습니다.

Passport 에서 로그인을 처리할 때 $p.id 변수에 소셜로그인 제공자를 구분할 수 있는 코드를 같이 삽입해주면 되는 방식입니다.

이번 패치에 대해 @horyu1234 님이 마이그레이션 및 패치를 구현하셔서 PR을 올리신다고 하셨으므로 이번 이슈는 곧 종결처리될 모양입니다.

이번 이슈에 관심 가져주신 모든 분들께 감사드립니다.

**Comment by small-sunshines** [comment]
위 이슈는 어느정도 해결된 것으로 판단, 이슈 닫겠습니다.
