### ISSUE TITLE
데이터 베이스 구축시 암호 입력이 안되요...

### ISSUE THREAD

**Issue by edisondl** [JJoriping/KKuTu#217]
C:\Program Files\PostgreSQL\10\bin>createdb -U "postgres" "main"
암호:
createdb: 데이터베이스 만들기 실패: ?ㅻ쪟:  "main" ?대쫫???곗씠?곕쿋?댁뒪???대? ?덉쓬

네 말그대로 암호 입력이 안됩니다.
설치시 암호를 입력했구요. 근데 cmd에서  createdb 명령어 입력하니  암호입력하라는데 영어 숫자 입력이 안되요. 한글도 한글자만 입력되고요. 몇번 재설치 했지만 그대로 네요...
어떻게 하죠?

**Comment by NiceGayy** [comment]
정상
