### ISSUE TITLE
passport 구현 중 오류

### ISSUE THREAD

**Issue by TheRealTolspac** [JJoriping/KKuTu#218]
![default](https://user-images.githubusercontent.com/32929371/33711654-18dd30aa-db88-11e7-850d-dc3e5724b7cf.PNG)

**Comment by kjbkjb1122** [comment]
그딴것을 해결을 못하게 이 지랄을 함? 바보세요??
적어도 오류로그를 읽을 수 있었으면서 이슈만 ㅈ대가리처럼 올리는 사람
너 밖에 없을 듯 ㅇㅈ? ㅇㅇㅈ ㅋ

**Comment by NiceGayy** [comment]
passport를 설치해주시면 됩니다

@kjbkjb1122 님이 쓰신 이슈들 읽어보니까님이 할말은 아닌듯

**Comment by yunho0508** [comment]
`npm install passport`를 실행하신 후 다시 시도 해보시기 바랍니다.

@kjbkjb1122 초보 프로그래머들 기 죽이지 마시고 님이 그 말 할 수 있는지 잘 생각해보시길 ^^

**Comment by TheRealTolspac** [comment]
![default](https://user-images.githubusercontent.com/32929371/33767657-ed28f870-dc65-11e7-9051-df220902a765.PNG)
윗님 말대로 해보니 이렇게 뜨네요.
추가로 코딩이 필요한가요?

**Comment by TheRealTolspac** [comment]
감사합니다. 해결되었습니당!!

**Comment by TheRealTolspac** [comment]
![default](https://user-images.githubusercontent.com/32929371/33831976-86c5ad8a-debd-11e7-83dd-48357371f724.PNG)
`npm install passport-google-oauth20`로 깔았는데 오류가 뜨네요.
