### ISSUE TITLE
구글 소셜 로그인을 할려면 계속 로딩만 합니다.

### ISSUE THREAD

**Issue by msquid** [JJoriping/KKuTu#22]
![b](https://cloud.githubusercontent.com/assets/25874496/23098951/7995646e-f69e-11e6-9e39-be51c98643cd.PNG)
![c](https://cloud.githubusercontent.com/assets/25874496/23098950/79949ef8-f69e-11e6-8c92-d93faf5ab677.PNG)
![a](https://cloud.githubusercontent.com/assets/25874496/23098949/7993111e-f69e-11e6-8ee9-4defca56b053.PNG)

계속 이러네요..

**Comment by ljs970624** [comment]
jauth.js 파일의 구글 로그인 부분에 R.go($p); 가 누락되어서 그렇습니다.
[](https://github.com/ljs970624/KKuTu/blob/master/Server/lib/sub/jauth.js) 링크를 참고하세요.

						try{ _doc = JSON.parse(_doc); }catch(e){ return R.go({ error: 500 }); }
						if(_doc.error) return R.go({ error: _doc.error.code });*/
						
						$p.type = "google";
						$p.id = doc.sub;
						$p.name = doc.name;
						$p.image = doc.picture;
						
						**R.go($p);**
						/* 망할 셧다운제
						$p._age = _doc.ageRange;
						if(_doc.birthday){
							$p.birth = _doc.birthday.split('-').map(Number);
							$p.birth.push($p.birth.shift());
						}
						$p.isAjae = Ajae($p.birth, $p._age);
						R.go($p);
					}

**Comment by msquid** [comment]
해결했습니다. 감사합니다

**Comment by Sichisky** [comment]
이 사이트 어떻게 들어가지는지 알려주실수 있나요..?
저는 다르게 떠서..
