### ISSUE TITLE
관리 페이지에서 GM 휘장 지급

### ISSUE THREAD

**Issue by rickykim2005** [JJoriping/KKuTu#221]
관리 페이지를 아무리 봐도 잘 모르겠습니다. 어떻게 하죠?

**Comment by TheRealTolspac** [comment]
자격 탭의 암호는 `global.json`에서 설정한 암호를 넣어주시고
테이블은 `ko`나 `en`을 입력후 `상점 DB다루기`에서 `bg_gm1`친후 `cost` 값을 `-1`에서 `0`으로 바꾸시면 상점에서 구입가능합니다.
(이전 이슈는 유저 db다루기를 사용하는 거지만 유저 db 다루기 사용법 을 모름)

**Comment by rickykim2005** [comment]
상점 DB 다루기에서 설정을 해보았지만 적용 버튼을 클릭해도 아무 반응이 없습니다. 참고로 아직 loclahost/gwalli으로 도메인 없이 접속했습니다.

**Comment by CraftyDragon678** [comment]
암호를 입력하지 않았을때 주로 아무 반응이 안 일어 나던에... 한번 확인해 주세요

**Comment by rickykim2005** [comment]
암호(식별자)를 정확하게 입력했습니다.(맨 위 암호 및 테이블도 입력했어요)

**Comment by NiceGayy** [comment]
윗분이 설명하신건.. 너무 그러언 방법입니다
자격 탭의 암호를 입력하시고
`끄투 DB 탭`에서 식별번호를 입력하시고 조회를클릭합니다
그러면 영어가 쭉 뜰탠데 그 중에 `box` 탭이 `{}` 이렇게 되어있을 겁니다
그걸 `{"b1_gm":1}`로 해주시고 끄투에들어가면 (착용안되있을거입니다) 프로필 관리에 들어와있을겁니다.

**Comment by JJoriping** [comment]
이슈 #23 을 참고하세요.
