### ISSUE TITLE
끄투 단어 주제(theme) 추가는 어떻게하나요?

### ISSUE THREAD

**Issue by gamcats** [JJoriping/KKuTu#222]
theme 추가 방법을 모르겠어요.. 시도는 해봤는데 안되서..

**Comment by CraftyDragon678** [comment]
const.js파일에 고유 번호를 추가해 주시고 ko_KR.json파일에 그 번호에 맞는 이름을 생성해 주세요.

**Comment by gamcats** [comment]
CraftyDragon678님 감사합니다.
