### ISSUE TITLE
끄투 서버등록이 안되요.(인증 파일의 내용이 올바르지 않습니다. 입력한 서버 주소와 같게 해 주세요.)

### ISSUE THREAD

**Issue by gamcats** [JJoriping/KKuTu#224]
![default](https://user-images.githubusercontent.com/34202054/33797254-fddbcf3e-dd47-11e7-9b37-88a09b5f01f6.PNG)
![2](https://user-images.githubusercontent.com/34202054/33797255-0126fa7e-dd48-11e7-8b0e-492d20a27056.PNG)

이렇게 했는데 위에 처럼되서 고생이네요. 해결 방법을 알려주실 수 있나요?

++

혹시나 싶어서 html도 올릴게요.

파일명: kkutu-dHA6Ly9ndW.html

![3](https://user-images.githubusercontent.com/34202054/33798213-f8dce436-dd57-11e7-8f53-27cc69b9e995.PNG)

**Comment by minesna** [comment]
html 태그없이 그냥 서버주소만 적어보세요

**Comment by TheRealTolspac** [comment]
파일명은 맞으시고 안 내용은 자기 도메인주소만 넣으셔도 됩니다.

**Comment by 111222enter** [comment]
저는 무슨말인지 이해가 잘안가네요.
