### ISSUE TITLE
끄투 서버 등록(등록 했지만 서버가 kkutu.kr에 안나오는오류)

### ISSUE THREAD

**Issue by gamcats** [JJoriping/KKuTu#225]
서버 등록을 성공했는데 거의 1시간 가까이 지났는데도 서버가 보이지않고 다시 등록해도 이미 등록된 서버라고 나오는데 어떻게 해야하나요?

![default](https://user-images.githubusercontent.com/34202054/33802326-e213fdb0-ddb7-11e7-84d4-cd8d2e603f13.PNG)

++ 현재 10시간째

**Comment by ment12da** [comment]
현재 확인결과 기존 등록된 서버도 접속자와 on/off 로드가 안되는 상황입니다. 오류가 해결될때 까지는 서버리스트에 등록하신 서버가 안보일 듯 합니다.
