### ISSUE TITLE
단어 목록

### ISSUE THREAD

**Issue by rickykim2005** [JJoriping/KKuTu#228]
안녕하세요. 끄투에 등록된 모든 단어를 보고 수정할 수 있을까요? 단어 추가 할때 오타 났는데 수정 방법을 모르겠습니다.

**Comment by TheRealTolspac** [comment]
gwalli에서 단어 불러오고 x 버튼 누르고
다시 단어 입력하세요

**Comment by NiceGayy** [comment]
관리페이지에서 하시면되요

**Comment by TheRealTolspac** [comment]
윗분 처럼 관리 페이지에서 `암호`와 `테이블`을 입력후,
단어를 삭제하시고, 다시 만드셔도 됩니다.
