### ISSUE TITLE
GM 설정

### ISSUE THREAD

**Issue by msquid** [JJoriping/KKuTu#23]

**Comment by ljs970624** [comment]
Server/lib/sub/global.json 파일의 ADMIN 칸에
GM 권한을 적용할 계정의 id값을 입력하면 됩니다.

**Comment by msquid** [comment]
감사합니다 :+1:

**Comment by msquid** [comment]
음, Admin 칸에 자신의 아이디를 놔도 안되네요. 채팅창에 /id <자신이름> 했는데도 말인데요.
![chapete](https://cloud.githubusercontent.com/assets/25874496/23099554/a62c181a-f6ad-11e6-8728-fb7332e1ce30.PNG)

**Comment by ljs970624** [comment]
서버 재부팅 후 채팅창에서 #kill 103111250635340929595 명령어를 입력해보세요.

참고로 [GM] 휘장은 권한과 관계 없는 휘장 아이템입니다.

**Comment by msquid** [comment]
감사합니다

**Comment by msquid** [comment]
그럼 어떻게 [GM] 휘장을 얻죠?

**Comment by ljs970624** [comment]
데이터베이스에서 직접 추가해주셔야 합니다.

UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '103111250635340929595';

**Comment by msquid** [comment]
데이터베이스에서 추가할려면 어느 프로그램을 써야 하죠?

**Comment by yom21c1020** [comment]
PostgreSQL 내장 CUI 도구(psql)를 이용하시면 됩니다.

**Comment by msquid** [comment]
됐네요. 감사합니다

**Comment by emptyme** [comment]
psql에 위에 나와있는대로 추가한 다음에 나오는건 뭘 입력해야 하나요

**Comment by DevloperCheongwol** [comment]
UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '77160036';
psql 콘솔에서 데이터베이스 main으로 설정해놓고 했는데
안됩니다... 도와주세요
