### ISSUE TITLE
닉네임 변경

### ISSUE THREAD

**Issue by Bambi1032** [JJoriping/KKuTu#233]
안녕하세요. 끄투리오, 끄투코리아, 비트유끄투, 야채 끄투에는 프로필 관리에서 닉네임을 자유롭게 변경 할 수 있는데 어떻게 설정하나요?

**Comment by CraftyDragon678** [comment]
직접 구현하셔야 되긴 합니다만.... users 테이블에 새로운 칼럼 하나 생성하셔서(닉네임란) 그쪽 바꿀 수 있게 exordial(상태메시지) 수정하는 부분과 같이 바꾸시고, 로그인시에 session테이블의 profile.titile값을 users테이블의 닉네임 칼럼 값을 불러오는 걸로 하시면 됩니다. (클라이언트 구현도 물론 하셔야 합니다)

**Comment by V-Remember** [comment]
ㅇ
