### ISSUE TITLE
[여기다 하는게 아닌거 같아서 닫을께요. 죄송합니다]혹시 라운드나 인원수 제한을 푸는법이 없을까요

### ISSUE THREAD

**Issue by shj0303** [JJoriping/KKuTu#235]
끄투 게임을 할때 라운드나 인원수 제한 때문에 아쉬울 때가 있는데 어디를 건드려야할지 모르겠네요.

**Comment by TheRealTolspac** [comment]
제한을 푸는 것이 체계가 무너질 것 같은데요

**Comment by shj0303** [comment]
체계부분이 무너지는건 둘째치더라도 가능은 할까요? 궁금해졌네요
