### ISSUE TITLE
pug문법 변환 부탁드립니다.

### ISSUE THREAD

**Issue by TheRealTolspac** [JJoriping/KKuTu#237]
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <script>
        (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "",
        enable_page_level_ads: true
      });
      </script>

이 html문법을 pug문법으로 바꿔드리면 감사드리겠습니다.

**Comment by NiceGayy** [comment]
```
script(async='', src='//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js')
script.
  (adsbygoogle = window.adsbygoogle || []).push({
  google_ad_client: "",
  enable_page_level_ads: true
  });

```
html을pug로바꿔주는사이트는 많으니까 검색하세요

**Comment by TheRealTolspac** [comment]
감사합니다.
