### ISSUE TITLE
passport사용중...

### ISSUE THREAD

**Issue by TheRealTolspac** [JJoriping/KKuTu#238]
옛날 보다는 편하졌는데, twitter를 제외한 다른 oauth들이 callback오류를 뿜습니다.
코드의 callback을 바꿔야하나요?
아니면 oauth발급 사이트의 callback을 바꿔야하나요??
![default](https://user-images.githubusercontent.com/32929371/34207586-76474f96-e5ce-11e7-90b0-24a0775e8961.PNG)

oauth발급 사이트라면 콜백 url을 https://kkutuscreen.com으로 하였구요.
코드는 그대로 두었습니다.

**Comment by NiceGayy** [comment]
오류내용보니까 callback을 www붙여서 한거아닌가요

**Comment by hatty163** [comment]
보아하니 둘 중 하나의 redirect url이 https://www.kkutuscreen.com 이고 다른 하나는 https://kkutuscreen.com 이네요 리다이렉트 url 확인 부탁드립니다.

**Comment by TheRealTolspac** [comment]
ssl 설정에서 www.kkutuscreen.com에서 kkutuscreen.com 으로 ssl 적용 URl을 바꿔서 하니,
정상 작동이 되군요.

**Comment by TheRealTolspac** [comment]
![default](https://user-images.githubusercontent.com/32929371/34338105-a0552cda-e9a8-11e7-8d96-1f828062e6d0.PNG)
이번엔 구글 OAUTH인데 이렇게 오류가 뜹니다.

**Comment by hatty163** [comment]
구글 개발자 콘솔에서 Google+ API를 활성화해야 합니다.
