### ISSUE TITLE
노란색 팝업창 띄우는 방법...

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#24]
제목 그대로 입니다. 저번에, 끄투 공식서버가 잠시 닫힐 때 노란색 팝업을 띄었는데, 그것을 프리 서버에서 띄우는 방법을 알려주시면 감사하겠습니다.

**Comment by heptagonkr** [comment]
Server/lib/Web/public/global_notice.html
이 파일에 텍스트를 추가하고 새로고침하면 보입니다
