### ISSUE TITLE
변수가 겹치는 건 가요?

### ISSUE THREAD

**Issue by TheRealTolspac** [JJoriping/KKuTu#240]
![default](https://user-images.githubusercontent.com/32929371/34453269-f8698590-ed92-11e7-8c6e-02a7c7c6545a.PNG)

이렇게 `LEVEL`변수가 2개나 만들어졌는데,
이 2개가 어디에서 활용되는지 궁금합니다

**Comment by horyu1234** [comment]
중복된 값입니다.
제 레포에서도 제거하였는데, 아무 문제 없었습니다.
둘중 하나는 제거하셔도 문제 없는 값입니다.
