### ISSUE TITLE
로그인에 대하여 도움을 받고싶습니다.

### ISSUE THREAD

**Issue by sonhun** [JJoriping/KKuTu#241]
include module

doctype html
html
	head
		title= L('title')
		script(src="https://apis.google.com/js/platform.js")
		meta(name="google-signin-client_id" content="895613122599-lu0cao2b8pv158nphmoj7pujh4b9fco8.apps.googleusercontent.com")
		+PageHead()
	body
		span#locale= JSON.stringify(LANG)
		span#stateKey= locals._id
		div.login-with= locals.text ? L(locals.text) : '구글 로그인만 가능합니다.'
		//button.with-naver= L('withNaver')
		//button.with-facebook= L('withFacebook')
	    //button.with-facebook= L('withGoogle')
		div#with-google(style='border-radius: 5px; margin: 8px auto; width: 210px; overflow: hidden;')
		//div.login-legal!= L('loginLegal')

이렇게 해놧는데 구글 로그인 버튼도 안뜨고 왜이럴까요ㅜㅜ 좀알려주세요 ㅜ

**Comment by TheRealTolspac** [comment]
[여기](https://blog.naver.com/kjbkjb1122/221173281324) 를 참고해주세요.
(최신 레포지토리를 받는 것을 적극적으로 권장드립니다.)
