### ISSUE TITLE
로그인 에러

### ISSUE THREAD

**Issue by Tobu1** [JJoriping/KKuTu#243]
끄투.한국에 로그인하려는데 로그인이 안됩니다..

**Comment by ment12da** [comment]
끄투 본 코드의 문제가 아니기 때문에 끄투 깃허브 이슈에 올리시지 마시고 끄투 한국에 문의하시길 바랍니다.

**Comment by TheRealTolspac** [comment]
본 소스코드에 대한 문제는 아니니,
일단은 이슈 닫아주세요.
