### ISSUE TITLE
서버가 등록 되지 않습니다.

### ISSUE THREAD

**Issue by TheRealTolspac** [JJoriping/KKuTu#244]
![default](https://user-images.githubusercontent.com/32929371/34466933-25da2b48-ef27-11e7-891d-d9d848e584ba.PNG)
이 상태로 계속 무한 로딩 중입니다.
어떻게 할 수 없을까요?

**Comment by JJoriping** [comment]
안녕하세요. 해당 도메인 `kkutuscreen.com`에 대응되는 IP 주소가 내부 IP인 것으로 보입니다. 공유기를 이용하고 있는 경우 도메인의 IP 주소를 외부 IP 주소로 설정하고 포트 포워딩 등으로 외부 IP와 내부 IP를 이어주어야 합니다.
