### ISSUE TITLE
데이터베이스오류

### ISSUE THREAD

**Issue by kkutu4444** [JJoriping/KKuTu#247]
데이터베이스오류떠요
createdb: template1 데이터베이스에 연결 할 수 없음: 치명적오류: 사용자  "postgres"의 password 인증을 실패했습니다
  C:\Users\come\AppData\Roaming\postgresql/pgpass.conf 파일에서 암호를 찾을수가 없다는데 어떻게함?

**Comment by hatty163** [comment]
1. 반모 쓰지 마세요. 여기는 인터넷 공간입니다.
2. PSQL 암호를 잘못 입력하셨을 때 발생하는 오류입니다. PSQL 암호를 확인해 보세요.
3.C:\Users\come\AppData\Roaming\postgresql/pgpass.conf 경로가 잘못됬습니다. (/와 \는 다릅니다.)
바른 주소는 C:\Users\come\AppData\Roaming\postgresql\pgpass.conf
입니다.

**Comment by kkutu4444** [comment]
암호 맞게 설정한것 같은데도 이러네요...

**Comment by TheRealTolspac** [comment]
pgAdmin에서 암호 변경하세요.
