### ISSUE TITLE
? 등등 특수문자로 끝나는 단어를 끝말잇기에서 치면 게임이 작동되지 않습니다.

### ISSUE THREAD

**Issue by shj0303** [JJoriping/KKuTu#249]
예전에 ?로 끝나는 단어를  추가했었는데 끝말잇기에서 써보니 현재 접속한 채널에 문제가 발생했다고 뜨면서 멈추더라구요. 그래서 gwalli가서 삭제를 시도했는데 삭제도 일반적인 방법으로는 안되는거같은데 제가 뭔가를 잘못 건드린건지 안그럼 끄투 버그인지 확인좀 바라겠습니다.

**Comment by JJoriping** [comment]
안녕하세요. 끄투 설계 당시에는 한글과 알파벳만이 단어의 끝으로 나올 수 있고 가운데에는 공백 문자와 숫자를 포함할 수 있음을 전제로 설계했습니다. 전제 밖의 상황에 대해서는 어떤 결과가 나올지 예상하기 힘든 점 양해 바랍니다. 일부 특수 문자가 포함된 내용을 삭제하기 위해서는 직접 PostgreSQL 데이터베이스를 조작해야 합니다. 관련 프로그램으로 [pgAdmin](https://www.pgadmin.org/)이나 psql(서버 설치 시 내장되어 있음)이 있으니 이들을 활용해 보기 바랍니다.
