### ISSUE TITLE
셧다운제

### ISSUE THREAD

**Issue by ljs970624** [JJoriping/KKuTu#25]
셧다운제를 적용할려는데 ajae.js 파일을 올려주실 수 있을까요?

**Comment by JJoriping** [comment]
안녕하세요. 해당 파일을 제공해 드리기에 앞서 저작권 관련 사항을 준수해 주시기 바랍니다.

GPL 3.0 제5조(Conveying Modified Source Versions)에 따라 소스 코드를 이용하시고자 할 때에는 반드시 해당 소스 코드에 저작권과 관련된 안내 사항이 명시되어야 합니다. @ljs970624 님의 레포지토리에서 이를 위반하는 변경(https://github.com/ljs970624/KKuTu/commit/b1c5c5071938fa8a3c9d26184424b3471766826a, https://github.com/ljs970624/KKuTu/commit/1050a5dca894123405f5c64895960f598230ebbd 등) 사항이 있어 말씀드립니다. 다소 번거로우시더라도 @ljs970624 님(의 변경 사항)과 저의 지적 재산 보호를 위해 저작권 관련 사항을 준수해 주시기 부탁드립니다.

**Comment by ljs970624** [comment]
초기 저작권 관련 사항이 기재되지 않은 소스코드를 다운받아 수정하여 누락된 부분으로 확인됩니다.

현재 수정하였으니 확인 부탁드립니다

**Comment by JJoriping** [comment]
https://github.com/JJoriping/KKuTu/commit/bc2ad206be5a9189184db95bd807064fcd2fd282
협조해 주셔서 감사합니다. 위 커밋을 참고해 주세요.

**Comment by ljs970624** [comment]
감사합니다 :)
