### ISSUE TITLE
끄투 로그인창 수정

### ISSUE THREAD

**Issue by Emily23805** [JJoriping/KKuTu#253]
끄투 로그인창 수정하고싶은데 어떤파일을 수정해야하나요?

**Comment by Kwon-JinSeok** [comment]
Server/lib/Web/views/login.pug, Server/lib/Web/public/css/in_login.css 를 수정해주면 될 듯 합니다.

**Comment by Emily23805** [comment]
그 처음접속시 나오는 화면 말한건데..................

**Comment by Kwon-JinSeok** [comment]
"로그인창" 수정이라고 말씀하셨지 않나요? 기본 페이지는 Server/lib/Web/views/portal.pug, Server/lib/Web/public/css/in_game_kkutu.css 를 수정해주시면 됩니다.

**Comment by Emily23805** [comment]
아 로그인창하고 처음접속시뜨는화면하고 제가 착각했네요 감사합니다
