### ISSUE TITLE
끄투 프리서버들의 GPL 위반 사항을 신고합니다.

### ISSUE THREAD

**Issue by L4by** [JJoriping/KKuTu#254]
안녕하세요, 먼저 귀중한 시간을 투자해 제작한 끄투를 모든 사람들이 호스팅할 수 있도록 허가해주신 쪼리핑님의 배려에 깊이 감사드립니다. 다름이 아니라, 현재 끄투 프리서버 목록에 등록되어 있는 프리서버들 중 GPL을 올바르게 이행하지 않는 서버들이 여럿 발견되어 이를 신고하고자 합니다. 본래 이메일로 연락드리려 했으나 이슈에 남기는 것이 맞는 것 같아 부득이하게 대체하는 점 양해해주시기 바랍니다. 글을 작성하는 시간인 2018년 1월 10일 오전 11시 50분 (KST 기준) 를 기준으로, GPL 위반 사항이 발견되는 것으로 보이는 서버는 다음과 같습니다.

1. 비트유끄투 **[주소](http://veatyou.xyz/) [Repo](https://github.com/minesna/vykkutu) [Repo Archive](https://archive.fo/C7RLT)**
- Fork가 아닌 직접 업로드 방식으로 원작자를 남기지 않았으며, 개작된 이후의 수정 사항을 공개하지 않은 것으로 보입니다.

2. 아리 끄투 **[주소](https://vtkkutu.kro.kr/) [Repo](https://github.com/Kwon-JinSeok/KKuTu) [Repo Archive](https://archive.fo/a6ugN) [Repo Archive 2](https://archive.fo/Y5Fek)**
- 쪼리핑님의 **[7f0c55d](https://github.com/yuedward0103/KKuTu/commit/7f0c55dbb37c4f5d0ddd21a69cb506d37bfeded8)** 커밋을 마지막으로 이후 개작된 사항들의 소스 코드를 일체 공개하지 않은 것으로 보입니다. 또한 새로 업로드된 레포지토리에서도 2.5.1 커밋을 마지막으로 일체 수정사항이 존재하지 않습니다.

3. 끄투닷넷 **[주소](http://끄투.닷넷) [Repo](https://github.com/hatty163/KKuTu) [Repo Archive](https://archive.fo/gjNkg)**
- #201 번 PR을 위한 **[10ced54](https://github.com/hatty163/KKuTu/commit/10ced546ac44aadf35e5a29a1685f1c9250c4207)** 커밋을 마지막으로 이후 개작된 사항들의 소스 코드를 일체 공개하지 않은 것으로 보입니다.

4. 과자끄투 **[주소](http://skkutu.kro.kr) [Repo](https://github.com/leeeunjae0215/skkutu) [Repo Archive](https://archive.fo/Mc5NM)**
- 모든 소스 코드 일체를 공개하지 않은 것으로 보입니다.

5. 갓투온라인 **[주소](http://game.갓투.kr:5) [Repo](https://github.com/godtuonline/KKuTu) [Repo Archive](https://archive.fo/sPJsA)**
- 쪼리핑님의 **[55553c3](https://github.com/godtuonline/KKuTu/commit/55553c363ef29edbd032c763bb75b163806e0fe6)** 커밋을 마지막으로 이후 개작된 사항들의 소스 코드를 일체 공개하지 않은 것으로 보입니다.

6. 라이트끄투 **[주소](http://litekkutu.oa.to:90) [Repo](https://github.com/shj0303/litekkutu) [Repo Archive](https://archive.fo/kVEe1)**
- Fork가 아닌 직접 업로드 방식으로 원작자를 남기지 않은 것으로 보입니다.

위와 같이 GPL 라이선스를 올바르게 이행하지 않은 것으로 보이는 프리서버들에 대해 검토해주시고 결과 회신 부탁드립니다. 다시 한 번 쪼리핑님의 배려에 감사드립니다.

**Comment by Kwon-JinSeok** [comment]
아리 끄투 - 해결 완료 하였습니다. 

새로운 레포지토리 주소 : https://github.com/Kwon-JinSeok/KKuTu

**Comment by KKHaneul** [comment]
@Kwon-JinSeok GPL에 대한 이해도가 조금 부족하신 것 아닌지 생각되는데, GPL을 표방하는 프로그램의 소스 코드를 개작하여 다른 사용자들에게 배포, 제공하고 있다면 해당 개작 소스 또한 공개해야 합니다. 하지만 새 레포지토리 주소로 가보아도 쪼리핑님의 2.5.1 PR Merge 커밋 이후의 변경사항이 존재하지 않습니다.

**Comment by shj0303** [comment]
라이트끄투 https://github.com/shj0303/LiteKKuTu 수정 완료하였습니다. 불편을 끼쳐드려서 죄송합니다.

**Comment by yangpa2449** [comment]
안녕하세요, 야채 끄투 (아리 끄투) 전 어드민 양파c입니다.
첫번째 Repo Archive에 있는 yuedward0103/KKuTu는 희망님이 올리셨고, 그때 당시엔 서버 개발이 진행되지 않았었습니다. GPL에 대해서 잘 몰랐어서 개발 이후에 올리지 못한 것에 대해 전 어드민으로서 죄송하다고 생각됩니다.

**Comment by hatty163** [comment]
끄투닷넷 - 해결 완료하였습니다.
https://github.com/hatty163/KKuTu

GPL에 대해 잘 몰라서 올리지 못한 것에 대해 대단히 죄송합니다.

**Comment by yunho0508** [comment]
끄투코리아도 GPL 위반에 해당 되는것 같습니다.

**Comment by hatty163** [comment]
내용 추가합니다. 위에 작성된 서버들을 제외한 2018년 1월 14일 정오(KST 기준) 를 기준으로, GPL 위반 사항이 발견되는 것으로 보이는 서버는 다음과 같습니다.

1. 끄투코리아 [주소](https://kkutu.co.kr/) [Repo](https://github.com/Kim-Daewoon/KKuTu) [Repo Archive](http://archive.is/rw4EA)
[4ed978f](https://github.com/Kim-Daewoon/KKuTu/commit/4ed978f9e2628961ff60348bc19adcd093b9c16e) 커밋을 마지막으로 이후 개작된 사항들의 소스 코드를 일체 공개하지 않은 것으로 보입니다.

위와 같이 GPL 라이선스를 올바르게 이행하지 않은 것으로 보이는 프리서버들에 대해 검토해주시고 결과 회신 부탁드립니다.

**Comment by minesna** [comment]
비트유끄투도 해결하였습니다
http://github.com/minesna/VYKKuTu

**Comment by BasixKOR** [comment]
@gamcats @godtuonline @leeeunjae0215 아직까지 소스코드가 업데이트되지 않은 3곳 프리서버의 Repo 소유자분들 호출합니다.

**Comment by leeeunjae0215** [comment]
그… 제 과자끄투 프리 서버는 종료를 하였는데… 그것도 혹시 라이선스 위반인가요?

Windows 10용 메일에서 보냄

보낸 사람: Basix
보낸 날짜: 2018년 2월 4일 일요일 오전 3:25
받는 사람: JJoriping/KKuTu
참조: leeeunjae0215; Mention
제목: Re: [JJoriping/KKuTu] 끄투 프리서버들의 GPL 위반 사항을 신고합니다. (#254)

@gamcats @godtuonline @leeeunjae0215 아직까지 소스코드가 업데이트되지 않은 3곳 프리서버의 Repo 소유자분들 호출합니다.

**Comment by leeeunjae0215** [comment]
네^^

Windows 10용 메일에서 보냄

보낸 사람: Basix
보낸 날짜: 2018년 2월 4일 일요일 오전 11:47
받는 사람: JJoriping/KKuTu
참조: leeeunjae0215; Mention
제목: Re: [JJoriping/KKuTu] 끄투 프리서버들의 GPL 위반 사항을 신고합니다. (#254)

@leeeunjae0215 그렇다면 문제가 없어보이네요. 좋은 하루 되세요!

**Comment by Kim-Daewoon** [comment]
끄투코리아 해결하였습니다.
늦어서 죄송합니다.
https://github.com/Kim-Daewoon/KKuTu

**Comment by sftblw** [comment]
서버 소프트웨어에서는 주로 AGPL을 쓰던 것 같은데 GPL에서 AGPL로의 라이센스의 변경이 필요하지 않을까요.

[GNU Affero GPL 설명](https://www.gnu.org/licenses/why-affero-gpl.ko.html) 인용

>(전략)
>
> 여기에는 하나의 추가 요건이 덧붙여져 있습니다. 만약 여러분이 서버에서 프로그램을 실행하여 그것이 서버 상에서 다른 사용자들과 통신하게 된다면, 여러분의 서버는 실행되고 있는 프로그램의 소스 코드를 사용자들이 다운로드 받을 수 있게 해야 한다는 것입니다.
>
> 그러나 주로 서버에서만 사용되는 프로그램을 생각해 보면, 개발자 홍길동은 개작한 프로그램을 자신의 서버에서만 실행하고 결코 배포하지 않을 수도 있습니다. 이렇게 되면 여러분은 개작된 판의 소스 코드를 결코 가질 수 없고 개작된 사항을 여러분 자신의 프로그램에 포함시킬 기회도 가질 수 없습니다. 여러분은 아마도 이러한 결과를 좋아하지 않을 것입니다.
>
> GNU Affero GPL을 사용하면 이러한 결과를 막을 수 있습니다. 
>
> (후략)

**Comment by BasixKOR** [comment]
@sftblw 좋은 생각이긴 하지맘 여기서 논의하긴 어려울 것 같네요. 따로 이슈를 생성해둘까요?

**Comment by KKHaneul** [comment]
@sftblw 좋은 생각이기는 하지만 AGPL로 라이선스를 변경하기 전의 코드들은 여전히 GPL로 배포되고 있을 것입니다. 처음부터 AGPL로 배포했으면 어땠을까 하는 생각이 드네요 :cry:
