### ISSUE TITLE
끄투 DB다루기

### ISSUE THREAD

**Issue by kkutu4444** [JJoriping/KKuTu#255]
gwalli페이지에서 
끄투 DB다루기에다 단어를 쳤더니 옆에 행동에 4가지(?) 버튼이 나오는데 그게 뭘의미하는지 알수있을까요

**Comment by JJoriping** [comment]
안녕하세요.
* ▲: 한 행 위로 (Shift 키를 같이 눌러 식별자 포함)
* X: 삭제
* ?: 식별자 편집
* ▼: 한 행 아래로 (Shift 키를 같이 눌러 식별자 포함)
보다 자세한 내용은 [소스 코드](https://github.com/JJoriping/KKuTu/blob/9e5f8e5de07818d2d74d79c2c5a4063c238e16dd/Server/lib/Web/lib/in_admin.js#L394)를 참고해 주세요.
