### ISSUE TITLE
끄투에 제 서버를 등록할때 서버 소유권을 어떻게 확인 하면 되나요?

### ISSUE THREAD

**Issue by 111222enter** [JJoriping/KKuTu#256]
제목그대로 입니다. 자세하게 알려주시길바랍니다. 제가 약간 초심자라서요... 
불편하시더라도 양해부탁드릴게요.

**Comment by TheRealTolspac** [comment]
다른 이슈를 찾아 보시는 것을 적극 추천드립니다.

**Comment by 111222enter** [comment]
어떻게 하는지 모르겠습니다. html 파일 만들어서 해봤는데도 아무반응이 없더군요.

**Comment by TheRealTolspac** [comment]
답변에 너무 늦어서 죄송합니다;;
*아래의 문장은 예시입니다.
먼저 http://kkutu.kr/kkutu-abc.html처럼
제시가 될것입니다.
그러면 `Server/lib/Web/public`에서
kkutu-abc.html을 파일명으로 만드시고,
`kkutu.kr`을 기입하시면 정상작동될것입니다.
