### ISSUE TITLE
서버가 정상정으로 열리지만 외부에서 들어와 지지 않습니다.

### ISSUE THREAD

**Issue by 111222enter** [JJoriping/KKuTu#257]
제목 그대로인데요. 이때는 어떻게 하면 되나요? 포트를 바꿔주어야 하는건가요?

**Comment by TheRealTolspac** [comment]
`포트포워딩`이나 `DMZ작업`을 해주셔야합니다.
만약 그래도 외부에서 안 들어와진다면,
`Server/lib/Web/main.js에서
Server.listen(80);을
Server.listen(50000); 등등으로 다이나믹 포트 사용을 권해드립니다.

**Comment by 111222enter** [comment]
해결되었습니다 감사합니다.
