### ISSUE TITLE
module.pug 및 ko_KR.josn 파일을 건드린 후

### ISSUE THREAD

**Issue by leeeunjae0215** [JJoriping/KKuTu#258]
제가 위 탭에 게임 탭과 갤러리 탭을 바꾸려고 했습니다
근데 게임탭은 정상적으로 바뀌었는데 갤러리 탭은 정상적으로 바뀌지 않아서 그냥 갤러리탭을
다시 원래대로 할려고 원래 상태로 바꿔놓고 서버를 재부팅 했는데 서버는 정상적으로
켜지지만 들어가 지지 않는군요

ERROR 문구 : 400 Bad Request

                       Your client has issued a malformed or illegal request.

라는 문구와 함께 400에러가 뜹니다

어떻게 해야할까요?

**Comment by JJoriping** [comment]
해당 오류는 구글 OAuth 부분에서 발생한 것으로 보이니, 관련 소스 코드나 구글 OAuth 설정을 올바르게 했는지 확인해 보세요.
