### ISSUE TITLE
구글 ID 어디에다 넣죠?

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#26]
제목 그대로 입니다

**Comment by yom21c1020** [comment]
API가 아닌 OAuth를 이용하셔야 합니다.
'사용자 인증 정보'로 가서 OAuth 클라이언트 ID를 하나 만드세요.

**Comment by kim-min** [comment]
클라이언트 ID는 어디에 등록하나요?

**Comment by msquid** [comment]
구글 아이디는 Server/lib/sub/jauth.js에 넣으시면 됩니다.

**Comment by msquid** [comment]
if(_err){ 
125 						JLog.warn("Error on profile-google: "+err.toString()); 
126 						R.go({ error: 500 }); 
127 					}else{ 
128 						try{ _doc = JSON.parse(_doc); }catch(e){ return R.go({ error: 500 }); } 
129 						if(_doc.error) return R.go({ error: _doc.error.code });*/ 
130 						 
131 						$p.type = "google"; 
132 						$p.id = doc.sub; 
133 						$p.name = doc.name; 
134 						$p.image = doc.picture; 
135 						 
136 						R.go($p); 
137 						/* 망할 셧다운제 
138  
139 						$p._age = _doc.ageRange; 
140 						if(_doc.birthday){ 

만약 넣어도 안된다면 jauth.js의 이 부분에서 R.go($p);를 추가하시면 됩니다.

**Comment by kim-min** [comment]
음... 아직도 안되네요. google.js도 만들어 봤는데 안되네요

**Comment by msquid** [comment]
구글 OAuth에서 제한사항 -> 승인된 Java 원본만 하셨나요? 안하셨다면 안됩니다.

**Comment by kim-min** [comment]
![12](https://cloud.githubusercontent.com/assets/13843919/23114157/adcbdd7a-f780-11e6-8360-3e0416099c90.JPG)
이렇게 하면 대부분 되지 않나요?

**Comment by msquid** [comment]
승인된 리디렉션 URI에서 http://kkutu.kr을 지우고 저장해보세요.

**Comment by kim-min** [comment]
![default](https://cloud.githubusercontent.com/assets/13843919/23115042/c90b3ea0-f785-11e6-90a2-00c7c97d9353.JPG)
여전합니다...

**Comment by msquid** [comment]
127.0.0.1에 접속하셨네요.
jjutu.kro.kr에 접속해보세요

**Comment by kim-min** [comment]
오오오 정상작동 합니다 감사합니다.
