### ISSUE TITLE
개발자도구 오류

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#262]
개발자도구를 켰더니 메모리가 수도없이 증가하여 컴터가 터집니다..

**Comment by hatty163** [comment]
이건 뭐... 어쩌라고 올리신 이슈인가요

**Comment by yunho0508** [comment]
이 오류는 끄투 오류가 아닌것 같습니다만

**Comment by JJoriping** [comment]
이 문제는 [electron-pug](https://github.com/yan-foto/electron-pug) 패키지가 일렉트론의 파일 읽기 요청을 올바르지 않게 처리해서 생기는 문제입니다. 직접 electron-pug 모듈을 편집하거나 이 모듈을 대체하는 다른 모듈을 사용해야 합니다.

**Comment by norhu1130** [comment]
@JJoriping 해당 이슈를 오픈한 유저는 계정이 삭제되었습니다.
이슈를 닫아주시기 바랍니다.
