### ISSUE TITLE
끄투 디버그 환경 설정 질문

### ISSUE THREAD

**Issue by BasixKOR** [JJoriping/KKuTu#263]
끄투 소스코드를 편집하고 있었는데, 이를 테스트하기 적절한 환경이 마땅치 않아 질문드립니다. 쪼리핑님이나 다른 분들은 어떻게 하고 계시는지요?

**Comment by TheRealTolspac** [comment]
저는 수준낮게 가상운영체제를 사용합니다...

**Comment by BasixKOR** [comment]
@TheRealTolspac 오, 좋은 방법 같네요. 참고할게요!
