### ISSUE TITLE
gwalli를 사용해 끄투 DB 검색 오류

### ISSUE THREAD

**Issue by gamcats** [JJoriping/KKuTu#264]
주제 (~부터 적으면 검색) 부분에 노인정 주제(예: 10(가톨릭)) 이런식으로 검색하면 다른 주제 단어까지 다 검색되는데 어떻게 해야 하나요?

**Comment by JJoriping** [comment]
`~` 이후에 작성하는 내용은 모두 정규 표현식으로 취급됩니다. 오직 10번 주제만을 갖고 있는 단어를 찾기 위해서는 `~10$`를 입력하면 됩니다.
