### ISSUE TITLE
쪼롤 리스트에서 정렬이 어떻게 되어있는건지 알수 있을까요?

### ISSUE THREAD

**Issue by shj0303** [JJoriping/KKuTu#265]
원래 제가 알고있는건 개설일 기준으로 정렬되어있는걸로 아는데 보니까 그건 아닌거같네요. 정렬 방식을 알수 있을까 하네요.

**Comment by ment12da** [comment]
Github 레포지토리 개설 일자를 따른다고 들었습니다.
