### ISSUE TITLE
모듈을 찾을 수 없다네요 제발 도와주세요ㅠㅠㅠ 서버 열리기 직전인데

### ISSUE THREAD

**Issue by ps2cho** [JJoriping/KKuTu#266]
서버 켜기를 눌렀더니 모듈을 찾을 수 없다고 뜹니다. 어떻게 해야할까요?

**Comment by CraftyDragon678** [comment]
로그 전체를 보여주세요

**Comment by TheRealTolspac** [comment]
readme.md을 다시 참고하시고 이 해결법을 봐주세요. 분명히 명시되있습니다.
`globol.inc.json` 파일 명을 `global.json`으로 바꾸시고,
마찬가지로 `auth.inc.json`  파일 명을 `auth.json`으로 바꾸시면 정상 작동하실것입니다.

**Comment by hatty163** [comment]
@ps2cho cmd에서 `cd` 명령어로 `./KKuTu/Server`로 이동하신 후 `npm install <패키지>`로 설치되지 않은 패키지를 설치하세요.
그리고 `server-setup.bat`을 실행한 적이 있다면 모듈은 찾을 수 있을텐데요

**Comment by TheRealTolspac** [comment]
너무 대충 말해서 죄송합니다.
`auth.inc.json` 파일과 `global.inc.json` 파일을
`auth.json` `global.json` 이런 식으로 바꾸시면 해결이 될 것 같습니다.
정말 죄송합니다 ㅠㅠ
