### ISSUE TITLE
GM설정을 어떻게 하나요?

### ISSUE THREAD

**Issue by pkpai0926** [JJoriping/KKuTu#27]
끄투 공식 서버에서는 GM은 **[GM]** 이라고 닉네임 앞에 붙은 걸 본 적이 있는데, 그것을 어떻게 설정하는지 궁금합니다. 단순하게 `/server/lib/sub.global.json` 파일을 수정하는 것만으로는 설정이 안 되네요.

**Comment by yom21c1020** [comment]
#23 이슈를 참고해 보세요. DB를 수정하셔야 합니다.
`UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '사용자 고유 ID';`
ID는 채팅창에서 `/id`를 입력하시면 됩니다.

**Comment by pkpai0926** [comment]
아 이미 관련된 이슈가 있었군요. 알려주셔서 감사합니다.
