### ISSUE TITLE
방을 만들었더니 오류가 납니다

### ISSUE THREAD

**Issue by minesna** [JJoriping/KKuTu#271]
방을 만들었더니
`[2018-02-21 07:02:40] Chan @0 Msg #102403092230212144801: {"type":"enter","title":"OOO님 ㅎㅇ","password":"","limit":"8","mode":"3","round":"5","time":"150","opts":{"injpick":[],"manner":true,"injeong":true,"mission":true,"loanword":false,"proverb":false,"strict":false,"sami":false,"no2":false,"onlyhighclass":false}} [2018-02-21 07:02:40] ERROR OCCURRED ON THE MASTER! :메인포트 [2018-2-21 07:02:40] ERROR: Error [ERR_IPC_CHANNEL_CLOSED]: channel closed Error [ERR_IPC_CHANNEL_CLOSED]: channel closed at ChildProcess.target.send (internal/child_process.js:588:16) at Worker.send (internal/cluster/worker.js:54:28) at exports.Client.my.enter (경로가림\Server\lib\Game\kkutu.js:561:14) at processClientRequest (경로가림\Server\lib\Game\master.js:1002:29) at Object.KKuTu.onClientMessage (경로가림\Server\lib\Game\master.js:676:3) at WebSocket.&lt;anonymous> (경로가림\Server\lib\Game\kkutu.js:298:11) at emitTwo (events.js:126:13) at WebSocket.emit (events.js:214:7) at Receiver.ontext (경로가림\Server\lib\node_modules\ws\lib\WebSocket.js:841:10) at 경로가림\Server\lib\node_modules\ws\lib\Receiver.js:536:18`
라 콘솔에 표시되며 방에 들어갈수 없어지고 만들수도 없어집니다.
원인을 알수있을까요 ㅠㅠ

**Comment by JJoriping** [comment]
이 메시지가 출력되기 전 어떤 이유로 인해 접속하려는 채널을 담당하는 프로세스가 종료된 것 같습니다.
