### ISSUE TITLE
The end of the string reached with no closing bracket ) found. 에러

### ISSUE THREAD

**Issue by ps2cho** [JJoriping/KKuTu#275]
doctype html
html
	head
		title= L('title')
		script(src="https:apis.google.com/js/platform.js")
		meta(name=google-signin-client_id" content="327745411377-2ojphk6hdkhgdthab42njtar70sovpja.apps.googleusercontent.com")
		+PageHead()
	body
		span#locale= JSON.stringify(LANG)
		span#stateKey= locals._id
		div.login-with= locals.text ? L(locals.text) : L('loginWith')
		div#with-google(style='border-radius: 5px; margin: 8px auto; width: 210px; overflow:
		hidden;')
		each val in loginList
		div.login-legal!= L('loginLegal')

이게 코드인데 왜 이런 에러가 뜨나요?

이게 오류입니다.

Error: D:\Users\user\Downloads\KKuTu-master\Server\lib\Web\views\login.pug:36:36 34| div#with-google(style='border-radius: 5px; margin: 8px auto; width: 210px; overflow: 35| hidden;') > 36| div.login-legal!= L('loginLegal') -------------------------------------------^ The end of the string reached with no closing bracket ) found.

**Comment by hatty163** [comment]
제발 에러 읽어보고 질문하세요..
The end of the string reached with no closing bracket ) found.는 괄호를 닫는 `)`가 누락되었다는 뜻입니다.

또한, 컴퓨터 지식이 없으면 서버를 열어도 유지보수가 힘듭니다. 컴퓨터 지식을 쌓거나 열지 않으시는 것을 권합니다.

**Comment by ps2cho** [comment]
그게 무슨 뜻인지는 아는데, 추가해보아도 똑같으니까 올린겁니다

**Comment by JJoriping** [comment]
`overflow:`와 `hidden;")` 사이 줄 바꿈이 있으면 안 됩니다.

**Comment by ps2cho** [comment]
줄바꿈을 없에었는데 여전히 안되네요

**Comment by ps2cho** [comment]
Error: D:\Users\user\Downloads\KKuTu-master\Server\lib\Web\views\login.pug:35:36 33| div.login-with= locals.text ? L(locals.text) : L('loginWith') 34| div#with-google(style='border-radius: 5px; margin: 8px auto; width: 210px; overflow: hidden;') > 35| div.login-legal!= L('loginLegal') -------------------------------------------^ The end of the string reached with no closing bracket ) found.
