### ISSUE TITLE
쪼롤 등록문제

### ISSUE THREAD

**Issue by Peter0630** [JJoriping/KKuTu#277]
"서버의 소유권을 확인하기 위해, 다음 주소로 접근했을 때 결과가 입력한 서버 주소와 같도록 처리해 주세요.

http://끄투.kro.kr/kkutu-dHA6Ly-rgY.html"

이 오류가 뜨는데 어떻게 처리하나요?

**Comment by TheRealTolspac** [comment]
Server/lib/Web/public에서
kkutu-dHA6Ly-rgY.html을 파일명으로 만드시고,
파일 안에는 `끄투.kro.kr`을 기입 해주세요.

**Comment by Peter0630** [comment]
"인증 파일의 내용이 올바르지 않습니다. 입력한 서버 주소와 같게 해 주세요." 이게뜹니다

**Comment by Peter0630** [comment]
"인증 파일의 내용이 올바르지 않습니다. 입력한 서버 주소와 같게 해 주세요." 이 오류가 뜹니다

**Comment by JJoriping** [comment]
한글이 올바르게 처리되지 않고 있습니다. 해당 파일의 인코딩 방식을 확인해 주세요.
