### ISSUE TITLE
jauth

### ISSUE THREAD

**Issue by Peter0630** [JJoriping/KKuTu#278]
jauth가 없어졌던데 뭘로 변했나요? auth.json과는 전혀 다르던데요

**Comment by ment12da** [comment]
#279 의 이슈와 같은 내용의 이슈로 추정됩니다. 이슈는 하나만 올려주시기 바랍니다.

jauth.js는 Passport 모듈로 변경하며 없어졌으며, 현재는 auth.json 에서 클라이언트 ID, 클라이언트 시크릿을 입력하여 별다른 조치없이 바로 소셜로그인을 본 서버에 적용시킬 수 있습니다.

만약 오류가 발생할경우 다른 이슈를 참고하여 주세요.

**Comment by ps2cho** [comment]
passport 는 어디에 있나요?

**Comment by ps2cho** [comment]
auth.json 만 부꾸면 로그인이 생기지 않습니다. 그리고 #279 에는 아무것도 써있지않습니다

**Comment by minesna** [comment]
auth 폴더안에서 jauth.js 역할을 하는것 같습니다.
