### ISSUE TITLE
깃헙올리는방법

### ISSUE THREAD

**Issue by ps2cho** [JJoriping/KKuTu#281]
깃헙에 소스 어케올려요?

**Comment by CraftyDragon678** [comment]
.. 그런거는 구글에 직접 검색해 보세요

**Comment by MintNetwork-Dev** [comment]
Git (버전 관리 프로그램) 사용법 :
https://rogerdudler.github.io/git-guide/

GitHub Desktop (더 쉽게 하실 수 있음) :
https://desktop.github.com/

**Comment by Alex4386** [comment]
Git (버전 관리 프로그램) 사용법 :
https://rogerdudler.github.io/git-guide/

GitHub Desktop (더 쉽게 하실 수 있음) :
https://desktop.github.com/ 

이 문서들이 조금이나마 도움이 될것 같습니다.

**Comment by Alex4386** [comment]
또한 issue를 올리기 전에 검색 먼저 해보시는 것을 추천드립니다.

**Comment by Alex4386** [comment]
P.S. 혹여나 자신이 GPL License 에 의거하여 소스코드를 제공하려고 하시는 거라면
이 레포지토리를 **Fork** 하신 후 생성된 자신의 레포지토리에 커밋하셔야 합니다.

**Comment by BasixKOR** [comment]
깃허브 이슈 란은 네이버 지식IN이 아닙니다.
