### ISSUE TITLE
쪼롤 CKKUTU[커밍순]

### ISSUE THREAD

**Issue by ps2cho** [JJoriping/KKuTu#284]
쪼롤에 보면 ckkutu 커밍쑨이라고 되있는데, 제 섭주가 ckkutu.kro.kr 이고 쪼롤에 올라와있는데, 이름이 같으면 안되는거아닌가요?

**Comment by Preta-Crowz** [comment]
쪼롤에 등록된 CKKUTU가 먼저 등록된 서버로 보입니다.
