### ISSUE TITLE
로그인 오류(로그인이 진행되지 않음)

### ISSUE THREAD

**Issue by bokmook** [JJoriping/KKuTu#286]
제목 그대로,
로그인 버튼을눌러 로그인을해봤습니다.
그런데, 게스트 상태로 그대로 있습니다.
계속 반복만 됩니다...
사진 첨부합니다.

1.로그인이 정상적으로 진행이 됩니다.
![image](https://user-images.githubusercontent.com/36400787/37822462-d8092670-2ec9-11e8-94d7-8d950306aaf6.png)

2.로그인이 정상적으로 됬지만 그대로 로그인이 되어있지 않습니다.
![image](https://user-images.githubusercontent.com/36400787/37822347-8552e04c-2ec9-11e8-9563-e9667e85ce1b.png)

+첨부사진_1
![image](https://user-images.githubusercontent.com/36400787/37822180-19d711ee-2ec9-11e8-9993-365afebce903.png)

+첨부사진_2
![image](https://user-images.githubusercontent.com/36400787/37821916-5be0a628-2ec8-11e8-9bcf-b9286a1bd4e2.png)

+2번에 주소가 ./code=4/AAARq3dBaMemg~ 가 뜹니다. (그 뒤에는 개인정보가 포함되있는 것 같아서 가렸습니다.)

어떻게 해야하죠?

**Comment by hatty163** [comment]
auth.json의 `callbackURL`을 끄투 서버의 주소가 아닌,
`http://서버.주소/login/google/callback`으로 설정하셔야 합니다.
