### ISSUE TITLE
리눅스 grunt 패치

### ISSUE THREAD

**Issue by SojuHanbyeong** [JJoriping/KKuTu#287]
리눅스에서 grunt패치하는 방법이 궁금합니다.
grunt 파일을 실행시켜도 안되고 터미널에 grunt를 쳐도 안됩니다.
grunt파일 경로까지 가서 grunt를 쳐도 명령어가 없다고 뜨면서 패치가 안됩니다.
sudo grunt를 쳐도 패치가 안됩니다.

**Comment by hatty163** [comment]
우선 bash에
`npm install -g grunt-cli` 쳐서 grunt 다운로드 받고 하셔야죠..
그리고 grunt 패치는 `sudo grunt`가 아니라 `./Server/lib` 폴더에 가셔서 `grunt default pack` 하셔야 합니다.

**Comment by SojuHanbyeong** [comment]
해결 완료하였습니다. 답변 감사합니다.
