### ISSUE TITLE
'불러오는중... 앞으로 1' 에서 계속 멈춤니다.

### ISSUE THREAD

**Issue by SeulSi** [JJoriping/KKuTu#288]
제목 말 그대로 저는 잘 들어가집니다. 다른분들도 메인까지는 잘들어와진다로 하시는데 게임에 들어오실때 자꾸 불러오는중... 앞으로 1 에서 멈춘다고 하십니다... 저도 해결하려고 하였지만 너무 어려워서 하지 못하였습니다... 돌머리인 저에게 쉽게 설명해 주시면 감사하겠습니다... 그리고 예전버전 깃도 올려주시면 감사하겠습니다...

**Comment by JJoriping** [comment]
안녕하세요. 연결 중 오류가 발생했을 가능성이 크니 F12 키를 눌러 개발자 도구를 연 뒤 콘솔 탭에서 오류 내용을 확인해 주세요. 끄투 소스 코드의 이전 버전은 모두 본 레포지토리에 포함되어 있으며 이에 관한 자세한 사항은 git에 대해 따로 학습하는 것을 권합니다.

**Comment by minesna** [comment]
포트포워딩을 80만 하신거 같네요.
#292 를 참고하여 추가로 포트포워딩 진행해주세요
