### ISSUE TITLE
내부네트워크에서 접속은 잘 되는데 외부에서 접속하면 "서버와의 연결이 끊어졌습니다" 가 나옵니다.

### ISSUE THREAD

**Issue by 3333303** [JJoriping/KKuTu#289]
제목 그대로입니다. 구축은 쉬운 설명 덕분에 간단히 할 수 있었지만 자꾸 외부에서 접속하면 연결을 끊어버리네요...

**Comment by hatty163** [comment]
포트포워딩 문제입니다.
`80` 포트, `MAIN_PORTS에 설정하신 포트(기본값:8080)`, `MAIN_PORTS에 설정하신 포트(기본값:8080) + 416`을 여셔야 합니다.
