### ISSUE TITLE
설치시.. 초기 DB 화일..

### ISSUE THREAD

**Issue by sonbonghee** [JJoriping/KKuTu#290]
끄투의 데이타 베이스화일이   POSTGRESQL 데이터 베이스인데.. 이거를 Mysql로 변환된 화일이 있을까요 ? 
아니면 POSTGRESQL 화일을 mysql로 변환해서 설치하면 잘 실행이 될까요 ?
 궁금합니다 지금 웹서버 환경이 mysql 환경이라서요..   혹시 변환해서 디비화일 사용이 가능할까요

**Comment by JJoriping** [comment]
기본적으로 PostgreSQL도 SQL을 사용하고 있기 때문에 해당 파일을 직접 파싱하여 MySQL 호환 파일을 구성할 수 있다고 생각합니다. 만약 그렇지 않다면, PostgreSQL 데이터베이스를 구축해 정보를 입력시킨 뒤 데이터베이스 정보를 긁어 MySQL 호환 파일로 출력하는 클라이언트를 직접 구현하는 방법이 있습니다.

**Comment by sonbonghee** [comment]
네.. 아마존 웹서비스도 정지먹을까요 ?

**Comment by hatty163** [comment]
@sonbonghee
.. 요점 파악 안되시나요? 통상적인 웹호스팅을 의미하는겁니다. AWS는 클라우드 서비스고요.

**Comment by minesna** [comment]
@hatty163 보는 사람이 불편 말투

**Comment by KKuTuIdiots** [comment]
@hatty163 병신 지도 지 서버 저작권 위반으로 신고당할 때 GPL이 뭔지도 몰랐으면서 니가 모르는 건 당연한거고 남이 모르는 건 개념가출한 싸가지없는 말뽄새로 까도 되는거냐? 하여간 애새끼들 말하는 뽄새가 씨발 ㅋㅋㅋㅋㅋㅋㅈㅋ

**Comment by JunhoYeo** [comment]
@KKuTuIdiots 다소 불편하신 마음은 이해합니다만 욕설은 자제하시는 것이 좋을 것 같습니다 ;(
