### ISSUE TITLE
서버증설 / 로비수정

### ISSUE THREAD

**Issue by SeulSi** [JJoriping/KKuTu#292]
끄투 처음에 주소 들어올때 로비는 어디서 수정하는건가요?

그리고 서버증설(끄투서버를 여러개로 나눔(마치 본섭처럼))은 어떻게 하나요?

서버인원수제한은 어떻게 변경하는건가요?

**Comment by SeulSi** [comment]
서버인원수제한은 어떻게 변경하는건가요?

**Comment by CraftyDragon678** [comment]
로비 페이지는 portal.pug에서 수정하실 수 있고요,
서버 증설은 루트 폴더에 있는 settings.json파일을 수정함을 통해 변경 하실 수 있습니다.(game-num-inst)
인원 수 제한은 수정 안해봐서 잘 모르겠네요...
