### ISSUE TITLE
쪼롤 등록문제

### ISSUE THREAD

**Issue by KRBlue** [JJoriping/KKuTu#294]
쪼롤에 사이트를 등록하기 위해 정보를 작성하고, 제출을 누르면 시간이 좀 오래 지나고 페이지 하나가 뜨는데 전송한 데이터가 없다고 뜨고 새로고침하면 오류가 납니다 ㅠ

**Comment by JJoriping** [comment]
안녕하세요. 문제가 있는 것으로 보이는 부분을 수정했으니 확인해 보세요.

**Comment by KRBlue** [comment]
혹시 몰라서 브라우저 세개로 확인해 봤습니다.(Chrome, Internet Explorer, Microsoft Edge)

--------------Chrome---------------

페이지가 작동하지 않습니다.
jjo.kr에서 전송한 데이터가 없습니다.
ERR_EMPTY_RESPONSE

----------새로 고침시---------

Cannot GET /kkutu/register

-----------Internet Explorer---------

이 페이지에 연결할 수 없음

•웹 주소 http://jjo.kr 이(가) 올바른지 확인하세요.
•Bing에서 이 페이지 검색
•페이지 새로 고침

------------새로고침 시------------

  | 웹 페이지를 찾을 수 없습니다.
-- | --
HTTP 404
  | 예측 가능한 원인:주소에 오타가 있을 수 있습니다.클릭한 링크가 만료된 것일 수도 있습니다.
  | 가능한 해결 방법:
  | 주소를 다시 입력하십시오. |   | 주소를 다시 입력하십시오.
  | 주소를 다시 입력하십시오.
  | 이전 페이지로 돌아갑니다.이전 페이지로 돌아갑니다. |   | 이전 페이지로 돌아갑니다.이전 페이지로 돌아갑니다.
  | 이전 페이지로 돌아갑니다.이전 페이지로 돌아갑니다.
  | 기본 사이트로 이동하여원하는 정보를 찾습니다. |   | 기본 사이트로 이동하여원하는 정보를 찾습니다.
  | 기본 사이트로 이동하여원하는 정보를 찾습니다.


-----------Microsoft Edge-----------


 | 이 페이지에 연결할 수 없음                                 다음을 시도해 보세요.                                                                                                           웹 주소가 맞는지 확인하세요.  http://jjo.kr                                     Bing에서 "http://jjo.kr" 검색                                     페이지 새로 고침                                                                                                                                                


세부 정보                                                                                                                                            웹 사이트와의 연결을 다시 설정했습니다.                                     오류 코드: INET_E_DOWNLOAD_FAILURE

--------새로고침 시에------

Cannot GET /kkutu/register

--------------------------------------------
