### ISSUE TITLE
턴 넘기지 않고 1번더하기

### ISSUE THREAD

**Issue by gameuser1234** [JJoriping/KKuTu#295]
한국어 끝말잇기 classic.js 에서 턴을 넘기지 않게 하려면 어떻게 해야 하나요?

**Comment by JJoriping** [comment]
[`./Server/lib/Game/kkutu.js`의 클래스 Room의 메소드 `turnNext()`](https://github.com/JJoriping/KKuTu/blob/55553c363ef29edbd032c763bb75b163806e0fe6/Server/lib/Game/kkutu.js#L1291)를 참고하세요.

**Comment by gameuser1234** [comment]
감사합니다.
