### ISSUE TITLE
사용법에 관해서.. 

### ISSUE THREAD

**Issue by sonbonghee** [JJoriping/KKuTu#296]
어렵게 우분투에 설치를 하였습니다. 
그런데..
--------------------------------------------------------------
경로 ./Server에서 다음 명령어들을 차례대로 실행합니다:
(게임 서버) node lib/Game/cluster.js 0 1
(웹 서버) node lib/Web/cluster.js 1
--------------------------------------------------------------
게임서버와 웹서버의 차이점이 뭔지 알고싶습니다. 두개 모두 실행시켜야 사용가능한건지요.? 
게임서버 실행하면.. 백그라운드로 안가서  컨트롤 C를 눌러 종료하고 웹서버로 넘어가야 하는데..
종료하고 웹서버만 해도 게임이 됩니다만.. ;;; 
웹서버만 실행하면 되는건지... 

궁금한 점이 많습니다. ;;

그리고 게임 단어사전을 한글 영어 모두 지우고.. 제가 만든 용어사전을 적용하고 싶습니다. 
만드는 방법을 모르겠어요. ㅜㅜ. 어디서 참고 가능할까요.. 

마지막으로 gpl 라이선스에 대한 이해도가 조금 부족합니다. 
양해 바라며.. 제가 웹페이지 자체를 수정해도 어디서 소스를 가져왔는지 공개하면 되는건가요? ;;
게임 웹 UI 변경에 관해서 입니다..   기능은 바꿀 능력이 안되고 디자인 효과음 아바타 정도요.. 
바꾸면 어떻게 허락을 받고 공지해야 할까요? ;;;;

**Comment by hatty163** [comment]
게임서버, 웹서버 둘다 실행해야 하며, **게임서버**를 먼저 실행하셔야 합니다. cmd(리눅스의 경우 bash) 창을 2개 여셔서 각각 게임서버, 웹서버 여시면 됩니다. 게임 단어사전은 게임 내 DB로 확인하므로, 따로 외부의 링크로 리다이렉트 시키시면 될 듯 합니다.
GPL 라이센스의 경우 **이용하시는 소스 코드를 (암호 등만 제외하고) 모두 공개하셔야 하며,** 소스 수정은 자유롭게 가능합니다.

**Comment by lshqqytiger** [comment]
게임 서버가 우리가 플레이하는 냉이, 다래 같은 서버일거구요 웹 서버가 주소로 들어가면 나오는 클라이언트일겁니다

**Comment by minesna** [comment]
@sonbonghee 혹시 ssh로밖에 리눅스에 접근할수 없는 상황이시라면
pm2를 사용해보시는것을 추천드립니다

**Comment by Helloyunho** [comment]
node lib/Game/cluster.js 0 1 & (앤터)
node lib/Web/cluster.js 1

이렇게 해보는것도 나쁘지 않을 것 같습니다
