### ISSUE TITLE
쪼롤 서버등록 문제

### ISSUE THREAD

**Issue by gameuser1234** [JJoriping/KKuTu#297]
쪼롤에 서버를 등록 할 때 주소와 암호를 입력했음에도 불구하고 주소와 암호를 입력하라고 하는데 해결해주시길 바랍니다.

**Comment by TheRealTolspac** [comment]
**제대로 찾아보시고 이슈 올리시죠 ^^;**

**Comment by JJoriping** [comment]
현재 정상 작동하고 있습니다. 다시 확인해 보세요.

**Comment by gameuser1234** [comment]
감사합니다.
