### ISSUE TITLE
로그인 구현 방법 질문

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#298]
![default](https://user-images.githubusercontent.com/39524005/40364278-dabcdad4-5e0c-11e8-99f2-f7973afcfb81.PNG)

로그인 어떻게 구현하나요? auth.json 에 NAVER 클라이언트 ID, 시크릿 집어넣어도 이상태네요..

**Comment by small-sunshines** [comment]
#252 참고해주세요

**Comment by lshqqytiger** [comment]
@small-sunshines .DIS 추가는 전에 시도해본 방법입니다만 Redis는 아직 안해봤네요. Redis는 어떻게 설치하나요?

**Comment by small-sunshines** [comment]
OS같은 서버 사양에 따라 설치방법이 조금씩 달라집니다. 그리고 확장자를 바꾸는 이유는 oauth에 관여하는 파일을 파일 이름의 패턴으로 찾아오기 때문입니다.

참고로 파일 확장자 바꿔주신 뒤에 웹서버를 다시시작하셔야 적용됩니다.

**Comment by lshqqytiger** [comment]
@small-sunshines 일단 로그인은 해결되었으나 관리자 설정법을 모르겠네요. global.json 에서 ADMIN 칸 안에 무엇을 써넣어야 하나요?

**Comment by small-sunshines** [comment]
그쪽은 이미 이슈에서 질문되었던 내용입니다. 잘 찾아보시면 GM설정 이라는 제목으로 올라온 같은 내용의 질문이 있습니다.

**Comment by lshqqytiger** [comment]
@small-sunshines 넵 찾아보겠습니다. 도와주셔서 감사합니다!

**Comment by lshqqytiger** [comment]
@small-sunshines 찾아보니 admin에 식별번호를 넣어야 한다는데 식별 번호가 /id 치면 나오는 건가요? 그리고 맞다면 #번호 로 나오던데 #도 포함인가요 아니면 숫자만 인가요?

**Comment by small-sunshines** [comment]
우선 이후 패치로 소셜로그인 제공사 구분용 고유코드도 같이 식별번호에 같이나옵니다.

/id 만 친다면 자신의 식별번호가 나오며, /id (유저 닉네임) (예시: /id 볕뉘) 로 친다면 그 유저의 식별번호가 나옵니다.

그리고 식별번호에서 # 은 포함되지 않습니다. 식별번호에는 영문 소문자와 -, 숫자만 들어갑니다.

**Comment by lshqqytiger** [comment]
@small-sunshines 제가 갖고 있는 파일은 패치 전 버전인가 보네요..#숫자 만 나옵니다..수정된 파일들을 찾아서 덮어쓰기 하면 될까요?

**Comment by small-sunshines** [comment]
네 그러면 될것같습니다

**Comment by lshqqytiger** [comment]
@small-sunshines 찾아보니 최근 레포지토리의 변경점은 없네요../id을 치면 #숫자만 나오고  /id (닉네임)을 치면 #영문소문자-숫자 이렇게 나오는걸까요?

**Comment by small-sunshines** [comment]
네

**Comment by lshqqytiger** [comment]
@small-sunshines 일단 집에 가서 해보겠습니다..게스트는 정상적으로 #영문숫자- 잘만 출력되는데 로그인 하면 #숫자만 출력되네요..

**Comment by small-sunshines** [comment]
게스트는 원래 랜덤 영문+숫자고요 회원이 위의 형식을 따릅니다.

**Comment by lshqqytiger** [comment]
@small-sunshines 위의 형식이 #영문+숫자죠? 일단 감사합니다. 너무 많이 질문드리는것 같아 죄송합니다.

**Comment by small-sunshines** [comment]
아뇨 제공사 식별코드-숫자 입니다.

**Comment by lshqqytiger** [comment]
@small-sunshines 정말 감사합니다! 덕분에 해결했습니다!
