### ISSUE TITLE
시간 속도 조절 방법

### ISSUE THREAD

**Issue by soonsoo12345** [JJoriping/KKuTu#299]
혹시 그 파란색 초가 줄어드는 속도를 빠르게 바꿀수 있나요?
![image](https://user-images.githubusercontent.com/34093441/40846314-3215a182-65f4-11e8-8449-9730a348b272.png)

**Comment by hatty163** [comment]
@soonsoo12345 가능합니다. 만약 5초를 추가하고 싶다고 가정하면,
우선 `KKuTu/Server/lib/Web/views/kkutu.pug`의 `select#room-time` 항목 하단에 `option(value=5)`처럼 추가해 주시고, `KKuTu/Server/lib/Game/master.js`의 `const ENABLE_ROUND_TIME = exports.ENABLE_ROUND_TIME = [ 10, 30, 60, 90, 120, 150 ];` 항목을 `const ENABLE_ROUND_TIME = exports.ENABLE_ROUND_TIME = [ 5, 10, 30, 60, 90, 120, 150 ];` 처럼 바꿔주시고 `KKuTu/Server/lib`에서 명령어 `grunt default pack`를 실행하시면 됩니다.

**Comment by pprcYT** [comment]
근데 150초부터 시작하는데 어쩌죠?
