### ISSUE TITLE
셧다운제 로그인

### ISSUE THREAD

**Issue by msquid** [JJoriping/KKuTu#30]
셧다운제 주석을 해제하고 ajae.js를 넣고 로그인 해보니
Bad Request라 뜨네요. 해결 방법이 없을까요?

**Comment by JJoriping** [comment]
우선 서버 소스 코드 내에서 400 Bad Request 응답을 보내는 부분을 확인해 보세요. `res.sendStatus(400)`이라고 검색하면 잘 나올 겁니다. 그런 뒤에 이 부분 위에서 `res.sendStatus(400)` 실행을 유도하는 요소들의 값이 각각 어떻게 설정되어 있는지 `console.log(...)` 함수 등으로 확인해 보세요.

**Comment by msquid** [comment]
!req.session.token 부분이네요.
