### ISSUE TITLE
끄투 구축 중입니다만...

### ISSUE THREAD

**Issue by endom4086** [JJoriping/KKuTu#300]
로그인을 구현할려고합니다...

auth.js에 구글 시크릿을 넣었습니다.
근데 로그인을 누르면 구글 로그인이 안 나오더군요...

어떻게 하면 활성화 할 수 있을까요?

두 번째는 끄투 UI관련 입니다.

끄투 메인화면(도메인으로 접속하면 나오는 화면)의 UI를 바꾸고 싶습니다만..

바꾸는 파일을 찾을수가 없네요...

여러 이슈들 찾아 봤는데 다른 이슈 언급하지 마시고 여기에 해결책 올려주세요..

**Comment by KRBlue** [comment]
auth.json에 입력하시고 auth_google.js 옆에 .DISBLED 가 붙어있나요? 붙어있으면 빼주셔야 작동합니다. 끄투 UI는 Server\lib\Web\views 이곳에 있습니다. portal.pug가 메인화면이구요 module.pug가 상단입니다. kkutu.pug는 끄투 게임화면이구요. 옆에 m_kkutu 이런식으로 된건 모바일 웹페이지 UI입니다.

**Comment by KRBlue** [comment]
@endom4086 포트포워딩 80포트와 서버에 들어가는 포트들을 열어주어야 합니다. 그리고 구글 API에서 도메인 설정을 해두셨나요?

**Comment by endom4086** [comment]
@KRBlue 도메인 설정을 해놓았지만, 포트포워딩이 안 되어 있어여...
지금은 도메인이 하마치 IP로 되어있어여

**Comment by KRBlue** [comment]
@endom4086 포트포워딩 하시고 도메인을 하마치가 아닌 컴퓨터의 외부IP로 설정해보세요.

**Comment by endom4086** [comment]
@KRBlue 등록해논 도메인이 내도메인.한국에서 한거라서...

그냥 IP포워딩의 IP를 바꿔도 될까요?

**Comment by KRBlue** [comment]
@endom4086 제가 내도메인.한국을 안써봐서 모르겠네요... oa.to나 도메인을 구매해서 쓰곤 해서...
도움이 되지 못해 죄송합니다.

**Comment by minesna** [comment]
상관 있고 없고가 중요한게 아니라 하마치 아이피로 하면 당연히..

**Comment by endom4086** [comment]
큐큨 그렇죠?
포트포워딩 빨리 해야되는데 시간이 없어서...

**Comment by minesna** [comment]
원하신다면 해드리겠습니다 minesna#9163으로 문의주세요

**Comment by Sichisky** [comment]
minesna님 하마치 아이피로 하면 당연히 안된다는 의미신..건가요 혹시?

**Comment by minesna** [comment]
@Sichisky 승인된 자바스크립트 원본에서 막힐꺼 같습니다만

**Comment by Sichisky** [comment]
음, 제가 학생이고 이슈를 통해 하는 법들을 배우며 저와 친구들이 즐기려고만 해 보면서 해보았습니다만..
자바에 대해 공부를 시작한 새내기라, 무슨 뜻이신지는 잘 모르겠으나 전 하마치를 이용해 네이버 로그인에 성공했습니다. 그리고, 구글 로그인도 성공했습니다.
![_2018_07_12_21_26_42_527](https://user-images.githubusercontent.com/31066511/42633102-f31dae52-85ce-11e8-8525-1827c882a294.png)

이 사진은 네이버로 로그인을 진행하였습니다.

**Comment by endom4086** [comment]
@Sichisky 혹시 현재 소스 파일을 메일로 받을 수 있을까요?
물론 예민한 로긴 코드는 제외하고요.

**Comment by Sichisky** [comment]
@endom4086 음.. 딱히 수정한게 없어서 초기 파일을 받는것과 같습니다.
제가 설정한건 auth.json 에 콜백 주소, 구글 아이디, 시크릿과 auth_google.js.DISABLED 를 auth_google.js 로 변경하였을 뿐 입니다.

**Comment by minesna** [comment]
@Sichisky 제가 헷갈렸나보네요

**Comment by Sichisky** [comment]
@minesna 알겠습니다. 좋은 하루 보내세요 :)

**Comment by Sichisky** [comment]
@endom4086 해결 안 되신다면 디스코드 같은 것들로 도와드리겠습니다.
