### ISSUE TITLE
단어 추가 오류

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#301]
global.json 에 있는 PASS 를 1234hihi 로 해두었습니다. 친구랑만 할 거라..
그다음 gwalli에 들어가서 암호를 1234hihi, 테이블을 postgres로 해두고 단어 추가를 시도했는데 조회도 안되고 아무것도 되질 않았습니다.

뭐가 문제일까요..?

**Comment by TheRealTolspac** [comment]
`table`은 `kr`이나 `en`을 기입해주시면 되요 :)
(`kr`은 `KO_KR.json`이 수정이 되고, `en`은 `EN_US,json`이 수정이 됨)

**Comment by Sichisky** [comment]
아하 오랜만이라 헷갈렸네요 감사합니다!

**Comment by Sichisky** [comment]
끄투 DB에 단어 추가하기에서 위에 주제에 class_1 라고 적고 큰 네모에 할 단어를 적으면 되는건가요? 제가 암호에 1234hihi로 하고 테이블을 KR로 했는데 안되서요.

**Comment by minesna** [comment]
‘ko’ 아닌가요?

**Comment by Sichisky** [comment]
감사합니다!
