### ISSUE TITLE
구글 소셜 로그인

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#303]
#285 와 같이 오류가 뜹니다. 그에 답변해서는 
console.developers.google.com 에서 google+ api를 활성화 하라고 하셨는데,
정확히 어디서 할 수 있는건지 찾지 못했습니다. 알려주실 수 있을까요?

**Comment by TheRealTolspac** [comment]
https://console.developers.google.com/apis/library에서
google+ api 검색 후 사용 설정

**Comment by Sichisky** [comment]
해결했습니다, 감사합니다!
