### ISSUE TITLE
쪼롤 서버목록 닫힘 표시

### ISSUE THREAD

**Issue by KRBlue** [JJoriping/KKuTu#304]
서버는 열려있는데 쪼롤 서버목록에서는 닫힘으로 뜨는데 이거 왜이런가요
![image](https://user-images.githubusercontent.com/38885432/42722340-725dab7e-8785-11e8-9384-656e7449e392.png)

**Comment by CraftyDragon678** [comment]
확인해본 결과 정상적으로 온라인 뜹니다!

**Comment by Sichisky** [comment]
서버에서 출력하는 결과를 옮기는게 아니라 인터넷에서 계산하고 띄우는게 아닐까요?

**Comment by CraftyDragon678** [comment]
@Sichisky 서버에서 출력하는 결과 입니다. 서버 등록시 /servers 와 /global_notice.html로 get 요청을 30초, 5분마다 보낸다는 것에서 알 수 있죠..

**Comment by minesna** [comment]
정상적으로 뜨는거 같으니 이슈 닫아주세요 :)
