### ISSUE TITLE
쪼롤 등록문제

### ISSUE THREAD

**Issue by legendkim5216** [JJoriping/KKuTu#305]
쪼롤 등록시 알림으로
서버주소 와 암호를 입력해주세요 라고 뜹니다;;
이거 해결어떻게 하나요?
https://cdn.discordapp.com/attachments/468399683409149952/470426129745051688/6e0fb275b0651c58.PNG

**Comment by hatty163** [comment]
서버 이름에는 특수문자(!)를 빼고 시도해 보십시오.

**Comment by legendkim5216** [comment]
네 일단 해보겠습니다.
