### ISSUE TITLE
2.5.1 버전 어캐열어야 하나여?

### ISSUE THREAD

**Issue by hjki001** [JJoriping/KKuTu#306]
옛날에 끄투 구축했던것이생각이나서 하려하는데
원래는 db넣기 ->설정(sub/글로벌.json 열고 pg_pass 수정 -> run.bat실행 ->창뜨면 서버시작 ->db is ready 라 나오면 접속 ㅇㅇ) 이거였는데 지금은 글로벌.json이 사라져서 다음을 진행을못해여 다른방법이없을까여?

**Comment by TheRealTolspac** [comment]
global.inc.json을 global.json으로 바꾸세요.

**Comment by hjki001** [comment]
저기 그 inc으로 된것 바꾸고 나서 설정했음에도 불구하고 무슨일인지 오류가납니다

**Comment by minesna** [comment]
무슨 오류 나시나요?

**Comment by hjki001** [comment]
오류 해결했습니다 auth 쪽 문제였네요 ㅎㅎ 여튼 이제 해결됬으니 이 레포지토리는 닫겠습니다 도와주신분들 감사드리고 그리고 열사병 조심하세요 :)
