### ISSUE TITLE
끄투 프리서버들의 GPL 위반 사항을 신고합니다.

### ISSUE THREAD

**Issue by kdhkr** [JJoriping/KKuTu#307]
2018년 7월 27일 정오(KST 기준) 를 기준으로, GPL 위반 사항이 발견되는 것으로 보이는 서버는 다음과 같습니다.

- 끄투코리아 [레프지토리](https://github.com/KKuTu-Korea/KKuTu)  [아카이브](http://archive.is/rmYcC)
최근 수정일 6월 16일 이후 수정 사항이 레프지토리에 업로드되지 않았습니다.

- Prj_KT [레프지토리](https://github.com/Preta-Crowz/Prj_KT)  [아카이브](http://archive.is/2jksS)
최근 수정일 4월 20일 이후 수정 사항이 레프지토리에 업로드되지 않았습니다.

- 갓투 [레프지토리](https://github.com/godtuonline/KKuTu)  [아카이브](http://archive.is/tqwKU)
개작된 소스를 일체 공개하지 않았습니다.

- 치투 [레프지토리](https://github.com/soonsoo12345/KKuTu)  [아카이브](http://archive.is/KQ2Sl)
개작된 소스를 일체 공개하지 않았습니다.

이외에도 몇 서버가 더 있으나, 이 서버들은 이미지 수정이나 업데이트 로그 수정 등 미미한 작업을 하였기에 직접 접속하여 파일을 받을 수 있기 때문에 제외시켰습니다. 결과 회신 부탁드립니다. 감사합니다.

@kdwkr @Preta-Crowz @godtuonline @soonsoo12345 분들은 조치 부탁드립니다.

**Comment by minesna** [comment]
손훈님이 운영하는 갓투의 깃허브는 다음과 같습니다 :
https://github.con/sonhun/kkutu
이슈를 열었을때에를 기준으로선 공개하고있는 것으로 보입니다

**Comment by sonhun** [comment]
31일자 업데이트 처리완료.
https://github.com/sonhun/KKuTu

**Comment by Preta-Crowz** [comment]
중요 사항 업데이트 중, 업데이트 시작 이전의 파일이 없어 업데이트 완료 후 업로드 예정입니다.

**Comment by Preta-Crowz** [comment]
업데이트 미뤄져서 일단 업데이트 완료했습니다

**Comment by Alex4386** [comment]
2019년 4월 22일 KST 14시 03분 현재도 갱신되고 있지 않습니다.
관련 서버 Maintainer/Administrator 들은 현재 KKuTu Software가 Free Software Foundation에서 제시하는 GPL Violation에 해당 하기 때문에, 공개할 것을 권장합니다. 

* 배포판에 GPL 원문이 포함되어 있는가?
* GPL에 의해서 배포되는 소프트웨어라는 사실이 명시되어 있는가? GPL로 선언된 소프트웨어가 아님에도 불구하고, GPL에 의한 소프트웨어라는 인상을 줄만한 문구가 포함되어 있는가?
* 배포판에 소스 코드가 함께 제공되고 있는가?
* 배포판이 바이너리, 즉 실행 파일만으로 구성되어 있다면 네트워크를 통한 배포와 같이 별도의 방법으로 소스 코드를 제공한다는 명시적인 확약이 있는가?
* 제공되는 소스 코드가 완전한 형태이거나 GPL 이외의 라이센스 조건을 따르는 모듈들과 함께 연동해서 사용할 수 있도록 만들어졌는가?

만약, 위와 같은 확인을 통해서 GPL 위반이라는 판단이 선다면 소프트웨어의 이름과 그 제품을 배포하고 있는 개인이나 단체의 이름 그리고 그들과 연락할 수 있는 주소와 전화 번호 등의 정보를 위반 사항과 함께 자세히 적어서 GPL에 대한 적용이 잘못되고 있음을 저작권자에게 알려주시기 바랍니다. 저작권자란 소프트웨어가 GPL로 관리되도록 선언할 수 있었던, 해당 소프트웨어에 대한 법률적 권리를 갖고 있던 사람을 의미합니다.

출처: [https://www.gnu.org/licenses/gpl-violation.html](https://www.gnu.org/licenses/gpl-violation.html)  
  
---
또한 이 상황에 대해서 소스코드 공개 없이 진행 하는 것은 엄연한 라이선스 위반 및 저작권 침해 행위로 간주됩니다.  

해당 사항에 관련되어서 오픈소스SW 라이선스 종합 정보 시스템의 라이선스 의의 부분, 그리고 아래 첨부한 GPLv3요약본을 참고 하여 주시기 바랍니다.
[https://www.olis.or.kr/license/introduction.do](https://www.olis.or.kr/license/introduction.do)
[https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

**Comment by Preta-Crowz** [comment]
과거 원작자와 디스코드 DM을 통해 해당 내용에 대해 대화를 했던 적이 있으며, 해당 대화에서 도출된 결론은 "GPL의 영향을 받지 않는다"였습니다.
GPL의 경우 클라이언트 등을 사용자에게 배포 할 경우에만 적용이 되기 때문이며, 서버만이 사용될 경우엔 AGPL을 적용하여야합니다.

**Comment by Alex4386** [comment]
@Preta-Crowz **원작자의 의사 표시와 해당사항은 관련이 없습니다**
해당 사항을 적용하려면 UNLICENSED로 Re-Licensing하는 방법이 있습니다.

**Comment by Preta-Crowz** [comment]
@JJoriping

**Comment by JJoriping** [comment]
2020년 1월 1일 AGPL 전환에 따라 본 이슈를 닫습니다.
