### ISSUE TITLE
깃헙에 레포지토리 올리는 방법

### ISSUE THREAD

**Issue by JuyoungK1m** [JJoriping/KKuTu#308]
깃헙에 레포지토리 올리는 방법좀 알려 주세요 올려야 되는데 어떻게하는지 몰라요;;;

**Comment by KRBlue** [comment]
그런건 네이버에 검색해주세요 여기가 지식in은 아닙니다 ;;

**Comment by minesna** [comment]
#281 참고하세요

**Comment by KRBlue** [comment]
@KKuTuIdiots 그런 욕설은 자제 바랍니다

**Comment by kkutu-hoos** [comment]
욕설이라니;; 깃헙도 어려운 사람들이 많거든요? 사이버 수사대에 신고도 가능한데;;
