### ISSUE TITLE
끄투 로그인 기능 구현 방법

### ISSUE THREAD

**Issue by kkutu-hooss** [JJoriping/KKuTu#309]
끄투 로그인 기능 구현 방법을 잘 모르겠습니다. 좀 알려주시길바랍니다

**Comment by KRBlue** [comment]
Server\lib\sub 들어가시면 auth.json이나 auth.inc.json이 있을겁니다. auth.inc.json은 .inc를 지워주시고, auth.json을 열고 api 키와 시크릿 키 등을 입력해주시면 됩니다.

**Comment by minesna** [comment]
API 는 
https://developers.kakao.com
https://console.developers.google.com
https://apps.twitter.com
https://developers.facebook.com
https://developers.naver.com
에서 하실수 있으십니다

**Comment by CraftyDragon678** [comment]
> 시크릿 코드는 뭐죠

API 만드시면 얻으실 수 있습니다.

**Comment by kkutu-hoos** [comment]
오 찾았습니다 시크릿 코드도 적었는데... 안나오네요.......

**Comment by KRBlue** [comment]
혹시 확장자 뒤에 .DISABLED를 지워보셨나요

**Comment by kkutu-hoos** [comment]
auth_~~~~~~~~~~~.js 밖에 없는데요 DISABLED는 원래 없네요.......

**Comment by KRBlue** [comment]
그럼 애초에 로그인 기능에서 오류나는걸로 압니다...

2018년 8월 9일 (목) 오후 8:46, hooss <notifications@github.com>님이 작성:

**Comment by Preta-Crowz** [comment]
> 오 찾았습니다 시크릿 코드도 적었는데... 안나오네요....... 로그인 버튼이.......................

사용하지 않는 로그인은 파일명을 변경해주세요.
ABC 순으로 파일을 불러오기 때문에 중간에 오류가 냘 경우 냐머지가 로드되지 않습니다.
기본 순서는 페이스북, 구글, 카카오, 네이버, 트위터입니다.

**Comment by kkutu-hoos** [comment]
해결 됬습니다!
