### ISSUE TITLE
실시간으로 공지를 보내는 기능을 사용하는 방법

### ISSUE THREAD

**Issue by pkpai0926** [JJoriping/KKuTu#31]
실시간으로 모든 유저들에게 공지를 날릴 수 있는 기능이 있었던 것 같은데, 그 기능을 사용하는 방법이 무엇인가요? 소스를 살펴보니까 `yell` 인 것 같은데 도무지 사용방법을 모르겠습니다.

**Comment by JJoriping** [comment]
채팅으로 `#yell (내용)`을 입력하면 됩니다. 다만 아직 모든 서버에 대해 메시지를 보낼 수는 없으므로 참고해 주세요.
