### ISSUE TITLE
끄투 서버구축하는데 키보드가;;

### ISSUE THREAD

**Issue by tjsgh5965** [JJoriping/KKuTu#310]
서버를 구축하기 위해 createdb.exe파일로 접속을 하는데 성공해서
암호를 입력해야 합니다.
그러나 엔터키랑 Alt+F4키를 제외한 그 어떤 조작키도 작동되지 않습니다.
그렇다고 메모장/다른 콘솔 등등에는 어떤 조작키든지 작동합니다.

한마디로 정리하면 , 암호를 입력할 때만 조작키가 작동되지 않습니다;;
어떻게 해야 하나욥?

**Comment by minesna** [comment]
암호는 입력되고 있는것입니다.
다만 보이지 않을 뿐이죠
