### ISSUE TITLE
GM권한 어떻게해야 받을 수 있는건지

### ISSUE THREAD

**Issue by SJang1** [JJoriping/KKuTu#311]
서버구동까지 모두 정상적으로 완료하고 auth설정도 하여 로그인도 완료하였으나, GM을 못받고 있습니다.
/server/lib/sub/global.json에서 "ADMIN": [ "Input admin id here" ], 에 ID를 적어 넣었는데도 권한을 획득하지 않는데, 어찌해야 GM을 받을 수 있는지요?

**Comment by minesna** [comment]
GM 휘장 말하시는거 같으신데..
관리페이지(/gwalli)에서 유저 DB 다루기에 자신의 아이디를 적고 조회를 해보세요
그후 box칸에  {"b1_gm":1}을 넣고 적용을 해보시면
자신의 보관함(?)에 휘장이 있을꺼에여

**Comment by SJang1** [comment]
관리 페이지 자체도 접속이 안되고 있었는데 좀 더 만지다보니까 좀전에 됬네요 어쨌든 감사합니다.
