### ISSUE TITLE
휘장추가관련

### ISSUE THREAD

**Issue by hjki001** [JJoriping/KKuTu#313]
휘장하나를 추가했는데 한번 써볼려고 db에서 아이템(추가한거) 를 gm계정에 추가 시킬려하는데 계속 오류 "users"이름의 릴레이션이없습니다. 가 뜨네여..   어캐해야 재대로 될까여??

**Comment by CraftyDragon678** [comment]
데베에 잘 추가되지 않은 것 같은데.. 아마 영어로 하면 relation not found (postgres)이고,
이 오류는 테이블이 없을 경우 나타나는 것으로 보입니다. 테이블을 확인해 주시고 추가해 주세요

참고 : https://www.google.com/search?q=%EC%9D%B4%EB%A6%84%EC%9D%98+%EB%A6%B4%EB%A0%88%EC%9D%B4%EC%85%98(relation)%EC%9D%B4+%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4&sourceid=chrome&ie=UTF-8
https://search.naver.com/search.naver?ie=UTF-8&sm=whl_hty&query=%EC%9D%B4%EB%A6%84%EC%9D%98+%EB%A6%B4%EB%A0%88%EC%9D%B4%EC%85%98(relation)%EC%9D%B4+%EC%97%86%EC%8A%B5%EB%8B%88%EB%8B%A4
https://www.google.com/search?q=relation+not+found+postgres&sourceid=chrome&ie=UTF-8
