### ISSUE TITLE
이거 오류 해결법 아시는분?.. (Windows)

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#314]
앞의 과정 다 마치고 마지막으로 run.bat을 실행했는데
module.js:549 throw err; ^ Error: Cannot find module './sub/global.json' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.&lt;anonymous> (C:\Users\백승우\Desktop\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)
G: CLOSED WITH CODE 1
module.js:549 throw err; ^ Error: Cannot find module '../sub/global.json' at Function.Module._resolveFilename (module.js:547:15) at Function.Module._load (module.js:474:25) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Object.&lt;anonymous> (C:\Users\백승우\Desktop\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3)
Worker 4272 died
W: CLOSED WITH CODE 0

이런 오류가 뜨더라고요...
이거 해결해주실분 있나요..?

**Comment by hjki001** [comment]
저오류는 global.json 를 찾을수없다는오류입니다.
C:\Users\백승우\Desktop\KKuTu-master\Server\lib\sub 여기를 한번살펴보시면 global.inc.json이있을겁니다 거기서 inc 이글자만 지워주신뒤 해보세여
