### ISSUE TITLE
끄투 서버 만들고 싶은데 어떻게 만듬?

### ISSUE THREAD

**Issue by wkddnjsdn360** [JJoriping/KKuTu#315]
서버 만들고 싶은데 어떻게 만들어요? 윈도우 10

**Comment by minesna** [comment]
https://github.com/JJoriping/KKuTu/blob/master/README.md

**Comment by hjki001** [comment]
적어도 저분(wk님)은 하려는노력은하는데 KKutuIdiots님은 입만나불거릴줄알지 서버운영못하잖?

**Comment by minesna** [comment]
p{margin-top:0;margin-bottom:0}
    


    이슈에서 자제
--------- 원본 메일 ---------

    
        보낸사람: KKuTuIdiots <notifications@github.com>
        받는사람: JJoriping/KKuTu <KKuTu@noreply.github.com>
        
            참조: minesna <admin@veatyou.kro.kr>, Comment <comment@noreply.github.com>
        
        날짜: 18.08.10 18:19 GMT +0900
        제목: Re: [JJoriping/KKuTu] 끄투 서버 만들고 싶은데 어떻게 만듬? (#315)
        
        
    
    
        리드미를 장식으로 아는 사람한테 누가 그런거 답변해주고 싶을까 ㅋㅋㅋ

**Comment by lshqqytiger** [comment]
README 읽어주시고 해결 되셨으면 이슈는 닫아주세요.
