### ISSUE TITLE
경험치량 수정 어떻게 하는지 아시는분?

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#316]
맥스 레벨이 720이 되어서 경험치 획득량을 늘리려고 하는데 점수를 더 많이 얻게 하는 방법 말고 경험치를 직접적으로 많이 늘리는 방법 없나요

**Comment by CraftyDragon678** [comment]
점수를 계산하는 부분이 kkutu.js파일의 getRewards에 있습니다.

**Comment by Preta-Crowz** [comment]
kkutu.js의 1384번째 줄 getRewards를 수정하면 됩니다.
