### ISSUE TITLE
psql에 대해서 아무것도 몰라서 질문합니다만

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#32]
psql 콘솔에서 UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '사용자 고유 ID'; 를 하는 것은 알고 있는데, psql 콘솔의 어디서 입력하는 지 모르겠습니다. 알려주시면 감사하겠습니다.

**Comment by JJoriping** [comment]
우선 psql을 실행하기 전 `--dbname main` 플래그를 넣거나 psql 콘솔 내에서 `\connect main` 명령어를 입력하여 SQL을 적용시킬 데이터베이스를 선택한 뒤 해당 SQL을 실행시키면 됩니다.

**Comment by kim-min** [comment]
UPDATE users SET box = '{"b1_gm":1}' WHERE _id = '사용자 고유 ID'; 를 그러면 어떤 데이터베이스에 설치해야 하나요? (경로까지 말해주시면 감사하겠습니다)

**Comment by JJoriping** [comment]
데이터베이스 이름이 `main`입니다. 위 방법으로 *현재 데이터베이스*를 `main`으로 설정한 뒤 해당 SQL을 입력하세요.

**Comment by kim-min** [comment]
죄송합니다만... 현재 데이터베이스를 main으로 어떻게 설정하나요;;; (정말 죄송합니다)

**Comment by yom21c1020** [comment]
`--dbname main` 플래그와 `\connect main` 명령어 모두 `main` 데이터베이스를 선택하는 명령어입니다.

**Comment by kim-min** [comment]
음.. 업데이트는 정상적으로 된것 같지만, GM 휘장이 자동으로 붙지 않네요. 어떻게해야 할까요?

**Comment by yom21c1020** [comment]
원래 자동으로 붙지 않습니다. 아이템에서 GM 휘장을 선택하셔야 합니다.

**Comment by kim-min** [comment]
감사 드립니다! 드디어 적용했네요!
