### ISSUE TITLE
레벨 확장

### ISSUE THREAD

**Issue by 3333303** [JJoriping/KKuTu#321]
끄투에서 레벨을 어떻게 확장하나요???
아시는 분은 답변해주시면 감사하겠습니다.

**Comment by Preta-Crowz** [comment]
in_game_kkutu.js에서 38번 줄을 `var MAX_LEVEL = {원하는 레벨};`로 바꾸면 됩니다.

**Comment by minesna** [comment]
정확히는 head.js에 `var MAX_LEVEL = 360;` 입니다.
바꾸고 server-flush.bat을 실행후 끝나면 server-setup.bat을 실행하시고 
Server/run.bat 을 실행해주세요.

**Comment by lshqqytiger** [comment]
366으로 변경을 하고 flush 및 setup도 했으나 360이 Infinity라고 나옵니다..당연히 이미지 파일도 추가 해 줬습니다.
