### ISSUE TITLE
Error when querying 발생

### ISSUE THREAD

**Issue by SJang1** [JJoriping/KKuTu#322]
[2018-08-15 15:50:26] Error when querying: SELECT * FROM users WHERE "_id"=(아이디) LIMIT 1 [2018-08-15 15:50:26] Context: error: operator does not exist: character varying = integer

해당 오류가 로그인 시와 kkutu 게임 접속 시 발생합니다. (불러오는 중... 앞으로 1에서 더이상 로딩되지 않는 현상발생)

auth_twitchtv.js는 다음과 같습니다.
![image](https://user-images.githubusercontent.com/29011440/44135484-34818892-a0a4-11e8-9cd9-f959128540fc.png)

**Comment by minesna** [comment]
passport-twitch를 사용해보세요
`npm install passport-twitch`

**Comment by SJang1** [comment]
passport-twitch를 사용하여도 동일한 현상이 발생합니다. (오류 동일)

**Comment by minesna** [comment]
그 패키지(?) 로 다 변경했을시에도 그 오류가 존재하나요?
