### ISSUE TITLE
뭐가 문제일까요...

### ISSUE THREAD

**Issue by junho0118** [JJoriping/KKuTu#33]
제가 소셜 로그인쪽을 건들였습니다. 또 제가 뭘 건들였는지 에러가 뜨네요.

환영합니다.
[2017-02-21 11:06:38] << KKuTu Server:8496 >>
C:\KKuTu-master\Server\lib\sub\jauth.js:40 client_id: 0U_0Ji4MrXXXXXXXXX, ^^^^^^^^^^^^^^^^^^^ SyntaxError: Unexpected identifier at Object.exports.runInThisContext (vm.js:76:16) at Module._compile (module.js:542:28) at Object.Module._extensions..js (module.js:579:10) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object. (C:\KKuTu-master\Server\lib\Web\main.js:28:14) at Module._compile (module.js:570:32)
Worker 8160 died
W: CLOSED WITH CODE 0
[2017-02-21 11:06:39] Master DB is ready. [2017-02-21 11:06:39] DB is ready.

클린트 아이디는 보안상 가리겠습니다. 해결방법 까지 알려주시면 좋겠어요.

**Comment by msquid** [comment]
jauth.js의 40번째 줄을 확인하세요.

**Comment by junho0118** [comment]
제가 메모장으로 봐서 더 정확한 답변 부탁드릴게요...

**Comment by junho0118** [comment]
원본으로 갈아 끼워 볼게요

**Comment by junho0118** [comment]
오 원본은 되네요 제가 오늘 소셜 로그인 api 신청해서 안되는 걸까요... 
네이버 소셜 로그인 하는 방법 알려 주세요. 페북,구글 소셜로그인 지우는것까지 알려주시면좋겠어요...

**Comment by msquid** [comment]
jauth.js의 

const NAVER_ID = "Naver ID";
const NAVER_SECRET = "Naver Secret ID";

부분을 바꾸면 됩니다.

**Comment by junho0118** [comment]
죄송하지만 한번더 물어 볼게요...
끄투 프리서버 목록에 제 서버 등록 하려는데 
이게 무슨말인지 모르겠어요. 파일을 생성을 하려는데 : / 이런게 안붙어요 
무슨말인지 간단하게 설명해주세요

**Comment by junho0118** [comment]
서버의 소유권을 인증하기 위해 다음 이름으로 파일을 생성하고 파일
의 내용을 입력한 서버 주소와 일치하도록 하십시오. 등록이 끝나면 해
당 파일을 삭제해도 됩니다.

파일:http://kkutu-korea.kro.kr/kkutu-dHA6Ly9ra3.html

**Comment by junho0118** [comment]
^^^^^ 위에걸로 파일 생성이 슬래시 그런거 같은게 안붙고요 파일의 내용을 입력한 서버 주소와 일치 하도록 하라는건 뭔 개소리인지... 확장자를 txt로 바꾸고 제 서버 주소를 적은다음,다시 html로 바꾸면 끝이라는 건가요...

**Comment by JJoriping** [comment]
이슈 #19 를 참고해 주세요.

**Comment by junho0118** [comment]
파일 업로드는 또 뭔가요?

**Comment by junho0118** [comment]
어떻게 하는지 잘 알려 주세요

**Comment by FrozenInclude** [comment]
적어도 기초 지식이라도 있으셔야지 보니깐 아무것도 모르시는것 같은데 쪼리핑님이뭘 어떻게 더 설명드려야 합니까

**Comment by junho0118** [comment]
감사합니다. 파일을 서버 폴더 안에 넣고 내용을 조금 수정하니 바로 등록이 되었네요
