### ISSUE TITLE
이름 어떻게 바꾸나요

### ISSUE THREAD

**Issue by usb9245** [JJoriping/KKuTu#330]
![이름을모르겠음ㅠㅠ](https://i.imgur.com/alAwW4W.png)
이거 링크랑 이름 어떻게 바꾸나요?

**Comment by minesna** [comment]
module.pug 에서 바꾸실수 있습니다
( Server/lib/web/views )

**Comment by usb9245** [comment]
감사합니다. 해결했습니다.
