### ISSUE TITLE
쪼롤에 서버가 등록이 되질 않습니다.

### ISSUE THREAD

**Issue by UnderC** [JJoriping/KKuTu#332]
제목대로입니다.
뭐가 문제인지 모르겠습니다.

**Comment by UnderC** [comment]
+ 서버 등록 버튼만 누르면 아무런 반응이 없습니다.

**Comment by UnderC** [comment]
서버 추가 버튼을 누르면 아무런 반응이 없습니다.
제 서버 주소는 http://c04.uy.to:67 입니다.

**Comment by CraftyDragon678** [comment]
F12를 눌러서 나오는 개발자 도구에 뭐라고 에러 혹은 출력이 나오는지 확인해 주세요.

**Comment by UnderC** [comment]
![asdfff](https://user-images.githubusercontent.com/42484007/44444790-8163e180-a619-11e8-8ddd-705b4810f9d9.png)
(버튼 클릭시) 아무런 오류가 없습니다.
쪼롤에 접속하였을때 오류는 favicon을 못불러왔다는 오류밖엔 없습니다.

![dsadsadasds](https://user-images.githubusercontent.com/42484007/44444903-04853780-a61a-11e8-9c82-5231af61d86e.png)
(버튼 클릭후 기다렸을시)
이게 무슨 오류인지는 모르겠습니다.

**Comment by JJoriping** [comment]
서버 등록 시 내부적으로 해당 URL로 접속하게 되는데 이 때 해당 서버가 응답하지 않아 생기는 문제로 보입니다. 입력한 URL이 외부에서 접속할 수 있는 서버인지 확인해 보세요.

**Comment by UnderC** [comment]
외부에서는 접속이 잘 되기는 하는데 포트는 67(웹서버)와 25565(메인 포트)를 열었는데 그 외에 다른 포트를 열어야 하나요?

![sadasdsaasdsadasdasd](https://user-images.githubusercontent.com/42484007/44504086-bda84800-a6d4-11e8-9765-eddeb2b83337.png)
