### ISSUE TITLE
국립국어원에 대해서

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#335]
끄투코리아, 끄투한국 제외하고는 다 한국어 뜻이 없더라고요...어디서 허락을 받아야하는지 그리고 데이터베이스랑 적용법이 뭔지 알려주세요..

1. 허락을 어디서 받는지
2. 데이터베이스를 어떻게 다운받는지
3. 적용을 어떻게하는지

**Comment by minesna** [comment]
한국복제전송저작권협회에서 받으실수 있습니다.
(직접 문의하셔야되요)
