### ISSUE TITLE
쪼롤 등록 실패

### ISSUE THREAD

**Issue by hebe1502** [JJoriping/KKuTu#337]
저 끄투를 쪼롤에 등록하려고 하는 사람인데요..
음 이게 등록하고 소유권 확인하기 위해 html파일 만들고
그리고 다시 서버 등록을 했는데
이전에 입력한 정보를 똑같이 입력하라 하네요..
전 분명 똑같이 했는데..
몇번을 해봐도 안되서 이슈에 올려봅니다...

**Comment by Preta-Crowz** [comment]
서버가 켜져있고, 서버의 public 폴더에 html 파일이 정상적으로 있는지 확인 해주세요. html 파일의 내용은 서버의 주소와 일치해야합니다. (http/https 포함)
