### ISSUE TITLE
끄투 봇 DB

### ISSUE THREAD

**Issue by bokmook** [JJoriping/KKuTu#338]
혹시 끄투 봇의 DB를 볼 수 있는 방법은 없을까요?
끄투 봇의 DB를 이용한 검색기를 하나 제작 중이라서,
부탁드립니다.

**Comment by Preta-Crowz** [comment]
끄투 봇의 DB는 따로 없으며, 끄투 자체의 DB를 사용합니다.

**Comment by bokmook** [comment]
@Preta-Crowz 혹시 그렇다면 끄투 봇의 작동 방식이나 알고리즘을 알 수 있을까요?
