### ISSUE TITLE
이건...

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#339]
저번에 이슈 답변 올려주셔서 감사하다는 말씀 드립니다.
현재 여러가지 오류가 생겼는데 해결해주시면 감사하겠습니다.

1. 127.0.0.2 로 들어가서 로그인 눌렀는데 아무것도 안뜸.
2. 불러오는 중...앞으로 1에서 멈춤
3. 서버 목록이 1개 밖에 안뜸.
4. 내 서버 등록하기해서 제출 눌렀는데 '서버의 소유권을 확인하기 위해...주세요'가 뜸.
5. TypeError랑 Redis 에러가 run.bat을 킬때 일어남.

ㅠㅠ

**Comment by Preta-Crowz** [comment]
1. 127.0.0.1로 접속해주세요.
2. 1번과 같은 문제인 것 같습니다.
3. 서버 갯수는 settings.json에서 설정 가능합니다.
4. 소유권 확인을 진행해야 등록이 가능합니다.
5. TypeError는 자세한 로그가 있어야 확인 가능하며, redis는 랭킹 관련 시스템으로, 없으면 랭킹이 표시되지 않지만, 서버는 정상 작동합니다.
되도록이면 여러 오류를 한 이슈에 적지 말아주세요. 분류가 힘들어집니다.

**Comment by minesna** [comment]
충분히 이슈와 README.md를 보면 알수있는문제 입니다.
충분히 검색을 해보시고 이슈남겨주세요
