### ISSUE TITLE
끄투는 어떤 포트를 사용하나요?

### ISSUE THREAD

**Issue by SkyLightQP** [JJoriping/KKuTu#34]
웹서버인 IIS하고 끄투를 동시에 돌리다보니
끄투 웹서버에 다른 포트를 활당해서 쓰고 있습니다. 그리고 게임서버를 2개 운영 중인데
여기까지해서 총 6개에 포트를 쓰더군요. 
게임서버 2개 운영 시 허용이 필요한 포트가 더 있나요?

웹서버 포트와 게임서버 2개 포트 그리고 나머지 3개는 어디에 쓰이는지 모르겠네요.
10000번대 2개와 9000번대 포트입니다.

**Comment by msquid** [comment]
끄투 게임서버 포트 같은거는 예를들어 8080번으로 포트를 지정했다 하면 거기에 416,417을 더한 8496,8497을 포트포워딩 해야합니다.

**Comment by JJoriping** [comment]
웹 서버와 게임 서버의 포트 번호에 대한 설명을 끄투 위키의 [클러스터링](https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81#%ED%8F%AC%ED%8A%B8-%EB%B2%88%ED%98%B8) 문서에 기재해 놓았으니 참고해 보세요.

**Comment by SkyLightQP** [comment]
감사합니다.
