### ISSUE TITLE
XSS 방지를 하는 코드는 어디쪽에 있나요?

### ISSUE THREAD

**Issue by cho060303** [JJoriping/KKuTu#340]
GM에게만 XSS 방지를 풀고 싶습니다. XSS 방지를 어디서 하는지 알려주실 수 있으신가요?

**Comment by CraftyDragon678** [comment]
콘솔에서 html태그를 우회하게 되어있습니다. 콘솔에 로그 띄우는 부분을 보시면 되는데.. GM에게만 풀 수 있는건.. 오히려 그렇게 하다가 더 취약점이 생길 수도 있는 부분이라서....

**Comment by kdwkr** [comment]
https://github.com/JJoriping/KKuTu/blob/f2e49fe82f68a809f4b2d25ce76c52bf61f7fa24/Server/lib/Web/lib/kkutu/body.js#L2675-L2718

해당 부분이 인게임 내에서 채팅을 표시하는 함수 입니다.  그 중
https://github.com/JJoriping/KKuTu/blob/f2e49fe82f68a809f4b2d25ce76c52bf61f7fa24/Server/lib/Web/lib/kkutu/body.js#L2695

이 부분을 보시면 채팅 메세지를 .text(msg)를 이용하여 삽입하는데요, .text() 함수는 esacpe html을 해줍니다.

따라서 GM만 채팅에서 HTML 코드를 사용할 수 있도록 하기 위해서는 해당 부분에서 만약 보내는 사람이 GM휘장을 착용하고 있다면 .text() 함수 대신 .html() 함수를 사용하도록 하면 됩니다.

```
       $stage.chat.append($item = $("<div>").addClass("chat-item") 
 		.append($bar = $("<div>").addClass("chat-head ellipse").text(profile.title || profile.name)) 
 		.append($msg = equip["BDG"]==="b1_gm"?$("<div>").addClass("chat-body").html(msg):$("<div>").addClass("chat-body").text(msg)) 
 		.append($("<div>").addClass("chat-stamp").text(time.toLocaleTimeString())) 
 	); 
```

이런식으로요.

**Comment by cho060303** [comment]
감사합니다.
