### ISSUE TITLE
디스코드 로그인

### ISSUE THREAD

**Issue by kkutu-hooss** [JJoriping/KKuTu#341]
디스코드 로그인이 끄투 기본 파일에 없어서 직접 만들려고 하는데 디스코드에 app은 만들었다만 로그인을 구현 못하고 있습니다. 도와주실 수 있으신가요?

**Comment by Preta-Crowz** [comment]
프로젝트 끄투에서 사용하는 디스코드 로그인 파일입니다.
```js
const config = require('../../sub/auth.json');

module.exports.config = {
    strategy: require('passport-discord').Strategy,
    color: '#7289DA',
    fontColor: '#FFFFFF',
    vendor: 'discord',
    displayName: 'withDiscord'
}

module.exports.strategyConfig = {
    clientID: config.discord.clientID,
    clientSecret: config.discord.clientSecret,
    callbackURL: config.discord.callbackURL,
    passReqToCallback: true,
    scope: "identify"
}

module.exports.strategy = (process, MainDB, Ajae) => {
    return (req, accessToken, refreshToken, profile, done) => {
        const $p = {};

        // var fullname = profile.username+"#"+profile.discriminator;

        $p.authType = "discord";
        $p.id = $p.authType+"-"+profile.id;
        $p.name = profile.username;
        $p.title = profile.username;
        $p.image = profile.avatar;

        process(req, accessToken, MainDB, $p, done);
    }
}
```

**Comment by kkutu-hooss** [comment]
감사합니다

**Comment by kkutu-hooss** [comment]
> 프로젝트 끄투에서 사용하는 디스코드 로그인 파일입니다.
> 
> ```js
> const config = require('../../sub/auth.json');
> 
> module.exports.config = {
>     strategy: require('passport-discord').Strategy,
>     color: '#7289DA',
>     fontColor: '#FFFFFF',
>     vendor: 'discord',
>     displayName: 'withDiscord'
> }
> 
> module.exports.strategyConfig = {
>     clientID: config.discord.clientID,
>     clientSecret: config.discord.clientSecret,
>     callbackURL: config.discord.callbackURL,
>     passReqToCallback: true,
>     scope: "identify"
> }
> 
> module.exports.strategy = (process, MainDB, Ajae) => {
>     return (req, accessToken, refreshToken, profile, done) => {
>         const $p = {};
> 
>         // var fullname = profile.username+"#"+profile.discriminator;
> 
>         $p.authType = "discord";
>         $p.id = $p.authType+"-"+profile.id;
>         $p.name = profile.username;
>         $p.title = profile.username;
>         $p.image = profile.avatar;
> 
>         process(req, accessToken, MainDB, $p, done);
>     }
> }
> ```
그럼 kr_KO도 변경 해야 되네요 withDiscord라는 키를 디스코드 로그인으로

**Comment by kkutu-hooss** [comment]
> 프로젝트 끄투에서 사용하는 디스코드 로그인 파일입니다.
> 
> ```js
> const config = require('../../sub/auth.json');
> 
> module.exports.config = {
>     strategy: require('passport-discord').Strategy,
>     color: '#7289DA',
>     fontColor: '#FFFFFF',
>     vendor: 'discord',
>     displayName: 'withDiscord'
> }
> 
> module.exports.strategyConfig = {
>     clientID: config.discord.clientID,
>     clientSecret: config.discord.clientSecret,
>     callbackURL: config.discord.callbackURL,
>     passReqToCallback: true,
>     scope: "identify"
> }
> 
> module.exports.strategy = (process, MainDB, Ajae) => {
>     return (req, accessToken, refreshToken, profile, done) => {
>         const $p = {};
> 
>         // var fullname = profile.username+"#"+profile.discriminator;
> 
>         $p.authType = "discord";
>         $p.id = $p.authType+"-"+profile.id;
>         $p.name = profile.username;
>         $p.title = profile.username;
>         $p.image = profile.avatar;
> 
>         process(req, accessToken, MainDB, $p, done);
>     }
> }
> ```

그렇다면

**Comment by kkutu-hooss** [comment]
그런데 시크릿 코드랑 그런건 어떻게 하죠;;

**Comment by small-sunshines** [comment]
[Discord 개발자 홈페이지](https://discordapp.com/) 에서 애플리케이션 생성 및 설정을 하시면 됩니다.
