### ISSUE TITLE
정확히 알려주시라고 해서 영상으로 올립니다.

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#345]
[녹화_2018_09_13_20_09_35_696.zip](https://github.com/JJoriping/KKuTu/files/2379013/_2018_09_13_20_09_35_696.zip)

압축푸셔서 영상 보시면 됩니다.
mp4파일이 안올려지더라고요

**Comment by small-sunshines** [comment]
![image](https://user-images.githubusercontent.com/11470513/46241964-a60f5e00-c3fc-11e8-9858-0f1fef123976.png)

1. 설정이 일부 제대로 진행되지 않은 것 같습니다.

![image](https://user-images.githubusercontent.com/11470513/46241968-bcb5b500-c3fc-11e8-898a-8f299ae98d3b.png)

2. PostgreSQL 설정이 제대로 진행되지 않은 것 같습니다.
3. OAuth 관련 설정을 진행해주세요.
