### ISSUE TITLE
점수 시스템과 그림 퀴즈 구현

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#347]
단어대결에서 주제가 많으면 많을 수록 점수가 더 들어가게 하는법은 없을까요?

**Comment by lshqqytiger** [comment]
그리고 그림 퀴즈는 어떻게 구현하나요?

**Comment by lshqqytiger** [comment]
+ 그리고 특수 규칙 중 새내기는 어떻게 구현하나요?

**Comment by kdwkr** [comment]
이곳은 기존 시스템에 대한 질문이나 버그 제보 등을 하는 공간으로, 새로운 기능을 만들기 위한 지식을 묻는 곳이 아닙니다.

**Comment by lshqqytiger** [comment]
@kdwkr 넵 알겠습니다..
