### ISSUE TITLE
127.0.0.1 접속 성공

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#348]
접속은 성공하였습니다.
로그인을 누르면

로그인 방법을 선택하세요.

(L#loginLegal)

이렇게 뜹니다.
Server\lib\Web\auth에서
facebook, kakao, twitter, example.js 모두 DISABLED입니다. Google+ API는 사용 설정한거 같은데 왜이러는지 알 수 없습니다.

**Comment by kkutu-hooss** [comment]
google을 사용하시는 거라면 google에는 DISABLED는 붙이시면 안됩니다
