### ISSUE TITLE
서버관련하여 여러가지 질문드립니다

### ISSUE THREAD

**Issue by KORraimi** [JJoriping/KKuTu#35]
구글 연동도 어떡게 하나요?

**Comment by KORraimi** [comment]
그리고 사이트의 head,body가 들어있는 문서는 무슨 파일인가요?

**Comment by FrozenInclude** [comment]
자바스크립트를 배우시면되는데..  아설마 모르시는건가요..? 에이설마 모르겠어요 서버운영하신다는데 적어도 서버프로그래밍정돈 능숙하게 할수있고 만들어보신것도 많으시겠어요~

**Comment by KORraimi** [comment]
아니요~ 자바는 어느정도 아는데 문제는 구글 연동할때 다른 네이버는 클라이언트 ID랑 시크릿 키만 넣으면 되는데 그런데 구글은 두개를 넣고 또 무언가를 넣어야 되는데 뭘 넣야되는지 몰라서 질문드리는거에요 ㅎ

**Comment by FrozenInclude** [comment]
그러시면 OAuth대해 공부해보세요

**Comment by KORraimi** [comment]
아니요 구글로그인 어떡게 하는지요

**Comment by KORraimi** [comment]
1.구글 연동 어떡게 하는지요
2.사전뜻 데이타베이스 어디서 다운받는지요
3.사전뜻 데이타베이스가 있으면 어떻게 링크하는지요

**Comment by FrozenInclude** [comment]
자살ㄱ

**Comment by JJoriping** [comment]
개괄적인 내용은 [README.md](https://github.com/JJoriping/KKuTu/blob/master/README.md) 파일과 다른 분들의 이슈들을 천천히 읽고 따라하시기 바라며 이슈를 반복적으로 여닫는 행위는 자제해 주시기 바랍니다.

**Comment by hjki001** [comment]
흠 구글은 살짝 어려울수있습니다 우선 리다이렉팅 주소가안맞으면 로그인 자체가안돼요..

**Comment by SoManyIdiotsInKKuTuIssues** [comment]
니는 숨쉬는법도 사람들한테 물어봐가면서 배움?

제발 리드미좀 쳐읽고살아라 븅신새끼야
