### ISSUE TITLE
SSL적용하려 할때 Web실행 시 file is not defined 발생

### ISSUE THREAD

**Issue by SJang1** [JJoriping/KKuTu#350]
Ubuntu에서 서버를 열어보려 하는데 SSL적용시키지 않으면 정상적으로 샐행되는게 적용하려하면 file is not defined가 발생하네요.  (Web 실행시발생, 오류발생 및 Web종료됨)

/ect/letsencrypt/live/(mydomain)/~~.pem를 global.json의 SSL_OPTIONS에 넣은 상태이며, 끄투경로의 /Server/lib/sub/secure.js:31에서 발생한다고 나옵니다.

**Comment by minesna** [comment]
` /` -> `//`
이렇게 해보세여

**Comment by SJang1** [comment]
마찬가지입니다.

**Comment by minesna** [comment]
저는 pem이 아닌
key와 crt파일을 사용했던거 같습니다

**Comment by SJang1** [comment]
pem으로는 안된다는 것인가요

**Comment by SJang1** [comment]
> 본 에러는 #251 에 해결된 버전이 있습니다. 필요하시다면 Discord 볕뉘#8486 으로 연락주세요. 수정해드리겠습니다.

도움으로  적용완료(해결완료)했습니다. 감사합니다.!
