### ISSUE TITLE
외부에서 접속이 되지 않습니다

### ISSUE THREAD

**Issue by and1094** [JJoriping/KKuTu#351]
![kakaotalk_photo_2018-09-23-22-03-48](https://user-images.githubusercontent.com/33094445/45928324-ac28b900-bf7c-11e8-8822-3c4471c8b6ef.png)
다른 건 다 잘되는 듯 싶은데 외부에서 접속이 되지 않네요. 포트포워딩 쪽에 문제가 있는 것 같긴 한데 잘은 모르겠네요... 좀 알려주세요

**Comment by Preta-Crowz** [comment]
우선 아이피로 직접 접속을 시도해보시고, 여기서 된다면 도메인 연결에 문제가 있는 것이며, 안될 경우는 포트포워딩에 문제가 있는 것입니다.

**Comment by and1094** [comment]
넵 감사합니다
