### ISSUE TITLE
오류 해결 방법점여..ㅠㅠ

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#352]
하라는대로 최대한 해 봤는데.. 이런 오류가 뜨는데여..

internal/modules/cjs/loader.js:711 throw err; ^ SyntaxError: 위치(비밀)\KKuTu-master\Server\lib\sub\global.json: Unexpected number in JSON at position 61 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27) at Module.load (internal/modules/cjs/loader.js:599:32) at tryModuleLoad (internal/modules/cjs/loader.js:538:12) at Function.Module._load (internal/modules/cjs/loader.js:530:3) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:20:18) at Object.&lt;anonymous> (위치(비밀)\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:689:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:711 throw err; ^ SyntaxError: 위치(비밀)\KKuTu-master\Server\lib\sub\global.json: Unexpected number in JSON at position 61 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:708:27) at Module.load (internal/modules/cjs/loader.js:599:32) at tryModuleLoad (internal/modules/cjs/loader.js:538:12) at Function.Module._load (internal/modules/cjs/loader.js:530:3) at Module.require (internal/modules/cjs/loader.js:637:17) at require (internal/modules/cjs/helpers.js:20:18) at Object.&lt;anonymous> (위치(비밀)\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:689:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
Worker 18892 died
W: CLOSED WITH CODE 0

여기서 SyntaxError이 무슨 에러인지 설명점여..(이런 쪽 초보라서 쉽게 설명점여)

**Comment by small-sunshines** [comment]
우선 global.json 파일은 현재 github에 실수로 올리는 것을 방지하기 위해 global.inc.json 으로 파일이름이 변경되어있는 상태입니다. 파일을 복사하여 global.json 으로 이름을 변경하신 뒤, 설정을 진행하여 주시면 됩니다.

같은 방식으로 auth.json 도 auth.inc.json 으로 파일이름이 변경되어있습니다.

반드시 readme.md 를 정독하신 뒤 끄투 설정을 진행하여 주시기 바랍니다.

**Comment by andjsrk** [comment]
??? 바꾼지가 오랜데여..

**Comment by andjsrk** [comment]
다 보고 한 건데..ㅠㅠ

**Comment by Preta-Crowz** [comment]
파일을 제대로 수정했는지 확인해주세요. JSON 문법이 잘못 된 것 같습니다.

**Comment by andjsrk** [comment]
제대로 수정했어여..ㅠㅠ

**Comment by dark7995** [comment]
저도 그오류떠여 ㅠㅠ
