### ISSUE TITLE
관리자페이지 들어가는법

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#355]
구동은 성공했는데 관리자페이지같은게 있나요? 있다면 알려주시면 감사하겠습니다.

**Comment by lorlol701** [comment]
관리자페이지는 http://서버도메인/gwalli 으로 진입할수 있습니다.

**Comment by jsp7228** [comment]
> 관리자페이지는 http://도메인/gwalli 으로 진입할수 있습니다. 단, 로비화면에서 관리자 계정으로 로그인되어있을때만 들어갈수있습니다.(error 400)
로그인 클릭하니깐 (L#loginLegal) 이라고 되어있어서 관리자계정로그인을 할수가없는데 어떻게하나요?

**Comment by lorlol701** [comment]
아직 로그인버튼이 작동되지 않아서 그런겁니다. 다른 이슈 둘러보시면 구글이나 카카오 등에서 API를 받아 로그인을 구현하는 방법이 있으니 참고하시기 바랍니다. 로그인이 된 후에는 게임 내에서 /id를 쳐 자신의 식별번호를 받고 global.json에서 ADMIN칸에 넣어주시면 됩니다.

**Comment by Preta-Crowz** [comment]
`(L#loginLegal)`은 ko_kr.json 언어 파일에서 loginLegal 값이 누락되어 나타나는 현상으로, 무시해도 됩니다.
해결 방법은 위의 내용과 동일합니다.
