### ISSUE TITLE
끄투 DB에서 단어를 삭제하는방법

### ISSUE THREAD

**Issue by lorlol701** [JJoriping/KKuTu#356]
제목 그대로입니다. 추가는 알겠는데 아직 삭제하는방법을 모르겠어서요

**Comment by kdwkr** [comment]
SQL문의 경우 다음과 같습니다.

한국어
```sql
DELETE FROM kkutu_ko WHERE id = '단어명';
```
영어
```sql
DELETE FROM kkutu_en WHERE id = '단어명';
```

**Comment by UnderC** [comment]
1. http://주소/gwalli 로 접속하여 암호와 테이블을 입력합니다.
    (단, global.json에서 admin에 자신의 식별번호가 있어야 하고 로그인 상태여야 합니다.)
2. 끄투 DB 다루기에서 단어에 삭제할 단어를 입력하고 조회 버튼을 누릅니다.
    (DB에 존재하지 않을 경우 나타나지 않음)
3. 오른쪽에 있는 행동에서 X를 눌러 삭제하고 적용을 누릅니다.

**Comment by lshqqytiger** [comment]
@lorlol701 해결되셨으면 이슈를 닫아주세요
