### ISSUE TITLE
단어 데이타베이스에 어떻게 단어를 추가하나요? 외 1가지 질문

### ISSUE THREAD

**Issue by MisileTV** [JJoriping/KKuTu#359]
제목 그대로입니다.
단어 데이터베이스에 어떻게 단어를 추가하고 단어의 뜻을 어떻게 추가하고 수정하나요?

**Comment by hebe1502** [comment]
GM으로 되어있는걸로 로그인을 통하고
자신의 서버주소/gwalli로 접속을 합니다.
그 다음 밑으로 내리시다 보면 단어 DB라고 있습니다. 거기서 (~뭐라뭐라) 써져있는 곳엔 단어의 카테고리 큰대는 단어를 나열하면서 치시면 됩니다 그리고 마지막으로 OK!
