### ISSUE TITLE
끄투 이미지 사용 질문

### ISSUE THREAD

**Issue by SkyLightQP** [JJoriping/KKuTu#36]
서버와 함께 배포된 파일 안에 이미지를 써도 될까요?
(카페, 옐로아이디 등)

쓰게된다면 GPL 라이센스를 지키면되나요?

**Comment by JJoriping** [comment]
안녕하세요. 본 레포지토리에 있는 이미지나 소리 등은 CC BY 라이선스에 따라 자유롭게 이용하실 수 있습니다. `./README.md` 파일에 관련 사항을 명시해 놓았으니 확인해 주세요.
