### ISSUE TITLE
패비콘

### ISSUE THREAD

**Issue by hebe1502** [JJoriping/KKuTu#361]
/public에 favicon.ico로 패비콘을 제대로 넣었는데도 불구하고
패비콘이 안뜨네요

**Comment by Preta-Crowz** [comment]
브라우저의 캐시를 지운 후 다시 로드해보세요.

**Comment by Alex4386** [comment]
브라우저 사이드 캐시일 수도 있습니다.
Ctrl+F5 또는 Shift+F5를 시도해 보시거나
Chrome의 경우 개발자 도구 -> Network -> Disable Cache를 체크 한 후 다시 로드해 주시기 바랍니다.
