### ISSUE TITLE
프로필 사진 삭제

### ISSUE THREAD

**Issue by usb9245** [JJoriping/KKuTu#362]
![image](https://user-images.githubusercontent.com/34123108/46658507-d40b5400-cbed-11e8-9737-564f225a8ec6.png)
프로필의 닉네임 옆 사진(사진의 빨간색 원)을 없애고 싶은데,
어떤 파일을 수정해야 할까요?

**Comment by 3333303** [comment]
/server/lib/web/views/kkutu.pug 파일 수정해야 하는 거 같습니다

**Comment by usb9245** [comment]
이게 어디 부분을 수정해야 할지... 모르겠네요...

**Comment by Preta-Crowz** [comment]
`/Server/lib/Web/lib/in_game_kkutu.min.js`,
`/Server/lib/Web/public/js/in_game_kkutu.min.js`에서
`.addClass("profile-image")` 부분을 삭제 혹은 주석 처리하면 됩니다.

**Comment by minesna** [comment]
정확히는 body.js를 수정하시는게 좋습니다

"Web/lib/kkutu/head.js",
	"Web/lib/kkutu/ready.js",
	"Web/lib/kkutu/rule_classic.js",
	"Web/lib/kkutu/rule_jaqwi.js",
	"Web/lib/kkutu/rule_crossword.js",
	"Web/lib/kkutu/rule_typing.js",
	"Web/lib/kkutu/rule_hunmin.js",
	"Web/lib/kkutu/rule_daneo.js",
	"Web/lib/kkutu/rule_sock.js",
	"Web/lib/kkutu/body.js",
	"Web/lib/kkutu/tail.js"
위와 같은 파일들이 모여 Server\lib\Web\lib\in_game_kkutu.js로 grunt된것이라 
body.js에서 위 코멘트대로 제거하시고 server-flush.bat 후 server-setup.bat을 실행해주시면 됩니다.

(모바일이라 ..ㅠㅠ)

**Comment by usb9245** [comment]
![image](https://user-images.githubusercontent.com/34123108/47370722-4e28f600-d721-11e8-94e1-541f27ad7f9c.png)
아 프로필 옆 사진은 없어졌는데, 이곳 사진이 안없어졌네요.
프로필 사진 없애면 저것도 없어질거라 생각해 프로필 사진 지우는법에 대해 질문했는데, 이쪽 사진도 없애고 싶습니다.
