### ISSUE TITLE
안녕하세요.

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#365]
저번에 도움을 주셔서 감사합니다. 덕분에 접속이 가능하였습니다.
근데, 한가지 여쭈어보겠습니다.

{
    "naver": {
        "clientID": "(입력함)",
        "clientSecret": "(입력함)",
        "callbackURL": "/login/naver/callback"
    }, "facebook": {
        "clientID": "",
        "clientSecret": "",
        "callbackURL": "/login/facebook/callback"
    }, "google": {
        "clientID": "(입력함)",
        "clientSecret": "",
        "callbackURL": "/login/google/callback"
    }, "twitter": {
        "consumerKey": "",
        "consumerSecret": "",
        "callbackURL": "/login/twitter/callback"
    }, "kakao": {
        "clientID": "(입력함)",
        "callbackURL": "http://127.0.0.1/login/kakao/callback"
    }
}
카카오톡에서는 잘못 접속했다고 하고, 네이버에서는 허락을 받아야한다고 하는데, 이 문제는 어떻게 해결하면 좋을까요?

**Comment by swoo5571** [comment]
뭔가 잘못된 요청을 하신 것 같아요.
error="invalid_client", error_description="Not exist client_id [클라이언트ID]"

**Comment by KRBlue** [comment]
카카오톡 부분에 콜백URL을 /login/kakao/callback 으로 변경하셔야 할듯 합니다. 네이버 로그인은 네아로 검수 통과하셨나요?

**Comment by swoo5571** [comment]
해볼려고 했지만 안됬던걸로 알고 있습니다. 127.0.0.1말고 혹시 일반 도메인(co.kr, oa.to 따위)으로 할 수 없을까요?

**Comment by lorlol701** [comment]
유료 도메인을 구매하시거나 무료도메인을 https://내도메인.한국 등에서 구하신 후에 도메인 DNS IP를 공인 IP로 설정해주시고 웹포워딩 (Redirect)도 설정해주시면 127.0.0.1 말고 도메인을 사용가능합니다.

**Comment by Preta-Crowz** [comment]
콜백에는 / 뒤의 url만 입력해야하며, 카카오는 카카오 API 설정에서 콜백 설정을 해주셔야합니다.
