### ISSUE TITLE
질문입니다

### ISSUE THREAD

**Issue by usb9245** [JJoriping/KKuTu#368]
![image](https://user-images.githubusercontent.com/34123108/47859408-9e930880-de31-11e8-98fb-0738e285f03e.png)
카카오톡 등에서 링크를 올리면 나오는 빨간색 원으로 표시된 부분을 수정하고 싶습니다.

**Comment by Ryzen72700** [comment]
저건 **~\KKuTu-master\Server\lib\Web\public**에서 **favicon.ico 파일**로 수정이 가능해보이네요
아니면 **~\KKuTu-master\Server\lib\Web\public\img**에서 **trademark.png**를 수정해보세요
(저 사이즈랑 비슷한 파일이 trademark.png 파일이네요

**Comment by CraftyDragon678** [comment]
![image](https://user-images.githubusercontent.com/25890954/47958586-503c6000-e011-11e8-93bd-d6096117de9f.png)
ogImage.png를 수정하셔야 됩니다. 메타 데이터가 뜨는거라서...
