### ISSUE TITLE
서버 관리자 관련

### ISSUE THREAD

**Issue by ys0503** [JJoriping/KKuTu#37]
![default](https://cloud.githubusercontent.com/assets/25845472/23159244/6f9e12bc-f865-11e6-837c-ad031d9be48d.PNG)

서버 관리자로 서버닫기 명령을 입력 하면 이런오류가 발생합니다.
끄투 게임내에서 소모품류 아이템 사용시에도 이런 비슷한 오류가 가끔 나더군요.
계속 놔뒀지만 저 혼자 힘으론 안될것 같아서 다시한번 이슈 열어봅니다.

**Comment by JJoriping** [comment]
서버 관리자 소스 코드에 문제가 발견되어 관련 부분을 수정했습니다. 제보 감사합니다.
