### ISSUE TITLE
서버를 열었는데 자꾸 HTTP 상태코드 426(업그레이드 필요)가 뜹니다.

### ISSUE THREAD

**Issue by SoBusted** [JJoriping/KKuTu#370]
다른 설정을 모두 완료하고 run.bat를 실행시킨 후

127.0.0.1:포트번호로 접속해 보면 Upgrade Required 라고 뜹니다. 

./Server/lib/sub/global.json 파일을 열어서

포트번호를 다른 걸로 바꾸고 접속하는 작업을 반복했지만

계속 같은 오류가 뜹니다.

어떻게하면 해결할 수 있을까요?

**Comment by minesna** [comment]
그건 게임서버 포트입니다
웹서버 포트 설정을 안하셨다면
http://주소 만 적어주세요

**Comment by kkutuonlines** [comment]
도메인을 연결하지 않았을 경우 127.0.0.1 로 접속 가능합니다.
뒤에 포트를 붙이지 않고 127.0.0.1 로 접속하세요.
global.json 의 메인포트 는 게임서버 포트이지 웹 서버 포트가 아닙니다.

**Comment by SoBusted** [comment]
> 도메인을 연결하지 않았을 경우 127.0.0.1 로 접속 가능합니다.
> 뒤에 포트를 붙이지 않고 127.0.0.1 로 접속하세요.
> global.json 의 메인포트 는 게임서버 포트이지 웹 서버 포트가 아닙니다.

다들 답변 감사합니다.

처음에 127.0.0.1로 접속하면 bitnami페이지가 나왔었는데

bitnami를 삭제하니 접속이 잘 되네요.

**Comment by SoBusted** [comment]
문제 해결~
