### ISSUE TITLE
로봇을 정상작동 시키려면 어느 부분을 수정해야 하나요?

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#38]
로봇이 사기봇 빼고 한턴을 못넘기길래 질문드립니다.
이슈 #3 에서 데이터베이스가 초기화되었다는 사실을 알고있긴 있는데,
classic.js 파일에서 어느 부분을 수정해야 하는지 알지 못하겠습니다.
답변해주시면 감사하겠습니다.

**Comment by yom21c1020** [comment]
단지 플레이를 반복해주시면 됩니다.
플레이를 반복함으로서 단어의 히트 수를 늘려 봇이 선택 가능한 단어를 늘리기 위함입니다.

**Comment by kim-min** [comment]
아 그렇군요.. 감사합니다.
