### ISSUE TITLE
끄투 카카오로그인관련..

### ISSUE THREAD

**Issue by Ryzen72700** [JJoriping/KKuTu#380]
일단 개발자등록까지 하고 사이트까지 등록해서 auth.json에 적용시키고 활성화하려고 합니다..
클라이언트 아이디랑 콜백 하려고 하는데 아래처럼 하면될까요?

    }, "kakao": {
        "clientID": "JavaScript 키",
        "callbackURL": "주소/login/kakao/callback"

그리고 플랫폼 -> 웹에서 사이트 도메인(주소) 등록하고 Redirect Path에 /login/kakao/callback 하면 될까요..?

**Comment by hatty163** [comment]
@Ryzen72700 JavaScript 키가 아닌 Admin 키를 쓰셔야 합니다.
callbackURL과 Redirect Path는 https://examp.le/login/kakao/callback과 같이 입력해주시면 됩니다.

**Comment by Ryzen72700** [comment]
> @Ryzen72700 JavaScript 키가 아닌 Admin 키를 쓰셔야 합니다.
> callbackURL과 Redirect Path는 [https://examp.le/login/kakao/callback과](https://examp.le/login/kakao/callback%EA%B3%BC) 같이 입력해주시면 됩니다.

OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-kakao\node_modules\passport-oauth2\lib\strategy.js:83:34) at new Strategy (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-kakao\lib\strategy.js:32:18) at glob.then (C:\Users\user\Desktop\KKuTu-master\Server\lib\Web\routes\login.js:75:26) at &lt;anonymous>

이오류는 혹시 뭐때문에 일어난건가요..?
저 건드린것 없는데 갑자기 뜨네요.. 혹시 카카오때문인지..

**Comment by Ryzen72700** [comment]
@hatty163 해결했어요!

**Comment by hatty163** [comment]
@Ryzen72700 해결되셨으면 이슈 닫아주시기 바랍니다.
