### ISSUE TITLE
레디스 + PostgreSQL 관련된 오류.. 인 것 같아여

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#385]
&lt;&lt; KKuTu Server:8496 >>
&lt;&lt; KKuTu Web >>
**Error** from Redis: **Error**: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2018-11-21 21:18:13] Run with no-redis mode.
**Error** from Redis: **Error**: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Run with no-redis mode.
Game server #1 has an **error**: **Error**: connect ECONNREFUSED 127.0.0.2:8080 [2018-11-21 21:18:13] Game server #1 closed: 1006
**Error** when connect to PostgreSQL server: **Error**: connect ECONNREFUSED 127.0.0.1:5432
**Error** when connect to PostgreSQL server: **Error**: connect ECONNREFUSED 127.0.0.1:5432
**Error** when connect to PostgreSQL server: **Error**: connect ECONNREFUSED 127.0.0.1:5432

라고 뜨는데..
Redis는 오류가 있는 게 확실한데..(깃허브에서 윈도우 용으로 다운로드 했는데 왜 그럴까여..)
PostgreSQL은 웹서버를 안 켜서 그런건가여..

이런 쪽 초보인데 자세하게 답변해주세여..

**Comment by Ryzen72700** [comment]
server #1 closed: 1006은 PostgreSQL 서버가 안열린거 같네요 아니면 네트워크 포트로 안열려있거나.. 그리고 redis는 없어도 접속 가능하다고 들었습니다.
redis는 https://github.com/MicrosoftArchive/redis/releases 에서 ~.msi 파일을 받은후 설치 하라는대로 하시면 작업관리자에 redis-server 이라고 백그라운드 앱에서 뜰겁니다.
아래 사진처럼 postgresql, redis가 실행중인지 확인후 서버를 실행해보세요.
![default](https://user-images.githubusercontent.com/43514034/48967471-562bcc80-f024-11e8-8f05-f80580ff6f61.PNG)

**Comment by andjsrk** [comment]
감사합니당..!
