### ISSUE TITLE
외부 PostgreSQL 서버 + a

### ISSUE THREAD

**Issue by KafuChinoDesu** [JJoriping/KKuTu#387]
게임 서버랑 외부에 있는 PostgreSQL 서버를 쓸려면 어떻해야 하죠?
그리고 저가 서버를 Heroku라는 NodeJS 호스팅에 올릴 예정인데 세팅을 어떻게 해야 할까요?

**Comment by Preta-Crowz** [comment]
Server/lib/Web/db.js의 43번 줄 부근 연결 생성에 주소를 추가하면 됩니다.
노드 호스팅의 경우 노드 모듈 설치 후, 실행 파일들을 실행해주면 될겁니다.
