### ISSUE TITLE
Windows 10 1809 업데이트 이후 이런 오류가 뜨며 서버가 열리지 않습니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#388]
npm에는

C:\Users\user\Desktop\Private\KKuTu-master\Server>npm start

> kkutu-server@2.5.1 start C:\Users\user\Desktop\Private\KKuTu-master\Server
> electron .

Pug interceptor registered successfully
W: events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES null:80
    at listenOnMasterHandle (net.js:1353:16)
    at rr (internal/cluster/child.js:126:12)
    at Worker.send (internal/cluster/child.js:93:7)
    at process.onInternalMessage (internal/cluster/utils.js:45:8)
    at process.emit (events.js:187:15)
    at emit (internal/child_process.js:812:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at listenOnMasterHandle (net.js:1354:21)
    at rr (internal/cluster/child.js:126:12)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:63:19)

[2018-11-25 15:10:59] W: CLOSED WITH CODE 0

이런 오류가 뜨고 서버 매니저에는

[2018-11-25 15:10:58] &lt;&lt; KKuTu Server:8496 >>
[2018-11-25 15:10:58] &lt;&lt; KKuTu Web >>
[2018-11-25 15:10:59] DB is ready.
[2018-11-25 15:10:59] Master DB is ready.
[2018-11-25 15:10:59] DB is ready.
events.js:167 throw er; // Unhandled 'error' event ^ Error: bind EACCES null:80 at listenOnMasterHandle (net.js:1353:16) at rr (internal/cluster/child.js:126:12) at Worker.send (internal/cluster/child.js:93:7) at process.onInternalMessage (internal/cluster/utils.js:45:8) at process.emit (events.js:187:15) at emit (internal/child_process.js:812:12) at process._tickCallback (internal/process/next_tick.js:63:19) Emitted 'error' event at: at listenOnMasterHandle (net.js:1354:21) at rr (internal/cluster/child.js:126:12) [... lines matching original stack trace ...] at process._tickCallback (internal/process/next_tick.js:63:19)
Worker 1976 died
W: CLOSED WITH CODE 0

이런 오류가 뜨면서 서버가 열리질 않습니다. 어떻게 해야할까요? 윈도우 1809 업데이트 말고는 아무것도 한게 없습니다.

**Comment by minesna** [comment]
내부에서 80포트를 사용중인 프로세스가 있는지 확인해주세여

**Comment by lshqqytiger** [comment]
제아이피:80 으로 접속해보면 404 에러가 뜨는데 포트가 사용중인건가요?

**Comment by Alex4386** [comment]
@lshqqytiger 네 netstat 으로 사용중인 프로세스를 확인해 주세요.

**Comment by lshqqytiger** [comment]
@Alex4386 netstat -an | find "80" 명령어로 보니까

  TCP    ip:80     ip:64220    ESTABLISHED
  TCP    ip:80     ip:34312   TIME_WAIT
  TCP    ip:80     ip:34398   TIME_WAIT
  TCP    ip:80     ip:34484   TIME_WAIT
  TCP    ip:80     ip:34516   TIME_WAIT
  TCP    ip:80     ip:34616   TIME_WAIT
  TCP    ip:80     ip:8468    ESTABLISHED
  TCP    ip:80     ip:8469    ESTABLISHED

ip 부분은 가렸구요 이렇게 나오네요 검색해보니까 ESTABLISHED이 연결된 상태라고; 어떻게 해야할까요?

**Comment by Preta-Crowz** [comment]
`netstat -ano | findstr :80` 입력 후, 표시되는 프로세스 아이디를 보고 프로세스를 종료하면 됩니다.

**Comment by lshqqytiger** [comment]
@Preta-Crowz 해봤더니 0이랑 4랑 7340, 496, 3492가 나오길래 taskkill /f /pid 0 해봤더니 중대한 시스템 프로세스라 하고 7340, 496, 3492는 종료가 돼고 4는 액세스 거부가 뜨네요..; 서버 실행은 똑같이 뜨며 안됩니다.

**Comment by Preta-Crowz** [comment]
0번과 4번은 시스템 프로세스로, 종료가 불가능합니다. iis 등이 실행 중인건 아닌지 확인해보세요.

**Comment by lshqqytiger** [comment]
@Preta-Crowz IIS Worker Process (w3wp.exe) 라는게 백그라운드로 실행되고 있길래 껐는데 다시 켜지네요. 꺼진 시간 사이 끄투 실행해도 똑같이 뜨구요..ㅠ

**Comment by Preta-Crowz** [comment]
IIS가 실행중인 것으로 보입니다. IIS를 사용하지 않는다면 제어판 -> 프로그램 -> Windows 기능 켜기/끄기의 인터넷 정보 서비스를 체크 해제하고 확인을 누르면 IIS가 제거됩니다.

**Comment by lshqqytiger** [comment]
@Preta-Crowz 덕분에 해결했습니다. 감사합니다!
