### ISSUE TITLE
jjo.kr/kkutu 의 서버 아이콘이 바뀌지 않습니다.

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#39]
서버 아이콘을 맨 하위에 있는 logo.ico를 변경하는 걸고 알고 있는데, 변경을 하여도 끄투 개구리만 나오네요. 바꾸는 방법이 있나요?

![d](https://cloud.githubusercontent.com/assets/13843919/23175732/9132d802-f8a3-11e6-9866-d8d6b5bdaa32.JPG)
(참고용입니다)

**Comment by msquid** [comment]
server\lib\web\public\favicon.ico를 바꿔보세요.

**Comment by kim-min** [comment]
감사합니다
