### ISSUE TITLE
외부 아이피로 도메인 설정 시 뜬금없이 끄투 서버가 아닌 공유기 홈페이지가 뜹니다

### ISSUE THREAD

**Issue by SeLeCT-Rumy** [JJoriping/KKuTu#392]
![0001](https://user-images.githubusercontent.com/44940733/49334946-b83c9100-f625-11e8-8cfa-6c94aaa5a661.PNG)
이렇게 하고 도메인으로 들어가봤더니 뜬금없이
![default](https://user-images.githubusercontent.com/44940733/49334950-d1ddd880-f625-11e8-9ec6-f6356b981abc.PNG)
얘가 뜹니다
어떻게 해야될까요
쪼롤에 서버 등록하려면 이렇게 하고 내부 아이피와 외부 아이피를 연결하라는데..

**Comment by minesna** [comment]
내부아이피로 접속해보세요
( 127.0.0.1 , 192.168.*.* )

**Comment by SeLeCT-Rumy** [comment]
접속이 문제가 아니고 지금 연결이 문제입니다. 어째서 외부 아이피로 도메인을 설정하면 도메인으로 연결 시도 시 끄투가 아닌 것이 나오는가..에요

**Comment by minesna** [comment]
디스코드 참고해주세요

**Comment by usb9245** [comment]
공유기 원격접속 설정 꺼보세요
