### ISSUE TITLE
유저 정지 해제하는법

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#393]
밴 테스트로 저에게 밴을 넣어보았는데
어떻게 푸는지 모르겠습니다.
black을 빈칸으로 둬도 다시 돌아오고...

**Comment by Preta-Crowz** [comment]
관리 페이지가 불안정하여 관리 페이지에서는 안됩니다. PgAdmin 등을 통하여 DB를 직접 수정해야합니다.

**Comment by plkmnb100** [comment]
제가 그 서버를 돌리는 것이 아니라 제가 그 서버의 GM입니다. 저는 현재 서버파일 수정권한이 하나도 없습니다. 어떻게 관리자페이지에서만 해결할 수는 없나요?

**Comment by Preta-Crowz** [comment]
현재로써는 방법이 없습니다. 개발자가 해제하는 방법을 만들거나, 직접 SQL을 수정해야합니다.

**Comment by lorlol701** [comment]
gwalli에서 black 칸을 null로 설정해 보세요.
