### ISSUE TITLE
서버 접속 문제(?)..

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#396]
'서버 자체는' 열리는 것 같은데 127.0.0.1에서 감자 서버 접속을 하면 
![vewwv](https://user-images.githubusercontent.com/43586090/49781636-d78a9b00-fd56-11e8-977b-25ad4693be5d.PNG)
이 상태로 무한로딩이 됩니다..
왜 그런거죠..
오류는 하나도 안 나는데;;

**Comment by Ryzen72700** [comment]
pug파일 또는 다른파일(어쨌든 웹사이트 구동하는데 필요한파일)중에 오류가뜬거 같네요
수정된 파일에서 **띄어쓰기/대, 소문자등..**이 잘못되었는지 확인해보세요
만약 문제없다면 원본 파일을 받아서 넣어보세요 (전 모듈파일때문에 접속이 막혔는데 어떤분이 새로받아서 하라는것?이 달려서 해봤는데 들어가지더라고요)

**Comment by andjsrk** [comment]
pug 파일을 완전히 새 걸로 교체했는데도 문제가 지속되는 것으로 보아 pug 파일 문제는 아닌 것 같아 보이는데요..

**Comment by andjsrk** [comment]
아 .js파일 2개가 문제였네요 해결했습니다.
감사합니다
