### ISSUE TITLE
끄투 봇이 계속 ...T.T을 치네요..

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#397]
127.0.0.1로 접속해서 하고 있는데 끄투 봇이 계속 <글자>...T.T만 치고 죽네요..
classic.js를 손보긴 했는데 그 경우는 아예 아무것도 안 치고 죽을 때 말하시는 것 같던데..

**Comment by CraftyDragon678** [comment]
#38 을 참고해 주세요

**Comment by andjsrk** [comment]
ROBOT_HIT_LIMIT 항목을 전부 1000으로 바꾸어도 그대로 ...T.T을 치네요..

**Comment by andjsrk** [comment]
??? 갑자기 정상작동 하네요.. 뭐지;
