### ISSUE TITLE
솎솎 글자

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#398]
솎솎 글자가
![cdsc](https://user-images.githubusercontent.com/43586090/49859886-f7e05580-fe3b-11e8-877e-0317d4f92405.PNG)
다음의 글자만. 즉, '정해진 글자밖에' 나오지 않습니다.

**Comment by Preta-Crowz** [comment]
소스 수정이 거의 이루어지지 않은 냉이 끄투에서 실험 결과, 잘 작동합니다.
서버 구축시에 DB를 입력하지 않았다면 단어가 부족하여 해당 현상이 발생 할 수 있는 것으로 보입니다.

**Comment by andjsrk** [comment]
DB를 입력했고, 단어도 충분합니다. 흠..
