### ISSUE TITLE
게임 서버의 master.js 부분에 대해 문의를 남기려고 합니다.

### ISSUE THREAD

**Issue by yom21c1020** [JJoriping/KKuTu#4]
라즈베리파이 모델 3B에서 운영하기 위하여 삽질을 하고 있습니다.
로비까지는 문제가 없는데, 방을 만드려고 시도하면 /Server/lib/Game/master.js의 139라인(확실한지는 모르겠습니다.), Cluster.on('mes~', function(worker, msg) {} 부분의 msg 인자가 선언되지 않은걸로 나옵니다. (TypeError: Cannot read property 'type' of undefined 혹은 비슷한 에러 문구)
인자를 제대로 함수로 넘겨주지 못하여 발생한 에러로 추정하고 있습니다만, 혹시 이에 대한 해결 방법이나 원인을 알 수 있을까요? 없다면 다른 오류를 고치기 위해 임의로 코드를 수정한 것이 문제였을 수 있을까요?

**Comment by JJoriping** [comment]
안녕하세요. `Cluster.on('message', ...)` 함수의 두 번째 인자(콜백 함수)의 두 번째 인자(`msg`)는 자식 프로세스(해당 파일에서는 `./Server/lib/Game/slave.js`)로부터 `process.send(...)` 함수가 호출되었을 때 이 함수의 첫 번째 인자가 넘어가는 구조입니다. 만약 임의로 `process.send(...)` 함수를 이용하신 경우 꼭 여기에 들어가는 인자가 `undefined`가 되지 않도록 유의해 주시기 바랍니다.

**Comment by yom21c1020** [comment]
답변해주셔서 감사드립니다..! 시도해도보록 하겠습니다.

**Comment by yom21c1020** [comment]
혹시 몰라서 재설치를 하였습니다. `msg`가 계속해서 `undefined`로 출력되며 따로` ./Server/lib/Game/slave.js` 부분을 건드리지는 않았습니다. 한 일은
Strict mode 활성화 (`SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode` 수정 위함)
`function(var, ...args)`를 `function(var, args)`로 수정 (`SyntaxError: Unexpected token ...` 수정 위함)
정도입니다.

**Comment by JJoriping** [comment]
호출 스텍을 보신 뒤에 `msg`가 어디서 `undefined`가 되는지 찾으시는게 좋겠습니다. 정 못 찾으시겠으면 `Cluster.on('message', ...)` 부분에서 `msg`가 `undefined`인 경우에 대한 예외 처리를 별도로 해 주세요.

**Comment by yom21c1020** [comment]
힘드네요 ㅠ 노력해 보겠습니다!
`msg`가 `undefined`일 경우에 예외처리를 해서 서버 동작이 가능할까요?;;

**Comment by JJoriping** [comment]
저는 일단 그런 적이 없어서 뭐라 확답해드릴 수가 없습니다 :( 아마 node.js 버전이 달라서 생기는 문제인 것 같은데 버전 6.9.5 기준으로 정상 작동하니 참고해 주세요.

**Comment by yom21c1020** [comment]
앗 참고하겠습니다!
