### ISSUE TITLE
네이버 소셜 로그인 

### ISSUE THREAD

**Issue by junho0118** [JJoriping/KKuTu#40]
질문하겠습니다. 

1. jauth.js 40-41번째 줄에 클린트 아이디랑 시크릿 아이디 작어야 하는게 맞죠?

그리고 또 19-20 줄에도 아이디랑 시크릿 적어야 하죠?

2. in_iogin.js에 몇번째 줄을 수정해야 네이버 소셜 로그인이 정상적으로 작동할까요?

3. 그외에 수정할게 있나요?

**Comment by pkpai0926** [comment]
1. 네 맞아요.
2. `in_login.js` 파일의 50번째 줄과 51번째 줄에 Client ID와 Callback URL 입력하면 됩니다.
3. `server-setup.bat` 파일 실행하셨다면 `server-flush.bat` 파일 실행시켰다가 다시 한 번 `server-setup.bat` 파일 실행시키세요.
