### ISSUE TITLE
정상적으로 운영 중이지 않은 서버에 대한 리스트 삭제 요청

### ISSUE THREAD

**Issue by L4by** [JJoriping/KKuTu#402]
안녕하세요. 요즈음 끄투 프리서버 리스트에 등록만을 하기 위한 목적으로 개설된 목적불명의 서버들이 나타나고 있습니다. 이는 끄투 프리서버의 방문이라는 리스트의 본 목적을 해치는 행위라 판단되어 12월 19일 기준 아래의 2개 서버에 대한 삭제 요청을 하고자 합니다.

1. [Wain Online](http://wain.cf)
접속자가 -2147483647명으로 표시되고 끄투 플레이를 위한 환경이 전혀 마련되지 않은 채 몇 달 동안 방치되어 있는 의미불명의 서버입니다.

2. [끄투 달력](https://date.kro.kr)
끄투 플레이를 위한 환경이 전혀 마련되지 않은 채 달력이라는 명분으로 몇 달 동안 방치되어 있는 의미불명의 서버입니다.

감사합니다.

**Comment by Preta-Crowz** [comment]
달력의 경우 KKSP 적용 직후로 삭제일이 예정된 상태입니다.

**Comment by hatty163** [comment]
@ptrkr님의 2개의 서버에 이어서,

끄투코리아 테스트
http://test.kkutu.co.kr
2017. 9. 26. 등록

모리끄투
https://kkutu.pw
2017. 9. 26. 등록

라이프끄투
http://lifekkutu.oa.to
2017. 10. 3. 등록

라이트끄투
http://litekkutu.xyz:90
2017. 9. 1. 등록

Gultu
http://gultu.ze.am
2017. 12. 3. 등록

끄투닷넷
http://끄투.닷넷
2017. 12. 28. 등록

가루끄투
http://gkkutu.kro.kr
2018. 3. 27. 등록

오투 온라인
https://www.otu.kr
2018. 5. 26. 등록

글쨔로뇰쟈
http://gzlnz.kro.kr
2018. 5. 27. 등록

메모리 끄투
http://kkutu.memorykkutu.zz.am
2018. 8. 13. 등록

아워끄투
https://ourkkutu.net
2018. 8. 28. 등록

이 서버들도 삭제 요청합니다. @JJoriping (11개)
5~6달은 열리지 않아 삭제가 필요한 서버입니다.

**Comment by SeLeCT-Rumy** [comment]
@hatty163 님에 이어서

STKTonline
http://satskkutu.kro.kr
2018. 11. 3 등록

하람끄투
http://haram2.kro.kr
2018. 9. 25 등록

LPKKUTU
http://lpkkutu.kro.kr
2018. 9. 5 등록

등록 이후로 열리는 것을 보지 못한 서버들입니다.

**Comment by lshqqytiger** [comment]
@hatty163 아워 끄투는 현재 운영중입니다. 지금은 아워 끄투 총괄분이 여행을 가셔서 잠시 저희 BF끄투에 일시 합병된 상태입니다.

**Comment by houlday** [comment]
2019년 6월차로 @SeLeCT-Rumy 님에 이어서

냉이끄투
http://냉이.한국
2018. 10. 24 등록 (2018년 10. 24 에서 6월 6일이면 5~6달이기 때문에 처리가 필요합니다)

**Comment by junykkutu** [comment]
2019년 10월차로 @houlday 님에 이어서
서비스 종료 (모두끄투)
https://modukkutu.kro.kr
스우 끄투
http://swoo-kkutu.kro.kr
스우끄투는 3달 전 접속한 결과 시공에 폭풍속으로 날라갔다고 뜨네요....
뜨투 시즌 블랙
http://ddutu.ze.am
2019년 10월차로 @houlday 님에 이어서
서비스 종료 (모두끄투)
https://modukkutu.kro.kr
스우 끄투
http://swoo-kkutu.kro.kr
스우끄투는 3달 전 접속한 결과 시공에 폭풍속으로 날라갔다고 뜨네요....
뜨투 시즌 블랙
http://ddutu.ze.am
나비 끄투
https://nabitu.ze.am 
나비끄투는 전에 디도스 공격을 받고 있었는데 총괄분도 개발 중단 상황이여서 그런지 서비스 종료인것 같습니다.

**Comment by junykkutu** [comment]
그리고 KKSP착수 이라면 10월 13일 0시 이후 닫혀있는 서버가 모두 삭제 된다고 합니다. 이제 이 의문의 (?) 서버도 모두 삭제되겠죠

**Comment by lorlol701** [comment]
10월 13일 0시 기준으로 `열려 있기만 하면` 삭제 처리되지 않습니다.

**Comment by L4by** [comment]
완료된 이슈인 것 같아 닫습니다.
