### ISSUE TITLE
로딩 화면 사진 변경 등

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#404]
로딩 화면 , 게임창 밖의 배경 (기본 검은 배경) , 게임 들어가기 전 서버 선택 화면의 KKUTU 로고 어떻게 바꾸나요?

각각 레포지토리의 폴더를 설명해주시면 감사하겠습니다.

**Comment by andjsrk** [comment]
\Server\lib\Web\public\img의
\bg\def.png가 게임창 밖의 배경이고요,
나머지는
\kkutu의 short_logo.png, intro.png입니다.

**Comment by plkmnb100** [comment]
>           \Server\lib\Web\public\img의
> \bg\def.png가 게임창 밖의 배경이고요,
> 나머지는
> \kkutu의 short_logo.png, intro.png입니다.

혹시 열린 방 / 닫힌 방 같은 사진도 있나요? 어디에 있나요? 이런
![default](https://user-images.githubusercontent.com/44970486/50285962-2b0c8f80-04a1-11e9-8b35-e3c90a317f3f.PNG)
거요

**Comment by Preta-Crowz** [comment]
해당 부분은 css로 구현된 부분이기에 이미지는 없습니다. 이미지를 추가하려면 별도의 작업이 필요합니다.

**Comment by lshqqytiger** [comment]
@plkmnb100 해결 되셨으면 이슈를 닫아주시기 바랍니다.
