### ISSUE TITLE
포트포워딩

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#405]
TPLINK 공유기인데 어떻게 해야할지 하나도 모르겠습니다....
![default](https://user-images.githubusercontent.com/44970486/50287525-5fcf1580-04a6-11e9-8067-040d3073d9c6.PNG)

**Comment by Preta-Crowz** [comment]
80, 8080, 8492번 포트를 포트포워딩해야합니다.
그리고 사진에 비밀번호 노출됐습니다. 바꾸세요.
