### ISSUE TITLE
Google+ api 중지

### ISSUE THREAD

**Issue by 3333303** [JJoriping/KKuTu#406]
2019년 3월 7일부로 구글이 google+ api를 중지한다고 합니다. 제가 알기로는 구글 계정으로 로그인에서 이 api를 사용하는데  이에 대해 대책이 필요할것 같습니다

**Comment by Preta-Crowz** [comment]
서버 구축 및 업데이트 시 로그인을 변경 할 수 있습니다. 기존의 로그인이 아닌 새로운 로그인을 추가 할 수 있으며, 프로젝트 끄투의 경우 기본 5종 외에 8곳을 지원 중입니다.
