### ISSUE TITLE
안녕하세요 끄투서버 구축하는데 로그인 기능에 문제가 생겨서요

### ISSUE THREAD

**Issue by developerLim** [JJoriping/KKuTu#407]
네이버 구글 카카오 이렇게 3개 구축했는데 카카오랑 네이버 구글 전부 오류가 납니다 로그인 창에서 400이나 오류같은거뜨고요 팀뷰어나 댓글로 도움청합니다 ㅠㅠ

**Comment by developerLim** [comment]
해결해주세요 ㅠㅠ 여기서 못넘어가고있어요

**Comment by Preta-Crowz** [comment]
로그에 오류 내용이 표시되는지 확인하고, 표시된다면 해당 내용을 첨부하여주세요.
