### ISSUE TITLE
권한 추가

### ISSUE THREAD

**Issue by developerLim** [JJoriping/KKuTu#408]
ADMIN 권한을 1명만 줄수있나요? 더 늘릴수는 없는건가요?

**Comment by lshqqytiger** [comment]
"ADMIN": [ "식별번호1", "식별번호2", "식별번호3" ], 이런 식으로 늘리시면 됩니다.

**Comment by lshqqytiger** [comment]
@developerLim 해결되셨으면 이슈를 닫아주시기 바랍니다.
