### ISSUE TITLE
round_start.mp3에 관련해서...

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#41]
round_start.mp3를 교체하려고 합니다만, 기존 음원보다 약 1초정도 더 깁니다.
그래서인지, 뒷부분이 잘리면서 게임이 바로 시작되네요.
round_start 재생시간을 늘리고 싶습니다. 어떻게 해야하나요?

**Comment by JJoriping** [comment]
각 게임 유형에 대한 소스 코드에서 `setTimeout(my.turnStart, 2400)` 부분의 `2400`을 모두 해당 음원의 지속 시간으로 바꾸어야 합니다.

**Comment by kim-min** [comment]
2400이라는 수는 기존 round_start.mp3 의 틱단위 인가요?

**Comment by JJoriping** [comment]
네.

**Comment by kim-min** [comment]
감사합니다.
