### ISSUE TITLE
로그인

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#410]
로그인 하는방법좀 알려주세요ㅠㅠ

**Comment by Preta-Crowz** [comment]
각 개발자센터에서 키를 발급받은 후, auth.json에 입력하세요. 사용하지 않는 로그인 방식은 비활성화해둬야합니다.

**Comment by lshqqytiger** [comment]
참고로 비활성화는 \KKuTu-master\Server\lib\Web\auth 에서 사용하지 않는 로그인 방식 파일의 파일명 맨 뒤 (확장자 뒤) 에 .DIS나 .disabled 등등을 붙이면 됩니다.

**Comment by lshqqytiger** [comment]
@hands8142 해결되셨다면 이슈를 닫아주세요.
