### ISSUE TITLE
추가한 주제가 단어 대결 등 게임모드 주제 선택창에서 안나옵니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#412]
분명히 주제를 추가했고, 끝말잇기에서 사용 가능한것도 확인했지만, 단어 대결, 그림 퀴즈 등 주제를 선택하는 게임 모드 주제 선택창에서 나오지 않습니다. 따로 설정해야 하는게 있나요?

**Comment by andjsrk** [comment]
혹시나 const.js에 안 넣으셨다면 const.js의 exports.KO_INJEONG = [ ]; 부분에 주제 코드 넣으셔야 할겁니다.

**Comment by lshqqytiger** [comment]
저번에 그림 퀴즈 추가하면서 주제 코드가 날아갔나보네요. 다시 넣어줬더니 정상적으로 표기됩니다.
