### ISSUE TITLE
서버 추가 방법

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#414]
서버 추가하는 방법을 모르겠어요

**Comment by Preta-Crowz** [comment]
ko_KR.json 파일을 수정하여 저작권 관련 표시를 수정한 이후, 쪼롤에서 내 서버 등록하기를 누른 후, 서버 이름, 서버 주소와 관리 비밀번호를 입력하세요. 단, 서버가 켜져있어야합니다.

**Comment by hands8142** [comment]
그거말고 감자서버 냉이서버 요

**Comment by andjsrk** [comment]
감자 서버는 기본적으로 있을 테고, 냉이 서버를 추가하시고 싶으시면 global.json의 `"MAIN_PORTS": [ 8080 ],`부분을 `"MAIN_PORTS": [ 8080, 8090 ],`으로 변경하시고 게임 서버를 클러스터링하면 됩니다.
클러스터링에 관해서는 https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81 참고해주세요

**Comment by lshqqytiger** [comment]
KKuTu/Server/lib/sub/global.json의 "MAIN_PORTS": [ 8080 ],를 "MAIN_PORTS": [ 8080, 8090 ],처럼 원하는 서버 개수만큼 포트를 적어주시면 됩니다. 포트의 경우 웹서버 포트(기본 80)과 게임 서버 포트와 게임 서버 포트 + 416을 열어주셔야 합니다.

#292 인용

**Comment by hands8142** [comment]
냉이서버가 만들어졌는데 여는거는어덯게해요 꺼져있는데

**Comment by andjsrk** [comment]
운영 체제 윈도우이신가요?

**Comment by kimhj050326** [comment]
settings.json 에서 서버 갯수를 2개로 늘려주세요.

**Comment by hands8142** [comment]
어느것을 수정해야 돼요??

**Comment by kimhj050326** [comment]
game_num_inst 값을 1에서 2로 수정해주세요.

**Comment by hands8142** [comment]
감사합니다
