### ISSUE TITLE
login.js 에러 관련입니다.

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#418]
![image](https://user-images.githubusercontent.com/31878663/51005428-1728ea80-1582-11e9-8229-e8c2c45d8b30.png)
이 오류가 뜨면서로그인버튼이 안뜹니다.

**Comment by lshqqytiger** [comment]
Server\lib\sub\auth.json의 클라이언트 ID 관련 문제 같습니다. 확인해보세요.

**Comment by 3110222F** [comment]
![image](https://user-images.githubusercontent.com/31878663/51006904-b2bd5980-1588-11e9-8fcb-5e9e5ee780cf.png)
이게 문제있는건가요? 어디가 문제있는 것인가요?

**Comment by lshqqytiger** [comment]
클라이언트 ID나 클라이언트 시크릿 키를 제대로 읽지 못하는 것 같네요.

**Comment by kimhj050326** [comment]
클라이언트 ID 와 시크릿 문제는 아닙니다.
auth 폴더에서 안쓰는 로그인 파일들은 이름앞에 DISABLE. 을 붙여주시길 바랍니다.

**Comment by lshqqytiger** [comment]
아 410 이슈 작성하신 분이랑 같은분이신 줄 알고 헷갈렸네요. 메일이 두개가 같이와서 혼동했습니다
