### ISSUE TITLE
또 오류가 발생했습니다

### ISSUE THREAD

**Issue by 3110222F** [JJoriping/KKuTu#419]
![image](https://user-images.githubusercontent.com/31878663/51031451-f7281400-15df-11e9-86b1-c59fe7ca2c84.png)
계속 이런 오류가 뜹니다어떻게 해야 하나요

**Comment by CraftyDragon678** [comment]
Redis서버를 깔아주셔야 합니다.

**Comment by 3110222F** [comment]
밑에 webㅇ어 쩌구요. 는 어캐 하나요
