### ISSUE TITLE
관리자 관련 기능, 단어 뜻 관련 질문

### ISSUE THREAD

**Issue by horyu1234** [JJoriping/KKuTu#42]
1. 특정 사용자 또는 아이피를 블록하거나 생성된 비밀 방에 강제로 들어가는 등의 기능이 있는지 여부가 궁금합니다.
2. 현재 프리 서버는 기본적으로 단어 뜻이 데이터베이스에서 빠져있는데, 이것을 따로 저작권관련 요청 등을 하여, 추가할 수 있는지 여부가 궁금합니다.

감사합니다.

**Comment by JJoriping** [comment]
주제가 다른 질문은 다른 분들이 찾아 보기가 쉽도록 가급적 별도의 이슈로 등록하는 것을 권합니다.

1. 강제로 들어가는 방법은 없습니다. 단 관리자 계정으로 채팅 `#tailroom {방 번호}`를 입력하면 해당 방에 대한 정보가 출력되면서 방의 암호를 알아낼 수 있습니다.
2. 표준국어대사전의 데이터베이스 이용 계약을 한국복제전송저작권협회와 맺어 국립국어원의 승인을 받은 뒤에는 계약에 명시된 범위 내에서 표준국어대사전의 데이터베이스를 자유롭게 이용하실 수 있으니 참고해 주세요.

**Comment by horyu1234** [comment]
감사합니다.
