### ISSUE TITLE
GM권한을 2명에게 주는 방법?

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#420]
Gm을 2분에게 지급하는 방법이 궁금합니다

다 시도해봤는데 오류나면서 서버 안켜질때도 있더라고요..

**Comment by CraftyDragon678** [comment]
Server/lib/sub/global.json의 "ADMIN"에다가 유저의 ID를 배열로 넣으면 됩니다. 문자열로 넣으시면 됩니다.

**Comment by plkmnb100** [comment]
> Server/lib/sub/global.json의 "ADMIN"에다가 유저의 ID를 배열로 넣으면 됩니다. 문자열로 넣으시면 됩니다.

어떻게 넣어야하나요? 지식이 부족해 이해가 안되네요 ㅠㅠ

**Comment by plkmnb100** [comment]
해결되었습니다
