### ISSUE TITLE
바꾸기

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#423]
처음에 나오는 개발자블로그 바로가기를 저의 디스코드로 만들려고 하는데 어떻게해요??

**Comment by lshqqytiger** [comment]
portal.pug의

		div#menu-bar(style='float: right; margin-top: 25px;')
			a(target='_blank', href='//cafe.bfkkutu.ze.am/', style='background-color: #189E47;')= 'Naver Cafe'
			a(target='_blank', href='//discord.gg/scPVHcE', style='background-color: #233599;')= 'Discord'

부분을 수정하시면 됩니다.

**Comment by hands8142** [comment]
링크말고 아이콘 링크는이미 만들었어요
