### ISSUE TITLE
구글 404 오류

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#424]
네이버를 알려주셔서 응용을 통해 구글도 했는데 404오류가 뜹니다
이건 어쩌죠?
![image](https://user-images.githubusercontent.com/31878663/51072130-0cb04300-169f-11e9-85fc-5ea19ccc7163.png)

**Comment by lorlol701** [comment]
OAuth로 리다이렉트되는 링크가 맞는지 체크해보시기 바랍니다.
