### ISSUE TITLE
게임, 갤러리바꾸기

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#425]
왼쪽위에있는 게임 갤러리를 바꾸는 방법을 알려주세요

**Comment by lorlol701** [comment]
게임 갤러리라는게 뭘 말하시는건지 알수가 없습니다.

**Comment by hands8142** [comment]
왼쪽위에 있습니다

**Comment by hands8142** [comment]
바로가기

**Comment by lorlol701** [comment]
왼쪽 위에 무엇을 말하시는건지 자세히 말해주셔야;

**Comment by hands8142** [comment]
그집모양이랑 게임 나오는 바로가기

**Comment by lshqqytiger** [comment]
module.pug의 	const MENU = [
		{ key: 'HOME', href: "http://bfkkutu.ze.am" },
		{ key: '소통', sub: [
			{ key: '디스코드', href: "https://discord.gg/scPVHcE" },
			{ key: '네이버 카페', href: "http://cafe.bfkkutu.ze.am" },
		]},
	];

부분을 수정하시면 됩니다.

**Comment by hands8142** [comment]
링크는 그렇게 바꾸는데 게임을 홈페이지바로가기라고 이름을 바구고싶은데

**Comment by lshqqytiger** [comment]
ko_KR.json에서     

"GAMES": "게임", 

부분을 찾아 바꾸세요.
