### ISSUE TITLE
redis 설치 오류

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#427]
![image](https://user-images.githubusercontent.com/31878663/51148085-27053f00-18a0-11e9-9265-e6435e6c3c0c.png)
이런 올오류가 뜹니다...

**Comment by SeLeCT-Rumy** [comment]
Redis는 끄투 내의 랭킹 및 일부 세션을 작동시키기 위한 매개체입니다.
Redis 서버가 작동되지 않으면 끄투 인게임 내 랭킹을 볼 수 없습니다.
