### ISSUE TITLE
봇

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#429]
봇이 바보에요

**Comment by lshqqytiger** [comment]
const ROBOT_HIT_LIMIT = [ 1000 ];

으로 하니까 잘 되는데요?

**Comment by hands8142** [comment]
???

**Comment by hands8142** [comment]
안돼는데요

**Comment by lorlol701** [comment]
제발 다른 이슈 둘러보고 말합시다;;

**Comment by mhnsoft** [comment]
> 안돼는데요
저는 잘만 되는데요???
윗분 말 처럼 다른 이슈 둘러보고 말하시고
그것도 이해가 안가면 기초적인 부분을 공부하세요.
이건 마인크래프트 서버와 다릅니다...

**Comment by lshqqytiger** [comment]
맞습니다. 끄투는 처음부터 끝까지 모두 직접 공부하고 구현해야합니다.
