### ISSUE TITLE
사용자를 차단하는 방법에 대하여

### ISSUE THREAD

**Issue by horyu1234** [JJoriping/KKuTu#43]
특정 사용자의 고유 번호로 차단한다거나, 아이피를 접근하지 못하도록 차단하는 등의 방법이 있을까요?

**Comment by JJoriping** [comment]
데이터베이스 `main`에서 `users` 테이블의 `black` 열의 값을 수정하면 해당 사용자의 게임 이용이 제한됩니다. IP 주소를 이용한 차단 방법은 끄투 쪽에서 구현된 사항이 아니며 현재로서는 운영 체제 수준에서 IP 주소를 차단해야 합니다.

**Comment by horyu1234** [comment]
감사합니다
