### ISSUE TITLE
관리자 사이트가 들어가지지 않습니다.

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#432]
일단 제가 구글 로그인을 해서 제 식별id를 받아서 아이디를 global.json에 넣었습니다
![image](https://user-images.githubusercontent.com/31878663/51219466-656c2e00-1974-11e9-98b5-bcf33aa9b9df.png)
그후 gwalli에 모든항목에도 제 id를 넣었습니다
![image](https://user-images.githubusercontent.com/31878663/51219503-8fbdeb80-1974-11e9-8e14-f57764d2ce83.png)

그후 psql을 이용하여 gm휘장을 얻었습니다.
![image](https://user-images.githubusercontent.com/31878663/51219520-a95f3300-1974-11e9-990b-4b34be252635.png)

그래서 http://서버주소/gwalli 에 들어가면 
![image](https://user-images.githubusercontent.com/31878663/51219542-bf6cf380-1974-11e9-9489-c5d277b2f128.png)
이런 오류가 뜨고 http://서버주소/C:\Users\GoUSER\Desktop\HappyPlus\KKuTu-master\Server\lib\Web\views\gwalli 에 들어가면 
![image](https://user-images.githubusercontent.com/31878663/51219623-ffcc7180-1974-11e9-8a58-3c175b2c2d99.png)
이 오류가 뜹니다.
이슈를 찾아보니 '디렉터리 로그인' 을 하라는데 '디렉터리 로그인'은 어떻게 하는것인가요?

**Comment by lorlol701** [comment]
관리페이지에서 err 400이 뜨는 경우는 자신의 프리 서버 로비에서 로그인이 되어잇지 않은 경우에 발생합니다. 먼저 로비에서 관리자 계정(global.json ADMIN 칸에 있는 유저) 으로 로그인 한 후 새 탭에서 관리페이지로 접속해보세요.

**Comment by lorlol701** [comment]
참고로 로그인한 후 탭은 계속 열어둬야 합니다. 로비 페이지를 닫을 경우 관리페이지가 작동하지 않습니다.

**Comment by kimhj050326** [comment]
@YTHappyPlus 설정후, 서버 재시작은 하셨는지 확인해주세요.
