### ISSUE TITLE
모드,조건 추가

### ISSUE THREAD

**Issue by developerLim** [JJoriping/KKuTu#433]
안녕하세요 프리서버 운영자입니다만 현재 그림퀴즈같은 모드랑 깐깐과 같은 조건을 추가하고 싶어 여쭤봅니다 모드랑 조건은 어디서 추가하는것인지 알려주시면 대단히 감사하겠습니다

**Comment by lshqqytiger** [comment]
그림퀴즈는 PR의 코드 사용하시면 되며, 조건은 특수 규칙은 ko_KR.json과 const.js에 관련 내용 추가하시고 나머지 부분은 직접 구현하셔야합니다.

**Comment by lshqqytiger** [comment]
#326 그림퀴즈 PR 입니다.

**Comment by lshqqytiger** [comment]
게임 모드를 추가하기 위해선 Game\games 폴더에 이름.js 파일을 생성하시고 ko_KR.json, kkutu.pug 등을 수정하셔서 직접 구현하셔야 합니다.

**Comment by lshqqytiger** [comment]
Server\lib\Web\lib\kkutu에 들어가보시면 rule_ 로 시작하는 파일들이 있습니다. 이것도 만드셔야 합니다.

**Comment by lshqqytiger** [comment]
1. Game\games에 js 파일 생성
2. Game\kkutu.js에 내용 추가
3. Gruntfile.js에 내용 추가
4. Web\lang\en_US.json에 내용 추가
5. Web\lang\ko_KR.json에 내용 추가
6. Web\lib\in_game_kkutu.js에 내용 추가
7. Web\lib\kkutu에 rule_~~~.js 파일 생성

등등 여러가지 파일을 수정/추가 하셔야 합니다.

**Comment by developerLim** [comment]
위에 말했던 7개만 수정하면 끝인가요?

**Comment by lshqqytiger** [comment]
그림퀴즈 같은 경우 CSS 파일도 수정합니다. 그리고 저것들 외에도 더 많은 파일 수정이 필요할 수 있습니다.

**Comment by developerLim** [comment]
어디 CSS를 수정하는거죠??

**Comment by lshqqytiger** [comment]
그림퀴즈의 경우 Server\lib\Web\public\css의 in_game_kkutu.css 도 수정합니다.

**Comment by developerLim** [comment]
넵 감사합니다

**Comment by developerLim** [comment]
ㅇin_game_kkutu.js 에는 무슨 내용을 추가하는거죠??

**Comment by lorlol701** [comment]
추가적으로 이슈를 열어 질문해주세요.

**Comment by kimhj050326** [comment]
무슨 내용을 추가하라고 정해진게 아닙니다. 직접 구현하시면 됩니다.

**Comment by SoBusted** [comment]
혹시 패션 개발자이신가요?

스스로 찾아볼 생각이 없으신 것 같은데
