### ISSUE TITLE
서버 접속안됨 (연결 시간 초과)

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#434]
localhost로 연결했을 때는 잘 됩니다.
하지만 내 IP로 접속했을 때에는 연결시간 초과가 됩니다.
참고로 포트포워딩이 아닌 DMZ로 사용중입니다
어제까지만 해도 잘 됐는데 왜 이럴까요..?
 (https://www.youtube.com/watch?v=l89z1njRTMY&feature=youtu.be)

**Comment by lshqqytiger** [comment]
영상에 IP 주소 노출되었습니다. 해킹당하실 수 있으니 빨리 지우세요.

**Comment by plkmnb100** [comment]
어차피 도메인만 알면 ip주소 ping 명령어로 알아낼수 있습니다.

**Comment by plkmnb100** [comment]
어차피 도메인만 알면 ip주소 ping 명령어로 알아낼수 있습니다.

**Comment by kimhj050326** [comment]
@lshqqytiger 어짜피 도메인 연동하면 IP공개되서 상관 없습니다.
@plkmnb100 외부 에서 접속을 하게하시려면, 포트포워딩으로 80포트, 8080포트, 8496포트 이렇게 열어주셔야 합니다.

**Comment by lshqqytiger** [comment]
근데 유튜브에 저렇게 노출되는건 좀 위험하지 않나요?

**Comment by plkmnb100** [comment]
@kimhj050326 DMZ로 설정하였고, 내부에서도 접속이 안됩니다

**Comment by plkmnb100** [comment]
@lshqqytiger 링크로만 접속할 수 있게 '미게시' 로 해놓았습니다만

**Comment by plkmnb100** [comment]
기다리니까 되네요.. 뭐죠? 이슈는 닫겠습니다.
