### ISSUE TITLE
휘장 관련 질문

### ISSUE THREAD

**Issue by developerLim** [JJoriping/KKuTu#437]
휘장 관련해서 질문드립니다 휘장을 착용했을때 모레미 휘장 착용된 모습은 보이고요 하지만 접속된 목록중에 휘장 [TWITCH]가 안뜹니다 GM 휘장을 잘 됩니다 어디가 문제죠??

**Comment by andjsrk** [comment]
in_game_kkutu_shop.css, in_game_kkutu.min.js에 GM과 똑같은 방식으로 칭호?를 추가해주세요.
