### ISSUE TITLE
그림퀴즈 추가 오류

### ISSUE THREAD

**Issue by developerLim** [JJoriping/KKuTu#438]
그림퀴즈를 추가하니  ERROR OCCURRED ON THE MASTER! :8080 [2019-1-19 15:16:51] ERROR: TypeError: Cannot read property 'processVendorMigration' of undefined TypeError: Cannot read property 'processVendorMigration' of undefined at exports.Client.my.refresh (C:\Users\Administrator\Desktop\KKuTu\Server\lib\Game\kkutu.js:424:31) at C:\Users\Administrator\Desktop\KKuTu\Server\lib\Game\master.js:341:8 at callback (C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\collection.js:316:13) at Result.preCB (C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (C:\Users\Administrator\Desktop\KKuTu\Server\lib\node_modules\pg\lib\query.js:144:10) at Connection.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:182:13) at Socket.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:182:13) at addChunk (_stream_readable.js:283:12) 이러한 오류가 발생합니다 그리고 게스트로만 게임을 들어갈수있고 로그인을하면 불러오는중 1에서 멈춥니다 그리고 그림퀴즈를 시작하면 그림이 안그려지고 브금이 나타나질않습니다

**Comment by lshqqytiger** [comment]
https://github.com/JJoriping/KKuTu/tree/17050314a383ce2bec55d4bfb3ce1e0605f66d63

를 다운로드 하고, 변경되는 파일들을 전부 기존 파일에 덮어쓰기 하세요.

**Comment by developerLim** [comment]
덮어쓰기하면 사라지지 않나요?
