### ISSUE TITLE
관리자(GM) 이 방에서 추방되는 것에 관련하여

### ISSUE THREAD

**Issue by horyu1234** [JJoriping/KKuTu#44]
관리자(GM) 을 방에서 추방하지 못하도록 하는 등의 조취를 취하여 합니다.
https://github.com/JJoriping/KKuTu/blob/9e5f8e5de07818d2d74d79c2c5a4063c238e16dd/Server/lib/Web/lib/kkutu/body.js#L621
이부분에서 아이디가 관리자 목록에 추가되어 있지 않을 경우에만 실행하도록 수정하려 하는데,
위 방법대로 수정을 하면 가능할지 조언좀 부탁드립니다 ㅠㅠ..

감사합니다.

**Comment by BasixKOR** [comment]
게임의 원활한 진행을 위하여 강퇴 이후에도 입장이 가능하게 만드는 편이 더 낫지 않을까 싶네요 ㅇㅂㅇ!

**Comment by horyu1234** [comment]
그럴까욤?..

**Comment by horyu1234** [comment]
근데 그렇게 되면 간혹 어떤 방에서 계속 추방하고 입장하고를 반복할 수가 있을 것 같아서 제는 추방자체를 막는게 좋을 것 같다고 생각이 드네욤..

**Comment by JJoriping** [comment]
막아야하는 의도를 잘 모르겠습니다만 [파일 `./Server/lib/Game/kkutu.js`](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Game/kkutu.js#L604)
쪽에서 조건문을 하나 추가하는 것을 권합니다.

**Comment by horyu1234** [comment]
감사합니다
