### ISSUE TITLE
컴퓨터 새로 설치하면 데이터베이스 다시 만들어야 하나요?

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#440]

**Comment by lshqqytiger** [comment]
데이터 베이스는 postgreSQL에 저장되므로 postgreSQL를 백업하지 않았다면 다시 구축해야합니다.

**Comment by plkmnb100** [comment]
그리고 백업안해놓으셨으면 유저DB 다 날아갑니다
유의하시기 바랍니다 (수정한 단어 DB 포함)
