### ISSUE TITLE
관리자 사이트에서 단어추가가 안 됩니다

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#442]
![image](https://user-images.githubusercontent.com/31878663/51532854-9244a780-1e84-11e9-9854-ea43d314de1c.png)
가 됬는데 단어 추가가 안됩니다.

**Comment by lshqqytiger** [comment]
자격 항목의 암호 (postgreSQL) 와 테이블 (ko, en) 항목을 입력하셨나요?

**Comment by YTHappyPlus** [comment]
그게 무엇인가요?

**Comment by lshqqytiger** [comment]
맨 위에 '자격' 이라고 된 부분에 비밀번호와 테이블 코드를 기입하여야만 동작합니다.

예시: postgreSQL을 설치할 때 비번을 123으로 설정했다면,

ㅡ자격ㅡ
123
ko

**Comment by lshqqytiger** [comment]
![](https://i.imgur.com/nU5GAnn.jpg)

이렇게요

**Comment by YTHappyPlus** [comment]
ko란에 데이터 베이스가 main이라면 main으르 넣어야 하나요?

**Comment by lshqqytiger** [comment]
글쎄요 전 ko와 en만 사용하기 때문에 그건 잘 모르겠네요.

**Comment by YTHappyPlus** [comment]
일단 해보겠습니다.
+@lshqqytige 
괜찮다면 디스코드 해피플러스 HappyPlus#6150 으로 물어도 될까요?

**Comment by lshqqytiger** [comment]
알겠습니다

**Comment by lshqqytiger** [comment]
안되는데요?

**Comment by lshqqytiger** [comment]
테이블을 main으로 설정하고 단어 불러오기하니까 오류를 뿜습니다.

**Comment by andjsrk** [comment]
테이블은 단어 관련 작업 시에는 ko(한국어), en(영어)를 쓰면 되며 나머지 작업(상점 데이터베이스 수정 등)을 하실 땐 그냥 공백으로 놔두시면 됩니다.

**Comment by lorlol701** [comment]
데이터베이스를 기재하는것이 아닙니다., ko 또는 en쪽의 테이블을 기재하는 거에요
