### ISSUE TITLE
추가가 안됩니다

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#443]
![image](https://user-images.githubusercontent.com/31878663/51575791-eb4d2380-1ef6-11e9-8576-3ca477eb6b9f.png)
파이일도 만들었는데 안됩니다

**Comment by lshqqytiger** [comment]
http://서버 주소/파일 이름 = Server\lib\Web\public\파일 이름
(http://서버 주소/favicon.ico에 들어가면 favicon.ico 파일이 웹페이지로 열림)

즉, Server\lib\Web\public에 그 파일을 넣으셔야 인식합니다.
