### ISSUE TITLE
기간밴 기능 추가하기

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#446]
기간밴 기능을 추가하려면 어느어느 파일을 수정/추가해야 하나요?

**Comment by kimhj050326** [comment]
여기는 구현방법을 묻는곳이 아닙니다. 이런 이슈등록은 삼가해주세요.

**Comment by kimhj050326** [comment]
그리고 기간밴같은 기존 끄투에 없던 기능들은 "직접" 구현하셔야 합니다.
