### ISSUE TITLE
쪼롤서버등록

### ISSUE THREAD

**Issue by lonylony** [JJoriping/KKuTu#448]
서버등록시 소유권을 확인하기위해서 다음주소로 접근했을때 입력한서버주소와 같도록처리해달라는데 그거 어떻게 넘어가나요?

**Comment by lshqqytiger** [comment]
Server\lib\Web\public에 kkutu-코드.html 이라는 파일을 생성한 후 자신 서버 도메인을 입력합니다.

**Comment by mhnsoft** [comment]
질문을 남기기 전에 먼저 이슈를 검색하세요.
검색하면 알 수 있는걸 굳이 질문하는 이유가 궁금하네요..

**Comment by plkmnb100** [comment]
#3
