### ISSUE TITLE
게임 로딩중...1에서 더이상 진행이 안됩니다.

### ISSUE THREAD

**Issue by KORraimi** [JJoriping/KKuTu#45]
http프로토콜로 연결하는겁니다만. 더이상 진행이 안되네요. 다른 이슈가 있지만 저랑은 다른 케이스인거 같아 남깁니다.

**Comment by SkyLightQP** [comment]
포트 열렸는지 확인해보세요.
개발자 도구 열고 콘솔보시면 문제 발생하면 로그 뜹니다.

**Comment by KORraimi** [comment]
in_kkutu~.js 계열 파일이 없네요

**Comment by JJoriping** [comment]
다른 케이스라는 것을 보이기 위한 부가적인 설명이 전혀 없어 답변을 드리기가 어렵습니다. 구체적으로 어떤 작업을 하는 중 오류가 발생했는지 작업 과정과 오류 내용 등이 담긴 사진 자료를 첨부하여 다른 사람들이 원인을 분석할 수 있도록 이슈를 남겨 주세요.

**Comment by KORraimi** [comment]
끄투서버를 열면 서버가 열립니다->끄투 게임 입장하기를 누릅니다-> 로딩에서 1 남겨넣고 진행이 안됩니다->개발자 도구 열어보니 404 에러가 뜹니다->? 인데 빈 파일을 어떻게 만드나요

**Comment by KORraimi** [comment]
제가 잘못생각했군요. 설정이 덜되서 일어나는걸로 보입니다.
