### ISSUE TITLE
외부아이피로 접속이 안됩니다

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#450]
현재 127.0.0.1로는 접속이 되었지만 제 실제 아이피로는 접속이 안됩니다.
DB is Ready라고는 떴는데 아예 서버가 127..0.0.1밖에 안되네요...
![1](https://user-images.githubusercontent.com/42174930/52052352-5f439780-2599-11e9-87ba-5f69f9968d2b.PNG)
![2 global](https://user-images.githubusercontent.com/42174930/52052353-610d5b00-2599-11e9-8012-b1c421a081cb.PNG)
![3 main](https://user-images.githubusercontent.com/42174930/52052355-636fb500-2599-11e9-8050-cbb18bcdf4f5.PNG)

**Comment by swoo5571** [comment]
수정1: 두번째 사진에서 , pg_pass가 유출되었던 점 수정.

**Comment by mhnsoft** [comment]
MAIN_PORTS를 8080으로 하셔야 할겁니다.

**Comment by UnderC** [comment]
통신사 공유기 1대와 iptime 공유기 1대를 사용중으로 예상됩니다.
통신사 공유기로 iptime 공유기 아이피를 포트포워드 시켜주신 뒤 iptime 공유기에서 
자신의 컴퓨터 아이피를 포트포워드 시켜주시면 되겠습니다

**Comment by swoo5571** [comment]
저는 iptime만 쓰고 있습니다.
