### ISSUE TITLE
STKT 서버 GPL 위반신고

### ISSUE THREAD

**Issue by kimhj050326** [JJoriping/KKuTu#452]
STKT Online 서버가 8월 13일에 쪼롤에 첫 등록 되었는데, 첫 커밋 이후로 수정된 소스코드를 지금까지 일체 공개하지 않았습니다.

레포지토리 주소: https://github.com/pixelamtor7903/KKuTu
쪼리핑님, 검토 부탁드립니다.

**Comment by PlavorSeol** [comment]
GPL은 AGPL이 아닙니다. 서버에 설치 및 실행하며 네트워크로 통신하는 소프트웨어의 소스 코드 공개 의무가 있는 것은 아닙니다.

**Comment by kimhj050326** [comment]
STKT 온라인이 소스코드를 수정한뒤 커밋을 안한건데, 그래도 상관없나요?
