### ISSUE TITLE
상점 아이템 승천

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#453]
휘장을 하나 추가했더니 아이템이 모두 승천했습니다.
왜 이러는 걸까요?
![default](https://user-images.githubusercontent.com/44970486/52172569-eca70780-27a4-11e9-85f0-49c5d821a408.PNG)

**Comment by mhnsoft** [comment]
\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

**Comment by lshqqytiger** [comment]
아이템 추가 후 서버 재부팅이 필요합니다.

**Comment by kimhj050326** [comment]
재부팅 해도 그대로라면, 아이템 추가할때 잘못 추가하였을경우 문제가 발생하여 로드되지 않는 경우도 있습니다. 아이템을 잘 추가했는지 확인해주세요.
