### ISSUE TITLE
다른사람은 잘접속이 됩니다만 제가 도메인으로 접속이 안됩니다 localhost로 접속해야만 됩니다 ..

### ISSUE THREAD

**Issue by Explorer4563** [JJoriping/KKuTu#454]

**Comment by PlavorSeol** [comment]
끄투 문제가 아니라 라우터 문제입니다. 일부 라우터는 외부 IP 주소를 통해 같은 네트워크 내부->외부 IP 주소->내부로 접속하는 것을 막기도 합니다. [위키](http://exit.plavormind.tk:81/)를 돌리고 있는 저 또한 마찬가지이며 이 경우 어떤 서버를 돌리든 똑같은 현상이 나타날 겁니다.

**Comment by Explorer4563** [comment]
해결법은 없을까요??

**Comment by SoBusted** [comment]
저도 그랬는데 공유기를 바꾸니까 잘되네요.

원래 공유기: SK_WiFi
지금 공유기: ipTime

광고하는게 아닙니다.

**Comment by Preta-Crowz** [comment]
일부 환경에서 서버컴에서 외부아이피로 서버를 접속 할 수 없는 경우가 있습니다. 이 경우 공유기 교체 등으로 환경을 변경해야합니다.
