### ISSUE TITLE
클러스터링

### ISSUE THREAD

**Issue by bucket12345** [JJoriping/KKuTu#456]
&lt;&lt; KKuTu Server:8496 >>
Master DB is ready.
Error on ws: Error: listen EADDRINUSE: address already in use 0.0.0.0:8080
DB is ready.
&lt;&lt; KKuTu Web >>
Game server #1 has an error: Error: unexpected server response (404)
Game server #1 closed: 1006
DB is ready.

라고 뜨는데, 클러스터링 문제인 건 확실한데 어떻게 해야 할지 모르겠습니다.

**Comment by ptrkr** [comment]
`8080`번 포트를 이미 다른 프로세스에서 사용하고 있기 때문에 발생하는 오류입니다. 해당 포트를 사용하는 프로세스를 중지한 후 다시 시도해 보세요.

**Comment by lorlol701** [comment]
8080포트에서 열린 다른 서버가 있는지 확인해보세요.
