### ISSUE TITLE
사전 정보 제공

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#457]
제가 다른 서버에 도움이 필요한데, 우리말샘 api까지 받았는데, 사전 정보 제공에 추가해야하거든요?
근데 사전 정보 제공: WordNet이라고만 뜨고, 밑에는 WordNet..(중략) All rights reserved. 이렇게 뜹니다.

                   사전 정보 제공:WordNet, 우리말샘
WordNet 3.0 Copyright 2019 by Princeton University.
Korean Copyright 2019 by 우리말샘.

이렇게 해야 하는데 어떻게 해야하나요?

**Comment by lshqqytiger** [comment]
`    "dictionarySupport": "사전 정보 제공:<a href='http://wordnet.princeton.edu' target='_blank'>WordNet</a>, <a href='https://opendict.korean.go.kr' target='_blank'>우리말샘</a><br><label style='color: #777777;'>WordNet 3.0 Copyright 2006 by Princeton University. All rights reserved.</label><br><label style='color: #777777;'>우리말샘 Copyright 2016 by 국립국어원. All rights reserved.</label>",`
