### ISSUE TITLE
쪼롤 도메인 강제변경?

### ISSUE THREAD

**Issue by plkmnb100** [JJoriping/KKuTu#458]
원래 저희 서버의 도메인은 modukkutu.kro.kr이었습니다.
그런데 갑자기 쪼롤에서 도메인을 다른 사람이 마음대로 바꾸어 버렸습니다.
기능에도 없는 것인데 어떻게 한 것일까요?
해킹당한 걸까요?

**Comment by lshqqytiger** [comment]
다른분이 모두끄투라는 이름으로 다시 등록하신걸수도..?

**Comment by mhnsoft** [comment]
> 다른분이 모두끄투라는 이름으로 다시 등록하신걸수도..?

아닙니다. 등록일이 1월 20일로 되어있습니다

**Comment by Preta-Crowz** [comment]
도메인 변경은 사이트 오너인 쪼리핑님만 가능한 것으로 알고있습니다. 답변 기다려보죠
