### ISSUE TITLE
쪼롤 등록할려는데 `주소와 암호를 입력해 주세요.`가 뜹니다

### ISSUE THREAD

**Issue by mhnsoft** [JJoriping/KKuTu#459]
![default](https://user-images.githubusercontent.com/18261800/52909233-bef3af80-32c8-11e9-9067-b4c4530b0a5c.PNG)
![default](https://user-images.githubusercontent.com/18261800/52909234-c2873680-32c8-11e9-8a59-6a439034bca2.PNG)
안녕하세요.저희 서버의 쪼롤에 등록된 주소가 알수없는 이유로 바뀌어서 쪼롤에 새로 등록할려고 하는데
ko_kr의 GPL 앞부분을 `모두와 함께하는 모두끄투!` 로 해서 그런지
`홈페이지 또는 게임 페이지의 저작권 관련 내용 표시가 조건에 맞지 않습니다.`가 떠서
원래대로 `글자로 놀자! 끄투 온라인` 으로 고치고 혹시 도메인이 예전에 등록한 http://modukkutu.kro.kr 
 로하면 안될 것 같아서 도메인도 바꿨습니다. 
그렇지만 계속 `주소와 암호를 입력해주세요.`가 뜨네요. 무엇이 문제일까요?

**Comment by plkmnb100** [comment]
참고로 저도 등록안됩니다.
컴퓨터, 환경의 문제가 아닌듯 합니다.
