### ISSUE TITLE
예전 배경음악 파일을 얻을 수 있을까요?

### ISSUE THREAD

**Issue by pkpai0926** [JJoriping/KKuTu#46]
2017년 1월 말(25~30일 사이)에 한시적으로 끄투 공식 서버의 대기실에서 사용되었던 통통 튀는 느낌의 BGM이 너무나도 마음에 들어서 그러는데 예전 배경음악 파일도 갖고 계신다면 그 BGM도 배포해주시면 좋겠습니다.

**Comment by JJoriping** [comment]
https://github.com/JJoriping/KKuTu/commit/7f0c55dbb37c4f5d0ddd21a69cb506d37bfeded8
업로드했습니다. 확인해 보세요.
