### ISSUE TITLE
T0~T10 노래가 끊기지 않고 계속 진행되게 할 수는 없나요?

### ISSUE THREAD

**Issue by Chunhak** [JJoriping/KKuTu#460]
2분짜리 노래로 했는데 단어 칠때마다 계속 다시 재생되네요...

**Comment by lshqqytiger** [comment]
당연히 계속 재생됩니다. T0은 15초, T1은 13초, T2는 12초 ... 이런 식으로 시간이 줄 때마다 노래가 바뀌니깐요.

노래가 중간에 바뀌지 않고 계속 재생되게 하는건 in_game_kkutu.js를 수정하셔야 합니다.
