### ISSUE TITLE
웹페이지 제목 변경법좀 알려주세요.

### ISSUE THREAD

**Issue by Chunhak** [JJoriping/KKuTu#461]
[스우끄투] 끝말잇기 하자! 스우끄투로 되는데
앞에 있는 [스우끄투]를 지울수는 없을까요

**Comment by lshqqytiger** [comment]
`Server\main.js`의 serverName: SETTINGS['server-name'] || process.env['KKT_SV_NAME'] 부분을 수정하시면 될 것 같습니다.

**Comment by Chunhak** [comment]
kkutu.pug의 block Subject를 바꾸면 되는군요
