### ISSUE TITLE
SSL 인증서 파일을 읽어오지 못하는 것 같습니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#462]
"IS_SECURED": true,
	"SSL_OPTIONS": {
		"PRIVKEY": "D:\\ssl\\domain.key",
		"CERT": "D:\\ssl\\private.key",
		"CA": "D:\\ssl\\ssl_chain.crt",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": true
	}
}

이렇게 다 입력해 줬는데

C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\slave.js:28 const options = Secure(); ^ ReferenceError: Secure is not defined at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\slave.js:28:18) at Module._compile (internal/modules/cjs/loader.js:688:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) at Module.load (internal/modules/cjs/loader.js:598:32) at tryModuleLoad (internal/modules/cjs/loader.js:537:12) at Function.Module._load (internal/modules/cjs/loader.js:529:3) at Module.require (internal/modules/cjs/loader.js:636:17) at require (internal/modules/cjs/helpers.js:20:18) at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\cluster.js:59:2) at Module._compile (internal/modules/cjs/loader.js:688:30)
[2019-02-19 12:30:05] Worker @1 17960 died

이런 식의 에러가 계속 반복되며 콘솔에 도배됩니다.

제가 보안 연결에 대해서는 잘 몰라서...도움이 필요합니다. 제가 뭘 빠트린게 있는 거 같은데..

**Comment by lshqqytiger** [comment]
아 그리고 Private키가 RSA PRIVATE KEY가 맞나요? 이상한걸 하고있는 건지..;

**Comment by kimhj050326** [comment]
slave.js 에서 변수 부분에 Secure 를 secure 로 바꿔주세요

**Comment by lshqqytiger** [comment]
소문자로 되어있어서 대문자로 했더니

C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31 options.key = File.readFileSync(Const.SSL_OPTIONS.PRIVKEY); ^ ReferenceError: File is not defined at module.exports (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31:23) at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\slave.js:28:18) at Module._compile (internal/modules/cjs/loader.js:688:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) at Module.load (internal/modules/cjs/loader.js:598:32) at tryModuleLoad (internal/modules/cjs/loader.js:537:12) at Function.Module._load (internal/modules/cjs/loader.js:529:3) at Module.require (internal/modules/cjs/loader.js:636:17) at require (internal/modules/cjs/helpers.js:20:18) at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\cluster.js:59:2)
[2019-02-19 17:22:28] Worker @1 9460 died

이런 오류가 계속 도배되네요

**Comment by kimhj050326** [comment]
흠 파일을 못읽어 오는것 같은데.. 저도 자세히는 모릅니다.

**Comment by lshqqytiger** [comment]
module.exports = () => {
    const options = {};
    if(Const.SSL_OPTIONS.isPFX == true) {
        options.pfx = File.readFileSync(Const.SSL_OPTIONS.PFX);
    } else {
        options.key = "D:\ssl\csr.key";
        options.cert = "D:\ssl\ssl_cert.crt";
        if(Const.SSL_OPTIONS.isCA == true) {
            options.ca = "D:\ssl\ssl_chain.crt";
        }
    }
    return options;
}

secure.js 자체의 내용을 바꿔버리니

_tls_common.js:113 c.context.setCert(cert); ^ Error: error:0906D06C:PEM routines:PEM_read_bio:no start line at Object.createSecureContext (_tls_common.js:113:17) at Server (_tls_wrap.js:868:27) at new Server (https.js:62:14) at Object.createServer (https.js:84:10) at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\slave.js:30:23) at Module._compile (internal/modules/cjs/loader.js:688:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) at Module.load (internal/modules/cjs/loader.js:598:32) at tryModuleLoad (internal/modules/cjs/loader.js:537:12) at Function.Module._load (internal/modules/cjs/loader.js:529:3)
[2019-02-19 23:36:51] Worker @1 8924 died

이런 오류를 뿜습니다. 왜이러는지 모르겠네요..;;

**Comment by minesna** [comment]
인증서가 잘못된거 같습니다

**Comment by lshqqytiger** [comment]
이번엔 이렇게 됩니다.

[2019-02-20 09:29:38] ERROR OCCURRED ON THE MASTER! :8080 [2019-2-20 09:29:38] ERROR: ReferenceError: File is not defined ReferenceError: File is not defined at module.exports (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31:23) at Object.MainDB.ready (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\master.js:278:20) at C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:166:7) at Object.onceWrapper (events.js:273:13) at Connection.emit (events.js:187:15) at Socket.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:133:12)
[2019-02-20 09:29:38] DB is ready.
[2019-02-20 09:29:38] OAuth Strategy naver loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy google loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy kakao loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy discord loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy twitch loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy github loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy line loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy instagram loaded successfully.
[2019-02-20 09:29:38] OAuth Strategy spotify loaded successfully.
[2019-02-20 09:29:38] DB is ready.
C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31 options.key = File.readFileSync(Const.SSL_OPTIONS.PRIVKEY); ^ ReferenceError: File is not defined at module.exports (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31:23) at Object.DB.ready (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\main.js:150:19) at C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:166:7) at Object.onceWrapper (events.js:273:13) at Connection.emit (events.js:187:15) at Socket.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:133:12)
Worker 14976 died

**Comment by lshqqytiger** [comment]
+ 사설 인증서로 해도

C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31 options.key = File.readFileSync(Const.SSL_OPTIONS.PRIVKEY); ^ ReferenceError: File is not defined at module.exports (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\sub\secure.js:31:23) at Object.DB.ready (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\main.js:150:19) at C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Web\db.js:87:30 at BoundPool.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:137:9) at C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\generic-pool\lib\generic-pool.js:347:9 at BoundPool.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg-pool\index.js:103:7) at Connection.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:166:7) at Object.onceWrapper (events.js:273:13) at Connection.emit (events.js:187:15) at Socket.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:133:12)

[중략 (로그인 불러오는 부분)]

 _tls_common.js:113 c.context.setCert(cert); ^ Error: error:0906D06C:PEM routines:PEM_read_bio:no start line at Object.createSecureContext (_tls_common.js:113:17) at Server (_tls_wrap.js:868:27) at new Server (https.js:62:14) at Object.createServer (https.js:84:10) at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\slave.js:39:23) at Module._compile (internal/modules/cjs/loader.js:688:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) at Module.load (internal/modules/cjs/loader.js:598:32) at tryModuleLoad (internal/modules/cjs/loader.js:537:12) at Function.Module._load (internal/modules/cjs/loader.js:529:3)

이 오류가 반복됩니다. 인증서 문제가 아닌 거 같습니다.

**Comment by Preta-Crowz** [comment]
해당 파일에서 File이 정의되지 않은 오류가 있습니다. secure.js를 다음과 같이 수정해주세요.
```js
const Const = require('../const')
const File = require('fs')

module.exports = () => {
    const options = {};
    if(Const.SSL_OPTIONS.isPFX == true) {
        options.pfx = File.readFileSync(Const.SSL_OPTIONS.PFX);
        options.passphrase = Const.SSL_OPTIONS.PFXPass;
    } else {
        options.key = File.readFileSync(Const.SSL_OPTIONS.PRIVKEY);
        options.cert = File.readFileSync(Const.SSL_OPTIONS.CERT);
        if(Const.SSL_OPTIONS.isCA == true) {
            options.ca = File.readFileSync(Const.SSL_OPTIONS.CA);
        }
    }
    return options;
}```

**Comment by lshqqytiger** [comment]
그렇게 했더니 이번엔 이런 오류를 뿜습니다.

_tls_common.js:113 c.context.setCert(cert); ^ Error: error:0906D06C:PEM routines:PEM_read_bio:no start line at Object.createSecureContext (_tls_common.js:113:17) at Server (_tls_wrap.js:868:27) at new Server (https.js:62:14) at Object.createServer (https.js:84:10) at Object.&lt;anonymous> (C:\Users\user\Desktop\Private\KKuTu-master\Server\lib\Game\slave.js:30:23) at Module._compile (internal/modules/cjs/loader.js:688:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10) at Module.load (internal/modules/cjs/loader.js:598:32) at tryModuleLoad (internal/modules/cjs/loader.js:537:12) at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by Preta-Crowz** [comment]
설정 파일을 다시 확인해보세요.
privkey가 private.key이고, CA는 비활성화하시면 될 듯합니다.

**Comment by lshqqytiger** [comment]
"IS_SECURED": true,
	"SSL_OPTIONS": {
		"PRIVKEY": "D:\\OpenSSL\\bin\\private.key",
		"CERT": "D:\\OpenSSL\\bin\\public.key",
		"CA": "",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": false

이렇게 했는데도 똑같은 오류가 나옵니다

**Comment by Preta-Crowz** [comment]
cert에 인증서 넣으세요.

**Comment by lshqqytiger** [comment]
오 되네요 감사합니다.

**Comment by lshqqytiger** [comment]
GetHTTPSForFree 기준

domain.key : PRIVKEY
ssl_chain.crt : CERT

CA는 false
