### ISSUE TITLE
서버 오류입니다

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#463]
2019-02-22 20:19:47] Master DB is ready.
[2019-02-22 20:19:47] &lt;&lt; KKuTu Web >>
[2019-02-22 20:19:47] &lt;&lt; KKuTu Server:8499 >>
[2019-02-22 20:19:47] &lt;&lt; KKuTu Server:8497 >>
[2019-02-22 20:19:47] Master DB is ready.
[2019-02-22 20:19:47] Master DB is ready.
[2019-02-22 20:19:48] Error on ws: Error: listen EACCES: permission denied undefined
[2019-02-22 20:19:48] Master DB is ready.
[2019-02-22 20:19:48] &lt;&lt; KKuTu Server:8501 >>
[2019-02-22 20:19:48] Master DB is ready.
[2019-02-22 20:19:48] &lt;&lt; KKuTu Server:NaN >>
[2019-02-22 20:19:48] Error on ws: Error: bind EACCES NaN

저 blind랑 perimission 오류가 계속뜹니다

**Comment by Preta-Crowz** [comment]
권한 문제로 보입니다. 관리자 계정에서 실행 중인지 확인해보세요. 혹은 포트가 잘못되었을 수도 있습니다.

**Comment by YTHappyPlus** [comment]
![image](https://user-images.githubusercontent.com/31878663/53279666-c64a0b80-3755-11e9-8ca5-5901d1d2deef.png)

**Comment by Preta-Crowz** [comment]
둘 중 하나인 것으로 보인다고 했습니다. 나머지 하나도 확인하세요.

**Comment by YTHappyPlus** [comment]
포트도 문제 없습니다

**Comment by Preta-Crowz** [comment]
관리자 권한으로 실행도 시도해보셨나요?

**Comment by YTHappyPlus** [comment]
run.bat 을요?

**Comment by Preta-Crowz** [comment]
네. 계정이 관리자 계정이어도 권한이 항상 관리자 권한인 것은 아닙니다.

**Comment by YTHappyPlus** [comment]
관리자 권한은 오류가 뜹니다

**Comment by Preta-Crowz** [comment]
관리자로 cmd를 켜고, cd로 위치 이동후 bat을 실행해보세요.

**Comment by YTHappyPlus** [comment]
![image](https://user-images.githubusercontent.com/31878663/53286600-6040a100-37b4-11e9-8801-3546c0ba7367.png)

**Comment by Preta-Crowz** [comment]
파일 말고 그 파일이 있는 폴더를 쳐야합니다. D드라이브 이동은 `D:`입니다.

**Comment by YTHappyPlus** [comment]
이동 했습니다

**Comment by Preta-Crowz** [comment]
이동해도 안되면 포트 사용 여부 등도 확인해야합니다.

**Comment by YTHappyPlus** [comment]
![image](https://user-images.githubusercontent.com/31878663/53286943-a5ff6880-37b8-11e9-9209-ccc51a08bfe2.png)
여기서 더 뭘 해야하나요?

**Comment by Preta-Crowz** [comment]
D 이동 후 cd로 디렉토리를 이동하세요.

**Comment by YTHappyPlus** [comment]
이렇게 했는데오 
![image](https://user-images.githubusercontent.com/31878663/53287008-97fe1780-37b9-11e9-9d5c-23cea2e3643f.png)
![image](https://user-images.githubusercontent.com/31878663/53287009-9c2a3500-37b9-11e9-8dee-940fba9deaf8.png)

ㅇ오류 나네요

**Comment by Preta-Crowz** [comment]
현재 각종 설정 자체가 잘못된 것으로 보입니다. 서버를 처음부터 다시 만들어보세요.

**Comment by YTHappyPlus** [comment]
음...근데 저 오류는 서버의 어떤문제가 생기죠?

**Comment by Preta-Crowz** [comment]
서버 접속이 안됩니다.

**Comment by YTHappyPlus** [comment]
한번 http://hpkktutu.kro.kr 접속해보실수 있나요 가능하면 로그인도요

**Comment by lshqqytiger** [comment]
접속 자체가 안됩니다. 연결할 수 없다 뜹니다.

**Comment by Preta-Crowz** [comment]
A레코드 다시 연결해보세요. 호스트 못찾고있습니다.

**Comment by YTHappyPlus** [comment]
http://hpkkutu.kro.kr/

**Comment by lshqqytiger** [comment]
이제 되네요
