### ISSUE TITLE
분명히 서버가 열려있는데 프리서버 목록에는 닫혀있다 뜹니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#465]
![123](https://user-images.githubusercontent.com/39524005/53293086-b04d5100-3810-11e9-8927-91d41cf09003.PNG)
분명히 http일때는 정상이었는데 https로 바꾼 뒤부터 서버가 열려있는데도 닫혀있다고 나오네요..당연히 https://bfk.playts.net 으로 접속하면 다 잘 됩니다.

**Comment by Preta-Crowz** [comment]
HSTS 설정을 해주세요.

**Comment by lshqqytiger** [comment]
이미 되어있는거 같습니다. http://bfk.playts.net 으로 들어가면 https://bfk.playts.net 으로 이동됩니다.

**Comment by Preta-Crowz** [comment]
쪼리핑님께 직접 문의해봐야 할 것 같습니다.

**Comment by lshqqytiger** [comment]
SSL 인증서 관련 문제였습니다. 해결 되었으니 이슈 닫습니다.
