### ISSUE TITLE
리눅스 데비안(라즈베리파이)에서 끄투서버 오픈관련해서 올려봅니다

### ISSUE THREAD

**Issue by Ryzen72700** [JJoriping/KKuTu#467]
현재 파이에서 끄투열려고 지금 한 5일정도 시도중인 사람입니다
필요한거(redis빼고) 받았고, db설정해서 server-setup의 확장자인 .bat을 .sh로 바꿔서 켜봤는데 npm install --lib ~~~ 뜨고 사라져서 다되었나보다 하고 ~/Server에서 run.bat을 sh로 바꾸고 켰는데 아래의 오류가뜹니다..
윈도우에서 하던걸 압축후 그대로 가져왔는데 그거때문일까요?

해결법 아는분 원격으로 해주시거나 답좀 달아주세요..;
(node:2524) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> kkutu-server@2.5.1 start /home/pi/Desktop/KKuTu-master/Server
> electron .

sh: 1: electron: not found

npm ERR! kkutu-server@2.5.1 start: `electron .`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the kkutu-server@2.5.1 start script.
npm ERR! This is most likely a problem with the kkutu-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get their info via:
npm ERR!     npm owner ls kkutu-server
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.79-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/KKuTu-master/Server
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/KKuTu-master/Server/npm-debug.log
npm ERR! not ok code 0

**Comment by kimhj050326** [comment]
README.md 에 리눅스 설치법 보고 하세요.

**Comment by Ryzen72700** [comment]
> README.md 에 리눅스 설치법 보고 하세요


pi@raspberrypi:~/Desktop/KKuTu-master $ sh server-setup.bat
Please wait... This may take several minutes.
npm install
npm install ./lib --prefix "./lib"
Completed.
server-setup.bat: 5: server-setup.bat: grunt: not found

이건 뭔뜻인가요..?

**Comment by Ryzen72700** [comment]
> README.md 에 리눅스 설치법 보고 하세요.

아 저거말고 이거요
-------------------

(node:1227) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> kkutu-server@2.5.1 start /home/pi/Desktop/KKuTu-master/Server
> electron .

sh: 1: electron: not found

npm ERR! kkutu-server@2.5.1 start: `electron .`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the kkutu-server@2.5.1 start script.
npm ERR! This is most likely a problem with the kkutu-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get their info via:
npm ERR!     npm owner ls kkutu-server
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.98-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /home/pi/Desktop/KKuTu-master/Server
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/Desktop/KKuTu-master/Server/npm-debug.log
npm ERR! not ok code 0

**Comment by Preta-Crowz** [comment]
`npm WARN This failure might be due to the use of legacy binary "node"`
node.js의 버전을 올려보세요. 구버전 호환성 문제로 추측됩니다.

상세 로그는 다음 위치에 저장되어있습니다.
`/home/pi/Desktop/KKuTu-master/Server/npm-debug.log`

**Comment by minesna** [comment]
server-setup이 정상적으로 되지 않은것 같습니다
Flush와 setup을 파일 수정을 중단하고 끄투파일을 사용하는 프로그램은 꺼주세요

**Comment by minesna** [comment]
그리고 배치파일이리 호환이 안되는 부분때문에 server-setup이 제대로 안될 수 도 있습니다

**Comment by Alex4386** [comment]
1. Raspberry Pi 1 이라면 armv6 architecture의 electron 미지원으로 불가능합니다.
2. + npm-debug.log 올려주세요.

**Comment by Ryzen72700** [comment]
> 1. Raspberry Pi 1 이라면 armv6 architecture의 electron 미지원으로 불가능합니다.
> 2. + npm-debug.log 올려주세요.

3 b+에요
(하도접은지 오래되서 파일을 지워버렸네요)
(일단 마감합니다)

**Comment by dalbodeule** [comment]
제가 이전에 서버가 여의치 않았을 때, 라즈베리파이 위에서 실행시켰던 적이 있긴 했습니다. 만약 끄투를 리눅스 환경에서 실행시킬 경우, 콘솔에서 직접 node.js 프로세스를 실행시켜 주어야 합니다.
