### ISSUE TITLE
표국대

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#468]
표준국어대사전 데이터베이스 넣는법 알려주세요

**Comment by YTHappyPlus** [comment]
이슈 #47 을 참고하세요

**Comment by swoo5571** [comment]
> 이슈 #47 을 참고하세요

잘 모르겠네요..초보라..

**Comment by Preta-Crowz** [comment]
크게 세 가지 정도가 있습니다.
1. 수동으로 모든 단어를 입력한다.
2. 표국대 DB를 수정하여 바로 SQL에 입력시킨다.
3. 표국대 DB를 수정하여 json으로 변환 후, 볕뉘님의 레포에서 파일을 받아 단어를 등록시킨다.

**Comment by kimhj050326** [comment]
@swoo5571 표준국어대사전 허가는 받으셨나요?
표준국어대사전은 한국복제전송저작권협회 에서 허가를 받아야합니다.

**Comment by YTHappyPlus** [comment]
허가는 어떻게 받죠 하하

**Comment by swoo5571** [comment]
> @swoo5571 표준국어대사전 허가는 받으셨나요?
> 표준국어대사전은 한국복제전송저작권협회 에서 허가를 받아야합니다.

네. 아마 서버에 들어가보면, 국립국어원 Copyright 되어있을겁니다.
