### ISSUE TITLE
데이터 베이스에 단어 추가하는 방법

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#47]
1. 만약, 플레이어들에게 단어 건의를 받았을 경우, 데이터 베이스에 단어를 추가하는 방법을 알고 싶습니다.

2. 만약, 국립국어원에서 허가를 받고 국어표준어대사전에서 데이터 베이스를 받으면, 어떤식으로 등록하여야 하나요?

**Comment by JJoriping** [comment]
주제가 다른 질문은 다른 분들이 찾아 보기가 쉽도록 가급적 별도의 이슈로 등록하는 것을 권합니다.

1. 관리자 페이지(URL `/gwalli`)를 활용하세요.
2. 국립국어원에서 제공하는 데이터베이스와 끄투 내부에서 사용하는 데이터베이스의 자료 구조가 다르기 때문에 이에 대한 마이그레이션 작업이 별도로 필요합니다. 이 과정에서 국립국어원 데이터베이스 파일을 파싱해야 할 것으로 예상됩니다.
