### ISSUE TITLE
피어슨같은 한방단어를 한방단어가 아니게 설정할수 있나요?

### ISSUE THREAD

**Issue by choroogyee** [JJoriping/KKuTu#471]
단어부 GM에서 슨자역 슨도메등등을 추가했는데 피어슨이 한방단어로 나옵니다. 이를 한방단어가 아니게 설정할수 있나요?

**Comment by Preta-Crowz** [comment]
사전에서 해당 단어가 정상적으로 검색되는지 확인하고, 서버도 한 번 다시 켜주세요. 아마 시스템상 한방단어를 캐싱하는 것으로 알고있습니다.

**Comment by choroogyee** [comment]
확인까지 다 했는데 슨이 한방단어로 나오네요 팀뷰어로 도움 받을수 있을까요? 디스코드 아이디만 알려주시면 DM 드리겠습니다

**Comment by choroogyee** [comment]
한방단어 문제 해결하였습니다 이슈 닫겠습니다
