### ISSUE TITLE
특수규칙을 적용 했는데 이리듐같은게 한방으로 되지 않습니다

### ISSUE THREAD

**Issue by choroogyee** [JJoriping/KKuTu#472]
언노운워드규칙을 추가했는데 이리듐이 한방단어로 나오지 않네요 왜그런거죠?

**Comment by andjsrk** [comment]
사전에 있는 단어를 제외한 모든 단어를 허용하기 때문에 한방단어로 나오지 않습니다.

**Comment by lshqqytiger** [comment]
당연히 한방처리 안됩니다. 듐듐듐듐듐듐듐 같은 단어 (사전에 없는 단어) 로 받아치면 되니깐요

**Comment by choroogyee** [comment]
kkutu.js에서 메너에 오타가있었습니다 해결하여 이슈 닫습니다
