### ISSUE TITLE
SSL인증서를 발급받았는데 적용법을 모르겠습니다

### ISSUE THREAD

**Issue by choroogyee** [JJoriping/KKuTu#473]
SSL 인증서를 발급 받았는데 적용법을 모르겠습니다 알려주시면 감사하겠습니다

**Comment by lshqqytiger** [comment]
Wiki의 SSL 문서를 확인해주세요.

**Comment by lshqqytiger** [comment]
그리고 secure 변수 관련 오류, secure.js에 File이 정의되지 않은 문제가 있으니 제 이슈를 확인해주세요.

**Comment by choroogyee** [comment]
감사합니다 적용 완료하였습니다
