### ISSUE TITLE
유튜브 데이터 api로 로그인 기능 추가

### ISSUE THREAD

**Issue by YTHappyPlus** [JJoriping/KKuTu#474]
구글+api가 3월7일에 지원이 안된다 하길레 구글 api 콘솔에서 유튜브 데이타 api를 받았습니다.
그후 passport 설치후 auth_youtube 를 만들었습니다
그후 서버를 구동했는데 Oauth Stragey Youtube Loaded 가 나왔습니다
그래서 로그인 사이트에서 유튜브 로그인 을 했더니 스코프 오류가 납니다. 유튜브 계정로그인은 어떤 스코프를 써야하나요?
일단 작성한 파일을 여기에 작성하겠습니다.
const config = require('../../sub/auth.json');

module.exports.config = {
    strategy: require('passport-youtube').Strategy,
    color: '#FFFFFF',
    fontColor: '#000000',
    vendor: 'youtube',
    displayName: 'withYoutube'
}

module.exports.strategyConfig = {
    clientID: config.youtube.clientID, // 보안을 위해서입니다.
    clientSecret: config.youtube.clientSecret, // 이 방법을 사용하는 것을
    callbackURL: config.youtube.callbackURL, // 적극 권장합니다.
    passReqToCallback: true,
    scope: ["chanel", "email"]
}

module.exports.strategy = (process, MainDB, Ajae) => {
    return (req, accessToken, refreshToken, profile, done) => {
        const $p = {};

        $p.authType = "youtube";
        $p.id = profile.id;
        $p.name = (profile.name.familyName != '' ? profile.name.familyName+' ' : '')+profile.name.givenName;
        $p.title = profile.nickname;
        $p.image = profile.photos[0].value;

        process(req, accessToken, MainDB, $p, done);
    }
}

**Comment by houlday** [comment]
유튜브는 구글과 같아 안하셔도 되는데요..?

**Comment by godmoonl** [comment]
.

> 유튜브는 구글과 같아 안하셔도 되는데요..?

? 무슨 말씀인지 모르겠네요

**Comment by houlday** [comment]
? 무슨 말씀인지 모르겠네요
그니까 구글 로그인 자체가 유튜브랑 똑같다는 말입니다
