### ISSUE TITLE
login 오류

### ISSUE THREAD

**Issue by lej10** [JJoriping/KKuTu#479]
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (C:\Users\lej10\OneDrive\바탕 화면\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (C:\Users\lej10\OneDrive\바탕 화면\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:48:18) at glob.then (C:\Users\lej10\OneDrive\바탕 화면\KKuTu-master\Server\lib\Web\routes\login.js:75:26)

위와같은 오류가 나네요
안쓰는 auth에 뒤에 .DISABLE도 붙였는데
오류가 나네요. 어떻게 해야할까요?

**Comment by lshqqytiger** [comment]
clientID 값을 불러오지 못하는 것 같습니다. auth.json에 clientID 값을 제대로 입력했는지 또는 auth_사용한로그인타입.js 파일이 정상인지 확인해 주세요.

**Comment by lej10** [comment]
해결완료 됬습니다.
