### ISSUE TITLE
끄투 명령어

### ISSUE THREAD

**Issue by lej10** [JJoriping/KKuTu#480]
끄투에서 채팅에 치는 명령어 모음 좀 달아주실 수 있나요? 아무리 찾아봐도 명령어 모음은 없네요.
# 명령어 등...

**Comment by andjsrk** [comment]
/Server/lib/Game/master.js의 80번째 줄부터 살펴봐주세요.

**Comment by Preta-Crowz** [comment]
일반 사용자의 명령어는 인게임에서 충분히 확인 가능합니다. 어드민 명령어의 경우 파일에서 `#tell` 등을 검색하여 확인 가능합니다.
