### ISSUE TITLE
ctrl+v

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#481]
옛한글 단어 추가했는데 입력하기 위해서 ctrl+c ctrl+v가 필요합니다. 근데, 막혀있더라고요.
이거 풀수 있는 방법 없나요? 필요합니다.
라운드 플레이 도중에, 복붙 기능이 막혀있어서 이거 풀 수 있는지 물어봅니다..

**Comment by kimhj050326** [comment]
@swoo5571 여기는 기능 구현방법을 묻는곳이 아닙니다.
이곳은 끄투 서버구동중 오류나 문제가 발생하였을 경우 도움받는 곳입니다.
직접 본인이 구현하시길 바랍니다.

**Comment by Preta-Crowz** [comment]
복붙 해제보다는 날개셋 한글 입력기 등의 추가 입력기를 사용하는 것을 권장합니다.
