### ISSUE TITLE
로그인하는데 자꾸 풀립니다

### ISSUE THREAD

**Issue by KAKAO24** [JJoriping/KKuTu#482]
안녕하세요 이번에 구름끄투를 만들게 된 총관리자 KAKAO 입니다 로그인 구현을 하고 로그인 하고 들어갈려니까 풀어져서 몇번을 시도 해야되네요..

[녹화_2019_04_06_13_05_31_875.zip](https://github.com/JJoriping/KKuTu/files/3050133/_2019_04_06_13_05_31_875.zip)
이 zip를 보시면 이렇습니다..

**Comment by Preta-Crowz** [comment]
끄투 자체를 80 / 443에 할당시키지 않고, 리버스 프록시 등을 이용할 경우 프록시의 세션 설정을 점검해보시기 바랍니다. 프로젝트 끄투에서는 리버스 프록시 세션 문제로 해당 현상이 발생한 바 있습니다.

**Comment by KAKAO24** [comment]
제가 좀 이해를 못하는데 쉽게 설명해주실 수 있나요

**Comment by KAKAO24** [comment]
해결 됐습니다. 감사합니다 
- 쪼리핑바보

**Comment by houlday** [comment]
흠
