### ISSUE TITLE
SNS 로그인 설정법

### ISSUE THREAD

**Issue by crafthome** [JJoriping/KKuTu#484]
네이버 개발자 사이트에서 클라이언트 ID와 시크릿 키를 얻어 Server\lib\sub\auth.json에 naver 부분에 클라이언트 ID와 시크릿키를 작성한뒤 재부팅을 했습니다. /login 로 들어가보니 아무것도 없었습니다. 네이버 로그인 파일 확장자를 disabled 으로 설정도 하지 않았습니다. 어떻게 /login 에 네이버 로그인을 추가할수 잇을까요? (지금 현재 네아로 개발중 상태로 되어있습니다.)

**Comment by Preta-Crowz** [comment]
네이버 외에 사용하지 않는 로그인 파일을 비활성화 했는지 확인해주세요.

**Comment by crafthome** [comment]
예 네이버 외에 사용하지 않는 로그인 파일을 비활성화 했습니다.

**Comment by houlday** [comment]
passport 설치하셨나요? ko-kr.json 인가 거기 안건드리셔도 되지만(하지만 L#login/로그인이름) 이렇게 나옵니다 passport 안설치 되어있으시다면
cd C:\끄투 서버 경로로 들어가셔서 
npm i passport-naver
이렇게 하시면 됩니다 디스코드는
npm i passport-discord
구요
아참 네이버는 검증인가 검수인가 받아야 유저들이 로그인 가능합니다.

**Comment by lshqqytiger** [comment]
passport는 기본적으로 서버 구축시 자동으로 설치됩니다. (구축 후 추가한 것은 예외)

**Comment by houlday** [comment]
예
