### ISSUE TITLE
서버 오류

### ISSUE THREAD

**Issue by lubudack** [JJoriping/KKuTu#485]
로그인 하면 불러오는 중..앞으로 1에서 멈춥니다
ERROR OCCURRED ON THE MASTER! :8080 [2019-4-24 14:46:44] ERROR: TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined at C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\Game\master.js:344:51 at exports.Tail.go (C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\sub\lizard.js:43:16) at C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\Game\kkutu.js:453:11 at callback (C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\sub\collection.js:316:13) at Result.preCB (C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\node_modules\pg\lib\query.js:144:10) at Connection.&lt;anonymous> (C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:189:13) at Socket.&lt;anonymous> (C:\Users\장승수.DESKTOP-G1CV311\Downloads\KKuTu-master\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:189:13)

**Comment by Preta-Crowz** [comment]
무언가 설정이 잘못된 것 같습니다. json 외 다른 파일을 수정하셨다면 롤백을 해보시고, 그래도 안된다면 서버를 다시 구축해보세요.

**Comment by lubudack** [comment]
(아직 해결은 안됬지만)감사합니다

**Comment by lubudack** [comment]
다시 서버 구축 했지만..

**Comment by lshqqytiger** [comment]
파일 새로받아서 해보세요
