### ISSUE TITLE
옵저버 수 늘리기

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#486]
8명 꽉찼을 때 추가로 들어갈 수 있는 옵저버의 수를 늘리고 싶습니다.

전에 분명 어디서 봤던 것 같은데 기억이 안나는군요.

**Comment by andjsrk** [comment]
const.js의 29번째 줄에 있습니다.

**Comment by lshqqytiger** [comment]
이걸 못찾다니; 감사합니다.
