### ISSUE TITLE
DB 삭제 및 재구축

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#487]
when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2019-04-27 20:44:29] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다 [2019-04-27 20:54:29] Error when querying: DELETE FROM session

이게 뜨는데, 분명 이슈에서는 main db를 삭제하고 다시 하라는데, main db를 어디서 삭제해야하나요?

**Comment by andjsrk** [comment]
pgAdmin에서 main 데이터베이스를 삭제해주시고 다시 구축해주세요.
