### ISSUE TITLE
쪼롤 등록 문제입니다. 해결해주세요.

### ISSUE THREAD

**Issue by bucket12345** [JJoriping/KKuTu#488]
![issue](https://user-images.githubusercontent.com/47386037/56856953-46ccf880-69a1-11e9-8cfb-c70cbbd56de0.PNG)
여기서 자꾸 막힙니다. 분명히, 서버주소랑 암호를 입력했는데... 이거 해결법 없을까요??

**Comment by godmoonl** [comment]
쪼롤 자체에서 그 서버를 막은거 같네요.

**Comment by lshqqytiger** [comment]
보통 그런 문제는 쪼롤에서 서버 등록을 차단할때 발생하는 경우가 있습니다.

쪼리핑님께 직접 문의하셔야 정확한 답을 얻으실 수 있습니다.
(디스코드)

**Comment by hands8142** [comment]
쪼리핑님 디스코드가 뭐에요

**Comment by JJoriping** [comment]
안녕하세요. 입력하고 제출하기 전 F12 키로 개발자 도구를 연 후 제출 단추를 클릭해 보세요. 같은 화면이 다시 나온다면 개발자 도구에서 다음과 같이 어떻게 입력이 들어갔는지 확인해 보세요.
![제목 없음](https://user-images.githubusercontent.com/12369657/62349928-1a92bc00-b53c-11e9-9541-99f197ca33dd.png)
