### ISSUE TITLE
SSL 인증서를 적용하고자 합니다.

### ISSUE THREAD

**Issue by pkpai0926** [JJoriping/KKuTu#49]
끄투의 웹 서버에 SSL인증서를 적용하여 https 연결을 하게끔 만들고 싶은데 어떤 파일을 고치면 되나요?

**Comment by JJoriping** [comment]
이슈 #21 을 참고해 주세요.

**Comment by pkpai0926** [comment]
감사합니다.

**Comment by soshimee** [comment]
똑같은 문제가 있는데 인증서 파일을 찾는 위치가 어디인지 모르겠습니다.

**Comment by lshqqytiger** [comment]
global.json의 SSL_OPTIONS 말하시는거라면 절대경로입니다.

**Comment by Moremi1** [comment]
![스크린샷 2024-07-17 170012](https://github.com/user-attachments/assets/4bec1f3d-4e6c-44ce-9427-d2db932f4b41)
다음과 같은 (db.json,cluster.json,main.json)같은 .json이 안됩니다

**Comment by lshqqytiger** [comment]
[README 공통 문단](https://github.com/JJoriping/KKuTu?tab=readme-ov-file#%EA%B3%B5%ED%86%B5)의 두 번째 항목 확인하세요.
