### ISSUE TITLE
이거 해결 하는법 알려주세요

### ISSUE THREAD

**Issue by KAKAO24** [JJoriping/KKuTu#491]
![캡처](https://user-images.githubusercontent.com/49306402/57506110-c65dae80-7335-11e9-9970-586bf2c102c9.PNG)

그리고 개속 닫임 뜨다가 열림 뜨다가 닫임

**Comment by lshqqytiger** [comment]
쪼롤에서는 global_notice.html 파일의 모든 내용을 가져옵니다. 따라서 global_notice.html 파일에는 공지할 내용만 담겨있어야 합니다.

**Comment by andjsrk** [comment]
global_notice.html의 내용은 **없었습니다.**
