### ISSUE TITLE
db에 뜻 추가

### ISSUE THREAD

**Issue by foxof4545** [JJoriping/KKuTu#495]
국립국어원에 허락을 받고 뜻추가할려고 하는데요:
![2222](https://user-images.githubusercontent.com/50654462/57756496-546ad800-772e-11e9-96cf-e847c390dad5.PNG)
여기다가 어떻게 추가해야하나요?

**Comment by foxof4545** [comment]
참고로, 이미 허락을 받은 상태입니다.

**Comment by lshqqytiger** [comment]
...거기에 하시면 안되고 관리자 페이지에 'DB에 단어 추가하기' 탭에 주제 코드를 기입한 뒤 단어 리스트를 넣으시면 됩니다. (당연히 SQL 비밀번호와 테이블 (ko / en) 을 먼저 기입하셔야 합니다.)

**Comment by lshqqytiger** [comment]
![133541](https://user-images.githubusercontent.com/39524005/57756802-fdb1ce00-772e-11e9-82f5-4e33185b37a9.PNG)
![512351](https://user-images.githubusercontent.com/39524005/57756837-0dc9ad80-772f-11e9-9d30-e91978c3641a.PNG)

**Comment by andjsrk** [comment]
https://github.com/JJoriping/KKuTu/issues/468 참고해주세요.
**참고로 sql 파일에 직접 추가하는 게 아닙니다.**

**Comment by foxof4545** [comment]
> #468 참고해주세요.
> **참고로 sql 파일에 직접 추가하는 게 아닙니다.**

초보라서 죄송합니다.
혹시 DB를 어떻게 적용시켜야하는지 모르겠는데, 디스코드 Wrong#6243으로 방법 알려주실수 있으세요?
