### ISSUE TITLE
쪼롤에 서버 등록할려고 하는데요

### ISSUE THREAD

**Issue by TYlemon** [JJoriping/KKuTu#496]
서버의 소유권을 확인하기 위해, 다음 주소로 접근했을 때 결과가 입력한 서버 주소와 같도록 처리해 주세요.
라고 쓰여있는데 어떻게 해야되나요?

**Comment by lshqqytiger** [comment]
Server\lib\Web\public 폴더 안에 kkutu-코드.html 파일을 만드시고 그 안에 입력한 서버 주소를 써넣으시면 됩니다.

**Comment by TYlemon** [comment]
그 안에 입력한 서버 주소를 써넣어야하는데 주소를 입력해야 되나요?

**Comment by lshqqytiger** [comment]
그게 없으면 단어 데이터 베이스 같은 게임 정보들을 어디에 저장할까요..
