### ISSUE TITLE
끄투 DB에서 kkuto_ko db사용 관련 질문드립니다.

### ISSUE THREAD

**Issue by IdiotGrape** [JJoriping/KKuTu#498]
끄투 DB중 kkutu_ko의 db만 사용하여 단어사전DB를 제작후 개인적인 끝말잇기 프로그램을 만들예정입니다만 GPL라이선스가 있으셔서 질문드립니다. 이 DB만 따로 사용하여 상업적인 이득을 취할수 있는지 또 이 DB만을 이용했을경우 따로 명시해야하는 부분이있는지 알려주시면 감사하겠습니다.

**Comment by JJoriping** [comment]
안녕하세요. 해당 스크립트가 포함된 프로그램을 직접 사용자에게 배포하는 형태가 아니라면(오프라인/P2P 방식 끝말잇기 등) GPL 라이선스의 영향을 받지 않으니 참고해 주세요.
