### ISSUE TITLE
send 함수 관련 질문

### ISSUE THREAD

**Issue by bokmook** [JJoriping/KKuTu#499]
in_game_kkutu.min.js의 코드를 보다가
send 함수를 알게 되었습니다.

그래서 send 함수를 통해 웹 소켓과 정보를 주고 받는 부분을 추가적으로 구현할 예정입니다만,
send 함수를 구현하게 하는 코드를 못 찾겠습니다.

아무리 찾아봐도 실력이 딸리는 건지... 도저히 못 찾겠더군요.

send 함수에서 if 문을 따로 추가해서 in_game_kkutu.min.js (게임 페이지)까지 전달하는 건데,

디스코드의 **{사용자}님이 입력 중입니다...** 처럼 작동되게 할 겁니다. ( html 부분과 js 코드는 이미 구현 되어 있습니다. )

send를 통하여 웹 소켓과 정보를 전달해서 사용자가 메시지를 입력 중임을 모든 유저가 알 수 있게할 건데...

**특히나, 끄투의 작동 방식 자체를 모르니 도저히 구현할 수가 없습니다...**

가능하면 보통은 저 혼자 찾아보고 하는데, 이번만은 도저히 안 될 것 같아 요청하게 됐습니다.

도와주시면 감사하겠습니다.

+ (끄투 관련 개발 커뮤니티도 없어 찾는데 더욱 어렵기만 합니다...)

**Comment by bokmook** [comment]
-아니 내가 올린 거라고-

**Comment by minesna** [comment]
어떻게 구현하는지 알려드리기는 힘들지만
현재 끄투는 채팅을 보낸다면 패킷이 전달됩니다
그래서 채팅을 입력시에는 서버도 모를것 같습니다

**Comment by bokmook** [comment]
채팅을 보내는 것이 아닌, 한 유저가 채팅을 입력 중일 때 **{사용자}님이 입력 중입니다...** 같은 내용이 모든 유저에게 Html로 전달될 수 있도록 하는 겁니다.
( 이미 **{사용자}님이 입력 중입니다...** 라는 내용을 보이게 하는 부분은 구현 됐으나, 모든 사용자에게 보이도록 하는 건 구현하지 못해서 말씀 드리게 된 겁니다. )

**Comment by bokmook** [comment]
모든 사용자에게 보이도록 하려면 웹소켓과 통신해서 신호를 받을 때, **{사용자}님이 입력 중입니다...** 같은 내용의 Html을 전달하게 하는 거죠.

**Comment by bokmook** [comment]
끄투에서 변수나 함수가 따로 있더라도,
사용법을 모르니 힘들기만 하네요... 

노가다 파도 도저히 안 됩니다.

**Comment by minesna** [comment]
채팅을 칠때도 통신을 하게 구현하셨다면
사용자에게 전달하는것은 [https://github.com/JJoriping/KKuTu/blob/27ee1ff9066e50798070cddf10996df418a28f6e/Server/lib/Game/kkutu.js#L151](url)
을 참고하여 구현시 더욱 수월할꺼 같습니다

~~어디부터 어디까지 뇌피셜일까~~

**Comment by bokmook** [comment]
DIC이라는 변수값을 어디서 전달받고 있는 거죠?

**Comment by minesna** [comment]
`master.js` 에서 `kkutu.js`를 불러오는걸 알수 있는데
`master.js` 에 DIC 의 객체가 비어있는것을 확인할 수 있습니다

~(뇌피셜이니 참고만 하시라우)~~

**Comment by bokmook** [comment]
흠... 일단 알겠습니다.
**또한, 참고 사항이라도 알려주셔서 감사합니다.**

**_우선 이슈를 닫아두고, 추후에 다른 문제 발생 시
새로 이슈를 열겠습니다._**
