### ISSUE TITLE
관리페이지에 대하여 문의드립니다.

### ISSUE THREAD

**Issue by Ganggroid** [JJoriping/KKuTu#5]
관리페이지에 대하여 문의드립니다.
관리페이지에서 상점 목록을 수정할때, 항목을 삭제하려면 어떻게 해야하나요

**Comment by JJoriping** [comment]
웹 클라이언트에서 삭제할 방법은 없습니다. pgAdmin 등의 GUI 툴을 이용하거나 `./Server/lib/Web/db.js` 모듈을 적절히 활용하여 `DB.kkutu_shop.remove(...).on(...)` 및 `DB.kkutu_shop_desc.remove(...).on(...)`과 같이 서버 소스 코드를 수정하여야 합니다.
