### ISSUE TITLE
끄투를 모바일로 제작하려고 합니다만,

### ISSUE THREAD

**Issue by gkfyddl2662** [JJoriping/KKuTu#50]
db.sql, 시/청각 리소스 및 데이터 (모드, 결과 계수, 스코어 계수등등)

만을 사용하고, 그 외에는 직접 개발해도 GPL 라이센스를 적용하여 서버 및 클라이언트 소스를 모두 공개해야하나요?

**Comment by JJoriping** [comment]
안녕하세요. `./README.md`에 명시된 대로 시청각 자료는 CC BY, 파일 `./db.sql` 및 게임 모드에 대한 구현 등은 SQL이나 JavaScript로 작성된 소스 코드이므로 GPL이 적용됩니다.

**Comment by gkfyddl2662** [comment]
모드에서 계산되는 수 및 문자열등과 같은 데이터만 사용하고, 구현은 다른 언어로 직접 개발하려합니다.

또한 SQL에 작성되어있는 단어 데이터만 가져가 써도 GPL이 적용되나요?

**Comment by JJoriping** [comment]
원칙적으로 소스 코드로부터 데이터를 가져와 사용할 때, 그렇게 제작된 모듈이 프로그램 실행에 필요한 경우 해당 프로그램에 GPL이 적용되어야 합니다. GPL이 적용되지 않게 하기 위해서는 끄투의 어떤 소스 코드도 인용했다고 판단되지 않도록 독자적인 프로그램을 제작하셔야 합니다.
