### ISSUE TITLE
서버 접속 문제(KT Wifi Home 공유기 사이트로 다이렉트 됨.)

### ISSUE THREAD

**Issue by foxof4545** [JJoriping/KKuTu#507]
![20190531_224324](https://user-images.githubusercontent.com/50654462/58709654-9a45c280-83f5-11e9-8035-4569b6865e7c.png)
컴퓨터 아이피로 IP연결 까지 완료했는데 서버 킨 순간 저런 화면만 뜨고 넘어가지 않습니다.
이거 어떻게 해야하나요?

**Comment by foxof4545** [comment]
참고로 127.0.0.1만 접속이되고 도메인으로는 저 화면만 계속 뜹니다

**Comment by lshqqytiger** [comment]
도메인에 연결된 IP가 잘못된 것 같습니다.

**Comment by foxof4545** [comment]
> 도메인에 연결된 IP가 잘못된 것 같습니다.

IP주소 분명히 잘 입력되었습니다. 디스코드 Wrong#6243으로 연락주세요

**Comment by 5tarlight** [comment]
@foxof4545 외부ip접속시 공유기 관리 페이지로 이동한다는것은 포트포워딩 설정이 되지 않았다는것을 의미합니다.
그 설정페이지로 가서 id는 바꾸지 않으셨다면 `ktuser`비밀번호는 `homehub` 일 겁니다.
로그인이 됬다면 왼쪽 메뉴바에서 `장치 설정`으로 가서 뜨는 메뉴중에`트래픽 관리`로 들어갑니다.
그러면 포트포워딩 설정이 보일텐데 외부 포트에 80 내부 ip주소는 터미널에 `ipconfig`를 입력해서 나오는 값을 넣고 내부 포트도 80으로 넣으시면 됩니다. 다른건 굳이 안넣어도 되니까 위의 3개만 넣으면 됩니다. 그리고 `추가`버튼을 누르면 포트포워딩 설정이 하나 추가되는데 이걸 8080 포트와 8496 포트 2개 모두 해주셔야 합니다.

**Comment by jwkim101201** [comment]
아마 kt가 8899 포트를 막았거나 아니면 포트포워딩을 안하신 것 같습니다
