### ISSUE TITLE
구글 소셜 로그인이 되지 않습니다 (CallbackURL 관련 문제인 것 같습니다)

### ISSUE THREAD

**Issue by TyphoonDANAS** [JJoriping/KKuTu#508]
구글로 로그인하려고 하면
로그인 화면까지는 잘 가졌다가
Cannot GET /auth/google/callback
이 뜨면서 로그인이 되지 않습니다.
어떻게 해결하면 좋을까요...?

**Comment by houlday** [comment]
저도 아직 잘 모르지만 구글에 http://가림.가림/auth/google/callback 으로 하는걸로 알고 있습니다

**Comment by houlday** [comment]
저도 아직 잘 모르지만 구글에 http://가림.가림/auth/google/callback 으로 하는걸로 알고 있습니다

**Comment by TyphoonDANAS** [comment]
@houlday 그렇게 했지만 위와 같은 오류가 뜹니다.

**Comment by lshqqytiger** [comment]
/login/google/callback 으로 연결되어야 정상입니다.

**Comment by TyphoonDANAS** [comment]
@lshqqytiger InternalOAuthError: failed to fetch user profile
    at C:\Users\user\Downloads\KKuTu-master\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\user\Downloads\KKuTu-master\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\user\Downloads\KKuTu-master\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
위와 같은 오류가 뜹니다.

**Comment by lshqqytiger** [comment]
auth_google.js 파일의 scope 부분이 잘못되었습니다.

**Comment by houlday** [comment]
https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/auth/auth_google.js
이 부분을 복붙하세요

**Comment by houlday** [comment]
<a href="https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/auth/auth_google.js">구글 로그인</a>
이 부분을 복붙하세요

**Comment by houlday** [comment]
###(참고 : 도메인이 있어야 합니다 도메인 등록은 하셨겠죠?)

**Comment by TyphoonDANAS** [comment]
@lshqqytiger 무엇이 잘못되었는지 잘 모르겠습니다...

**Comment by lshqqytiger** [comment]
172.30.1.254 (KT 공유기 설정) 으로 리다이렉트 설정이 되어 있습니다. 네이버에 내아이피 치셔서 나오는 IP로 리다이렉트 시키셔야 합니다.

**Comment by houlday** [comment]
<a href="http://ipipip.kr">이 부분도 됩니다</a>

**Comment by TyphoonDANAS** [comment]
@houlday 여기서 어느 부분을 수정하면 되는 건가요?
https://cafe.naver.com/ArticleWrite.nhn?clubid=29049311&menuid=&boardtype=L&m=write#

**Comment by houlday** [comment]
const config = require('../../sub/auth.json');

module.exports.config = {
    strategy: require('passport-google-oauth2').Strategy,
    color: '#FFFFFF',
    fontColor: '#000000',
    vendor: 'google',
    displayName: 'withGoogle'
}

module.exports.strategyConfig = {
    clientID: config.google.clientID, // 보안을 위해서입니다.
    clientSecret: config.google.clientSecret, // 이 방법을 사용하는 것을
    callbackURL: config.google.callbackURL, // 적극 권장합니다.
    passReqToCallback: true,
    scope: ['profile', 'email', 'https://www.googleapis.com/auth/plus.login']
}

module.exports.strategy = (process, MainDB, Ajae) => {
    return (req, accessToken, refreshToken, profile, done) => {
        const $p = {};

        $p.authType = "google";
        $p.id = profile.id;
        $p.name = (profile.name.familyName != '' ? profile.name.familyName+' ' : '')+profile.name.givenName;
        $p.title = profile.nickname;
        $p.image = profile.photos[0].value;

        process(req, accessToken, MainDB, $p, done);
    }
}

**Comment by houlday** [comment]
전 이렇게 되어있습니다만

**Comment by 5tarlight** [comment]
@TyphoonDANAS 
구글 콘솔에서 `Google+ API` 가 `turn off` 꺼져있지 않은지 확인하십시오.
그리고 본인의 도메인을 가지고 있다는 전재 하에 `http://도메인.gg/auth/google/callback` 으로 리다이렉션을 지정하십시오
auth.json 정도만 건들면 됩니다.

**Comment by 5tarlight** [comment]
그리고 @houlday 그 파일은 건들 필요가 없습니다

**Comment by TyphoonDANAS** [comment]
@SkyLightQP 리다이렉션을 그렇게 지정하고 재부팅했더니 npm 오류가 뜨고 electron이 실행디지 않는데, 이건 관계가 있는 건가요?

**Comment by lshqqytiger** [comment]
아뇨 리다이렉션과 저런 오류는 관계가 없습니다.

**Comment by 5tarlight** [comment]
@TyphoonDANAS 일렉트론 재설치같은거 해보세요

**Comment by houlday** [comment]
@TyphoonDANAS Electron 이라는 명령어가 없다고 보이네요

**Comment by TyphoonDANAS** [comment]
npm 문제는 해결했지만, @5tarlight 님이 알려주신 대로 했더니 다른 알 수 없는 사이트로 들어가집니다.
![음](https://user-images.githubusercontent.com/49607272/58757336-988b1480-8545-11e9-9fb3-6b887ffd5d2c.PNG)

**Comment by 5tarlight** [comment]
아 진짜 저걸 그렇게 하셨구나
@TyphoonDANAS 도메인설정에서 `http://도메인.gg/auth/google/callback`으로 설정하라고 했던건 하나의 예시었습니다

**Comment by 5tarlight** [comment]
예를들어 도메인이 `5tarlight.kro.kr`라면 설정을 `http://5tarlight.kro.kr/auth/google/callback`으로 설정하라는 뜻이었습니다

**Comment by TyphoonDANAS** [comment]
@5tarlight 다시 Cannot GET /auth/google/callback이 뜹니다

**Comment by lshqqytiger** [comment]
/login/google/callback으로 하셔야 합니다.

**Comment by TyphoonDANAS** [comment]
해결했으니 이슈 닫습니다.
