### ISSUE TITLE
한방단어가 아닌 단어가 한방단어로 뜹니다.

### ISSUE THREAD

**Issue by TyphoonDANAS** [JJoriping/KKuTu#509]
단어 '켓사나'를 추가하였지만, 다단식로켓, 이륙보조로켓 등이 한방단어로 나옵니다.
한방단어가 아니게 설정하려면 어떻게 해야 하나요?

**Comment by minesna** [comment]
``혹시 켓사나 단어가 어인정이 아닌지 ->
플레이를 어인정 없이 하였는지 ``
가 의심되네여

**Comment by TyphoonDANAS** [comment]
@minesna 어인정은 킨 상태였습니다.

**Comment by lorlol701** [comment]
`gwalli` 에서 해당 단어가 제대로 추가되었는지 조회를 해보세요.

**Comment by JJoriping** [comment]
안녕하세요. 내부적으로 한방 단어는 '더 이을 수 있는가?'를 판단해야 하는데, 사용자가 매 턴 단어를 입력할 때마다 이를 판단하는 것은 오래 걸리는 일이기 때문에 한 번 판단한 단어에 대해서는 그 정보를 데이터베이스에 기록해둬 나중에 같은 판단을 해야할 때 데이터베이스에서 바로 꺼내오는 방식으로 구현되어 있습니다.
https://github.com/JJoriping/KKuTu/blob/a4f948b3fbb0cf9dd0655b3f19f67b2d08166458/Server/lib/Game/games/classic.js#L448-L455
따라서 추후 단어를 추가했더라도 한방 단어였던 사실이 데이터베이스에 아직 남아있기 때문에 한방 단어로 인식하게 됩니다. 그래서 데이터베이스의 테이블 `kkutu_manner`에서 한방 단어였던 단어를 찾아 그 정보를 삭제해야 정상 작동합니다.

**Comment by TyphoonDANAS** [comment]
@JJoriping 늦어서 죄송합니다.
혹시 kkutu_manner이라는 테이블이 어디 있는지 알 수 있을까요?

**Comment by lshqqytiger** [comment]
![123](https://user-images.githubusercontent.com/39524005/66717410-b03ba900-ee13-11e9-82b8-2df4c87d6239.PNG)

이곳에 존재합니다.

**Comment by TyphoonDANAS** [comment]
해결했습니다. 도움 주신 분들 감사합니다. 이슈 닫습니다.
