### ISSUE TITLE
이거는 무슨 문제이고 어떻게 해결해야 하나요

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#510]
![20190603_200028](https://user-images.githubusercontent.com/42174930/58798012-72946b80-863c-11e9-8827-eafd63aac28e.png)
이렇게 잘 들어가있는데,
![20190603_165044](https://user-images.githubusercontent.com/42174930/58798021-7c1dd380-863c-11e9-8b6b-c6ac24144153.png)
갑자기 이렇게 뜹니다.

(+)채팅창에 채팅이 안써지고, 전송 버튼도 눌르면 아무런 작동이 되지 않습니다. in_game_kkutu.min.js를 다시 원래대로 해야하나요? 아니면은 따로 무슨 문제가 있나요?

**Comment by lshqqytiger** [comment]
뭔가를 잘못 만지신 듯 합니다.

**Comment by bokmook** [comment]
**+ 추가 서류**

**심각한 서버 오류(_[SERVER EMERGENCY WARNING]_)라는 메시지가 지속적으로 뜬다 합니다.**


_[허트끄투 - 개발부] 올림._

**Comment by lorlol701** [comment]
개발자 도구 콘솔을 참조하여 오류가 발생하였는지 확인해보시면 좋을듯 합니다.
