### ISSUE TITLE
쪼롤에 등록이 되지 않습니다.

### ISSUE THREAD

**Issue by TyphoonDANAS** [JJoriping/KKuTu#511]
html 파일 이름도 올바르게 설정했고, 안 내용도 서버 주소를 기입했지만 계속해서 소유권을 확인하기 위해...가 뜹니다.
![서버등록오류 1](https://user-images.githubusercontent.com/49607272/58961391-f8065000-87e3-11e9-9845-4c2fdb94411f.PNG)
![서버등록오류 2](https://user-images.githubusercontent.com/49607272/58961401-fb99d700-87e3-11e9-8a94-dcbfae024f1b.PNG)
어디가 잘못된 건가요?

**Comment by lshqqytiger** [comment]
www를 빼보세요

**Comment by TyphoonDANAS** [comment]
@lshqqytiger 똑같은 메세지가 뜨면서 등록이되지 않습니다.

**Comment by lshqqytiger** [comment]
쪼리핑님께 문의하셔야 합니다. 저도 전에 등록이 안되어서 쪼리핑님께 디스코드로 문의드렸더니 원인이 무엇인지 알려주셨습니다.

**Comment by lorlol701** [comment]
해당 html파일의 경로를 확인해 보세요. `lib/Web/public` 경로에 생성해주셔야 합니다.

**Comment by TyphoonDANAS** [comment]
현재 단어 수정으로 인해 등록은 어렵지만, 해결했으니 이슈 닫습니다.
