### ISSUE TITLE
사전에 검색을 하여도 검색 중 만뜨고 별 반응이 없습니다.

### ISSUE THREAD

**Issue by houlday** [JJoriping/KKuTu#512]
위 제목처럼 사전에 단어를 검색하려니 검색 중만 뜨네요

**Comment by minesna** [comment]
어디가 문제인지 모르겠네요 ( ͡° ͜ʖ ͡°)
브라우저 콘솔 오류를 확인해주세요

**Comment by houlday** [comment]
> 어디가 문제인지 모르겠네요 ( ͡° ͜ʖ ͡°)
> 브라우저(&끄투) 콘솔 오류를 확인해주세요

![이리듐 딴딴딴](https://user-images.githubusercontent.com/50253488/59006473-16f4f880-885d-11e9-8850-11370c338a4c.PNG)

**Comment by andjsrk** [comment]
`a-zA-Zㄱ-ㅎ0-9가-?`부분이 문제인 것 같은데요. 가-?를 가-힣으로 바꿔보세요.

**Comment by bokmook** [comment]
인코딩 실수로 잘못 등록된 것 같습니다.
