### ISSUE TITLE
웹 소켓 연결 안 됨

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#514]
`WebSocket connection to 'ws://(URL):8080/hVIdCWFUVeTuXVsJpOY8hMrfiahJOkc_' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT
h @ in_game_kkutu.min.js:1598`이라고 뜨며 서버 연결이 1에서 멈추며 서버와의 연결이 끊깁니다.

**Comment by houlday** [comment]
무언가를 잘못 만지신 듯 합니다

**Comment by andjsrk** [comment]
그건 저도 알고 있습니다.
애초에 문제가 있어서 이슈를 남기는건데 왜 그렇게 말하시는거죠

**Comment by minesna** [comment]
혹시 서버 주소를 알 수 있을까요??

**Comment by houlday** [comment]
> 그건 저도 알고 있습니다.
> 애초에 문제가 있어서 이슈를 남기는건데 왜 그렇게 말하시는거죠

죄송합니다....

**Comment by andjsrk** [comment]
> 혹시 서버 주소를 알 수 있을까요??

http://kkutu.today
입니다

**Comment by bokmook** [comment]
``in_game_kkutu.min.js`` 파일의 598번줄 부분을 참고하면 될 것 같습니다.

**Comment by bokmook** [comment]
오류 핸들링은 직접하셔야 됩니다. 
현재 코드를 직접 확인하지 않는 이외에는 오류 메시지만으로는 정확하게 말씀드리기가 어렵습니다.

**Comment by andjsrk** [comment]
해결했습니다.
