### ISSUE TITLE
GM전용 단어

### ISSUE THREAD

**Issue by Chunhak** [JJoriping/KKuTu#515]
GM전용 단어 설정이 가능한가요

**Comment by houlday** [comment]
가능합니다 하지만 구현하는건 직접 하셔야 합니다
파일 이름 : MASTER.JS

**Comment by houlday** [comment]
그외에도 in_game_kkutu_min 인가 거기서도 만져야 하는걸로 압니다

**Comment by lorlol701** [comment]
직접 개발하시면됩니다.

**Comment by houlday** [comment]
치명타 엌

(해결 되셨으면 이슈를 닫아주세요)

**Comment by bokmook** [comment]
> 그외에도 in_game_kkutu_min 인가 거기서도 만져야 하는걸로 압니다

``in_game_kkutu.min.js`` 파일과는 관련이 없습니다.
``master.js`` 및 ``Game`` 폴더 내에서 수정하고자 하는 모드의 파일을 수정하면 됩니다.
