### ISSUE TITLE
환경 설정에 새로 추가한 항목들의 값이 저장되지 않습니다.

### ISSUE THREAD

**Issue by lshqqytiger** [JJoriping/KKuTu#517]
환경 설정에 새로 추가한 옵션들을 건드려도 저장 후 다시 설정 창에 들어가면 원래대로 되어있습니다. 새로 추가한 옵션들이 아닌 기존에 있던 옵션들은 잘만 저장됩니다. 제가 수정을 안한 부분이 있는 것 같은데 어디를 더 수정해야 할까요?

수정한 것들
in_game_kkutu.js
body.js
ready.js
kkutu,pug
in_game_kkutu.min.js
ko_KR.json

**Comment by andjsrk** [comment]
혹시 파일 저장 후 바로 설정을 껐다 켜셨나요?
혹시 그러셨다면, 서버를 재부팅하고 재시도하세요.

**Comment by lshqqytiger** [comment]
이미 수십번 재부팅 되었지만 동일합니다.

**Comment by andjsrk** [comment]
어떤 부분을 추가하셨나요?

**Comment by lshqqytiger** [comment]
제대로 minfy 하지 않아 발생한 문제 같습니다. 일단 이슈 닫고 다시 시도해보겠습니다.
