### ISSUE TITLE
이거 삭제법 알려주세요

### ISSUE THREAD

**Issue by KAKAO24** [JJoriping/KKuTu#519]
![캡처](https://user-images.githubusercontent.com/49306402/60884068-f8808380-a286-11e9-864a-c1169e7ce9d0.PNG)

**Comment by lshqqytiger** [comment]
ko_KR.json에 해당 값을 추가하셔야 합니다. 이미 추가한 상태라면 서버 재부팅하세요. (ko_KR.json은 서버 재부팅시 다시 불러옴)

**Comment by houlday** [comment]
@KAKAO24 이슈가 해결 되셨다면 닫아주시길 바랍니다
