### ISSUE TITLE
영어 단어 뜻처럼 한국어 단어에 뜻 추가

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#520]
![20190717_174007](https://user-images.githubusercontent.com/42174930/61360721-f2f3f080-a8b9-11e9-9fd5-86bfc503a8fe.png)
영어는 WordNet 자료가 들어가서 저렇게 되어있는데, 그러면 한국어 단어는 어떻게 추가해야하나요? 직접 구현해야하는건 알겠는데, 영어처럼 " 1 " elephant " 2 " idiot 이렇게 하는 것처럼,
한국어도 " 1 " 육대주 중 가장 큰 땅. " 2 " 오대양 중 가장 큰 바다. 이렇게 [ 1 ] ( 1 ) 빼서 추가하면 되나요?

**Comment by swoo5571** [comment]
" 1 " [ 1 ] ( 1 ) 애니메이션 중 하나(예제).
에서,
" 1 " 사과는 맛있쪙(예제).
이렇게요.

**Comment by andjsrk** [comment]
관리자 페이지에서 하셔야 합니다.

**Comment by lorlol701** [comment]
저 파일 수정을 통해 추가하는게 아닌 걸로 알고 있습니다.

**Comment by swoo5571** [comment]
![캡2222처](https://user-images.githubusercontent.com/42174930/62466669-d23dfd00-b7cc-11e9-9525-9d44e298999c.PNG)
이렇게 하려면 어떻게 해야하나요. 50만개 솔직히 한꺼번에 추가하고 싶은데(초보라서...)
