### ISSUE TITLE
쪼롤 추가

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#521]
홈페이지 또는 게임 페이지의 저작권 관련 내용 표시가 조건에 맞지 않습니다 라는 문구가나와요 찾아봐도 이런건 찾을부가 없어요

**Comment by andjsrk** [comment]
ko_KR.json의 맨 윗줄 GPL에 보면, `글자로 놀자! 끄투 온라인 Copyright (C) {년도} {배포자}({이메일 등})<br>이 프로그램은(중략)<a target='_blank' href='{이 서버의 소스 코드 위치}'>{이 서버의 소스 코드 위치}</a>`라고 되어있는데요, 년도와 배포자(이메일 등)에는 각자 괄호를 지우고 현재 년도와 자신의 이름(또는 자신의 이메일)을 적고, `<a target='_blank' href='{이 서버의 소스 코드 위치}'>{이 서버의 소스 코드 위치}</a>`에서는 괄호를 지우고 자신이 포크한 끄투 레포지토리의 링크(예 : https://www.github.com/JJoriping/KKuTu )를 넣어주시면 됩니다.

**Comment by hands8142** [comment]
감사합니다
