### ISSUE TITLE
ssl 만드는법

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#523]
ssl을 만들려고 하는대 뭐로 선택해야 할지 모르겠어요 윈도우로 하고있습니다
![캡처](https://user-images.githubusercontent.com/46277532/62262981-96660900-b455-11e9-865b-94c81c3c8a66.PNG)

**Comment by lshqqytiger** [comment]
https://www.sslforfree.com/
(Let's Encrypt)

전 이 사이트 사용합니다. 제일 간편하고 좋은거 같더라구요.

**Comment by hands8142** [comment]
3개 고르라고 나오는대 뭘로해요??

**Comment by lshqqytiger** [comment]
.well-known 이었나 그 폴더로 인증하는게 제일 편합니다. 영어 설명 보고 고르세요

**Comment by hands8142** [comment]
![캡처1](https://user-images.githubusercontent.com/46277532/62506300-1831aa00-b83b-11e9-8d8f-2ad503cb57f2.PNG)
이거 3개중에요

**Comment by lshqqytiger** [comment]
Manual Verification 입니다.

**Comment by hands8142** [comment]
![캡처](https://user-images.githubusercontent.com/46277532/62672502-edc82400-b9d5-11e9-8c19-1d6a56e53a26.PNG)
ssl을 적용했는데 거부가 되었다고 떠요

**Comment by JJoriping** [comment]
서버 설정이 잘못되어 올바른 포트로 서버가 열리지 않았거나, 방화벽에서 포트를 개방하지 않았거나, 포트포워딩이 되지 않은 것으로 보입니다. 기존 SSL 관련 이슈 #462, #473 등에서 제시한 서버 설정들을 참고해 적절히 설정해 보기 바랍니다.

**Comment by hands8142** [comment]
ssl을 없에면 들어가지는대 ssl을 추가시키면 안들어가져요 설정은 다로 만지건없고 포트포워딩은 재대로 되었고 방화뵥을 없에도 이현상이 생깁니다

**Comment by Seia-Soto** [comment]
Let's Encrypt를 사용하여 SSL 인증서를 생성시키는 경우에는 총 2가지의 방법이 있습니다. 여기에서 방법이라함은 SSL을 무료로 제공하여 HTTP 보안 연결률을 높이려는 Let's Encrypt 사의 도메인 검증 시스템입니다. 각각 첫 번째는 파일을 사용하여 두 번째는 DNS를 사용하여 인증합니다.

시작하기 전에 HTTP와 HTTPS 연결을 위한 포트를 모두 개방해야 합니다.

- HTTP: 80
- HTTPS: 443

저의 경우에는 **Ubuntu 환경에서 DNS를 사용**한 방법으로 진행하겠습니다.

먼저 `letsencrypt` 패키지를 설치합니다. 이는 기존의 Certbot으로 알려졌던 인증서 발급 및 자동 갱신 도구와 동일한 패키지의 상위 버전이며 Certbot의 최신 버전을 사용하셔도 됩니다.

> DNS를 사용할 경우에는 자동 갱신이 불가능하니 3개월마다 다시 발급하셔야 합니다

```sh
sudo su

apt update
apt install letsencrypt

letsencrypt --manual --preferred-challenges dns certonly -d domain.tld
```

마지막에 DNS 발급의 전체 명령어를 적어놓았습니다.

그리고 접속 거부와 같은 메세지는 따로 오류 코드를 첨부하셔야 합니다.
보통의 경우에는 서버 설정의 오류입니다.

잘못된 인증서를 제공하는 등의 여러가지 원인이 있으니 서버 로그를 확인하시기 바랍니다.
또 Express와 같이 Node.JS 상의 웹 서버를 사용하는 경우 보안을 위해서 Nginx를 통해 프록시로 서비스하시기를 강력히 권해드립니다.

**Comment by lshqqytiger** [comment]
443 포트도 개방해야 하는군요. 전 포트포워딩 없이 서버를 열어서 모르고 있었네요.

**Comment by hands8142** [comment]
그러면 포트포워딩 442포트만 열어주면되나요?? 아니면 다른것도 추가해야하나요??

**Comment by Seia-Soto** [comment]
네, **443** 포트를 개방하시면 됩니다.

필요한 것은 위에서 모두 설명했고 다른 추가 질문 사항은 질문하기 전에 미리 Google 등에 검색하시기 바랍니다. 프로젝트의 이슈 탭은 개개인의 문제로 인해 여는 것이 아닙니다. 완료되셨으면 누가 해당 이슈 닫아주시기 바랍니다.

**Comment by Seia-Soto** [comment]
또한 자신의 SSL이 얼마나 보안 향상에 도움이 되는지 알아보기 위해서 [Mozilla Observatory](https://observatory.mozilla.org/)를 사용할 수 있으니 참고해보시기 바랍니다. 저의 경우에는 B등급을 지속적으로 유지하고 있습니다.

**Comment by hands8142** [comment]
근대 방만들기를 하면 방이 안만들어져요
![캡처](https://user-images.githubusercontent.com/46277532/63072197-73f7e380-bf5d-11e9-9edd-73d912c1af80.PNG)

**Comment by Seia-Soto** [comment]
소켓 작동하는지 확인해주시고 해당 이슈와는 관계가 없으므로 닫아주시길 바랍니다.

**Comment by hands8142** [comment]
소켓은 잘작동합니다 그리고 이일은 ssl을 적용 하고나서부터 생겼습니다

**Comment by Seia-Soto** [comment]
그렇다고 현재 이슈가 위 제목 내에서 성립되기 어렵습니다. 또한 문제 해결에 도움을 청하실 때에는 반드시 에러를 포함한 로그파일을 포함해주시고 완전한 재현가능한 방법을 서술해주셔야 도움이 됩니다.
