### ISSUE TITLE
상점 아이템 증발

### ISSUE THREAD

**Issue by hyusan12334** [JJoriping/KKuTu#529]
상점에서 아이템을 삭제하려다 뭘 잘못만져서 상점 아이템이 전부 증발했습니다

뭘 수정해야 원래대로 돌아오나요

**Comment by lshqqytiger** [comment]
원래 상점 아이템 변경 사항 저장 후에는 서버 재부팅 전까지는 상점에 아무것도 뜨지 않습니다.

**Comment by hyusan12334** [comment]
아예 상점 아이템 자체가 증발됬습니다.

**Comment by lshqqytiger** [comment]
원본 DB를 가져와서 적용하시거나 다시 추가하시면 됩니다.

**Comment by hyusan12334** [comment]
db.sql 원본꺼 복붙해도 그대로입니다

**Comment by lshqqytiger** [comment]
관리자 페이지에서 상점 DB 관리에 ~ALL 검색해보셨나요?

**Comment by hyusan12334** [comment]
db.sql을 원본꺼로 복붙해도 db가 여전히 남아있네요
