### ISSUE TITLE
관리자 페이지 접속 시 오류 발생

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#53]
http://서버주소/gwalli 를 주소창에 입력을 하였더니, {"error":400"} 이 발생합니다.
버그인가요? 아니면 제가 설정을 잘못한건가요?

**Comment by JJoriping** [comment]
관리자 계정으로 로그인을 한 뒤에 페이지에 접근할 수 있습니다.

**Comment by kim-min** [comment]
![default](https://cloud.githubusercontent.com/assets/13843919/23352833/bd6d33dc-fd0c-11e6-92ab-59b57a2c47f1.PNG)
다음과 같은 화면을 띄우며 접속 할 수 없습니다.

**Comment by pkpai0926** [comment]
최신 버전의 소스 코드를 다운로드 받지 않은 모양이시네요.
`끄투폴더/Server/lib/Web/views/gwalli.pug` 파일의 첫 번째 줄 `//` 뒤에 `-` 하나를 추가하세요.

**Comment by kim-min** [comment]
감사합니다.
