### ISSUE TITLE
db.sql엔 없는 아이템이 인게임 데이터엔 존재합니다

### ISSUE THREAD

**Issue by hyusan12334** [JJoriping/KKuTu#530]
현재 상점 아이템 노출에 문제가 생겨 db.sql을 원본으로 치환했습니다.
그리고 관리자페이지를 들어가 상점db 란에 ~ALL을 쳤습니다
그랬더니 db.sql을 치환하기 전의 아이템들이 그대로 남아있더라고요
인게임 데이터와 db.sql이 같은거 아닌가요?

**Comment by andjsrk** [comment]
db를 갈아엎으셔야 합니다. 전부 갈아엎으시려면 pgadmin에서 main db를 삭제한 뒤, cmd로 재구축해주세요.
