### ISSUE TITLE
배경 gif 파일이 불러와지지 않습니다.

### ISSUE THREAD

**Issue by hyusan12334** [JJoriping/KKuTu#531]
상점에 배경으로 gif파일을 등록했습니다.
이름 잘 작성했습니다.
그러나 상점에 들어가보면 이미지 로딩이 안되어있습니다.
![df](https://user-images.githubusercontent.com/53594682/62478001-0c1afd80-b7e5-11e9-82bc-80aeba7e3a31.png)

뭐 gif 용량제한이 있나요 파일개수 제한이 있나요

**Comment by andjsrk** [comment]
제가 알기론(저도 잘 모르지만) 관리자 페이지에서 뭔가 따로 설정을 해줘야 할겁니다.

**Comment by lshqqytiger** [comment]
관리자 페이지에서 따로 gif 설정을 하지 않으면 png 파일만 인식합니다.

관리자 페이지에서 해당 아이템 능력에 "gif":true 를 추가해 주세요.
