### ISSUE TITLE
csv to db.sql

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#532]
제가 어느 github에서 표국대 alldic.csv를 가지고 있는데 이거를 어떻게 db.sql에 넣는지 궁금합니다. 가능하면 JJoriPing님이 답변해주시면 좋겠습니다. 코딩초보인 저는 진짜로 모르겠네요...어떻게 하는지 부탁드립니다..

**Comment by andjsrk** [comment]
구글에 검색 조금만 해 봐도 csv에서 sql파일로 바꾸는 방법 나옵니다. **검색을 하세요.**

**Comment by sunho** [comment]
csv 칼럼 구조를 끄투 디비의 구조에 맞춰줘야 합니다. mysql을 공부해보시길...

**Comment by lshqqytiger** [comment]
http://www.convertcsv.com/csv-to-sql.htm

구글에 치면 바로나옵니다만..

**Comment by sunho** [comment]
오호라 저런 툴이 있군. 만약 운이 좋게 csv 구조가 끄투 디비와 동일하다면 오케이 버튼을 누르기만 하면 되겠네요. 그렇지 않다면 Output options에서 이거저거 건드려줘서 끄투 디비에 맞춰줘야 할 겁니다.

**Comment by Seia-Soto** [comment]
아마 보통의 경우라면 구조적인 차이가 있을겁니다. 보통의 경우에는 환형 큐를 사용하여 SQL로 조금씩 입력시키는 방식이 적당합니다. 해당 CSV 파일의 구조를 알 수가 없어 정확한 답변은 못 드리겠습니다. 그러나 어떤 언어라도 CSV 파일을 읽고 조금씩 데이터베이스에 쿼리한 다음 해당 데이터베이스를 추출하시는 등의 방식으로 가능합니다.

1. CSV 파일 읽기
2. 파일을 읽고 자신이 원하는 형식으로 변환
3. SQL 쿼리를 통해 데이터베이스에 원하는 형식으로 전송
4. 데이터베이스를 SQL 형식으로 추출

위와 같은 형식의 작업이 될 것입니다. 이 때 원하는 형식은 끄투의 포맷이 될 것이고요.
