### ISSUE TITLE
그림퀴즈 추가 오류

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#533]
![y8yo9i](https://user-images.githubusercontent.com/53849587/62595761-95801c00-b91a-11e9-8b81-32b822fe750d.PNG)
그림퀴즈를 추가했더니 사진과 같은 오류가 나옵니다
뭐 해결할려고 만져도 보긴 했지만 잘 모르겠네요
해결방법이 있나요?

**Comment by spnia** [comment]
'ulm': { name: "Unlimited" }
를 지우니 저 오류는 사라졌습니다
근데 한글 그림퀴즈를 하면 서버가 10초뒤에 재부팅되고
영어 끝말잇기를 하면 "kkutu_cw_en" 이름의 릴레이션이 없다 나오네요

**Comment by andjsrk** [comment]
랜덤미션쪽에서 오류가 났는데요..?
