### ISSUE TITLE
데이터 배이스에 있는걸 어덯게 빼요??

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#534]
알려주세요...

**Comment by lshqqytiger** [comment]
pgAdmin 4에 백업 기능 있습니다.

**Comment by hands8142** [comment]
![캡처](https://user-images.githubusercontent.com/46277532/62608180-55c92c80-b93a-11e9-84e3-d435f3ffbb4a.PNG)
여기서 어떻게해요???

**Comment by andjsrk** [comment]
우클릭하신 뒤 delete/drop을 누르시고, OK를 눌러주세요.

**Comment by hands8142** [comment]
[Errno 13] Permission denied: 'C:\\main.sql' 이런 오류가 생겨요

**Comment by JJoriping** [comment]
데이터베이스에 있는 많은 것들 중 어떤 것을 가리키는 것인지, 뺀다는 것이 무슨 의미인지 모호합니다.
데이터베이스에 등록된 단어 하나를 빼려 하는 거라면 간단한 SQL 구문으로 처리할 수 있으니 SQL에 대해 설명하고 있는 여러 문서[(나무위키 등)](https://namu.wiki/w/Structured%20Query%20Language)들을 꼭 숙지하기 바랍니다.

**Comment by hands8142** [comment]
그냥 싹다 빼고 호스팅을 하려고 데이터베이스에있는 main 에있는 모든것을 움길려고요

**Comment by JJoriping** [comment]
안녕하세요. 해당 작업은 [이 블로그](https://server-talk.tistory.com/30)에서 소개하고 있는 SQL로 충분히 진행할 수 있습니다. 자세한 설명은 구글에서 `mysql db 이동`같은 검색어를 통해 쉽게 접할 수 있습니다.

**Comment by hands8142** [comment]
링크에 블로그는 위도우가 아닌거같은데요 저는 윈도우를 사용는데... 일단 재가 찾아볼게요 알려주시면 감사합니다

**Comment by bokmook** [comment]
> 링크에 블로그는 위도우가 아닌거같은데요 저는 윈도우를 사용는데... 일단 재가 찾아볼게요 알려주시면 감사합니다

윈도우와 저 블로그가 설명하는 것과 무슨 상관인지는 모르겠으나,
SQL문이 작동되지 않으시는 것이라면 SQL의 Command Line Interface가 깔려 있지 않거나, cd 명령어 등을 통하여 작업위치를 CLI 실행위치로 옮기고, 다시 한번 SQL문 시도해 보세요(환경변수를 미리 추가해 두시면 위의 반복적인 작업을 생략할 수 있습니다)
