### ISSUE TITLE
그림퀴즈 실행시 kkutu_cw_en 이름의 릴레이션이 없습니다.

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#535]
한국어/영어 그림퀴즈 플레이 실행시
when querying: SELECT * FROM kkutu_cw_en WHERE TURE [2019-08-07 16:15:42] Context: error: "kkutu_cw_en" 이름의 릴레이션(relation)이 없습니다
라고 나옵니다

그림퀴즈 PR을 아예 덮어씌우긴 다른 모드도 있어서 약간 좀 그런데
이거만 고칠 수 있는 방법이 있나요

**Comment by lshqqytiger** [comment]
그림퀴즈 오류는 제 경험상 덮어 씌우는 것 외에는 해결하기 힘듭니다. 저 오류는 kkutu_cw_en 컬럼을 만들어 주시면 해결됩니다.

**Comment by spnia** [comment]
테이블 위치가 어디인가요?

**Comment by spnia** [comment]
kkutu_cw_ko랑 비슷한 내용인가요?

**Comment by lshqqytiger** [comment]
내용은 알 수 없습니다. 저는 kkutu_cw_ko만 존재합니다.
