### ISSUE TITLE
ssl 인증 오류

### ISSUE THREAD

**Issue by hands8142** [JJoriping/KKuTu#536]
ssl을 적용을 했는대 접근이 거부되었다고 떠요

**Comment by JJoriping** [comment]
안녕하세요.
접근이 거부되었다고만 말씀하시면 구체적으로 어디로의 접근이 막혔는지 확인하기 어렵습니다. 오류 내용이 포함된 스크린샷을 함께 첨부해 주시면 해결 가능성이 커집니다. 또한 본 이슈는 기존에 만들어진 #523 이슈에서 계속해 주세요.
