### ISSUE TITLE
이 에러는 뭐죠

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#537]
ERROR OCCURRED ON THE MASTER! :8080 [2019-8-7 23:05:10] ERROR: TypeError: Cannot read property 'url' of undefined TypeError: Cannot read property 'url' of undefined at WebSocketServer.&lt;anonymous> (C:\Users\user\Downloads\KKuTu-master\Server\lib\Game\master.js:289:32) at WebSocketServer.emit (events.js:203:13) at C:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:88:16 at WebSocketServer.completeUpgrade (C:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:270:5) at WebSocketServer.handleUpgrade (C:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:197:10) at Server.&lt;anonymous> (C:\Users\user\Downloads\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:87:14) at Server.emit (events.js:203:13) at onParserExecuteCommon (_http_server.js:605:14) at onParserExecute (_http_server.js:544:3)

분명 포트포워딩 80 8080 8492 다하고 기본설정까지 다했더니 저렇게 뜹니다.
서버는 잘 들어가지는데 이상하게 로그인까지는 정상이고 아예 감자서버자체에 접속이 안되요

**Comment by JJoriping** [comment]
안녕하세요. 이 오류는 끄투에서 사용하는 `ws` 모듈 버전을 최근 업그레이드시키면서 websockets/ws#1099 이슈에 대한 처리가 빠져 생긴 문제입니다. 이제 처리를 했으니 레포지토리를 다시 받아 작동시켜 보세요.

**Comment by swoo5571** [comment]
해결되었습니다. 감사합니다.
