### ISSUE TITLE
public.kkutu_cw_en 이름의 릴레이션이 없습니다

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#538]
pgadmin에서 kkutu_cw_ko가 들어간 데이터에서 내용의 ko만 en으로 바꾸고 kkutu_cw.en.sql 이런식으로 바꿔서 추출을 하고 cmd에서 program files\postgresql\11₩bin 에서 psql~~ 치니 public.kkutu_cw_en 이름의 릴레이션이 없다 나옵니다.
(psql -U "postgres" -d "main" -f "경로₩kkutu_cw_en(생략).sql)
약 5가지(kkutu_cw_ko__id_seq.sql, kkutu_cw_en.sql, _id.sql, map.sql, data.sql, kkutu_cw_en_key.sql)을 만들어서 넣어봐도 전부 저 오류가 나옵니다

뭐 따로 또 있는건가요
아니면 명령어나 경로같은걸 잘못 입력한건가요

**Comment by andjsrk** [comment]
kkutu_cw_en은 기존 끄투 db엔 없는 테이블입니다. 뭔가를 잘못 하신 게 아닐까요

**Comment by spnia** [comment]
그래서 kkutu_cw_en.sql을 만들어 넣을려고 하는데 저 오류가 나옵니다
명령어같은게 잘못됬나요
