### ISSUE TITLE
그림퀴즈 멈춤

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#539]
![lll](https://user-images.githubusercontent.com/53849587/62647258-18d95600-b98b-11e9-8fc2-0b4a164da97f.png)
kkutu_cw_en sql들 만들어서 넣고
그림퀴즈 PR에 있는것들 빠짐없이 복사하고 일부 파일은 덮어 씌우고 했는데
시작 누르면 저상태로 멈춰버립니다.

뭐 로그같은데에도 아무것도 안나오니 원 알수가 없네요
해결할 수 있나요

**Comment by spnia** [comment]
구글 콘솔 보니 in_kkutu.min.js가 없다고 나오는데...
이 파일이 뭔가요?
어디서도 찾을수가 없네요

**Comment by andjsrk** [comment]
제대로 추가하신 게 맞나요? 잘못 추가함으로 인해 저렇게 되는 것일 확률이 있습니다.

**Comment by spnia** [comment]
Pr에 나온 코드/추가 파일들은 전부 넣었고 확인도 했습니다

**Comment by lorlol701** [comment]
`in_kkutu.min.js`는 원래 존재하지 않는 파일입니다.

**Comment by lshqqytiger** [comment]
그냥 전체적으로 문제가 있어보입니다. 싹 갈아엎고 다시 작업하시는 게..
