### ISSUE TITLE
그림퀴즈 오류

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#542]
(요즘 질문을 좀 많이하네요..)
![ㄱ2342432](https://user-images.githubusercontent.com/53849587/62822719-347a7180-bbc2-11e9-9f77-409f483f7e84.png)
전의 오류는 kkutu_cw_en에 데이터를 넣었더니 해결은 되었습니다만
저렇게 십자말풀이 ui가 나옵니다
그리고 아직 4개만 넣어서 그런지 모르겠지만 라운드가 2만 작동합니다. 2라운드부터 시작하고 2라운드에서 끝납니다
뭐가 빠졌는지 한 몇십번은 확인한거같은데 다 있습니다.
현재
.gitignore 수정
drawing.js 추가
kkutu.js 수정
slave.js 수정
Gruntfile.js 수정
en_US.json 수정
ko_KR.json 수정
in_kkutu.js 수정
body.js 수정
head.js 수정
ready.js 수정
rule_drawing.js 추가
in_m_kkutu.css 수정
fabric.min.js 추가
m_kkutu.pug 수정
const.js 수정
collection.js 수정
in_game_kkutu.js 수정
in_game_kkutu.min.js 수정
jquery.js 수정
했습니다.
데이터가 부족해서 저런 버그가 나는걸까요 진짜 뭐가 빠진건지 모르겠네요

**Comment by lshqqytiger** [comment]
cw는 crossword의 줄임말입니다. 따라서 kkutu_cw_en DB는 십자말풀이 DB입니다. 지금 영어 십자말풀이 코드가 들어간것 같습니다.

**Comment by spnia** [comment]
근데 처음에 오류엔 kkutu_cw_en 릴레이션이 없다나와서 저 테이블을 만든겁니다

**Comment by spnia** [comment]
그림퀴즈pr로 구동시켰을때랑 개작파일로 구동시켰을때의 데이터베이스는 같은데
왜 개작파일로 했을땐 안되는지 모르겠네요

**Comment by spnia** [comment]
일단 paint_색상.png 같은 여러 파일이 로딩이 안됬네요

**Comment by spnia** [comment]
Uncaught TypeError: Cannot read property 'dir' of undefined
    at HTMLDivElement.$lib.Crossword.onBar (in_game_kkutu.min.js:22)
    at HTMLDivElement.dispatch (jquery.js:20)
    at HTMLDivElement.y.handle (jquery.js:20)
오류가 뜹니다
