### ISSUE TITLE
끄투 프리서버를 운영하고 싶습니다

### ISSUE THREAD

**Issue by cukiecat** [JJoriping/KKuTu#546]
![20190816_231302](https://user-images.githubusercontent.com/50296931/63173812-9d0e9600-c07b-11e9-80f9-4cf06bde7cb3.png)
자꾸 암호를 입력하면 No such file or directory가 뜨는데 이걸 하기 전에 다른것들을 실행해야 하나요? 저는 readme.md에서 server-setup.bat까지는 실행시켰지만 run.bat은
![2](https://user-images.githubusercontent.com/50296931/63174093-3a69ca00-c07c-11e9-82c6-52687c74f18d.png)
이런 오류가 뜨네요... 저는 잘 모르겠어서요...
하는법 알려주실수 있나요?

**Comment by lorlol701** [comment]
명령어에서 가르키는 sql 파일의 경로는 끄투 레푸지토리 내의 db.sql 파일의 경로입니다.

**Comment by lshqqytiger** [comment]
db.sql은 끄투 파일 내에 있습니다. postgreSQL과 npm에 대한 기본 지식을 가지고 시작하시는 것이 쉽습니다.

**Comment by andjsrk** [comment]
`?ㅻ쪟: "main" ?대쫫???곗씠?곕쿋?댁뒪???대? ?덉쓬` 이건
https://github.com/JJoriping/KKuTu/issues/391#issuecomment-443499959 여기 참고하시고
db.sql 파일은 KKuTu-master\KKuTu-master 폴더에 있습니다.
run.bat 파일은 셋업을 하면 KKuTu-master\KKuTu-master\Server 폴더에 생기구요,
`npm start`는 run.bat 파일을 열었을 때 자동적으로 실행되는 겁니다.

**Comment by lorlol701** [comment]
`npm start` 를 `run.bat` 실행 없이 직접 입력해도 됩니다. 다만 `KKuTu-Master` 최상위 경로에서 이를 실행 시 오류가 나므로, `cd` 명령어 등을 이용해서 `Server` 폴더 경로로 이동해 주시거나, 해당 폴더 안에서 명령 창 실행 후 `npm start` 를 사용하여 주세요.

**Comment by lorlol701** [comment]
저 과정을 생략하는 게 `run.bat` 이므로, `Server`폴더 내에 있는 `run.bat`을 실행시켜 주시는 것이 편리합니다.

**Comment by lorlol701** [comment]
1. `?ㅻ쪟: "main" ?대쫫???곗씠?곕쿋?댁뒪???대? ?덉쓬` : main 데이터베이스가 이미 존재합니다. 해당 과정을 건너 뛰어 보세요.
2. `psql -U "postgres" -d "main" -f "(SQL 파일 경로)"` 명령어에서의 SQL 파일 경로는 끄투 파일 내의 db.sql의 경로 입니다. 예 : `"C:\Users\testUser\Desktop\KKuTu-master\db.sql"`
3. `npm start` 사용 시 `Server` 폴더 내애서 사용해야 합니다. 되도록 `run.bat`을 실행하여 주세요.

**Comment by houlday** [comment]
이건 리드미에서 보셔서 아실텐데
global.inc.json을 -> global.json으로 바꾸고
그 파일을 들어가셔서 pass에 자신이 postgresql에 지정한 비밀번호를 넣어야합니다.

**Comment by lorlol701** [comment]
저분에게서 발생한 오류는 그것과는 관련이 없습니다.

**Comment by lorlol701** [comment]
@houlday PASS가 아니고 PG_PASSWORD 입니다.

**Comment by cukiecat** [comment]
{
	"ADMIN": [ "Input admin id here" ],
	"MAIN_PORTS": [ 8080 ],
	"KKUTUHOT_PATH": "/kkutu/data/kkutuhot.json",
	"PASS":"Your password for management Here",
	"PG_USER": "postgres",
	"PG_PASSWORD": "여기에 postgre SQL 비번 들어감",
	"PG_PORT": 5432,
	"PG_DATABASE": "main",
	"GOOGLE_RECAPTCHA_TO_GUEST": false,
	"GOOGLE_RECAPTCHA_TO_USER": false,
	"GOOGLE_RECAPTCHA_SITE_KEY": "Your Google Recaptcha site key Here",
	"GOOGLE_RECAPTCHA_SECRET_KEY": "Your Google Recaptcha secret key Here",
	"IS_SECURED": false,
	"SSL_OPTIONS": {
		"PRIVKEY": "Your SSL Private Key Here",
		"CERT": "Your SSL Certificate Here",
		"CA": "Your SSL CA-Bundle Here",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": false
	}
}
그럼 여기서 어덯게 하면 되죠
죄송해요 컴퓨터를 게속 하지를 못해서 늦었네요

**Comment by cukiecat** [comment]
근데 서버가 열렸네요 run.bat 하기 전에 readme.md 보니까 명령 프롬포트에 grunt 설치를 안했더라구요
postgre 비번은 넣었고요. 근데 에러가 뜨네여 허헣
환영합니다.
[2019-08-28 20:42:59] &lt;&lt; KKuTu Server:8496 >>
[2019-08-28 20:42:59] &lt;&lt; KKuTu Web >>
[2019-08-28 20:43:00] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-08-28 20:43:00] Run with no-redis mode. [2019-08-28 20:43:00] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-08-28 20:43:00] Run with no-redis mode.
TypeError: OAuth2Strategy requires a clientID option at Strategy.OAuth2Strategy (c:\Bitnami\wampstack-7.3.5-0\apache2\htdocs\KKuTu-master\Server\lib\node_modules\passport-oauth2\lib\strategy.js:82:34) at new Strategy (c:\Bitnami\wampstack-7.3.5-0\apache2\htdocs\KKuTu-master\Server\lib\node_modules\passport-facebook\lib\strategy.js:54:18) at glob.then (c:\Bitnami\wampstack-7.3.5-0\apache2\htdocs\KKuTu-master\Server\lib\Web\routes\login.js:75:26)
[2019-08-28 20:43:01] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080 [2019-08-28 20:43:01] Game server #1 closed: 1006
[2019-08-28 20:43:01] DB is ready. [2019-08-28 20:43:01] Master DB is ready.
[2019-08-28 20:43:02] Error when querying: UPDATE users SET "server"='' WHERE "server"='0' [2019-08-28 20:43:02] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2019-08-28 20:43:02] Context: error: "users" 이름의 릴레이션(relation)이 없습니다 [2019-08-28 20:43:02] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2019-08-28 20:43:02] Error when querying: SELECT * FROM kkutu_shop WHERE TRUE [2019-08-28 20:43:02] Context: error: "kkutu_shop" 이름의 릴레이션(relation)이 없습니다
[2019-08-28 20:43:02] Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 [2019-08-28 20:43:02] Run with no-redis mode.
[2019-08-28 20:43:02] DB is ready.
[2019-08-28 20:43:02] Error when querying: SELECT * FROM kkutu_shop_desc WHERE TRUE [2019-08-28 20:43:02] Context: error: "kkutu_shop_desc" 이름의 릴레이션(relation)이 없습니다

어떻게 하면 될까요
그리고 redis는 어디서 깔면 될까요?
그리고 이 서버는 어디서 접속 가능한가요?

**Comment by lshqqytiger** [comment]
DB 구축부터 다시 하셔야 합니다.
Redis는 구글링하면 나옵니다.
해당 PC의 IP 주소를 통해 접속할 수 있습니다.

**Comment by cukiecat** [comment]
감사합니다!
DB는 DB.js에서 하면 되죠? 무었을 배우면 쉽게 할수 있을까요?

**Comment by lshqqytiger** [comment]
...DB.js는 별관련 없는 파일입니다..db.sql을 PostgreSQL DB에 넣으셔야죠

**Comment by cukiecat** [comment]
postgre가 다 영어로 되어 있고 복잡해서 잘 모르겠습니다 어디에 어떻게 넣어야 할까요

**Comment by houlday** [comment]
redis는 https://github.com/microsoftarchive/redis/releases 에서 깔아 주시면 됩니다

**Comment by lshqqytiger** [comment]
쪼리핑님 블로그 끄투 서버 구축 글에 postgreSQL DB 구축하는 방법 있습니다.

**Comment by lorlol701** [comment]
기본적인 서버 구축에 필요한 과정은 readme.md 와 쪼리핑님의 블로그에서 설명하고 있으니 해당 글을 참조해 주세요.

**Comment by cukiecat** [comment]
감사합니다 시간되면 해보겠습니다 아자아자!

**Comment by cukiecat** [comment]
이건 또 뭐죠
![에러 왜뜨지](https://user-images.githubusercontent.com/50296931/64061968-22697d00-cc1c-11e9-93b4-e1958824be00.png)

**Comment by lorlol701** [comment]
어떤 상황에서 발생하였나요? 정상적인 끄투 서버 구축 과정에서는 해당 오류가 날 상황이 없습니다.

**Comment by cukiecat** [comment]
redis를 끄투 마스터에넣은 후 cdm에 들어가 kkutu-master\server에 들어가 run.bat을 실행시켜서 창이 떳는데요 거기서 서버를 닫지 않은 채 창을 끈 후 다시 켰을때 일어난 일입니다. 계속 그럽니다

**Comment by cukiecat** [comment]
+
main.js의 icon: __dirname + "/../logo.ico"에서
main.js의 icon: __dirname + "/../샤투.jpg로 바꾸었습니다.

**Comment by lorlol701** [comment]
redis를 왜 끄투 마스터에 넣으셨죠

**Comment by cukiecat** [comment]
네

**Comment by lorlol701** [comment]
redis를 끄투 폴더에 넣었다는건 설치했다는 의미인가요 아니면 진짜로 파일을 그냥 넣으셨다는 의미인가요?

**Comment by cukiecat** [comment]
넣었습니다
파일 다 흩어져있어서 모아서 새로만든 폴더 Redis에 넣었습니다

**Comment by cukiecat** [comment]
![redis](https://user-images.githubusercontent.com/50296931/64063220-5056bd80-cc2c-11e9-9590-92284b0cff0e.png)

**Comment by lshqqytiger** [comment]
...Redis는 설치하면 자동으로 끄투와 연계됩니다..

**Comment by cukiecat** [comment]
그럼 어떻게 하죠

**Comment by cukiecat** [comment]
db는 
![문제가 많다](https://user-images.githubusercontent.com/50296931/64063611-69ae3880-cc31-11e9-858b-20a6cd9259a3.png)이렇게 됩니다 ㅠㅠ

**Comment by lorlol701** [comment]
Readme.md 및 개발자 블로그의 내용을 읽으면 충분히 해결될 만한 문제인데..?

**Comment by lorlol701** [comment]
그리고 아까도 말씀 드렸지만 명령어 내의 경로는 끄투 파일 내 db.sql 의 경로입니다. 제발 꼼꼼히 체크하면서 해주세요.

**Comment by lshqqytiger** [comment]
Redis는 그냥 **설치**만 해주시면 되고, DB는 윗분 말씀처럼 **끄투 파일 내 db.sql 파일** (`KKuTu-master\db.sql`) 을 입력하셔야 합니다.

**Comment by cukiecat** [comment]
네...

**Comment by lorlol701** [comment]
Readme.md 및 개발자 블로그에 설명되어 있는 과정을 꼼꼼이 읽지 않아 발생한 문제는 **이미 해결책이 있는** 문제이므로 무조건 도움을 바라기 보다는 스스로 해결해 나가 주세요.

**Comment by hatty163** [comment]
@cukiecat님을 어제 도와드렸습니다만, 이런식으로 하나하나 질문하여 나갈 경우에는 결국 남에게 의존해야 하는 서버가 되며, 서버를 겨우 열었더라도 기능 추가 등이 없어 오래 못갈겁니다.

저는 @cukiecat님이 먼저 Javascript과 Node의 기초, HTML/CSS 다루는 법을 어느 정도 익혀야만 서버를 오래 유지할 수 있을 거라 느낍니다.

본인 말론 Scratch/Entry 대회에서 상 받았다고 좋아하시는데, 이런 블럭 코딩은 말그대로 알고리슴 학습을 위한 거지, 실무에는 아무짝에도 쓸모 없습니다.

이점 유의해주십시요.

**Comment by lorlol701** [comment]
윗분의 말처럼 끄투 프리서버 운영을 위해선 어느 정도의 컴퓨터 지식을 가지고 있어야 합니다. 따라서 만약 끄투 서버를 구축하는데 큰 어려움을 느낀다면 이 점을 고려해 보아야 합니다.

**Comment by cukiecat** [comment]
네! 그럼 배우고 오겠습니다

**Comment by MegaKkutu** [comment]
#689
