### ISSUE TITLE
로그인 버튼 추가법

### ISSUE THREAD

**Issue by choroogyee** [JJoriping/KKuTu#547]
카카오 구글 등 로그인 버튼을 넣으려 하는데 어떻게 해야하나요?

**Comment by lshqqytiger** [comment]
ClientID와 ClientSecret을 auth.json에 알맞게 기입하시면 auth_~~~.js 파일들이 정상이라면 서버 재부팅 후 로그인 버튼이 추가됩니다.

**Comment by choroogyee** [comment]
제말은 그게 아니라 로그인버튼 이미지를 넣으려 합니다

**Comment by lorlol701** [comment]
Ishqqytiger님이 설명하신 과정을 거치면 로그인 버튼이 생성됩니다. 다만 `로그인 이미지` 라는게 무엇을 의미하는 건지 잘 모르겠네요.

**Comment by choroogyee** [comment]
소셜 네트워크 로그인 이미지 말하는겁니다 
![image](https://user-images.githubusercontent.com/47732670/63583953-f4aa8580-c5d6-11e9-9d5e-56a8becf5d6b.png) 이것처럼요

**Comment by lshqqytiger** [comment]
login.pug와 auth_kakao.js를 수정하고 해당 이미지 파일을 img 폴더에 넣으시면 됩니다.

**Comment by choroogyee** [comment]
감사합니다

**Comment by choroogyee** [comment]
auth_kakao.js를 어떻게 수정해야 하나요?

**Comment by dalbodeule** [comment]
현재 로그인 버튼을 이미지로 덮어씌우는 기능은 제공되고 있지 않습니다만, 이미지와 유사한 폼으로 CSS를 적용할 수 있도록 PR이 제공되고 있습니다. #251 을 확인해주세요.

추가적으로 이미지를 사용하도록 하는 옵션도 고려해 보겠습니다.
