### ISSUE TITLE
ssl 인증서 적용법?

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#548]
![wuierhfiruwef](https://user-images.githubusercontent.com/53849587/63646464-36117100-c74e-11e9-821b-000fc0b339e4.PNG)
사진과 같이 인증서가 있습니다
어디에 어떤 경로/파일를 입력해야하나요?

**Comment by lshqqytiger** [comment]
PRIVKEY: 프라이베이트 키 (private.key)
CERT: 인증서 파일
CA: 인증서 발급 기관의 인증서 파일

**Comment by spnia** [comment]
win-acme v1.9.11.2 로 let's encrypt 로 받았습니다.

**Comment by spnia** [comment]
.crt는 없고 ~-crt.der 이런 파일만 있네요

**Comment by lshqqytiger** [comment]
프로그램을 사용하는 것보다는 웹사이트에서 발급받는 것이 더 편리합니다.

도메인-crt.pem: 인증서 파일 (CERT)
도메인-key.pem: 프라이베이트 키 (PRIVKEY)
ca-도메인-crt.pem: 인증서 발급 기관의 인증서 파일 (CA)

**Comment by spnia** [comment]
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P i
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
n JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
G: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:798 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\trt
werfg\KKuTu-master\Server\lib\sub\global.json: Unexpected token P in JSON at position 536 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:795:27) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3) at Module.require (internal/modules/cjs/loader.js:690:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\trtwerfg\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:776:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
Worker 2064 died
W: CLOSED WITH CODE 0

위와 같은 오류가 뜹니다

**Comment by spnia** [comment]
인증서 경로가 따로 있나요

**Comment by lshqqytiger** [comment]
문법 오류입니다.
