### ISSUE TITLE
lang\eng_US.json 파일을 수정하는데 오류가 발생하네요

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#55]
개인적인 문제이긴 하지만, 아래에서 위파일의 어느부분에 구문오류가 나는 지 모르겠습니다. 알려주시면 감사드리겠습니다.

module.js:590 throw err; ^ SyntaxError: C:\Users\이창순\Desktop\KKuTu-master\Server\lib\Web\lang\en_US.json: Unexpected token O in JSON at position 10280 at Object.parse (native) at Object.Module._extensions..json (module.js:587:27) at Module.load (module.js:487:32) at tryModuleLoad (module.js:446:12) at Function.Module._load (module.js:438:3) at Module.require (module.js:497:17) at require (internal/module.js:20:19) at Object. (C:\Users\이창순\Desktop\KKuTu-master\Server\lib\sub\webinit.js:23:11) at Module._compile (module.js:570:32) at Object.Module._extensions..js (module.js:579:10)

**Comment by BasixKOR** [comment]
`master\Server\lib\Web\lang\en_US.json: Unexpected token O in JSON at position 10280 at Object.parse (native) at Object.Module._extensions..json`

에러 코드에 O라는 문자가 갑자기 튀어나와서 파싱에 실패했다고 친절하게도 알려주고 있습니다.
