### ISSUE TITLE
아이템 db를 어떻게 초기화하죠

### ISSUE THREAD

**Issue by Flug893** [JJoriping/KKuTu#552]
데이터베이스 충돌이라는데 아이템db를 어떻게 초기화 해야하나요.

**Comment by hatty163** [comment]
PGAdmin 등의 PostgreSQL 관리 도구를 이용해 보십시요.
해당 사항은 끄투 외적인 것으로 판단되며, 자세한 도움은 드리기 어렵습니다.

**Comment by Flug893** [comment]
감사합니다
