### ISSUE TITLE
상점 DB 다루기에 추가되어있는 아이템을 삭제하고 싶습니다.

### ISSUE THREAD

**Issue by Flug893** [JJoriping/KKuTu#554]
따로 다른 확장자로 덮어씌우는것이 아닌 삭제하고 싶습니다. 어떻게 해야하나요

**Comment by spnia** [comment]
PGAdmin 실행(postgreSQL 설치시 설치됩니다) -> postgreSQL 설치시 입력했던 비밀번호 입력 -> Databases/main/Schemas/public/Tables/kkutu_shop 의 테이블을 탐색 -> 해당 태이블을 오른쪽 마우스 버튼을 클릭하고 View/Edit Data > All Rows -> 필요없는 아이템을 삭제하기

인걸로 압니다

**Comment by Flug893** [comment]
해결되었습니다 감사합니다 ㅜㅜ
