### ISSUE TITLE
ERROR OCCURRED ON THE MASTER!

### ISSUE THREAD

**Issue by andjsrk** [JJoriping/KKuTu#556]
![image](https://user-images.githubusercontent.com/43586090/64704603-8b3cd900-d4e9-11e9-8bd5-edea41ad54cb.png)
위 사진과 같이 에러가 뜹니다.
원본 파일로 갈아끼워도 마찬가지입니다.
js 파일 관련해서 수정한 건 단 하나도 없습니다.

**Comment by junykkutu** [comment]
포트 8080 맞으신가요?

**Comment by junykkutu** [comment]
흠.. 이코드 때문인것 같네요... MASTER.JS에 이런 코드가 있던데...
File.appendFile("/jjolol/KKUTU_ERROR.log", text, function(res){
		JLog.error(`ERROR OCCURRED ON THE MASTER!`);
		console.log(text);
	});
});

**Comment by lorlol701** [comment]
그 코드는 오류를 남기는거지 오류를 발생시키는 원인이 아닙니다.

**Comment by lshqqytiger** [comment]
저 코드에 대해 오히려 고마워 해야합니다. 저 코드로 오류가 발생했다는 것을 알고 고칠 수 있으니까요.
