### ISSUE TITLE
데이터베이스 구축중 (설치경로)/(버전)/bin 디렉토리 이동 오류

### ISSUE THREAD

**Issue by samdasuEric** [JJoriping/KKuTu#557]
데이터베이스 9번 도중에 cd 명령어 이용해서 디렉토리 이동중에 경로를 찾을수 없다고ㅓ 합니다

**Comment by hatty163** [comment]
cd (설치경로)/(버전)/(bin)은 PostgreSQL 설치 경로를 의미합니다. Linux 운영체제는 설치하시면 PATH 설정도 해주니 아닐 테고, Windows 운영체제시면 기본 설치 경로는 C:\Program Files\PostgreSQL\[설치 버전]\bin입니다.
설치 버전에는 본인이 설치하신 버전(ex: 12,8,9,10)을 입력하여 이동하시면 됩니다.
아울러, 기본적인 프로그래밍 지식이 없는 상태에서의 끄투 서버 구축은 추천드리지 않습니다.
