### ISSUE TITLE
모드 만드는법 뭐에요?

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#558]
뭐 방만들기 누르면 매너,어인정등등 뜨잖아요.. 그거 체크표시 만드는법 뭐에요?

**Comment by junykkutu** [comment]
빨리 알려주세요

**Comment by lshqqytiger** [comment]
**여기는 그런 기본적인 것들의 구현 방법을 알려주는 곳이 아닙니다.**

`const.js`, `ko_KR.json` 가 기본적으로 수정해야 하는 것들이고,
`[게임모드].js (classic.js, daneo.js 등)` 등의 파일도 추가로 수정해야 하는 경우도 있습니다.
