### ISSUE TITLE
쪼롤에서 비트유끄투가 "확인 불가" 상태

### ISSUE THREAD

**Issue by minesna** [JJoriping/KKuTu#559]
(https://cdn.discordapp.com/attachments/516193651802505227/624248776441200660/unknown.png)

사진과 같이 끄투 프리서버 목록에서는 비트유끄투가 "확인 불가"라고 표시됩니다.
하지만 서버는 외부에서도 잘 접속됩니다
왜 오프라인인지 궁금합니다

**Comment by hatty163** [comment]
서버 주소는 http://veatyou.xyz로 등록되어 있는 것으로 보이나, 접속 시 https://veatyou.xyz로 이동됩니다. 쪼리핑님께 부탁하여 주소를 바꾸시거나, 새로 등록하시면 됩니다.

**Comment by minesna** [comment]
하지만 이전에도 그대로 사용해 왔습니다
갑자기 확인 불가가 표시되니.. 음

**Comment by hatty163** [comment]
HTTPS Redirect를 이전에는 적용하시지 않은 것으로 아는 바입니다.
가능한 해결 방법:
1. /servers 페이지 REDIRECT 비활성화 (조금만 만지심 해결됩니다.)
2. 주소 https://로 변경
3. HTTPS REDIRECT 비활성화
등등이 있겠네요.

**Comment by minesna** [comment]
그 전에도 ssl을 사용하였고 자동으로 리다이렉트되었습니다

**Comment by minesna** [comment]
혹시 모르니 테스트로 쪼롤에 서버를 하나 더 추가해보겠습니다

**Comment by minesna** [comment]
엇 실수로 닫았네요

**Comment by minesna** [comment]
1번으로 시도하여 '열림'으로 변경됐네요 답변 감사합니다
