### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by cho060303** [JJoriping/KKuTu#56]
네이버 소셜 로그인 API를 등록하려 합니다.
Callback  URL는 뭘로 써놓아야 하죠?

**Comment by ljs970624** [comment]
로그인 완료 후 메인 페이지로 리다이렉트 되기 때문에
끄투 메인 페이지 주소를 적어주시면 됩니다.

예) http://kkutu.io

**Comment by pkpai0926** [comment]
NAVER Developers의 내 애플리케이션 관리하는 곳 들어가서 본인이 설정한 Callback URL을 입력하면 됩니다. Callback URL 설정칸은 API 설정 탭에 이렇게 http://i.imgur.com/qZnNUWF.png 있습니다.

**Comment by cho060303** [comment]
감사합니다. 해결했습니다.
