### ISSUE TITLE
채널 포트 뭐죠

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#562]
저 고구마 까지 채널 만들고싶은대 고구마 포트가 뭔가요?

**Comment by andjsrk** [comment]
8170입니다.

**Comment by kdhkr** [comment]
https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81
제발 Docs 읽고 삽시다.. 이상한 이슈 올리지 마시고요.

**Comment by junykkutu** [comment]
> 8170입니다.
근데 왜 서버가 닫히죠

**Comment by lshqqytiger** [comment]
'서버가 닫힌다' 보다는 '~~ 이런 오류 (또는 에러) 가 발생하며 서버가 종료된다' 는 표현이 문제 해결에 더 도움이 되지 않을까요
