### ISSUE TITLE
도와주세요

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#567]
방만들기에 이름을 어떻게 바꾸죠? 얘들들어 방만들기를 집만들기로 바꾼다던지
그리고 방만들기 버튼에 사진은 어떻게 넣죠?
그리고 운영자만의 특별한 방은 어떻게 만드는지 좀 알려주세요..
그리고 끄투 폰트는 저작권 문제 없는지요.. (파일 가져온 그대로의 폰트)

**Comment by lshqqytiger** [comment]
이름 변경은 ko_KR을 수정하시면 됩니다.
사진 삽입은 css를 수정하시면 됩니다.
운영자 방은 따로 구현을 하셔야 합니다. (in_game_kkutu.min.js와 css 수정)

**Comment by junykkutu** [comment]
> **직접 코드를 찾아보시는게 훨씬 이해가 잘됩니다.**
> 
> 이름 변경은 ko_KR을 수정하시면 됩니다.
> 사진 삽입은 css를 수정하시면 됩니다.
> 운영자 방은 따로 구현을 하셔야 합니다. (in_game_kkutu.min.js와 css 수정)

이거 css는 무슨파일을 건드려야 돼나요?

**Comment by andjsrk** [comment]
사진 삽입은 in_kkutu.css같은 파일을 수정하시면 됩니다

**Comment by hatty163** [comment]
@lshqqytiger in_game_kkutu.min.js 파일을 직접 수정하시는 건 추천드리지 않습니다.
해당 파일은 `./Server/lib/Web/lib/`의 `head.js`, `ready.js`, `body.js`가 `grunt`가 실행될 때 합쳐지면서, Uglify된 파일입니다. 가능하면 위 3개의 파일 수정 후 `grunt`를 실행하는 것을 추천드리는 바입니다.

(ready.js가 body.js보다 더 우선 로드됩니다.)
