### ISSUE TITLE
제발 아무나 답변 바랍니다

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#569]
채널처럼 감자,냉이 이런거 말고 아얘 그냥 도매인 2개 하고싶어서 하는법이 무엇인지 물어봅니다. 해결이 다되면 이슈를 닫겠습니다.

**Comment by khjkr** [comment]
이곳은 끄투 서버의 오류나 문제를 해결하는 곳이지, 하는 방법 또는 구현법을 요구하는곳이 아닙니다. 이슈의 목적을 잘 파악하고 이슈를 달아주세요.

**Comment by lshqqytiger** [comment]
하나의 PC가 두개의 IP 주소를 가지는 방법 (두개의 도메인을 사용하는 방법) 은..제 상식 선에서는 힘든 것으로 알고 있습니다.
VM (가상 머신) 을 사용한다면 될 수도 있겠네요.

**Comment by khjkr** [comment]
@lshqqytiger 웹서버 / 게임서버 포트만 다르게 해도 충분히 가능한 부분입니다. (DB도 다르게)
굳이 아이피가 두개가 필요한 일이 아니죠.
