### ISSUE TITLE
광고 다는 방법

### ISSUE THREAD

**Issue by emptyme** [JJoriping/KKuTu#57]
광고 칸에 애드센스 광고를 달려는데 어느 파일에 코드를 넣어야하나요?

**Comment by JJoriping** [comment]
광고는 웹 클라이언트의 뷰(`./Server/lib/Web/views`)에서 pug 문법으로 설정할 수 있습니다. 각 뷰가 나타내고 있는 페이지는 웹 서버(`./Server/lib/Web/main.js`, `./Server/lib/Web/routes` 등)에서 확인해 주세요.
