### ISSUE TITLE
제발 도와주세요

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#570]
단어부나 유저관리부 이런거 표시 어떤거 수정하면 되나요?

**Comment by junykkutu** [comment]
아 그리고 운영자  추가 어떻게 해요? 운영자를 더 추가할때 쉼표 넣어야 하나요?

**Comment by lorlol701** [comment]
네에 쉼표 넣으셔야 됩니다

**Comment by junykkutu** [comment]
> 단어부나 유저관리부 이런거 표시 어떤거 수정하면 되나요?

이거 답변 해주세요 그리고 운영자 추가할때 아이디 써야하나요?

**Comment by lshqqytiger** [comment]
**제발 기본적인건 이슈로 올리지 맙시다. JSON 문법만 알아도 없을 이슈입니다.**

단어부, 유저관리부는 따로 구현을 해야하며, 끄투에 기본적으로 있는 기능이 아닙니다.
운영자 추가는 다음과 같이 합니다.

`"ADMIN": ["식별번호1", "식별번호2"]`
예) `"ADMIN": ["12345678", "12345679"]`

**Comment by junykkutu** [comment]
> **제발 기본적인건 이슈로 올리지 맙시다. JSON 문법만 알아도 없을 이슈입니다.**
> 
> 단어부, 유저관리부는 따로 구현을 해야하며, 끄투에 기본적으로 있는 기능이 아닙니다.
> 운영자 추가는 다음과 같이 합니다.
> 
> `"ADMIN": ["식별번호1", "식별번호2"],`
> 예) `"ADMIN": ["12345678", "12345679"],`

감사합니다. 이제부터는 안그럴께요....
