### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by g-jpg** [JJoriping/KKuTu#571]
제가 만든 끄투 서버에서 로그인을 할려고 하는데 로그인  방법을 선택하세요 라고 뜨는데 및엔 아무 것도 안 떠요

**Comment by lorlol701** [comment]
다른 OAuth 관련 이슈들을 보고 와주세요.

**Comment by g-jpg** [comment]
혹시 clientID 부분에는 뭐를 넣어야 되는지 알수 있을까요?

**Comment by g-jpg** [comment]
auth.json 에서요

**Comment by andjsrk** [comment]
구글 로그인을 예로 들겠습니다.
구글 로그인에서 OAuth를 만든 뒤, 설정을 하고 나면 clientID와 clientSecret이 발급됩니다.
그걸 auth.json에다기입하면 됩니다.
