### ISSUE TITLE
(구글) OAuth 2.0 로그인 실패관련

### ISSUE THREAD

**Issue by Ryzen72700** [JJoriping/KKuTu#574]
> **콘솔쪽**
`InternalOAuthError: failed to fetch user profile at C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28 at passBackControl (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9) at IncomingMessage.&lt;anonymous> (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7) at IncomingMessage.emit (events.js:203:15) at endReadableNT (_stream_readable.js:1129:12) at process._tickCallback (internal/process/next_tick.js:63:19)
InternalOAuthError: failed to fetch user profile at C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28 at passBackControl (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9) at IncomingMessage.&lt;anonymous> (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7) at IncomingMessage.emit (events.js:203:15) at endReadableNT (_stream_readable.js:1129:12) at process._tickCallback (internal/process/next_tick.js:63:19)`

> **웹페이지**
`InternalOAuthError: failed to fetch user profile
    at C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

현재 클라우드 플랫폼에서 id랑 secret쪽 다넣었으며 콜백은 **http://(사이트명).kro.kr/login/google/callback**으로 되어있습니다.
클라우드 플랫품 nternalOAuthError: failed to fetch user profile at C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28 at passBackControl (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9) at IncomingMessage.&lt;anonymous> (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7) at IncomingMessage.emit (events.js:203:15) at endReadableNT (_stream_readable.js:1129:12) at process._tickCallback (internal/process/next_tick.js:63:19)
InternalOAuthError: failed to fetch user profile at C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28 at passBackControl (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9) at IncomingMessage.&lt;anonymous> (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7) at IncomingMessage.emit (events.js:203:15) at endReadableNT (_stream_readable.js:1129:12) at process._tickCallback (internal/process/next_tick.js:63:19)`

> **웹페이지**
`InternalOAuthError: failed to fetch user profile
    at C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\user\Desktop\KKuTu-master\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1129:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)`

현재 클라우드 플랫폼에서 id랑 secret쪽 다넣었으며 콜백은 **http://(사이트명).kro.kr/login/google/callback**으로 되어있습니다.
클라우드 플랫품 리디렉션 url에도 똑같이 설정되어 있고요..

제 실력쪽에선 일단 해볼수 있는건 해봤는데.. 똑같이 오류떠서 로그인을 못하고있네요..
혹시 해결방법 있을까요?

+ 깃허브 이슈는 자주 못볼 가능성이 높습니다.

**Comment by lshqqytiger** [comment]
Issue #572 참고해주세요.

**Comment by Ryzen72700** [comment]
> Issue #572 참고해주세요.

해결했습니다
