### ISSUE TITLE
닉네임 변경기능 구현시 수정해야하는 파일?

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#577]
이슈와 맞지 않는다는건 알고있으나 영 몰라서 질문합니다.
현재 닉네임 변경기능을 구현하기 위해 login.js와 major.js만 수정한 상태입니다.
이 외에 수정해야 하는 파일이 있나요?

**Comment by lshqqytiger** [comment]
네 당연합니다.
kkutu.pug
kkutu.js
body.js (in_game_kkutu.min.js)
등을 수정해야 하며,
이 외에도 닉네임 저장을 위해 새로 컬럼도 만들어야 합니다.
