### ISSUE TITLE
서버를 한 컴퓨터에서 많이 돌리면 어떻게 되나요?

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#582]
아무리 이슈랑 안 맞아도 이건 완전히 몰라서 묻는 질문입니다.

**Comment by lorlol701** [comment]
이슈랑 안 맞는건 안 올리시는게 맞습니다.

**Comment by lshqqytiger** [comment]
이런 의미없는 이슈 (또는 질문) 는 안올리시는게 맞습니다. 이건 뭐 구현 방법 묻는거만큼이나 의미없는 질문이네요.
