### ISSUE TITLE
정체불명의 파워쉘 스크립트 파일들

### ISSUE THREAD

**Issue by TyphoonDANAS** [JJoriping/KKuTu#585]
![파워쉘](https://user-images.githubusercontent.com/49607272/68299936-18fb0600-00e0-11ea-83c9-35968b869c0d.PNG)
KKuTu-master-Server-lib에 위와 같은 정체불명의 파워쉘 스크립트 파일들이 있습니다.
이것이 뜬 이유로 게임 내에서 채팅이 쳐지지 않는 것 같은데, 해결 방법이 없을까요?
+파워쉘 스크립트 파일들의 내용은 모두 같습니다.

**Comment by lorlol701** [comment]
정상적인 KKuTu-Master 파일이라면 해당 경로에 `.ps1`의 확장자를 가진 해당 유형의 파일들은 **존재하지 않습니다.**

**Comment by TyphoonDANAS** [comment]
해결했으니 이슈 닫습니다.
