### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by g-jpg** [JJoriping/KKuTu#586]
그 관리자 사이트에서 관리를 할려는데 암호칸에 암호적는건 알겠는데 테이블은 뭐에요?

**Comment by lorlol701** [comment]
말 그대로 끄투 DB의 테이블 입니다.

**Comment by lshqqytiger** [comment]
단어를 추가 / 변경할 때 입력합니다.
한국어 DB: ko
영어 DB: en
등
