### ISSUE TITLE
서버 켜기 에러

### ISSUE THREAD

**Issue by shs3182ym** [JJoriping/KKuTu#587]
i
nternal/modules/cjs/loader.js:638 throw err; ^ Error: Cannot find module '../sub/global.json' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15) at Function.Module._load (internal/modules/cjs/loader.js:562:25) at Module.require (internal/modules/cjs/loader.js:692:17) at require (internal/modules/cjs/helpers.js:25:18) at Object.&lt;anonymous> (C:\Users\ZenithH500\Desktop\KKuTu\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:778:
30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10) at Module.load (internal/modules/cjs/loader.js:653:32) at tryModuleLoad (internal/modules/cjs/loader.js:593:12) at Function.Module._load (internal/modules/cjs/loader.js:585:3)
Worker 10864 died
W: CLOSED WITH CODE 0 에러

**Comment by lshqqytiger** [comment]
global.inc.json에 서버 정보를 넣고 global.json으로 이름을 바꿔주세요.
README에 나와있는 내용입니다.
