### ISSUE TITLE
서버 접속 관련 질문

### ISSUE THREAD

**Issue by g-jpg** [JJoriping/KKuTu#588]
죄송합니다. 제가 아는게 별로 없어 이슈를 여러번 남기게 되네요.

그 끄투 서버를 열었는데 저는 접속이 되는데 친구는 접속이 안된다네요. 80번 포트 열었는데도 왜 안되는거죠?

![1235캡처](https://user-images.githubusercontent.com/52651763/69227267-eb748900-0bc4-11ea-9c35-67fa38e766e9.PNG)

이렇게 설정 하는게 맞나요?

**Comment by lshqqytiger** [comment]
서버를 열었는데 외부에서 접속이 되지 않을 경우
1. 포트포워딩이 되지 않은 경우
2. PC 또는 공유기 방화벽에서 차단하는 경우

포트포워딩을 제대로 하셨는지 (80, 8080, 8492), 방화벽에서 차단하고 있지는 않은지 확인해주세요.

**Comment by khjkr** [comment]
@lshqqytiger 8492가 아니라 8496(8080 + 416)포트 입니다.

**Comment by lshqqytiger** [comment]
405번 이슈에는 8492라고 되어있어서 헷갈렸네요.
저는 포트포워딩 없이 여는지라..

**Comment by hatty163** [comment]
@lshqqytiger @khjkr 
보충 설명하자면
https://github.com/JJoriping/KKuTu/blob/27ee1ff9066e50798070cddf10996df418a28f6e/Server/lib/Game/cluster.js#L44
여기 보시면 `게임 서버 포트 + 416 + 슬레이브 번호 (0, 1, 2, 3 ...)`로 갑니다. `game-num-cpu` 값에 따라 포트가 추가됩니다.
