### ISSUE TITLE
run.bat를 실행 했을때 나오는 오류

### ISSUE THREAD

**Issue by soonsoo12345** [JJoriping/KKuTu#591]
![순수드](https://user-images.githubusercontent.com/34093441/69900573-88e76e00-13b8-11ea-9933-47e40a688924.PNG)
이런식으로 파일을 실행 시켰을때 오류가 뜨면서 실행이 되지 않습니다.

**Comment by andjsrk** [comment]
셋업을 다시한번 해보세요

**Comment by Carlo-Woo** [comment]
@soonsoo12345 해결하셨다면 이슈 닫아주세요.
