### ISSUE TITLE
사용자차단구체적으로알려주세요

### ISSUE THREAD

**Issue by norhu1130** [JJoriping/KKuTu#592]
#43 
이거 를봐도 구체적으로 어떻게하면돼는지안나와있습니다
그리고 벤도 명령어로만들수없을까요?

**Comment by lshqqytiger** [comment]
그냥 소스코드 뜯어보시면 다 나옵니다.
관페에 차단 항목에 `null, chat` 등의 값을 입력해주면, SQL로 값을 저장하여 반영하는 방식입니다.
`null: 차단 X
chat: 채팅 금지
그 외 아무 string 값: 차단 (차단 사유)`
차단 명령어의 경우 일반 차단과 IP 차단에 따라 구현 방식이 다릅니다.
일반 차단을 명령어로 구현하고 싶으시면 명령어를 입력하면 SQL에 그 값을 저장하도록 구현하면 되고, IP 차단을 명령어로 구현하고 싶으시면 여러가지 방법이 있습니다만 접속시 IP를 차단 기록 정보와 비교하여 일치하는 것이 있으면 접속을 차단하는 방식으로 구현하시면 되겠습니다.
