### ISSUE TITLE
Affero GPL

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#594]
Affero GPL 적용을 시행해야 한다고 쪼롤에서 봤습니다.
이 GPL 적용을 어떻게 해야하는지 몰라서 여기에 남깁니다.

**Comment by lshqqytiger** [comment]
제가 알기론 서버를 구성하는 모든 소스 코드 파일 (자체 개발 항목 포함) 을 업로드 해야하는 것으로 알고 있습니다. (저는 이미 모든 소스 코드 파일을 업로드하고 있습니다.)

**Comment by hatty163** [comment]
Affero GPL의 경우 기존 GPL의 조약과 더불어 다음 호 중 하나 이상 해당될 시 모든 소스를 공개해야 합니다.
1. 소프트웨어와 네트워크 통신이 일어나는 경우
1. 소프트웨어의 소스코드와 연결된 모든 경우
1. Affero GPL을 사용하는 소프트웨어를 일부 또는 전부 사용할 경우
즉, 실제 서버에서 사용하는 소스 코드와 이 소프트웨어와 직접적인 통신(POST 요청을 보내는 등의 경우, 단순 데이터베이스 값 수정은 해당되지 않음)을 하는 모든 소스 코드를 공개하셔야 합니다.
