### ISSUE TITLE
저작권 GPL에 대해 질문합니다!

### ISSUE THREAD

**Issue by junykkutu** [JJoriping/KKuTu#595]
표기 방식이 달라져서 GPL 표기를 다르게 해야 하나요?

**Comment by JJoriping** [comment]
안녕하세요. 2020년 1월 1일 끄투 소스 코드 라이선스를 AGPL로 바꾸는 과정에서 jjo.kr에 서버를 등록하기 위해 필요한 조치도 지금과 달라지게 됩니다. 그렇지만 1월 1일 이후, 본 레포지토리에 적용되는 새로운 소스 코드를 내려받아 사용하면 소스 코드를 직접 수정하지 않아도 서버 등록에 필요한 조치가 알아서 이루어지는 점 참고해 주세요.

**Comment by junykkutu** [comment]
감사합니다
