### ISSUE TITLE
jaqwi.js 에서 문제가 발생하여 채널이 재시작 됩니다.

### ISSUE THREAD

**Issue by Ganggroid** [JJoriping/KKuTu#6]
![image](https://cloud.githubusercontent.com/assets/5188404/22984798/e1940776-f3e9-11e6-8d8f-f99ed1311edc.png)
jaqwi.js 소스중에서 roundready 부분인 저 부분에서 $ans가 null로 잡혀 오류가 납니다.

**Comment by JJoriping** [comment]
`$ans`가 `null`인 경우 같은 파일의 `getAnswer(theme, nomean)` 함수에서 `R.go(null)`이 넘어가는 경우입니다. 현재 뜻 정보가 삭제된 관계로 해당 함수의 `$res[pick].mean.length >= 30`을 만족시키는 단어가 없기 때문에 이 구문을 삭제하시면 정상 작동할 것으로 생각됩니다.

**Comment by Ganggroid** [comment]
확인해보았습니다. getAnswer함수
![image](https://cloud.githubusercontent.com/assets/5188404/22991097/8f62072c-f3fe-11e6-8c7c-e1b7adf663ec.png)
이부분에서 마지막 R.go(null); 가 실행이 됩니다.
게임을 시작하기도 전에 getAnswer함수가 호출되는데요.
어떻게 하면 될까요

**Comment by Ganggroid** [comment]
확인을 해본 결과 args.push([ 'flag', { $lte: 7 } ]); 의 조건에 맞지 않은 디비가 나와서 그런것 같습니다.
부디 확인 부탁드립니다. (__)

**Comment by JJoriping** [comment]
아, 구문을 삭제하는게 아니라 구문을 항상 `true`로 만들어 주어야 정상 작동합니다. 관련 변경 사항을 수정하여 커밋했습니다. 제보 감사드립니다.
