### ISSUE TITLE
GUEST 사용자를 차단할 수 있는 방법에 대하여

### ISSUE THREAD

**Issue by horyu1234** [JJoriping/KKuTu#60]
감자 (GUEST 입장 가능) 서버에서 GUEST 의 고유 코드 (예: xjRy1BRYUYuS3OhFF1FPGHpDR6lkReF1)
를 차단할 수 있는 방법이 있는지 알고 싶습니다.

다른 방법으로는 냉이와 같이 회원 전용 서버를 이용하면 되지만, 혹시 몰라 질문을 올려봅니다..
감사합니다.

**Comment by JJoriping** [comment]
안녕하세요. 손님 계정의 식별자는 세션 단위로 구분을 하고 있고 데이터베이스를 이용하지 않습니다. 특정 손님 계정의 게임 이용을 차단하는 방법은 아직 구현되지 않았기 때문에 직접 프로세스 내부에서 IP 주소, 세션 식별자, 또는 클라이언트 환경 등을 이용하여 차단 모듈을 구성해야 합니다.

**Comment by return0927** [comment]
IP차단은 실제로 사용해보았는데 보통 게스트를 막을 경우가 도배나 테러로 인해 차단하는 경우가 대부분일텐데,
아이피 차단이 될걸 미리 알고 VPN을 사용하더라구요.

브라우저 정보나 세션 식별자 등을 이용하여 차단하는 방향이 좋을 듯 합니다.
