### ISSUE TITLE
jjo.kr/kkutu에 서버 등록안됨

### ISSUE THREAD

**Issue by wjdgustn** [JJoriping/KKuTu#600]
![image](https://user-images.githubusercontent.com/34962071/71083176-c11ee700-21d5-11ea-8029-80469d335c04.png)
소유권 파일을 서버에 넣어도 끄투 서버 등록이 되지 않습니다.

**Comment by lshqqytiger** [comment]
SSL 인증서 관련 문제가 발생했을 가능성이 있습니다.
저도 같은 문제를 겪어봤는데, 제 경우에는 인증 기관 인증서를 제대로 입력하지 않아서 발생한 문제였습니다.
직접 쪼리핑님께 문의해 보세요.

**Comment by wjdgustn** [comment]
![image](https://user-images.githubusercontent.com/34962071/71240340-37ddf080-234c-11ea-99c6-3ca9b0587919.png)
![image](https://user-images.githubusercontent.com/34962071/71240358-43c9b280-234c-11ea-80bc-1dd81ed54125.png)
![image](https://user-images.githubusercontent.com/34962071/71240372-49bf9380-234c-11ea-8e8f-0e6bab8cb13d.png)
@lshqqytiger 
수정해야 할 것이 있나요?

**Comment by lshqqytiger** [comment]
이건 본인 서버 인증서구요.
**인증 기관의 인증서**를 제대로 입력을 하셨는지 확인해 주세요.

`"IS_SECURED": true,
	"SSL_OPTIONS": {
		"PRIVKEY": "개인 키 (PRIVATE.KEY)",
		"CERT": "본인 서버 인증서",
		"CA": "**인증 기관의 인증서**",
		"PFX": "없어도됨 (무시)",
		"isPFX": false,
		"isCA": true
	}`

**Comment by wjdgustn** [comment]
![image](https://user-images.githubusercontent.com/34962071/71243140-fe5cb380-2352-11ea-98ec-3e2edbd8e50e.png)
SSL만 등록하고 isCA를 true 로 바꾸지 않아 생긴 문제였습니다...
감사합니다!
