### ISSUE TITLE
게임서버 연결안됨

### ISSUE THREAD

**Issue by issac4892** [JJoriping/KKuTu#602]
맨 처음에 로비 서버는 접속이 되는데 감자 서버가 초록색이 안뜨고 그냥 접속 인원도 -로 뜹니다. 그런데 ../?server=0 으로 접속하면 접속이 됩니다.

**Comment by issac4892** [comment]
kkutu.eq.kro.kr 가능한 많이 열어놓겠습니다

**Comment by hatty163** [comment]
웹 서버가 게임 서버보다 먼저 열려 생긴 문제로 추정됩니다.
Server 디렉토리 내에서 터미널(또는 명령 프롬포트)를 열어 `node lib/Game/cluster.js 0 1`로 게임 서버를 연 뒤, 터미널 하나를 추가로 열어 `node lib/Web/cluster.js 1`을 통하여 웹 서버를 열어주십시오.
아울러, 이슈가 발생할 때에는 우선 다른 이슈를 둘러봐 주시고, 문제가 지속되면 이슈를 열 때 서버 로그를 첨부해 주시면 더욱 빠른 시일 내 도와드릴 수 있습니다.
