### ISSUE TITLE
왜 쪼롤에서 끄투 등록이 안되는거죠?

### ISSUE THREAD

**Issue by ytseokggtv** [JJoriping/KKuTu#603]
![image](https://user-images.githubusercontent.com/35792532/71620632-35ae4880-2c0e-11ea-9224-95f7186a9dff.png)
왜 등록이 안되죠?
저작권 표기까지 다했는데 뭐가 문제일까요?
그리고 layout.pub이랑 m_layout.pub을 수정을 해야하는데 어느부분을 수정해야하나요? 끄투 서버 등록에 보니깐 그냥 상략 중략만 되어있어서 몰라서 그럽니다.

**Comment by lshqqytiger** [comment]
모든 저작권 내용 표시가 정상인데도 표시된다면 쪼리핑님께 개인적으로 문의해보셔야 하며, layout.pu**g**를 정확히 어떻게 수정하신다는건지 이해가 안됩니다. 어디에 수정하라고 나와있는지 어떤 내용인지 알려주세요.

**Comment by ytseokggtv** [comment]
https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0
여기에서 이해가 않가요

**Comment by lshqqytiger** [comment]
`div#Bottom
			block Bottom
			div.bottom-legal
				if locals.as_pc
					a(href='?')= L('AS_MOBILE')
				br
				a.bottom-contact(href='http://blog.jjo.kr/', target='_blank')= L('CREATOR')
				a.bottom-contact(href='mailto:op@jjo.kr', target='_blank') Contact op@jjo.kr
			div.bottom-legal!= L('GPL')
			+separator(10)`

이 부분인데, 기본적으로 이렇게 세팅되어 있어 수정할 부분이 없을텐데요.

**Comment by ytseokggtv** [comment]
정확히 표기했는데 안되요.

**Comment by lshqqytiger** [comment]
끄투코리아의 코드를 fork 했기 때문으로 보입니다.
(https://github.com/ytseokggtv/KKuTu)
오리지널 끄투의 코드를 fork 해주시기 바랍니다.
(끄투코리아의 코드 중 레벨 이미지는 저작권 제한이 걸려있어 사용할 수 없습니다.)

**Comment by ytseokggtv** [comment]
오리지널 끄투 코드를 fork 했는데 안됩니다. 똑같은 문구가 뜹니다.

**Comment by lshqqytiger** [comment]
서버 주소좀 알려주실 수 있나요 (디스코드 베프#4867)

**Comment by ytseokggtv** [comment]
YT석궁TV#8612 로 친추주세요. 글로 친추가 안되요

**Comment by lshqqytiger** [comment]
저도 그쪽으로 친추가 안됩니다.

**Comment by ytseokggtv** [comment]
https://discord.gg/t9bqjf 일로 들어와서 예기합시다
