### ISSUE TITLE
단어 주제 추가

### ISSUE THREAD

**Issue by ytseokggtv** [JJoriping/KKuTu#604]
단어 주제 추가 할라고 이미 닫힌 이슈를 보고 주재 추가 해봤는데 오류가 뜨네요.
좀더 재대로 된 주제 추가할수있는 방법 없나요?

**Comment by lshqqytiger** [comment]
무슨 오류가 뜨는지 몇번 이슈를 보신건지 알려주세요.

**Comment by ytseokggtv** [comment]
https://github.com/JJoriping/KKuTu/issues/222 이쪽에서 봤어요.
저가 언노원드를 추가할려니깐 오류나요
![image](https://user-images.githubusercontent.com/35792532/71637987-69cd4c00-2c96-11ea-9223-c69b2710e874.png)
이렇게게 떠요

**Comment by lshqqytiger** [comment]
문법 오류입니다. 직접 파일을 봐야 알 수 있습니다. 원격 가능하신가요

**Comment by ytseokggtv** [comment]
해결했는데 주제 표시가 않나네요.

**Comment by ytseokggtv** [comment]
ko_KR.json 도 건드렸는데 않뜨네요

**Comment by lshqqytiger** [comment]
서버 재부팅 해보세요.
const.js와 ko_KR.json은 켜질 때 불러오고 그뒤 수정사항은 재부팅해야 반영됩니다.

**Comment by ytseokggtv** [comment]
![image](https://user-images.githubusercontent.com/35792532/71638100-0ba26800-2c9a-11ea-8f69-97fe6cf3c460.png)
그냥 이렇게마만 떠요

**Comment by lshqqytiger** [comment]
#222는 **주제**를 추가하는 방법에 대한 이슈이고 언노운워드는 **특수 규칙**입니다.
위 이슈와는 관련이 없습니다.

**Comment by ytseokggtv** [comment]
특수규칙 어떻게 추가하죠?

**Comment by lshqqytiger** [comment]
const.js와 ko_KR.json, [해당 특수 규칙을 사용할 게임 유형].js, kkutu.js를 기본적으로 수정하셔야 하며, 일부 특수 규칙의 경우 in_game_kkutu 등을 수정해야 하는 경우도 있습니다.

**Comment by ytseokggtv** [comment]
음 꽤 복잡하겠군요....

**Comment by ytseokggtv** [comment]
저가 아직 구축한지 1일되서 아무것도 몰라서 특수 규칙을 만들수없네요.
따로 강의라던지 있으면 괜찮은데...

뭐 도움주셔서 감사합니다.

그리고 그나저나 주제 추가한뒤에 뜨지않는거는 무슨문제인지는 모르겠지만 최소한 저의 능력으로 해결해볼게요.
