### ISSUE TITLE
게임중 음악 안됨

### ISSUE THREAD

**Issue by Edward2854** [JJoriping/KKuTu#605]
게임 중의 음악을 다른걸로 바꿔서 했는데 몇초 이후로 부터는 안됩니다. 길이는 전이랑 똑같이 했는데... 안되는 이유 아시는 분 계실까요

**Comment by lshqqytiger** [comment]
게임 중 BGM은 하나만 있는게 아닙니다.
T0~T10.mp3 파일들을 전부 길이에 맞게 배속하여 수정해 주셔야 합니다.

**Comment by Edward2854** [comment]
T0~T10까지 다 길이에 맞게 수정을 했습니다
