### ISSUE TITLE
createdb

### ISSUE THREAD

**Issue by basjul-hooss** [JJoriping/KKuTu#606]
createdb 를 하고 있었는데

createdb: error: could not connect to database template1: 서버에 연결할 수 없음: Connection refused (0x0000274D/10061)
        "localhost" (::1) 호스트에 서버가 가동 중인지,
        5432 포트로 TCP/IP 연결이 가능한지 살펴보십시오.
서버에 연결할 수 없음: Connection refused (0x0000274D/10061)
        "localhost" (127.0.0.1) 호스트에 서버가 가동 중인지,
        5432 포트로 TCP/IP 연결이 가능한지 살펴보십시오.

이렇게 뜹니다

**Comment by g-jpg** [comment]
음.. 그건 아마도 postgresql 설치 하실때 포트를 이상하게 선택하셔서 일겁니다.
