### ISSUE TITLE
깃랩 로그인 오류 해결법 알려주세요

### ISSUE THREAD

**Issue by KAKAO24** [JJoriping/KKuTu#607]
SyntaxError: Unexpected end of JSON input at JSON.parse (&lt;anonymous>) at L:\KKuTu-master\node_modules\passport-gitlab\lib\strategy.js:31:23 at passBackControl (L:\KKuTu-master\node_modules\oauth\lib\oauth2.js:134:9) at IncomingMessage.&lt;anonymous> (L:\KKuTu-master\node_modules\oauth\lib\oauth2.js:157:7) at IncomingMessage.emit (events.js:215:7) at endReadableNT (_stream_readable.js:1184:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by andjsrk** [comment]
json 문법이 맞지 않습니다.
문법에 맞게 적어주세요.
