### ISSUE TITLE
로그인 안됨

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#611]
로그인 버튼을 눌렀는데 아무것도 안떠요

**Comment by lshqqytiger** [comment]
아무런 OAuth 설정을 안한 상태에서는 당연합니다.
auth.json에 ClientID와 ClientSecret 등을 입력했는지, 모든 OAuth Strategy가 모두 정상적으로 로드되었는지 확인해주세요.

**Comment by cuteduzzi** [comment]
흠..., 이런 작업은 처음이라 뭐를 입력해야 할지 모르겠어요.. ㅠ

**Comment by lshqqytiger** [comment]
사용하려는 OAuth Strategy (Naver, Discord 등) 의 개발자 DashBoard에 접속 후 애플리케이션을 생성하고 ClientID와 ClientSecret을 발급 받은 후 auth.json에 입력하시고 Callback URL 등 애플리케이션 설정을 하시면 됩니다.

**Comment by DevLunael** [comment]
추가로 사용 하지 않는 auth 방식의 파일은 auth.js.DISABLE 처럼 이름을 바꿔주시길 바랍니다.

**Comment by hatty163** [comment]
@DevLunael 이번에 패치되서 그러실 필요 없습니다 :)

**Comment by lshqqytiger** [comment]
이름을 안바꿔주면 서버 열 때 로그가 더 길게 뜰 뿐 오류가 나거나 하진 않습니다.
