### ISSUE TITLE
운영자 권한

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#612]
자신의 서버에서 운영자 권한을 어떻게 얻나요?

**Comment by lshqqytiger** [comment]
닫힌 이슈 먼저 찾아보세요.

#23 <- 똑같은 내용의 이슈입니다.

**Comment by cuteduzzi** [comment]
#23 여기서 휘장 얻는법 해봤는데 안되는데 쉬운 방법 없을까요?

**Comment by lshqqytiger** [comment]
저건 SQL 명령어를 사용하는 방법입니다.
좀 더 쉽게 하려면
관리자 페이지 (http://서버도메인또는IP/gwalli) 에서 하시면 됩니다.

**Comment by cuteduzzi** [comment]
error 뜹니다 ㅠ

**Comment by lshqqytiger** [comment]
JSON 문법에 맞도록 작성하셔야 합니다.

`{"아이템이름":갯수,"아이템이름":갯수}`

예를 들어 이름이 `b1_gm`인 아이템을 `1`개 지급하고 싶다면, 

`{"$WPC가":1,"b1_gm":1}`

이런 식으로 기존 아이템들 뒤에 콤마 (`,`) 를 붙이고 추가 하시면 됩니다.

**Comment by andjsrk** [comment]
{"error":400}이 뜬다면 관리자 권한이 제대로 들어오지 않았다는 뜻입니다.
