### ISSUE TITLE
Server Open 에러

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#613]
Chan @0 Msg #guest__1: {"type":"seek"}이 run.bat 키면 계속 뜨고 감자 서버가 꺼져있는 상태로 뜹니다. 혹시 포트포워딩에 오류가 있는지 질문드리고 싶어서 올립니다.

**Comment by andjsrk** [comment]
`Chan @0 Msg #guest__1: {"type":"seek"}`는 최근에 커밋된 도커 부분때문에 그런겁니다.
