### ISSUE TITLE
연결 불가

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#617]
다른 사람들이 서버에 못들어옵니다

**Comment by andjsrk** [comment]
정확히 어떻게 못 들어오는건가요?
1. 로딩 화면에서 1에서 더이상 로드가 안 되고 에러가 난다.
2. 게임 시작 버튼을 눌렀을 때 로딩 화면이 깨져 보인다.
3. 감자 서버가 꺼져있다.
4. 도메인으로 들어가지진 않지만 ip로는 들어가진다.
5. 그냥 ip로도 접속 자체가 안 된다.

**Comment by cuteduzzi** [comment]
도메인으로 연결했을때 웹페이지에 연결이 되지 않는다.

**Comment by andjsrk** [comment]
첫번째는 ip로는 접속이 되는지 확인 부탁드리고, ip로도 접속이 안 된다면 포트포워딩을 먼저 해주세요.
두번째는 https://github.com/JJoriping/KKuTu/issues/602 를 참고해보세요.

**Comment by cuteduzzi** [comment]
도메인으론 접속아 안되는데 아이피로 접속이 됍니다

**Comment by lshqqytiger** [comment]
도메인과 아이피가 제대로 연결이 되어있지 않은것 같습니다.

**Comment by cuteduzzi** [comment]
도메인으론 로비만 들어가지지만 아이피로는 서버까지 들어가집니다.

**Comment by andjsrk** [comment]
혹시 도메인을 알려주실 수 있나요?

**Comment by cuteduzzi** [comment]
ddutu.kro.kr

**Comment by cuteduzzi** [comment]
사람들이 하마치론 들어와집니다.

**Comment by cuteduzzi** [comment]
물론 내부아이피로 포트포워딩까지 했습니다.
