### ISSUE TITLE
다른 사람들이 하마치를 써야 서버에 들어가집니다.

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#621]
사람들이 하마치론 들어와집니다.
물론 내부아이피로 포트포워딩까지 했습니다.
내부 아이피로 포트포워딩을 해야 하나요?

**Comment by lshqqytiger** [comment]
포트포워딩을 할 때는 보통 내외부 아이피를 전부 적지 않나요..
![321](https://user-images.githubusercontent.com/39524005/73120458-6dac6f80-3fb1-11ea-8917-f255881eef65.PNG)

**Comment by cuteduzzi** [comment]
전 포워딩 아이피, 내부포트, 외부포트 뿐입니다.

**Comment by cuteduzzi** [comment]
해결 완료
