### ISSUE TITLE
방 생성 오류

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#622]
ERROR OCCURRED ON THE MASTER! :8080 [2020-1-26 18:23:17] ERROR: TypeError: Cannot read property 'url' of undefined TypeError: Cannot read property 'url' of undefined at WebSocketServer.&lt;anonymous> (H:\KKuTu-master\Server\lib\Game\master.js:289:32) at WebSocketServer.emit (events.js:203:13) at H:\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:88:16 at WebSocketServer.completeUpgrade (H:\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:270:5) at WebSocketServer.handleUpgrade (H:\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:197:10) at Server.&lt;anonymous> (H:\KKuTu-master\Server\lib\node_modules\ws\lib\WebSocketServer.js:87:14) at Server.emit (events.js:203:13) at onParserExecuteCommon (_http_server.js:605:14) at onParserExecute (_http_server.js:544:3)

**Comment by lshqqytiger** [comment]
master.js 파일 전부의 내용을 한번 봐야 해결이 가능하지 않을까 싶습니다.
