### ISSUE TITLE
끄투 등록이 안됨

### ISSUE THREAD

**Issue by wjdgustn** [JJoriping/KKuTu#623]
http://jjo.kr/kkutu 에 등록이 되지 않는데 인증서 문제인가요?
![image](https://user-images.githubusercontent.com/34962071/73267015-77391000-421b-11ea-8a83-72a482b92da9.png)
![image](https://user-images.githubusercontent.com/34962071/73267034-8455ff00-421b-11ea-8a4b-9658455daba1.png)

**Comment by lshqqytiger** [comment]
`인증 파일`이란, 해당 끄투 서버에 업로드 된 `kkutu-dHA6Ly****.html`과 같은 파일을 말합니다.

해당 인증 파일의 내용을 끄투 서버의 도메인과 같게 입력해 주신 후 다시 시도해주세요.

**Comment by wjdgustn** [comment]
**해결 완료**

**Comment by cuteduzzi** [comment]
ds
