### ISSUE TITLE
끄투 title 에서 [undefined] 제거하는 방법

### ISSUE THREAD

**Issue by trustypeople** [JJoriping/KKuTu#63]
끄투 language 배열, title 변수로 출력하는 부(예: html head title, 끄투 서버선택 화면)에 [undefined] 가 붙어있습니다. 혹시 제거하는 방법이나 그 변수를 설정하는 방법을 아시는 분들께 답변 부탁드립니다.

**Comment by pkpai0926** [comment]
끄투 폴더의 최상위 경로에 위치해 있는 `settings.json` 파일 속에서 값 수정이 가능합니다.

**Comment by trustypeople** [comment]
넵 확인결과 settings.json 의 server-name 은 웹서버에서는 'KKT_SV_NAME' 이라는 환경변수로 설정되어 들어감을 확인하였습니다.

쪼리핑님의 구동기가 아닌 PM2를 사용하여서 나타난 오류로 보이며, 오류해결이 완료되었으므로 Close 하겠습니다.
