### ISSUE TITLE
서버에 들어가지지 않아요

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#631]
답변해주시는 분들 항상 수고하십니다.
제가 할줄 아는게 없어서 자꾸 이슈를 올려서 죄송합니다.

1.서버 목록이 서버가 꺼져있다고 뜬다.
2.끄투서버에 들어가면 1에서 서버와의 연결이 끊깁니다. (#1006)
![pt1](https://user-images.githubusercontent.com/59755674/73910066-973e9280-48f1-11ea-9876-e8ece8fdcdab.PNG)
![pt2](https://user-images.githubusercontent.com/59755674/73910068-986fbf80-48f1-11ea-9b92-aed543c6bc8a.PNG)

사진을 첨부해드릴테니 봐주실수 있는분들은 부탁드립니다.

**Comment by lshqqytiger** [comment]
게임 서버가 열리지 않은 것 같습니다.

**Comment by cuteduzzi** [comment]
일단 서버 목록을 불러오는데까진 성공했습니다만 1006오류가 나면서 서버와 연결이 끊깁니다.

**Comment by pprcYT** [comment]
이전버전의 레포인데도 그래요...
