### ISSUE TITLE
사이트 하단부 저작자 표시

### ISSUE THREAD

**Issue by tjtdkr** [JJoriping/KKuTu#632]
![image](https://user-images.githubusercontent.com/30541362/73960411-31342880-494e-11ea-9d11-5c77dd111475.png)
본 이미지 글을 수정할 수 있는 파일 경로가 어디일까요?

**Comment by andjsrk** [comment]
[/Server/lib/Web/lang/ko_KR.json의 GPL부분](https://github.com/JJoriping/KKuTu/tree/master/Server/lib/Web/lang/ko_KR.json#L3)입니다.
