### ISSUE TITLE
이게 정상인가요

### ISSUE THREAD

**Issue by poomghangkkkutu** [JJoriping/KKuTu#635]
psql -U "postgres" -d "main" -f "db위치"
라고 썼는데 이렇게 뜹니다
SET
SET
SET
SET
SET
SET
SET
SET
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
SET
SET
SET
CREATE TABLE
ALTER TABLE
CREATE SEQUENCE
ALTER TABLE
ALTER SEQUENCE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
CREATE TABLE
ALTER TABLE
COMMENT
ALTER TABLE
COPY 462
 setval
--------
    468
(1개 행)

COPY 147023
COPY 0
COPY 431398
COPY 1496
COPY 1983
COPY 80
COPY 80
COPY 0
COPY 0
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE

C:\Program Files\PostgreSQL\9.6\bin>psql -U "postgres" -d "main" -f "D:\365kkutu\365\365\db.sql"
postgres 사용자의 암호:
SET
SET
SET
SET
SET
SET
SET
SET
CREATE EXTENSION
COMMENT
CREATE EXTENSION
COMMENT
SET
SET
SET
psql:D:/365kkutu/365/365/db.sql:75: ?ㅻ쪟:  "kkutu_cw_ko" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:89: ?ㅻ쪟:  "kkutu_cw_ko__id_seq" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
ALTER SEQUENCE
psql:D:/365kkutu/365/365/db.sql:112: ?ㅻ쪟:  "kkutu_en" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:126: ?ㅻ쪟:  "kkutu_injeong" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:142: ?ㅻ쪟:  "kkutu_ko" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:162: ?ㅻ쪟:  "kkutu_manner_en" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:208: ?ㅻ쪟:  "kkutu_manner_ko" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:225: ?ㅻ쪟:  "kkutu_shop" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:240: ?ㅻ쪟:  "kkutu_shop_desc" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:253: ?ㅻ쪟:  "session" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:274: ?ㅻ쪟:  "users" ?대쫫??由대젅?댁뀡(relation)???대? ?덉뒿?덈떎
ALTER TABLE
COMMENT
ALTER TABLE
psql:D:/365kkutu/365/365/db.sql:760: ?ㅻ쪟:  以묐났????媛믪씠 "kkutu_cw_ko_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세정보:  (_id)=(1) ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_cw_ko, line 1
 setval
--------
    468
(1개 행)

psql:D:/365kkutu/365/365/db.sql:147798: ?ㅻ쪟:  以묐났????媛믪씠 "kkutu_en_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세정보:  (_id)=(2) ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_en, line 1
COPY 0
psql:D:/365kkutu/365/365/db.sql:579212: ?ㅻ쪟:  以묐났????媛믪씠 "kkutu_kr_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세정보:  (_id)=(?먯퐳?쒗뙆由? ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_ko, line 1
psql:D:/365kkutu/365/365/db.sql:580716: ?ㅻ쪟:  以묐났????媛믪씠 "kkuut_manner_en_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세 정보:  (_id)=(.) ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_manner_en, line 1
psql:D:/365kkutu/365/365/db.sql:582707: ?ㅻ쪟:  以묐났????媛믪씠 "kkuut_manner_ko_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세 정보:  (_id)=(?? ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_manner_ko, line 1
psql:D:/365kkutu/365/365/db.sql:582795: ?ㅻ쪟:  以묐났????媛믪씠 "kkutu_shop_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세정보:  (_id)=(b2_fire) ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_shop, line 1
psql:D:/365kkutu/365/365/db.sql:582883: ?ㅻ쪟:  以묐났????媛믪씠 "kkutu_shop_desc_key" 怨좎쑀 ?쒖빟 議곌굔???꾨컲??상세 정보:  (_id)=(beardoll) ?ㅺ? ?대? ?덉뒿?덈떎.
구문:  COPY kkutu_shop_desc, line 1
COPY 0
COPY 0
psql:D:/365kkutu/365/365/db.sql:582907: ?ㅻ쪟:  "kkutu_cw_ko" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582915: ?ㅻ쪟:  "kkutu_en" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582923: ?ㅻ쪟:  "kkutu_injeong" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582931: ?ㅻ쪟:  "kkutu_ko" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582939: ?ㅻ쪟:  "kkutu_shop_desc" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582947: ?ㅻ쪟:  "kkutu_shop" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582955: ?ㅻ쪟:  "kkutu_manner_en" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582963: ?ㅻ쪟:  "kkutu_manner_ko" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582971: ?ㅻ쪟:  "session" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎
psql:D:/365kkutu/365/365/db.sql:582979: ?ㅻ쪟:  "users" ?뚯씠釉붿뿉???대? 湲곕낯?ㅺ? ?덉뒿?덈떎

**Comment by andjsrk** [comment]
> COPY 147023
COPY 0
COPY 431398
COPY 1496
COPY 1983
COPY 80
COPY 80
COPY 0
COPY 0
ALTER TABLE
(중략)
ALTER TABLE
468
(1개 행)

부분까진 정상인걸로 알고있습니다.
혹시 `psql -U "postgres" -d "main" -f "db.sql 위치"`를 여러번 쓰셨나요?

**Comment by 365kkutu** [comment]
@andjsrk 네

**Comment by andjsrk** [comment]
한 번만 쓰시면 됩니다. 뭐하러 두 번 쓰신거죠

**Comment by lshqqytiger** [comment]
여러번 입력하시면 오히려 꼬일 수도 있습니다.
