### ISSUE TITLE
gwalli에 맨 위에 있는거

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#636]
암호랑 테이블 칸이 있는데 그건 뭐하는 건가요?

**Comment by andjsrk** [comment]
암호는 global.json의 PASS 값을 넣으면 되고,
테이블은 단어 관련 작업을 할 때 사용됩니다.
한국어는 ko, 영어는 en을 넣습니다.

**Comment by lshqqytiger** [comment]
암호: `global.json`의 `PASS` 값. (관리 페이지 암호)
테이블: 단어 조작에만 해당. 조작할 단어 DB의 언어 설정.

예를 들어 `global.json`의 `PASS` 값을 `0000`으로 설정했고, 한국어 DB를 조작하려고 한다면,
암호는 `0000`, 테이블은 `ko`
영어 DB를 조작하려고 한다면,
암호는 `0000`, 테이블은 `en`
