### ISSUE TITLE
방 입장 버튼 텍스쳐를 바꾸려는데

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#637]
![dsa](https://user-images.githubusercontent.com/59755674/74215557-cc2d5980-4ce4-11ea-9e6f-ed65a4896367.PNG)
이거 텍스쳐가 어디에 있나요

**Comment by lshqqytiger** [comment]
직접 찾아보세요. 해당 부분은 CSS로 구현되어있습니다.
