### ISSUE TITLE
서버 증축을 하고 싶어요

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#638]
항상 수고가 많으십니다. 
다름이 아니라
서버를 이용자용 / GM 전용 / 대회용 서버 이렇게 구분하고 싶은데 어떻게 해야 하나요?
할수 있다면 서버를 껏다 켰다를 어떻게 하는지도 알려 주시면 감사하겠습니다.

**Comment by lshqqytiger** [comment]
#292 참고하시고
서버 수동 제어는 직접 구현하셔야 합니다.

**Comment by cuteduzzi** [comment]
어떻게 구현하나요?

**Comment by lshqqytiger** [comment]
파일 뜯어 고치셔야죠.
