### ISSUE TITLE
정말로 아무도 못 도와주시나요?

### ISSUE THREAD

**Issue by good777LUCKY** [JJoriping/KKuTu#639]
끄투는 정상 작동하고, db도 제데로 연결됩니다. 그런데, 게임 시작하고 봇이랑 대결 할때 마다 오류가 로그에 뜨면서, 게임이 멈춥니다. 플레이어가 입력하는 것은 잘 게임 진행되는데, 봇이 입력을 못하고 오류만 나옵니다.
```
Error when querying: SELECT * FROM kkutu_ko WHERE "_id" ~ E'^[\\uce74-\\ud0bf].{1}$' AND "type" ~ '(,|^)(0|1|3|7|8|11|9|16|15|17|2|18|20|26|19|INJEONG)(,|$)' LIMIT 20
Context: error: parallel worker failed to initialize

```
Error when querying: SELECT * FROM kkutu_ko WHERE "_id ............ 이런 오류나,
Context: error: parallel worker failed to initialize 이런 오류가 자꾸 나옵니다.

이런 상황때는 어떻게 합니까? DB문제입니까? 아니면 끄투 서버 문제입니까?

**Comment by lshqqytiger** [comment]
#3 을 참고하여 수정해 보시고 그래도 동일한 문제가 발생한다면 아마 끄투 DB에 문제가 있지 않나 싶습니다.

**Comment by good777LUCKY** [comment]
참고해봤는데, 안되네요.. 끄투 db 재설치해볼게요..

**Comment by good777LUCKY** [comment]
끄투 db 재설치해봐도 계속 비슷한 오류나오네요.. 도와주세요

**Comment by good777LUCKY** [comment]
게임에서 뭘 할때 마다 ```Context: error: parallel worker failed to initialize``` 오류가 뜹니다. 이 오류가 나면 게임 진행이 멈춥니다.
그리고 게임에서 봇 차례가 왔을때
```
Error when querying: SELECT * FROM kkutu_ko WHERE "_id" ~ E (생략함. 위에 오류랑 비슷함.)
Context: error: parallel worker failed to initialize
```
이런 오류가 뜨면서 게임 진행이 멈춥니다.
그런데 이상하게도 플레이어가 입력하고, 단어를 전송했을때는 아무런 DB 오류가 발생하지 않았습니다...

**Comment by good777LUCKY** [comment]
단어 대결에서는 이상하게도 모든 것이 정상 작동해요...

**Comment by lshqqytiger** [comment]
특이하네요. 지금껏 본 적 없는 사례입니다.

**Comment by good777LUCKY** [comment]
그러면 어떻게 해야 하죠?..

**Comment by andjsrk** [comment]
> #3 을 참고하여 수정해 보시고 그래도 동일한 문제가 발생한다면 아마 끄투 DB에 문제가 있지 않나 싶습니다.

뒷북이지만 해당 사례는 hit는 1 이상이지만 HIT_LIMIT이 0이어서 그런 것으로 보이므로 해당 사례는 다른 경우라고 판단됩니다.
이 사례는 봇이 단어를 입력할 때 **오류가** 납니다.

**Comment by JJoriping** [comment]
```
postgres=# create table foox as select generate_series(1, 10000) as a;
SELECT 10000
postgres=# alter table foox set (parallel_workers = 4);
ALTER TABLE
postgres=# set max_parallel_workers_per_gather = 4;
SET
postgres=# select count(*) from foox;
ERROR:  lost connection to parallel worker
postgres=# select count(*) from foox;
ERROR:  parallel worker failed to initialize
HINT:  More details may be available in the server log.
```
http://micronetinternational.com/index.pl/en/00/https/www.postgresql-archive.org/parallel-c-oblivion-of-worker-startup-failures-td5983820i20.html
PostgreSQL 설정 상 문제로 보입니다. 위 글에서 언급된 변수들인 `parallel_leader_participation`, `parallel_workers`, `max_parallel_workers_per_gather` 등을 적절히 설정해 시도해 보고, 그래도 문제가 생긴다면 다른 버전의 PostgreSQL을 설치하거나 MySQL로 옮겨야 하겠습니다.

**Comment by good777LUCKY** [comment]
다시 작동합니다! 감사합니다
