### ISSUE TITLE
쪼롤 등록이 안됩니다

### ISSUE THREAD

**Issue by Maple-kkutu** [JJoriping/KKuTu#640]
쪼롤 등록에 저작권 양식도 맞게 썼고 그랬는데 서버를 지우고 다시 할려고 하는데 저작권 양식이 안 맞아요...

**Comment by andjsrk** [comment]
[조건](https://github.com/JJoriping/KKuTu/wiki/내-서버-등록하기#저작권-관련-정보-양식)을 충족하는지 점검해보세요.

**Comment by norhu1130** [comment]
저도 오픈할때그랬는데 위키에서 참고하라는 소스복붙하고 수정하니 잘됩니다

**Comment by Carlo-Woo** [comment]
@norhu1130 해결하셨으면 이슈 닫아주세요.

**Comment by norhu1130** [comment]
예? 이거 제가연게아니라..

**Comment by Maple-kkutu** [comment]
네? 무슨 말씀이시죠?

**Comment by Carlo-Woo** [comment]
아 멘션 잘못했네요. @Maple-kkutu 이슈 닫아주세요
