### ISSUE TITLE
끄투 게임서버가 안열려요..

### ISSUE THREAD

**Issue by bit1208** [JJoriping/KKuTu#641]
끄투 게임 서버가 안열리고 어떤 게스트가 들어와서 계속 메시지를 입력하기만 합니다... 웹서버 먼저 열고 그다음 게임 서버를 열어도 게스트가 들어와서 메시지를 입력하는 현상은 없지만 게임 시작이 안들어가져요...

**Comment by bit1208** [comment]
리눅스로 해서 이렇게 되서 윈도우로도 해봤는데 똑같아요...

**Comment by andjsrk** [comment]
[**이 버전**](https://github.com/JJoriping/KKuTu/tree/5663dd47d53b05c6c16f1e0568eef5b5095e3ca2)의 레포지토리로 시도해보세요.

**Comment by bit1208** [comment]
성공했어요! 감사합니다^^
