### ISSUE TITLE
관리자 접속 질문

### ISSUE THREAD

**Issue by bit1208** [JJoriping/KKuTu#643]
리눅스로 끄투서버를 구축했는데 ssl 만들기가 어려워서 보안적용을 안했는데 api키를 만드려면 보안 적용을 해야 한다네요... 그래서 로그인 창을 못만들고있는데 단어를 수정하고 싶어요.. 게스트로도 관리자 페이지 들어가서 단어수정 가능한가요?

**Comment by bit1208** [comment]
어차피 친구랑 할 서버여서 아무나 관리자 페이지 접속해도 상관없어용...

**Comment by lshqqytiger** [comment]
페이스북만 SSL을 요구하고 다른 로그인 방식은 상관 없는 것으로 알고 있습니다.

게스트로 관리자 페이지 접근을 원하시면 직접 뜯어 고치셔야 합니다.

**Comment by bit1208** [comment]
감사합니다^^
