### ISSUE TITLE
SSL 오류

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#647]
SSL 파일경로 까지 입력했고 IS_SECURED를 true로 바꾸었습니다. 하지만 서버를 키면 이렇게 오류가 납니다.
![2](https://user-images.githubusercontent.com/42174930/75618354-48161580-5bb0-11ea-93c2-80cd980df1f6.PNG)
![3](https://user-images.githubusercontent.com/42174930/75618357-4a786f80-5bb0-11ea-9334-880d5357cc50.PNG)

**Comment by swoo5571** [comment]
오류가 주르륵 뜹니다

**Comment by lshqqytiger** [comment]
파일이 잘못된 것 같습니다.
[SSL For Free](https://www.sslforfree.com/)를 사용하여 다시 시도해보세요.

**Comment by swoo5571** [comment]
> 파일이 잘못된 것 같습니다.
> [SSL For Free](https://www.sslforfree.com/)를 사용하여 다시 시도해보세요.

해석할 수는 있으나 자꾸 확인할 수 없다며 오류가 뜹니다.(내도메인.한국 쓰고 있습니다.)

**Comment by lshqqytiger** [comment]
무슨 방법으로 진행하셨나요

**Comment by swoo5571** [comment]
> 무슨 방법으로 진행하셨나요

3번째 2번째 방법이요 첫번째는 그냥 계속 오류나서

**Comment by lshqqytiger** [comment]
두번째 방법으로 진행하시고 크롬으로 하셔야 합니다
1. 도메인 입력
2. Manual Verification 선택
3. Manually Verify Domain 클릭
4. Download File #1 다운로드
5. `Server\lib\Web\public\.well-known\acme-challenge`에 다운로드한 파일 붙여넣기
6. `http://도메인/.well-known/acme-challenge/~`에 접속
7. Download SSL Certificate 클릭
8. Download All SSL Certificate Files 클릭
9. 다운로드된 `sslforfree.zip` 파일 압축 해제
```CA: ca_bundle.crt
CERT: certificate.crt
PRIVKEY: private.key```

**Comment by swoo5571** [comment]
> 두번째 방법으로 진행하시고 크롬으로 하셔야 합니다
> 
> 1. 도메인 입력
> 2. Manual Verification 선택
> 3. Manually Verify Domain 클릭
> 4. Download File #1 다운로드
> 5. `Server\lib\Web\public\.well-known\acme-challenge`에 다운로드한 파일 붙여넣기
>    (폴더가 만들어지지 않을 경우 cmd 사용 `mkdir .well-known`)
> 6. `http://도메인/.well-known/acme-challenge/~`에 접속
> 7. Download SSL Certificate 클릭
> 8. Download All SSL Certificate Files 클릭
> 9. 다운로드된 `sslforfree.zip` 파일 압축 해제
> 
> ```
> CA: ca_bundle.crt
> CERT: certificate.crt
> PRIVKEY: private.key
> ```

6번 할 때 끄투 서버는 열어져 있어야하나요?

**Comment by lshqqytiger** [comment]
네 당연히 열려있어야 합니다.
베프#4867
