### ISSUE TITLE
use this if you want 오류

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#648]
main.js에서 101열에 use this if you want에서 //* 을 제거했더니 아래와 같은 오류가 뜹니다.
이거 해결법이 궁금한데 알려주실 수 있나요?

D:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\main.js:101 use this if you want ^^^^ SyntaxError: Unexpected token 'this' at wrapSafe (internal/modules/cjs/loader.js:1067:16) at Module._compile (internal/modules/cjs/loader.js:1115:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10) at Module.load (internal/modules/cjs/loader.js:1000:32) at Function.Module._load (internal/modules/cjs/loader.js:899:14) at Module.require (internal/modules/cjs/loader.js:1040:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (D:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\cluster.js:35:2) at Module._compile (internal/modules/cjs/loader.js:1151:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
Worker 15012 died
W: CLOSED WITH CODE 0
[2020-03-01 18:51:02] &lt;&lt; KKuTu Server:null >>
[2020-03-01 18:51:02] Master DB is ready.
[2020-03-01 18:51:02] DB is ready.

**Comment by wjdgustn** [comment]
혹시 use this if you want까지 같이 주석 푸셨나요?
use this if you want에 같이있는 코드만 풀고 use this if you want라는 문구는 주석처리하거나 지워주세요.
