### ISSUE TITLE
소유권 인증에서 자꾸 멈춥니다.

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#649]
쪼롤에 등록하기 위해 서버 이름, 서버주소, 비밀번호 다 입력했고, /server/lib/web/public에 html파일까지 생성했는데도 불구하고 등록이 되지 않습니다. html안에 서버주소도 입력했고, 조건에 맞게 파일 수정까지 하였습니다.

**Comment by lshqqytiger** [comment]
어떤 오류가 뜨는지 알아야하며, 쪼롤 등록 문제는 깃허브 이슈를 올리시는 것보다 쪼리핑님께 
DM 보내시는 것이 훨씬 처리가 빠릅니다.

**Comment by foxof4545** [comment]
쪼리핑님 디스코드 아이디가 뭐죠

**Comment by cuteduzzi** [comment]
JJoriping#7429
