### ISSUE TITLE
쪼롤 등록문제

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#650]
오랫동안 서버를 열지 않고 다시 열려고 하니 기존 도메인 서버에 문제가 발생했나 봅니다. 접속이 안되더군요
그래서 도메인 호스트를 바꿨어요. 그리고 이제 쪼롤에 다시 등록하려고 등록하려니 인증파일의 내용이 올바르지 않다고 나옵니다. kkutu-~~~~~~~~~.html 인증파일이 없음에도 말이죠. 어떤 문제인가요?

**Comment by lshqqytiger** [comment]
인증 파일의 내용은 등록할 서버의 도메인 주소여야 합니다.
등록할 서버 주소가 `https://example.com`이라면 인증 파일의 내용도 `https://example.com`이어야 합니다.

**Comment by spnia** [comment]
인증파일 자체가 없음에도 그 문제가 나타납니다.
