### ISSUE TITLE
쪼롤 등록문제

### ISSUE THREAD

**Issue by spnia** [JJoriping/KKuTu#651]
전 오류는 도메인을 바꿔서 해결했습니다.
쪼롤에 서버를 등록하려는데 '주소와 암호를 입력해 주세요' 메세지가 나옵니다
끄투 런처엔 확인차 ip? 접속기록이 잘 나오는데 자꾸 저 메세지가 나오네요

**Comment by salam1028** [comment]
쪼롤등록 문제는 쪼리핑님의 디스코드로 문의하시는게 더 빠를듯합니다.
#649 에서 쪼리핑님 디스코드 아이디가 있으니, 참고해주십시오

**Comment by spnia** [comment]
주소와 암호를 입력해주세요 메세지는 나타나지 않는데요
이젠 '서버의 소유권을 확인하기 위해~~~~~' 메세지가 나타납니다.
html 파일도 public 폴더 안에 잘 있고 html 파일에 작성된 도메인도 정확한데 말이죠

**Comment by spnia** [comment]
(아직 해결되지 않았습니다)
