### ISSUE TITLE
글로벌JSON에 문제가 있나봐요 빨리 도와주세요 ㅠㅠ

### ISSUE THREAD

**Issue by pobymin1115** [JJoriping/KKuTu#653]
{
	"ADMIN": [ "Input admin id here" ],
	"MAIN_PORTS": [ 8080 ],
	"GAME_SERVER_HOST": "127.0.0.2",
	"KKUTUHOT_PATH": "/kkutu/data/kkutuhot.json",
	"PASS":"----",
	"PG_HOST": "127.0.0.1",
	"PG_USER": "postgres",----",
	"PG_PORT": 5432,
	"PG_DATABASE": "main",
	"GOOGLE_RECAPTCHA_TO_GUEST": false,
	"GOOGLE_RECAPTCHA_TO_USER": false,
	"GOOGLE_RECAPTCHA_SITE_KEY": "Your Google Recaptcha site key Here",
	"GOOGLE_RECAPTCHA_SECRET_KEY": "Your Google Recaptcha secret key Here",
	"IS_SECURED": false,
	"SSL_OPTIONS": {
		"PRIVKEY": "Your SSL Private Key Here",
		"CERT": "Your SSL Certificate Here",
		"CA": "Your SSL CA-Bundle Here",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": false
	}
}

이렇게 썼는데 문법 문제? 같은게 떠요 ㅠㅠ ----는 비번 가린겁니다

**Comment by lshqqytiger** [comment]
`"PG_USER": "postgres",----",` 부분이 잘못되었습니다.

**Comment by Carlo-Woo** [comment]
해결하셨으면 이슈 닫아주시기 바랍니다.
