### ISSUE TITLE
끄투서버를만들었는대채널목록에회색으로뜨고게임시작이않됩니다

### ISSUE THREAD

**Issue by yeokyoomin** [JJoriping/KKuTu#655]

**Comment by lshqqytiger** [comment]
[#631](https://github.com/JJoriping/KKuTu/issues/631)을 참고해주세요.

**Comment by yeokyoomin** [comment]
감사합니다
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
