### ISSUE TITLE
api설정의 서비스 url을 어떻게 설정하나요?

### ISSUE THREAD

**Issue by kjbkjb1122** [JJoriping/KKuTu#66]
3개 파일을 다 설정하고도 안 됀다는 거는 저가 api가 잘못 설정한거 아니냐 생각이 됩니다.

서비스 url을 (저의 끄투 도메인)/login로 해야하나요?
지금 계속 로그인을 해결 못하네여;;;

**Comment by JJoriping** [comment]
이슈 #1 및 #22 를 참고해 보시고 서비스 URL은 도메인만 입력하시면 됩니다.
