### ISSUE TITLE
혹시 서버들 보면 그 노란색박스안의글씨(?) 같은거 어떻게만드나요?

### ISSUE THREAD

**Issue by lubudack** [JJoriping/KKuTu#664]
혹시 서버들 보면 그 노란색박스안의글씨(?) 같은거 어떻게만드나요?
그 맨 위에 뜨는데 누르면 사라지는 그거요

**Comment by lshqqytiger** [comment]
`global_notice.html` 안에 내용을 입력하면 자동으로 생깁니다.
