### ISSUE TITLE
상점 아이템 증발(원격 가능)

### ISSUE THREAD

**Issue by lubudack** [JJoriping/KKuTu#666]
언제부턴진 몰라도 상점 아이템이 전부 날라갔습니다.
새 db로 교체해봐도 똑같습니다.(아이템 추가한 적이 없음)
어떻게 하죠? 원격 가능합니다.

**Comment by lshqqytiger** [comment]
관페에서 `updatedAt` 값이 같은 아이템이 있는지 확인해주세요.
