### ISSUE TITLE
주제코드를 알려주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by kim-min** [JJoriping/KKuTu#67]
끄투 DB에 단어를 추가할 때, 주제에서 주제코드(?)를 입력하는데, 주제코드를 알지 못하여 질문드립니다.
만화/애니 같은 경우는 주제코드가 JAN 일때, 다른 코드 리스트들을 알려주시면 감사하겠습니다.

**Comment by JJoriping** [comment]
https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/lang/ko_KR.json#L353
이 곳에서 주제 코드에 대한 한국어 표현이 나타나 있으니 참고해 주세요.

**Comment by kim-min** [comment]
감사합니다!
