### ISSUE TITLE
기존에 있던 특수 규칙 말고 다른 특수 규칙 은 어떻게만드나요?

### ISSUE THREAD

**Issue by yeokyoomin** [JJoriping/KKuTu#671]

**Comment by lshqqytiger** [comment]
`const.js`, `ko_KR.json`을 수정하시고 나머지 기능들은 `[게임모드].js`, `in_game_kkutu.min.js`, `kkutu.js` 등을 통해 구현하시면 됩니다.

**Comment by yeokyoomin** [comment]
예

**Comment by yeokyoomin** [comment]
어렵겠군요

**Comment by yeokyoomin** [comment]
어떻게하는지모르겠네요

**Comment by lshqqytiger** [comment]
프로그래밍 (JavaScript, Node.js, jQuery) 을 기본적으로 배우고 하셔야죠

**Comment by yeokyoomin** [comment]
예

**Comment by jusnorare** [comment]
[게임모드].js 파일이 없어요
manner.js
man.js
다 없어요 살려주세요

**Comment by lshqqytiger** [comment]
manner (man)은 게임모드가 아닌 특수규칙입니다.

**Comment by jusnorare** [comment]
특수규칙 기능들을 수정할려하는데 어디서 수정해야하나요?

**Comment by lshqqytiger** [comment]
[#671.605768490](https://github.com/JJoriping/KKuTu/issues/671#issuecomment-605768490)

**Comment by jusnorare** [comment]
KKT가 한쿵쿵따인건 알겠는데 다른 게임 모드좀 알려주새요 ㅠㅠ

**Comment by lshqqytiger** [comment]
ko_KR.json 확인하세요.
#671 이슈에서 좀 벗어난 주제같습니다.
