### ISSUE TITLE
서버가많이있는대 하나의서버말고는 아무서버도 열리지않습니다

### ISSUE THREAD

**Issue by yeokyoomin** [JJoriping/KKuTu#672]

**Comment by lubudack** [comment]
혹시 방화벽과 (공유기 쓰시면) 포트포워딩에서 설정하신 포트 (예: 8080 8090이라면) 8080과 8090,8090+416(8506)을 전부 열으셨는지 확인해 주세요. 또한 포트는 global.json의 main_ports:의
[]사이에 8090, 8100같은 형식으로 있어야 합니다.

**Comment by yeokyoomin** [comment]
아 해결됬네요 갑자기
