### ISSUE TITLE
닉네임 변경 시스템 오류

### ISSUE THREAD

**Issue by lubudack** [JJoriping/KKuTu#673]
Pull requests에 있는 #596 을 적용하면 정확히 언제 이런 오류가 뜨는진 모르겠지만 이런 오류가 뜹니다. 또한 닉네임 변경이 작동되지도 않습니다. 이런 오류를 어떻게 고치는지, 나아가 닉네임 변경 #596 의 사용법도 알려주세요.
^ TypeError: Cannot read property 'kkutu' of undefined at MainDB.users.findOne.on (E:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\routes\login.js:37:13) at callback (E:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\collection.js:316:13) at Result.preCB (E:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (E:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\
query.js:144:10) at Connection.&lt;anonymous> (E:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:198:13) at Socket.&lt;anonymous> (E:\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:198:13) at addChunk (_stream_readable.js:288:12) at readableAddChunk (_stream_readable.js:269:11)

**Comment by pprcYT** [comment]
저도 그래요 nickname컬럼에 데이터타입을 text로 했지만요

**Comment by lshqqytiger** [comment]
실수로 올려진 PR인지라 문제가 있을 수 있습니다.
직접 문제 원인을 파악하며 수정하셔야 합니다.
