### ISSUE TITLE
상점이 이상해요 ㅠㅠ

### ISSUE THREAD

**Issue by Carlo-Woo** [JJoriping/KKuTu#674]
제가 관리자 페이지에서 아이템을 하나 추가하고 서버 재시작을 했는데
상점에 새로 만든 아이템 빼고 아무것도 없네요 ㅠㅠ
어떻게 하죠?

**Comment by Flug893** [comment]
해당 아이템을 지워보십시오.

**Comment by Carlo-Woo** [comment]
어떻게 지우는지 몰라요 ㅠ

**Comment by lshqqytiger** [comment]
pgAdmin을 사용하시면 됩니다.

**Comment by Carlo-Woo** [comment]
어떻게 하는건가요?

**Comment by lshqqytiger** [comment]
직접 찾아보시는게 더 낫습니다.
아니면 아예 상점 아이템 삭제 기능을 개발하세요.
(저는 자체개발해서 사용중입니다)

**Comment by Carlo-Woo** [comment]
개발을 못해서... 찾아볼게요(?)

**Comment by lshqqytiger** [comment]
https://www.tutorialspoint.com/postgresql/postgresql_delete_query.htm
참고하세요

**Comment by Carlo-Woo** [comment]
해보고는 있는데 저런 명령어(?)를 어디서 입력하는 건가요?

**Comment by lshqqytiger** [comment]
pgAdmin을 켜시고 상단 메뉴에 Tools -> Query Tool 들어가시면 됩니다.

**Comment by Carlo-Woo** [comment]
질문만 너무 많이 해서 Ishqqytiger님이 고생하실 것 같지만... 끄투 운영을 잘 못해서 그러는데
DB 연결은 어떻게 하나요?

**Comment by lshqqytiger** [comment]
Servers -> PostgreSQL -> Databases -> main 들어가고 비밀번호 입력하면 연결됩니다

**Comment by Carlo-Woo** [comment]
이것이 마지막 질문이 될 것 같네요. Servers가 pgAdmin 4 홈페이지에서 들어가는 건 아닐 것 같은데 찾아보니 KKuTu 폴더에도 없는것 같습니다. 어디서 찾는 건가요?

**Comment by lshqqytiger** [comment]
![321](https://user-images.githubusercontent.com/39524005/78864296-54767380-7a76-11ea-88e5-95e94930a7f0.PNG)

**Comment by Carlo-Woo** [comment]
https://www.tutorialspoint.com/postgresql/postgresql_delete_query.htm
이곳의 예인 COMPANY 를 아이템으로 바꾸면 되나요?
