### ISSUE TITLE
제 서버 주소를 바꿔 주실수 있나요?

### ISSUE THREAD

**Issue by cuteduzzi** [JJoriping/KKuTu#676]
안녕하세요 제가 서버 주소를 바꾸게 되면서 오류가 생겼습니다.
http://ddutu.kro.kr 에서 http://edutu.kro.kr 로 바꾸게 되었는데 바꾸어 주실수 있으신가요?

**Comment by lshqqytiger** [comment]
쪼리핑님께 DM으로 문의하시면 금방 바꿔주십니다.
