### ISSUE TITLE
게임 시간 늘리기

### ISSUE THREAD

**Issue by lubudack** [JJoriping/KKuTu#677]
혹시 게임 시간을 어떻게 늘리나요? 줄이는 방법을 통해서 늘리기에도 적용을 해봤는데 시간이 넓어진 듯 보이나 150초에서 시작합니다.

**Comment by pprcYT** [comment]
저도 많이 궁금합니다. (저도 그럼)

**Comment by pprcYT** [comment]
저도 #299 를 따라했거든요 ...

**Comment by hatty163** [comment]
[여기](https://github.com/JJoriping/KKuTu/search?q=15000&unscoped_q=15000)를 참고해주세요.
(15000ms = 150초)

**Comment by pprcYT** [comment]
15000을 600초가 최대먼 60000으로바꾸는거 맞나요?

**Comment by pprcYT** [comment]
15000을 30000으로 바꾼 후 grunt를 실행하고 리붓을했더니

[녹화_2020_08_02_20_18_06_34.zip](https://github.com/JJoriping/KKuTu/files/5012038/_2020_08_02_20_18_06_34.zip)
위의 파일같아요... 어쩌죠?
