### ISSUE TITLE
서버 이름 수정

### ISSUE THREAD

**Issue by Maple-kkutu** [JJoriping/KKuTu#678]
내 직원 끄투를 메이플끄투로 바꿀려고 하는데요 어떻게 이름을 바꾸죠?
그리고 로비 배경도 어떻게 바꾸죠?

**Comment by lshqqytiger** [comment]
`settings.json`을 수정하시면 됩니다.
`img\kkutu\gamebg.png` (첫 화면 및 인게임 배경)
`img\bg\def.png` (인게임 로비 배경)
