### ISSUE TITLE
게임 시작 버튼을 누르면 게임서버 로딩이 되지 않습니다

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#681]
제목 그대로 게임 시작 버튼을 누르면 그냥 아무 반응도 없는데 해결할 수 있는 방법이 없을까요?

**Comment by lshqqytiger** [comment]
게임 서버가 열리지 않은 것 같습니다.
[이전 버전의 레포지토리](https://github.com/JJoriping/KKuTu/tree/5663dd47d53b05c6c16f1e0568eef5b5095e3ca2)를 다운로드 한 후 서버를 열어보세요.
#629 를 참고하세요.

**Comment by norhu1130** [comment]
@JJoriping 해당 이슈를 오픈한 유저는 계정이 삭제되었습니다.
이슈를 닫아주시기 바랍니다.
