### ISSUE TITLE
서버 접속 주소를 도무지 못 찾겠습니다

### ISSUE THREAD

**Issue by DamDadyee** [JJoriping/KKuTu#683]
![흑흑 (1)](https://user-images.githubusercontent.com/63593724/79239856-031e1800-7eac-11ea-83bd-cda0be9a963f.PNG)
![흑흑 (2)](https://user-images.githubusercontent.com/63593724/79239860-03b6ae80-7eac-11ea-9993-5a37a2ddae8c.PNG)
![흑흑 (3)](https://user-images.githubusercontent.com/63593724/79239863-044f4500-7eac-11ea-981c-45412df2d35e.PNG)
![흑흑 (4)](https://user-images.githubusercontent.com/63593724/79239867-04e7db80-7eac-11ea-831c-17bbd887df7d.PNG)
![흑흑 (5)](https://user-images.githubusercontent.com/63593724/79239870-04e7db80-7eac-11ea-98aa-4415ea55ea6a.PNG)

살려주세요

**Comment by lshqqytiger** [comment]
서버가 제대로 열리지도 않았습니다..참고하세요
`폴더 ./Server/lib/sub에 oAuth 설정 파일(auth.json)과 전역 설정 파일(global.json)을 반드시 만들어 주세요. 본 레포지토리에는 각 파일의 양식이 들어가 있습니다.`

**Comment by DamDadyee** [comment]
global.json 은 있는데 auth.json 은 없고 inc 붙은 것만 있네요
auth.inc 는 따로 빼돌리지 않고 바로 inc만 삭제해도 상관 없나요?
