### ISSUE TITLE
방 구성이 잘못되었습니다. 오류

### ISSUE THREAD

**Issue by swoo5571** [JJoriping/KKuTu#685]
서버를 구축하고 포트포워딩까지 다했는데 방을 만들려고 했더니 방이 전혀 안만들어집니다. GM(어드민)만 방이 안 만들어지고, 일반 유저들만 방이 만들어집니다. 어느 부분을 수정해야 이 오류가 해결해야될지 모르겠습니다.

**Comment by Carlo-Woo** [comment]
global.json을 제외한 다른 파일을 건드리셨나요?
