### ISSUE TITLE
쪼롤 등록오류

### ISSUE THREAD

**Issue by joonroot** [JJoriping/KKuTu#688]
쪼롤에 등록을 하려할때 항상 다른이슈를 보고 해결하다 마지막것이 않돼서 이슈를 올립니다, 서버는 구동중이고.ko_kr,en_이 파일들 모두 수정하였지만,"페이지 또는 게임 페이지의 저작권 관련 내용 표시가 조건에 맞지 않습니다."이 오류가 계속 뜹니다 해결방법이 있나요?

**Comment by hatty163** [comment]
JJO.KR 서버 등록 관련 사항은 [여기](https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0)를 참고해주세요.

**Comment by joonroot** [comment]
GLOBAL": {
		"GPL": "<div style='color: #666;'>글자로 놀자! 끄투 온라인 Copyright (C) 2020년 joonroot(joonrootkkutu@gmail.com)<br>이 프로그램은 제품에 대한 어떠한 형태의 보증도 제공되지 않습니다.<br>이 프로그램은 자유 소프트웨어이며 배포 규정을 만족시키는 조건 아래 자유롭게 재배포할 수 있습니다.<br>이에 대한 자세한 사항은 본 프로그램의 구현을 담은 다음 레포지토리에서 확인하십시오: <a target='_blank' href='https://github.com/JJoriping/KKuTu'>https://github.com/JJoriping/KKuTu</a></div>", 현재 이렇게 수정하였는데 않됍니다

**Comment by lshqqytiger** [comment]
`GPL` 항목은 다음과 같은 형식을 띄어야 합니다.
```"GPL": "<div style='color: #666;'>글자로 놀자! BF끄투 Copyright (C) 2018 OPG 이승훈(<a target='_blank' href='mailto:bfk@sdbx.dev'>bfk@sdbx.dev</a>)<br>이 프로그램은 제품에 대한 어떠한 형태의 보증도 제공되지 않습니다.<br>이 프로그램은 자유 소프트웨어이며 배포 규정을 만족시키는 조건 아래 자유롭게 재배포할 수 있습니다.<br>이에 대한 자세한 사항은 본 프로그램의 구현을 담은 다음 레포지토리에서 확인하십시오: <a target='_blank' href='https://github.com/bfkkutu/KKuTu'>https://github.com/bfkkutu/KKuTu</a></div>",```

**Comment by hatty163** [comment]
2020**년**에서 '년'을 제거해주시기 바랍니다.

**Comment by hatty163** [comment]
또한, 레포지토리 주소는 본인의 Repo를 적으셔야 합니다.

**Comment by joonroot** [comment]
한번 해보겠습니다.답변주셔서 감사합니다

**Comment by joonroot** [comment]
해결하였습니다.감사합니다
