### ISSUE TITLE
언노운

### ISSUE THREAD

**Issue by joonroot** [JJoriping/KKuTu#690]
언노운모드를 추가하려합니다 어떻게 추가하고 어떠한 파일을 건드려야 하나요?

**Comment by Carlo-Woo** [comment]
#689 참고하시기 바랍니다.

**Comment by hatty163** [comment]
최근 무분별한 이슈가 급격히 늘고 있음에 따라, 몇가지를 안내해 드리기 위하여 작성합니다.
이슈를 작성하기 전에는 반드시 아래의 사항들을 확인해 주시기 바랍니다.

1. 이곳은 **끄투 서버 자체의 문제점**만을 기술하시기 바랍니다.
**다른 사람의 풀 리퀘스트(PR)나 소스 코드를 사용함에 따라 발생하는 문제는 그 곳에서 질문하시기 바랍니다.** 이곳은 끄투 본연의 소스 코드 혹은 머지(Merge)된 소스 코드에서 발생한 문제점에 한하여 도와드리고 있습니다.

2. 이곳은 본인이 개발하기를 원하는 **기능을 어떻게 구현하는지** 질문하는 곳이 아닙니다.
"특수 규칙을 만들고 싶은데 어떻게 만들어야 하나요?" 혹은 "닉네임 변경 기능은 어떻게 만드나요?"와 같은 질문은 삼가주시기 바랍니다. 아울러, 끄투 서버의 정상적인 운영을 위해서는 **충분한 개발 실력을 요구**합니다. 부족하다고 여겨질 경우, **다른 개발자를 구하거나 외주를 맡기시기 바랍니다.** 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.

3. 이슈 작성에 앞서 `README.md` 파일과 [위키](https://github.com/JJoriping/KKuTu/wiki) 및 **이미 존재하는 이슈**를 참고하시기 바랍니다.
현재 작성이 이루어지는 이슈 중 상당수는 이미 답변된 문제점이거나 README.md 또는 위키에 자세히 서술되어 있는 경우가 많습니다. 이러한 것들을 읽지 않고서 발생하는 문제에 관해서는 도와드리기 어렵습니다.

4. 마지막으로, 이슈 작성 시에는 **문제점들을 자세히 서술**해주시고, 높임말을 사용하시기 바랍니다.
이곳은 게임 고객센터가 아닙니다. 본인이 궁금하신 부분에 대한 명쾌한 답변을 받기 위해서는 높임말을 사용해주시기 바랍니다. 또한, 문제점들을 자세히 서술해 주시지 않을 경우 원인을 파악하기가 어려워 답변이 더욱 어려워집니다.

위 사항들을 잘 지켜 불필요한 이슈 생성이 없길 바랍니다.
감사합니다.

**Comment by joonroot** [comment]
무분별한 이슈츄가 죄송합니다.그점은 조심하겠습니다

**Comment by hatty163** [comment]
@joonroot 애초에 "언노운워드"는 "프로젝트 끄투"에서 개발한 특수 규칙이므로, 구현 방법과 관련된 문의는 [프로젝트 끄투 레포지토리](https://github.com/Preta-Crowz/KKuTu-Priv)에서 해주시는 것이 맞습니다.

이곳에서는 아무런 도움을 드릴 수 없습니다.

**Comment by lshqqytiger** [comment]
프로젝트 끄투 쪽에 문의하세요. 프로젝트 끄투 측이 개발한 것이라서 해당 게임 모드를 사용하고 있는 끄투 서버라도 프로젝트 끄투를 제외하고는 도와드리기 힘듭니다.

**Comment by hatty163** [comment]
이슈 닫아주시기 바랍니다.

**Comment by Carlo-Woo** [comment]
@joonroot 이슈 닫아주세요.
