### ISSUE TITLE
안녕하세요 지속적으로 서버 테러를 당하고 있씁니다

### ISSUE THREAD

**Issue by joonroot** [JJoriping/KKuTu#692]

**Comment by joonroot** [comment]
게스트를 막는법이있을까요?

**Comment by lshqqytiger** [comment]
게스트 관련 코드를 삭제하시거나 처리하세요.
BF끄투의 경우 이미 몇개월 전부터 게스트 기능을 사용하지 않고 있습니다.

**Comment by Javselver-node** [comment]
+ 레포지토리 소스에 있는 캡챠 기능으로 게스트를 제한하여금 어느정도 테러를 방지할 수 있습니다.

**Comment by lshqqytiger** [comment]
제 경우에는 캡챠도 뚫어버리는 테러를 당한 경험이 있어서 게스트를 아예 막았습니다.
