### ISSUE TITLE
끄투 오류입니다.

### ISSUE THREAD

**Issue by pprcYT** [JJoriping/KKuTu#696]
끄투 지금 최신버전이 서버구축을 하고나면 원랜 서버가 초록불이 있어야 하는데 회색으로 서버가 안열립니다. 구버전은 됩니다. 고쳐주십시오

**Comment by joonroot** [comment]
현재 레포는 게임시작이 않눌리는현상이 있습니다 구레포로 하시면 해결될것같습니다.

**Comment by hatty163** [comment]
현재 레프지토리에 포함된 서버 클라이언트를 사용할 경우 웹 서버가 게임 서버보다 먼저 열려 발생하는 문제로 보입니다. `./Server` 디렉토리에서
`node lib/Game/cluster.js 0 1` 명령어를 입력하여 게임 서버를 먼저 연 후,
다른 창에서 `node lib/Web/cluster.js 1` 명령어를 입력하여 웹 서버를 열어주시면 해결됩니다.
