### ISSUE TITLE
소셜 로그인에 대해 문의 드립니다.

### ISSUE THREAD

**Issue by yom21c1020** [JJoriping/KKuTu#7]
게임 실행 이슈는 node.js 업데이트(제 버전이 `4.x`더라구요;;)를 통해 해결했습니다. 감사드립니다!
다만 소셜 로그인에서 `./Server/lib/sub/jauth.js`를 수정하고 또 해야할 작업이 있나요? OAuth 인증용 키를 입력했습니다만 인증 요청이 제대로 가지 않네요. (`client_id=????????????????`)
또한 트위터 OAuth 인증 부분이 주석처리 되어있는 것 같은데, 활성화 하거나 추가해야 할 코드가 있는지 알려주시면 감사드리겠습니다.

**Comment by Ganggroid** [comment]
소셜로그인 하시려면 jauth.js, in_login.js 수정하셔야 합니다.

**Comment by yom21c1020** [comment]
수정을 한 것 같다고 했는데도 이러네요;;

**Comment by JJoriping** [comment]
이슈 #1 을 참고해 보세요.

**Comment by JJoriping** [comment]
트위터 oAuth 관련 사항은 전혀 구현되어 있지 않기 때문에 관련 연동 작업을 처음부터 다시 하셔야 합니다.

**Comment by yom21c1020** [comment]
앗 알겠습니다!

**Comment by yom21c1020** [comment]
웹 브라우저에서 소스를 뜯어보았습니다만, `./Server/lib/Web/lib/in_login.js`의 수정한 파일 내용이 적용되지 않고 원래 파일 그대로 적용이 되고 있습니다. 해결 방법이 있을까요..?
![2017-02-16_22-43-23_chrome](https://cloud.githubusercontent.com/assets/10514697/23023723/2cf9cb32-f49a-11e6-885c-3afd320f7154.png)

**Comment by JJoriping** [comment]
크롬 브라우저에서는 개발자 도구를 켜 놓은 상태에서 강력 새로고침(Shift+F5) 등을 지원하고 있으니 활용해 보세요. 캐시 문제가 아니라면 `./Server/lib/Web/lib/in_login.js`에서 수정한 사항을 `./Server/lib/grunt` 등으로 uglify하였는지 확인해 주세요. Uglify는 `./Server/lib` 디렉토리에서 명령어 `grunt default pack`을 입력하시면 됩니다.

**Comment by yom21c1020** [comment]
uglify를 하고 테스트를 하니 소스는 들어갔는데, 구글 로그인이 되지 않아 ./Server/lib/Web/views/login.pug의 google-signin-client_id를 수정했습니다. 구글 로그인 창이 뜨는데, 허용해도 실질적으로 로그인은 되지 않네요.
또한 리디렉션 URL을 서버 루트로 잡았는데, 이것도 요청을 받는 다른 경로가 있나요?

**Comment by JJoriping** [comment]
셧다운제 관련 구현을 지우면서 지우지 말아야 할 것까지 지워버렸네요. 관련 부분을 복구하여 커밋했습니다. 제보 감사드립니다.

**Comment by yom21c1020** [comment]
앗 수정 감사드립니다!

**Comment by yom21c1020** [comment]
업데이트 후 테스트를 해도 계속해서 `./Server/lib/Web/views/login.pug`의 Client ID를 가져오는 것 같습니다.
또한 `./Server/lib/Web/libs/in_login.js`의 `gapi.signin2.render(...)`에서 정의된 `scope`와도 다른 것 같습니다.(`openid`) 해결 방법이 있을까요?
![2017-02-17_13-51-08_chrome](https://cloud.githubusercontent.com/assets/10514697/23052941/ac71b5fe-f518-11e6-9cb7-add930ca811b.png)

**Comment by JJoriping** [comment]
`./Server/lib/Web/views/login.pug`의 클라이언트 ID를 갖고 오는 것이 맞습니다. 업데이트하실 때 oAuth 관련 설정이 모두 덮어쓰기되었을 가능성이 있으므로 한 번 확인해 보시고 이 이상은 저도 모르는 문제입니다. 참고로 구글 로그인 후 URL `/login/google`로 POST 통신하게 되어있으니(`./Server/lib/Web/main.js`) 이 쪽에서도 `console.log` 등으로 확인해 보세요.

**Comment by yom21c1020** [comment]
답변 감사드립니다! 삽질 해보도록 하겠습니다.
