### ISSUE TITLE
어디서 오류가 난건지 모르겠습니다.

### ISSUE THREAD

**Issue by Carlo-Woo** [JJoriping/KKuTu#700]
얼마전까지는 정상적으로 서버가 잘 열렸습니다. 그런데 갑자기 서버를 열어도 접속이 되지 않습니다. 어느 부분에서 문제가 난 것일까요?

**Comment by lshqqytiger** [comment]
portal에 접속이 되지 않는 것인지, 인게임에 접속이 되지 않는 것인지, 일렉트론에 에러 로그는 뜨는지 확인해보세요.

**Comment by Carlo-Woo** [comment]
에러 로그는 뜨지 않고 인게임에 접속은 아예 안됩니다.

**Comment by lshqqytiger** [comment]
불러오는 중 1..에서 멈추는 증상인가요

**Comment by Carlo-Woo** [comment]
아니요, 아예 '접속 시간 초과'라고 나옵니다

**Comment by lshqqytiger** [comment]
도메인에 연결된 IP와 서버가 열린 IP가 같은지 확인해보세요.

**Comment by Carlo-Woo** [comment]
저는 따로 그렇게 하지는 않고 영어 도메인 ( OOO.kro.kr ) 로 접속해서 그 방법이 되는지는 모르겠지만 해보겠습니다.

**Comment by lshqqytiger** [comment]
이거 설정 하셨나요
![1](https://user-images.githubusercontent.com/39524005/82977061-b46fac00-a01b-11ea-86b2-02d053c300cb.PNG)

**Comment by Carlo-Woo** [comment]
네 그렇게 했습니다.

**Comment by lshqqytiger** [comment]
외부 아이피로 하신거죠?

**Comment by Carlo-Woo** [comment]
맞습니다.
