### ISSUE TITLE
오류 1006

### ISSUE THREAD

**Issue by KafuChinoDesu** [JJoriping/KKuTu#702]
![image](https://user-images.githubusercontent.com/39993457/82735458-e7d0e300-9d5c-11ea-85d0-c1aeb7fba672.png)
![image](https://user-images.githubusercontent.com/39993457/82735463-f0c1b480-9d5c-11ea-8d2b-df076a4d7dd3.png)
![image](https://user-images.githubusercontent.com/39993457/82735470-fa4b1c80-9d5c-11ea-9584-205fc73f0c3d.jpeg)
설정 README대로 하였고 컨픽은 스샷에 나와있습니다. 다 보고 따라한건데도 문제가 생기네요. 당연하게도 서버에 접속도 안됩니다. Azure위에서 돌리고 포트도 열어놨는데 말이죠. 깃헙 이슈들도 겁색해 봤고 몇몇개 해보기도 했으나 해결이 되지 않습니다.

**Comment by hatty163** [comment]
당연하지만 게임 서버 먼저 열어주셔야 합니다.

**Comment by KafuChinoDesu** [comment]
> 당연하지만 게임 서버 먼저 열어주셔야 합니다.

먼저열고 한겁니다. GNU Screen써서 분리되어있을 뿐입니다.

**Comment by hatty163** [comment]
@KafuChinoDesu UNIX 기반 운영체제에서는 root 계정을 제외한 나머지 계정으로 1024 미만의 포트를 사용하실 수 없습니다. `sudo bash` 명령어를 사용하여 root 계정에서 실행하시거나, nginx 등의 웹 서버 소프트웨어로 리버스 프록싱 환경을 구축하는 것을 권장드립니다.

**Comment by KafuChinoDesu** [comment]
> @KafuChinoDesu UNIX 기반 운영체제에서는 root 계정을 제외한 나머지 계정으로 1024 미만의 포트를 사용하실 수 없습니다. `sudo bash` 명령어를 사용하여 root 계정에서 실행하시거나, nginx 등의 웹 서버 소프트웨어로 리버스 프록싱 환경을 구축하는 것을 권장드립니다.

*NIX 많이 쓴지라 그정돈 알고있고요 한가지 의문인건 게임 클러스터가 config한 포트가 아닌 다른 포트를 쓴다는 점입니다.

![image](https://user-images.githubusercontent.com/39993457/82862798-89258800-9f5b-11ea-9831-36ceb0acbb33.png)

![image](https://user-images.githubusercontent.com/39993457/82862811-8fb3ff80-9f5b-11ea-8c76-2aab55658ac2.jpeg)

여기서 볼수있듯이 root로도 동일증상 발생합니다

**Comment by hatty163** [comment]
@KafuChinoDesu `./sever-setup.bat`을 실행해 주시기 바랍니다.
배치 확장자로 되어 있지만 리눅스 환경에서도 정상적으로 실행이 가능하며, 단순히 `npm install`만 진행하였을 경우에는 일부 구성 요소들이 제대로 작동하지 않을 수 있습니다.

**Comment by KafuChinoDesu** [comment]
> @KafuChinoDesu `./sever-setup.bat`을 실행해 주시기 바랍니다.
> 
> 배치 확장자로 되어 있지만 리눅스 환경에서도 정상적으로 실행이 가능하며, 단순히 `npm install`만 진행하였을 경우에는 일부 구성 요소들이 제대로 작동하지 않을 수 있습니다.

README보고 다 했단내용 안보셨습니까? 그래도 혹시몰라서 한번 더 했지만 똑같습니다.

**Comment by hatty163** [comment]
> @hatty163 *NIX 많이 쓴지라 그정돈 알고있고요 한가지 의문인건 게임 클러스터가 config한 포트가 아닌 다른 포트를 쓴다는 점입니다.
@KafuChinoDesu 우선 끄투 게임 서버는 마스터 프로세스와 슬레이브 프로세스로 나뉘어져 있습니다.
`node ./lib/Game/cluster.js 0 1`에서 `0`은 게임 서버 번호 (인 게임 내 감자, 냉이 등으로 구분되는 게임 서버), `1`은 해당 게임 서버의 슬레이브 수를 뜻합니다.

만약 게임 서버 포트가 `9821`이고 슬레이브 수가 하나라면, `9821` 말고도 `9821+416` 포트를 슬레이브가 Listen합니다. 예를 들어, 슬레이브 수가 2개면 `9821+416+1` 포트도 함께 사용하며, 3개면 `9821+416`, `9821+416+1`, `9821+416+2`를 사용합니다. 이 슬레이브 포트는 게임 내에서 웹소켓 요청을 Listen하기 때문에 함께 열어주셔야 합니다.

**Comment by hatty163** [comment]
> README보고 다 했단내용 안보셨습니까? 그래도 혹시몰라서 한번 더 했지만 똑같습니다.
본인은 Azure 클라우드 플랫폼을 사용해본 적이 없어 답변이 정확하지 않을 수도 있습니다. 그래도 최선을 다하여 도와드리고 있으니 양해 부탁드립니다.
