### ISSUE TITLE
끄투 인게임에서 부관리자를 설정하려면

### ISSUE THREAD

**Issue by KAINNY5669** [JJoriping/KKuTu#703]
global.json에서 쉼표로 구분하여 작성하면 되는가요?
예) 관리자 식별번호 : 1234 부관리자 식별번호 : 5678

global.json

"ADMIN": [ "1234, 5678"]

**Comment by lshqqytiger** [comment]
[참고](https://github.com/JJoriping/KKuTu/wiki/S~global.json)

**Comment by KAINNY5669** [comment]
감사합니다
