### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by KakaoKK** [JJoriping/KKuTu#704]
![image](https://user-images.githubusercontent.com/49306402/83009406-ac326380-a051-11ea-8a3a-47f8ab26dfe7.png)
해결법좀 알려주세요

**Comment by norhu1130** [comment]
뭘할떄나는지요

**Comment by norhu1130** [comment]
주소에 www.이있다면 www.을지워주세요

**Comment by KakaoKK** [comment]
www 아닙니다

**Comment by KakaoKK** [comment]
서버로 접속 하면 저렇게 됍니다 다른사람은 돼는데 저만

**Comment by hatty163** [comment]
제공해주신 정보만 가지고는 어떠한 도움도 드리기 어렵습니다.
자신의 서버 주소, 서버 환경 등을 상세히 기술해주시고, 문제 상황을 자세히 설명해주시기 바랍니다.

**Comment by lshqqytiger** [comment]
localhost로도 접속해보시고 공유기 자체에서 막는건 아닌지 확인해보세요.

**Comment by KakaoKK** [comment]
IPTIME 공유기 입니다
localhost 로는 접속이 잘 됍니다

**Comment by Carlo-Woo** [comment]
윈도 방화벽 설정도 다 하셨나요?
