### ISSUE TITLE
닉네임 변경 시스템을 하기 위해 건드리다가

### ISSUE THREAD

**Issue by KAINNY5669** [JJoriping/KKuTu#707]
https://youtu.be/qRgniGAMyCE
버그는 이 모양입니다. 무슨 파일을 수정해야 할까요ㅠㅠ

**Comment by lshqqytiger** [comment]
닉네임 변경 시스템 때문에 발생하는 것 같지는 않아보이는데요..

**Comment by hatty163** [comment]
자세한 설명도 없을 뿐더러, 소스 코드나 에러 등의 자료도 전무하여 도와드릴 수 없습니다.
#689 참고 바랍니다. 이곳에서는 끄투 서버 자체의 문제점만을 기술하시기 바랍니다.

**Comment by KAINNY5669** [comment]
끄투 이슈를 분별하게 올린 점 반성하겠습니다. 앞으로 이슈를 작성할 때에는 신중히 판단 후 이슈 올리겠습니다.
