### ISSUE TITLE
서버 증설

### ISSUE THREAD

**Issue by Carlo-Woo** [JJoriping/KKuTu#708]
#292 번 이슈를 봤지만 저로서는 어떻게 하는지 잘 모르겠습니다. 자세한 설명 부탁드립니다.

**Comment by hatty163** [comment]
[해당 위키 페이지](https://github.com/JJoriping/KKuTu/wiki/%ED%81%B4%EB%9F%AC%EC%8A%A4%ED%84%B0%EB%A7%81)를 참고해주세요.

**Comment by Carlo-Woo** [comment]
settings.json의 `game-num-inst` 값을 바꾸면 된다는 건가요?

**Comment by hatty163** [comment]
@Carlo-Woo `game-num-inst` 값을 변경하신 후, global.json의 `MAIN_PORTS`에도 인스턴스 값 만큼의 포트를 추가해주셔야 합니다.

만약 `game-num-cpu`:1, `game-num-inst`: 2, `MAIN_PORTS`: 8080, 8090일 경우
`8080`, `8090`, `8496`, `8506` 포트를 개방해주시면 됩니다.

**Comment by Carlo-Woo** [comment]
그러면 윈도 방화벽 설정에서도 8506 포트 설정을 '허용'으로 바꿔야 하는 것 아닌가요?

**Comment by lshqqytiger** [comment]
아마 포트포워딩 해주시고 인바운드 규칙도 추가하셔야 할 것 같습니다.

**Comment by Carlo-Woo** [comment]
인바운드 규칙에서 기존에 만들어 뒀던 규칙을 수정하면 되겠죠?

**Comment by Carlo-Woo** [comment]
제 서버 컴퓨터가 좋지 않아서 서버를 증설해봤자 CPU만 더 쓰기 때문에(?) 이슈 닫습니다.
