### ISSUE TITLE
포탈 underfined

### ISSUE THREAD

**Issue by norhu1130** [JJoriping/KKuTu#709]
안녕하세요? 사소한문제지만 올려봅니다.
일단 콘솔에 뜨는버그나문제는없습니다.
현재 소스코드는 저의github에있습니다.
그 사이트접속시 탭에 [underfined] (설정한title)이뜹니다.
underfined를 어떻게없앨수있는지 궁그음합니다

**Comment by Carlo-Woo** [comment]
KKuTu-OOOOOO\setting.json의 `"server-name": "underfined",`를 바꾸시면 됩니다.

**Comment by norhu1130** [comment]
> KKuTu-OOOOOO\setting.json의 `"server-name": "underfined",`를 바꾸시면 됩니다.

벌써해보았습니다.

**Comment by hatty163** [comment]
@norhu1130 끄투 서버는 환경 변수 `KKT_SV_NAME`의 값을 불러옵니다. 해당 환경 변수를 원하시는 값으로 정의하시면 됩니다.

**Comment by norhu1130** [comment]
> @norhu1130 끄투 서버는 환경 변수 `KKT_SV_NAME`의 값을 불러옵니다. 해당 환경 변수를 원하시는 값으로 정의하시면 됩니다.

안됩니다
현재 리녹스방법으로 열고있는데 이거떄문일까요?

**Comment by norhu1130** [comment]
정확히는
[underfined]글자로 놀자! XX끄투 이렇게뜹니다

**Comment by hatty163** [comment]
자세한 사항은 [Node.js Documention](https://nodejs.org/api/cli.html#cli_environment_variables)을 참고해주세요.

**Comment by hatty163** [comment]
이것은 KKuTu 자체의 문제와는 거리가 있으므로 자세한 도움은 드리기 어렵습니다.
