### ISSUE TITLE
상점에서 아이템 추가

### ISSUE THREAD

**Issue by msquid** [JJoriping/KKuTu#71]
상점에서 아이템 추가 어떻게 합니까??

**Comment by JJoriping** [comment]
관리 페이지(기본 URL `./gwalli`)에 관리자 권한으로 접속하면 상점 아이템을 관리할 수 있습니다. 상점 아이템을 변경한 뒤에는 웹 서버를 다시 시작하는 것이 권장됩니다.

**Comment by msquid** [comment]
감사합니다.
