### ISSUE TITLE
하다하다 이런 것도 뜨네요...

### ISSUE THREAD

**Issue by Maple-kkutu** [JJoriping/KKuTu#710]
internal/modules/cjs/loader.js:1008 throw err; ^ SyntaxError: C:\Users\user\Desktop\KKuTu\Server\lib\Web\lang\ko_KR.json: Unexpected string in JSON at position 4156 at JSON.parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1005:27) at Module.load (internal/modules/cjs/loader.js:811:32) at Function.Module._load (internal/modules/cjs/loader.js:723:14) at Module.require (internal/modules/cjs/loader.js:848:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\user\Desktop\KKuTu\Server\lib\sub\webinit.js:22:11) at Module._compile (internal/modules/cjs/loader.js:955:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10) at Module.load (internal/modules/cjs/loader.js:811:32)

**Comment by lshqqytiger** [comment]
그냥 간단한 문법 문제입니다. ```ko_KR.json``` 파일을 확인해주세요.

**Comment by Maple-kkutu** [comment]
네 확인해볼게요

**Comment by Carlo-Woo** [comment]
@Maple-kkutu 해결하셨으면 이슈 닫아주세요.

**Comment by Maple-kkutu** [comment]
아직 해결이 안 됐는데... 이슈도 작성자 마음(?) 입니다.

**Comment by lshqqytiger** [comment]
아직도 해결이 안되셨나요 간단한 문제라 원하시면 제가 수정해서 보내드릴 수 있습니다.

**Comment by Maple-kkutu** [comment]
네 보내드릴게요.

**Comment by Maple-kkutu** [comment]
아하... 죄송합니다. 제가 고쳐놨어요. 이슈 끌게요
