### ISSUE TITLE
로그인 후 portal로 이동하면서 오류가 뜨며 로그인이 풀립니다.

### ISSUE THREAD

**Issue by TyphoonDANAS** [JJoriping/KKuTu#711]
어떤 로그인이든
`Error when querying: INSERT INTO session ("profile", "createdAt", "_id") (중략) ON CONFLICT (_id) DO UPDATE SET (후략)` 후
`Context: error: ON CONFLICT 절을 사용하는 경우, unique 나 exclude 제약 조건이 있어야 함`
이 뜹니다.
이런 오류는 처음이라 당황스럽네요...
어떻게 해결하면 좋을까요?

**Comment by lshqqytiger** [comment]
세션이나 로그인에 관해 영향을 줄 만한 부분을 건드리신 적 있나요

**Comment by TyphoonDANAS** [comment]
> 

> 세션이나 로그인에 관해 영향을 줄 만한 부분을 건드리신 적 있나요

postgreSQL 포트를 5433으로 변경한 점 말고는 없습니다

**Comment by TyphoonDANAS** [comment]
데이터베이스 접속 시 `string indices must be integers`가 뜨는 것으로 보아 데이터베이스 관련 문제 같습니다.
일단은 이슈 닫습니다.

**Comment by TyphoonDANAS** [comment]
postgreSQL 재설치 후에도 계속 같은 반응을 보이고 있습니다.

**Comment by TyphoonDANAS** [comment]
데이터베이스 백업본 손상이었습니다.
이슈 닫습니다.
