### ISSUE TITLE
분홍끄투가 않들어가져요

### ISSUE THREAD

**Issue by mossyboab** [JJoriping/KKuTu#715]
갑자기 분홍끄투 이슈가 않되서 그런데
왜 분홍끄투 예전거 않들어가지나요..
원래 https://kkutu.pw 이었는대 http://d6bwgizqujydbcexod7g.3kdsjsohwknzkqq.kro.kr:200/ 가 됬어요

빨리 해결 부탁드립니다

**Comment by lshqqytiger** [comment]
이 곳은 끄투 레포지토리 또는 끄투 서버 구축 중에 문제가 발생했을 때 묻는 곳이지 프리서버에 대한 문의를 하는 곳이 아닙니다. 이슈 지워주시기 바랍니다.

**Comment by mossyboab** [comment]
http://218.148.38.237:200/
여기서도 가능해요

**Comment by lshqqytiger** [comment]
디스코드로 문의하시고 **이슈 닫아주세요 #689 **

**Comment by mossyboab** [comment]
저디코벤먹엇는데.. 알겠습니다ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ

**Comment by mossyboab** [comment]
죄송한데 Porxy가 먼가요???

**Comment by KAINNY5669** [comment]
위키 백과를 찾아보시기 바랍니다. 참고로 여기는 **끄투 관련 질문만 다루는 곳**입니다.

**Comment by mossyboab** [comment]
아닠ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
분홍끄투가 끄투죸ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by lshqqytiger** [comment]
프리서버 말고 끄투 레포지토리에 관한 것들을 다루는 곳입니다.
Proxy는 서버의 IP를 가려서 DDoS나 DoS 같은 공격들을 당하지 않도록 방지하는 기술입니다.

**Comment by dalnala** [comment]
분홍끄투가 예전에 안들어 가졌어요
