### ISSUE TITLE
타임아웃문제

### ISSUE THREAD

**Issue by norhu1130** [JJoriping/KKuTu#717]
안녕하세요?
GCP로 윈도우 서버 2012 R2 운영체제로 서버를 키는데까지는 성공했으나...
방화벽설정을해도 타임아웃이발생합니다.
어떻게 해결해야할지몰라 이슈를남겨두겠습니다.
아예 연결이안되며 콘솔엔 아무것도안뜹니다.(서버부팅제외)

수정

localhost로는접속이되며 서버컴퓨터로 IP입력해서 접속하는것은 전부안됩니다.

**Comment by hatty163** [comment]
#689 참고해주세요.
이것은 끄투 외적인 문제로, 저희가 도움을 드릴 수가 없습니다.

추가로, GCP에서 Windows Server 2012 R2 사용 시, Windows단에 위치한 방화벽과 GCP 상단 방화벽 설정 모두 하셔야 합니다.
