### ISSUE TITLE
끄투 단어 추가 하기

### ISSUE THREAD

**Issue by papakia1234** [JJoriping/KKuTu#718]
단어 추가는 어떻케 하는지 궁금합니다 끄투에서 단어 추가 하는방법을 알려주세요 ! (사전에 없어도 파일로)

**Comment by lshqqytiger** [comment]
http://도메인/gwalli 에서 합니다.

**Comment by KAINNY5669** [comment]
http://자기서버주소/gwalli 에 들어갑니다.
global.json 에 기입한 암호를 적고, 테이블에는 한글이면 ko, 영어면 en을 적습니다.
맨 밑으로 쭉 내려가시면 끄투DB에 단어 추가하기란이 있습니다. 주제는 이러합니다.
`"theme_IMS": "THE iDOLM@STER",
		"theme_VOC": "VOCALOID",
		"theme_KRR": "개구리 중사 케로로",
		"theme_KTV": "국내 방송 프로그램",
		"theme_NSK": "니세코이",
		"theme_KOT": "대한민국 철도역",
		"theme_DOT": "도타 2",
		"theme_DRR": "듀라라라!!",
		"theme_DGM": "디지몬",
		"theme_RAG": "라면/과자",
		"theme_LVL": "러브 라이브!",
		"theme_LOL": "리그 오브 레전드",
		"theme_MRN": "마법소녀 리리컬 나노하",
		"theme_MMM": "마법소녀 마도카☆마기카",
		"theme_MAP": "메이플스토리",
		"theme_MKK": "메카쿠시티 액터즈",
		"theme_MNG": "모노가타리 시리즈",
		"theme_MOB": "모바일 게임",
		"theme_HYK": "빙과",
		"theme_CYP": "사이퍼즈",
		"theme_HRH": "스즈미야 하루히",
		"theme_STA": "스타크래프트",
		"theme_KGR": "아지랑이 프로젝트",
		"theme_ESB": "앙상블 스타즈!",
		"theme_ELW": "엘소드",
		"theme_OIM": "오레이모",
		"theme_OVW": "오버워치",
		"theme_NEX": "온라인 게임",
		"theme_WMV": "외국 영화",
		"theme_WOW": "월드 오브 워크래프트",
		"theme_YRY": "유루유리",
		"theme_KPO": "유명인",
		"theme_JLN": "라이트 노벨",
		"theme_JAN": "만화/애니메이션",
		"theme_ZEL": "젤다의 전설",
		"theme_POK": "포켓몬스터",
		"theme_HAI": "하이큐!!",
		"theme_HSS": "하스스톤",
		"theme_KMV": "한국 영화",
		"theme_HDC": "함대 컬렉션",
		"theme_HOS": "히어로즈 오브 더 스톰",`
예를 들어. 만약 한국 영화 단어를 추가하시고 싶으시면 주제에 KMV를 기입하시고 밑의 커다란 칸에다가 단어를 적으시고 확인 버튼을 누르시면 됩니다. 주제는 딱히 안 적으셔도 됩니다.

**Comment by papakia1234** [comment]
음 2분다 감사합니다 일단 2개다 해볼게요

**Comment by papakia1234** [comment]
근데 http://자기서버주소/gwalli  에 들어가니 
{"error":400} 라고 뜨는데요...

**Comment by KAINNY5669** [comment]
@papakia1234 권한 설정이 안 되있는겁니다. Server-lib-sub 폴더로 들어가시면 global.json 파일이 보일 겁니다. 그것을 여시면 2번째 줄에 `"ADMIN": [ "Input Admin Id Here"], `라는 줄이 있을겁니다.
거기에 자신의 id를 넣으시고 5번째 줄에` "PASS":"",` 라는 줄이 있는데, 거기는 관리자 페이지의 암호 부분입니다. 마창가지로 json 문법에 맞게 작성하셔야 합니다..

**Comment by lshqqytiger** [comment]
관리자 권한이 있는 계정으로 로그인 후 다시 시도하세요.

**Comment by papakia1234** [comment]
일단 1,2 시간 늦엿지만 한번 해볼게요 감사 합니다

**Comment by papakia1234** [comment]
근데 그거 아세요 ? 똑같아요....

**Comment by papakia1234** [comment]
코드: 
```
{
	"ADMIN": [ "papakia" ],
	"MAIN_PORTS": [ 8080 ],
	"KKUTUHOT_PATH": "/kkutu/data/kkutuhot.json",
	"PASS": "1234",
	"PG_USER": "postgres",
	"PG_PASSWORD": "1234580",
	"PG_PORT": 5432,
	"PG_DATABASE": "main",
	"GOOGLE_RECAPTCHA_TO_GUEST": false,
	"GOOGLE_RECAPTCHA_TO_USER": false,
	"GOOGLE_RECAPTCHA_SITE_KEY": "Your Google Recaptcha site key Here",
	"GOOGLE_RECAPTCHA_SECRET_KEY": "Your Google Recaptcha secret key Here",
	"IS_SECURED": false,
	"SSL_OPTIONS": {
		"PRIVKEY": "Your SSL Private Key Here",
		"CERT": "Your SSL Certificate Here",
		"CA": "Your SSL CA-Bundle Here",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": false
	}
}
```

**Comment by lshqqytiger** [comment]
**식별번호**를 입력하셔야 합니다. | **[참고](https://github.com/JJoriping/KKuTu/wiki/S~global.json)**

**Comment by papakia1234** [comment]
식별 번호는 어떻케 받지요? 
그리고 ssl 문서가 없어요 ㅋㅋ

**Comment by papakia1234** [comment]
학생이라 그런 돈을 내기가 ㅠㅠ

**Comment by papakia1234** [comment]
일단 제가 할수 있을거 같은 메인화면에서 /id 하면 나오는 거 한번 해볼게요 ㅠㅠ

**Comment by papakia1234** [comment]
앗! 하니까 됏어요 !

**Comment by papakia1234** [comment]
이제 어떡해 하지요?

**Comment by papakia1234** [comment]
창 타이틀이

***  jjo.kr 관리 페이지 ***
이라고 ...

**Comment by hatty163** [comment]
> 학생이라 그런 돈을 내기가 ㅠㅠ

Let's Encrypt 등의 무료 SSL 발급자를 이용해보세요.

**Comment by hatty163** [comment]
#689 3. 참고 바랍니다.
이슈 작성에 앞서 README.md 파일과 위키 및 이미 존재하는 이슈를 참고하시기 바랍니다. #47

**Comment by papakia1234** [comment]
음...... 해티 ... 디코에서 봣네요 ㅋㅋ

**Comment by hatty163** [comment]
**이곳에서 개인 메신저 언급은 자제하여 주시기 바랍니다.**
이곳은 끄투와 관련된 이슈를 작성하는 곳이지, 잡담을 위한 공간이 아닙니다.

**Comment by papakia1234** [comment]
아네 ~

**Comment by papakia1234** [comment]
어떤 메뉴에 서 단어가 추가 가능한가요?

**Comment by KAINNY5669** [comment]
쭈욱 내려가셔서 끄투 DB 다루기에서요..
제가 제일 첫 번째로 답을 달아 드린 게 단어 추가 방법입니다.
http://자기서버주소/gwalli 에 들어갑니다.
global.json 에 기입한 암호를 적고, 테이블에는 한글이면 ko, 영어면 en을 적습니다.
맨 밑으로 쭉 내려가시면 끄투DB에 단어 추가하기란이 있습니다. 주제는 이러합니다.
"theme_IMS": "THE iDOLM@STER", "theme_VOC": "VOCALOID", "theme_KRR": "개구리 중사 케로로", "theme_KTV": "국내 방송 프로그램", "theme_NSK": "니세코이", "theme_KOT": "대한민국 철도역", "theme_DOT": "도타 2", "theme_DRR": "듀라라라!!", "theme_DGM": "디지몬", "theme_RAG": "라면/과자", "theme_LVL": "러브 라이브!", "theme_LOL": "리그 오브 레전드", "theme_MRN": "마법소녀 리리컬 나노하", "theme_MMM": "마법소녀 마도카☆마기카", "theme_MAP": "메이플스토리", "theme_MKK": "메카쿠시티 액터즈", "theme_MNG": "모노가타리 시리즈", "theme_MOB": "모바일 게임", "theme_HYK": "빙과", "theme_CYP": "사이퍼즈", "theme_HRH": "스즈미야 하루히", "theme_STA": "스타크래프트", "theme_KGR": "아지랑이 프로젝트", "theme_ESB": "앙상블 스타즈!", "theme_ELW": "엘소드", "theme_OIM": "오레이모", "theme_OVW": "오버워치", "theme_NEX": "온라인 게임", "theme_WMV": "외국 영화", "theme_WOW": "월드 오브 워크래프트", "theme_YRY": "유루유리", "theme_KPO": "유명인", "theme_JLN": "라이트 노벨", "theme_JAN": "만화/애니메이션", "theme_ZEL": "젤다의 전설", "theme_POK": "포켓몬스터", "theme_HAI": "하이큐!!", "theme_HSS": "하스스톤", "theme_KMV": "한국 영화", "theme_HDC": "함대 컬렉션", "theme_HOS": "히어로즈 오브 더 스톰",
예를 들어. 만약 한국 영화 단어를 추가하시고 싶으시면 주제에 KMV를 기입하시고 밑의 커다란 칸에다가 단어를 적으시고 확인 버튼을 누르시면 됩니다. 주제는 딱히 안 적으셔도 됩니다.
추가로 확인 버튼을 누르시고 OK 알림이 뜨면 정상적으로 단어가 추가된 것입니다

**Comment by papakia1234** [comment]
아 ~~~ 너무 감사 합니다 해결 됏어요
