### ISSUE TITLE
상점 카테고리

### ISSUE THREAD

**Issue by kkutu-gamsa** [JJoriping/KKuTu#719]
상점의 전체, 배경, 휘장, 특수 등의 카테고리는 어디서 추가하나요?

**Comment by lshqqytiger** [comment]
```const.js```, ```ko_KR.json```, 필요한 경우 ```in_game_kkutu.js``` 등을 수정해야 합니다.

**Comment by Carlo-Woo** [comment]
@kkutu-gamsa 해결하시고 이슈 닫아주세요.
