### ISSUE TITLE
리눅스서버에서 node js 컴파일이 되지 않습니다.

### ISSUE THREAD

**Issue by k4584587** [JJoriping/KKuTu#72]
`[root@localhost KKuTu-master]# ./server-setup.sh

KKuTu-master/Server/setup.js:22
let step = [
    ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
./server-setup.sh: line 5: grunt: command not found`

스크립트를 실행하면 오류뜨는데 js 수정할곳이 있나요?
서버는CentOS 6.8 입니다.

**Comment by BasixKOR** [comment]
Node.js를 최신 버전으로 재설치해보세요. 주로 nodejs.org에서 다운로드 받지 않고 패키지 메니저로 다운받는 경우 현상이 발생합니다.

**Comment by trustypeople** [comment]
패키지매니저로 다운받으실 경우 구버전이 설치되며, 따로 저장소를 설정하신 뒤 패키지매니저로 다운받으실 경우 해결됩니다.

**Comment by BasixKOR** [comment]
실례합니다, 문제가 해결되셨다면 이슈를 닫아주시지 않겠습니까?

**Comment by k4584587** [comment]
> BasixKOR<br>

어디를 선택하면 닫을수있나요? 깃허브 홈페이지 배우는중이라. 버튼을 못찾겠네요.

**Comment by ingari** [comment]
이 이슈에 코멘트를 다실 때 Comment 버튼 말고 Close and Comment 버튼을 누르시면 이슈가 닫아집니다.
