### ISSUE TITLE
구글 계정으로 로그인할시에 이름 앞에 undefined가 추가됩니다.

### ISSUE THREAD

**Issue by Smile-Apple-0** [JJoriping/KKuTu#720]
passport 구글 auth 0.2.0으로 바꾸고 구글게정으로 로그인하니까 이름 앞에 undefined라는 이름으로 설정됩니다.

**Comment by lshqqytiger** [comment]
auth_google.js 파일을 수정해주세요.

**Comment by Smile-Apple-0** [comment]
해결했습니다. 감사합니다
