### ISSUE TITLE
jjo.kr과 kkutu.kr 접속 불가

### ISSUE THREAD

**Issue by issac4892** [JJoriping/KKuTu#725]
들어가면 사용자 이름과 비밀번호를 요구합니다

**Comment by KAINNY5669** [comment]
현재 kkutu.kr은 jjo.kr로 리다이렉팅 되어있고, jjo.kr 홈페이지는 현 공사중에 있습니다.

**Comment by issac4892** [comment]
넹 알겠습니다

**Comment by lshqqytiger** [comment]
쪼롤은 아직 테스트용 API 키를 사용하는 중이기 때문에 접속이 불가합니다.
프리 서버 목록은 [임시 프리 서버 목록](https://jjo.kr/kkutu) 에서 확인 가능합니다.
