### ISSUE TITLE
모든 이슈를 참고해도 봇이 안움직여요. 게다가 로그인도 잘 안돼요.

### ISSUE THREAD

**Issue by AA1004** [JJoriping/KKuTu#729]
거의 봇에 대한 모든 이슈를 둘러봤는데
안됐고, 아예 사끄봇 말고 다 바보가 돼서..... 
망했어요. 무슨 방법 없을까요?
게다가 로그인에 대한 모든 설정을 바꾸었는데도 네이버 로그인 조차도 안돼요.
방법이란 방법은 다 시도 해 볼게요....

**Comment by lshqqytiger** [comment]
classic.js를 대충 이렇게 수정해보세요
```const ROBOT_HIT_LIMIT = [ 1000 ];```

**Comment by AA1004** [comment]
안돼요. ROBOT_HIT_LIMIT를 다 1000 으로 해봐도 안됐고, 걍 1000으로 해도 봇은 바보인데요......

**Comment by lshqqytiger** [comment]
전 이렇게 하면 잘 작동했었는데..흠

**Comment by AA1004** [comment]
const ROBOT_START_DELAY = [ 1200, 800, 400, 200, 1 ];
const ROBOT_TYPE_COEF = [ 1250, 750, 500, 250, 1 ];
const ROBOT_THINK_COEF = [ 4, 2, 1, 1, 1 ];
const ROBOT_HIT_LIMIT = [ 1000,1000,1000,1000,1000 ];
const ROBOT_LENGTH_LIMIT = [ 3, 4, 9, 99, 99 ];
const RIEUL_TO_NIEUN = [4449, 4450, 4457, 4460, 4462, 4467];
const RIEUL_TO_IEUNG = [4451, 4455, 4456, 4461, 4466, 4469];
const NIEUN_TO_IEUNG = [4455, 4461, 4466, 4469];

이렇게 나옵니다. 이게 사끄봇밖에 안돼서.... 망한거죠.

**Comment by kdhkr** [comment]
#3 #38을 참고해주세요.

**Comment by kdhkr** [comment]
> 게다가 로그인에 대한 모든 설정을 바꾸었는데도 네이버 로그인 조차도 안돼요.
방법이란 방법은 다 시도 해 볼게요....

소셜 로그인은 Naver, Google 등의 소셜 로그인 제공업자에게서 API 키를 먼저 발급받으신 후, `./Server/lib/sub/auth.json`의 `clientID`, `clientSecret` 부분에 알맞은 값을 넣어주시면 됩니다.

**Comment by AA1004** [comment]
그건 성공 했습니다
봇은요....

**Comment by lshqqytiger** [comment]
#38 을 제대로 안읽으신 것 같습니다.
```yom21c1020 commented on 22 Feb 2017
단지 플레이를 반복해주시면 됩니다.
플레이를 반복함으로서 단어의 히트 수를 늘려 봇이 선택 가능한 단어를 늘리기 위함입니다.```

**Comment by AA1004** [comment]
전 그게 귀찮아서 말 하는겁니다.

**Comment by lshqqytiger** [comment]
그럼 직접 hit 수를 올려 주시면 됩니다.
![1](https://user-images.githubusercontent.com/39524005/89104646-c32c7200-d455-11ea-8c2a-f6dcc6715588.PNG)

**Comment by AA1004** [comment]
해 볼게요.......

**Comment by AA1004** [comment]
robot.js는 어떤 방식으로 수정해야 할까요?
