### ISSUE TITLE
끄투 프리서버 목록에 추가가 안됩니다.

### ISSUE THREAD

**Issue by dasilver12** [JJoriping/KKuTu#73]
http://jjo.kr/kkutu 여기에 내서버 등록하기 눌러서 적힌대로 모두 다했지만

홈페이지 또는 게임 페이지의 저작권 관련 표시가 조건에 맞지 않다고 뜨는데 왜 그러는지 알수있을까요?

주소는 http://dalca.kr:2 입니다

이거 전에 http://kkutu.dalca.kr에다가도 해봤는데 안되네요

**Comment by JJoriping** [comment]
안녕하세요. 현재 dalca.kr, dalca.kr:2, kkutu.dalca.kr 모두 접근을 시도해 보았으나 접근할 수 없었습니다. 외부에서 서버에 접속할 수 있도록 설정했는지 확인해 보세요.

**Comment by dasilver12** [comment]
아 오후8시 경부터 새벽 4시까지 서버 점검에 좀 들어갔었습니다...
 
지금은 정상 접속이 가능합니다
 
-----Original Message-----

**Comment by JJoriping** [comment]
![image](https://cloud.githubusercontent.com/assets/12369657/24318858/29fe4782-1150-11e7-81aa-ccbed057fd86.png)

<a> 태그의 target 속성이 지정되어 있지 않았습니다만, 일단 이 속성이 없어도 등록이 가능하게 조치했습니다. 감사합니다.

**Comment by dasilver12** [comment]
a태그에 타겟이 그대로 적혀있는데 왜그러지... 일단 감사합니다!
