### ISSUE TITLE
서버에서 127.0.0.2로 연결 불가

### ISSUE THREAD

**Issue by ejl-kr** [JJoriping/KKuTu#733]
서버에서 127.0.0.2로 연결이 불가합니다.

Connect ECONNREFUSED 127.0.0.2:8080 에러가 뜨고 이 포트를 사용하는 노드를 Kill 하는 등 방법을 써보았지만
해결되지 않았습니다. 어떻게 해야 하나요?

**Comment by KAINNY5669** [comment]
#726 참고해주세요.

**Comment by hgl-215** [comment]
> #726 참고해주세요.

Redis를 설치해도 게임 서버로 연결은 불가하네요.. 아직도 1006 에러가 뜨고요..
