### ISSUE TITLE
끄투 GM 휘장 어떻게 하는거죠? #23 에서 보고 왔습니다만. 근데 어떻게 쓰는지좀 알려주세요.

### ISSUE THREAD

**Issue by Manrebat121719** [JJoriping/KKuTu#734]
Server [localhost]:
Database [postgres]:
Port [5432]:
Username [postgres]: 
이 부분에는 다 뭐를 써야 되는지좀 알려주세요.

**Comment by lshqqytiger** [comment]
휘장은 관리자 페이지 (/gwalli) 에서 하시면 되고
따로 아무런 설정도 하지 않았다면 위에서부터
localhost
postgres
5432
postgres
입니다.

**Comment by Manrebat121719** [comment]
들어가는건 아는데 자격? 추가 요정 뭐 어떤곳에서 해야하죠?

**Comment by lshqqytiger** [comment]
자격: 비밀번호. [관련 문서](https://github.com/JJoriping/KKuTu/wiki/S~global.json) 참고
테이블: 단어 관련 작업 시 사용. (ko/en)
휘장은 `유저 DB 다루기`에서 합니다.
![1](https://user-images.githubusercontent.com/39524005/89799432-6d984980-db68-11ea-8750-06f9b3dc8471.PNG)
빨간색으로 표시된 곳에 JSON 형식을 지켜서 `"b1_gm":1`을 추가합니다.
예시) 추가 전 `{"abcdefg":1}`
추가 후 `{"abcdefg":1,"b1_gm":1}`

**Comment by lshqqytiger** [comment]
그리고 이슈 #735 는 닫아주시기 바랍니다.

**Comment by Manrebat121719** [comment]
근데 다 해서 비밀번호까지 다 하고 마무리해서 다시 들어갔는데 GM휘장이 없어요

**Comment by KAINNY5669** [comment]
적용 버튼을 누르셨을 때 OK 알림창이 뜨셨나요?

**Comment by lshqqytiger** [comment]
보관함 확인해봐도 없다면 JSON 형식에 어긋났거나 비밀번호가 틀렸거나 한 것입니다.

**Comment by Manrebat121719** [comment]
비밀번호를 어떻게 하는지 모르겠어요 이해가 안가요.

**Comment by kkutu-gamsa** [comment]
global.json의 pass값 입니다.

**Comment by kdhkr** [comment]
#689 를 참고해주세요. 이곳은 고객센터가 아닙니다.
끄투 서버의 정상적인 운영을 위해서는 충분한 개발 실력을 요구합니다. 부족하다고 여겨질 경우, 다른 개발자를 구하거나 외주를 맡기시기 바랍니다. 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.
