### ISSUE TITLE
내도메인.한국 들어갔는데 txt가 무슨 의미인지 모르겠어요

### ISSUE THREAD

**Issue by Manrebat121719** [JJoriping/KKuTu#737]
내 도메인.한국 들어갔는데 txt가 무슨 의미이죠? 알려주시면 감사하겠습니다.

**Comment by lshqqytiger** [comment]
끄투와 무관한 이슈는 올리지 말아주세요.
TXT 레코드: 텍스트 레코드(Text Record)의 줄임말로, 임의의 문자열로 구성된 값입니다.

**Comment by Maple-kkutu** [comment]
사실 제가 한 겁니다.. 나중에 닫으라고 그럴게요

**Comment by kdhkr** [comment]
#689 참고해주세요. 끄투와 전혀 무관한 내용입니다.

**Comment by Maple-kkutu** [comment]
끄투와 무관한 내용은 알아요 닫아야 할텐데 그 분이 아직 안 닫으셔가지고 잘못 된거예요
