### ISSUE TITLE
관리자 페이지 초강력 오류

### ISSUE THREAD

**Issue by AA1004** [JJoriping/KKuTu#738]
자 설명 하겠습니다!
일단 단어추가는 기본으로 안돼고, 뒷 배경은 원래 없는지 모르지만 일단 다른 이슈를 확인한 결과 없습니다.
여기서 제일 심각한 문제는 SQL Gate(제가 쓰는 포스트그래스 편집 프로그램) 만기가 다 돼서 관리자 페이지로 수정해야 하는데
원래는 첫 추가로 웃는 눈을 관리자 페이지로 추가했습니다. 그거까진 잘 되었는데, 그 후로 다른 걸 추가하려고 추가를 눌렀더니
오히려 안되더라고요. 그래서 아빠한테 노가다 시켰더니 버그랍니다. 어떻게 고치는 방법 없나요? 다 작동을 안하는데요.

**Comment by lshqqytiger** [comment]
단어추가: 비밀번호나 테이블 누락 또는 불일치
뒷배경: 뭔가 잘못만짐
상점 DB: 원래 불안정해서 감수해야함

**Comment by AA1004** [comment]
근데요, pgAdmin을 쓸 줄을 몰라서....... 어케 쓸까요.

**Comment by lshqqytiger** [comment]
사용법은 직접 익히셔야죠.
저도 직접 해보면서 익숙해졌습니다.
(지금은 DBeaver 쓰지만..)

**Comment by AA1004** [comment]
익혀도 잘 안됍니다.
딱 그것만 알면 끄투 관련은 다 가능합니다.

**Comment by lshqqytiger** [comment]
그럼 그냥 DB 다시 구축하시는게 낫습니다.

**Comment by kdhkr** [comment]
#689를 참고해주세요. 이곳은 고객센터가 아닙니다.
말씀해주신 내용은 본인께서 SQL 질의를 잘못 실행시켰기 때문에 발생한 오류입니다.
관리자 페이지 동작 방식 특성상, 항목에 값이 `undefined` 또는 `null`인 칼럼이 하나라도 있을 경우 제대로 작동하지 않습니다.
이 점은 본인께서 pgAdmin이나 HeidiSQL, DataGrip 등의 데이터베이스 관리 툴로 직접 문제가 되는 부분을 찾아 수정해주셔야 합니다.

**Comment by Preta-Crowz** [comment]
관리 페이지 관련 소스를 수정하지 않은 타 서버에서 실험 결과, 모든 기능이 정상 동작합니다. 이는 본 이슈가 끄투 레포지토리의 문제가 아님을 뜻하며, 본 이슈가 해당 서버에서만 발생하는 현상임을 뜻합니다.
