### ISSUE TITLE
끄투 Games 서버 내 함수 문서화

### ISSUE THREAD

**Issue by BasixKOR** [JJoriping/KKuTu#74]
`getData()` 등 함수 이름에서 어떤 일을 하는지 유추하기 어려워 보입니다. 다른 프리서버를 위해서라도, 끄투의 문서화가 필요해 보입니다. (자원봉사자 분이라도 좋을 것 같고요.) 깃허브 위키에서 하면 좋을 것 같긴 합니다만, 다른 분들은 어찌 생각하시나요?

**Comment by BasixKOR** [comment]
JSDoc를 이용하는 것도 좋은 대안이 될 것 같습니다.

**Comment by BasixKOR** [comment]
관심있으신분은 이 이슈에 코멘트 달아주세용

**Comment by JJoriping** [comment]
안녕하세요. 다소 급하게 소스 코드를 정리하고 올린 처지여서 미처 소스 코드에 대한 설명을 하지 못한 점 양해 부탁드립니다. 말씀하신 사항은 끄투 박물관을 구현한 뒤 끄투 영어판과 함께 진행할 예정입니다.

**Comment by BasixKOR** [comment]
답변 감사합니다 :) 개발자분이 해주신다니 정말 고맙고 감사하네요..!
