### ISSUE TITLE
관리자 페이지에서 상점 DB다루기

### ISSUE THREAD

**Issue by rnrygus0613** [JJoriping/KKuTu#740]
관리자 페이지에서 상점 DB다루기에 보면 # cost hit term group updatedAtoptions name_ko_KR  desc_ko_KR  name_en_US desc_en_US 이렇게 있는데 나머지는 알것같은데 group에는 뭐를 넣어야하나요? 그리고 넣을수있는 단어는 뭐뭐있나요?

**Comment by lshqqytiger** [comment]
const.js를 참고하세요.
```
exports.GROUPS = {
	'spec': [ "PIX", "PIY", "PIZ", "CNS" ],
	'skin': [ "NIK" ],
	'badge': [ "BDG1", "BDG2", "BDG3", "BDG4" ],
	'head': [ "Mhead" ],
	'eye': [ "Meye" ],
	'mouth': [ "Mmouth" ],
	'clothes': [ "Mclothes" ],
	'hs': [ "Mhand", "Mshoes" ],
	'back': [ "Mback", "Mfront" ]
};
```

**Comment by rnrygus0613** [comment]
그 아바타? 그 모레미 스킨을 만들어서 적용하고싶은데 그거는 뭐라고해야하나요?

**Comment by pprcYT** [comment]
#719 이거 말씀이신가요?

**Comment by rnrygus0613** [comment]
네 맞는거 같습니다 근데 다른 상품들은 착용을 할수있는데 방금 카테고리를 만들어서 넣은 아바타?는 착용이 안됩니다

**Comment by rnrygus0613** [comment]
앗 해결했습니다 이슈 닫으면 되나요?
