### ISSUE TITLE
카카오 로그인 문제

### ISSUE THREAD

**Issue by norhu1130** [JJoriping/KKuTu#741]
안녕하세요?
#645 이슈를 참조 수정해도 안되었으며
#675 PR 변경사항을 적용해도 문제는 여전했습니다.
증상은 다음과같습니다.
로그인시 서버가 꺼짐(웹서버)

**Comment by kdhkr** [comment]
`서버가 꺼진다`라고만 표현하시면 제대로 된 답변을 드리기가 어렵습니다.
관련된 오류 스크린샷과 소스 코드를 함께 첨부해주시기 바랍니다.

**Comment by norhu1130** [comment]
> `서버가 꺼진다`라고만 표현하시면 제대로 된 답변을 드리기가 어렵습니다.
> 관련된 오류 스크린샷과 소스 코드를 함께 첨부해주시기 바랍니다.

소스코드는 Github에있으며.
로그인시 웹서버가 셧다운됩니다.

**Comment by lshqqytiger** [comment]
그냥 서버가 꺼지기만 하나요? 아무런 에러 없이?

**Comment by kdhkr** [comment]
> > `서버가 꺼진다`라고만 표현하시면 제대로 된 답변을 드리기가 어렵습니다.
> > 관련된 오류 스크린샷과 소스 코드를 함께 첨부해주시기 바랍니다.
> 
> 소스코드는 Github에있으며.
> 로그인시 웹서버가 셧다운됩니다.

그건 당연한겁니다. **관련된 오류 스크린샷과 소스 코드를 함께 첨부해주시기 바랍니다.**

**Comment by norhu1130** [comment]
오류 스크린샷 잠시만요

**Comment by norhu1130** [comment]
아 설정을 잘못했네요 해결했습니다.
