### ISSUE TITLE
KKuTu at agpl : kkutu.sql 이슈

### ISSUE THREAD

**Issue by Tilto0822** [JJoriping/KKuTu#744]
kkutu.sql을 mysql에 입력하던 중 250번째 라인(kkutu_manner_ko INSERT문)에서 
`ERROR 1062 (23000) at line 250: Duplicate entry '②' for key 'kkutu_manner_ko.PRIMARY'`오류가 발생합니다.
그래서 INSERT문 의 id에 해당하는 값 중 ②에 해당하는 부분을 지웠더니,
이번에는 `ERROR 1062 (23000) at line 250: Duplicate entry '③' for key 'kkutu_manner_ko.PRIMARY'`오류가 발생하더군요....
그렇기에 ①~ⓚ가 ASCII에서 utf8로 변환되며 저장되는 중에 값이 겹치는 것이 아닌가.... 의심됩니다.

마지막으로 INSERT문 의 id에 해당하는 값 중 ①~ⓚ부분을 지웠더니 오류가 사라지고 sql문이 정상 작동하는 것을 확인하였습니다.
왜 이런 오류가 나타나는지 정확한 사유는 모르겠습니다.

**Comment by JJoriping** [comment]
안녕하세요.
`kkutu_manner_ko`나 `kkutu_manner_en` 테이블은 일종의 캐시 테이블로 작동하기 때문에 처음에 테이블을 비워 두어도 서버 작동 중 자동으로 채워지게 됩니다. 해당 부분에서 INSERT 중 오류가 났다면 아예 테이블을 비워 둔 채로 진행해도 됩니다.

**Comment by Tilto0822** [comment]
알겠습니다. 궁금증을 해결했으니, 일단 이슈는 닫도록 하겠습니다.
