### ISSUE TITLE
서버 실행중 에러

### ISSUE THREAD

**Issue by rnrygus0613** [JJoriping/KKuTu#747]
제가 인게임 신고기능을 만들고 서버를 껏다 키려는데 

**internal/modules/cjs/loader.js:968 throw err; ^ Error: Cannot find module '../sub/crypto' Require stack: - C:\Users\RABBIT\Desktop\Kkutu\Server\lib\Game\master.js - C:\Users\RABBIT\Desktop\Kkutu\Server\lib\Game\cluster.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15) at Function.Module._load (internal/modules/cjs/loader.js:841:27) at Module.require (internal/modules/cjs/loader.js:1025:19) at require (internal/modules/cjs/helpers.js:72:18) at Object.&lt;anonymous> (C:\Users\RABBIT\Desktop\Kkutu\Server\lib\Game\master.js:26:14) at Module._compile (internal/modules/cjs/loader.js:1137:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10) at Module.load (internal/modules/cjs/loader.js:985:32) at Function.Module._load (internal/modules/cjs/loader.js:878:14) at Module.require (internal/modules/cjs/loader.js:1025:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'C:\\Users\\RABBIT\\Desktop\\Kkutu\\Server\\lib\\Game\\master.js', 'C:\\Users\\RABBIT\\Desktop\\Kkutu\\Server\\lib\\Game\\cluster.js' ] }**

이런 오류가 떴습니다 해결방법이 있을까요?

**Comment by lshqqytiger** [comment]
`../sub/crypto` 모듈을 찾지 못하고 있습니다.
Crypto.js 모듈 사용을 원하시는 것이라면 `npm install crypto-js` 실행 후 
```
var CryptoJS = require("crypto-js");
```
를 추가해 불러와 주시기 바랍니다.

**Comment by rnrygus0613** [comment]
### ### crypto.js 파일 생성후 무엇을 작성해야하나요?

**Comment by lshqqytiger** [comment]
crypto.js 파일로 뭘 하고 싶으신 거죠?

**Comment by rnrygus0613** [comment]
그냥 저는 신고기능을 구현하고싶습니다 어떤사람이 만든거를 참고해서 만든거라서 crypto.js이 있는듯 합니다

**Comment by lshqqytiger** [comment]
그럼 제가 어떻게 도와드릴 수 있는게 없습니다.
기존에 신고 기능을 먼저 구현한 서버들의 깃허브에 가서 코드들을 참고하면서 직접 개발하는 수 밖에요.

**Comment by rnrygus0613** [comment]
알겠습니당 일단 이슈 닫겠습니다
