### ISSUE TITLE
서버 목록

### ISSUE THREAD

**Issue by rnrygus0613** [JJoriping/KKuTu#748]
원래 잘되다가 오늘 서버를 켰더니
![image](https://user-images.githubusercontent.com/61346843/91270910-57b79500-e7b4-11ea-967c-00ff64615dc2.png)
이렇게 서버가 뜹니다
물론 서버 재부팅과 F5도 눌러보았습니다
(게임시작누르면 게임 들어가지기는합니다)

**Comment by rnrygus0613** [comment]
추가로
오늘부터 자꾸 로그에 
[2020-08-26 15:53:43] Chan @0 Msg #guest__1: {"type":"seek"}
이런게 계속 올라옵니다

**Comment by lshqqytiger** [comment]
해당 이슈는 도커 때문입니다. 이미 관련 PR도 존재합니다. #697

**Comment by rnrygus0613** [comment]
해결됬습니다 감사합니다 이슈 닫겠습니당
