### ISSUE TITLE
Let's Encrypt 인증서 사용시 TLS 적용에 대해 질문 드립니다.

### ISSUE THREAD

**Issue by yom21c1020** [JJoriping/KKuTu#75]
TLS 적용을 위해 `./Server/lib/Game/master.js`, `./Server/lib/Game/slave.js`를 수정했습니다. 게임서버 측 오류는 없지만 웹서버 측에서 `Error: self signed certificate`라며 연결을 하지 못합니다.
Let's Encrypt로 발급받은 인증서로 Nginx에서 잘 쓰고 있었는데, 자가서명 인증서라며 이러니 당황스럽네요. 
`process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`도 추가해 보았습니다만 오류는 여전합니다. 해결 방법이 있을까요?

**Comment by trustypeople** [comment]
혹시 FullChine 파일을 crt 로 등록하셨나요?

이 파일을 crt로 등록하셔야 정상적으로 이용이 가능합니다. Let's Encrypt 는요

**Comment by yom21c1020** [comment]
파일을 잘못 사용했네요. 닫겠습니다.
