### ISSUE TITLE
상점 닉네임스킨

### ISSUE THREAD

**Issue by rnrygus0613** [JJoriping/KKuTu#750]
제가 상점에 닉네임스킨을 추가했는데 닉네임에는 색 적용이 되지 않습니다.
어떻게 해야 색을 적용시킬수있나요?

**Comment by lshqqytiger** [comment]
in_game_kkutu_shop.css를 수정하세요.

**Comment by rnrygus0613** [comment]
.x-brown_name{ color: #613B3B; }
이렇게 추가했었습니다 하지만 인게임에서 적용되지 않았습니다

**Comment by lshqqytiger** [comment]
in_game_kkutu.min.js를 수정하세요.

**Comment by rnrygus0613** [comment]
color  #613b3b라고 뜹니다

**Comment by lshqqytiger** [comment]
닉네임 Element가 .x-brown_name 클래스를 가지고 있나요

**Comment by rnrygus0613** [comment]
그러면 어떻게 해야 원래있던 닉네임 스킨처럼 할수있을까요?

**Comment by lshqqytiger** [comment]
그럼 안 될 리가 없을텐데요..

**Comment by rnrygus0613** [comment]
일단은 알겠습니당 이슈닫겠습니다
