### ISSUE TITLE
핑 배율

### ISSUE THREAD

**Issue by papakia1234** [JJoriping/KKuTu#751]
게임을 했을때 핑을 더많이 줄수 있나요 ? 

끄투 개발자 분들에게 물어 봤는데

않알려줌 ㅅㄱ 이러셔서.,...

**Comment by lshqqytiger** [comment]
핑 획득 등은 kkutu.js에서 처리합니다.

**Comment by KAINNY5669** [comment]
#680 이미 존재하는 이슈를 참고해주세요.

**Comment by kdhkr** [comment]
#689 
2. 이곳은 본인이 개발하기를 원하는 **기능을 어떻게 구현하는지** 질문하는 곳이 아닙니다.
"특수 규칙을 만들고 싶은데 어떻게 만들어야 하나요?" 혹은 "닉네임 변경 기능은 어떻게 만드나요?"와 같은 질문은 삼가주시기 바랍니다. 아울러, 끄투 서버의 정상적인 운영을 위해서는 **충분한 개발 실력을 요구**합니다. 부족하다고 여겨질 경우, **다른 개발자를 구하거나 외주를 맡기시기 바랍니다.** 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.

**Comment by papakia1234** [comment]
@kdhkr 말을 들어 보니 그러네요 하니만 답변을 않해도 돼니 뭐 저는 그래도 도움을 받겠습니다

@lshqqytiger 어케 수정하나요?

**Comment by lshqqytiger** [comment]
그건 직접 능력껏 하셔야죠..

**Comment by kdhkr** [comment]
> @kdhkr 말을 들어 보니 그러네요 하니만 답변을 않해도 돼니 뭐 저는 그래도 마지막으로 특수한 도움을 받겠습니다
> 어케 수정하나요?

계속 여기를 끄투 고객센터마냥 생각하시는거 같으신데, 이곳은 끄투 자체의 문제점에 대하여 질문하고, 이를 해결하기 위해 존재하는 곳이지 본인의 개발 실력이 부족한 것을 다른 사람에게 떠넘기는 곳이 아닙니다.

**Comment by papakia1234** [comment]
쩝 이슈 닫을게요
