### ISSUE TITLE
끄투 서버가 열리지 않습니다.

### ISSUE THREAD

**Issue by jwkim101201** [JJoriping/KKuTu#755]
![캡처](https://user-images.githubusercontent.com/37768795/93552853-98b65a00-f9ac-11ea-8046-3c68ab3f0306.PNG)
이런 오류가 뜹니다. 그리고 netstat로 확인해본 결과
![캡처](https://user-images.githubusercontent.com/37768795/93552888-b4b9fb80-f9ac-11ea-97dc-8d19cb060e3c.PNG)
이것밖에 뜨지 않는데 이런 경우에는 어떻게 해야할까요?
\+ 관리자 권한으로도 열어보았습니다.

**Comment by lshqqytiger** [comment]
![1](https://user-images.githubusercontent.com/39524005/93555418-d3ba8c80-f9b0-11ea-9abc-08e69538771e.PNG)
이렇게 해보셨나요

**Comment by jwkim101201** [comment]
조금 있다 해보겠습니다

**Comment by jwkim101201** [comment]
Docker가 있길래 Docker를 껐더니 되네요 감사합니다
