### ISSUE TITLE
AI의 지능을 어덯게 올리나요?

### ISSUE THREAD

**Issue by Oein** [JJoriping/KKuTu#757]
고수끄투봇은 너무 못하고
사기는 너무강해서

**Comment by lshqqytiger** [comment]
각 게임 모드 모듈 파일 속
ROBOT_START_DELAY
ROBOT_TYPE_COEF
ROBOT_THINK_COEF
ROBOT_HIT_LIMIT
ROBOT_LENGTH_LIMIT
상수를 적당히 조절해주세요.

**Comment by Oein** [comment]
감사합니다
