### ISSUE TITLE
소셜로그인 에러

### ISSUE THREAD

**Issue by Oein** [JJoriping/KKuTu#759]
github oauth를 등록한뒤
github로 로그인을 했습니다.

어떨때는 로그인을 했지만 로그인 버튼이 닉네임으로 바뀌지 않고 로그인이 안되었습니다.
로그인이 됬을떄는 접속했을때 풀리는 현상이 있습니다.

로그인 버튼이 닉네임으로 바꿘뒤 서버에 로그인 버튼으로 내용이 바뀌지 않을때는 될때도 있지만 얼마있다가 로그인이 풀리고
내 정보에 들어가면 잘못된 접근이라네요

**Comment by kkutu-gamsa** [comment]
#742

**Comment by kdhkr** [comment]
#79 
Redis를 설치하지 않으셨을 경우 세션 기능이 작동하지 않는 점 참고 부탁드립니다.
