### ISSUE TITLE
관리자 페이지에서 DB단어 추가나 관리가 안됩니다.

### ISSUE THREAD

**Issue by dasilver12** [JJoriping/KKuTu#76]
![dddddd](https://cloud.githubusercontent.com/assets/7719901/24320224/3a4f4e46-1174-11e7-9025-039ea5ea0ff6.png)
![dddddd2](https://cloud.githubusercontent.com/assets/7719901/24320226/3c9d3564-1174-11e7-8ed5-0fcd84a8f683.png)

유저나 상점 db를 보고 수정하고는 잘되나 단어쪽을 건드리면 이런 오류가 나타납니다.

**Comment by dasilver12** [comment]
그리고 맨밑에 인기단어 조회를 누르면 웹서버랑 게임서버중에 웹서버가 터집니다 W: closed with code 0

**Comment by JJoriping** [comment]
안녕하세요. 페이지 가장 위의 암호 및 테이블을 올바르게 입력해 주세요. 한국어는 `ko`, 영어는 `en`입니다.
인기 단어 조회는 해당 문구 위에 있는 자세한 오류 내역을 보여주시면 검토해 보겠습니다.

**Comment by dasilver12** [comment]
올바르게 입력하였습니다 그래서 유저나 상점은 조회랑 수정이 되나 단어만 조회나 수정이 되지않습니다.

![sdzxczxcxc](https://cloud.githubusercontent.com/assets/7719901/24320519/44efa052-117a-11e7-8f0b-e73d7e0de13c.png)

**Comment by dasilver12** [comment]
아 단어 조회나 추가는 정상적으로 완료 되었습니다 다만 역시 인기는 누르면 서버가 터지네요

**Comment by JJoriping** [comment]
상수 `GLOBAL.KKUTUHOT_PATH`가 가리키는 파일이 존재하지 않거나 액세스할 수 없어서 생기는 오류입니다. 해당 경로에 파일이 있는지 확인해 주세요.

**Comment by dasilver12** [comment]
확인해봤으니 경로 자체는 정상이고 파일도 있음에도 그러네요 일단 지금당장은 pgadmin에서 select문으로 hit 순차정렬해서 확인해야겠습니다 감사합니다
