### ISSUE TITLE
sns 로그인

### ISSUE THREAD

**Issue by VEREN7** [JJoriping/KKuTu#760]
디스코드 로그인은 완성했는데 카카오 네이버 구글 페이스북 등등 로그인은 어떻게 만들어야할지 잘 모르겠습니다

**Comment by Oein** [comment]
네이버 : https://developers.naver.com/apps
깃허브 : https://github.com/settings/developers
구글 : https://console.developers.google.com/apis

**Comment by lshqqytiger** [comment]
`[OAuth 제공자] OAuth API` 또는 `[OAuth 제공자] API`라고 구글에 검색하면 다 나옵니다.

**Comment by KAINNY5669** [comment]
디스코드를 기준으로 설명드릴게요

1. [디스코드 개발자 페이지](https://discord.com/developers/applications) 에 들어가요
2. 로그인 한 다음, Applications 탭에 들어가요
3. New Applications 버튼을 눌러요
![sh](https://user-images.githubusercontent.com/65794272/95010948-12ff0380-0668-11eb-935a-d4188ff86dd8.png)
4. 원하는 이름을 설정해 주시고 create 버튼을 눌러요
![sgh](https://user-images.githubusercontent.com/65794272/95010955-172b2100-0668-11eb-9036-03cd3236fd5c.png)
5. 애플리케이션이 만들어지면, Oauth2 탭에 들어갈게요
![fk](https://user-images.githubusercontent.com/65794272/95010987-50639100-0668-11eb-9a40-1a49583574b2.png)
6. Redirects와 OAuth2 URL Generator를 설정해주세요
![is](https://user-images.githubusercontent.com/65794272/95011012-8f91e200-0668-11eb-81d9-a55716cb5868.png)
7. 다시 General info에 들어가서, 클라이언트 id를 복사할게요
![gh](https://user-images.githubusercontent.com/65794272/95011035-ce279c80-0668-11eb-99da-bdcdad74d26d.png)
8. `끄투폴더/lib/web/sub` 에 들어가시면 `auth.json`이 있을거예요. 그걸 열어주시고 22번째 줄의 `"clientID": "",`에서 따옴표 사이에 복사한 클라이언트 아이디를 넣어줄게요
![ajk](https://user-images.githubusercontent.com/65794272/95011093-41311300-0669-11eb-82c7-534993448f8e.JPG)
9. 다시 디스코드 개발자 포탈로 돌아가서 시크릿키를 복사해주세요.
![yrdk](https://user-images.githubusercontent.com/65794272/95011105-57d76a00-0669-11eb-978e-e36eaa4a62b2.png)
10. `끄투폴더/lib/web/sub` 에 들어가시면 `auth.json`이 있을거예요. 그걸 열어주시고 23번째 줄의 `"clientSecret": "",`에서 따옴표 사이에 복사한 시크릿키를 넣어줄게요
![aj'](https://user-images.githubusercontent.com/65794272/95011130-7dfd0a00-0669-11eb-830b-19c29484f3f2.JPG)
11. 끄투 서버를 재시작하시면 디스코드 로그인이 생겨있을거예요
![fl](https://user-images.githubusercontent.com/65794272/95011168-bdc3f180-0669-11eb-8922-fa1cd0337e59.png)
