### ISSUE TITLE
닉네임 변경기능 하려다...

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#761]
Pull requests에서 닉네임 변경기능 테스트해봤는데 불러오는 중 만 계속 떠요 ㅠㅠ
그래서...어떻게 해야하죠?
어쩔 수 없으면 이슈 닫겠습니다...ㅠ

**Comment by lshqqytiger** [comment]
저 PR 기초는 제가 짠거라 베프#4867로 DM 주시면 도와드리겠습니다.

**Comment by kdhkr** [comment]
#689 

1. 이곳은 **끄투 서버 자체의 문제점**만을 기술하시기 바랍니다.
**다른 사람의 풀 리퀘스트(PR)나 소스 코드를 사용함에 따라 발생하는 문제는 그 곳에서 질문하시기 바랍니다.** 이곳은 끄투 본연의 소스 코드 혹은 머지(Merge)된 소스 코드에서 발생한 문제점에 한하여 도와드리고 있습니다.

**Comment by Random-Studio** [comment]
그 곳이 어디라는 거죠? 그 끄투를 이용하라는건가요?

**Comment by lshqqytiger** [comment]
아뇨 PR이요 #753

**Comment by perfectkkutu** [comment]
grunt를 돌리시면 됩니다

**Comment by Random-Studio** [comment]
이미 해결되었습니다.
PR보고 하였습니다.
