### ISSUE TITLE
상단에 "빠른 소환사 검색" 부분 삭제

### ISSUE THREAD

**Issue by qkrehddls** [JJoriping/KKuTu#764]
안녕하세요 상단에 생기는 "빠른 소환사 검색" 부분을 삭제하고싶은데 css,pug 파일을 다 뒤져봐도 어디에 있는지 모르겠더라고요 아시는분 있으면 답글 부탁드립니다ㅠ

**Comment by lshqqytiger** [comment]
module.pug에 있습니다.

**Comment by qkrehddls** [comment]
이슈 닫습니다
