### ISSUE TITLE
GM 이 사용할 수 있는 명령어를 알려주세요.

### ISSUE THREAD

**Issue by dugom0kr** [JJoriping/KKuTu#765]
딱히 정리된게 없어서 이슈에 남깁니다.

**Comment by lshqqytiger** [comment]
[master.js](https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Game/master.js#L72)만 찾아보셔도 금방 찾으실 수 있습니다.
