### ISSUE TITLE
제휴 서버 관련

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#766]
끄투 중 제휴 서버를 만드려고 하는데 들어가면 https://jjo.kr/gallery 라고 뜨고 바꾸려고 하는데 수정을 어디에 해야하는지...
![image](https://user-images.githubusercontent.com/60588744/97165703-7394e280-17c7-11eb-85d5-718cbf8b70b8.png)

**Comment by lshqqytiger** [comment]
너무 기본적인 것까지 질문하지 말아주세요. 애초에 이슈 기능의 존재 목적은 기능 구현에 관한 질문이 아닙니다.
[module.pug](https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Web/views/module.pug#L21)에 있습니다.

**Comment by Random-Studio** [comment]
...네 알겠습니다.
