### ISSUE TITLE
게임 중인 방에서 나갈시 [#409] 해당 계정은 이미 접속 중에 있습니다.undefined 팝업창 발생

### ISSUE THREAD

**Issue by qkrehddls** [JJoriping/KKuTu#767]
안녕하세요 지금 게임 서버는 우분투에서 nginx으로 리버스 프록시 설정해서 사용하고 있는데
게임중인 방에서 나갈시 
[#409] 해당 계정은 이미 접속 중에 있습니다.undefined
팝업창이 나타나는데 다중 계정 탐지 부분을 삭제하고싶은데 어디에 있는지 모르겠네요 ㅠ
아시는분 있으면 답장 부탁드리겠습니다

**Comment by lshqqytiger** [comment]
[master.js](https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Game/master.js#L316)
[slave.js](https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Game/slave.js#L136)

**Comment by qkrehddls** [comment]
감사합니다

**Comment by lshqqytiger** [comment]
[kkutu.js](https://github.com/JJoriping/KKuTu/blob/8454e7b85f2389815642645ae4b2e72deec4f94e/Server/lib/Game/kkutu.js#L453)

**Comment by qkrehddls** [comment]
전부다 주석처리 하였는데도 [#409] 해당 계정은 이미 접속 중에 있습니다.undefined 창이 나타나네요 ㅠ

**Comment by kdhkr** [comment]
어떤 부분을 주석처리 하셨는지, 어떤 부분을 수정하셨는지 아무런 정보도 없이 말씀하시면 심히 곤란합니다.
아울러, 수정된 소스 코드의 오류에 관해서는 도움을 드리기가 어렵습니다.

**Comment by qkrehddls** [comment]
master.js 파일의 316~319번 줄을 주석처리 하였고
slave.js 파일의 136~139번줄을 주석처리 하였고
kkutu.js 파일의 453번줄을 주석처리 하였는데도
[#409] 해당 계정은 이미 접속 중에 있습니다.undefined 창이 나타납니다
소스코드 수정 전에도 나타났었습니다

**Comment by qkrehddls** [comment]
도메인은 https://kkutu.us 입니다

**Comment by lshqqytiger** [comment]
해당 버그는 끄투에 원래 있는 문제인 것으로 알고 있습니다.
클라이언트 쪽 코드를 수정하셔야 할 것 같습니다.

**Comment by qkrehddls** [comment]
클라이언트 쪽 코드면 main.js인가요?

**Comment by lshqqytiger** [comment]
아뇨 그건 서버입니다.
`Server\lib\Web\lib\kkutu` 폴더 속 파일들이 클라이언트 쪽입니다.

**Comment by qkrehddls** [comment]
409가 들어간 코드는 전부다 주석처리 하였더니 해결되었습니다 모두들 감사드립니다
