### ISSUE TITLE
./gwalli 단어 추가하는법

### ISSUE THREAD

**Issue by msquid** [JJoriping/KKuTu#77]
![default](https://cloud.githubusercontent.com/assets/25874496/24330912/1e9a38c8-1264-11e7-8aec-40a2c19de380.PNG)

단어 추가법좀 알려주세요.. ㅠ

**Comment by return0927** [comment]
PostgreSQL 콘솔에서 쿼리문으로 추가하세요.

**Comment by msquid** [comment]
그게 아니고 ./gwalli 페이지에서 추가하는법을 알려달라는겁니다
