### ISSUE TITLE
달달소 로그인 도중 오류 발생

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#770]
달달소 로그인을 하고 접속 하는데
ERROR OCCURRED ON THE MASTER!
:8080 [2020-11-10 5:34:36 ├F10: PM┤] ERROR: TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined at C:\Users\user\Desktop\22\KKuTu\Server\lib\Game\master.js:345:51 at exports.Tail.go (C:\Users\user\Desktop\22\KKuTu\Server\lib\sub\lizard.js:43:16) at C:\Users\user\Desktop\22\KKuTu\Server\lib\Game\kkutu.js:458:11 at callback (C:\Users\user\Desktop\22\KKuTu\Server\lib\sub\collection.js:316:13) at Result.preCB (C:\Users\user\Desktop\22\KKuTu\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (C:\Users\user\Desktop\22\KKuTu\Server\lib\node_modules\pg\lib\query.js:144:10) at Connection.&lt;anonymous> (C:\Users\user\Desktop\22\KKuTu\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:315:20) at Socket.&lt;anonymous> (C:\Users\user\Desktop\22\KKuTu\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:315:20) 이런게 뜨는데... 어떻하죠?

**Comment by qkrehddls** [comment]
특정 모듈 오류같은데 모듈을 확인해 보시는게 어떨까요?

**Comment by Random-Studio** [comment]
모듈요?
잠시만요

**Comment by qkrehddls** [comment]
혹시 https://github.com/JJoriping/KKuTu/pull/743 쓰고 계시면 passport-daldalso 모듈을 업데이트 시켜보시는게 어떨까요?

**Comment by Random-Studio** [comment]
네 알겠습니다

**Comment by Random-Studio** [comment]
그러고 보니 **"다른 사람의 풀 리퀘스트(PR)나 소스 코드를 사용함에 따라 발생하는 문제는 그 곳에서 질문하시기 바랍니다."**  이런게 있었네요...;;;;; 까먹...

**Comment by Random-Studio** [comment]
해결 되었습니다!
