### ISSUE TITLE
저의 kkutu 서버에 구글 에드센스 광고 및 다른 협찬 광고를 넣고 싶은데 아래에 AD 광고를 넣는 곳이 안보이는데 이거를 어떻게 보이게 해요?

### ISSUE THREAD

**Issue by Manrebat121719** [JJoriping/KKuTu#771]
그 사진을 보여드리겠습니다. 
![image](https://user-images.githubusercontent.com/66554317/99621250-bebeb000-2a6a-11eb-9c31-f22fba81b0ae.png)

**Comment by kdhkr** [comment]
#689 
2. 이곳은 본인이 개발하기를 원하는 **기능을 어떻게 구현하는지** 질문하는 곳이 아닙니다.
"특수 규칙을 만들고 싶은데 어떻게 만들어야 하나요?" 혹은 "닉네임 변경 기능은 어떻게 만드나요?"와 같은 질문은 삼가주시기 바랍니다. 아울러, 끄투 서버의 정상적인 운영을 위해서는 **충분한 개발 실력을 요구**합니다. 부족하다고 여겨질 경우, **다른 개발자를 구하거나 외주를 맡기시기 바랍니다.** 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.

**Comment by qkrehddls** [comment]
구글 애드센스는 tk도메인으로 통과 안되는것으로 알고있습니다.

**Comment by kdhkr** [comment]
@qkrehddls 참고로 그런거 없습니다.
.tk 도메인으로도 통과 잘 됩니다.

**Comment by lshqqytiger** [comment]
애드센스는 정책상 인게임 내 광고 삽입이 불가능한 것으로 알고 있습니다.
