### ISSUE TITLE
서버 켜기 애러

### ISSUE THREAD

**Issue by Log5440** [JJoriping/KKuTu#772]
[2020-11-21 21:18:10] &lt;&lt; KKuTu Web >>
[2020-11-21 21:18:10] &lt;&lt; KKuTu Server:8496 >>
[2020-11-21 21:18:10] OAuth Strategy naver is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy facebook is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy google is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy twitter is not loaded [2020-11-21 21:18:10] OAuthStrategy requires a consumerKey option
[2020-11-21 21:18:10] OAuth Strategy kakao is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy discord is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy twitch is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy github is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy line is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy instagram is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] OAuth Strategy spotify is not loaded [2020-11-21 21:18:10] OAuth2Strategy requires a clientID option
[2020-11-21 21:18:10] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080 [2020-11-21 21:18:10] Game server #1 closed: 1006

**Comment by lshqqytiger** [comment]
node.exe 외의 8080 포트를 사용하는 프로세스가 있는지 확인해주세요.

**Comment by Log5440** [comment]
> node.exe 외의 8080 포트를 사용하는 프로세스가 있는지 확인해주세요.

어떻게 확인해요?

**Comment by qkrehddls** [comment]
netstat -a

**Comment by Log5440** [comment]
> netstat -ano | findstr 8080

아무것도 안나와요

**Comment by lshqqytiger** [comment]
```
netstat -ano | findstr 8080
netstat -ano | findstr 8496
netstat -ano | findstr 80
```

셋 다 해보시고 나오는 PID를 찾아서

```taskkill /f /pid 찾은 PID```

또는 ```tasklist | findstr 찾은 PID```로 PID에 해당하는 프로세스를 찾으신 후
```taskkill /f /im 프로세스 이름```
으로 종료해주세요.

**Comment by Log5440** [comment]
> ```
> netstat -ano | findstr 8080
> netstat -ano | findstr 8496
> netstat -ano | findstr 80
> ```
> 
> 셋 다 해보시고 나오는 PID를 찾아서
> 
> ```
> taskkill /f /pid 찾은 PID
> ```
> 
> 또는 `tasklist | findstr 찾은 PID`로 PID에 해당하는 프로세스를 찾으신 후
> `taskkill /f /im 프로세스 이름`
> 으로 종료해주세요.

원인: 액세스가 거부되었습니다.
이렇게 나와요

**Comment by qkrehddls** [comment]
CMD를 관리자 권한으로 실행해 주세요

**Comment by Log5440** [comment]
> CMD를 관리자 권한으로 실행해 주세요

관리자 권한도 안돼요

**Comment by qkrehddls** [comment]
netstat -a -b
로 사용중인 프로세스의 이름을 말해주실 수 있나요?

**Comment by Log5440** [comment]
> netstat -a -b
> 로 사용중인 프로세스의 이름을 말해주실 수 있나요?

  프로토콜  로컬 주소           외부 주소              상태
  TCP    0.0.0.0:135            DESKTOP-J6VTPRD:0      LISTENING
  RpcSs
 [svchost.exe]
  TCP    0.0.0.0:445            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    0.0.0.0:5040           DESKTOP-J6VTPRD:0      LISTENING
  CDPSvc
 [svchost.exe]
  TCP    0.0.0.0:5432           DESKTOP-J6VTPRD:0      LISTENING
 [postgres.exe]
  TCP    0.0.0.0:49664          DESKTOP-J6VTPRD:0      LISTENING
 [lsass.exe]
  TCP    0.0.0.0:49665          DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    0.0.0.0:49666          DESKTOP-J6VTPRD:0      LISTENING
  Schedule
 [svchost.exe]
  TCP    0.0.0.0:49667          DESKTOP-J6VTPRD:0      LISTENING
  EventLog
 [svchost.exe]
  TCP    0.0.0.0:49668          DESKTOP-J6VTPRD:0      LISTENING
 [spoolsv.exe]
  TCP    0.0.0.0:49669          DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:5939         DESKTOP-J6VTPRD:0      LISTENING
 [TeamViewer_Service.exe]
  TCP    127.0.0.1:12025        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12110        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12119        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12143        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12465        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12563        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12993        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:12995        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:27275        DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    127.0.0.1:49671        DESKTOP-J6VTPRD:65001  ESTABLISHED
 [nvcontainer.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:0      LISTENING
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49696  ESTABLISHED
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49730  FIN_WAIT_2
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49731  FIN_WAIT_2
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49732  FIN_WAIT_2
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49733  FIN_WAIT_2
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49734  FIN_WAIT_2
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49674        DESKTOP-J6VTPRD:49735  FIN_WAIT_2
 [NVIDIA Web Helper.exe]
  TCP    127.0.0.1:49684        DESKTOP-J6VTPRD:49674  TIME_WAIT
  TCP    127.0.0.1:49686        DESKTOP-J6VTPRD:49674  TIME_WAIT
  TCP    127.0.0.1:49687        DESKTOP-J6VTPRD:49674  TIME_WAIT
  TCP    127.0.0.1:49696        DESKTOP-J6VTPRD:49674  ESTABLISHED
 [NVIDIA Share.exe]
  TCP    127.0.0.1:49697        DESKTOP-J6VTPRD:49674  TIME_WAIT
  TCP    127.0.0.1:49698        DESKTOP-J6VTPRD:49674  TIME_WAIT
  TCP    127.0.0.1:49699        DESKTOP-J6VTPRD:49674  TIME_WAIT
  TCP    127.0.0.1:49730        DESKTOP-J6VTPRD:49674  CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    127.0.0.1:49731        DESKTOP-J6VTPRD:49674  CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    127.0.0.1:49732        DESKTOP-J6VTPRD:49674  CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    127.0.0.1:49733        DESKTOP-J6VTPRD:49674  CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    127.0.0.1:49734        DESKTOP-J6VTPRD:49674  CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    127.0.0.1:49735        DESKTOP-J6VTPRD:49674  CLOSE_WAIT
 [NVIDIA Share.exe]
  TCP    127.0.0.1:65001        DESKTOP-J6VTPRD:0      LISTENING
 [nvcontainer.exe]
  TCP    127.0.0.1:65001        DESKTOP-J6VTPRD:49671  ESTABLISHED
 [nvcontainer.exe]
  TCP    169.254.147.138:139    DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    169.254.197.8:139      DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    192.168.219.105:139    DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    192.168.219.105:49672  a96-7-251-152:http     TIME_WAIT
  TCP    192.168.219.105:49673  5.62.53.225:https      TIME_WAIT
  TCP    192.168.219.105:49675  5.62.53.25:https       TIME_WAIT
  TCP    192.168.219.105:49676  a23-211-14-153:http    TIME_WAIT
  TCP    192.168.219.105:49677  5.62.53.225:https      TIME_WAIT
  TCP    192.168.219.105:49678  a23-211-14-153:http    TIME_WAIT
  TCP    192.168.219.105:49679  5.62.54.89:https       ESTABLISHED
 [TuneupSvc.exe]
  TCP    192.168.219.105:49680  a96-7-251-152:http     TIME_WAIT
  TCP    192.168.219.105:49682  69.94.69.208:https     TIME_WAIT
  TCP    192.168.219.105:49689  a96-7-251-152:http     TIME_WAIT
  TCP    192.168.219.105:49690  ec2-52-221-145-65:https  TIME_WAIT
  TCP    192.168.219.105:49691  ec2-13-124-71-167:https  TIME_WAIT
  TCP    192.168.219.105:49692  5.62.54.89:http        ESTABLISHED
 소유권 정보를 가져올 수 없습니다.
  TCP    192.168.219.105:49700  5.62.53.160:https      ESTABLISHED
 소유권 정보를 가져올 수 없습니다.
  TCP    192.168.219.105:49701  5.62.53.160:https      ESTABLISHED
 [TuneupSvc.exe]
  TCP    192.168.219.105:49702  ec2-13-124-71-167:https  TIME_WAIT
  TCP    192.168.219.105:49703  ec2-13-124-71-167:https  TIME_WAIT
  TCP    192.168.219.105:49707  210.89.167.4:https     TIME_WAIT
  TCP    192.168.219.105:49708  210.89.167.4:https     TIME_WAIT
  TCP    192.168.219.105:49715  210.89.167.4:https     TIME_WAIT
  TCP    192.168.219.105:49724  152.195.56.209:https   ESTABLISHED
 [NVIDIA Share.exe]
  TCP    192.168.219.105:49725  202.43.61.121:https    ESTABLISHED
  WpnUserService_74c4d
 [svchost.exe]
  TCP    192.168.219.105:49726  202.43.61.121:https    ESTABLISHED
  WpnUserService_74c4d
 [svchost.exe]
  TCP    192.168.219.105:49727  a96-7-111-240:http     ESTABLISHED
  WpnUserService_74c4d
 [svchost.exe]
  TCP    192.168.219.105:49728  a96-7-111-240:http     ESTABLISHED
  WpnUserService_74c4d
 [svchost.exe]
  TCP    192.168.219.105:49736  ec2-13-124-71-167:https  TIME_WAIT
  TCP    192.168.219.105:49737  ec2-13-124-71-167:https  TIME_WAIT
  TCP    192.168.219.105:49738  192.229.189.146:https  ESTABLISHED
 [NVIDIA Share.exe]
  TCP    192.168.219.105:49741  69.94.69.212:http      ESTABLISHED
 [TuneupSvc.exe]
  TCP    192.168.219.105:49744  ti-in-f188:5228        ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49746  ec2-52-78-231-108:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49747  ec2-52-78-231-108:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49748  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49749  151.101.228.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49750  ec2-52-78-231-108:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49751  ec2-52-4-115-36:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49752  lb-140-82-114-25-iad:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49753  ec2-54-180-75-25:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49754  ec2-54-180-75-25:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49755  a23-35-220-150:https   ESTABLISHED
 소유권 정보를 가져올 수 없습니다.
  TCP    192.168.219.105:49756  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49757  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49758  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49759  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49760  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49761  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49762  151.101.108.133:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49763  nrt20s08-in-f14:https  ESTABLISHED
 [whale.exe]
  TCP    192.168.219.105:49764  any-in-2215:http       ESTABLISHED
 소유권 정보를 가져올 수 없습니다.
  TCP    192.168.219.105:49765  any-in-2215:https      TIME_WAIT
  TCP    192.168.219.105:49766  5.62.53.22:8443        TIME_WAIT
  TCP    192.168.219.105:49767  5.62.53.22:8443        TIME_WAIT
  TCP    [::]:135               DESKTOP-J6VTPRD:0      LISTENING
  RpcSs
 [svchost.exe]
  TCP    [::]:445               DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::]:5432              DESKTOP-J6VTPRD:0      LISTENING
 [postgres.exe]
  TCP    [::]:7680              DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::]:49664             DESKTOP-J6VTPRD:0      LISTENING
 [lsass.exe]
  TCP    [::]:49665             DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::]:49666             DESKTOP-J6VTPRD:0      LISTENING
  Schedule
 [svchost.exe]
  TCP    [::]:49667             DESKTOP-J6VTPRD:0      LISTENING
  EventLog
 [svchost.exe]
  TCP    [::]:49668             DESKTOP-J6VTPRD:0      LISTENING
 [spoolsv.exe]
  TCP    [::]:49669             DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12025            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12110            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12119            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12143            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12465            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12563            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12993            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:12995            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:27275            DESKTOP-J6VTPRD:0      LISTENING
 소유권 정보를 가져올 수 없습니다.
  TCP    [::1]:49670            DESKTOP-J6VTPRD:0      LISTENING
 [jhi_service.exe]
  UDP    0.0.0.0:500            *:*
  IKEEXT
 [svchost.exe]
  UDP    0.0.0.0:4500           *:*
  IKEEXT
 [svchost.exe]
  UDP    0.0.0.0:5050           *:*
  CDPSvc
 [svchost.exe]
  UDP    0.0.0.0:5353           *:*
 [whale.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5353           *:*
 [whale.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5353           *:*
 [whale.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5353           *:*
 [whale.exe]
  UDP    0.0.0.0:5353           *:*
 [whale.exe]
  UDP    0.0.0.0:5353           *:*
 [whale.exe]
  UDP    0.0.0.0:5353           *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:5353           *:*
 [chrome.exe]
  UDP    0.0.0.0:5355           *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:49720          *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:49967          *:*
 [chrome.exe]
  UDP    0.0.0.0:50102          *:*
 [chrome.exe]
  UDP    0.0.0.0:52255          *:*
 [chrome.exe]
  UDP    0.0.0.0:53149          *:*
 [TeamViewer_Service.exe]
  UDP    0.0.0.0:53171          *:*
 [nvcontainer.exe]
  UDP    0.0.0.0:53779          *:*
 [chrome.exe]
  UDP    0.0.0.0:53783          *:*
 [chrome.exe]
  UDP    0.0.0.0:53824          *:*
 [chrome.exe]
  UDP    0.0.0.0:56026          *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:59953          *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:60487          *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:60545          *:*
 [chrome.exe]
  UDP    0.0.0.0:60546          *:*
 [chrome.exe]
  UDP    0.0.0.0:60547          *:*
 [chrome.exe]
  UDP    0.0.0.0:60548          *:*
 [chrome.exe]
  UDP    0.0.0.0:60933          *:*
 [chrome.exe]
  UDP    0.0.0.0:63194          *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    0.0.0.0:63959          *:*
  Dnscache
 [svchost.exe]
  UDP    0.0.0.0:64555          *:*
 [chrome.exe]
  UDP    0.0.0.0:65141          *:*
 [chrome.exe]
  UDP    0.0.0.0:65142          *:*
 [chrome.exe]
  UDP    0.0.0.0:65255          *:*
 [chrome.exe]
  UDP    0.0.0.0:65534          *:*
  Dnscache
 [svchost.exe]
  UDP    127.0.0.1:48201        *:*
 [NVIDIA Web Helper.exe]
  UDP    127.0.0.1:48202        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:59936        *:*
 [nvcontainer.exe]
  UDP    127.0.0.1:63192        *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    127.0.0.1:63320        *:*
  iphlpsvc
 [svchost.exe]
  UDP    169.254.6.127:5353     *:*
 [TeamViewer_Service.exe]
  UDP    169.254.147.138:137    *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    169.254.147.138:138    *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    169.254.147.138:5353   *:*
 [TeamViewer_Service.exe]
  UDP    169.254.147.138:5353   *:*
 [nvcontainer.exe]
  UDP    169.254.197.8:137      *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    169.254.197.8:138      *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    169.254.197.8:5353     *:*
 [TeamViewer_Service.exe]
  UDP    169.254.197.8:5353     *:*
 [nvcontainer.exe]
  UDP    192.168.219.105:137    *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    192.168.219.105:138    *:*
 소유권 정보를 가져올 수 없습니다.
  UDP    192.168.219.105:5353   *:*
 [nvcontainer.exe]
  UDP    [::]:500               *:*
  IKEEXT
 [svchost.exe]
  UDP    [::]:4500              *:*
  IKEEXT
 [svchost.exe]
  UDP    [::]:5353              *:*
 [whale.exe]
  UDP    [::]:5353              *:*
 [whale.exe]
  UDP    [::]:5353              *:*
 [chrome.exe]
  UDP    [::]:5353              *:*
 [chrome.exe]
  UDP    [::]:5353              *:*
 [whale.exe]
  UDP    [::]:5353              *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:5353              *:*
 [chrome.exe]
  UDP    [::]:5355              *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:49720             *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:53150             *:*
 [TeamViewer_Service.exe]
  UDP    [::]:53172             *:*
 [nvcontainer.exe]
  UDP    [::]:56026             *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:59953             *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:60487             *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:63959             *:*
  Dnscache
 [svchost.exe]
  UDP    [::]:65534             *:*
  Dnscache
 [svchost.exe]
  UDP    [::1]:59941            *:*
 [postgres.exe]
  UDP    [fe80::11cf:6ca0:8f5a:67f%12]:5353  *:*
 [TeamViewer_Service.exe]
  UDP    [fe80::208c:82e6:5807:c508%5]:5353  *:*
 [TeamViewer_Service.exe]
  UDP    [fe80::208c:82e6:5807:c508%5]:5353  *:*
 [nvcontainer.exe]
  UDP    [fe80::490a:e868:af51:938a%10]:5353  *:*
 [nvcontainer.exe]
  UDP    [fe80::490a:e868:af51:938a%10]:5353  *:*
 [TeamViewer_Service.exe]
