### ISSUE TITLE
끄투 효과음 관련 질문

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#773]
끄투 효과음을 다른 효과음으로 바꿨는데 기본 끄투 효과음이 나옵니다. 어떻하죠?

**Comment by kdhkr** [comment]
#689 
2. 이곳은 본인이 개발하기를 원하는 **기능을 어떻게 구현하는지** 질문하는 곳이 아닙니다.
"특수 규칙을 만들고 싶은데 어떻게 만들어야 하나요?" 혹은 "닉네임 변경 기능은 어떻게 만드나요?"와 같은 질문은 삼가주시기 바랍니다. 아울러, 끄투 서버의 정상적인 운영을 위해서는 **충분한 개발 실력을 요구**합니다. 부족하다고 여겨질 경우, **다른 개발자를 구하거나 외주를 맡기시기 바랍니다.** 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.

**Comment by Random-Studio** [comment]
?

**Comment by qkrehddls** [comment]
캐시를 초기화 해보세요

**Comment by Random-Studio** [comment]
어떤 캐시를 초기화할까요?

**Comment by qkrehddls** [comment]
브라우저 캐시요

**Comment by Random-Studio** [comment]
마지막입니다. 인터넷 익스플로러는 되는데 크롬은 그대로네요...
