### ISSUE TITLE
PostgreSQL.exe 실행 오류

### ISSUE THREAD

**Issue by fevertimes1009** [JJoriping/KKuTu#775]
https://www.postgresql.org/download/
이곳에서 postgreSQL.exe 설치 후 이 파일 실행하려고 하면 알 수 없는 오류코드가 뜹니다 
![1](https://user-images.githubusercontent.com/75085964/100370086-1780e080-3049-11eb-86c0-9f4fef51d211.JPG)
빨리 답변해주세요 ㅠㅜ

**Comment by lshqqytiger** [comment]
11.2.1 버전을 쓰면 해결된다고 합니다.
https://www.netzwelt.de/software-download/26666-postgresql.html

**Comment by fevertimes1009** [comment]
해결됐습니다 감사합니다
