### ISSUE TITLE
gwalli 들어가는법

### ISSUE THREAD

**Issue by DevloperCheongwol** [JJoriping/KKuTu#78]
gwalli을 어떻게 들어가나요
GM설정을 하고 들어갔을때 
{"error":400}
이라고 뜨며 안들어가지는데 해결방안 부탁드립니다!
(여기다 올리는거 맞겠지??)

**Comment by return0927** [comment]
루트 디렉토리에서 로그인이 되어있는지 확인해보세요

**Comment by DevloperCheongwol** [comment]
로그인이 되있는데 오류가납니다 ㅠㅠ
(네이버 소셜로그인사용)

**Comment by DevloperCheongwol** [comment]
아 업데이트 하니까 됬네요 친절하게 답변해주셔서 감사합니다~
