### ISSUE TITLE
사용방법

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#780]
COPY 147023
COPY 0
COPY 431398
COPY 1496
COPY 1983
COPY 80
COPY 80
COPY 0
COPY 0
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
라고떠서
데이터 베이스가 성공적으로 구축되었는데
이뒤에 서버를 어떻게 구축하나요?

**Comment by Random-Studio** [comment]
redis 설치 하셨나요?

**Comment by lshqqytiger** [comment]
README.md에 나와있는 대로 6번과 7번을 따라하시면 됩니다.
