### ISSUE TITLE
서버 만들기문제

### ISSUE THREAD

**Issue by qwertykkutu** [JJoriping/KKuTu#782]
[2020-12-09 09:58:41] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080 라고 뜨면서 서버 열기가 안됩니다

**Comment by qkrehddls** [comment]
Redis 설치 하셨나요?

**Comment by qwertykkutu** [comment]
네

**Comment by qkrehddls** [comment]
8080 포트를 사용하는 프로세스가 있나요?

**Comment by qwertykkutu** [comment]
그게 뭔가요?

**Comment by qwertykkutu** [comment]
없는것같은데요

**Comment by qkrehddls** [comment]
음 사용하시는 OS가 뭔가요

**Comment by qwertykkutu** [comment]
윈도우 에요

**Comment by qwertykkutu** [comment]
> 음 사용하시는 OS가 뭔가요

왜 답변이 없으시나요?

**Comment by kdhkr** [comment]
#776
ECONNREFUSED는 연결이 거부되었을 경우 발생하는 오류입니다. 대부분의 경우, 게임 서버가 정상적으로 구동되지 않아 발생하는 오류입니다. 웹 서버가 게임 서버보다 먼저 열릴 경우, 웹 서버가 열린 시점에 게임 서버로 요청을 보낼 수 없어 게임 서버가 열리지 않은 것처럼 표시됩니다.

이에 따라, 레프지토리에 포함된 구동기(`./Server/run.bat`)를 사용하시는 것보다 아래와 같이 명령어를 입력하여 차례차례 구동하는 것을 권장합니다.

(Windows 기준, `./Server` 디렉토리에서 실행해주세요.)
(게임 서버) `node lib\Game\cluster.js 0 1`
(웹 서버) `node lib\Web\cluster.js 1`

아울러, 이미 존재하는 이슈들을 참고해주시면 더욱 빠르게 답변을 받을 수 있습니다.

**Comment by kdhkr** [comment]
@qwertykkutu 이슈는 고객센터가 아닙니다. 저를 포함하여 답변해주시는 모든 분들은 개인적으로 시간을 내서 도와드리려는 것일 뿐이며, 빠르게 답변해드려야 하는 의무는 존재하지 않습니다. 이에 따라, "왜 답변이 없으시나요?" 답변을 재촉하는 행위는 좀 실례라고 생각됩니다.

**Comment by lshqqytiger** [comment]
ECONNREFUSED 오류와 Redis 설치 여부 / 8080 포트 사용 가능 여부는 별로 상관 관계가 없습니다.
Redis를 설치하지 않았을 때는 ```Error from Redis: Error: Redis connection to 127.0.0.1:6379 failed```
8080 포트를 사용할 수 없을 때는 EADDRINUSE 오류가 나옵니다.
