### ISSUE TITLE
외부 접속이 되지 않습니다.

### ISSUE THREAD

**Issue by jhj1228** [JJoriping/KKuTu#783]
말 그대로 외부 접속이 되지 않습니다. 이슈에서 확인한대로 80,8080,8496 포트 모두 열어줬는데, 상대방 컴퓨터는 접속이 아예 되지 않습니다. 정확한 이유가 뭘까요..

**Comment by qkrehddls** [comment]
사용하시는 OS가 뭔가요?

**Comment by lshqqytiger** [comment]
1. 포트 포워딩이 잘못 되어있음
2. 방화벽 문제

**Comment by jhj1228** [comment]
Windows 10 Pro v2004입니다.

**Comment by qkrehddls** [comment]
윈도우 방화벽 끄셨나요?

**Comment by jhj1228** [comment]
> 사용하시는 OS가 뭔가요?

Windows 10 Pro v2004입니다.

**Comment by jhj1228** [comment]
> 윈도우 방화벽 끄셨나요?

아뇨. 그땐 켜놨었습니다.

**Comment by qkrehddls** [comment]
사용하시는 인터넷 회사가 뭔가요? SKB나 티브로드같은 일부 인터넷 회사들은 80이나 443을 막는 경우가 있어서요

**Comment by jhj1228** [comment]
> 사용하시는 인터넷 회사가 뭔가요? SKB나 티브로드같은 일부 인터넷 회사들은 80이나 443을 막는 경우가 있어서요

KT입니다.

**Comment by qkrehddls** [comment]
윈도우 방화벽 꺼보시고 접속 안되시면 공유기를 확인해보시는게 어떨까요

**Comment by jhj1228** [comment]
> 윈도우 방화벽 꺼보시고 접속 안되시면 공유기를 확인해보시는게 어떨까요

일단 알겠습니다. 도움주신 모든 분들께 감사드립니다. 이슈 닫겠습니다.

**Comment by lshqqytiger** [comment]
![1](https://user-images.githubusercontent.com/39524005/102681643-77ad1180-4206-11eb-9bfb-b2bfb5aa6001.PNG)
참고로 굳이 방화벽을 끄지 않아도 인바운드 규칙에 UDP, TCP 각각 80, 8080, 8496 전부 등록하시면 됩니다.

**Comment by jhj1228** [comment]
> ![1](https://user-images.githubusercontent.com/39524005/102681643-77ad1180-4206-11eb-9bfb-b2bfb5aa6001.PNG)
> 참고로 굳이 방화벽을 끄지 않아도 인바운드 규칙에 UDP, TCP 각각 80, 8080, 8496 전부 등록하시면 됩니다.

근데 이 작업도 공유기 포트포워딩을 한 후에 하는게 맞죠?

**Comment by lshqqytiger** [comment]
뭘 먼저 하시던 상관 없으나 둘 다 해야하는 작업입니다.
