### ISSUE TITLE
상점 아이템 구매 후, 인벤토리에 없음

### ISSUE THREAD

**Issue by boyangsic** [JJoriping/KKuTu#786]
상점에서 아이템을 구매하여 구매 메시지를 받고, 인벤토리에 들어가봤지만 아무것도 없네요.. 직접 추가해야 하는건가요? 아니면 제가 뭔가를 잘못하고 있는건가요?

**Comment by lshqqytiger** [comment]
관리자 페이지 유저 DB 다루기에서 
![1](https://user-images.githubusercontent.com/39524005/102830611-08fdcd00-442d-11eb-8bd1-10861bf8c2f6.PNG)
아이템이 이런 식으로 잘 들어와 있는지 확인해주시고,
잘 들어와 있다면 아이템 DB 쪽 설정이 잘못된 것이고
안 들어와 있다면 아이템 지급 코드 쪽이 문제거나 아이템 지급 과정에서 뭔가 문제가 생긴 것입니다.

**Comment by boyangsic** [comment]
들어와 있는데 아이템이 없네요. 흠..

**Comment by boyangsic** [comment]
그런데, DB를 어떻게 바로잡아야 할까요?

**Comment by lshqqytiger** [comment]
지금 어떻게 되어있는지 볼 수가 없네요.
해당 아이템 파일이 없거나 아예 아이템이 상점 DB에 없거나 한 것 같습니다.

**Comment by boyangsic** [comment]
해결되었습니다.
