### ISSUE TITLE
서버 구축중 1000 오류가 났습니다.

### ISSUE THREAD

**Issue by catgl1715** [JJoriping/KKuTu#787]
항상 수고하십니다.
이번에 웹프로그래밍 공부 겸 끄투서버를 열어보려 하는데 아직 초보다 보니 모르는게 많아 질문합니다.
리드미에서 하라는 대로 redis도 설치했고 auth, global.json 파일들도 다 설정했습니다.
처음에는 1006 error가 나서 컴퓨터도 바꿔보고 포트도 바꿔보고
npm start(run.bat)대신 게임서버와 웹서버를 따로 batch 파일로 만들어 열어보기도 했는데 안되더군요.
그러다가 게임서버 포트랑 global.json 파일의 MAIN_PORTS 를 같게 설정하니 1006오류는 사라졌습니다.
그런데 이번엔 1000번 오류가 뜨네요... 1000번 오류는 기존 issue들을 정독해도 사례도 적고
해결방법이 똑부러지게 나오지 않아 질문 드립니다.

이하는 웹서버를 따로 batch 파일로 만들어 실행시킨 로그입니다. 게임서버는 이미 실행되어 있었구요.

C:\Users\user\Desktop\KKuTu-master\Server>node lib/Web/cluster.js 1
[2020-12-24 14:38:49] << KKuTu Web >>
[2020-12-24 14:38:49] Game server #1 connected
[2020-12-24 14:38:49] Game server #1 closed: 1000

그리고 이하는 웹서버를 **실행시키고 나서** 게임서버 로그입니다.

C:\Users\user\Desktop\KKuTu-master\Server>node lib/Game/cluster.js 0 1
[2020-12-24 14:50:52] << KKuTu Server:10427 >>
[2020-12-24 14:51:33] Wrong channel value undefined on @1

여기서 제가 질문드리고 싶은것은 1000번 error는 무엇인지,
혹시 제가 1006번 error를 해결하기 위해 게임서버 포트와 global.json의 MAIN_PORTS의 값을 같게 한 것이 잘못된 방법인지,
혹시 잘못된 방법이라면 제대로 된 방법은 무엇인지 궁금합니다.

윈도우 환경에서 서버열기를 성공하신 분들께 염치없지만 도움 요청해봅니다. 읽어주셔서 감사합니다.
괜한 걸로 issue 올린거 같아 너무 죄송스럽네요... 혹시 필요하신 정보가 있다면 전부 드리겠습니다.

**Comment by lshqqytiger** [comment]
게임서버를 먼저 여셔야 합니다.

**Comment by catgl1715** [comment]
> 게임서버를 먼저 여셔야 합니다.

당연히 게임서버를 열고 웹서버를 실행시켰습니다.
웹서버를 실행시키니 1000번 error가 발생하고 그 다음 게임서버에 2번째 줄과 같은 로그가 떴습니다.

**Comment by lshqqytiger** [comment]
본문에는 ```그리고 이하는 웹서버를 실행시키고 나서 게임서버 로그입니다.``` 이렇게 적혀있어서요.
WebSocket 1000 Error는 Normal closure입니다.
```
Normal closure; the connection successfully completed whatever purpose for which it was created.
```
1006 Error는 Abnormal closure이구요.
따로 이 코드를 통해 알 수 있는 것은 없습니다.

**Comment by catgl1715** [comment]
친절한 답변 감사드립니다. 알려주신대로 레파지토리 버전을 낮춰서 시도해보겠습니다.
