### ISSUE TITLE
단어를 정상적으로 넣었는데 단어대결에서는 사용이 안됩니다.

### ISSUE THREAD

**Issue by jhj1228** [JJoriping/KKuTu#788]
주제를 추가하고 단어를 추가했습니다. 보시다시피 끝말잇기에서는 사용이 잘 됩니다.
![hjgkhgjklgjkld](https://user-images.githubusercontent.com/43434644/103264584-7a6dea80-49ee-11eb-8e44-7337e218f726.PNG)

그런데 단어대결에서 진행하면 아무런 단어도 되지 않습니다. 혹시 몰라 재추가를 해보았는데도 동일한 증상입니다..
![ddada](https://user-images.githubusercontent.com/43434644/103264603-8b1e6080-49ee-11eb-9a0f-5f1a851dc64f.PNG)

**Comment by lshqqytiger** [comment]
봇이 아니라 유저가 사용했을 때도 동일 증상이 나타나나요?

**Comment by jhj1228** [comment]
![dase](https://user-images.githubusercontent.com/43434644/103265622-57910580-49f1-11eb-8bb1-e50274f55c4b.PNG)
일반 유저한테도 되지않고, 다른 주제라고 나옵니다.

**Comment by kdhkr** [comment]
단어 추가 후 서버 재가동 해보셨나요?
+ 끄투코리아측 레벨 이미지를 무단으로 사용하시는것 같아 보입니다. 허가를 받으신게 아니라면 사용하지 마셔야 합니다.

**Comment by lshqqytiger** [comment]
저는 겪어보지 않은 문제라 사진과 글만 봐서는 정확히 뭐가 문제인지 잘 모르겠네요.
서버 재가동 해보시고 그래도 동일 증상이 발생하면 관련 부분 코드를 좀 뜯어볼 필요도 있어보입니다.
끄투코리아 측 레벨 리소스는 저작권이 있는 걸로 알고 있습니다.
혼자 즐기시는 비공개 서버가 아니라면 조만간 끄투코리아 측에서 개인적으로 연락이..

**Comment by jhj1228** [comment]
> 단어 추가 후 서버 재가동 해보셨나요?
> 
> * 추가) 끄투코리아측 레벨 이미지를 무단으로 사용하시는것 같아 보입니다. 허가를 받으신게 아니라면 사용하지 마셔야 합니다.

이미 재가동을 몇번씩이나 해봤고, 단어추가를 몇번씩이나 해봤는데도 동일한 증상입니다.

**Comment by lshqqytiger** [comment]
daneo.js 파일의 주제 체크 부분을 디버깅 해보시는게 좋을 것 같습니다.

**Comment by Carlo-Woo** [comment]
해결되셨으면 이슈 닫아주세요
