### ISSUE TITLE
루트디렉터리에서 게임으로 갈시 네이버로그인이 풀립니다

### ISSUE THREAD

**Issue by DevloperCheongwol** [JJoriping/KKuTu#79]
루트 디렉터리에서 로그인을 한후 게임으로 들어갈시 네이버 로그인이 풀리고
게임안에서 로그인을 해도 네이버 로그인이 풀립니다
도와주세요!

**Comment by SkyLightQP** [comment]
저도 그런 오류가 있더라고요...

**Comment by JJoriping** [comment]
안녕하세요. 로그인(세션) 및 랭킹 기능은 Redis 서버를 설치한 뒤 Redis 관련 주석을 해제한 후 서버를 작동시켜야 정상 작동하니 참고해 주세요. Redis 서버를 설치하지 않는 경우 각 프로세스마다 별도로 세션 정보를 기록하기 때문에 일어나는 현상입니다.

**Comment by DevloperCheongwol** [comment]
Redis 서버는 설치했는데
Redis 관련주석의 위치를 알려주실수있나요?
