### ISSUE TITLE
포트 이후 오류 발생

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#791]
제가 포트 오류 문제로 구버전 레포지토리로 바꾸고 Redis Installer (.msi) 파일로 바꾸고 옮겼는데 이번엔 8080 포트 오류가 아닌 
Game server #1 has an error: Error: Parse Error: Expected HTTP/ 라고 뜹니다. 이게 무슨 상황이죠...?

**Comment by qkrehddls** [comment]
Node.js v12 같은 구버전을 사용해보세요

**Comment by Random-Studio** [comment]
아...그렇군요

**Comment by Random-Studio** [comment]
해결 되었습니다 ㅎㅎ 이슈 닫습니다
