### ISSUE TITLE
끄투안에 서버를 여려개를 만들어놨는데 작동이 되지 않습니다. 이 문제를 어떻게 할까요?

### ISSUE THREAD

**Issue by msrykkutuzard** [JJoriping/KKuTu#792]
![24243234234](https://user-images.githubusercontent.com/77523545/104798580-3d399300-580b-11eb-993c-5e2da0ffbd4d.PNG)
지금 이런식으로 오류를 냅다 뽑으면서 감자 서버만 구동이 되가고 있습니다. 도와주세요!
Now, only the potato server is running while picking out errors in this way. Help!

**Comment by lshqqytiger** [comment]
settings.json과 global.json을 모두 수정하셨나요

**Comment by msrykkutuzard** [comment]
어떤식으로 수정하면 되나요? settings.json는 다 설정해놨습니다.
