### ISSUE TITLE
이 오류는 대체 어떤 오류일까요?

### ISSUE THREAD

**Issue by msrykkutuzard** [JJoriping/KKuTu#793]
![image](https://user-images.githubusercontent.com/77523545/104883467-27ada000-59a8-11eb-8e41-a932cfb9e24f.png)
아니 평소처럼 서버를 열었는데 갑자기 이런 오류가 뜨면서 노동자 8904가 사망했네요.
이 오류를 어떻게 해야 할까요?

**Comment by qkrehddls** [comment]
ko_KR.json 파일을 순정으로 교체해보세요

**Comment by msrykkutuzard** [comment]
구버전 레포지토리인데... 이거 파일을 어떻게 구할까요?

**Comment by qkrehddls** [comment]
https://raw.githubusercontent.com/JJoriping/KKuTu/35dc04cc20c15da73ef0b80abb1ba9e83db574ef/Server/lib/Web/lang/ko_KR.json

이 파일을 저장해서 이걸로 교체해보세요

**Comment by msrykkutuzard** [comment]
어... 고쳐지긴 했는데... 
![image](https://user-images.githubusercontent.com/77523545/104884336-89223e80-59a9-11eb-996b-6bd31f0240db.png)
프로필 사진이 안나오는 버그가 또 생기네요 ㅋㅋㅋ

**Comment by qkrehddls** [comment]
주소를 남겨주실수 있으신가요?

**Comment by msrykkutuzard** [comment]
잠깐만요... 저 지금 도메인 설정을 해야되서..

**Comment by msrykkutuzard** [comment]
http://kkutul.kro.kr
여기입니다

**Comment by qkrehddls** [comment]
kkutul.kro.kr 도메인 A레코드가 192.168.219.105 로 설정이 되어있는데 재대로 IP를 설정하신게 맞으신가요?

**Comment by msrykkutuzard** [comment]
포트포워딩하고 DMZ설정까지 했습니다.

**Comment by qkrehddls** [comment]
192.168.219.105 는 사설 IP인거 같은데요? 공인 IP로 A레코드를 설정해보세요

**Comment by msrykkutuzard** [comment]
공인 아이피요? 공인 아이피는 뭔가요?  실제 아이피로 하란 소린 가요?

**Comment by qkrehddls** [comment]
https://whatismyipaddress.com/ 에 나오는 IP로 A레코드를 설정해보세요

**Comment by msrykkutuzard** [comment]
이런 오류가 뜨네요?..
![image](https://user-images.githubusercontent.com/77523545/104886815-b5d85500-59ad-11eb-952d-dcfbaaff8a01.png)
이건 대체 무슨오류

**Comment by qkrehddls** [comment]
80포트를 공유기 관리자 페이지 같은게 점유하고있는지 확인해보세요

**Comment by msrykkutuzard** [comment]
8080포트는 쓰는게 두개네요...?? 
하나는 127.0.0.2:8080 하나는 TCP [::] :8080

**Comment by qkrehddls** [comment]
8080포트가 아닌 80포트를 공유기 관리자 페이지 같은게 점유하고 있는걸 확인해보세요

**Comment by msrykkutuzard** [comment]
0:0:0:0 80포트가 있고
하나는 TCP [::] :80포트가...

**Comment by qkrehddls** [comment]
공유기 관리자 페이지에서 관리자 페이지 외부 접속이 켜져있는지 확인해보세요

**Comment by msrykkutuzard** [comment]
어.. 외부 접속이 없어요

**Comment by lshqqytiger** [comment]
방화벽 설정을 확인하세요.
웹서버, 게임서버 포트가 전부 인바운드 규칙에 등록되어 있어야 합니다.

**Comment by msrykkutuzard** [comment]
방화벽 설정은 잘 되어있는데.. 왜 도대체 공인아이피로 접속이 안되는지 의문이 가네요...
