### ISSUE TITLE
관리자 명령어 적용 안됩니다.

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#794]
제가 관리자 명령어를 적용하려고 하는데 제이쿼리인가 그게 적용이 안되더라고요? yell은 되는데 notice 이런거도 안되고 <script> ??? </script> 해봐도 안되고 자바 스크립트 등 구글링 해봐도 적용이 안됩니다. 어떡하죠?

**Comment by Random-Studio** [comment]
https://user-images.githubusercontent.com/60588744/105967171-e6647100-60c8-11eb-9b74-6ba14af3bb39.mp4

**Comment by Random-Studio** [comment]
https://user-images.githubusercontent.com/60588744/105967386-1dd31d80-60c9-11eb-8922-1149bf661e0c.mp4

**Comment by lshqqytiger** [comment]
"notice"는 기본적으로 끄투에는 존재하지 않는 명령어입니다.
직접 개발하셔야 합니다.

**Comment by Random-Studio** [comment]
그렇군요...
