### ISSUE TITLE
달달소 로그인 오류

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#796]
다른 사람들이 로그인 할 때InternalOAuthError: Failed to obtain access token at Strategy.OAuth2Strategy._createOAuthError (C:\Users\Owner\Desktop\KKuTu\Server\node_modules\passport-oauth2\lib\strategy.js:348:17) at C:\Users\Owner\Desktop\KKuTu\Server\node_modules\passport-oauth2\lib\strategy.js:171:43 at C:\Users\Owner\Desktop\KKuTu\Server\node_modules\oauth\lib\oauth2.js:191:18 at passBackControl (C:\Users\Owner\Desktop\KKuTu\Server\node_modules\oauth\lib\oauth2.js:132:9) at IncomingMessage.&lt;anonymous> (C:\Users\Owner\Desktop\KKuTu\Server\node_modules\oauth\lib\oauth2.js:157:7) at IncomingMessage.emit (events.js:215:7) at endReadableNT (_stream_readable.js:1184:12) at processTicksAndRejections (internal/process/task_queues.js:80:21) 라고 뜹니다. 그리고 끄투 목록에서 가능한 송수신체 없음 이 뜹니다. 달달소 로그인 까지 만들었는데 무슨 문제죠?
![image](https://user-images.githubusercontent.com/60588744/106555417-e0571000-6560-11eb-9437-9e1911ba1fbc.png)

**Comment by kdhkr** [comment]
- 환영합니다! 끄투 서버 운영에 관심을 갖고 찾아와 주셔서 감사 드립니다. 서버 목록에 들어가기 위해서는 끄투를 서비스하고 **승인을 받은 달달소 송수신체**를 하나 선택해야 합니다.

해당 문제는 달달소 송수신체가 승인되지 않은 상태임에 따라 발생합니다. 이에 대한 자세한 사항은 [여기](https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0)를 참고해주세요.

**Comment by Random-Studio** [comment]
검수가 문제였네요...이슈 닫습니다.
