### ISSUE TITLE
오류 해결 (우분투)

### ISSUE THREAD

**Issue by kdh0901** [JJoriping/KKuTu#798]
$ sudo apt install nodejs npm postgresql 으로 (nodejs, npmm postgresql)전부다 설치 완료했고요 db도 임시로 만들고 $ sudo node lib/Game/cluster.js 0 1 으로 서버를 실행하려고 했는데 다음과 같은 오류가 뜹니다.

module.js:549
          throw err;
          ^

Error: Cannot find module 'home/kdh0901/kkutu/Server/lib/lib/web/cluster.js'
        at Function.Module._resolveFilename (module.js:547:15)
        at Functon.Module._load (module.js:474:25)
        at Function.Module.runmain (module.js:693:10)
        at startup (bootstrap_node.js:188:16)
        at bootstrap_node.js:609:3

특이사항으로는 Ubuntu LTS 18.04 i386 버전입니다. 혹시 arm64버전이 아니라 i386이라서 작동이 안되는 건가요..?
리눅스 이제 막 다루기 시작해서... 도움 부탁드립니다.

**Comment by qkrehddls** [comment]
cluster.js 파일을 찾을수 없다는거 같은데요?

**Comment by kdh0901** [comment]
Cluster.js 파일은 찾아보니 정상적인 위치에 위치해 있습니다.

**Comment by kdh0901** [comment]
아 혹시 경로가 home/kdh0901/kkutu/Server/lib/lib/web/cluster.js 여기서 lib가 2개 들어가 있는데 (lib/lib 부분) 이건 파일 시스템으로 찾아보아도 lib 다음에 lib 폴더는 없는데 이건 무슨 의미일까요...

**Comment by kdh0901** [comment]
#784 참고하고 해결했습니다. 고맙습니다!
