### ISSUE TITLE
닉네임 변경 기능을 구현 시켰는데 이딴 (?) 오류가 뜹니다. 어떤식으로 고치면 될까요?

### ISSUE THREAD

**Issue by applewatermelon1217** [JJoriping/KKuTu#799]
Error: C:\Users\apple\OneDrive\바탕 화면\KKuTu-35dc04cc20c15da73ef0b80abb1ba9e83db574ef\Server\lib\Web\views\kkutu.pug:352:1 350| div.dialog-bar.tail-button 351| button#replay-view= L('replayView') > 352| +Dialog('DressDiag', 600, 300, L('dress')) ---------^ 353| div.dialog-bar 354| h4(style='width: 150px;')= L('myNickname') 355| input#dress-nickname(type='textfield', placeholder=L('myNicknameX'), style='width: 435px;', maxlength=10) Invalid indentation, you can use tabs or spaces but not both

이런식으로 뜨는데 어떻게 할까요?

**Comment by jhj1228** [comment]
조금만 구글링해도 금방 나오는 것인데..

탭과 스페이스를 동시에 사용해서 생긴 오류입니다. 스페이스 키를 썼다면 탭으로 바꿔주시면 됩니다.
