### ISSUE TITLE
끄투 meta tag 추가 건의

### ISSUE THREAD

**Issue by trustypeople** [JJoriping/KKuTu#8]
쪼리핑님께서도 그렇고 다른 개발자분도 끄투 리스트 같은 것을 만드시는 분이 많습니다.

끄투 리스트를 만든다면 그 끄투 리스트 안에서 플레이어가 얼마나 접속해있는지 같은 정보를 파악하려면 서버 상태를 표시하는 부분을 해석하여 표시해주어야 합니다.

하지만 쉽게 파싱해올 수 있는 부분을 만든다면 어떨까요?

메인 페이지에
<meta name="kkutu:type" content="kkutu">
<meta name="kkutu:playeramount" content="플레이어 총합">

이런식으로 파싱해올 수 있는 기반을 만들어 놓는 것입니다.

type 는 어떤 소스를 기반으로 제작되었는가. 를 나타내는 tag, playeramount 는 페이지가 로드될 때를 기준으로 플레이어가 얼마나 접속해있는지 를 나타내는 tag 입니다.

한번 좋다고 떠오른 아이디어를 이슈에 남겨 건의해봅니다.

**Comment by trustypeople** [comment]
어.. 뭔가 이상하게 됬나보네요.. pug 식으로 다시써보겠습니다 ㅋㅋㅋㅋ

meta(name='kkutu:type' content='kkutu')
meta(name='kkutu:playeramount' content='총 플레이어')

이런식으로요..

여기는 html 코드에 대한 이스케이핑이 없나봅니다..

**Comment by ryush00** [comment]
총 접속자수는 `/servers`에 GET 요청을 보내면 표시됩니다. (간단히 말해 주소 뒤에 `/servers` 입력하면 서버 접속자 정보 뜸) 다만 최대 접속자수를 제공하지 않고 있어서 #9 를 만들었습니다.

**Comment by ryush00** [comment]
여튼 메타 태그로 하는것도 좋은 생각이라고 생각하지만, https://schema.org/GameServer 를 이용해서 하는것도 괜찮은 방법 아닐까 싶습니다.

**Comment by ryush00** [comment]
https://schema.org/GameServer 에서도 최대 접속자수 표기란은 없나 보네요. -_-.. 역시 meta 태그밖에 답이 없는걸까요...

**Comment by JJoriping** [comment]
일단 커밋 https://github.com/JJoriping/KKuTu/commit/59da57a4208e872f14dec12ef6122457bf31523c 에서 관련 구현을 해 놓았습니다.
