### ISSUE TITLE
어드민(관리자) 명령어 추가하는 방법

### ISSUE THREAD

**Issue by SkyLightQP** [JJoriping/KKuTu#80]
#yell, #tailroom 등처럼 이런 관리자 명령어를 추가할려 합니다.
yell 명령어하고 같은 기능인데 보내지는 메세지만 정해져있는 명령어입니다.
master.js에서 윗부분하고 아래부분에서 추가해도 작동되지가 않네요.

명령어를 추가할려면 어떻게 해야되나요?

**Comment by msquid** [comment]
명령어를 추가하실려면
`case "(명령어)":`
                       `//동작`
			`return null;`
을 추가하시면 됩니다.
#(명령어) 이렇게 치면 되는게 아니라
#(명령어) (값)을 치셔야 명령어가 실행됩니다.
