### ISSUE TITLE
달달소 로그인 에러 해결법 요청입니다.

### ISSUE THREAD

**Issue by foxof4545** [JJoriping/KKuTu#800]
이번에 달달소 로그인이 추가되면서 설정했고, 이미지도 올려놨는데 에러가 뜨네요.
![error1](https://user-images.githubusercontent.com/50654462/107190980-e2244600-6a2e-11eb-9455-d0dbc5a1059c.PNG)
![error2](https://user-images.githubusercontent.com/50654462/107190990-e486a000-6a2e-11eb-85c1-4996de4ea033.PNG)

**Comment by lshqqytiger** [comment]
권한이 다음과 같을 때 존재해야 할 .profile.image를 불러오려 해서 발생한 오류로 보입니다.

![1](https://user-images.githubusercontent.com/39524005/107208623-33d7cb00-6a45-11eb-9a3d-4c689078b0dc.PNG)

auth_daldalso.js 파일 내
```$p.image = o.profile.image;```
부분을 다음과 같이 임시로 수정해주세요.
```$p.image = 'https://daldal.so/anonymous.png';```

**Comment by foxof4545** [comment]
감사합니다. 해결되었습니다. 이슈 닫겠습니다.
