### ISSUE TITLE
 DB is ready. 가 뜨지 않습니다

### ISSUE THREAD

**Issue by Aurorarain** [JJoriping/KKuTu#802]
C:\Users\user\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server>node lib\Game\cluster.js 0 1
[2021-02-09 14:22:18] << KKuTu Server:8496 >>

한 10분정도 기다렸는데 뜨지 않습니다

**Comment by lshqqytiger** [comment]
#790 을 참고해보세요.

**Comment by jhj1228** [comment]
[#790](https://github.com/JJoriping/KKuTu/issues/790) 

DB를 구버전으로 바꿔서 실행해보세요.

**Comment by Aurorarain** [comment]
저 db 9.5입니다

**Comment by lshqqytiger** [comment]
11, 13도 시도해보세요

**Comment by starprica** [comment]
nodejs버전을 10으로 해보세요

**Comment by Aurorarain** [comment]
해결됬으니 닫겠습니다
