### ISSUE TITLE
위치 오류

### ISSUE THREAD

**Issue by Aurorarain** [JJoriping/KKuTu#805]
![끄투](https://user-images.githubusercontent.com/78781863/108020553-f6d09180-705f-11eb-9c3b-6836e34647bf.PNG)
위치가 좀 잘못된거 같은데 이게 어떻게 된일인가요

**Comment by qkrehddls** [comment]
CSS가 깨진거같은데요?

**Comment by Aurorarain** [comment]
어떤 파일을 수정해야할까요..?

**Comment by qkrehddls** [comment]
접속 가능한 IP나 주소를 주실수 있나요?

**Comment by Aurorarain** [comment]
http://aurorakkutu.kro.kr/

**Comment by lshqqytiger** [comment]
kkutu.pug
layout.pug
in_game_kkutu.css
in_kkutu.css

위 파일들을 원본으로 교체해보세요.

**Comment by Aurorarain** [comment]
kkutu.pug 파일을 교체하니까 되네요 :)
