### ISSUE TITLE
프로필 관리가 눌리지 않습니다

### ISSUE THREAD

**Issue by Aurorarain** [JJoriping/KKuTu#807]
닉네임 변경을 추가하였는데 프로필 관리가 눌리지 않는 버그가 생겼습니다

**Comment by lshqqytiger** [comment]
개발자 도구에 남은 에러 로그를 첨부해주세요.
아마 kkutu.pug를 잘못 수정하신 것 같습니다.

**Comment by jhj1228** [comment]
닉네임 변경 기능을 구현했을 때 칼럼도 같이 만들었나요?

**Comment by Aurorarain** [comment]
아 아니요..?

**Comment by jhj1228** [comment]
> 아 아니요..?

닉네임 기능 구현할 때 칼럼도 필요합니다.

**Comment by kdhkr** [comment]
#689 
**1. 이곳은 끄투 서버 자체의 문제점만을 기술하시기 바랍니다.**
다른 사람의 풀 리퀘스트(PR)나 소스 코드를 사용함에 따라 발생하는 문제는 그곳에서 질문하시기 바랍니다. 이곳은 끄투 본연의 소스 코드 혹은 머지(Merge)된 소스 코드에서 발생한 문제점만 도와드리고 있습니다.
> 아래와 같은 이슈들은 답변을 드리기가 어렵습니다.
> - 서버 외부 접속이 안돼요. (방화벽 설정을 확인해주세요.)
> - 도메인을 연결할 수 없어요. (끄투와 관련성이 없는 질문입니다.)
> - 풀 리퀘스트에 있는 소스 코드를 적용했는데 제대로 작동하지 않아요. (해당 풀 리퀘스트에 문제점을 남겨주세요.)

**Comment by Aurorarain** [comment]
아 넵
