### ISSUE TITLE
끄투 외부 접속 어캐하죠?

### ISSUE THREAD

**Issue by SuperSalt27** [JJoriping/KKuTu#808]
서버를 만들었는데 외부에서 접속하려면 어떻게 해야하는지 알려주실 수 있나요? 다른데 다 찾아봤는데 안나와서...

**Comment by lshqqytiger** [comment]
웹서버 포트, 게임서버 포트 전부 포트포워딩, 방화벽 포트 개방 (인바운드 규칙) 후 IP 주소로 접속 or IP 주소로 포워딩된 도메인으로 접속

**Comment by SuperSalt27** [comment]
웹/게임 서버 포트 어디서 확인하나요?

**Comment by lshqqytiger** [comment]
따로 건든게 없다면 80, 8080, 8496, 443(HTTPS) 입니다.
기존 이슈 #783 만 참고해도 충분히 해결 가능합니다.

**Comment by jhj1228** [comment]
일부 공유기에 한해 80포트가 차단되어 있는 경우도 있으니 이 점 유의해 주세요.

**Comment by msrykkutuzard** [comment]
혹시나 방법을 못 찾았다면 두엿#3562로 DM 주세요.
원격으로 해드립니다.
