### ISSUE TITLE
서버 접속시 로그인 오류

### ISSUE THREAD

**Issue by SuperSalt27** [JJoriping/KKuTu#809]
도메인까지 만들고 로그인 설정 몇개 해놨는데 로그인 하고 게임에 들어가면 로그인이 풀립니다.

**Comment by kdhkr** [comment]
#79
Redis를 설치하지 않으셨을 경우 세션 기능이 작동하지 않는 점 참고 부탁드립니다.

**Comment by SuperSalt27** [comment]
Radis 설치했는데 그래요

**Comment by SuperSalt27** [comment]
문제 해결 했습니다. 클로스 할게요
