### ISSUE TITLE
위쪽에 있는 검색이랑 쪼롤로 이동되는걸 바꿀수있나요?

### ISSUE THREAD

**Issue by DevloperCheongwol** [JJoriping/KKuTu#81]
제목그대로입니다!

**Comment by JJoriping** [comment]
안녕하세요. 페이지 상단 메뉴는 [이 쪽](https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/views/module.pug#L56)에서 변경할 수 있습니다.

**Comment by DevloperCheongwol** [comment]
만약 저부분에서 검색을 지울라면
div#quick-search 를 부분을 지우면 되요?
