### ISSUE TITLE
아이템을 추가했는데 왜 상점이 없어지고 안보이는걸까요?

### ISSUE THREAD

**Issue by msrykkutuzard** [JJoriping/KKuTu#811]
![깃허브 이슈 1](https://user-images.githubusercontent.com/77523545/108595367-cc196c80-73c2-11eb-8b6d-8ca350a423e8.PNG)
![깃허브 이슈 2](https://user-images.githubusercontent.com/77523545/108595368-cd4a9980-73c2-11eb-902b-15dbecbb4351.PNG)
지금 이런식으로 아이템을 추가 하고 파일 확장명 까지 똑같게 했는데 적용 하고 나면 상점이 안보여지는 버그입니다.
이거는 어떻게 수정해야지 정상적으로 할수 있을까요?

**Comment by lshqqytiger** [comment]
가격 값이 -1이면 상점 구매 불가합니다.

**Comment by msrykkutuzard** [comment]
아 그게 아니라 -1에서 100으로 바꾸면 상점이 안보여지는 겁니다

**Comment by Flug893** [comment]
아이템을 추가할 경우 서버를 껐다 켜야 상점이 로딩됩니다

**Comment by msrykkutuzard** [comment]
잠깐만요 서버 껏다가 키고 안되면 말씀드릴게요

**Comment by msrykkutuzard** [comment]
됬네요 이슈 닫겠습니다.
