### ISSUE TITLE
주석 풀라는데...

### ISSUE THREAD

**Issue by SuperSalt27** [JJoriping/KKuTu#812]
자꾸 이슈 올려서 죄송합니다.

#809 에서 도움받고 Radis관련 주석:
```
	/* use only for redis-installed
	store: new Redission({
		client: Redis.createClient(),
		ttl: 3600 * 12
	}),*/
```
이걸 풀었는데 이 주석이 아닌지 오류가 납니다.

ReplyError: ERR wrong number of arguments for 'set' command at parseError (C:\Users\user\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:193:12) at parseType (C:\Users\user\KKuTu-master\Server\lib\node_modules\redis-parser\lib\parser.js:303:14)

**Comment by norhu1130** [comment]
redis가 제대로 설치되었는지 확인해주세요.
[ 우분트등 리눅스환경은 redis-server커맨드를 실행해야합니다 ]
 	store: new Redission({
		client: Redis.createClient(),
		ttl: 3600 * 12
	})

**Comment by lshqqytiger** [comment]
redis-server 프로세스가 실행 중인지 확인해주세요.

**Comment by SuperSalt27** [comment]
최신버전인데요..

**Comment by kdhkr** [comment]
@norhu1130 일단 디렉토리 구조부터 윈도우 환경이라는게 보이는데..

Redis가 설치되었고 정상적으로 작동 중인지 다시 한번 확인해보세요.
Windows 버전의 Redis 서버는 [이곳](https://github.com/tporadowski/redis/releases)에서 내려받으실 수 있습니다.

**Comment by SuperSalt27** [comment]
> @norhu1130 일단 디렉토리 구조부터 윈도우 환경이라는게 보이는데..
> 
> Redis가 설치되었고 정상적으로 작동 중인지 다시 한번 확인해보세요.
> Windows 버전의 Redis 서버는 [이곳](https://github.com/tporadowski/redis/releases)에서 내려받으실 수 있습니다.

@kdhkr 감사합니다. 이 사이트 들어가보니 최신버전이 있었네요.
