### ISSUE TITLE
run.bat 실행도중 JS 에러

### ISSUE THREAD

**Issue by sjkim04** [JJoriping/KKuTu#813]
node.js 설치, 데이터베이스 구축 등 설정 끝내고 run.bat 실행해보니
![image](https://user-images.githubusercontent.com/38371178/108682104-41a44a80-7533-11eb-8787-c27a6fd1b8a4.png)
이런 에러가 뜨네요
node 관련 에러 같은데.. 정확히 잘 모르겠어서 이렇게 이슈 남깁니다

--스펙--
Windows 8.1 K 64x / Intel Core i5-3337U CPU @ 1.80Ghz / 4GB RAM

**Comment by qkrehddls** [comment]
./server-setup.bat 하셨나요?

**Comment by sjkim04** [comment]
그거 안하면 run.bat이 안뜨는 걸로 알고 있는데

**Comment by sjkim04** [comment]
지금 ./server-flush.bat 하고 다시 실행중입니다

**Comment by qkrehddls** [comment]
서버 디렉토리에서 npm install colors 해보세요

**Comment by sjkim04** [comment]
설치가 안됐었네요;;
일단 프로그램은 실행됐는데
![image](https://user-images.githubusercontent.com/38371178/108683955-9c3ea600-7535-11eb-9a60-19bedc655251.png)
이건 또 뭐지.. ws 설치하면 되나요?

**Comment by sjkim04** [comment]
설치가 안됐었네요..
감사합니다!
