### ISSUE TITLE
DB를 다른파일로..

### ISSUE THREAD

**Issue by yangdoyun446** [JJoriping/KKuTu#814]
DB 파일을 다른 형식으로 제공하지 않습니까?

**Comment by qkrehddls** [comment]
현재로써는 Postgresql 형식의 DB파일 밖에 제공하지 않습니다 pg2mysql 같은걸로 변환한 후에 코드 수정해서 사용하실수 있습니다

**Comment by lshqqytiger** [comment]
내용이 너무 간략하여 어떤 상황인지 파악하기가 어렵습니다.
다른 형식의 파일이 왜 필요한지, 현재 문제 상황이 무엇인지 정확하게 적어주셔야 더 정확도 높은 답변이 가능합니다.
