### ISSUE TITLE
SSL을 적용 했는데, 이상한 오류가 뜨면서 서버가 고장납니다.

### ISSUE THREAD

**Issue by msrykkutuzard** [JJoriping/KKuTu#815]
![캡처](https://user-images.githubusercontent.com/77523545/108838671-4d693d00-7617-11eb-8897-17be7b516fe5.PNG)
SSL을 global.json에서 적용한후 게임서버를 실행해보니 수많은 워커들이 죽어가면서 실행이 안됩니다.
이런 오류는 어떻게 하면 될까요?

**Comment by lshqqytiger** [comment]
/root/KKuTu/private.key 파일이 존재하지 않습니다.

**Comment by msrykkutuzard** [comment]
잠깐만여

**Comment by msrykkutuzard** [comment]
제가 영어를 읽지 못해서;;; 죄송합니다 무분별한 이슈때매 
닫겠습니다.
