### ISSUE TITLE
단어 대결 주제를 추가했더니 다음과같이 오류를 뿜습니다

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#828]
C:\Users\spang\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\const.js:195 }; ^ SyntaxError: Unexpected token ';' at wrapSafe (internal/modules/cjs/loader.js:915:16) at Module._compile (internal/modules/cjs/loader.js:963:27) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\spang\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\secure.js:24:15) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

근데 솔직히 단어대결 문제는 아닌거같은데.. 왜이럴까요?

**Comment by andjsrk** [comment]
파일 내용을 정확히 어떻게 변경하셨나요?

**Comment by Seburancev** [comment]
> const.js 파일의 내용을 정확히 어떻게 변경하셨나요?

저같은 경우는 #222 참고했습니다

**Comment by Seburancev** [comment]
결국엔 const js 주제떄문에 그런게 맞는거같네요. 이슈닫습니다. 해결됬으니

**Comment by Seburancev** [comment]
재오픈합니다. 계속 똑같이 뜨네요 단어대결 주제떄문 맞는거같네요..

**Comment by Seburancev** [comment]
![캡처](https://user-images.githubusercontent.com/80502528/110931430-989c8300-836d-11eb-968b-eb046807dddf.PNG)
![캡처2](https://user-images.githubusercontent.com/80502528/110931448-9df9cd80-836d-11eb-8027-b68419a77705.PNG)

이거 보고 답변 부탁드리겠습니다..

**Comment by lshqqytiger** [comment]
...오류 메시지를 제발 읽어주세요.
const.js 195번째줄에서 문법 오류.
세미콜론이 존재하면 안되는 곳에 세미콜론이 존재.
