### ISSUE TITLE
맨 아래 설명란은 어떻게 바꾸는지..

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#829]
로비/게임 등 맨 아래에 있는 이거 어떻게 수정하나요?
글자로 놀자! 끄투 온라인 Copyright (C) {년도} {배포자}({이메일 등})
이 프로그램은 제품에 대한 어떠한 형태의 보증도 제공되지 않습니다.
이 프로그램은 자유 소프트웨어이며 배포 규정을 만족시키는 조건 아래 자유롭게 재배포할 수 있습니다.
이에 대한 자세한 사항은 본 프로그램의 구현을 담은 다음 레포지토리에서 확인하십시오: {이 서버의 소스 코드 위치}

**Comment by kdhkr** [comment]
#689 
[https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0#%EC%A0%80%EC%9E%91%EA%B6%8C-%EA%B4%80%EB%A0%A8-%EC%A0%95%EB%B3%B4-%EC%96%91%EC%8B%9D](https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0#%EC%A0%80%EC%9E%91%EA%B6%8C-%EA%B4%80%EB%A0%A8-%EC%A0%95%EB%B3%B4-%EC%96%91%EC%8B%9D) 참고 바랍니다.

**Comment by Seburancev** [comment]
> #689
> https://github.com/JJoriping/KKuTu/wiki/%EB%82%B4-%EC%84%9C%EB%B2%84-%EB%93%B1%EB%A1%9D%ED%95%98%EA%B8%B0#%EC%A0%80%EC%9E%91%EA%B6%8C-%EA%B4%80%EB%A0%A8-%EC%A0%95%EB%B3%B4-%EC%96%91%EC%8B%9D 참고 바랍니다.

앗 알겠습니다.. 다음부터 조심하겠습니다..
