### ISSUE TITLE
구글 로그인과 기타 질문들

### ISSUE THREAD

**Issue by magpie720** [JJoriping/KKuTu#83]
1. 구글 API 관리자에서 클라이언트 ID와 비밀번호를 발급받아 jauth.js에 입력하였습니다.
그후 구글 로그인 창도 잘 뜨고 넘어가는데 http://주소/register 에서 Unauthorized 라는 에러가 발생하고 로그인이 되지 않습니다.
2. 데이터베이스의 직접적인 수정 방법이 궁금합니다. pgAdmin4 로 시도해보았지만 제가 방법을 모르는건지 cost나 money 같은 값들을 직접 수정하는 방법을 찾을수가 없었습니다
3. 서버당 최대인원을 조절하는 방법이 궁금합니다

**Comment by BasixKOR** [comment]
한 문제당 하나의 이슈를 만드는 것이 이슈 트래킹에 더욱 효율적입니다. 굳이 수정하실 필요는 없지만요..!

**Comment by BasixKOR** [comment]
1. 혹시 콜백 URL을 설정하셨는지요? 아마 위키와 이미 닫힌 이슈들의 답안에서 해결방법을 확인하실 수 있습니다.
2. 이 이슈는 phpPgAdmin에 문의하셔야 할 것 같습니다. 아니면 주변에 물어보셔도 괜찮고요!
3. const.js의 맨 윗줄, `exports.KKUTU_MAX = 400`을 수정하시면 됩니다. 각각 설정하시는 경우에는 소스코드에 직접적인 수정이 필요합니다.

**Comment by magpie720** [comment]
감사합니다 일단 확인해보겠습니다

**Comment by BasixKOR** [comment]
무슨 일이신가요? :-)

**Comment by magpie720** [comment]
구글 로그인 문제는 해결했습니다만
const.js의 맨 윗줄, exports.KKUTU_MAX = 400을 수정하여도 최대 인원수가 변하지 않았습니다.
서버는 감자서버 1개만 사용중이고 최대 인원수를 줄이고자 합니다

**Comment by BasixKOR** [comment]
서버 재부팅 이후에도 그러한가요?

**Comment by magpie720** [comment]
네 그렇습니다

**Comment by BasixKOR** [comment]
그렇다면 버그인 지도 모르겠네요. @JJoriping

**Comment by magpie720** [comment]
별도로 위에는 없었던 질문입니다만, 카카오톡 같은곳에서 링크 주소를 입력하면
"쪼롤 - League of Legends 정보.. 롤 전적검색은 JJO.KR"
이렇게 나옵니다. lib\Web\views 파일들의 title을 변경해주었는데도 변함이 없었습니다
다른 방법으로 바꾸어야 하는건가요?

**Comment by BasixKOR** [comment]
브라우저의 캐시가 문제일 수 있습니다. 브라우저 캐시를 초기화해보십시오.

**Comment by magpie720** [comment]
데이터 삭제 후에도 동일합니다

**Comment by magpie720** [comment]
프로필 관리에서 소개 한마디가 적용되지 않는 문제도 있는것 같습니다

**Comment by JJoriping** [comment]
안녕하세요. 위에서도 이야기가 나왔지만 다른 분들을 위해 되도록 한 이슈에는 한 주제만 이야기하기를 권장합니다.
1. 상수 `exports.KKUTU_MAX`의 값은 서버가 취급합니다. 클라이언트는 `./Server/lib/Web/lib/in_portal.js` 파일의 `LIMIT` 값을 설정해야 합니다.
1. 카카오 측에서도 캐싱을 하고 있을 것이기 때문에 카카오톡에서 반영되기까지 시간이 걸릴 수 있습니다.

**Comment by BasixKOR** [comment]
https://developers.kakao.com/docs/cache 카카오톡 캐시를 삭제하는 서비스를 카카오 측에서 제공중입니다.

**Comment by magpie720** [comment]
답변 감사합니다. 
./Server/lib/Web/lib/in_portal.js 파일의 LIMIT 값을 설정하고 서버를 재시작 해보았으나 변화가 없습니다

**Comment by JJoriping** [comment]
https://github.com/JJoriping/KKuTu/wiki/C~Gruntfile.js
클라이언트 소스 코드를 수정한 뒤에 grunt 작업을 해 주시기 바랍니다.

**Comment by magpie720** [comment]
해결하였습니다. 감사합니다
