### ISSUE TITLE
관리자 페이지에서 추가한 단어는 수정, 삭제가 되는것인가요?

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#830]
db.sql 에서는 추가한 단어는 보이지 않는데..
실제 추가하면 게임에서 적용은 되네요
단어를 잘못 생성에서 삭제를 할려하는데,
관리자 페이지에서 생성이 되는 단어들은 어디에서 추가가 되는건가요?

**Comment by legendkkutu** [comment]
관리자 페이지에서 단어를 직접 삭제할 수 있습니다. '끄투 DB 다루기' 항목에서 단어를 입력하고 '조회' 버튼을 누르면 단어의 정보가 나오는데, 거기서 'X' 버튼을 누르고 '적용' 버튼을 누르면 단어를 삭제할 수 있습니다.

**Comment by jhj1228** [comment]
관리자 페이지에서 단어를 직접 삭제할 수 있습니다. '끄투 DB 다루기' 항목에서 단어를 입력하고 '조회' 버튼을 누르면 단어의 정보가 나오는데, 거기서 'X' 버튼을 누르고 '적용' 버튼을 누르면 단어를 삭제할 수 있습니다.

**Comment by lshqqytiger** [comment]
db.sql은 백업 파일일 뿐, 그 파일에 DB의 변경 사항을 저장하지 않습니다.
관리자페이지 또는 pgAdmin 등을 사용해 DB를 수정할 수 있습니다.

**Comment by Seburancev** [comment]
두분 다 감사합니다! 이슈 닫겠습니다
