### ISSUE TITLE
주제를 삭제했을때, 그 주제의 단어들을 삭제하지 않았다면 단어는 그대로 사용이 가능한가요?

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#832]
저는 주제를 없앴는데 제가 옛날에 추가한 단어가 아직 남아있는거같아 말씀드립니다..
관리자 페이지에도 단어가 있다고 나오네요

**Comment by lshqqytiger** [comment]
주제를 없앤다고 단어가 없어지는건 아닙니다.
DB에서 지워주세요

**Comment by Seburancev** [comment]
감사합니다 도움됬습니다
