### ISSUE TITLE
https 오류

### ISSUE THREAD

**Issue by Aurorarain** [JJoriping/KKuTu#835]
안녕하세요 zerossl로 https연결을 했습니다. 인증서를 다운받고 global.json에 적용하였습니다. 443포트를 열고 서버를 켰는데 엑세스가 거부됬다고 뜹니다.

main.js를 80에서 443으로 변경하면 응답하는데 시간이 너무 오래 걸린다고 하고
events.js:167 throw er; // Unhandled 'error' event ^ Error: bind EADDRINUSE null:443 at listenOnMasterHandle (net.js:1397:16) at shared (internal/cluster/child.js:115:3) at Worker.send (internal/cluster/child.js:86:7) at process.onInternalMessage (internal/cluster/utils.js:42:8) at process.emit (events.js:187:15) at emit (internal/child_process.js:797:12) at process._tickCallback (internal/process/next_tick.js:174:19) Emitted 'error' event at: at listenOnMasterHandle (net.js:1398:21) at shared (internal/cluster/child.js:115:3) [... lines matching original stack trace ...] at process._tickCallback (internal/process/next_tick.js:174:19)
이라는 오류가 나옵니다. 어떻게 해야할까요?

**Comment by qkrehddls** [comment]
443포트를 다른 프로세스가 사용중인거 같습니다

**Comment by Aurorarain** [comment]
443포트를 다른 프로세스가 사용중이네요.

**Comment by Aurorarain** [comment]
혹시 종료하는법이 있나요?

**Comment by qkrehddls** [comment]
윈도우 환경이신가요 리눅스 환경이신가요

**Comment by Aurorarain** [comment]
윈도우 환경입니다.

**Comment by qkrehddls** [comment]
netstat -nao | findstr 433
taskkill /f /pid (443 포트를 사용중인 프로세스의 PID)

**Comment by Aurorarain** [comment]
C:\Users\user>netstat -nao | findstr 433

C:\Users\user>taskkill /f /pid 443
오류: 프로세스 "443"을(를) 찾을 수 없습니다.

C:\Users\user>

**Comment by qkrehddls** [comment]
taskkill에서 443 말고 (443 포트를 사용중인 프로세스의 PID) 를 적으셔야합니다

**Comment by Aurorarain** [comment]
tasklist 에는 없지만 netstat /a 에는 443포트가 있습니다

**Comment by Aurorarain** [comment]
네 알겠습니다

**Comment by qkrehddls** [comment]
netstat -nao | findstr 443 해서 나온거 보내주세요

**Comment by Aurorarain** [comment]
TCP    0.0.0.0:443            0.0.0.0:0              LISTENING       6064
  TCP    192.168.0.4:49857      23.201.36.11:443       CLOSE_WAIT      12196
  TCP    192.168.0.4:50505      185.199.110.133:443    ESTABLISHED     2664
  TCP    192.168.0.4:50516      162.159.133.234:443    ESTABLISHED     2664
  TCP    192.168.0.4:50534      15.164.81.167:443      ESTABLISHED     2664
  TCP    192.168.0.4:50535      54.180.75.25:443       ESTABLISHED     2664
  TCP    192.168.0.4:50638      172.217.31.174:443     TIME_WAIT       0
  TCP    192.168.0.4:50666      172.217.25.78:443      TIME_WAIT       0
  TCP    192.168.0.4:50680      216.58.197.243:443     TIME_WAIT       0
  TCP    192.168.0.4:50684      211.231.101.139:443    ESTABLISHED     2664
  TCP    192.168.0.4:50685      211.231.101.139:443    ESTABLISHED     2664
  TCP    192.168.0.4:50686      211.231.101.139:443    ESTABLISHED     2664
  TCP    192.168.0.4:50687      211.231.101.139:443    ESTABLISHED     2664
  TCP    192.168.0.4:50688      211.231.101.139:443    ESTABLISHED     2664
  TCP    192.168.0.4:50689      211.231.101.139:443    ESTABLISHED     2664
  TCP    192.168.0.4:50707      185.199.111.154:443    ESTABLISHED     2664
  TCP    192.168.0.4:50708      140.82.114.25:443      ESTABLISHED     2664
  TCP    192.168.0.4:50721      172.217.26.42:443      ESTABLISHED     2664
  TCP    192.168.0.4:50726      172.217.25.206:443     ESTABLISHED     2664
  TCP    192.168.0.4:55872      20.198.162.78:443      ESTABLISHED     4280
  TCP    192.168.0.4:56181      20.198.162.76:443      ESTABLISHED     4260
  TCP    192.168.0.4:57199      20.198.162.76:443      ESTABLISHED     4260
  TCP    192.168.0.4:57576      52.199.42.11:443       CLOSE_WAIT      2096
  TCP    192.168.0.4:65193      23.40.45.233:443       CLOSE_WAIT      5700
  TCP    192.168.0.4:65194      23.40.45.233:443       CLOS

**Comment by qkrehddls** [comment]
taskkill /f /pid 6064

**Comment by Aurorarain** [comment]
443포트가 없어졌습니다

**Comment by Aurorarain** [comment]
kkutu.cloud에 대한 액세스가 거부됨이 페이지를 볼 수 있는 권한이 없습니다.
HTTP ERROR 403

**Comment by qkrehddls** [comment]
VMWare가 443포트를 점유하고 있는데요 VMWare를 삭제하셔야할듯합니다

**Comment by Aurorarain** [comment]
알겠습니다.

**Comment by Aurorarain** [comment]
kkutu.cloud에서 응답하는 데 시간이 너무 오래 걸립니다.
events.js:167 throw er; // Unhandled 'error' event ^ Error: bind EADDRINUSE null:443 at listenOnMasterHandle (net.js:1397:16) at shared (internal/cluster/child.js:115:3) at Worker.send (internal/cluster/child.js:86:7) at process.onInternalMessage (internal/cluster/utils.js:42:8) at process.emit (events.js:187:15) at emit (internal/child_process.js:797:12) at process._tickCallback (internal/process/next_tick.js:174:19) Emitted 'error' event at: at listenOnMasterHandle (net.js:1398:21) at shared (internal/cluster/child.js:115:3) [... lines matching original stack trace ...] at process._tickCallback (internal/process/next_tick.js:174:19)
[2021-03-27 17:58:32] Exit web server #1
Worker 912 died
W: CLOSED WITH CODE 0
zerossl의 It looks like your certificate has not been installed yet. Please check for errors and try again. 오류도 포함되나요?

**Comment by qkrehddls** [comment]
netstat -nao | findstr 443 해서 나온거 보내주세요

**Comment by Aurorarain** [comment]
TCP    192.168.0.4:49676      40.126.35.129:443      TIME_WAIT       0
  TCP    192.168.0.4:49698      52.78.231.108:443      TIME_WAIT       0
  TCP    192.168.0.4:49700      172.217.25.234:443     TIME_WAIT       0
  TCP    192.168.0.4:49705      172.217.161.42:443     TIME_WAIT       0
  TCP    192.168.0.4:49707      54.180.75.25:443       TIME_WAIT       0
  TCP    192.168.0.4:49708      140.82.114.25:443      ESTABLISHED     9388
  TCP    192.168.0.4:49709      138.91.136.108:443     TIME_WAIT       0
  TCP    192.168.0.4:49736      23.59.72.58:443        ESTABLISHED     11288
  TCP    192.168.0.4:49744      52.198.155.53:443      CLOSE_WAIT      13196
  TCP    192.168.0.4:49745      54.230.62.21:443       TIME_WAIT       0
  TCP    192.168.0.4:49747      3.34.110.13:443        ESTABLISHED     13196
  TCP    192.168.0.4:49749      54.230.155.103:443     TIME_WAIT       0
  TCP    192.168.0.4:49769      23.40.45.233:443       ESTABLISHED     13360
  TCP    192.168.0.4:49770      23.40.45.233:443       ESTABLISHED     13360
  TCP    192.168.0.4:49771      23.213.13.41:443       CLOSE_WAIT      13360
  TCP    192.168.0.4:49776      52.109.12.19:443       TIME_WAIT       0
  TCP    192.168.0.4:49795      23.40.45.233:443       ESTABLISHED     13360
  TCP    192.168.0.4:49800      172.217.175.110:443    TIME_WAIT       0
  TCP    192.168.0.4:49802      216.58.197.163:443     TIME_WAIT       0
  TCP    192.168.0.4:49808      34.64.4.80:443         TIME_WAIT       0
  TCP    192.168.0.4:49816      172.217.161.78:443     TIME_WAIT       0
  TCP    192.168.0.4:49820      13.225.112.109:443     TIME_WAIT       0
  TCP    192.168.0.4:49821      104.18.72.113:443      TIME_WAIT       0
  TCP    192.168.0.4:49831      104.18.72.113:443      TIME_WAIT       0
  TCP    192.168.0.4:49833      104.16.51.111:443      TIME_WAIT       0
  TCP    192.168.0.4:49834      44.225.112.240:443     TIME_WAIT       0
  TCP    192.168.0.4:49845      40.126.52.150:443      ESTABLISHED     10848
  TCP    192.168.0.4:49855      52.78.231.108:443      ESTABLISHED     9388
  TCP    192.168.0.4:49856      185.199.110.133:443    ESTABLISHED     9388
  TCP    192.168.0.4:49857      172.217.161.78:443     TIME_WAIT       0
  TCP    192.168.0.4:49858      172.217.31.131:443     TIME_WAIT       0
  TCP    192.168.0.4:49861      172.217.26.14:443      TIME_WAIT       0
  TCP    192.168.0.4:49867      54.180.75.25:443       ESTABLISHED     9388
  TCP    192.168.0.4:49868      172.217.26.54:443      ESTABLISHED     9388
  TCP    192.168.0.4:49869      172.217.161.66:443     ESTABLISHED     9388
  TCP    192.168.0.4:49873      216.58.197.225:443     ESTABLISHED     9388
  TCP    192.168.0.4:49874      172.217.26.1:443       ESTABLISHED     9388
  TCP    192.168.0.4:49875      172.217.25.234:443     ESTABLISHED     9388
  TCP    192.168.0.4:49883      211.117.24.110:443     ESTABLISHED     9388
  TCP    192.168.0.4:49884      211.117.24.110:443     ESTABLISHED     9388
  TCP    192.168.0.4:49887      39.117.36.61:443       SYN_SENT        9388
  TCP    192.168.0.4:49888      39.117.36.61:443       SYN_SENT        9388
  TCP    192.168.0.4:49889      39.117.36.61:443       SYN_SENT        9388
  TCP    192.168.0.4:49893      204.79.197.200:443     ESTABLISHED     7940
  TCP    192.168.0.4:49894      204.79.197.200:443     ESTABLISHED     7940
  TCP    192.168.0.4:49895      204.79.197.222:443     ESTABLISHED     7940

**Comment by qkrehddls** [comment]
재부팅 해보시고 다시 서버를 켜보세요

**Comment by Aurorarain** [comment]
같은 오류가 납니다.

**Comment by Aurorarain** [comment]
오 감사합니다 들어가집니다
