### ISSUE TITLE
서버 증설 오류

### ISSUE THREAD

**Issue by ghost** [JJoriping/KKuTu#836]
settings.json의 "game-num-inst"값을 늘려보고 서버를 켜도 오류밖에 안뜨고 게임서버가 한개 켜집니다.
어찌 해야할까요??

**Comment by lshqqytiger** [comment]
어떤 오류가 뜨는지 알려주셔야 도움을 드릴 수가 있습니다.

**Comment by jhj1228** [comment]
서버 값만 늘려놓고 포트를 안열으섰다면 당연히 서버가 1개만 켜지죠..

**Comment by lshqqytiger** [comment]
[global.json](https://github.com/JJoriping/KKuTu/blob/3ed4bfdfa69c99c51e03a853d9052f79eda3f926/Server/lib/sub/global.inc.json#L3)도 수정하셨는지 확인해보세요.

**Comment by norhu1130** [comment]
@JJoriping 해당 유저는 삭제되었습니다.
따라서 이슈 클로즈가 불가능합니다.
클로즈처리 부탁드립니다.
