### ISSUE TITLE
이번에는 이런 에러가 떠요...

### ISSUE THREAD

**Issue by wkddndud12** [JJoriping/KKuTu#842]
[2021-04-04 16:28:09] OAuth Strategy spotify is not loaded
[2021-04-04 16:28:09] OAuth2Strategy requires a clientID option
[2021-04-04 16:28:09] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2021-04-04 16:28:09] Game server #1 closed: 1006
C:\Users\MASTER\Desktop\ㄲㅌ\Server\lib\node_modules\pg\lib\connection.js:454 throw new Error("Unknown authenticationOk message type" + util.inspect(msg)); ^ Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } at Connection.parseR (C:\Users\MASTER\Desktop\ㄲㅌ\Server\lib\node_modules\pg\lib\connection.js:454:9) at Connection.parseMessage (C:\Users\MASTER\Desktop\ㄲㅌ\Server\lib\node_modules\pg\lib\connection.js:370:17) at Socket.&lt;anonymous> (C:\Users\MASTER\Desktop\ㄲㅌ\Server\lib\node_modules\pg\lib\connection.js:129:22) at Socket.emit (events.js:314:20) at addChunk (_stream_readable.js:297:12) at readableAddChunk (_stream_readable.js:272:9) at Socket.Readable.push (_stream_readable.js:213:10) at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Worker 9844 died
W: CLOSED WITH CODE 0

**Comment by wkddndud12** [comment]
해결 방안 없나요?

**Comment by TyphoonDANAS** [comment]
node.js 버전이 몇이신가요?

**Comment by lshqqytiger** [comment]
PostgreSQL, pg 모듈, Node.js 간 호환 문제로 인해 발생하는 문제로 보입니다.
PostgreSQL 11.0
pg 6.4.2
Node.js 12.21.0
으로 맞추신 후 다시 시도해보세요.

**Comment by wkddndud12** [comment]
node-v12.22.0-x64 입니다

**Comment by lshqqytiger** [comment]
PostgreSQL과 pg 버전도 확인해주세요.

**Comment by wkddndud12** [comment]
postgreSQL 11.11 도 괜찮죠?

**Comment by lshqqytiger** [comment]
pg 버전은요
