### ISSUE TITLE
createdb -U "postgres" "main" 하는데 오류가 발생합니다

### ISSUE THREAD

**Issue by CHEEY-BORIN** [JJoriping/KKuTu#843]
createdb: database creation failed: ERROR:  database "main" already exists
이라고 오류가 뜹니다

참고로 저는 9.3버전입니다.

**Comment by lshqqytiger** [comment]
createdb: database creation failed: ERROR: database "main" already exists
createdb: 데이터베이스 만들기 실패: 에러: 데이터베이스 "main" 이미 존재

DB 구축이 이미 된 상태입니다.

**Comment by JNHA123** [comment]
만약 psql -U "postgres" -d "main" -f "(경로)" 하시고 비밀번호 쳤을때 DB 구축이 안됬다면, PostgreSQL을 지우시고,
C:\Program Files에 있는 PostgreSQL 디렉토리도 지우세요, 그리고 나서 새로 다시 PostgreSQL를 설치하시고 다시 DB 작업을 하시면
잘될듯 합니다. (전 수많은 오류 경험을 해봤기 때문에 이런걸 압니다(?)
