### ISSUE TITLE
서버 문제

### ISSUE THREAD

**Issue by CHEEY-BORIN** [JJoriping/KKuTu#844]
node:internal/modules/cjs/loader:927 throw err; ^ Error: Cannot find module './sub/global.json' Require stack: - E:\KKuTu-master (2)\KKuTu-master\Server\lib\const.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Game\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15) at Function.Module._load (node:internal/modules/cjs/loader:769:27) at Module.require (node:internal/modules/cjs/loader:996:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (E:\KKuTu-master (2)\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (node:internal/modules/cjs/loader:1092:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) at Module.load (node:internal/modules/cjs/loader:972:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:996:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\const.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Game\\cluster.js' ] }
G: CLOSED WITH CODE 1
node:internal/modules/cjs/loader:927 throw err; ^ Error: Cannot find module '../sub/global.json' Require stack: - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\db.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\main.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15) at Function.Module._load (node:internal/modules/cjs/loader:769:27) at Module.require (node:internal/modules/cjs/loader:996:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (node:internal/modules/cjs/loader:1092:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) at Module.load (node:internal/modules/cjs/loader:972:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:996:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\db.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\main.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\cluster.js' ] }
Worker 16880 died
W: CLOSED WITH CODE 0node:internal/modules/cjs/loader:927 throw err; ^ Error: Cannot find module './sub/global.json' Require stack: - E:\KKuTu-master (2)\KKuTu-master\Server\lib\const.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Game\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15) at Function.Module._load (node:internal/modules/cjs/loader:769:27) at Module.require (node:internal/modules/cjs/loader:996:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (E:\KKuTu-master (2)\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (node:internal/modules/cjs/loader:1092:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) at Module.load (node:internal/modules/cjs/loader:972:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:996:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\const.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Game\\cluster.js' ] }
G: CLOSED WITH CODE 1
node:internal/modules/cjs/loader:927 throw err; ^ Error: Cannot find module '../sub/global.json' Require stack: - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\db.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\main.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15) at Function.Module._load (node:internal/modules/cjs/loader:769:27) at Module.require (node:internal/modules/cjs/loader:996:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (node:internal/modules/cjs/loader:1092:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) at Module.load (node:internal/modules/cjs/loader:972:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:996:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\db.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\main.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\cluster.js' ] }
Worker 16880 died
W: CLOSED WITH CODE 0node:internal/modules/cjs/loader:927 throw err; ^ Error: Cannot find module './sub/global.json' Require stack: - E:\KKuTu-master (2)\KKuTu-master\Server\lib\const.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Game\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15) at Function.Module._load (node:internal/modules/cjs/loader:769:27) at Module.require (node:internal/modules/cjs/loader:996:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (E:\KKuTu-master (2)\KKuTu-master\Server\lib\const.js:19:14) at Module._compile (node:internal/modules/cjs/loader:1092:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) at Module.load (node:internal/modules/cjs/loader:972:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:996:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\const.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Game\\cluster.js' ] }
G: CLOSED WITH CODE 1
node:internal/modules/cjs/loader:927 throw err; ^ Error: Cannot find module '../sub/global.json' Require stack: - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\db.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\main.js - E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\cluster.js at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15) at Function.Module._load (node:internal/modules/cjs/loader:769:27) at Module.require (node:internal/modules/cjs/loader:996:19) at require (node:internal/modules/cjs/helpers:92:18) at Object.&lt;anonymous> (E:\KKuTu-master (2)\KKuTu-master\Server\lib\Web\db.js:22:15) at Module._compile (node:internal/modules/cjs/loader:1092:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10) at Module.load (node:internal/modules/cjs/loader:972:32) at Function.Module._load (node:internal/modules/cjs/loader:813:14) at Module.require (node:internal/modules/cjs/loader:996:19) { code: 'MODULE_NOT_FOUND', requireStack: [ 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\db.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\main.js', 'E:\\KKuTu-master (2)\\KKuTu-master\\Server\\lib\\Web\\cluster.js' ] }
Worker 16880 died
W: CLOSED WITH CODE 0

구축을 완료하고 서버를 킬려고 하는데 이런 요상한(?) 오류가 나네요..

**Comment by jhj1228** [comment]
모듈을 찾을 수 없다고 뜹니다만... global.inc.json에서 global.json로 이름을 바꿨는지 확인해보세요.

**Comment by Seburancev** [comment]
auth.inc.json > auth.json global.inc.json > global.json
그냥 삭제 말고 복사하시고 바꾸셔도 됩니다..

**Comment by jhj1228** [comment]
@CHEEY-BORIN 해결되었으면 이슈 닫아주시기 바랍니다.
