### ISSUE TITLE
"mcEnglish" , "mcKorean" 같은 것은 어느 곳에서 수정이 가능한가요? ( 게임 모드는 어떻게 추가하나요?(한국어나 영어같은)

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#845]
ko_KR.json을 보다가 게임모드가 있길래 봤는데, 어디서 수정하는지가 궁굼해서
간단하게 어디서만 수정하는지만 궁굼해서 물어봅니다

**Comment by jhj1228** [comment]
모드 구현은 대체로 classic.js에서 합니다.

**Comment by Seburancev** [comment]
그 모드가 아닌 ko_kr.json 에 있는 게임 유형을 말한겁니다.  타 프리서버인 *프 끄투나 분*끄투 같은 경우에도 한국어 유형,영어 유형 아래에 특별 유형이 있는 그걸 말한겁니다.

**Comment by jhj1228** [comment]
kkutu.pug 166~181 문단 말하는 것 같네요. 

만약 일본어모드를 추가하고 싶다! 하시면
> optgroup(label=L('mcJapanese'))
이런 식으로 추가하시면 될 것 같네요.

**Comment by Seburancev** [comment]
해결 완료. 감사합니다
