### ISSUE TITLE
const.js, ko_kr.json 에서는 정상적으로 되있으나, 인게임에선 이상합니다

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#846]
![hahahaha](https://user-images.githubusercontent.com/80502528/113708461-35a7cd00-971c-11eb-8605-a342994b3fc5.png)
(분홍끄투 소스 사용) 에서는 미션만 나와있고.
![hahahaha1](https://user-images.githubusercontent.com/80502528/113708590-625be480-971c-11eb-823f-bc86384fe187.png)
에 ko_kr.json도 정상적으로 등록이 되었습니다.
![hahahaha2](https://user-images.githubusercontent.com/80502528/113708640-73a4f100-971c-11eb-90f5-7595d6fe3317.png)
허나 인게임 내에서는 계속 이런식으로 뜹니다.

**Comment by lshqqytiger** [comment]
kkutu.pug에 게임 모드 번호가 잘못된 것으로 보입니다.

**Comment by Seburancev** [comment]
감사드립니다.
