### ISSUE TITLE
일본어 단어대결을 개발해서 거의 다 완성했는데, 마지막에 걸립니다.

### ISSUE THREAD

**Issue by Seburancev** [JJoriping/KKuTu#847]
![kkutu](https://user-images.githubusercontent.com/80502528/113815319-eca05900-97ad-11eb-8578-d050df63d59c.png)
이렇게 exports.EXAMPLE_TITLE 에다가 추가를 했더니 갑자기
![kkutu2](https://user-images.githubusercontent.com/80502528/113815408-0f327200-97ae-11eb-8030-fb25283330b0.png)기
다음과 같이 SyntaxError가 걸립니다.

**Comment by andjsrk** [comment]
"abcdefghij" 뒤에 컴마를 붙이지 않아서 생긴 문제입니다.

**Comment by Seburancev** [comment]
감사드립니다.

**Comment by jhj1228** [comment]
일반적인 메모장 말고 다른 프로그램 쓰세요. 메모장은 어느 부분에 에러났는지 알기 어려워서 추천 안해요.

**Comment by Seburancev** [comment]
좋은 답변 감사합니다.
