### ISSUE TITLE
프로필 관리에서 소개 한마디가 적용되지 않습니다

### ISSUE THREAD

**Issue by magpie720** [JJoriping/KKuTu#85]
gwalli에서 수정하면 일단 적용이 되긴 합니다만, 프로필 관리에서 직접 적용하려고 하면 확인을 눌러도 적용되지가 않습니다

**Comment by JJoriping** [comment]
프로필 관리 창이 가로로 긴 관계로 모바일 화면에서는 프로필 관리 창을 띄울 수 없도록 설계해 놓았습니다. 혹시 모종의 방법으로 띄울 수 있거나 강제로 띄우도록 설정한 부분이 있나요?

**Comment by magpie720** [comment]
아니요 없습니다.
혹시 방법이 있나요?

**Comment by JJoriping** [comment]
창을 띄우기 전에 프로필 관리 창의 가로 길이를 모바일 화면에 맞도록 직접 재구성해야 합니다. 이 작업이 완료되기 전까지는 `./Server/lib/Web/views/m_kkutu.pug` 쪽에서 해당 단추를 지워 주세요.

https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/views/m_kkutu.pug#L292

**Comment by magpie720** [comment]
모바일 프로필 관리 창은 어디에서 조절할수 있나요?
이 토픽 주제인 프로필 관리에서 소개 한마디가 적용되지 않는것도 답변 부탁드리겠습니다.

**Comment by JJoriping** [comment]
안녕하세요. 이슈를 미처 확인하지 못한 점 양해 부탁드립니다. 이 문제가 아직 해결되지 않았다면 소개 한마디를 적용하려 할 때 개발자 도구(클라이언트 측)나 콘솔(서버 측)에 특별한 메시지가 출력되지 않는지 확인해 보세요.
