### ISSUE TITLE
물음표 들어간 단어 입력시 오류 발생하는 현상 or 봇이 바보된 현상

### ISSUE THREAD

**Issue by hyusan30** [JJoriping/KKuTu#850]
![fffdf](https://user-images.githubusercontent.com/82587027/115139339-4cc7b280-a06c-11eb-8e0a-e0b893365ef5.PNG)

물음표가 포함된 단어를 입력하면 위에 있는 사진과 같은 에러가 표출됩니다. 다른 특수문자는 안뜨는데 오직 물음표가 입력되었을때에만 해당 현상이 표출됩니다.

구글링 해보니 대충 정규 표현식쪽에 오류가 있다는걸로 보여 
classic.js의 var aqs = [[ '_id', new RegExp(adv) ]]; 를 
var aqs = [[ '_id', new RegExp('adv') ]];

으로 수정하였더니 일단은 물음표를 입력하여도 잘 되더라고요
다만 그 어떤 봇도 아무런 단어도 입력하지 못하게 되었습니다. (로봇 히트는 4000으로 설정되어 있습니다.)

봇이 완전 바보가 되어버렸습니다.

어떻게 수정해야 잘 해결할 수 있을까요?

**Comment by lshqqytiger** [comment]
adv는 gameType에 따라 정해집니다.
해당 상황의 경우 KSH 게임 모드에서 adc가 "?"인 경우로 추정되며, adc가 "?"인 경우는 char가 "?"이고 (subc ? ("|"+subc) : "")가 ""인 경우입니다.
제 예상으로는, ?로 끝나는 단어를 사용하였기 때문에 char 값이 "?"가 되었고 정규 표현식에서의 ?는 앞 문자가 0회 또는 1회 반복되었다는 것을 의미하지만 앞에는 문자가 아무것도 없어서 발생하는 것으로 보입니다.
해결 방법으로는 char == "?"인 경우를 걸러내서 따로 처리하거나 하는 방법이 있겠습니다.

**Comment by hyusan30** [comment]
다른 방법으로 해결하긴 했습니다
무튼 도움주셔서 감사드립니다
