### ISSUE TITLE
외부접속

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#851]
끄투 127.0.0.1은 접속이되고
외부에서는 접속이 안되는데 어떻게 해요?
80,8080,8496 포트포워딩 했습니다. DMZ 설정도 했고요.

**Comment by ehxhfl7** [comment]
포트 포워딩을 하시고 DMZ 설정을 하신 건가요?

**Comment by wd5dw** [comment]
> 포트 포워딩을 하시고 DMZ 설정을 하신 건가요?

예

**Comment by ehxhfl7** [comment]
방화벽, 도메인 설정 확인 하셨나요?

**Comment by wd5dw** [comment]
> 방화벽, 도메인 설정 확인 하셨나요?

어떻게 하면 되나요?
방화벽은 껐습니다.

**Comment by ehxhfl7** [comment]
당연하겠지만 도메인에 본인의 외부 아이피를 연결해주시면 될 것 같습니다

**Comment by wd5dw** [comment]
> 당연하겠지만 도메인에 본인의 외부 아이피를 연결해주시면 될 것 같습니다

저는 그냥 도메인 없이 아이피로 접속할 것이라서 안했어요.

**Comment by ehxhfl7** [comment]
외부 접속이 안 된다는 게 본인이 본인 외부 아이피로 안 들어 와진다는 건가요 다른 사람들도 외부 아이피로 안 들어와진다는 건가요

**Comment by wd5dw** [comment]
> 외부 접속이 안 된다는 게 본인이 본인 외부 아이피로 안 들어 와진다는 건가요 다른 사람들도 외부 아이피로 안 들어와진다는 건가요

나와 다른 사람 모두 안들어가집니다.

**Comment by lshqqytiger** [comment]
https://ipipip.kr
에 접속 시 나오는 IP 주소로 접속하신게 맞나요

**Comment by wd5dw** [comment]
> https://ipipip.kr
> 에 접속시 나오는 IP 주소로 접속하신 게 맞나요

네

**Comment by lshqqytiger** [comment]
localhost는 되고 외부 아이피는 안된다는걸로 봐선 공유기밖에 의심이 안되는데요
공유기 설정 초기화 후 포트포워딩, DMZ 다시해보세요.

**Comment by wd5dw** [comment]
> localhost는 되고 외부 아이피는 안된다는걸로 봐선 공유기밖에 의심이 안되는데요
> 공유기 설정 초기화 후 포트포워딩, DMZ 다시해보세요.

알겠습니다.

**Comment by wd5dw** [comment]
> localhost는 되고 외부 아이피는 안된다는걸로 봐선 공유기밖에 의심이 안되는데요
> 공유기 설정 초기화 후 포트포워딩, DMZ 다시해보세요.

https://www.yougetsignal.com/tools/open-ports/
에서 체크해보니 포트가 열려있다고 뜨는데 접속은 안됩니다.

**Comment by norhu1130** [comment]
웹 서버 구동이 완료된게 확실한가요

**Comment by wd5dw** [comment]
> 웹 서버 구동이 완료된게 확실한가요

네 맞습니다. 127.0.0.1로 들어가면 연결됩니다.

**Comment by KAINNY5669** [comment]
구형 공유기이실 경우엔 같은 ip로 서버를 열고 접속할 시에 "연결이 거부되었습니다" 라는 문구가 띄워질 수 있습니다. 휴대폰의 데이터 연결로 접속해보세요.

**Comment by wd5dw** [comment]
> 일부 구형 공유기이실 경우엔 같은 ip로 서버를 열고 접속할 시에 "연결이 거부되었습니다" 라는 문구가 띄워질 수 있습니다. 휴대폰의 데이터 연결로 접속해보세요.

안되네요 ㅠㅠ
그리고 정정합니다. 포트가 열려있는지 확인시 닫혀있다고 뜹니다.
