### ISSUE TITLE
포트포워딩 실패

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#855]
![ipTIME N704BCM - Chrome 2021-04-26 오전 8_47_44 (2)](https://user-images.githubusercontent.com/75468001/116013678-62d90280-a66c-11eb-93e1-9727084adf2b.png)
iptime 192.168.0.1 사이트 접속시 위와 같이 외부ip가 192.168의 형태로 뜹니다.
다른사람 말로는 외부아이피가 저렇게 되있으면 저만 접속할 수 있다고 하는데 어떻게 해야하나요?
일단 포트포워딩은 했지만 iptime 외부아이피로 저만 접속 할 수 있습니다.

**Comment by sky-kiwi** [comment]
https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%EB%82%B4%EC%95%84%EC%9D%B4%ED%94%BC 여기서..외부아이피를 봐보시는건 어떤가요

**Comment by sky-kiwi** [comment]
그 아이피는 내부아이피입니다.

**Comment by kdhkr** [comment]
#689 참고하세요.

**Comment by wd5dw** [comment]
> #689 참고하세요.

알겠습니다. 보지도 않고 이슈 올려 죄송합니다.

**Comment by sky-kiwi** [comment]
![!!@!@!@](https://user-images.githubusercontent.com/81307722/116016188-ded84800-a676-11eb-9a02-42ea8c139ee3.PNG)


@wd5dw 이슈 닫아주세요
