### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by 124525** [JJoriping/KKuTu#856]
구글 로그인 OAuth에서 나온 아이디와 비번 제 끄투에다가 넣었는데 로그인 버튼이 안 보이네요... 따른걸 보니 뒤에 disabled를 지우라는데 그게 어디있는거죠;;;

**Comment by lshqqytiger** [comment]
`Server\lib\Web\auth` 폴더 내 auth_google.js 파일 외의 다른 파일들의 확장자를 바꾸어 login.js가 인식하지 못하게 만드시면 됩니다.

**Comment by 124525** [comment]
구글 외 나머지 js 확장자 이름을 .md라고 했는데도 안 되네요... 그리고 이상하건 구글 로그인 아이디는 .com 으로 끝나는데 이게 맞는건가요..

**Comment by lshqqytiger** [comment]
로그에
```OAuth Strategy google loaded successfully.```
이게 뜨는지 확인해주세요.

**Comment by 124525** [comment]
그런 표시들은 안 뜨고 그냥 뭐 [2021-04-27 15:52:43] @9amp0ZVIY- login, {} 이런거만 뜨는데...
이런거 알려 주는 영상 강의같은건 없나요...
``[2021-04-27 14:46:33] OAuth Strategy google is not loaded``

**Comment by lshqqytiger** [comment]
auth.inc.json을 auth.json으로 이름 수정하셨나요

**Comment by 124525** [comment]
구글 로그인 외부로 설정하지 않아서 발생한 문제 같긴 한데....
localhost로 해도 안 됩니다.
외부로 설정하지 않아서 발생한 문제는 아닌거 같습니다만...

**Comment by lshqqytiger** [comment]
그냥 아예 구글 로그인 자체를 인식을 못하고 있는 것 같습니다.

**Comment by 124525** [comment]
사용자 인증정보에 있는 OAuth 2.0 클라이언트 ID에서 준 아이디와 비번을 넣었습니다.
디스코드 로그인 구현하는 영상을 확인해 보니, 그곳에서는 OAuth2 의 Redirects에서 도메인과 /login/discord를 사용하던데
구글에서도 그것을 추가하는 기능이 있는건가요..

**Comment by ehxhfl7** [comment]
![image](https://user-images.githubusercontent.com/57280515/116200571-758a2f00-a773-11eb-91f8-21c20bc2db24.png)
이런 거 말씀 하시는 건가요?

**Comment by lshqqytiger** [comment]
`OAuth Strategy google is not loaded`
가 나왔다는 것은 auth_google.js 파일이 로드되지 못했다는 말이고 callback url과는 무관하고 그보다다 이전에 해결해야할 문제입니다.

**Comment by 124525** [comment]
[2021-04-27 16:16:34] (ex:0.0.0.0.0) @9amp0ZVIY- login, {}
[2021-04-27 16:17:12] (ex:0.0.0.0.0) @NkQDg6jV8M portal, {}
이렇게 뜨는데..
그 ``OAuth Strategy google is not loaded``는 로그 초반에 뜬 거고요
ex:0.0.0.0은 제 공인 Ip라서 가린겁니다

**Comment by lshqqytiger** [comment]
그건 그냥 접속 로그입니다.

**Comment by 124525** [comment]
지금 callback이 상관 없다는 말씀이신건가요?

**Comment by lshqqytiger** [comment]
일단 지금 로그인 버튼도 안나오는 상황 아닌가요?
그런 상황에서는 callback URL이 우선시 되어야 할 상황이 아닙니다.

**Comment by 124525** [comment]
저 서버를 껏다 다시 키니까 되는데요....ㅋㅋㅋㅋㅋ
이제는 callback을 해야 되는 건가요?

**Comment by ehxhfl7** [comment]
![image](https://user-images.githubusercontent.com/57280515/116203937-2d6d0b80-a777-11eb-8bf0-7b6c11931b84.png)
사용자 인증 정보에서 callback 관리하실 수 있습니다.

**Comment by 124525** [comment]
callback은 어케 하는거ㅈ

**Comment by lshqqytiger** [comment]
끄투는 프론트엔드 작업을 제외한 거의 모든 작업은 갱신을 위해선 서버 재부팅이 필요합니다.
callback URL 설정을 안하셨다면 해야죠. 제가 위에 적어두었습니다.

**Comment by 124525** [comment]
InternalOAuthError : 
    C : \ Users \ Neonews \ OneDrive \ 바탕 화면 \ Coding Shout \ KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2 \ Server \ lib \ node_modules \ passport-google-oauth2 \ lib \ oauth2.js : 92 : 28 
    에서 passBackControl 에서 사용자 프로필을 가져 오지 못했습니다 . C : \ Users \ Neonews \ OneDrive \ 바탕 화면 \ Coding Shout \ KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2 \ Server \ lib \ node_modules \ oauth \ lib \ oauth2.js : 132 : 9) 
    at IncomingMessage. <anonymous> (C : \ Users \ Neonews \ OneDrive \ 바탕 화면 \ Coding Shout \ KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2 \ Server \ lib \ node_modules \ oauth \ lib \ oauth2.js : 157 : 7) 
    at IncomingMessage.emit (events.js : 326 : 22) 
    at endReadableNT (_stream_readable.js : : 12) 
    at processTicksAndRejections (internal / process / task_queues.js : 84 : 21)

**Comment by 124525** [comment]
InternalOAuthError? 처음 들어보네요

**Comment by lshqqytiger** [comment]
설정을 다 안하신 것 같은데요요

**Comment by 124525** [comment]
3개 작성하면 되는거 아닌가요...

**Comment by 124525** [comment]
이름
http://geraldine.kro.kr
http://geraldine.kro.kr/login/google/callback
이렇게 했는데

**Comment by lshqqytiger** [comment]
번역 전이 InternalOAuthError: failed to fetch user profile 이었던 것 같네요.
scope 값이 잘못된 것입니다.
```js
scope: ['profile', 'email']
```

**Comment by 124525** [comment]
어디에다가 설정 하는건지 잘 모르것습니다

**Comment by lshqqytiger** [comment]
auth_google.js입니다.
당연히 서버 재부팅 하셔야 적용되구요.

**Comment by 124525** [comment]
scope: ['profile', 'email']
이렇게 적어도 똑같은 오류가 생기는거 같은데
InternalOAuthError: failed to fetch user profile
    at C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by lshqqytiger** [comment]
package.json 안의 ```json
"passport-google-oauth2": "^0.1.6",
```
을 아래와 같이 바꾸고
```json
"passport-google-oauth2": "^0.2.0",
```
cmd로 `
npm install
`한번 해보세요요

**Comment by 124525** [comment]
Package.json에
``"passport-google-oauth2": "^0.1.6",``
이라는 말이 없습니다.
그리고 추가해서 
``"passport-google-oauth2": "^0.2.0",``
이렇게 하면 서버가 실행이 안 되고요
제가 Kkutu 신 버전이 아닌 구버전으로 하고 서버를 구축하고 있습니다.
신버전에는 package.json이 다른 건가요?
제가 한번 확인해 보겠습니다

**Comment by 124525** [comment]
``/server/package.json`` 말하시는거 아닌가요?
전체 코드가
``{
  "name": "kkutu-server",
  "version": "2.5.1",
  "description": "Rule the words! KKuTu Online Server",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/JJoriping/KKuTu",
  "keywords": [
    "kkutu"
  ],
  "author": "JJoriping",
  "license": "GPL-3.0",
  "devDependencies": {
    "electron": "^1.4.15",
    "electron-packager": "^8.5.1",
    "electron-pug": "^1.5.1"
  }
}
``
이렇게 됩니다

**Comment by lshqqytiger** [comment]
제가 말씀드린 건 `Server\lib\package.json`입니다.

**Comment by lshqqytiger** [comment]
npm install은 `Server\lib` 안에서 하시면 됩니다.

**Comment by 124525** [comment]
되었는데.. 게임을 실행하면 대기상태에서 1초 남기고 서버와 연결이 끊겼다고 합니다
이런 오류는 어떻게 해결하는 건가요?

**Comment by lshqqytiger** [comment]
그건 구글 로그인과 무관한 이슈입니다.
게임 서버와 제대로 연결이 안되었을 가능성이 높지만 디버깅 해봐야 알 수가 있죠.

**Comment by 124525** [comment]
``Pug interceptor registered successfully
W: InternalOAuthError: failed to fetch user profile
    at C:\Users\jslim\OneDrive\諛뷀깢 ?붾㈃\?뺣━\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\passport-google-oauth2\lib\oauth2.js:92:28
    at passBackControl (C:\Users\jslim\OneDrive\諛뷀깢 ?붾㈃\?뺣━\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\jslim\OneDrive\諛뷀깢 ?붾㈃\?뺣━\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)``

**Comment by 124525** [comment]
구글 로그인 하기 전까지는 잘 실행이 되었습니다만..

**Comment by lshqqytiger** [comment]
게임 서버가 열려있는지 확인해주세요.

**Comment by 124525** [comment]
서버가 정상적으로 켜져 있는ㄷ

**Comment by 124525** [comment]
localhost는 잘 되는데 포트포워딩된 geraldine.kro.kr 만 안 되네요..

**Comment by lshqqytiger** [comment]
포트포워딩은 특정 도메인을 대상으로 하는 것이 아닙니다.
포트포워딩과는 무관하고, 방화벽 설정은 하셨나요요

**Comment by 124525** [comment]
방화벽은 그냥 나오는거 다 허용했는데....
수동으로 해야 되는 것이 있나요?

**Comment by lshqqytiger** [comment]
네 당연하죠.
방화벽에서 지금 게임 서버 포트를 통한 웹소켓 통신을 제한하고 있습니다.

**Comment by 124525** [comment]
어떻게 하는 건가요...ㅠ

**Comment by lshqqytiger** [comment]
원래 이슈는 이런 것까지 세세하게 알려드리는 곳이 아닙니다.
어떻게 보면 포트포워딩보다 쉬운 작업입니다.
검색하면 다 찾을 수 있는 것들이고 다른 이슈에서도 이미 여러번 언급된 적이 있습니다.
![1](https://user-images.githubusercontent.com/39524005/116334748-aff5d980-a810-11eb-9b2a-b7b22ed60673.PNG)
![2](https://user-images.githubusercontent.com/39524005/116334755-b1bf9d00-a810-11eb-9733-96c477cb2a93.PNG)
![3](https://user-images.githubusercontent.com/39524005/116334759-b2f0ca00-a810-11eb-9602-dcefa82cb58c.PNG)
![4](https://user-images.githubusercontent.com/39524005/116334760-b3896080-a810-11eb-874e-0e7981900bbc.PNG)
![5](https://user-images.githubusercontent.com/39524005/116334761-b421f700-a810-11eb-9b7f-b6abf9306417.PNG)

**Comment by 124525** [comment]
포트 번호를 저 4개만 등록하면 되는건가요?
서버와 연결이 종료되었습니다#1006 이라는 표시가 나서..

**Comment by lshqqytiger** [comment]
따로 포트를 변경하거나 하지 않았다면 저 4개가 기본입니다다

**Comment by 124525** [comment]
포트포워딩한 그 포트번호는 안 넣어도 되는건가요?(???)

**Comment by lshqqytiger** [comment]
끄투에서 사용하는 포트는 80, 443, 8080, 8496이 전부인데 어떤 포트를 포워딩하신거죠죠

**Comment by 124525** [comment]
제가 Ipv4인가 그걸로 해서 따로 한 제럴딘.온라인.한국 이라는 게 있는데
그거는 딱히 뭐 안 정해도 되는거 같아요

**Comment by 124525** [comment]
8090으로 한거 같아요

**Comment by lshqqytiger** [comment]
ipv4는 IP 주소를 적는 곳이고 제럴딘.온라인.한국은 도메인입니다;

**Comment by 124525** [comment]
안 되네요... 하 도대체 왜 안되는거죠...

**Comment by 124525** [comment]
구글 로그인 하기 전까지만 해도 그거 안 해도 잘 들어가 졌는데..

**Comment by 124525** [comment]
그니까.. 제가 포트포워딩을 할때 제 집 공유기 에다가 저의 IP를 넣었어요
근데 그 아이피를 아까 고급 보완이 설정된 뭐시기 에다가 넣는건 아닌거죠?

**Comment by lshqqytiger** [comment]
![1](https://user-images.githubusercontent.com/39524005/116336983-6909e300-a814-11eb-98a0-5e9a0bf6c76e.PNG)
8080 포트포워딩도 하셨고 방화벽에서도 8080 포트 연결 허용도 하신거 맞나요요

**Comment by 124525** [comment]
!!
80번 포트를 포트포워딩 했는뎈ㅋㅋ
그러면
보호 뭐시기 에다가 적은 포트번호들 다 포트포워딩 해야 되는 건가요?

**Comment by lshqqytiger** [comment]
네 4개 전부 포트포워딩과 방화벽에서 연결 허용 설정까지 해줘야합니다다

**Comment by 124525** [comment]
포트포워딩 하면 왜 KT 로그인 화면이 나오죠 ㅋㅋㅋㅋㅋ

**Comment by 124525** [comment]
외부접속 포트 번호를
각 각 80, 8080, 443, 8096
추가 하고, 내부 IP 주소는 네이버에 내 Ip 쳐서 나온것을 넣었습니다
그랬는데 저게 나왔습니다.

**Comment by lshqqytiger** [comment]
도메인이 외부 아이피로 연결되어있는게 맞나요요

**Comment by 124525** [comment]
내부 IP로 연결 되어 있는데..
외부 아이피로는 어떻게 하는거ㅈ

**Comment by lshqqytiger** [comment]
네이버에 내 아이피 검색한거면 외부 아이피가 맞을거고
가끔 공유기 중에 그런 공유기가 있는데 그런 공유기에 당첨 되신 것 같습니다.

**Comment by 124525** [comment]
공유기 설정...
KT인데
왜 하필 그런 공유기 인거ㅈ

**Comment by lshqqytiger** [comment]
저도 KT 공유기인데 전 안그럽니다.
모든 KT 공유기가 그런건 아닌 것 같고 공유기 설정이나 KT 공유기도 종류가 여러개기 때문에

**Comment by 124525** [comment]
그리고 내부포트도 입력해야 하는 건가요? 외부포트만 입력을 해 놔서

**Comment by lshqqytiger** [comment]
외부 포트와 같은 값으로 입력하면 됩니다.

**Comment by 124525** [comment]
[2021-04-29 14:47:23] ERROR OCCURRED ON THE MASTER! :8080 [2021-4-29 2:47:23 ├F10: PM┤] ERROR: TypeError: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined at C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\master.js:345:51 at exports.Tail.go (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\lizard.js:43:16) at C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\kkutu.js:453:11 at callback (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\collection.js:316:13) at Result.preCB (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\sub\collection.js:298:6) at Result.Query.handleReadyForQuery (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\query.js:144:10) at Connection.&lt;anonymous> (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\client.js:180:19) at Connection.emit (events.js:314:20) at Socket.&lt;anonymous> (C:\Users\jslim\OneDrive\바탕 화면\정리\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\node_modules\pg\lib\connection.js:133:12) at Socket.emit (events.js:314:20)

**Comment by lshqqytiger** [comment]
그건 저도 뜨던데
```js
DNAME[($c.profile.title || $c.profile.name).replace(/\s/g, "")] = $c.id;
```
이 부분이 문제인 것 같습니다.
원인은 잘 모르겠고 일단 이렇게 하면 오류 발생은 막을 수 있습니다.
```js
if(!$c.profile.title && !$c.profile.name) 
DNAME[($c.profile.title || $c.profile.name).replace(/\s/g, "")] = $c.id;
```

**Comment by 124525** [comment]
어... 저는 어디에 입력하는 건지 모르겠습니다...
당신도 잘 아실거라고 생각을 하고 있습니다...
그렇습니다.....

**Comment by lshqqytiger** [comment]
master.js요

**Comment by 124525** [comment]
그리고 GM 설정에 대한 이슈를 보았는데..
Server [localhost]: 
Database [postgres]:
Port [5432]: 
Username:
이렇게 입력하는 창이 있더라고요
거기에 Database는 무엇을 입력하는지 알고..
localhost, Port, Username 에 각각 80, 80, ...? 를 입력하는 걸 잘 알겠지만 모르겠습니다
(이건 구글 로그인이 아닌ㄷ )

**Comment by lshqqytiger** [comment]
?? GM 설정을 왜 sql shell에서 하시죠
global.json만 수정하면 됩니다.
자세한건 위키의 global.json 문서를 참고하세요요

**Comment by 124525** [comment]
그것만 수정했는데도
안 되요

**Comment by lshqqytiger** [comment]
서버 재부팅은요요

**Comment by 124525** [comment]
어제 그거 하고 저장하고
오늘 서버 다시 켰어요

**Comment by 124525** [comment]
ADMIN 칸 말고 
따로 입력해야 하는 곳이 있나요?

**Comment by lshqqytiger** [comment]
혹시 number 타입으로 넣으신거아니죠죠

**Comment by 124525** [comment]
Number 타입 말고 뭘로 넣어야 되는 건가요?

**Comment by lshqqytiger** [comment]
...아 제발 위키좀 보세요 문자열이라고 되어있잖아요요

**Comment by 124525** [comment]
넹

**Comment by 124525** [comment]
그 위키좀 알려주실수 있으신가요<<<<<<ㅍ
(진짜 뭘 못 찾아서 죄송합니다)

**Comment by lshqqytiger** [comment]
![Uploading 1.PNG…]()

**Comment by 124525** [comment]
어디있는걸까요.................

**Comment by lshqqytiger** [comment]
컨셉인가요..https://github.com/JJoriping/KKuTu/wiki
https://github.com/JJoriping/KKuTu/wiki
https://github.com/JJoriping/KKuTu/wiki

**Comment by 124525** [comment]
확인 했는데...
제가 구글로 로그인을 했거등요?
그러면 
뭐 google-식별번호 이렇게 입력하면 되는거죠?

**Comment by KAINNY5669** [comment]
#23

**Comment by lshqqytiger** [comment]
접속해서 /id 쳐서 나온거 건드리지 말고 그대로 복사해서 붙여넣기 하면 됩니다
중복 이슈 있는 내용을 왜자꾸 질문하세요요

**Comment by 124525** [comment]
GM 휘장은 어케 얻는건가요
GM 권한은 된거 같습니다

**Comment by lshqqytiger** [comment]
#23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23 #23

**Comment by 124525** [comment]
네 거기에 이슈가 나와있습니다
제가 궁금해 하는건 localhost, Name, Port 번호를 80, (?), 80 이렇게 입력 하는 것이 맞는건가 입니다
이름은 뭘로 해야 하는지 모르겠습니다

**Comment by lshqqytiger** [comment]
순서대로 따라하세요
엔터
main 입력 엔터
엔터
엔터
비번 입력력

**Comment by 124525** [comment]
main=# 이라는 글자가 나왔는데요

**Comment by lshqqytiger** [comment]
거기다 UPDATE ... 저걸 입력하면 되잖아요..

**Comment by 124525** [comment]
아 ㅋㅋㅋ

**Comment by 124525** [comment]
UPDATE 1이 나왔습니다
그러면 창을 꺼도 되는 건가요?

**Comment by 124525** [comment]
..

**Comment by 124525** [comment]
그냥 창 닫을게요

**Comment by kdhkr** [comment]
네 닫아주세요

**Comment by jhj1228** [comment]
이정도로 헤맬실거면 끄투서버 제작 포기하시고요. 조금이라도 공부하신 후에 하시는 걸 추천드립니다. 이슈를 작성하기 전에 관련 이슈가 있는지 확인하신 후, 정말로 안나오는 이슈는 따로 올려주세요.

**Comment by 124525** [comment]
네 안 되네요
정말 신기해요

**Comment by 124525** [comment]
닫겠습니다

**Comment by starprica** [comment]
이미 닫았지만 님! 
#689
추천합니다!
