### ISSUE TITLE
네이버 로그인 이름이 나타나지 않습니다

### ISSUE THREAD

**Issue by Doyun0928** [JJoriping/KKuTu#858]
(사진은 어케 첨부하는건지 몰라서 못 첨부했습니다..)
끄투 서버를 구축중인데 테스트로 네이버 아이디로 들어갔더니
이름 표시가 안 되더라고요...
찾아봐도 관련된 이슈가 없는거 같아서 올립니다

**Comment by norhu1130** [comment]
네이버 아이디 권한설정이 제대로되었는지 확인해주세요.

**Comment by Doyun0928** [comment]
권한 설정은 이름만 하면 되는 건가요?

**Comment by lshqqytiger** [comment]
![1](https://user-images.githubusercontent.com/39524005/116661295-2e987580-a9cf-11eb-87ad-27e32de777e8.PNG)

**Comment by Doyun0928** [comment]
그 두개를 체크 표시를 한뒤, 수정만 하면 바로 되는 건가요? (서버 재부팅은 완료했습니다) 제가 체크 표시를 하기 전에 네이버 로그인을 한 계정으로 테스트를 해 보았는데 똑같네요...

**Comment by lshqqytiger** [comment]
이름 표시가 안된다는 것이 정확히 어떤 증상인지 모르겠습니다
스크린샷을 첨부해주시거나 아니면 제가 직접 접속해서 확인해봐야 알 것 같은데요.

**Comment by chuhyeonjin** [comment]
이미 데이터베이스에 그 계정의 식별 번호와 잘못된 이름이 들어가있어서 그런거 아닌가요?

**Comment by n98nd2** [comment]
한번 다른 네이버 계정을 생성해서 해 보시는 것을 추천 드립니다

**Comment by kdhkr** [comment]
> 
> 
> 이미 데이터베이스에 그 계정의 식별 번호와 잘못된 이름이 들어가있어서 그런거 아닌가요?

기본적으로 끄투는 계정의 이름을 DB에 저장하지 않습니다.
네이버의 경우 로그인 도중 권한을 설정하는 창이 나오는데, 이때 필수 권한도 제거할 경우 닉네임이 표시되지 않습니다.
이 경우, 네이버 계정 설정에서 계정 연동을 해제한 뒤에 다시 로그인해보시면 해결됩니다.
