### ISSUE TITLE
/gwalli 에서 인기단어 조회시 서버가 뻗는 문제

### ISSUE THREAD

**Issue by magpie720** [JJoriping/KKuTu#86]
gwalli에서 인기단어를 조회하면
```
Server\lib\Web\routes\admin.js:118 var data = JSON.parse(file.toString()); ^ TypeError: Cannot read property 'toString' of undefined at ReadFileContext.callback (C:\KKuTu-master\Server\lib\Web\routes\admin.js:118:29) at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
[2017-04-09 19:01:08] Exit web server #1
Worker 8784 died
W: CLOSED WITH CODE 0
```
서버가 위와같은 에러를 내면서 뻗습니다.
봇이 작동하는것을 보면 어느정도 단어 사용량이 쌓인것 같은데 여전히 조회가 되지 않습니다.

**Comment by JJoriping** [comment]
상수 `GLOBAL.KKUTUHOT_PATH`에서 정의한 파일 경로에 파일이 있는지 확인해 보세요. 파일을 불러오지 못한 경우 변수 `file`이 정의되지 않습니다. 자세한 사항은 해당 콜백 함수 바로 아래에
 `console.log(err.toString())` 등을 삽입하여 알 수 있습니다.

**Comment by magpie720** [comment]
감사합니다. 해결하였습니다
단어의 사용 횟수는 모두 DB에 저장될텐데 `kkutuhot.json`이 필요한 이유가 무엇인가요?

**Comment by JJoriping** [comment]
[끄투에서의 인기 단어](http://blog.jjo.kr/220940466936)에서 이전에 비해 단어 입력이 얼마나 집계되었는지 확인하기 위함입니다.

**Comment by magpie720** [comment]
답변 감사합니다.
