### ISSUE TITLE
서버 시작 오류

### ISSUE THREAD

**Issue by riruhyun** [JJoriping/KKuTu#863]
> node 12.19.0, npm 6.14.8, pg 8.6.0, redis 5.0.10, postgreSQL 13.2.2

**db도 만들어서 db.sql 파일을 넣었습니다.
server-setup.bat 파일을 실행하고
run.bat 파일을 실행했습니다.**

![Error Log](https://user-images.githubusercontent.com/74291106/117435849-450f7580-af69-11eb-9207-1c991339d4b8.png)

이렇게 이상한 authentication 에러가 나는 것 같습니다.
**8080 포트**, **8496 포트**에 아무것도 실행되고 있지 않았습니다.

그래서 `lib\sub\global.json`의 포트를 **8090**으로도 바꿔보았지만 오류가 나며 프로그램이
꺼지는 것은 동일했습니다.

![global json](https://user-images.githubusercontent.com/74291106/117436472-f9a99700-af69-11eb-8e27-89d894b3cf5d.png)

`global.json`의 `PASS`와 `PG_PASSWORD`에도 비밀번호를 넣은 상태입니다.
그런데도 오류는 납니다.

그래서 게임 서버를 먼저 실행하려고 했는데
![Game server error](https://user-images.githubusercontent.com/74291106/117437151-cb788700-af6a-11eb-802e-7c49fb1703c8.png)

이런 오류가 나버립니다.
그리고 10초 뒤에 동일한 오류가 납니다.

이것저것 해봤지만 했던 시도들은
모두 실패했습니다..

어떻게 해야 정상적으로 서버를 열 수 있을까요..?

**Comment by lshqqytiger** [comment]
#854 
PostgreSQL < 12

**Comment by riruhyun** [comment]
감사합니다!
PostgreSQL을 12버전보다 낮은 버전을 재설치하니
잘 돌아가네요
