### ISSUE TITLE
Oauth 계정 이름 변경

### ISSUE THREAD

**Issue by riruhyun** [JJoriping/KKuTu#866]
![ScreenShot](https://user-images.githubusercontent.com/74291106/117535129-5327c980-b02f-11eb-89cc-dcfbfb3b827f.png)
**네이버 계정으로 로그인한 상태입니다.**

네이버 계정으로 로그인 했더니 끄투 이름이 네이버 계정의
별명이 이름으로 적용되어 있어서 내 정보에 있는 아바타를 클릭해서
이름을 변경하려 했는데 소개 한마디 밖에 없었습니다.

그래서 `psql`로 `main` 데이터베이스의 `user` 테이블을 살펴보았지만
`id`는 있었지만 이름은 없었습니다.

그래도 `gwalli`에는 `유저 감시하기` 탭에서 이름이 나왔지만
어떻게 변경하는지는 모르겠습니다.

다른 이슈들도 보았지만 도움 되는 이슈는 찾지 못했습니다.

어떻게 하면 이름을 변경할 수 있을까요?
아니면 어떤 코드를 추가해야 이름을 변경할 수 있을까요..?

**Comment by kdhkr** [comment]
#689 

**2. 이곳은 본인이 개발하기를 원하는 기능을 어떻게 구현하는지 질문하는 곳이 아닙니다.**
"특수 규칙을 만들고 싶은데 어떻게 만들어야 하나요?" 혹은 "닉네임 변경 기능은 어떻게 만드나요?"와 같은 질문은 삼가시기 바랍니다. 아울러, 끄투 서버의 정상적인 운영을 위해서는 충분한 개발 실력을 요구합니다. 부족하다고 여겨질 경우, 다른 개발자를 구하거나 외주를 맡기시기 바랍니다. 이곳에서는 기능 구현 관련 질문에 대답해드릴 이유가 없습니다.
> 아래와 같은 이슈들은 답변을 드리기가 어렵습니다.
> - 특수 규칙/게임 유형/기능을 어떻게 만들어야 하나요?
> - 핑/경험치 배율을 어떻게 조정해야 하나요?
> - 광고를 어떻게 삽입해야 하나요?

**Comment by riruhyun** [comment]
네, 죄송합니다.

**Comment by lshqqytiger** [comment]
이미 해당 기능을 master 브랜치에 추가하는 PR이 준비 중입니다.

**Comment by riruhyun** [comment]
> 이미 해당 기능을 master 브랜치에 추가하는 PR이 준비 중입니다.

네, 알겠습니다.
