### ISSUE TITLE
클라우드플레어 프록시 사용

### ISSUE THREAD

**Issue by Jippang** [JJoriping/KKuTu#870]
클라우드플레어를 사용할 때 프록시를 사용하면 방 만들기와 입장이 안 되는걸로 알고 있는데요, 프록시를 사용하면서 방 만들기와 입장도 가능하게 하려면 어떻게 조치해야 할까요?

**Comment by lshqqytiger** [comment]
웹소켓 핸들러를 분리하시고 API 서버와 인게임에 각각 따로 프록시를 사용하면 됩니다.
![1](https://user-images.githubusercontent.com/39524005/117976531-db2d0c80-b36a-11eb-8cc3-46fe60074b40.png)

**Comment by Jippang** [comment]
죄송하지만 포트를 어디에서 변경해야 하나요?

**Comment by Jippang** [comment]
`/Server/lib/sub/global.json`에서 메인포트를 2053으로 설정 후 `/Server/lib/Game/cluster.js`에서 슬레이브 포트?를 메인 + 30 + 서버 번호로 하도록 설정했습니다. (클플 제공 포트 2053, 2083)
그러나 `cluster.js`에서 변경한 내용이 적용되지 않는 것 같습니다. 내용 변경 후 따로 해야 할 작업이 있을까요?

**Comment by lshqqytiger** [comment]
master.js도 변경하셔야 합니다.

**Comment by Jippang** [comment]
감사합니다.
