### ISSUE TITLE
gawlli 작동 안함

### ISSUE THREAD

**Issue by B0X0B** [JJoriping/KKuTu#873]
gawlli에서 유저 DB 다루기에서 다른 사람한테 핑을 주려해도
아무 반응도 없고, 단어 추가를 해도 아무 반응이 없습니다. 그냥 아무일도 일어나지 않습니다.
어떻게 고치나요?

**Comment by Jippang** [comment]
비밀번호를 입력했나요?

**Comment by B0X0B** [comment]
어떤 비밀번호를 말씀하시는 건가요?

**Comment by Jippang** [comment]
![image](https://user-images.githubusercontent.com/67180662/118358019-e6c14300-b5b7-11eb-9c9e-b264883a48ac.png)
암호 부분에 `/Server/lib/sub/global.json`에서 작성한 PASS값을 넣어주세요.
또한 단어를 추가할 때는 테이블 부분에 `ko` 또는 `en`을 추가해주세요.

**Comment by B0X0B** [comment]
감사합니다. 해결이 되었습니다. 이슈는 닫겠습니다.
