### ISSUE TITLE
상점 항목 추가 & 상점 물건 판매

### ISSUE THREAD

**Issue by B0X0B** [JJoriping/KKuTu#875]
![lowkkutu2](https://user-images.githubusercontent.com/73378483/118382051-232e8680-b62c-11eb-8bde-2d5418fb6c0a.PNG)
위와 같이 상점 항목 추가랑,
![lowkkutu3](https://user-images.githubusercontent.com/73378483/118382054-2f1a4880-b62c-11eb-8ef3-f22aa71c0247.PNG)
위와 같은 물건 판매 하는법을 알려주세요.

**Comment by lshqqytiger** [comment]
#689
