### ISSUE TITLE
Bind Eacces Error

### ISSUE THREAD

**Issue by suhong0204** [JJoriping/KKuTu#879]
[2021-05-22 22:03:05] &lt;&lt; KKuTu Web >>
[2021-05-22 22:03:06] &lt;&lt; KKuTu Web >>
[2021-05-22 22:03:07] &lt;&lt; KKuTu Server:NaN >>
[2021-05-22 22:03:07] Error on ws: Error: bind EACCES NaN
[2021-05-22 22:03:08] &lt;&lt; KKuTu Server:NaN >>
[2021-05-22 22:03:08] Error on ws: Error: bind EACCES NaN
[2021-05-22 22:03:09] &lt;&lt; KKuTu Server:8496 >>
[2021-05-22 22:03:09] &lt;&lt; KKuTu Server:8497 >>
[2021-05-22 22:03:11] Master DB is ready.
[2021-05-22 22:03:11] Error on ws: Error: listen EACCES: permission denied undefined
이런 오류가 뜹니다.
이슈 #876 을 참고 하였지만, 도움이 되지 않았습니다.
어떻게 고쳐야 할까요?

**Comment by SaDa10** [comment]
음.. settings.json하고 global.json 설정을 어떻게 하셨나요?

**Comment by suhong0204** [comment]
settings.json
{
	"server-name": "끄투로우",
	"web-num-cpu": 2,
	"game-num-cpu": 2,
	"game-num-inst": 2
}
_______________________________________________________

global.json
{
	"ADMIN": [ "Input admin id here" ],
	"MAIN_PORTS": [ 8080 ],
	"GAME_SERVER_HOST": "127.0.0.2",
	"KKUTUHOT_PATH": "/kkutu/data/kkutuhot.json",
	"PASS":"~~개인정보~~",
	"PG_USER": "postgres",
	"PG_PASSWORD": "~~개인정보~~",
	"PG_PORT": 5432,
	"PG_DATABASE": "main",
	"GOOGLE_RECAPTCHA_TO_GUEST": false,
	"GOOGLE_RECAPTCHA_TO_USER": false,
	"GOOGLE_RECAPTCHA_SITE_KEY": "Your Google Recaptcha site key Here",
	"GOOGLE_RECAPTCHA_SECRET_KEY": "Your Google Recaptcha secret key Here",
	"IS_SECURED": false,
	"SSL_OPTIONS": {
		"PRIVKEY": "Your SSL Private Key Here",
		"CERT": "Your SSL Certificate Here",
		"CA": "Your SSL CA-Bundle Here",
		"PFX": "Your PFX Bundle Here",
		"isPFX": false,
		"isCA": false
	},
	"USER_BLOCK_OPTIONS": {
		"USE_MODULE": false,
		"USE_X_FORWARDED_FOR": false,
		"BLOCK_IP_ONLY_FOR_GUEST": true,
		"DEFAULT_BLOCKED_TEXT": "관리자에 의해 서비스 이용이 제한되었습니다.",
		"BLOCKED_FOREVER": "영구 이용제한"
	}
}

**Comment by lshqqytiger** [comment]
게임 서버를 2개로 설정하셨지만, 게임 서버 #2의 포트를 설정하지 않으셨습니다.
MAIN_PORTS 값을 다음과 같이 바꿔주세요.
```json
"MAIN_PORTS": [ 8080, 8090 ]
```

**Comment by SaDa10** [comment]
global.json 
"MAIN_PORTS": [ 8080 ], 부분을 "MAIN_PORTS": [ 8080, 8090, 8100 ], 으로 하고 다시 해주세요!

**Comment by suhong0204** [comment]
해결 되었습니다. 감사합니다 👍 **이슈**는 닫겠습니다.
