### ISSUE TITLE
랭킹에서 특정 사용자를 영구히 제외할 수 있나요?

### ISSUE THREAD

**Issue by magpie720** [JJoriping/KKuTu#88]
제목이 곧 내용입니다

**Comment by JJoriping** [comment]
끄투 서버를 운영하기 위해 필수적인 사안이 아니라 구현된 것은 없습니다. ssh 등으로 직접 Redis 클라이언트에 연결해 콘솔에서 `ZREM` 명령어를 사용해야 합니다. 앞으로도 해당 사용자가 추가될 수 없도록 하기 위해서는 사용자 데이터베이스에 별도로 플래그를 하나 심은 뒤 게임 서버 쪽에서 그 플래그의 상태에 따라 랭킹 등록 여부를 결정하게 할 수 있습니다.

**Comment by magpie720** [comment]
어느 부분이 랭킹과 관련된 부분인지 알 수 있을까요?

**Comment by JJoriping** [comment]
https://github.com/JJoriping/KKuTu/blob/9e5f8e5de07818d2d74d79c2c5a4063c238e16dd/Server/lib/Game/kkutu.js#L450

위 함수의 `DB.redis.putGlobal` 쪽에서 Redis 서버와 통신하고 있으니 참고하세요.

**Comment by magpie720** [comment]
답변 감사합니다.
