### ISSUE TITLE
고치고 나니 또 다른 오류에 접근 했습니다.

### ISSUE THREAD

**Issue by suhong0204** [JJoriping/KKuTu#880]
로그인을 하면 로그인이 풀리는 상황이 발생하였습니다.
에러는 안뜨는데, 안됩니다. 어떻게 해야되나요

**Comment by SaDa10** [comment]
#79 이슈를 참고해주세요!

**Comment by suhong0204** [comment]
![github](https://user-images.githubusercontent.com/80574663/119228327-73867680-bb4d-11eb-960b-dbc855579f69.PNG)
혹시 이거 지우시라는 건가요

![github2](https://user-images.githubusercontent.com/80574663/119228336-7e410b80-bb4d-11eb-815a-6de96be0a617.PNG)
이거 지우시라는 건가요?

56~65번째 줄이 주석처리가 되지 않아 있어서..

**Comment by chuhyeonjin** [comment]
첫번째꺼 지우시면 될겁니다

**Comment by lshqqytiger** [comment]
PR 등 여러가지 커밋들로 인해 줄 수가 바뀐 것 같습니다.
위쪽 주석을 푸시면 됩니다.
(아래쪽은 디도스 공격을 감지하는 코드입니다)

**Comment by kmsimproject** [comment]
해결이 되셨다면 이슈를 닫아주세요.
