### ISSUE TITLE
끄투 /id 질문

### ISSUE THREAD

**Issue by B0X0B** [JJoriping/KKuTu#882]
![githubquestion](https://user-images.githubusercontent.com/73378483/119439248-f29dc980-bd5c-11eb-8c35-9662f396ea7b.PNG)
위에 같이 id 앞에 #disco나 discord-를 없애는 법이 있을까요?

**Comment by kmsimproject** [comment]
#689 확인바랍니다.

**Comment by lshqqytiger** [comment]
#689 깃허브 이슈는 개발하고 싶은 기능에 대해 질문하는 곳이 아닙니다.
