### ISSUE TITLE
끄투 로비 화면 수정하는 pug 파일은 무엇인가요?

### ISSUE THREAD

**Issue by MegaKkutu** [JJoriping/KKuTu#884]
제목 그대로 입니다..
``KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\views``에 있는 파일 일거 같은데 혹시 ``kkutu.pug`` 파일 인가요?

**Comment by kmsimproject2** [comment]
#689 확인바랍니다.

**Comment by MegaKkutu** [comment]
그냥 뭔지 알려주시면 안 되는 건가요..

**Comment by kmsimproject2** [comment]
> 그냥 뭔지 알려주시면 안 되는 건가요..

kkutu.pug와 in_kkutu.css 파일입니다. 다음부터는 이곳에 구현관련 질문을 하지 말아주셨으면 합니다.
