### ISSUE TITLE
아이템이 안뜸/

### ISSUE THREAD

**Issue by B0X0B** [JJoriping/KKuTu#886]
![ee](https://user-images.githubusercontent.com/73378483/120067638-a08bd980-c0b7-11eb-82f3-3b6db2317312.PNG)
![ee2](https://user-images.githubusercontent.com/73378483/120067639-a1bd0680-c0b7-11eb-8491-e1a40118d6e0.PNG)

위 사진처럼 아이템이 안됩니다. DBeaver로 81번에 있는 아이템을 Delete 했는데, 이렇게 떴습니다.
어떻게 해야하나요?

**Comment by ehxhfl7** [comment]
B0X0B님의 인벤토리에 db에는 존재하지 않는 아이템이 있는 것 같습니다.
관리 페이지에서 유저 프로필 조회 → 본인의 ID 또는 닉네임 입력
→ box에서 없는 아이템이 존재하는지 확인하고 그 아이템을 지워보세요.

**Comment by B0X0B** [comment]
해결되었습니다. 이슈 닫습니다.
