### ISSUE TITLE
광고 표시가 안되는 문제

### ISSUE THREAD

**Issue by SkyLightQP** [JJoriping/KKuTu#89]
애드센스 광고 코드를 pug 구문으로 바꾸어 적용은 하였습니다만
광고가 표시 안되는 문제가 있습니다.

끄투 자체 문제인가요?
아니면 애드센스쪽 문제일려나요?

**Comment by BasixKOR** [comment]
혹시 개발자 도구에서 콘솔을 확인해 보셨는지요?

**Comment by SkyLightQP** [comment]
확인해봤습니다.

**Comment by Ganggroid** [comment]
delete setTimeout; 구문을 삭제해보세요. 애드센스 같은 경우에는 이렇게 해결했습니다.

**Comment by SkyLightQP** [comment]
Server/lib/Web/lib/kkutu/tail.js 경로에 있는 구문(delete window.setTimeout)을 말씀하시는건가요?

**Comment by Ganggroid** [comment]
네

**Comment by SkyLightQP** [comment]
음.. 그래도 작동이 안되네요.
알려주셔서 감사합니다
