### ISSUE TITLE
도메인 등록을 하고 섭을 켯는데 localhost 는 잘 돌아가는데 도메인은 무한 로딩 무엇일까요

### ISSUE THREAD

**Issue by CHEEY-BORIN** [JJoriping/KKuTu#890]
도메인 등록 하고 섭 켰는데 로컬호스트는 잘 되는데 도메인은 무한 로딩 걸리네요...ㅠㅠ

도메인은 cherrykkutu.kro.kr 입니다
왜 안되는 걸까요;;

**Comment by KAINNY5669** [comment]
도메인이 ip와 연결되지 않았습니다.

**Comment by CHEEY-BORIN** [comment]
연결 되어있습니다

**Comment by KAINNY5669** [comment]
![Screenshot_20210605-100057_Samsung Internet.png](https://user-images.githubusercontent.com/65794272/120875102-09f27780-c5e5-11eb-9c48-ec8b4a9d3d5e.png)
네?

**Comment by lshqqytiger** [comment]
지금은 문제가 해결된 것으로 보입니다. 이슈를 닫아주세요.

**Comment by CHEEY-BORIN** [comment]
알겠습니다
