### ISSUE TITLE
오류발생으로 이슈 염.

### ISSUE THREAD

**Issue by CHEEY-BORIN** [JJoriping/KKuTu#892]
in_m_kkutu.css 686 줄에 #KickVoteDiag 이 부분이 에러랍니다.

Do not use empty rulesetscss(emptyRules) 

^
||
에러내용

왜 이러는 거죠

룰 세팅을 안했다고 하는데

**Comment by lshqqytiger** [comment]
Empty Ruleset은 아래와 같은 상황을 말합니다.
```css
#KickVoteDiag {
}
```
위와 같이 안에 아무것도 들어 있지 않은 Ruleset을 지워주세요.

**Comment by CHEEY-BORIN** [comment]
이슈 닫음
