### ISSUE TITLE
무한로딩문제

### ISSUE THREAD

**Issue by CHEEY-BORIN** [JJoriping/KKuTu#894]
저는 잘 되는데 외부 IP주소를 사용하는 분들은 접속이 안된다고 하네요 왜 그럴까요~?

**Comment by MegaKkutu** [comment]
포트포워딩 방화벽 설정은 진행 하셨나요?

**Comment by MegaKkutu** [comment]
한번 #856 에 나와있는 내용대로 진행해 보시길 바랍니다

**Comment by lshqqytiger** [comment]
포트포워딩(or DMZ) 작업을 안하셨거나 방화벽 인바운드 설정(or 방화벽 비활성화)을 안하신겁니다.

**Comment by CHEEY-BORIN** [comment]
근데 방화벽 해제 해도 접속이 안되는데 왜 이러는 거죠

**Comment by CHEEY-BORIN** [comment]
불러오는중 앞으로 1에서 좀 기다려지다가 갑자기 서버와 연결이 끊어졌습니다! (#1006) 뜨는데
왜 이러는 거죠

**Comment by Doyun0928** [comment]
방화벽을 해제 하는것이 아니라 새로운 인바인드 규칙을 만드셔야죠

**Comment by CHEEY-BORIN** [comment]
인바인드 규칙을 만들려고 하는데 어떤식으로 만들면 됄까요?

**Comment by Doyun0928** [comment]
#689

**Comment by Doyun0928** [comment]
이미 비슷한 이슈가 많이 있습니다.
찾아 보시길 바랍니다

**Comment by CHEEY-BORIN** [comment]
개발실력은 있습니다만

**Comment by Doyun0928** [comment]
;;

**Comment by lshqqytiger** [comment]
제가 이미 #856 에 아주 친절히 스크린샷까지 첨부해서 설명해 놓았습니다. 질문 전에 검색부터 해주세요.

**Comment by graykkutu** [comment]
ㅋㅋㅋㅋ 진짜 친절하게 하셨네요

**Comment by graykkutu** [comment]
해결 되셨으면 이슈 닫아 주시면 감사하겠습니다!

**Comment by CHEEY-BORIN** [comment]
포트포워딩 하고 공유기를 껏다 켯는데 인터넷 폭발함 (랜선은 연결되어있는데 인터넷 연결 안됨)

**Comment by graykkutu** [comment]
존댓말 사용바랍니다.

**Comment by CHEEY-BORIN** [comment]
그 포트포워딩을 하는데 외부 포트는 뭘로 하나요?

**Comment by lshqqytiger** [comment]
그것도 #856에 다 나와있습니다.

**Comment by CHEEY-BORIN** [comment]
외부 포트와 같은 값으로 입력하면 됩니다

하는데 내부포트와 외부포트와 같으면 안된다고 하네요 (전 SKB 와이파이 씁니다)

**Comment by lshqqytiger** [comment]
보안 정책이 그렇게 되어있나 보네요.
그냥 DMZ 설정을 하시는게 좋을 것 같습니다.

**Comment by Doyun0928** [comment]
관련된 이슈가 많이 있습니다;;;
확인 후 이슈를 열어주셨으면 감사하겠습니다

**Comment by CHEEY-BORIN** [comment]
![image](https://user-images.githubusercontent.com/79044687/125180343-dcc46500-e233-11eb-91f4-c4168c53e360.png)

**Comment by CHEEY-BORIN** [comment]
외부 포트는 어떻게 하면 좋을까요?

**Comment by lshqqytiger** [comment]
내부와 같습니다.

**Comment by CHEEY-BORIN** [comment]
아 혹시 프로토콜은 TCP 인가요

**Comment by chuhyeonjin** [comment]
네

**Comment by CHEEY-BORIN** [comment]
![image](https://user-images.githubusercontent.com/79044687/125180765-f6b47680-e238-11eb-883d-d3d566f276d6.png)

**Comment by chuhyeonjin** [comment]
말그대로 공유기에서 8080 포트를 외부에 공개하지 못하게 막고 있네요

**Comment by lshqqytiger** [comment]
외부에서 8080포트에 접근할 수 없게 설정되어있네요. 따로 해제하는 방법이 없다면 공유기를 바꿔보세요.

**Comment by CHEEY-BORIN** [comment]
아 그럼 한번 찾아보겠습니다 ㅎㅎ

**Comment by CHEEY-BORIN** [comment]
포탈 접속은 가능하므로 이슈 닫습니다.
