### ISSUE TITLE
gwalli 단어 등록 문제

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#895]
``TypeError: Cannot read property 'insert' of undefined at onKKuTuDB (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\Web\routes\admin.js:173:12) at Layer.handle [as handle_request] (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\layer.js:95:5) at next (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\route.js:137:13) at Route.dispatch (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\route.js:112:3) at Layer.handle [as handle_request] (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\layer.js:95:5) at C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\index.js:281:22 at Function.process_params (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\index.js:335:12) at next (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\index.js:275:10) at C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\Web\main.js:94:4 at Layer.handle [as handle_request] (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\node_modules\express\lib\router\layer.js:95:5)``
무슨 오류 인가요...
gwalli 단어 등록이 안 됩니다
#689만 하지 말아주시고,
해결책을 알려주십시오

**Comment by lshqqytiger** [comment]
[이미 예외 처리가 되어있는 부분](https://github.com/JJoriping/KKuTu/blob/9540f8f3f9c20556d54accee3b844d4c7326d9b8/Server/lib/Web/routes/admin.js#L172)이지만, onKKuTuDB 함수의 실행이 종료되지 않아 발생하는 문제입니다.
해당 부분을 return하도록 수정하시면 됩니다.

**Comment by lshqqytiger** [comment]
#896

**Comment by graykkutu** [comment]
``C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\Web\routes\admin.js:118 var data = JSON.parse(file.toString()); ^ TypeError: Cannot read property 'toString' of undefined at ReadFileContext.callback (C:\Users\ealjs\Desktop\KKuTu-master\Server\lib\Web\routes\admin.js:118:30) at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)``
이번에는 이런 오류가 뜹니다.
return으로 바꾸었는데 말입니다

**Comment by lshqqytiger** [comment]
KKuTuHot 파일이 존재하지 않아 발생하는 문제입니다.
직접 만드시거나 아예 관련 기능을 삭제하시면 됩니다.

**Comment by graykkutu** [comment]
kkutuhot.json을 어느 경로에다가 추가하면 될까요?

**Comment by graykkutu** [comment]
``C:\KKuTu-master\Server\lib\Web\routes`` 에다가 하는 건가요?

**Comment by lshqqytiger** [comment]
[global.json](https://github.com/JJoriping/KKuTu/wiki/S~global.json)의 KKUTUHOT_PATH 값 확인 바람.

**Comment by Doyun0928** [comment]
다 되셨으면 이슈를 닫아 주세요
