### ISSUE TITLE
부탁드립니다

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#897]
GM 휘장이 아닌 다른 휘장을 Database에 추가하려고 합니다.
pgadmin4인데 추가하는 경로가 어떤것이죠?

**Comment by kmsimproject** [comment]
관리페이지에서 추가하실수 있습니다. 그리고 여기는 **끄투서버의 구현을 묻는곳이 아닙니다. 다음부턴 이런 이슈 자제 바랍니다.** #689

**Comment by graykkutu** [comment]
네

**Comment by lshqqytiger** [comment]
Duplicate of #734
