### ISSUE TITLE
궁금해서 이슈 올립니다

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#898]
``lib\Web\public`` 이 경로에다가 제가 ``index.html`` 이라는 파일을 만들었는데, 이 파일에서 게임 시작 버튼을 눌렀는데도 게임이 실행이 안되고 그냥 가만히 있네요. ''?server=0이 변하긴 합니다'' 그래서 그 파일의 이름을 ``main.html`` 이라고 수정을 한 뒤에 도메인/main.html에 들어가니 되네요. 그런데 /main.html을 빼면 일반 끄투로 들어와 지고요 (당연한거죠) 일반 도메인에 들어갔을때에도 main.html이 되도록 하는 방법은 어떻게 하는 건가요? 
#689만 하지 말아주시고, 해결책을 알려주시면 감사하겠습니다

**Comment by lshqqytiger** [comment]
HTML 사용은 권장하지 않습니다.
정 HTML을 사용하고 싶으시면 서버 코드 자체를 수정해서 view engine을 외부 모듈을 사용해서 HTML로 지정하시거나 view engine 없이 HTML 자체를 렌더링하게끔 수정하세요.
끄투 자체의 문제점이 아니므로 끄투 이슈칸에서는 정확한 해결책을 제시하기 어렵습니다.
