### ISSUE TITLE
서버 리스트에서 그래프가 올바르지 않게 표시되는 문제

### ISSUE THREAD

**Issue by Ganggroid** [JJoriping/KKuTu#90]
![image](https://cloud.githubusercontent.com/assets/5188404/25072440/0e839492-2309-11e7-84aa-aacabac20eab.png)
![image](https://cloud.githubusercontent.com/assets/5188404/25072438/04468c64-2309-11e7-9e16-dbbaff540430.png)
리스트 수치상으로는 올바르게 인식하여 1600으로 표기를 하지만, 그래프에서는 2400명으로 인식하나 봅니다. 수정 부탁드릴게요.

**Comment by JJoriping** [comment]
수정했습니다. 제보 감사합니다.
