### ISSUE TITLE
로그인 문제 입니다

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#900]
냉이 서버를 만들기 위해 ``/settings.json``를 수정하고, ``/lib/sub/global.json`` 파일을 수정하였습니다. 그리고 고급 방화벽까지 수정을 하였는데 서버 로그상으로는 문제가 없었지만 메인 서버에 들어갈때까지도 문제가 없었습니다. 그런데 서버 시작을 눌렀는데 로그인이 풀리면서 게스트로 게임에 들어가 집니다. 게임 서버 로그상으로는 아무 표시도 안 났는데 무슨 문제일까요??

**Comment by graykkutu** [comment]
관련된 이슈에 따라서 수정을 하였는데도 이런 문제가 발생하여서 이슈를 열었습니다

**Comment by ehxhfl7** [comment]
Redis 설치 하셨나요

**Comment by graykkutu** [comment]
네 하였습니다

**Comment by graykkutu** [comment]
서버가 1개일때에는 아무런 문제가 없었습니다

**Comment by B0X0B** [comment]
global.json에서

`"MAIN_PORTS": [ 8080, 8090 ],`

이렇게 감자서버랑 냉이서버 포트를 적었나요?

**Comment by lshqqytiger** [comment]
관련 이슈에 따라 수정했다는 것이 Redis 관련 주석을 푸셨다는 건가요?

**Comment by graykkutu** [comment]
> global.json에서
> 
> `"MAIN_PORTS": [ 8080, 8090 ],`
> 
> 이렇게 감자서버랑 냉이서버 포트를 적었나요?

네 그렇게 하였습니다

> 관련 이슈에 따라 수정했다는 것이 Redis 관련 주석을 푸셨다는 건가요?

Redis 관련 주석은 풀지 않았습니다

**Comment by lshqqytiger** [comment]
당연히 푸셔야 레디스와 연결이 되면서 로그인 세션이 유지됩니다.

**Comment by MegaKkutu** [comment]
죄송합니다만 어느 부분인지 알 수 있을까요?

**Comment by MegaKkutu** [comment]
감자서버만 운영을 할때는 아무런 문제가 없었습니다만

**Comment by MegaKkutu** [comment]
허허라... Redis 주석이 풀려있습니다만
감자 서버만 운영을 할때에는 이런 오류가 없었거든요...

**Comment by graykkutu** [comment]
네 저도 Redis 주석이 풀려있는데 이런 오류가

**Comment by graykkutu** [comment]
뭐 그냥 서버 1개로만 운영할게요~
