### ISSUE TITLE
이딴거 올려서 죄송합니다만..

### ISSUE THREAD

**Issue by MegaKkutu** [JJoriping/KKuTu#901]
#689만 하지 말아주시고, 방법을 알려주시면 감사하겠습니다. 이딴거 올려서 죄송합니다만 어떻게 아는 방법이 없어서요...
끄투 레벨 이미지 파일은 어디에다가 이미지를 넣으면 되는 건가요..?

**Comment by lshqqytiger** [comment]
body.js의 2511번째 줄 getLevelImage 함수만 봐도 알 수 있습니다.
이런 이슈는 더이상 올리지 말아주셨으면 좋겠습니다.

**Comment by graykkutu** [comment]
이건 좀 아닌듯 합니다

**Comment by MegaKkutu** [comment]
죄송합니다
