### ISSUE TITLE
간단한거 1가지만 질문 하겠습니다

### ISSUE THREAD

**Issue by Doyun0928** [JJoriping/KKuTu#903]
끄투 개발중에 어려움이 있어 질문 남깁니다. (비슷한)이슈중엔 DB 에 내용을 삭제하는 내용이랑 관련 이슈 중에 있는 내용을 참고해도 문제가 해결 되지 않아 질문 남깁니다. 
끄투 서버에 적용할 YT 이미지 파일을 만들었습니다 (GM 처럼요) 그걸 DBeaver 에다가 어떻게 등록을 하는지 궁금합니다. KKutu_shop에서 있는 DB내용은 삭제 할 수 있지만 추가는 안 되더라고요... db.sql 에서 하는건 맞는거 같은데 어떻게 하는 건지 궁금합니다. #689 보다는 맞는 해결책을 주셨으면 감사하겠습니다

**Comment by SaDa10** [comment]
item 추가는, DBeaver에서 하는게 아닌, 끄투의 관리자 페이지에서 item을 등록할수 있습니다.

**Comment by lshqqytiger** [comment]
이 이슈 내용은 끄투 이슈에서 다룰 내용이 아닌 것 같습니다.
DBeaver 사용 방법에 대해서는 관련 문서를 검색해보시기 바랍니다.

**Comment by Doyun0928** [comment]
이렇게 답변해 주셔서 너무나도 감사합니다. 상품을 등록하려면 고유 식별자가 필요하다는데 그 식별자는 어떻게 얻는 걸까요~?

**Comment by inpeu** [comment]
식별자는 그 아이템 이미지 이름을 입력해야 합니다. (예 : 아이템 이름 : item.png  식별자 : item) 이런식으로요

**Comment by Doyun0928** [comment]
감사합니다 :) 또 오류가 발생하면 다시 이슈를 열도록 하겠습니다

**Comment by Doyun0928** [comment]
엇 이미지 파일은 어떻게 적용을 하는 거죠?

**Comment by ehxhfl7** [comment]
1. /public/img/kkutu/moremi 폴더 안에 카테고리에 맞는 폴더에 이미지 파일을 추가
2. 그 이미지의 이름(확장자 제외)으로 된 아이템을 관리자 페이지에서 추가
3. 서버 재시작

**Comment by Doyun0928** [comment]
![이거 진자 왜](https://user-images.githubusercontent.com/75249935/123200394-96f56600-d4eb-11eb-98d9-e88e0e3a4f28.png)
이렇게 하고 서버 재부팅을 하였습니다 
``Server\lib\Web\public\img\kkutu\moremi\badge``에다가 ``b1_yt.png`` 이라는 파일을 생성 하였습니다.

**Comment by Doyun0928** [comment]
![이미지 파일들](https://user-images.githubusercontent.com/75249935/123200650-1b47e900-d4ec-11eb-9862-dfa96d28fa02.png)
이렇게 하였습니다

**Comment by lshqqytiger** [comment]
badge가 아닙니다. 다른 아이템에 설정된 값을 참고하세요.

**Comment by Doyun0928** [comment]
BDG4로 group 값을 정하면 어떨까요?

**Comment by Doyun0928** [comment]
그렇게 하니깐 되긴 하였는데 그것을 적용을 하면...
![야이런](https://user-images.githubusercontent.com/75249935/123204436-12a6e100-d4f3-11eb-8664-def43de0716c.png)

**Comment by Doyun0928** [comment]
잘 등록되었으므로, 이 이슈를 종료합니다
