### ISSUE TITLE
버튼 누를때 생기는 문제

### ISSUE THREAD

**Issue by Random-Studio** [JJoriping/KKuTu#904]
https://user-images.githubusercontent.com/60588744/124336553-6a230c00-dbd9-11eb-9e3f-652eaf5240cc.mp4

버튼 누를때 다른 기능이 되는데 이벤트 창에만 기능이 안됩니다.
이것도 개발에 해당되나요?
안되면 다른 분 부르고 이슈 닫을게요.

**Comment by lshqqytiger** [comment]
#689 의 2번 항목에 해당합니다.

**Comment by Random-Studio** [comment]
네
