### ISSUE TITLE
무슨 오류 인가요?

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#905]
간단한 겁니다. GM 휘장 앞에 있는 운영자 라는 단어를 YT 휘장 에다가 등록 하려고 하는데 in_game_kkutu.js 를 수정하는 것만으로는 안 되더군요.. 또 어떤 파일을 수정해야 되는 걸까요..?

**Comment by jhj1228** [comment]
[#437](https://github.com/JJoriping/KKuTu/issues/437)

**Comment by lshqqytiger** [comment]
끄투 기본 구조부터 파악해 주시기 바랍니다.
끄투 구조를 파악했다면 올라올 이유가 없는 너무 기본적인 이슈(사실 이슈라고 칭하기에도 애매한)입니다.
깃허브 이슈 기능은 원래 레포지토리 자체의 문제, 버그 등에 대해 기술하는 곳이지 기능 구현 방법에 대해 질문하는 곳이 아닙니다.

**Comment by graykkutu** [comment]
네 죄송합니다

**Comment by graykkutu** [comment]
#437
과 같은 방법으로 추가하였는데 게임에 들어가려고 하니 불러오는 중에서 가만히 멈춥니다.
``min.js`` 에 grunt로 수정하는 방법을 잘 몰라서 Notepad++ 로 편집해서 저장하였더니 이런 오류가 발생합니다

**Comment by graykkutu** [comment]
console 코드는 다음과 같다고 나옵니다:
``Failed to load resource: the server responded with a status of 404 (Not Found)
in_kkutu.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
in_game_kkutu.min.js:20 Uncaught SyntaxError: Unexpected identifier
DevTools failed to load source map: Could not load content for https://graykkutu.kro.kr/js/jquery.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE``

**Comment by graykkutu** [comment]
![Uploading source.png…]()

**Comment by graykkutu** [comment]
![source](https://user-images.githubusercontent.com/85274920/124349639-1ccf8a80-dc2b-11eb-900a-1198724882e7.png)

**Comment by ehxhfl7** [comment]
min.js를 직접 수정하지 말고 /Server/lib/grunt.cmd를 실행하세요

**Comment by graykkutu** [comment]
grunt cli 를 설치하였습니다만 ``grunt.cmd``를 실행하니 바로 창이 꺼집니다

**Comment by graykkutu** [comment]
![화면 캡처 2021-07-03 182640](https://user-images.githubusercontent.com/85274920/124349835-3f15d800-dc2c-11eb-846b-230508f2a7b9.png)

**Comment by graykkutu** [comment]
``npm install -g grunt-cli`` 이렇게 해서 설치는 된 것 같습니다만..
grunt.cmd를 눌러도 어떤 명령어만 나오고 창이 닫힙니다

**Comment by lshqqytiger** [comment]
```cmd
npm uninstall grunt grunt-cli
npm install grunt@1.0.4 grunt-cli@1.2.0
grunt default pack
```

**Comment by graykkutu** [comment]
![화면 캡처 2021-07-03 183349](https://user-images.githubusercontent.com/85274920/124350048-4db0bf00-dc2d-11eb-8e3b-d0d1f301e990.png)

**Comment by graykkutu** [comment]
``grunt default pack`` 을 입력하니 이렇게 창이 나옵니다

**Comment by lshqqytiger** [comment]
body.js에 자바스크립트 문법에 맞지 않는 잘못된 내용이 들어가 있습니다.

**Comment by graykkutu** [comment]
경로는 ``C:\Users\ealjs\Desktop\KKuTu-master\Server\lib`` 에서 진행하였습니다만

**Comment by lshqqytiger** [comment]
경로는 그게 맞는데 오류 로그 중에서 중요한 부분만 빼고 캡처가 되었습니다.

**Comment by graykkutu** [comment]
![화면 캡처 2021-07-03 184002](https://user-images.githubusercontent.com/85274920/124350189-1a226480-dc2e-11eb-98a8-a395e32a77c6.png)

**Comment by graykkutu** [comment]
``body.js`` 는 전혀 손을 댄적이 없습니다만 ( 레벨 확장만 수정하였는데..)

**Comment by graykkutu** [comment]
아 그리고 ``grunt default pack`` 를 입력했을때, ``grunt.cmd``를 입력하고 나온거랑 똑같습니다 (grunt.cmd는 나오는 창이 0.1초 밖에 안 되서 잘 못 보긴 했지만요)

**Comment by lshqqytiger** [comment]
[Server\lib\Web\lib](https://github.com/JJoriping/KKuTu/tree/master/Server/lib/Web/lib) 폴더 내 모든 파일을 원본으로 교체 후 다시 시도해보세요.

**Comment by graykkutu** [comment]
모두 교체 해도 그렇습니다...
이거 뭐ㅈ

**Comment by lshqqytiger** [comment]
![1](https://user-images.githubusercontent.com/39524005/124350423-a41efd00-dc2f-11eb-9019-be015586dd97.png)
저는 너무 잘되는데요.

grunt를 못쓰시겠다면 그냥 외부 unminifier를 통해 (그나마) 보기 편하게 만드신 후 minifier로 압축하시는 방법을 쓰시거나 minify를 하지 않고 사용하는 방법도 있습니다.

**Comment by graykkutu** [comment]
그 2번쨰 task 하고 바로 창이 꺼져버립니다

**Comment by lshqqytiger** [comment]
혹시 grunt.cmd를 직접 실행하셨나요

**Comment by graykkutu** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그래서 그랬던 거군요 cmd로 하니 잘 되네요

**Comment by graykkutu** [comment]
근데 grunt로 어떻게 편집하라는 건지 막막하네요..

**Comment by lshqqytiger** [comment]
grunt는 코드 편집기가 아니고 uglifier입니다.
원본 코드(Server\lib\Web\lib)를 수정한 후 grunt를 돌리면 Server\lib\Web\public\js에 minify된 파일들이 생성됩니다.
문제 해결되셨으면 이슈 닫아주세요.

**Comment by graykkutu** [comment]
#437 에 맞춰서 ``in_game_kkutu_shop.css`` ``in_game_kkutu_min.js(?)`` 를 수정하였는데 표시가 나질 않습니다
![제목 없음](https://user-images.githubusercontent.com/85274920/124353317-beada200-dc40-11eb-97c8-9ffe3689bf6c.png)

**Comment by lshqqytiger** [comment]
body.js를 수정하고 grunt를 돌리신 건가요?

**Comment by ehxhfl7** [comment]
body.js와 in_game_kkutu.js를 수정하고 grunt를 돌려서 적용해보세요

**Comment by jhj1228** [comment]
body.js를 수정안하신 듯 합니다.

**Comment by graykkutu** [comment]
지금 까지 도와 주신 모든 분들 감사합니다.
성공했습니다!
