### ISSUE TITLE
소셜로그인 오류

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#908]
디스코드 로그인을 구현하고 로그인을 할려는데 에러가 발생했습니다.
수정한것은 auth.json의 파일입니다. 어떻게 해야하나요?
![계정 액세스를 승인하기  - Chrome 2021-07-10 오후 7_48_50](https://user-images.githubusercontent.com/75468001/125160524-5585db80-e1b8-11eb-917a-080085b99bea.png)

**Comment by jhj1228** [comment]
디스코드 개발자 사이트에서 애플리케이션을 등록하고 ID와 시크릿 코드를 부여받아 auth.json에 넣으셨나요? 만일 하셨다면 리다이렉트 URL을 안적으셨거나 올바르지 않은 것 같습니다.

**Comment by lshqqytiger** [comment]
![1](https://user-images.githubusercontent.com/39524005/125160926-5d467f80-e1ba-11eb-9be2-e5ee3b371137.png)
이 화면까지는 진행되던가요?

**Comment by wd5dw** [comment]
> ![1](https://user-images.githubusercontent.com/39524005/125160926-5d467f80-e1ba-11eb-9be2-e5e

> ![1](https://user-images.githubusercontent.com/39524005/125160926-5d467f80-e1ba-11eb-9be2-e5ee3b371137.png)
> 이 화면까지는 진행되던가요?

아니요

**Comment by wd5dw** [comment]
> ![1](https://user-images.githubusercontent.com/39524005/125160926-5d467f80-e1ba-11eb-9be2-e5ee3b371137.png)
> 이 화면까지는 진행되던가요?

아니요

**Comment by lshqqytiger** [comment]
auth.json에 잘못된 값을 입력하신 것 같습니다. 제대로 입력하셨는지 확인해주세요.

**Comment by jhj1228** [comment]
디스코드 개발자 사이트에서 부여받은 ID와 시크릿 코드를 auth.json에 정확히 넣었는지 봐주세요.

**Comment by wd5dw** [comment]
감사합니다. 해결되었습니다.
