### ISSUE TITLE
접속 문제

### ISSUE THREAD

**Issue by CHEEY-BORIN** [JJoriping/KKuTu#909]
안녕하세요
어디서 문제인지 몰라 이슈 엽니다.

계속 게임 시작을 눌르면

사이트 연결할 수 없음 ( 웨일 )

이 뜹니다

만일 된다면 불러오는 중 ... 앞으로 1에서 멈추거나 아예 로딩이 안됩니다.

왜이러는 건가요?

암만 찾아봐도 오류는 없어 보입니다.

오류는 따로 뜨는것은 없고요 redis 도 잘 켜져있습니다.

**Comment by CHEEY-BORIN** [comment]
redis 문제 같습니다
사람임님이 한번 마이크로소프트 레디스로 바꾸라고 해서 바꿔봤더니 이번엔 이렇게 뜹니다
![image](https://user-images.githubusercontent.com/79044687/125188167-c3400f00-e26d-11eb-80d3-37853529cd2c.png)
.

**Comment by CHEEY-BORIN** [comment]
한마디로 똑같습니다

**Comment by lshqqytiger** [comment]
접속이 불가능한 것과 레디스는 직접적인 상관관계가 없습니다.
게임 서버로 연결이 안되는 것은 8080 포트가 닫혀있기 때문입니다.
![화면 캡처 2021-07-11 173218](https://user-images.githubusercontent.com/39524005/125188232-0ac69b00-e26e-11eb-93f0-77f8e853aa95.png)

**Comment by CHEEY-BORIN** [comment]
8080포트가 아니라면 어떻게 돼나요?

**Comment by lshqqytiger** [comment]
게임서버 포트를 8080이 아닌 다른 포트로 설정하셨나요?

**Comment by CHEEY-BORIN** [comment]
아니요 8080포트 설정을 다른 설정으로 하면 어떻게 돼는지 궁금해서 그런겁니다

**Comment by lshqqytiger** [comment]
서버에서 포트 설정을 바꾸면 다른 포트로 연결할 수 있죠

**Comment by CHEEY-BORIN** [comment]
SKB 는 외부포트 설정을 어디서 해야 할까요..ㅠㅠ

**Comment by jhj1228** [comment]
SK를 안써서 모르겠는데 공유기마다 사이트가 각각 다른 것 같네요. 공유기 홈페이지로 들어갔을 때 뭐가 뜨는지 알 수 있을까요?

**Comment by CHEEY-BORIN** [comment]
![image](https://user-images.githubusercontent.com/79044687/125189968-c939ee00-e275-11eb-921e-236418ce49ca.png)

**Comment by lshqqytiger** [comment]
8888번 포트로 접속 시 8080으로 연결되게 되어있네요.
global.json에서 게임서버 포트를 8888로 바꿔보세요.

**Comment by CHEEY-BORIN** [comment]
접속 완료로 이슈 닫습니다.
