### ISSUE TITLE
사용자 차단을 푸는 방법

### ISSUE THREAD

**Issue by SkyLightQP** [JJoriping/KKuTu#91]
테스트로 제 자신한테 차단을 해보았고 풀기 위해 관리자 페이지에 차단 칸을 비워놨습니다만
풀리지 않고 직접 DB에서 차단 칸을 비워놔도 풀리지 않고 사유가 [null]로만 뜨네요...

계정 자체를 삭제해야 풀리나요?
아니면 어떻게 푸나요?

**Comment by Ganggroid** [comment]
쿼리문으로 초기화 해주셔야합니다.
