### ISSUE TITLE
구글 로그인에서 오류

### ISSUE THREAD

**Issue by cho060303** [JJoriping/KKuTu#92]
일단 계정 권한 동의까지는 잘 넘어가는데 그 뒤가 문제네요.

로그 : `Error when querying: INSERT INTO session ("profile", "createdAt", "_id") VALUES 
Context: error: syntax error at or near "ON"` 이렇네요 어떻게 고쳐야 하나요

**Comment by JJoriping** [comment]
해당 오류는 이슈 #70 에서 다루어진 문제와 같아 보이니 확인해 보세요.

**Comment by cho060303** [comment]
감사합니다.
