### ISSUE TITLE
무슨 오류인가요?

### ISSUE THREAD

**Issue by graykkutu** [JJoriping/KKuTu#920]
lnternal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\Web\lang\ko_KR.json: Unexpected token \ in JSON at position 3002 at parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\ㅁㄴㅇㄹ\Desktop\KKuTu-master\Server\lib\sub\webinit.js:22:11) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)

이렇게 하곤 서버가 꺼집니다.

**Comment by CHEEY-BORIN** [comment]
모듈 설치가 잘못 되어 보입니다.

**Comment by CHEEY-BORIN** [comment]
server-flush 하시고 다시 server-setup 하시면 될듯 합니다.

**Comment by CHEEY-BORIN** [comment]
저가 보기에는 모듈 설치중 오류가 발생하여 설치가 제대로 안된것으로 보입니다. 그리하여 모듈 오류가 뜬것으로 보입니다.

**Comment by kache13** [comment]
> 저가 보기에는 모듈 설치중 오류가 발생하여 설치가 제대로 안된것으로 보입니다. 그리하여 모듈 오류가 뜬것으로 보입니다.

저건 모듈 오류가 아닙니다. ko_KR.json 파일에서
Json 문법에 맞지않는 텍스트를 써서 그렇습니다.

**Comment by CHEEY-BORIN** [comment]
저가 아직 JLog 오류를 습득을 못해서 그런거 그런거로 보입니다. 모듈 오류는 아닌걸로 보이긴 합니다.

**Comment by lshqqytiger** [comment]
JSON 문법에서는 Escape Character라고 해서 `\`를 그냥 쓸 경우 의도대로 동작하지 않습니다.
`\` 부분을 `\\`로 바꾸신 후 다시 시도하세요.

**Comment by graykkutu** [comment]
ko_KR.json 파일을 싹 바꿨더니 오류가 해결되었습니다
