### ISSUE TITLE
채팅 관련 질문

### ISSUE THREAD

**Issue by wd5dw** [JJoriping/KKuTu#927]
끄투 서버를 만들고 나서 채팅을 빠르게 치면 
"과도한 메시지 전송으로 관련 기능을 잠시 이용할 수 없습니다."
라는 문구가 뜨고 채팅을 잠시 칠 수 없게 되는데 어떤 부분을 수정해야 이 기능을 없앨 수 있나요?

**Comment by lshqqytiger** [comment]
#924 에서 이미 답변드렸습니다.

**Comment by wd5dw** [comment]
> #924 에서 이미 답변드렸습니다.

kkutu.js의 어떤 부분을 수정해야하는지 잘 모르겠습니다.

**Comment by lshqqytiger** [comment]
그건 깃허브 이슈에서 다룰 만한 내용이 아닙니다.
ko_KR.json에서 관련 부분을 찾아보면 blocked라는 키워드가 나옵니다.
해당 키워드를 기반으로 IDE의 검색 기능을 이용하면 됩니다.
이런 내용은 깃허브 이슈에서 다루지 않으므로 디스코드 등의 커뮤니티를 이용해 주셨으면 좋겠습니다.

**Comment by haekr** [comment]
> > #924 에서 이미 답변드렸습니다.
> 
> kkutu.js의 어떤 부분을 수정해야하는지 잘 모르겠습니다.

https://blog.naver.com/dosel1005/220585511118

이거를 확인해도 좋을것 같네요.
