### ISSUE TITLE
SSL 인증서 에러

### ISSUE THREAD

**Issue by wkddndud12** [JJoriping/KKuTu#928]
인증서를 적용 시키니 이런 에러가 뜹니다

internal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\global.json: Unexpected token x in JSON at position 518 at parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)
G: CLOSED WITH CODE 1
internal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\global.json: Unexpected token x in JSON at position 518 at parse (&lt;anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.&lt;anonymous> (C:\Users\Administrator\Desktop\KKuTu\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)
Worker 2296 died

**Comment by wkddndud12** [comment]
그리고 인증서를 넣는 경로는 어디 인가요

**Comment by haekr** [comment]
> 인증서를 적용 시키니 이런 에러가 뜹니다
> 
> internal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\global.json: Unexpected token x in JSON at position 518 at parse (<anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.<anonymous> (C:\Users\Administrator\Desktop\KKuTu\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)
> G: CLOSED WITH CODE 1
> internal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\global.json: Unexpected token x in JSON at position 518 at parse (<anonymous>) at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object.<anonymous> (C:\Users\Administrator\Desktop\KKuTu\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)
> Worker 2296 died

이런식으로 오류가 뜨는 경우는. 예를 들자면, SSL 경로를 
C:\(asdf)\ADMIN\바탕화면\KKUTU\SSL (\) \ 이 아닌, /을 적용해주세요,(C:/(asdf)/ADMIN/바탕화면/KKUTU/SSL 이런식으로 적용해주세요!) 안그러면 JSON 문법때매 오류납니다.

**Comment by graykkutu** [comment]
> > 인증서를 적용 시키니 이런 에러가 뜹니다
> > internal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\global.json: Unexpected token x in JSON at position 518 at parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object. (C:\Users\Administrator\Desktop\KKuTu\Server\lib\const.js:19:14) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)
> > G: CLOSED WITH CODE 1
> > internal/modules/cjs/loader.js:1044 throw err; ^ SyntaxError: C:\Users\Administrator\Desktop\KKuTu\Server\lib\sub\global.json: Unexpected token x in JSON at position 518 at parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Object. (C:\Users\Administrator\Desktop\KKuTu\Server\lib\Web\db.js:22:15) at Module._compile (internal/modules/cjs/loader.js:999:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) at Module.load (internal/modules/cjs/loader.js:863:32)
> > Worker 2296 died
> 
> 이런식으로 오류가 뜨는 경우는. 예를 들자면, SSL 경로를
> C:(asdf)\ADMIN\바탕화면\KKUTU\SSL () \ 이 아닌, /을 적용해주세요,(C:/(asdf)/ADMIN/바탕화면/KKUTU/SSL 이런식으로 적용해주세요!) 안그러면 JSON 문법때매 오류납니다.

Windows의 경우 폴더를 \ 로 나타냅니다. 하지만 \가 JSON에서는 escape 문자로 사용됩니다. 모든 \는 \\로 바꾸어 주셔야 합니다. 예시: C:\ssl\cert.pem 의 경우, C:\\ssl\\cert.pem 으로 바꿔주면 됩니다. 이 사항은 리눅스에서도 폴더 이름에 \가 들어갈 경우에는 같은 방식으로 바꿔주시면 됩니다.
