### ISSUE TITLE
서버가 오프라인이며, 에러도 뜨지않고, 링크로는 잘 들어가집니다.

### ISSUE THREAD

**Issue by boyangsic** [JJoriping/KKuTu#930]
> [2021-08-06 23:45:36] Master DB is ready.
> [2021-08-06 23:45:38] << KKuTu Web >>
> [2021-08-06 23:45:38] << KKuTu Server:8496 >>
> [2021-08-06 23:45:39] DB is ready.
> [2021-08-06 23:45:39] OAuth Strategy daldalso is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy naver is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy facebook is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy google is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy twitter is not loaded
> [2021-08-06 23:45:39] OAuthStrategy requires a consumerKey option
> [2021-08-06 23:45:39] OAuth Strategy kakao is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy discord is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy twitch is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy github loaded successfully.
> [2021-08-06 23:45:39] OAuth Strategy line is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy instagram is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] OAuth Strategy spotify is not loaded
> [2021-08-06 23:45:39] OAuth2Strategy requires a clientID option
> [2021-08-06 23:45:39] New user #guest__1
> [2021-08-06 23:45:39] Game server #1 connected
> [2021-08-06 23:45:39] DB is ready.

로그입니다.

**Comment by boyangsic** [comment]
서버를 127.0.0.2로 하니까 잘 열리네요! 다음부터는 제대로 확인하고 올릴게요.

**Comment by boyangsic** [comment]
서버를 127.0.0.2로 하니까 잘 열리네요! 다음부터는 제대로 확인하고 올릴게요.

**Comment by CHEEY-BORIN** [comment]
127.0.0.2 는 로컬호스트랑 똑같습니다. 개인만의 플레이만 가능하며 상대방이 접속 할려면 호스트 IP주소 또는 호스트 IP로 되어있는 도메인으로 접속 해야합니다.

**Comment by graykkutu** [comment]
ip.pe.kr에서 확인하십시오
