### ISSUE TITLE
닉네임 html태그.

### ISSUE THREAD

**Issue by boyangsic** [JJoriping/KKuTu#933]
닉네임의 html태그를 막는법을 알고싶습니다.

**Comment by boyangsic** [comment]
![wwaddawwdwad](https://user-images.githubusercontent.com/53971009/129380959-3a1a03ec-c041-4b2b-884d-f5d9f85a21ef.PNG)

**Comment by lshqqytiger** [comment]
#689

**Comment by boyangsic** [comment]
넵. 죄송합니다. 이슈규칙 확인 잘 하고 올리도록 하겠습니다
