### ISSUE TITLE
인증서 위치

### ISSUE THREAD

**Issue by soshimee** [JJoriping/KKuTu#936]
인증서를 어디서 읽어드리는지 모르겠습니다... 그것만 있으면 되는데..

**Comment by ehxhfl7** [comment]
#689

**Comment by lshqqytiger** [comment]
절대경로입니다.

**Comment by haekr** [comment]
#928

**Comment by papakia1234** [comment]
./Server/lib/sub/global.json 입니다
https://github.com/JJoriping/KKuTu/wiki/SSL 에서 확인하시면 되는데 무분별한 이슈 생성 자제 부탁드립니다

**Comment by soshimee** [comment]
위키가 있었군요...

**Comment by papakia1234** [comment]
닫아주세요

**Comment by ljoljo9959** [comment]
#689

**Comment by ljoljo9959** [comment]
도토리님과 나의 압박으로 결국 이슈를 닫아버렸다.

**Comment by soshimee** [comment]
까먹었던것...
