### ISSUE TITLE
하위 경로 (ex: https://www.example.com/kkutu) 설정 방법 문의 입니다.

### ISSUE THREAD

**Issue by zzstudio-dev** [JJoriping/KKuTu#938]
안녕하세요. 끄투 홈페이지와 다른 홈페이지를 함께 운영해야해서 하위 경로 설정 방법에 대해 문의 드립니다.
예를 들어 https://www.example.com/kkutu 에 접속하면 끄투가 나오고, https://www.example.com에 접속하면 제가 운영중인 홈페이지(PHP 기반)이 나오게 하고 싶습니다.
해결 방안 부탁드립니다.

**Comment by lshqqytiger** [comment]
nginx로 가능할 것 같습니다.
이 곳은 끄투 레포지토리 자체의 문제점에 대해 기술하는 곳입니다. #689
