### ISSUE TITLE
로그인 API / 단어 쿼리로 추가

### ISSUE THREAD

**Issue by Sichisky** [JJoriping/KKuTu#94]
어.. 가정용 인터넷으로 서버를 열거라 80 포트가 지원 되지 않아서
3포트를 이용하니 주소:3 이잖아요,
여기서 네아로 같은 API가 :3 에 적용 안될 뿐더러
callback URL를 같은 URL로 설정하면 오류가 납니다. 이거 무슨 현상이죠..? 네이버에 문의해야하나요?

그리고, gwalli 의 단어 추가를 어떻게 해야하는지 모르겠어서..
단어를 쿼리를 이용해 추가하는법이 궁금합니다..!

**Comment by JJoriping** [comment]
주제가 다른 질문은 다른 분들이 찾아 보기가 쉽도록 가급적 별도의 이슈로 등록하는 것을 권합니다.

1. 네이버에서 특정 포트(80이나 443 등)로만 연결이 가능하게 제한했다고는 생각하지 않습니다만, 해당 문제는 끄투 쪽에서 건드릴 수 있는 문제가 아닌 것 같습니다. [네이버 개발자 센터 포럼](http://forum.developers.naver.com/) 쪽으로 문의를 해 보세요.

2. 본 레포지토리 위키의 [`Agent`의 `PostgresTable`](https://github.com/JJoriping/KKuTu/wiki/S~collection.js~Agent#%ED%95%A8%EC%88%98-%EB%AA%A9%EB%A1%9Dpostgrestable-%EC%9D%B8%EC%8A%A4%ED%84%B4%EC%8A%A4)에서 정의하고 있는 `direct` 함수를 이용할 수 있습니다.

**Comment by Sichisky** [comment]
제가 psql에 대해서도 아무것도 모르는데 어떻게 해아하죠..?
direct 함수..를 어떻게..해야..

**Comment by JJoriping** [comment]
psql은 [블로그](http://blog.jjo.kr/220935346136)에서 조금 언급되었지만 PostgreSQL 서버와 통신하는 프로그램입니다. 이 프로그램으로 서버와 연걸한 뒤 SQL을 이용하면 데이터베이스를 다룰 수 있습니다. psql이나 SQL 등에 대한 자세한 내용은 검색어 "psql 사용법" 등으로 검색해 보시길 권해 드립니다.

**Comment by Sichisky** [comment]
감사합니다!

**Comment by Sichisky** [comment]
저와 같은 오류가 뜨시는분들을 위해 코멘트 하나 달겠습니다!

저는 in_login_min.js 의 callback url 를 설정하지 않아 생긴 오류였습니다.
in_login_min.js / in_login.js 에서 redirect 를 callbackurl 과 같게 해주시면 됩니다.
저같은 경우 http://아이피:3/ 로 하였습니다!
