### ISSUE TITLE
끄투 파일 터미널에서 실행

### ISSUE THREAD

**Issue by dug0m** [JJoriping/KKuTu#940]
서버를 리눅스 터미널을 사용합니다.
끄투 매니저 프로그램이 일렉트론으로 알고있는데 이러면 끄투 서버는 리눅스 터미널에서 어떻게 여나요? 코드가 따로 있나요?

**Comment by chuhyeonjin** [comment]
[README](https://github.com/JJoriping/KKuTu#linux-%ED%99%98%EA%B2%BD) 읽으시면 거기에 다 나와있습니다
