### ISSUE TITLE
메인화면 업데이트 목록 수정

### ISSUE THREAD

**Issue by jusnorare** [JJoriping/KKuTu#943]
진짜 이런 사소한것까지 이슈 열어서 죄송합니다.
메인 화면에 있는 업데이트 목록 수정 어떻게 하나요?

**Comment by graykkutu** [comment]
`kkutu_bulletin.html` 말씀하시는 건가요?

**Comment by ehxhfl7** [comment]
메인 화면에 있는 업데이트 목록 파일 위치 : `Server\lib\Web\public\kkutu_bulletin.html`
![image](https://user-images.githubusercontent.com/57280515/133050549-504cf5a7-7dfd-433b-a3f5-870a7f1bf998.png)
와 같은 방식으로 버전/업데이트 날짜/업데이트 내용 등을 추가하시면 됩니다. 알아서 요령껏 수정하시면 됩니다.

그리고 같은 내용의 이슈가 있습니다. 같은 내용의 이슈가 있는지 꼼꼼히 확인하고 이슈 올려주세요. #214

**Comment by lshqqytiger** [comment]
Duplicate of #214
