### ISSUE TITLE
몇개 질문합니다

### ISSUE THREAD

**Issue by jusnorare** [JJoriping/KKuTu#944]
1. 새로운 라운드 초 추가는 어떻게 하나요
  - 다른 이슈를 참고하여 추가하였는데 3초 및 300초는 0초로 표시됩니다.
  - 그리고 해보니 모바일은 아예 추가가 되지 않았습니다.

2. 갑자기 라운드 초가 (L#영어라 모름)라고 뜨는데 어떻게 해결하나요
  - 새로운 라운드 초 추가하고 보니 저렇게 되어있습니다.

3. 새로운 규칙을 추가하려면 무슨 자바 파일을 만져야 하나요

4. 창 위에 노란색 공지사항 같은거는 어떻게 띄우나요

**Comment by graykkutu** [comment]
#689

**Comment by lshqqytiger** [comment]
Duplicate of #24 #299 #671

**Comment by jusnorare** [comment]
#299 를 보고 따라 하였는데 3초 및 300초는 0초로 뜨면서 사용하면 방 설정이 잘못되었다고 뜹니다.
그리고 2번에 대한 답변을 해주세요

**Comment by lshqqytiger** [comment]
#689 이곳은 프리서버 내 기능 구현에 대해 묻는 곳이 아닙니다.
