### ISSUE TITLE
서버 콘솔 원 색이 이상해져요

### ISSUE THREAD

**Issue by emptyme** [JJoriping/KKuTu#95]
![ejwfwvsohcamamc7cadaykpibqgsnkstgro_nnv3nfmaz1xmm4dqnxvafs4iy7dtzerwbrnpv839nlbidvk1l-ourbmcooqy1obl9ikolodiou8h-yibkkciepjd8rlt3mzvdwngirw](https://cloud.githubusercontent.com/assets/9034282/26035522/c07d8ff8-3908-11e7-91c9-41faa271fb86.png)
이런식으로 콘솔 위에 있는 원 색이 구운 계란 노른자 색이 되는데, 이렇게 되면 서버는 열려있고 이미 접속 된 사람은 플레이를 하는데, 접속은 안되요 ㅠㅠ 서버를 재시작하면 되긴 되는데 왜이럴까요?

**Comment by JJoriping** [comment]
웹 서버에 오류가 생겨 종료된 경우 발생합니다. 이 경우 종료의 원인이 된 오류 내용을 보여야 원인 분석이 가능합니다. 현재 끄투 서버 관리자를 사용하는 경우 (가능하다면) 게임 서버로 별도 공지 후 서버를 재시작하는 수 밖에 없습니다.
