### ISSUE TITLE
끄투 튕김오류

### ISSUE THREAD

**Issue by rainbow1017** [JJoriping/KKuTu#954]
끄투 서버를 운영하면서 1분에 1번씩은 튕기는거같습니다.
서버와의 연결이 종료되었습니다. (#1006).
그런데 다른분들은 안 튕기는거같네요.
끄투만 그래서 이슈남깁니다
제 컴퓨터가 끄투랑 맞지 않나요?왜 그럴까요.

**Comment by lshqqytiger** [comment]
포트포워딩 및 방화벽 설정이 되어 있나요?

**Comment by lshqqytiger** [comment]
WAF 사용 중이신가요?

**Comment by CJwKr** [comment]
만약 CloudFlare(WAF)를 사용중이시라면, WAF 서비스에서는 1분동안 응답이 없을경우 튕기게 되니,
WAF PR을 적용한후, 다시 한번 접속해보세요.

**Comment by rainbow1017** [comment]
저는 WAF사용하지 않고있습니다.

**Comment by rainbow1017** [comment]
그리고 게임 중에만 튕기는 오류같습니다. 서버 로그에는 다른건 뜨지 않고  Exit만 뜨고요

**Comment by norhu1130** [comment]
개발자 로그를 확인해보세요.

**Comment by rainbow1017** [comment]
단순 렉이었습니다
