### ISSUE TITLE
잇기 게임중에서 사전에 단어가 없을시 게임이 끊김

### ISSUE THREAD

**Issue by rainbow1017** [JJoriping/KKuTu#955]
예시로 기차->차ㄴ어ㅐㅑㅓㄷㄹ 이렇게 적으면
아무것도 안뜨면서 게임이 멈추고
![1](https://user-images.githubusercontent.com/93560564/141036544-b2d65b0b-fe5d-4ae2-b0db-4edd8b89ee71.PNG)
이렇게 게임이 멈춰버립니다. 어떤 오류일까요

**Comment by rainbow1017** [comment]
단어 대결 같은것만 오류가 안뜹니다

**Comment by jhj1228** [comment]
로그를 보여주셔야 어떤 오류인지 파악할 수 있습니다

**Comment by rainbow1017** [comment]
Redis로그와 끄투 로그엔 어떠한 오류도 뜨지 않고 입력했다고만 뜹니다.

**Comment by lshqqytiger** [comment]
개발자도구를 통해 프론트엔드 쪽 오류를 봐야합니다.

**Comment by rainbow1017** [comment]
죄송합니다. 어디서 보는지 알수 있을까요?

**Comment by rainbow1017** [comment]
콘솔에는 오류가 안뜨네요

**Comment by lshqqytiger** [comment]
![화면 캡처 2021-11-10 174522](https://user-images.githubusercontent.com/39524005/141079919-2c6492bc-2a19-4e4a-a247-1ededc886dcc.png)

**Comment by rainbow1017** [comment]
kkutu.club/:7 GET https://kkutu.club/js/in_kkutu.min.js net::ERR_ABORTED 404 (Not Found)
DevTools failed to load source map: Could not load content for https://kkutu.club/js/jquery.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
in_game_kkutu.min.js:20 관리자 모드
in_game_kkutu.min.js:20 room-conn 1 105
in_game_kkutu.min.js:20 room-disc 1 105
in_game_kkutu.min.js:20 room-conn 1 105

**Comment by lshqqytiger** [comment]
그 내용이 전부인가요?

**Comment by rainbow1017** [comment]
네

**Comment by lshqqytiger** [comment]
정확히 증상이 어떻게 될까요
혹시 동영상 녹화나 서버 주소를 얻을 수 있을까요?

**Comment by rainbow1017** [comment]
https://kkutu.club

**Comment by lshqqytiger** [comment]
백엔드, 프론트엔드에서 오류가 발생하지 않고 있기 때문에 직접 디버깅해보지 않는 한 해결하기 힘듭니다.
또한 현재 공개된 레포지토리에 업로드 된 파일들이 서버에서 실제 사용하고 있는 것과 많이 다른 것 같기 때문에 도움드리기가 어렵습니다.

**Comment by rainbow1017** [comment]
네 그럼 제가 파일 수정한것들을 일부 되돌려보겠습니다.

**Comment by rainbow1017** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
cdn.discordapp.com/avatars/904280251281068063/null.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
추가로 이게 뜨는데 이것도 관련된건가요?

**Comment by rainbow1017** [comment]
콘솔

**Comment by lshqqytiger** [comment]
디스코드 OAuth를 통해 접속한 유저의 프로필 사진을 불러오지 못하고 있는 것 같은데 이 이슈와는 무관합니다.

**Comment by rainbow1017** [comment]
고쳐졌습니다.
