### ISSUE TITLE
cluster.js 1006 에러

### ISSUE THREAD

**Issue by soshimee** [JJoriping/KKuTu#957]
```
[2021-11-26 19:07:51] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2021-11-26 19:07:51] Game server #1 closed: 1006
```
위와 같은 오류가 발생합니다.
PostgreSQL은 실행중이고 게임 서버 먼저 실행했습니다.
#123 과 #148 이랑 동일한 문제로 보이는데, PostgreSQL을 직접 실행해도 똑같은 문제가 발생합니다.
혹시 몰라 거꾸로 실행시켜도 보았지만 동일한 오류가 발생합니다.

**Comment by chuhyeonjin** [comment]
#840 과 같은 문제로 보입니다

**Comment by lshqqytiger** [comment]
Already resolved at #840

**Comment by soshimee** [comment]
Node.js 15 이상을 요구하는 다른 서버도 구동하고 있어 다운그레이드는 어려울 것 같습니다.

**Comment by lshqqytiger** [comment]
최신버전의 Node.js와 동작하는 PR을 준비 중에 있습니다.
큰 문제가 없다면 약간 불안정한 상태로 일주일 내로 올라올 것으로 보입니다.
그 전까지는 직접 해결책을 찾으시는 것 밖에는 방법이 없습니다.

**Comment by Preta-Crowz** [comment]
#123, #148, #840과는 다른 문제로 보입니다. 이미 반년 가까이 된 이슈이지만, 방금 새로 등록한 #1024 이슈가 동일한 현상인것 같습니다.
