### ISSUE TITLE
서버를 키니까 오류가 납니다

### ISSUE THREAD

**Issue by rainbow1017** [JJoriping/KKuTu#960]
[2021-11-30 14:07:24] &lt;&lt; KKuTu Web >>
internal/modules/cjs/loader.js:573 throw err; ^ Error: Cannot find module './routes/major' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15) at Function.Module._load (internal/modules/cjs/loader.js:497:25) at Module.require (internal/modules/cjs/loader.js:626:17) at require (internal/modules/cjs/helpers.js:20:18) at C:\Users\user\Desktop\KKuTu\Server\lib\Web\main.js:205:2 at Array.forEach (&lt;anonymous>) at Object.&lt;anonymous> (C:\Users\user\Desktop\KKuTu\Server\lib\Web\main.js:204:8) at Module._compile (internal/modules/cjs/loader.js:678:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10) at Module.load (internal/modules/cjs/loader.js:589:32)
오늘 수정한 파일 쭉~봤는데 오류가 될만한건 하나도 없네요

**Comment by rainbow1017** [comment]
+비슷한 이슈 다 살펴보았습니다

**Comment by jhj1228** [comment]
routes 폴더에 major.js 파일이 있나요?

**Comment by rainbow1017** [comment]
routes 파일이 없어졌네요..?

**Comment by rainbow1017** [comment]
아 제가 착각했네요 major.js 있네요..그런데도 똑같네요

**Comment by rainbow1017** [comment]
아 제가 2번이나 착각했네요 파일위치가 잘못됐네요..
