### ISSUE TITLE
서버 오류인가요?

### ISSUE THREAD

**Issue by masimellomi** [JJoriping/KKuTu#961]
포트포워딩 및 기본 설정을 완료하고 서버를 열었습니다.

Edge 및 localhost에서는 문제없이 잘 작동하는데,

크롬에서는 서버와의 연결이 끊어짐, 혹은 아예 접속이 안되는 증상이 발생합니다.

왜 그러는지에 대한 이유와 함께 해결방안을 말씀해주시면 감사하겠습니다.

**Comment by lshqqytiger** [comment]
증상에 대한 언급이 확실하지 않아 답변이 어렵습니다.

1. **localhost를 통한 접속, 외부 IP 주소를 통한 접속 두 가지 상황 모두** Edge 브라우저에서는 접속이 되지만 Chrome 브라우저에서는 접속이 되지 않는다.
2. **브라우저 환경과 무관하게** localhost를 통한 접속은 문제 없으나 외부 IP 주소를 통한 접속에서는 문제가 발생한다.
3. Edge 브라우저를 사용해 localhost로 접속할 때는 문제가 없었으나 Chrome 브라우저를 사용해 외부 IP를 통해 접속 시 문제가 발생한다.

3번 상황의 경우 (같은 디바이스에서 이뤄진 접속 시도였다는 가정 하에) Edge 브라우저와 Chrome 브라우저에서 각각 localhost로의 접속, 외부 IP 주소로의 접속 모두 가능한지 여부를 알아야 명확한 해결 방안을 제안해 드릴 수 있습니다.
조작 변인이 브라우저 환경 뿐인지(네트워크 환경 조건 및 같은 디바이스 여부가 통제된 상황인지) 알아야 합니다.

**Comment by masimellomi** [comment]
Edge와 Chrome에서 동일한 주소로 접속헀을때 (도메인 설정 후)
Edge는 정상적으로 작동하지만.
Chrome는 작동하지 않았습니다.
