### ISSUE TITLE
이 오류는 뭔가요?

### ISSUE THREAD

**Issue by kogunggom111** [JJoriping/KKuTu#969]
서버 상태가 이상해서 nodejs 버전을 0.12.0 으로 바꾸었는데 이 오류가 났습니다.
C:\Users\ksh-0\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\cluster.js:23 console.log(Invalid CPU Number ${CPU}); ^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16) at node.js:814:3
C:\Users\ksh-0\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\cluster.js:30 console.log(Invalid Server ID ${process.argv[2]}); ^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16) at node.js:814:3
W: CLOSED WITH CODE 1
G: CLOSED WITH CODE 1

이 문제는 어떻게 해결하나요?

**Comment by lshqqytiger** [comment]
[이전 답변](https://github.com/JJoriping/KKuTu/issues/968#issuecomment-1027828296)
12.22.9 버전으로 재설치하시면 됩니다.

**Comment by CJwKr** [comment]
> 서버 상태가 이상해서 nodejs 버전을 0.12.0 으로 바꾸었는데 이 오류가 났습니다. C:\Users\ksh-0\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Web\cluster.js:23 console.log(Invalid CPU Number ${CPU}); ^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16) at node.js:814:3 C:\Users\ksh-0\Desktop\KKuTu-5663dd47d53b05c6c16f1e0568eef5b5095e3ca2\Server\lib\Game\cluster.js:30 console.log(Invalid Server ID ${process.argv[2]}); ^ SyntaxError: Unexpected token ILLEGAL at exports.runInThisContext (vm.js:73:16) at Module._compile (module.js:443:25) at Object.Module._extensions..js (module.js:478:10) at Module.load (module.js:355:32) at Function.Module._load (module.js:310:12) at Function.Module.runMain (module.js:501:10) at startup (node.js:129:16) at node.js:814:3 W: CLOSED WITH CODE 1 G: CLOSED WITH CODE 1
> 
> 이 문제는 어떻게 해결하나요?

https://nodejs.org/es/blog/release/v12.22.9/
Windows 32-bit Installer(4GB 이하), Windows 64-bit Installer(4GB 이상) 다운받으세요

**Comment by kogunggom111** [comment]
> [이전 답변](https://github.com/JJoriping/KKuTu/issues/968#issuecomment-1027828296) 12.22.9 버전으로 재설치하시면 됩니다.

안되는데..........
어떻게 하죠?

**Comment by lshqqytiger** [comment]
기존 버전(0.12.0)을 제거 후 12.22.9를 설치하시고 다시 시도하셨는데도 같은 증상(SyntaxError: Unexpected token ILLEGAL)이 나타난다는 말씀이신가요?

**Comment by kogunggom111** [comment]
> 기존 버전(0.12.0)을 제거 후 12.22.9를 설치하시고 다시 시도하셨는데도 같은 증상(SyntaxError: Unexpected token ILLEGAL)이 나타난다는 말씀이신가요?
run.bat 실행 하자마자 튕기는데요

**Comment by lshqqytiger** [comment]
run.bat이 실행 직후 종료되는 현상은 보통 모듈 누락 (구축 시 또는 구축 후 삽질하다가 문제 발생) 때문입니다.
server-flush.bat 실행 => server-setup.bat 실행 후 다시 시도해보시고 그래도 동일한 문제가 발생하면
이미 DB 구축까지는 끝내신 것 같으니 파일 다시 다운로드 후 server-setup.bat 실행 후 다시 시도해보세요.

또한 현재 구축에 사용 중이신 파일은 구버전(5663dd47d53b05c6c16f1e0568eef5b5095e3ca2, 2019년 마지막 커밋)입니다.
다른 이슈들을 보시고 이전 버전의 파일을 사용하시는 것이라면 그 당시에 있었던 중요 버그/오류들은 이미 거의 수정되었으니 [최신 레포지토리](5663dd47d53b05c6c16f1e0568eef5b5095e3ca2) 사용을 권장합니다.

**Comment by kogunggom111** [comment]
> `run.bat`이 실행 직후 종료되는 현상은 보통 모듈 누락/electron 관련 모듈에 문제 발생 (구축 시 또는 구축 후 삽질하다가 문제 발생) 때문입니다. `server-flush.bat` 실행 => `server-setup.bat` 실행 후 다시 시도해보시고 그래도 동일한 문제가 발생하면 현재 실행되는 Node.js 버전이 12.22.9가 맞는지 확인해보시고 (cmd에 `node --version`) 이미 DB 구축까지는 끝내신 것 같으니 파일 다시 다운로드 후 `server-setup.bat` 실행 후 다시 시도해보세요.
> 
> 또한 현재 구축에 사용 중이신 파일은 구버전(`5663dd47d53b05c6c16f1e0568eef5b5095e3ca2`, 2019년 마지막 커밋)입니다. 다른 이슈들을 보시고 이전 버전의 파일을 사용하시는 것이라면 그 당시에 있었던 중요 버그/오류들은 이미 거의 수정되었으니 [최신 레포지토리](https://github.com/JJoriping/KKuTu/archive/refs/heads/master.zip) 사용을 권장합니다.
아직도 튕기는데 어떻게 하나요?

**Comment by kogunggom111** [comment]
아직도 튕기는데 어떻게 하면 되나요?

**Comment by lshqqytiger** [comment]
제가 말씀드린대로 그대로 하셨으면 튕길 이유가 없는데요..
새 파일로 다시 시도도 해보셨나요?

**Comment by kogunggom111** [comment]
그냥 새 레포지토리 받아서 .inc 없애고 server-setup.bat 실행하면 튕기고 server-flush.bat 실행해도 튕기고 run.bat  실행해도 튕기더라구요.......

**Comment by jhj1228** [comment]
새 레포지토리 받고 다시 db를 구축하셨나요?

**Comment by chuhyeonjin** [comment]
[달달소 공식 디스코드](https://discord.gg/daldalso) 들어와 보실래요

**Comment by kogunggom111** [comment]
> 새 레포지토리 받고 다시 db를 구축하셨나요?

네

**Comment by norhu1130** [comment]
현재 Nodejs버전
PostgreSQL버전
하신일 전부의 순서 알려주세요

**Comment by kogunggom111** [comment]
> 새 레포지토리 받고 다시 db를 구축하셨나요?
네 물론이죠

**Comment by kogunggom111** [comment]
> 새 레포지토리 받고 다시 db를 구축하셨나요?

네

**Comment by kogunggom111** [comment]
........
