### ISSUE TITLE
구글 소셜로그인 관련 문의

### ISSUE THREAD

**Issue by alforeplay** [JJoriping/KKuTu#97]
우선 끄투 소스코드 공개에 감사드립니다.

* 문의사항
끄투서버를 oAuth 를 통해 구글 소셜 로그인을 구현은 하였습니다. 그러나 구글 로그인 화면 진행 후 '/register' 디렉토리로 리다이렉트 되면서 "Unauthorized"라는 페이지만 떠서, Issue #83 의 1번에 나온 대로 콜백 URL 을 변경 하려 했으나 해당 내용을 찾지 못하여 in_login.js 의 모든 '/register'를 '/'로 변경하고 flush 하였더니 루트디렉토리로 반환은 되나 로그인이 되지 않습니다.

정확히 어디를 변경해야 하나요....

**Comment by JJoriping** [comment]
안녕하세요. 우선 이슈 #26 에서 언급된 리디렉션 URI를 이용해 보고 그래도 문제가 해결되지 않는다면 문제 분석을 위해 꼭 관련 이미지 등을 첨부해 주시면 감사하겠습니다.

**Comment by alforeplay** [comment]
Google Developer Console 상에서 Redirection URI 셋팅은 완료 하였습니다.

콜백 URI 수정을 위해 수정한 파일의 부분과 현재 증상을 이미지로 첨부하겠습니다.

### 구글 로그인 클릭시 정상적으로 로그인 진행, 루트 디렉토리로 반환됨.
![1](https://cloud.githubusercontent.com/assets/26217177/26455368/f867c2e0-41a4-11e7-9a45-9e2c6a89d036.PNG)

### 그러나 로그인이 진행되지 않음, gwalli 페이지 또한 {400:ERROR}로 접근 불가.
![2](https://cloud.githubusercontent.com/assets/26217177/26455374/fcb858aa-41a4-11e7-9089-9404f8aa64e1.PNG)

### 콜백 URI 구현을 위해 수정한 in_login.js의 변수
![3](https://cloud.githubusercontent.com/assets/26217177/26455445/30764274-41a5-11e7-931a-e8e0624f6e1d.PNG)

**Comment by JJoriping** [comment]
안녕하세요. 기존 끄투 구현에서는 리다이렉션 URI를 `/register`로 설정한 것으로 취급하고 이 쪽으로 로그인 관련 처리가 진행됩니다. ([https://github.com/JJoriping/KKuTu/blob/master/Server/lib/Web/main.js#L262|해당 부분 소스 코드 참고]) 부득이한 이유로 리다이렉션 URI를 변경한 뒤에는 해당 주소에서 로그인 관련 처리를 끝내 주세요. 401 Unauthorized 문제는 추측컨데 [https://github.com/JJoriping/KKuTu/blob/master/Server/lib/sub/jauth.js#L130|이 쪽]에서 반환하는 것으로 보입니다. 해당 파일의 상수 `GOOGLE_ID`, `GOOGLE_API`, `GOOGLE_SECRET`을 올바르게 설정했는지 확인해 보세요.

**Comment by alforeplay** [comment]
## 문제를 해결하였습니다
해결 방안 : 
jauth.js의 GOOGLE_ID는 Credentials에서 확인 할수 있는 Client ID이고
GOOGLE_API는 API Manager의 상단에서 확인 할 수 있는 API자체의 ID이며,
GOOGLE_SECRET은 Client Secret입니다.

여기서 문제가 발생했던 이유는 **GOOGLE_ID의 값과 GOOGLE_API의 값의 순서를 바꿔서 입력** 했더군요.

순서를 원상태로 바꿔 입력한 후, server-flush를 진행해주고 다시 setup을 진행하니 로그인이 정상적으로 진행됩니다.
