### ISSUE TITLE
왜 튕기지......?

### ISSUE THREAD

**Issue by kogunggom111** [JJoriping/KKuTu#972]
이거 왜 튕기나요?
서버 redis 실행했고
nodejs 문제없음
postgreSQL 문제없음
왜 이렇나요?

**Comment by norhu1130** [comment]
학생 이슈닫아

**Comment by kogunggom111** [comment]
> 학생 이슈닫아

1개 닫았어요

**Comment by kogunggom111** [comment]
아 그런데 run.bat 명령어는 npm start 라서 파일 위치 들어가보니 npm.cmd 있어서 실행했더니 이런 오류가 나더라구요


npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Program Files\nodejs\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Program Files\nodejs\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ksh-0\AppData\Roaming\npm-cache\_logs\2022-02-05T11_22_28_737Z-debug.log

이래서 튕겼나......?

**Comment by chuhyeonjin** [comment]
그 https://discord.gg/xWrkH3RE 들어와보실레요

**Comment by lshqqytiger** [comment]
npm.cmd는 npm이 설치된 경로에서 실행되므로 현재 문제 상황과는 무관한 파일입니다.

**Comment by kogunggom111** [comment]
> npm.cmd는 npm이 설치된 경로(Node.js가 설치된 경로)에서 실행되므로 그런 오류 메시지가 출력되는 것이 정상이고 현재 문제 상황과는 무관한 파일입니다.

그럼 어케하나요?

**Comment by lshqqytiger** [comment]
이미 가능한 해결 방법을 다 알려드렸지만 여전히 해결이 되지 않으니 의심이 가는 부분들부터 무엇이 문제인지 확인을 해봐야 하는데 깃허브 이슈에서는 원할한 소통이 어려워 작업이 힘듭니다.

**Comment by norhu1130** [comment]
1. Nodejs 0.12.0삭제 * 꼭 확인하세요.
2. Nodejs 재설치
3. server-setup.bat실행
4. 서버실행

**Comment by kogunggom111** [comment]
> 1. Nodejs 0.12.0삭제 * 꼭 확인하세요.
> 2. Nodejs 재설치
> 3. server-setup.bat실행
> 4. 서버실행

됐다~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by kogunggom111** [comment]
> > 1. Nodejs 0.12.0삭제 * 꼭 확인하세요.
> > 2. Nodejs 재설치
> > 3. server-setup.bat실행
> > 4. 서버실행
> 
> 됐다~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

핰핰핰핰하 드디어 됐다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by chuhyeonjin** [comment]
돼셔서 기쁘시면 이제 본인이 여신 이슈들 다 닫으시면 되겠네요

**Comment by norhu1130** [comment]
WA 해결!

**Comment by kogunggom111** [comment]
> 돼셔서 기쁘시면 이제 본인이 여신 이슈들 다 닫으시면 되겠네요

.......

**Comment by kogunggom111** [comment]
여튼 다 됐네
