### ISSUE TITLE
봇 활성화 방법

### ISSUE THREAD

**Issue by kogunggom111** [JJoriping/KKuTu#974]
제가 끄투 서버 만들고 봇으로 플레이하니까 한글은 사기 봇만 되고 영어만 되더라구요.
#3, #338 등의 이슈를 보았는데 참고해도 고쳐지지 않았습니다.
이 경우는 어떻게 해결하면 될까요?

**Comment by lshqqytiger** [comment]
#841 
단어 데이터베이스에 hit 수가 많이 누적되지 않은 상태라서 그런 것 같은데, 임의로 hit 값을 조정해보세요.

**Comment by kogunggom111** [comment]
> #841 단어 데이터베이스에 hit 수가 많이 누적되지 않은 상태라서 그런 것 같은데, 임의로 hit 값을 조정해보세요.

어떻게 조정하면 되나요?

**Comment by whskr** [comment]
![image](https://user-images.githubusercontent.com/57280515/153713370-f26b2e4d-660e-439c-bb79-32e8bcf581d3.png)
저는 그냥 이렇게 했습니다

**Comment by CHEEY-BORIN** [comment]
#689

**Comment by CHEEY-BORIN** [comment]
689 일부 : 1. 이곳은 끄투 서버 자체의 문제점만을 기술하시기 바랍니다.

**Comment by kogunggom111** [comment]
아 해결됐네요 감사합니다
