### ISSUE TITLE
head 부분 질문드립니다.

### ISSUE THREAD

**Issue by kimlulz** [JJoriping/KKuTu#976]
![image](https://user-images.githubusercontent.com/42508318/155089605-d2a86045-d12b-44ce-a417-b342430d9b51.png)

도커를 통해 서버를 구축하였습니다.
저 `undefined` 부분을 수정 할 수 있을까요?

**Comment by lshqqytiger** [comment]
내장된 끄투 서버 매니저(electron)를 사용하지 않는 경우 `KKT_SV_NAME` 환경 변수가 지정되지 않아 발생합니다.
[webinit.js#44](https://github.com/JJoriping/KKuTu/blob/fadc0f1699e31252a216463be5bd7bda01cf1c06/Server/lib/sub/webinit.js#L44) 부분을 적당히 수정하시면 됩니다.

**Comment by kimlulz** [comment]
DockerFile 내에 환경변수를 추가하여 해결하였습니다.
**`ENV KKT_SV_NAME <서버이름>`**

감사합니다.
