### ISSUE TITLE
2가지 질문 드립니다.

### ISSUE THREAD

**Issue by ingari** [JJoriping/KKuTu#98]
1. 서버 이름 변경
[undefined] 글자로 놀자! 끄투 온라인에서 undefined를 바꾸고 싶은데 어느 파일을 수정해야 하나요?

2. 서버 최대 수용 인원 변경
현재 기본으로 400명으로 서버 최대 수용 인원이 설정되어 있습니다. 어디를 수정해야 서버 최대 수용 인원을 변경할 수 있을까요?

**Comment by alforeplay** [comment]
### Issue 하나당 질문은 하나씩 해주세요!


1. server-setup.bat과 같은 폴더 (kkutu상에서 최상단 폴더) __settings.json__ 파일의 _server-name_  값을 수정해 주세요.

2. Issue #83를 참고해 주세요!

**Comment by ingari** [comment]
setting.json의 server-name 값을 수정했으나 서버를 다시 켜도 적용되지 않습니다.

**Comment by alforeplay** [comment]
server-flush를 진행 후 다시 server-setup 진행해 보시겠습니까?

**Comment by ingari** [comment]
윈도우 기준으로 말씀드리는 거 같은데 리눅스 환경에서는 어떻게 해야 하는지 혹시 알고 계시나요?

**Comment by alforeplay** [comment]
### Issue #63 에서 확인 할 수 있네요.
서버관리자 미 사용시 서버 이름은 LINUX에서 환경변수 KKT_SV_NAME에 저장된다고 합니다.
따라서 리눅스에서 실행파일(./file-name 식으로 실행하는 파일, 실행할것이니 chmod +x file-name 필수!) 만드시고 
`export KKT_SV_NAME="undefined를 바꿀 이름."
 <이하에는 기존 실행코드>`

로 하시면 될것 같습니다.

#### (이렇게 이슈트래킹을 빠르게 할 수 있도록 여러분들께서 이슈 하나당 질문 하나씩 올려주시면 감사하겠습니다....)

**Comment by ingari** [comment]
콘솔에 `export KKT_SV_NAME="undefined를 바꿀 이름."`을 쳐봐도, 실행파일에 `export KKT_SV_NAME="undefined를 바꿀 이름."`을 입력해서 실행해서 서버를 다시 켰는데도 그대로이네요..
제가 이해력이 별로인건지..

**Comment by alforeplay** [comment]
제가 리눅스에서 한번 열고 다시 알려드리겠습니다.

**Comment by ingari** [comment]
감사합니다 :)

**Comment by ingari** [comment]
보니까 KKT_SV_NAME 이 등록되기는 하는데 적용이 되지 않는 거 같습니다.
등록되기만 하니까 서버 컴퓨터를 다시 키면 KKT_SV_NAME 이 없어집니다.

**Comment by alforeplay** [comment]
그래서 실행파일을 제작하는 것을 요청드린겁니다.

일일이 `export KKT_SV_NAME="undefined를 바꿀 이름."` 입력후 쉘을 실행하는 것은 불가능이라고 생각 하기에.....

**Comment by ingari** [comment]
.sh 실행 파일에다가 `export KKT_SV_NAME="undefined를 바꿀 이름."`을 넣어 실행해도 [undefined] 글자로 놀자! 끄투 온라인 이라고 뜹니다.

**Comment by JJoriping** [comment]
서버의 이름을 정할 때는 파일 `./settings.json`의 `server-name` 필드를 우선 탐색하며 해당 필드가 없는 경우
 환경 변수 `KKT_SV_NAME`을 참조합니다. 환경 변수는 node.js 내에서 `process.env['KKT_SV_NAME']` 등으로 설정할 수도 있으니 참고하세요.

**Comment by ingari** [comment]
![image](https://user-images.githubusercontent.com/27482277/27762780-46b211fa-5eb3-11e7-885e-e82441fb9025.png)
환경 변수는 나중에 시도해 보겠습니다만, 이 파일에는 문제가 없는거죠?

**Comment by JJoriping** [comment]
네 맞습니다. 참고로 파일 `./settings.json`에 작성한 내용은 서버 관리자를 위한 설정 파일이며 이를 거치지 않고 직접 웹 서버 및 게임 서버를 열려는 경우에는 환경 변수 `KKT_SV_NAME`을 설정해 주어야 합니다.
