### ISSUE TITLE
서버 구축중의 문제

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#980]
![화면 캡처 2022-03-20 211629](https://user-images.githubusercontent.com/81745150/159659160-11ff4017-e233-435f-813a-3495b6b5d002.png)
끄투 매니저에서 서버 열라고 하면 이렇게 뜨는데 이거 왜 이카죠? 그리고 sql을 지웠다 깔았는데 postgreSQL 에서 계속 아래처럼
![화면 캡처 2022-03-21 172121](https://user-images.githubusercontent.com/81745150/159659302-199e074c-81fc-4a3d-829e-008f74fe859e.png)
이런오류가 뜨는데 어케 고치죠?

**Comment by june2007** [comment]
sql 때문에 저렇게 뜨는것 같긴 하지만 sql오류는 왜 저런지 모르겠습니다.

**Comment by asdf3434asdf** [comment]
폴더권한이 없어서 설치가 이상하게 된거같습니다.
postgresql을/를 지우고 cmd에
net user postgres /delete 이렇게 입력하여 postgres 계정을 삭제합니다.
net user /add postgres <패스워드를 기억할수 있게 적어주세요> 이렇게 postgres 계정을 생성합니다.
net localgroup administrators postgres /add 이렇게 postgres계정에 관리자권한을 부여합니다.
net localgroup "power users" postgres /add 이렇게 postgres에 파워유저를 추가
runas /user:postgres cmd.exe postgres계정으로 cmd.exe 실행
postgres계정으로 실행된 cmd로 postgresql를 다시 설치해주세요
postgres 사용자 계정과 사용자 디렉토리를 삭제합니다
net localgroup administrators postgres /delete

하지만 이것도 안된다면 postgresql 데이터 파일 postgres-data 파일을 생성하고
postgres-data파일에 엑세스 권한을 부여해주세요
postgresql 설치과정에서 postgresql 설치경로를 postgres-data로 바꾸시고 설치를 진행하세요

**Comment by Rook992** [comment]
> ![화면 캡처 2022-03-20 211629](https://user-images.githubusercontent.com/81745150/159659160-11ff4017-e233-435f-813a-3495b6b5d002.png) 끄투 매니저에서 서버 열라고 하면 이렇게 뜨는데 이거 왜 이카죠? 그리고 sql을 지웠다 깔았는데 postgreSQL 에서 계속 아래처럼 ![화면 캡처 2022-03-21 172121](https://user-images.githubusercontent.com/81745150/159659302-199e074c-81fc-4a3d-829e-008f74fe859e.png) 이런오류가 뜨는데 어케 고치죠?

SQL 서버에 연결하지 못한다고 합니다.
Server/lib/sub 경로에서 global.json 파일을 확인해보세요.
"PG_PASSWORD": "", <- 여기 "" 부분 안에 자신이 설정해둔 SQL 비밀번호를 입력하세요.
혹여 틀렸다면 다시 수정해주시고. 맞는데 안된다면 SQL 설치 여부를 확인해주세요.

Failed To load SQL moduels into the database cluster. 문제는

asdf3434asdf님의 답변 잘 적용하세요.

**Comment by june2007** [comment]
> 폴더권한이 없어서 설치가 이상하게 된거같습니다. postgresql을/를 지우고 cmd에 net user postgres /delete 이렇게 입력하여 postgres 계정을 삭제합니다. net user /add postgres <패스워드를 기억할수 있게 적어주세요> 이렇게 postgres 계정을 생성합니다. net localgroup administrators postgres /add 이렇게 postgres계정에 관리자권한을 부여합니다. net localgroup "power users" postgres /add 이렇게 postgres에 파워유저를 추가 runas /user:postgres cmd.exe postgres계정으로 cmd.exe 실행 postgres계정으로 실행된 cmd로 postgresql를 다시 설치해주세요 postgres 사용자 계정과 사용자 디렉토리를 삭제합니다 net localgroup administrators postgres /delete
> 
> 하지만 이것도 안된다면 postgresql 데이터 파일 postgres-data 파일을 생성하고 postgres-data파일에 엑세스 권한을 부여해주세요 postgresql 설치과정에서 postgresql 설치경로를 postgres-data로 바꾸시고 설치를 진행하세요

거의 적용? 했는데 postgres 계정에서 설치를 어떻게 하죠?

**Comment by asdf3434asdf** [comment]
postgresql 설치파일이 있는경로를 그대로 입력해보세요

**Comment by june2007** [comment]
>postgresql 설치파일이 있는경로를 그대로 입력해보세요

 액세스가 거부 됬다고 떠요

**Comment by asdf3434asdf** [comment]
cmd가 관리자권한으로 실행되어있나요
