### ISSUE TITLE
서버 접속시 Upgrade Required 뜨는 문제

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#981]
끄투 서버를 열면 오류 없이 잘 열리고 콘솔에 연결됬다는 메시지 뜨는데
크롬에서 끄투 서버 주소로 접속하면 Upgrade Required라고만 떠요

![image](https://user-images.githubusercontent.com/93064596/160228215-5ed13027-cbe6-4552-9894-31105b0ccc0a.png)

**Comment by IAMIHAH** [comment]
8080으로 들어가시면 안됩니다.
기본 포트는 80이므로
끄투 서버가 내부인 경우 `127.0.0.1`
끄투 서버가 외부인 경우 `끄투 서버가 구동중인 서버의 IP`로
입장하셔야 합니다. 포트는 다시면 안되고요.

**Comment by lshqqytiger** [comment]
8080은 게임 서버 포트입니다.
80 포트 (생략 가능) 로 접속하셔야 합니다.
e.g. `http://{ip}/`, `http://localhost/`, `http://{domain}/`, `http://{ip}:80/`, `http://localhost:80/`, `http://{domain}:80/`
