### ISSUE TITLE
이거 어케고쳐여

### ISSUE THREAD

**Issue by dalnala** [JJoriping/KKuTu#982]
끄투 실행 했는데

Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080\

라고 뜨는데 이거 어떻게 고치나요?

**Comment by lshqqytiger** [comment]
사용 중인 Node.js 버전이 README.md에 기재된 요구 사항을 만족하는지 확인해주세요.
#958 #965

**Comment by dalnala** [comment]
와ㅏ 실행 됬다 감사합니다

**Comment by dalnala** [comment]
끄투 드뎌 만들어졌다!

**Comment by kmsimproject** [comment]
해결되었다면 이슈를 닫아주시기 바랍니다.
