### ISSUE TITLE
끄투 외부접속

### ISSUE THREAD

**Issue by june2007** [JJoriping/KKuTu#983]
DMZ 로 바꾸고 내도메인.한국 으로 도메인 했고 방화벽도 열었는데 외부접속이 안되네요
여기 규칙(?)에서 좀 벗어날수 있지만 외부접속 하게 하는거 어떻게 해요?
참고로 서버는  localhost(내부아이피 로도 가능)로 들어갈수 있는 상태입니다.

**Comment by Rook992** [comment]
#689 
1번을 자세히 보시기 바랍니다. 여기는 끄투의 문제점'만' 다루는 곳입니다.
규칙에서 벗어날 수 있다는 것을 인지하고 있다면 왜 이슈를 열었을까요?
이슈 닫아주세요.

**Comment by lshqqytiger** [comment]
1. 서버가 정상적으로 열려 있음.
2. 인터넷과 연결되어 있음.
3. `80`, `8080`, `8496` 포트가 열려 있음. (포트포워딩, DMZ 등)
4. 고급 보안이 포함된 Windows Defender 방화벽에서 `80`, `8080`, `8496` 포트에 대한 접근을 허가하는 인바운드 규칙을 생성함.
5. 도메인 DNS 설정이 제대로 되어 있음. (A 레코드로 외부 IP에 접근)

위 조건이 만족되지 않았을 것 같습니다.

1. IP로 외부 접속 시도.
접속이 안되는 경우: 도메인 DNS 설정에 선행해야 하는 조건 중 하나 이상이 만족되지 않음.
접속이 되는 경우: 도메인 DNS 설정 확인.
2. [포트 상태 확인 도구](https://www.yougetsignal.com/tools/open-ports/) 이용.
`Remote Address` 칸에 외부 IP를 입력 했을 때와 도메인을 입력 했을 때 `80`, `8080`, `8496` 포트가 전부 열려 있다고 나오는지 확인.
