### ISSUE TITLE
도움말 어인정 메뉴의 '사용 가능한 단어 그룹' 오류 (?)

### ISSUE THREAD

**Issue by Carlo-Woo** [JJoriping/KKuTu#984]
오픈소스에서 내려받은 코드도 그렇고 거의 대부분 서버도 같은 거 같아서 질문합니다.
제목과 같이 도움말의 어인정 메뉴를 보면 아래와 같이 ko_KR.json에서 정의한 대로 뜨지 않고 `theme_OOO` 같은 형식으로 표시되네요.
이 현상이 정상인가요?
![캡처](https://user-images.githubusercontent.com/58204246/160271351-1f29a366-6a2c-4ddc-9e4d-b94398b40d47.PNG)

(문제가 있으면 이슈 삭제하겠습니다.)

**Comment by lshqqytiger** [comment]
#985

**Comment by Carlo-Woo** [comment]
따로 PR 올라왔으므로 이슈는 닫겠습니다.
