### ISSUE TITLE
끄투 서버 만들고 있는데요

### ISSUE THREAD

**Issue by KjaeH** [JJoriping/KKuTu#987]
Cannot find module 'pg' Require stack라고 뜨면서 서버가 안 만들어져요 ㅠㅠㅠ
해결법 있나요? ㅠㅠ

**Comment by lshqqytiger** [comment]
서버 구축이 제대로 되지 않은 것입니다.
`server-flush.bat` 실행 후 `server-setup.bat` 실행해보세요.

**Comment by KjaeH** [comment]
된거같긴한데 [2022-04-09 16:37:08] Game server #1 has an error: Error: connect ECONNREFUSED 127.0.0.2:8080
[2022-04-09 16:37:08] Game server #1 closed: 1006 이렇게 뜨네요 ㅠㅠ 이거 해결책은 없나요?

**Comment by lshqqytiger** [comment]
#982
