### ISSUE TITLE
끄투 메인화면 어떻게 커스텀하나요???

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#992]
/home/ubuntu/KKuTu/Server/lib/Web/public/ 에 들어가봐도
변경 내용 그런거 입력하는 html 파일만 있어서 그런데
끄투 들어갔을때 게임시작 버튼 있는 그 메인화면을 커스텀하려고 하는데
그 메인화면 html 파일이 어디있나요???
그리고 가능하면 로딩화면,방선택 같은 화면의 html 파일 위치도 알려주세요 ㅠㅠ

**Comment by lshqqytiger** [comment]
끄투2는 html을 사용하지 않습니다.
#884

**Comment by 1325ok** [comment]
감사합니다

**Comment by 1325ok** [comment]
> 끄투2는 최상위 프론트엔드 구성에 html을 사용하지 않습니다. #884

갑자기 한참전에 닫은 이슈에서 질문해서 죄송합니다
1가지 궁금한게 있는데요
당시에 이 이슈를 올린이유가 

![image](https://user-images.githubusercontent.com/93064596/167344501-8b49a3f7-d915-409b-b99d-c3dc07facd76.png)

다른 PR 살펴보다 이런 내용이 있어서 html로도 되나 싶어서 남겼던거라
위 의미는 그럼 무엇인지 해석이 가능할가요?
잘 이해가 안되서요

**Comment by lshqqytiger** [comment]
Express를 통해 html을 직접 제공하거나(정적 파일 접근 또는 res.send) html 기반의 템플릿 엔진을 사용하는 경우를 의미한 것 같으나 끄투에서 일반적으로 사용하는 방식이 아닙니다.

**Comment by 1325ok** [comment]
> Express를 통해 html을 직접 제공하거나(정적 파일 접근 또는 res.send) html 기반의 템플릿 엔진을 사용하는 경우를 의미한 것 같으나 끄투에서 일반적으로 사용하는 방식이 아닙니다.

감사합니다
아니면 혹시 html 템플릿으로 만든 파일을 pug로 변환하고
원래 메인화면 pug 파일의 서버 목록 표시하는 부분을 가져와서
html 템플릿을 pug로 변환한 파일에 넣어도 작동하나요?

일단 html 템플릿을 pug로 변환해서 끄투 서버 메인화면 pug 파일에
덮어쓰기 했더니 거기 까지는 정상작동은 합니다

**Comment by lshqqytiger** [comment]
in_portal.min.js jquery.js를 로드하는 script 태그와 in_portal.css를 로드하는 link 태그까지 옮겨야 의도한대로 동작할겁니다.
html 탬플릿과 기존 코드를 섞는 것은 css 간섭 같은 문제 때문에 별로 권하고 싶지는 않습니다.

**Comment by 1325ok** [comment]
> in_portal.min.js jquery.js를 로드하는 script 태그와 in_portal.css를 로드하는 link 태그까지 옮겨야 의도한대로 동작할겁니다. html 탬플릿과 기존 코드를 섞는 것은 css 간섭 같은 문제 때문에 별로 권하고 싶지는 않습니다.

PUG에 원본PUG의 코드 불러오고 조금 손보고 레이아웃 파일 복붙해서 이름 바꿔서 새로운 메인화면 pug에 널고
레이아웃 파일 내용 바꿔서 상단바 제거하고 코드 손보고 서버 목록 표시 부분만 안지우고 좀 손봐서 성공했네요
css가 서버 목록 표시에 위에 서버 목록 제목과 새로 고침 버튼이 크기가 크게 나오긴 하지만 성공했네요
답 달아주셔서 감사합니다
