### ISSUE TITLE
관리자로 로그인이 안됩니다

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#994]
http://129.154.210.213/gwalli 로 들어가도 {"error":400} 떠서 다른 이슈 찾아봐서 해결은 됬는데
global.json에서 	"ADMIN": [ "" ], 안에 사용자 식별값을 넣어야 하는것 같은데 
디스코드를 통해 로그인했더니
닉네임에 # 옆에 숫자가 안붙고
1325OK GAMES #disco 라고 써져 있어서
사용자 식별코드가 이게 아닌거 같은데 사용자 식별코드를 어떻게 얻을수 있나요???

**Comment by 1325ok** [comment]
아...리눅스 콘솔에서 찾았네요 ㅠㅠ
죄송합니다 ㅠㅠ

**Comment by IAMIHAH** [comment]
IP를 노출하시면 DDoS 및 DoS 공격에 취약할 수 있습니다.
또한 테스트 중이신 것 같은데 서버에 다른 누군가가 접속할 수도 있고요.

사용자 식별번호는 인게임 명령어 `/id` 를 통해 얻을 수 있습니다.
다른 사람의 식별번호는 `/id [닉네임]` 으로 얻으실 수 있습니다.
