### ISSUE TITLE
GPL 저작권 관련하여 1가지만 물어보겠습니다

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#996]
끄투 자체의 문제를 올리는 이슈에 올려서 죄송하지만
저작권 위반하기는 당연히 싥어서 그리고 끄투 서버 개발하는 사람들 모인 네아버카페,디스코드,오픈채팅이 있는것도 아니기 때문에
 어쩔수 없이 물어봅니다...GPL 표시할때 

이에 대한 자세한 사항은 본 프로그램의 구현을 담은 다음 레포지토리에서 확인하십시오: <a target='_blank' href='{이 서버의 소스 코드 위치}'>{이 서버의 소스 코드 위치} 

여기에서 서버 소스코드를 꼭 적어야하나요???
소스코드를 매번 깃허브에 올리기도 힘들고
이 끄투 온라인 소스코드 주소를 올리는건 또 아닌것 같기도해서요 ...

(끄투 서버 개발하는 사람들 모인 네아버카페,디스코드,오픈채팅 그 3개중 하나로도 있으면 편할것같다...)

**Comment by lshqqytiger** [comment]
끄투 서버 목록에 서버를 공개하기 위해서는 필수적이나 비공개, 비상업적 목적으로 이용 시 누락하여도 아무도 뭐라하지 않습니다.

**Comment by 1325ok** [comment]
> [끄투 서버 목록](https://kkutu.kr)에 서버를 공개하기 위해서는 필수적이나 비공개, 비상업적 목적으로 이용 시 누락하여도 아무도 뭐라하지 않습니다.

광고를 넣기는 할건데 끄투 서버 목록에는 되도록이면 넣고 싶지만
소스코드를 매번 올리기 힘들어서 서버 목록에는 안넣을건데
대신 사람들이 플레이 할수있게 검색엔진에도 올릴건데 광고도 넣고
그러려면 GPL을 표시해야하나요?

**Comment by lshqqytiger** [comment]
애초에 소스코드를 제공하지 않는 것은 GPL 라이선스를 위반하는 행위입니다. (파생물 배포 의무)
서버 공개 여부와는 상관 없이 소스코드는 제공하는 것이 원칙이나 서버를 외부에 공개하지 않는 경우 파생물 배포 의무가 지켜지고 있는지 확인할 방법이 없기 때문에 상관 없다고 말씀드린 것입니다.

**Comment by 1325ok** [comment]
> 애초에 소스코드를 제공하지 않는 것은 GPL 라이선스를 위반하는 행위입니다. (파생물 배포 의무) 서버 공개 여부와는 상관 없이 소스코드는 제공하는 것이 원칙이나 서버를 외부에 공개하지 않는 경우 파생물 배포 의무가 지켜지고 있는지 확인할 방법이 없기 때문에 상관 없다고 말씀드린 것입니다.

그럼 한번 컴퓨터 폴더 파일을 실시간으로 동기화해서 Git으로 올리는 프로그램 찾아봐야겠군요

**Comment by 1325ok** [comment]
> 애초에 소스코드를 제공하지 않는 것은 GPL 라이선스를 위반하는 행위입니다. (파생물 배포 의무) 서버 공개 여부와는 상관 없이 소스코드는 제공하는 것이 원칙이나 서버를 외부에 공개하지 않는 경우 파생물 배포 의무가 지켜지고 있는지 확인할 방법이 없기 때문에 상관 없다고 말씀드린 것입니다.

혹시 그럼 게임물관리위원회 전체이용가 판정 같은거 받는건 무료인가요?

**Comment by whskr** [comment]
> ... 그리고 끄투 서버 개발하는 사람들 모인 네아버카페,디스코드,오픈채팅이 있는것도 아니기 때문에 어쩔수 없이 물어봅니다...

> ... (끄투 서버 개발하는 사람들 모인 네아버카페,디스코드,오픈채팅 그 3개중 하나로도 있으면 편할것같다...) ...

끄투 프리 서버 목록 우측 하단에 달달소 디스코드 위젯 단추가 있습니다. 달달소 > 🎮 함께놀아요 > #⚓끄투

**Comment by lshqqytiger** [comment]
게임물관리위원회는 심의 수수료를 받습니다.

**Comment by 1325ok** [comment]
> 게임물관리위원회는 심의 수수료를 받습니다.

네 ㅠㅠ
그럼 필수로 해야하나요?
프리서버 목록보니 게임물관리위원회 검증 받은 서버도 있고 안된곳도있어서요

**Comment by lshqqytiger** [comment]
광고 게재를 위해서는 필수입니다.

**Comment by 1325ok** [comment]
> 광고 게재를 위해서는 필수입니다.

네

**Comment by 1325ok** [comment]
> 게임물관리위원회는 심의 수수료를 받습니다. (10MB 미만: 2.1만 네트워크: ×1.5 => 3.15만)

장르별 계수는 3군인가요?

**Comment by 1325ok** [comment]
![image](https://user-images.githubusercontent.com/93064596/168733835-c218b693-b032-4df7-b08f-0e10ca24bfee.png)
일단 용량은 10MB~100MB에 들어가서 28000에 네트워크 게임이라
28000 x 1.5 해서 42000 원 나왔고 장르가 3군인가요? 한글화 계수는 한글인가요?
![image](https://user-images.githubusercontent.com/93064596/168734067-c7c40187-b71a-465b-954d-1c82f17d2a82.png)

**Comment by lshqqytiger** [comment]
웹 게임 심의 시 용량은 이용자가 서버로부터 가져오는 리소스 기준입니다.
장르는 3군이고 한글화계수는 한글(1.0)입니다.
그리고 깃허브 이슈에서 다룰 만한 내용은 아닌 것 같습니다.
(끄투 자체의 문제점 아님, 끄투 외적인 내용임)

**Comment by kmsimproject** [comment]
그리고 참고로 또 말하자면 통신 판매업 신고도 해야하는걸로 알고 있습니다.

**Comment by 1325ok** [comment]
> 애초에 소스코드를 제공하지 않는 것은 GPL 라이선스를 위반하는 행위입니다. (파생물 배포 의무) 서버 공개 여부와는 상관 없이 소스코드는 제공하는 것이 원칙이나 서버를 외부에 공개하지 않는 경우 파생물 배포 의무가 지켜지고 있는지 확인할 방법이 없기 때문에 상관 없다고 말씀드린 것입니다.

아직 플레이하는 사용자가 많지않고 시간이 없어서 아직 소스를 못올려서
지금 올리고 광고는 포기했고 끄투 프리서버 목록에 올리려고
[5년전에 소스코드 동기화를 중단한 끄투 코리아 ](https://github.com/KKuTu-Korea/KKuTu)처럼 서버 폴더 내부를 올려야 하는지
[분홍끄투의 소스코드 처럼 모두를 올려야하는지 궁금합니다](https://github.com/pinkleaves/KKuTu)

**Comment by 1325ok** [comment]
> 웹 게임 심의 시 용량은 이용자가 서버로부터 가져오는 리소스 기준입니다. 장르는 3군이고 한글화계수는 한글(1.0)입니다. 그리고 깃허브 이슈에서 다룰 만한 내용은 아닌 것 같습니다. (끄투 자체의 문제점 아님, 끄투 외적인 내용, 이 이슈의 원래 주제를 이탈)

그리고 플레이스토어에 웹뷰로 앱으로 올리고 앱에 광고 넣는거는
구글에서 제공하는 자체등급분류로 등급분류받으면 게임 심의 안받고 앱에서만 이라도 광고 넣는게 가능 한가요?

**Comment by lshqqytiger** [comment]
1. GPL 라이선스가 적용된 모든 파일을 공개하셔야 합니다.
2. 게임물관리위원회 또는 Google에 문의하셔야 할 부분이라고 생각합니다.

**Comment by 1325ok** [comment]
> 

그럼 맨 상위 폴더 KKuTu 폴더 전체를 공개하겠습니다
