### ISSUE TITLE
게임 끝난후 핑이 안생기고 랭킹이 안뜨고 제목창에 [undefined] 뜨는 오류

### ISSUE THREAD

**Issue by 1325ok** [JJoriping/KKuTu#997]
![화면 캡처 2022-04-22 154425](https://user-images.githubusercontent.com/93064596/164619265-1b27be42-cbbe-4a0e-8707-57329786700f.png)
![화면 캡처 2022-04-22 154733](https://user-images.githubusercontent.com/93064596/164619268-d0e8d9a3-264f-4559-9004-cb50bf3adc1b.png)
![화면 캡처 2022-04-22 154755](https://user-images.githubusercontent.com/93064596/164619272-4b7b7238-1f5f-48e7-9ecf-ca71ebe75301.png)

게임이 끝나고 핑이 생기지 않고
랭킹도 전혀 안뜨고
방선택 화면에서는 랭킹 누르면 아무 반응이 없고

브라우저 제목창에 [undefined]가 있습니다

**Comment by whskr** [comment]
#63 #98

**Comment by 1325ok** [comment]
> #63 #98

이 방법으로 해결이 안되네요...
(참고로 저는 우분투(리눅스) 사용중입니다)

**Comment by IAMIHAH** [comment]
1. 핑 관련은 직접 조절하셔야 합니다.
2. redis 서버와 연결되지 않은 것 같습니다. 실행되고 있나요?
3. **웹서버**를 실행중인 스크린 또는 셸에서 `KKT_SV_NAME`을 설정하셨나요?

**Comment by lshqqytiger** [comment]
봇과 둘이서만 게임 진행 시 보상이 제대로 지급되지 않습니다.
Redis가 설치되었는지, 실행 중인지(redis-server), Redis 서버와 끄투 서버가 연결되었는지(로그) 확인해주세요.
리눅스 계열에서는 #976 을 참고하세요.

**Comment by 1325ok** [comment]
> 봇과 둘이서만 게임 진행 시 보상이 제대로 지급되지 않습니다. Redis가 설치되었는지, 실행 중인지(redis-server), Redis 서버와 끄투 서버가 연결되었는지(로그) 확인해주세요. [설치하지 않았다면 이 문서의 4. Redis 설치하기 참고](https://github.com/lshqqytiger/KKuTuManual/blob/main/%EA%B5%AC%EC%B6%95.md#4-%EC%84%A0%ED%83%9D-redis-%EC%84%A4%EC%B9%98%ED%95%98%EA%B8%B0) 리눅스 계열에서는 #976 을 참고하세요.

오!!! webinit.js에 	44번 줄을 if(R['title']) R['title'] = ` ${R['title']}`; 로 바꾸니까 없어졌네요!!!!!!
Redis도 apt 로 설치하니 작동되고요!!!

**Comment by 1325ok** [comment]
> 1. 핑 관련은 직접 조절하셔야 합니다.
> 2. redis 서버와 연결되지 않은 것 같습니다. 실행되고 있나요?
> 3. **웹서버**를 실행중인 스크린 또는 셸에서 `KKT_SV_NAME` 환경변수를 설정하셨나요?

혹시 핑은 어떻게 조절하나요?
다른 이슈를 참고해도 이해가 안되서 물어봅니다

**Comment by Rook992** [comment]
kkutu.js의 rw.money = 부분을 수정해주세요.(줄 1400 정도에 있을겁니다.)

**Comment by 1325ok** [comment]
> kkutu.js의 rw.money = 부분을 수정해주세요.(줄 1400 정도에 있을겁니다.)

어느정도의 값이 적당한가요?

**Comment by 1325ok** [comment]
> kkutu.js의 rw.money = 부분을 수정해주세요.(줄 1400 정도에 있을겁니다.)

	rw.score += bonus;
	rw.score = rw.score || 0;
	rw.money = rw.money || 0;

이부분인가요

function getRewards(mode, score, bonus, rank, all, ss){
	var rw = { score: 0, money: 0 };
	var sr = score / ss; 
이부분인가요

**Comment by 1325ok** [comment]
> kkutu.js의 rw.money = 부분을 수정해주세요.(줄 1400 정도에 있을겁니다.)

	return r;
}
function getRewards(mode, score, bonus, rank, all, ss){
	var rw = { score: 0, money: 0 };
	var sr = score / ss;
	
	// all은 1~8
	// rank는 0~7
	switch(Const.GAME_TYPE[mode]){
		case "EKT":
			rw.score += score * 1.4;
			break;
		case "ESH":
			rw.score += score * 0.5;
			break;
		case "KKT":
			rw.score += score * 1.42;
			break;
		case "KSH":
			rw.score += score * 0.55;
			break;
		case "CSQ":
			rw.score += score * 0.4;
			break;
		case 'KCW':
			rw.score += score * 1.0;
			break;
		case 'KTY':
			rw.score += score * 0.3;
			break;
		case 'ETY':
			rw.score += score * 0.37;
			break;
		case 'KAP':
			rw.score += score * 0.8;
			break;
		case 'HUN':
			rw.score += score * 0.5;
			break;
		case 'KDA':
			rw.score += score * 0.57;
			break;
		case 'EDA':
			rw.score += score * 0.65;
			break;
		case 'KSS':
			rw.score += score * 0.5;
			break;
		case 'ESS':
			rw.score += score * 0.22;
			break;
		default:
			break;
	}
	rw.score = rw.score
		* (0.77 + 0.05 * (all - rank) * (all - rank)) // 순위
		* 1.25 / (1 + 1.25 * sr * sr) // 점차비(양학했을 수록 ↓)
	;
	rw.money = 1 + rw.score * 0.01;
	if(all < 2){
		rw.score = rw.score * 0.05;
		rw.money = rw.money * 0.05;
	}else{
		rw.together = true;
	}
	rw.score += bonus;
	rw.score = rw.score || 0;
	rw.money = rw.money || 0;

여기중 어디인가요

**Comment by Carlo-Woo** [comment]
`switch(Const.GAME_TYPE[mode]){` 아래 부분일 겁니다. 각각의 case는 플레이하는 모드를 뜻하구요

**Comment by Rook992** [comment]
> > kkutu.js의 rw.money = 부분을 수정해주세요.(줄 1400 정도에 있을겁니다.)
> 
> ```
> return r;
> ```
> 
> } function getRewards(mode, score, bonus, rank, all, ss){ var rw = { score: 0, money: 0 }; var sr = score / ss;
> 
> ```
> // all은 1~8
> // rank는 0~7
> switch(Const.GAME_TYPE[mode]){
> 	case "EKT":
> 		rw.score += score * 1.4;
> 		break;
> 	case "ESH":
> 		rw.score += score * 0.5;
> 		break;
> 	case "KKT":
> 		rw.score += score * 1.42;
> 		break;
> 	case "KSH":
> 		rw.score += score * 0.55;
> 		break;
> 	case "CSQ":
> 		rw.score += score * 0.4;
> 		break;
> 	case 'KCW':
> 		rw.score += score * 1.0;
> 		break;
> 	case 'KTY':
> 		rw.score += score * 0.3;
> 		break;
> 	case 'ETY':
> 		rw.score += score * 0.37;
> 		break;
> 	case 'KAP':
> 		rw.score += score * 0.8;
> 		break;
> 	case 'HUN':
> 		rw.score += score * 0.5;
> 		break;
> 	case 'KDA':
> 		rw.score += score * 0.57;
> 		break;
> 	case 'EDA':
> 		rw.score += score * 0.65;
> 		break;
> 	case 'KSS':
> 		rw.score += score * 0.5;
> 		break;
> 	case 'ESS':
> 		rw.score += score * 0.22;
> 		break;
> 	default:
> 		break;
> }
> rw.score = rw.score
> 	* (0.77 + 0.05 * (all - rank) * (all - rank)) // 순위
> 	* 1.25 / (1 + 1.25 * sr * sr) // 점차비(양학했을 수록 ↓)
> ;
> rw.money = 1 + rw.score * 0.01;
> if(all < 2){
> 	rw.score = rw.score * 0.05;
> 	rw.money = rw.money * 0.05;
> }else{
> 	rw.together = true;
> }
> rw.score += bonus;
> rw.score = rw.score || 0;
> rw.money = rw.money || 0;
> ```
> 
> 여기중 어디인가요

직.접.하.세.요
모르시면 뭐.. 때려치우시고 공부나 하러 가세요
